
class AntRunner {
    public static void main(String[] args) {
        
        // Default constructor
        Ant a1 = new Ant(); 
        a1.species = "Carpenter"; 
		a1.role = "Worker"; 
		a1.color = "Black";
        Ant a2 = new Ant(); 
        a2.species = "Fire"; 
		a2.role = "Soldier"; 
		a2.color = "Red";
        Ant a3 = new Ant(); 
        a3.species = "Bullet"; 
		a3.role = "Forager"; 
		a3.color = "Dark Brown";
        Ant a4 = new Ant(); 
        a4.species = "Leafcutter"; 
		a4.role = "Queen"; 
		a4.color = "Brown";
        Ant a5 = new Ant();
        a5.species = "Weaver"; 
		a5.role = "Builder"; 
		a5.color = "Greenish";
        Ant a6 = new Ant(); 
        a6.species = "Sugar"; 
		a6.role = "Scout"; 
		a6.color = "Orange";
        Ant a7 = new Ant(); 
        a7.species = "Pharaoh"; 
		a7.role = "Worker"; 
		a7.color = "Yellow";
        Ant a8 = new Ant(); 
        a8.species = "Argentine"; 
		a8.role = "Drone"; 
		a8.color = "Light Brown";
        Ant a9 = new Ant(); 
        a9.species = "Thief"; 
		a9.role = "Scavenger"; 
		a9.color = "Pale Yellow";
        Ant a10 = new Ant(); 
        a10.species = "Odorous House"; 
		a10.role = "Worker"; 
		a10.color = "Dark Brown";
        Ant a11 = new Ant(); 
        a11.species = "Pavement"; 
		a11.role = "Soldier"; 
		a11.color = "Blackish";
        Ant a12 = new Ant(); 
        a12.species = "Ghost"; 
		a12.role = "Forager"; 
		a12.color = "Translucent";
        Ant a13 = new Ant(); 
        a13.species = "Crazy"; 
		a13.role = "Scout"; 
		a13.color = "Dark Grey";
        Ant a14 = new Ant(); 
        a14.species = "Rover"; 
		a14.role = "Worker"; 
		a14.color = "Pale Blonde";
        Ant a15 = new Ant(); 
        a15.species = "Acrobat"; 
		a15.role = "Defender"; 
		a15.color = "Light Red";
        Ant a16 = new Ant(); 
        a16.species = "Harvester"; 
		a16.role = "Gatherer"; 
		a16.color = "Orangeand color of ant Red";
        Ant a17 = new Ant(); 
        a17.species = "Velvet"; 
		a17.role = "Solitary"; 
		a17.color = "Redand color of ant Black";
        Ant a18 = new Ant(); 
        a18.species = "Army"; 
		a18.role = "Hunter"; 
		a18.color = "Tan";
        Ant a19 = new Ant(); 
        a19.species = "Driver"; 
		a19.role = "Soldier"; 
		a19.color = "Deep Red";
        Ant a20 = new Ant(); 
        a20.species = "Trapand color of ant jaw"; 
		a20.role = "Predator"; 
		a20.color = "Dark Amber";
        Ant a21 = new Ant(); 
        a21.species = "Honeypot"; 
		a21.role = "Storage"; 
		a21.color = "Amber";
        Ant a22 = new Ant(); 
        a22.species = "Gliding"; 
		a22.role = "Worker"; 
		a22.color = "Black";
        Ant a23 = new Ant(); 
        a23.species = "Vampire"; 
		a23.role = "Queen"; 
		a23.color = "Pale";
        Ant a24 = new Ant(); 
        a24.species = "Jack Jumper"; 
		a24.role = "Hunter"; 
		a24.color = "Black and Yellow";
        Ant a25 = new Ant(); 
        a25.species = "Turtle"; 
		a25.role = "Defender"; 
		a25.color = "Brownishand color of ant Grey";

        System.out.println("Ant species is  : " + a1.species + "and there role" + a1.role + " and color of ant  " + a1.color);
        System.out.println("Ant species is  : " + a2.species + "and there role" + a2.role + " and color of ant  " + a2.color);
        System.out.println("Ant species is  : " + a3.species + "and there role" + a3.role + " and color of ant  " + a3.color);
        System.out.println("Ant species is  : " + a4.species + "and there role" + a4.role + " and color of ant  " + a4.color);
        System.out.println("Ant species is  : " + a5.species + "and there role" + a5.role + " and color of ant  " + a5.color);
        System.out.println("Ant species is  : " + a6.species + "and there role" + a6.role + " and color of ant  " + a6.color);
        System.out.println("Ant species is  : " + a7.species + "and there role" + a7.role + " and color of ant  " + a7.color);
        System.out.println("Ant species is  : " + a8.species + "and there role" + a8.role + " and color of ant  " + a8.color);
        System.out.println("Ant species is  : " + a9.species + "and there role" + a9.role + " and color of ant  " + a9.color);
        System.out.println("Ant species is  : " + a10.species + "and there role" + a10.role + " and color of ant  " + a10.color);
        System.out.println("Ant species is  : " + a11.species + "and there role" + a11.role + " and color of ant  " + a11.color);
        System.out.println("Ant species is  : " + a12.species + "and there role" + a12.role + " and color of ant  " + a12.color);
        System.out.println("Ant species is  : " + a13.species + "and there role" + a13.role + " and color of ant  " + a13.color);
        System.out.println("Ant species is  : " + a14.species + "and there role" + a14.role + " and color of ant  " + a14.color);
        System.out.println("Ant species is  : " + a15.species + "and there role" + a15.role + " and color of ant  " + a15.color);
        System.out.println("Ant species is  : " + a16.species + "and there role" + a16.role + " and color of ant  " + a16.color);
        System.out.println("Ant species is  : " + a17.species + "and there role" + a17.role + " and color of ant  " + a17.color);
        System.out.println("Ant species is  : " + a18.species + "and there role" + a18.role + " and color of ant  " + a18.color);
        System.out.println("Ant species is  : " + a19.species + "and there role" + a19.role + " and color of ant  " + a19.color);
        System.out.println("Ant species is  : " + a20.species + "and there role" + a20.role + " and color of ant  " + a20.color);
        System.out.println("Ant species is  : " + a21.species + "and there role" + a21.role + " and color of ant  " + a21.color);
        System.out.println("Ant species is  : " + a22.species + "and there role" + a22.role + " and color of ant  " + a22.color);
        System.out.println("Ant species is  : " + a23.species + "and there role" + a23.role + " and color of ant  " + a23.color);
        System.out.println("Ant species is  : " + a24.species + "and there role" + a24.role + " and color of ant  " + a24.color);
        System.out.println("Ant species is  : " + a25.species + "and there role" + a25.role + " and color of ant  " + a25.color);

        // Parameterized constructor
        Ant p1 = new Ant("Wood", "Worker", "Reddishand color of ant Brown");
        Ant p2 = new Ant("Citronella", "Swarm", "Yellow");
        Ant p3 = new Ant("Field", "Forager", "Black and Red");
        Ant p4 = new Ant("Bigand color of ant headed", "Soldier", "Brown");
        Ant p5 = new Ant("Cornfield", "Worker", "Light Brown");
        Ant p6 = new Ant("False Honey", "Scout", "Dark Brown");
        Ant p7 = new Ant("Little Black", "Worker", "Jet Black");
        Ant p8 = new Ant("Whiteand color of ant footed", "Forager", "Black with White");
        Ant p9 = new Ant("Siafu", "Soldier", "Redand color of ant Brown");
        Ant p10 = new Ant("Marauder", "Queen", "Dark Red");
        Ant p11 = new Ant("Red Wood", "Defender", "Red and Black");
        Ant p12 = new Ant("Silky", "Worker", "Silky Black");
        Ant p13 = new Ant("Smoky Brown", "Scavenger", "Smoky");
        Ant p14 = new Ant("Tramp", "Worker", "Brown");
        Ant p15 = new Ant("Dorylus", "Hunter", "Brownishand color of ant Red");
        Ant p16 = new Ant("Ponerine", "Predator", "Black");
        Ant p17 = new Ant("Bull", "Soldier", "Reddish");
        Ant p18 = new Ant("Meat", "Scavenger", "Purpleand color of ant Black");
        Ant p19 = new Ant("Greenand color of ant head", "Hunter", "Metallic Green");
        Ant p20 = new Ant("Banded Sugar", "Worker", "Striped");
        Ant p21 = new Ant("Spinifex", "Forager", "Yellowand color of ant Brown");
        Ant p22 = new Ant("Desert", "Scout", "Silver");
        Ant p23 = new Ant("Sahara Silver", "Worker", "Silveryand color of ant White");
        Ant p24 = new Ant("Matabele", "Medic", "Black");
        Ant p25 = new Ant("Dracula", "Queen", "Yellowand color of ant Orange");

        System.out.println("Param Ant 1: " + p1.species + "and there role" + p1.role + " and color of ant  " + p1.color);
        System.out.println("Param Ant 2: " + p2.species + "and there role" + p2.role + " and color of ant  " + p2.color);
        System.out.println("Param Ant 3: " + p3.species + "and there role" + p3.role + " and color of ant  " + p3.color);
        System.out.println("Param Ant 4: " + p4.species + "and there role" + p4.role + " and color of ant  " + p4.color);
        System.out.println("Param Ant 5: " + p5.species + "and there role" + p5.role + " and color of ant  " + p5.color);
        System.out.println("Param Ant 6: " + p6.species + "and there role" + p6.role + " and color of ant  " + p6.color);
        System.out.println("Param Ant 7: " + p7.species + "and there role" + p7.role + " and color of ant  " + p7.color);
        System.out.println("Param Ant 8: " + p8.species + "and there role" + p8.role + " and color of ant  " + p8.color);
        System.out.println("Param Ant 9: " + p9.species + "and there role" + p9.role + " and color of ant  " + p9.color);
        System.out.println("Param Ant 10: " + p10.species + "and there role" + p10.role + " and color of ant  " + p10.color);
        System.out.println("Param Ant 11: " + p11.species + "and there role" + p11.role + " and color of ant  " + p11.color);
        System.out.println("Param Ant 12: " + p12.species + "and there role" + p12.role + " and color of ant  " + p12.color);
        System.out.println("Param Ant 13: " + p13.species + "and there role" + p13.role + " and color of ant  " + p13.color);
        System.out.println("Param Ant 14: " + p14.species + "and there role" + p14.role + " and color of ant  " + p14.color);
        System.out.println("Param Ant 15: " + p15.species + "and there role" + p15.role + " and color of ant  " + p15.color);
        System.out.println("Param Ant 16: " + p16.species + "and there role" + p16.role + " and color of ant  " + p16.color);
        System.out.println("Param Ant 17: " + p17.species + "and there role" + p17.role + " and color of ant  " + p17.color);
        System.out.println("Param Ant 18: " + p18.species + "and there role" + p18.role + " and color of ant  " + p18.color);
        System.out.println("Param Ant 19: " + p19.species + "and there role" + p19.role + " and color of ant  " + p19.color);
        System.out.println("Param Ant 20: " + p20.species + "and there role" + p20.role + " and color of ant  " + p20.color);
        System.out.println("Param Ant 21: " + p21.species + "and there role" + p21.role + " and color of ant  " + p21.color);
        System.out.println("Param Ant 22: " + p22.species + "and there role" + p22.role + " and color of ant  " + p22.color);
        System.out.println("Param Ant 23: " + p23.species + "and there role" + p23.role + " and color of ant  " + p23.color);
        System.out.println("Param Ant 24: " + p24.species + "and there role" + p24.role + " and color of ant  " + p24.color);
        System.out.println("Param Ant 25: " + p25.species + "and there role" + p25.role + " and color of ant  " + p25.color);
    }
}
