
class BangleRunner {
    public static void main(String[] args) {
//default constructor
        Bangle b1 = new Bangle(); 
		b1.color = "Red";
        Bangle b2 = new Bangle(); 
		b2.color = "Green";
        Bangle b3 = new Bangle(); 
		b3.color = "Blue";
        Bangle b4 = new Bangle(); 
		b4.color = "Yellow";
        Bangle b5 = new Bangle();
		b5.color = "Orange";
        Bangle b6 = new Bangle(); 
		b6.color = "Purple";
        Bangle b7 = new Bangle(); 
		b7.color = "Pink";
        Bangle b8 = new Bangle(); 
		b8.color = "Brown";
        Bangle b9 = new Bangle(); 
		b9.color = "Black";
        Bangle b10 = new Bangle(); 
		b10.color = "White";
        Bangle b11 = new Bangle(); 
		b11.color = "Gray";
        Bangle b12 = new Bangle(); 
		b12.color = "Cyan";
        Bangle b13 = new Bangle(); 
		b13.color = "Magenta";
        Bangle b14 = new Bangle(); 
		b14.color = "Maroon";
        Bangle b15 = new Bangle(); 
		b15.color = "Navy";
        Bangle b16 = new Bangle(); 
		b16.color = "Olive";
        Bangle b17 = new Bangle(); 
		b17.color = "Teal";
        Bangle b18 = new Bangle(); 
		b18.color = "Lime";
        Bangle b19 = new Bangle(); 
		b19.color = "Indigo";
        Bangle b20 = new Bangle(); 
		b20.color = "Violet";
        Bangle b21 = new Bangle(); 
		b21.color = "Coral";
        Bangle b22 = new Bangle(); 
		b22.color = "Salmon";
        Bangle b23 = new Bangle(); 
		b23.color = "Turquoise";
        Bangle b24 = new Bangle(); 
		b24.color = "Beige";
        Bangle b25 = new Bangle(); 
		b25.color = "Ivory";

        System.out.println("Bangle color : " + b1.color);
        System.out.println("Bangle color : " + b2.color);
        System.out.println("Bangle color : " + b3.color);
        System.out.println("Bangle color : " + b4.color);
        System.out.println("Bangle color : " + b5.color);
        System.out.println("Bangle color : " + b6.color);
        System.out.println("Bangle color : " + b7.color);
        System.out.println("Bangle color : " + b8.color);
        System.out.println("Bangle color : " + b9.color);
        System.out.println("Bangle color : " + b10.color);
        System.out.println("Bangle color : " + b11.color);
        System.out.println("Bangle color : " + b12.color);
        System.out.println("Bangle color : " + b13.color);
        System.out.println("Bangle color : " + b14.color);
        System.out.println("Bangle color : " + b15.color);
        System.out.println("Bangle color : " + b16.color);
        System.out.println("Bangle color : " + b17.color);
        System.out.println("Bangle color : " + b18.color);
        System.out.println("Bangle color : " + b19.color);
        System.out.println("Bangle color : " + b20.color);
        System.out.println("Bangle color : " + b21.color);
        System.out.println("Bangle color : " + b22.color);
        System.out.println("Bangle color : " + b23.color);
        System.out.println("Bangle color : " + b24.color);
        System.out.println("Bangle color : " + b25.color);
//parameterized constructor
        Bangle p1 = new Bangle("Gold");
        Bangle p2 = new Bangle("Silver");
        Bangle p3 = new Bangle("Bronze");
        Bangle p4 = new Bangle("Copper");
        Bangle p5 = new Bangle("Platinum");
        Bangle p6 = new Bangle("Ruby");
        Bangle p7 = new Bangle("Sapphire");
        Bangle p8 = new Bangle("Emerald");
        Bangle p9 = new Bangle("Amethyst");
        Bangle p10 = new Bangle("Topaz");
        Bangle p11 = new Bangle("Pearl");
        Bangle p12 = new Bangle("Jade");
        Bangle p13 = new Bangle("Onyx");
        Bangle p14 = new Bangle("Amber");
        Bangle p15 = new Bangle("Quartz");
        Bangle p16 = new Bangle("Garnet");
        Bangle p17 = new Bangle("Opal");
        Bangle p18 = new Bangle("Zircon");
        Bangle p19 = new Bangle("Aquamarine");
        Bangle p20 = new Bangle("Peridot");
        Bangle p21 = new Bangle("Obsidian");
        Bangle p22 = new Bangle("Malachite");
        Bangle p23 = new Bangle("Lapis");
        Bangle p24 = new Bangle("Citrine");
        Bangle p25 = new Bangle("Spinel");

        System.out.println("Color of  Bangle 1: " + p1.color);
        System.out.println("Color of  Bangle 2: " + p2.color);
        System.out.println("Color of  Bangle 3: " + p3.color);
        System.out.println("Color of  Bangle 4: " + p4.color);
        System.out.println("Color of  Bangle 5: " + p5.color);
        System.out.println("Color of  Bangle 6: " + p6.color);
        System.out.println("Color of  Bangle 7: " + p7.color);
        System.out.println("Color of  Bangle 8: " + p8.color);
        System.out.println("Color of  Bangle 9: " + p9.color);
        System.out.println("Color of  Bangle 10: " + p10.color);
        System.out.println("Color of  Bangle 11: " + p11.color);
        System.out.println("Color of  Bangle 12: " + p12.color);
        System.out.println("Color of  Bangle 13: " + p13.color);
        System.out.println("Color of  Bangle 14: " + p14.color);
        System.out.println("Color of  Bangle 15: " + p15.color);
        System.out.println("Color of  Bangle 16: " + p16.color);
        System.out.println("Color of  Bangle 17: " + p17.color);
        System.out.println("Color of  Bangle 18: " + p18.color);
        System.out.println("Color of  Bangle 19: " + p19.color);
        System.out.println("Color of  Bangle 20: " + p20.color);
        System.out.println("Color of  Bangle 21: " + p21.color);
        System.out.println("Color of  Bangle 22: " + p22.color);
        System.out.println("Color of  Bangle 23: " + p23.color);
        System.out.println("Color of  Bangle 24: " + p24.color);
        System.out.println("Color of  Bangle 25: " + p25.color);
    }
}
