class BookshelfExecutor {

    public static void main(String[] args) {

        Bookshelf shelf1 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf1.shelfBrand);
        System.out.println("The shelfId is : " + shelf1.shelfId);
        System.out.println("The shelfPrice is : " + shelf1.shelfPrice);
        System.out.println("The isAvailable is : " + shelf1.isAvailable);
        System.out.println("The shelfType is : " + shelf1.shelfType);
        System.out.println("The numberOfShelves is : " + shelf1.numberOfShelves);
        System.out.println("The weight is : " + shelf1.weight);
        System.out.println("The isPortable is : " + shelf1.isPortable);
        System.out.println("The material is : " + shelf1.material);
        System.out.println("The warrantyYears is : " + shelf1.warrantyYears);
        System.out.println("The height is : " + shelf1.height);
        System.out.println("The hasGlassDoor is : " + shelf1.hasGlassDoor);
        System.out.println("The color is : " + shelf1.color);
        System.out.println("The stockQuantity is : " + shelf1.stockQuantity);
        System.out.println("The width is : " + shelf1.width);
        System.out.println("The isEcoFriendly is : " + shelf1.isEcoFriendly);
        System.out.println("The finishType is : " + shelf1.finishType);
        System.out.println("The rating is : " + shelf1.rating);
        System.out.println("The maxLoad is : " + shelf1.maxLoad);
        System.out.println("The isCertified is : " + shelf1.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf1.manufacturingYear);
        System.out.println("The depth is : " + shelf1.depth);
        System.out.println("The isFoldable is : " + shelf1.isFoldable);
        System.out.println("The certificationType is : " + shelf1.certificationType);

        shelf1.shelfBrand = "WoodCraft";
        shelf1.shelfId = 1;
        shelf1.shelfPrice = 150.75;
        shelf1.isAvailable = true;
        shelf1.shelfType = "Wall Mounted";
        shelf1.numberOfShelves = 5;
        shelf1.weight = 25.0;
        shelf1.isPortable = false;
        shelf1.material = "Wood";
        shelf1.warrantyYears = 2;
        shelf1.height = 180.0;
        shelf1.hasGlassDoor = false;
        shelf1.color = "Brown";
        shelf1.stockQuantity = 12;
        shelf1.width = 80.0;
        shelf1.isEcoFriendly = true;
        shelf1.finishType = "Matte";
        shelf1.rating = 4;
        shelf1.maxLoad = 120.0;
        shelf1.isCertified = true;
        shelf1.countryOfOrigin = "India";
        shelf1.manufacturingYear = 2025;
        shelf1.depth = 30.0;
        shelf1.isFoldable = false;
        shelf1.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf1.shelfBrand);
        System.out.println("The shelfId is : " + shelf1.shelfId);
        System.out.println("The shelfPrice is : " + shelf1.shelfPrice);
        System.out.println("The isAvailable is : " + shelf1.isAvailable);
        System.out.println("The shelfType is : " + shelf1.shelfType);
        System.out.println("The numberOfShelves is : " + shelf1.numberOfShelves);
        System.out.println("The weight is : " + shelf1.weight);
        System.out.println("The isPortable is : " + shelf1.isPortable);
        System.out.println("The material is : " + shelf1.material);
        System.out.println("The warrantyYears is : " + shelf1.warrantyYears);
        System.out.println("The height is : " + shelf1.height);
        System.out.println("The hasGlassDoor is : " + shelf1.hasGlassDoor);
        System.out.println("The color is : " + shelf1.color);
        System.out.println("The stockQuantity is : " + shelf1.stockQuantity);
        System.out.println("The width is : " + shelf1.width);
        System.out.println("The isEcoFriendly is : " + shelf1.isEcoFriendly);
        System.out.println("The finishType is : " + shelf1.finishType);
        System.out.println("The rating is : " + shelf1.rating);
        System.out.println("The maxLoad is : " + shelf1.maxLoad);
        System.out.println("The isCertified is : " + shelf1.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf1.manufacturingYear);
        System.out.println("The depth is : " + shelf1.depth);
        System.out.println("The isFoldable is : " + shelf1.isFoldable);
        System.out.println("The certificationType is : " + shelf1.certificationType);


        Bookshelf shelf2 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf2.shelfBrand);
        System.out.println("The shelfId is : " + shelf2.shelfId);
        System.out.println("The shelfPrice is : " + shelf2.shelfPrice);
        System.out.println("The isAvailable is : " + shelf2.isAvailable);
        System.out.println("The shelfType is : " + shelf2.shelfType);
        System.out.println("The numberOfShelves is : " + shelf2.numberOfShelves);
        System.out.println("The weight is : " + shelf2.weight);
        System.out.println("The isPortable is : " + shelf2.isPortable);
        System.out.println("The material is : " + shelf2.material);
        System.out.println("The warrantyYears is : " + shelf2.warrantyYears);
        System.out.println("The height is : " + shelf2.height);
        System.out.println("The hasGlassDoor is : " + shelf2.hasGlassDoor);
        System.out.println("The color is : " + shelf2.color);
        System.out.println("The stockQuantity is : " + shelf2.stockQuantity);
        System.out.println("The width is : " + shelf2.width);
        System.out.println("The isEcoFriendly is : " + shelf2.isEcoFriendly);
        System.out.println("The finishType is : " + shelf2.finishType);
        System.out.println("The rating is : " + shelf2.rating);
        System.out.println("The maxLoad is : " + shelf2.maxLoad);
        System.out.println("The isCertified is : " + shelf2.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf2.manufacturingYear);
        System.out.println("The depth is : " + shelf2.depth);
        System.out.println("The isFoldable is : " + shelf2.isFoldable);
        System.out.println("The certificationType is : " + shelf2.certificationType);

        shelf2.shelfBrand = "WoodCraft";
        shelf2.shelfId = 2;
        shelf2.shelfPrice = 250.75;
        shelf2.isAvailable = true;
        shelf2.shelfType = "Wall Mounted";
        shelf2.numberOfShelves = 5;
        shelf2.weight = 25.0;
        shelf2.isPortable = false;
        shelf2.material = "Wood";
        shelf2.warrantyYears = 2;
        shelf2.height = 180.0;
        shelf2.hasGlassDoor = false;
        shelf2.color = "Brown";
        shelf2.stockQuantity = 12;
        shelf2.width = 80.0;
        shelf2.isEcoFriendly = true;
        shelf2.finishType = "Matte";
        shelf2.rating = 4;
        shelf2.maxLoad = 120.0;
        shelf2.isCertified = true;
        shelf2.countryOfOrigin = "India";
        shelf2.manufacturingYear = 2025;
        shelf2.depth = 30.0;
        shelf2.isFoldable = false;
        shelf2.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf2.shelfBrand);
        System.out.println("The shelfId is : " + shelf2.shelfId);
        System.out.println("The shelfPrice is : " + shelf2.shelfPrice);
        System.out.println("The isAvailable is : " + shelf2.isAvailable);
        System.out.println("The shelfType is : " + shelf2.shelfType);
        System.out.println("The numberOfShelves is : " + shelf2.numberOfShelves);
        System.out.println("The weight is : " + shelf2.weight);
        System.out.println("The isPortable is : " + shelf2.isPortable);
        System.out.println("The material is : " + shelf2.material);
        System.out.println("The warrantyYears is : " + shelf2.warrantyYears);
        System.out.println("The height is : " + shelf2.height);
        System.out.println("The hasGlassDoor is : " + shelf2.hasGlassDoor);
        System.out.println("The color is : " + shelf2.color);
        System.out.println("The stockQuantity is : " + shelf2.stockQuantity);
        System.out.println("The width is : " + shelf2.width);
        System.out.println("The isEcoFriendly is : " + shelf2.isEcoFriendly);
        System.out.println("The finishType is : " + shelf2.finishType);
        System.out.println("The rating is : " + shelf2.rating);
        System.out.println("The maxLoad is : " + shelf2.maxLoad);
        System.out.println("The isCertified is : " + shelf2.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf2.manufacturingYear);
        System.out.println("The depth is : " + shelf2.depth);
        System.out.println("The isFoldable is : " + shelf2.isFoldable);
        System.out.println("The certificationType is : " + shelf2.certificationType);


        Bookshelf shelf3 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf3.shelfBrand);
        System.out.println("The shelfId is : " + shelf3.shelfId);
        System.out.println("The shelfPrice is : " + shelf3.shelfPrice);
        System.out.println("The isAvailable is : " + shelf3.isAvailable);
        System.out.println("The shelfType is : " + shelf3.shelfType);
        System.out.println("The numberOfShelves is : " + shelf3.numberOfShelves);
        System.out.println("The weight is : " + shelf3.weight);
        System.out.println("The isPortable is : " + shelf3.isPortable);
        System.out.println("The material is : " + shelf3.material);
        System.out.println("The warrantyYears is : " + shelf3.warrantyYears);
        System.out.println("The height is : " + shelf3.height);
        System.out.println("The hasGlassDoor is : " + shelf3.hasGlassDoor);
        System.out.println("The color is : " + shelf3.color);
        System.out.println("The stockQuantity is : " + shelf3.stockQuantity);
        System.out.println("The width is : " + shelf3.width);
        System.out.println("The isEcoFriendly is : " + shelf3.isEcoFriendly);
        System.out.println("The finishType is : " + shelf3.finishType);
        System.out.println("The rating is : " + shelf3.rating);
        System.out.println("The maxLoad is : " + shelf3.maxLoad);
        System.out.println("The isCertified is : " + shelf3.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf3.manufacturingYear);
        System.out.println("The depth is : " + shelf3.depth);
        System.out.println("The isFoldable is : " + shelf3.isFoldable);
        System.out.println("The certificationType is : " + shelf3.certificationType);

        shelf3.shelfBrand = "WoodCraft";
        shelf3.shelfId = 3;
        shelf3.shelfPrice = 350.75;
        shelf3.isAvailable = true;
        shelf3.shelfType = "Wall Mounted";
        shelf3.numberOfShelves = 5;
        shelf3.weight = 25.0;
        shelf3.isPortable = false;
        shelf3.material = "Wood";
        shelf3.warrantyYears = 2;
        shelf3.height = 180.0;
        shelf3.hasGlassDoor = false;
        shelf3.color = "Brown";
        shelf3.stockQuantity = 12;
        shelf3.width = 80.0;
        shelf3.isEcoFriendly = true;
        shelf3.finishType = "Matte";
        shelf3.rating = 4;
        shelf3.maxLoad = 120.0;
        shelf3.isCertified = true;
        shelf3.countryOfOrigin = "India";
        shelf3.manufacturingYear = 2025;
        shelf3.depth = 30.0;
        shelf3.isFoldable = false;
        shelf3.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf3.shelfBrand);
        System.out.println("The shelfId is : " + shelf3.shelfId);
        System.out.println("The shelfPrice is : " + shelf3.shelfPrice);
        System.out.println("The isAvailable is : " + shelf3.isAvailable);
        System.out.println("The shelfType is : " + shelf3.shelfType);
        System.out.println("The numberOfShelves is : " + shelf3.numberOfShelves);
        System.out.println("The weight is : " + shelf3.weight);
        System.out.println("The isPortable is : " + shelf3.isPortable);
        System.out.println("The material is : " + shelf3.material);
        System.out.println("The warrantyYears is : " + shelf3.warrantyYears);
        System.out.println("The height is : " + shelf3.height);
        System.out.println("The hasGlassDoor is : " + shelf3.hasGlassDoor);
        System.out.println("The color is : " + shelf3.color);
        System.out.println("The stockQuantity is : " + shelf3.stockQuantity);
        System.out.println("The width is : " + shelf3.width);
        System.out.println("The isEcoFriendly is : " + shelf3.isEcoFriendly);
        System.out.println("The finishType is : " + shelf3.finishType);
        System.out.println("The rating is : " + shelf3.rating);
        System.out.println("The maxLoad is : " + shelf3.maxLoad);
        System.out.println("The isCertified is : " + shelf3.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf3.manufacturingYear);
        System.out.println("The depth is : " + shelf3.depth);
        System.out.println("The isFoldable is : " + shelf3.isFoldable);
        System.out.println("The certificationType is : " + shelf3.certificationType);


        Bookshelf shelf4 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf4.shelfBrand);
        System.out.println("The shelfId is : " + shelf4.shelfId);
        System.out.println("The shelfPrice is : " + shelf4.shelfPrice);
        System.out.println("The isAvailable is : " + shelf4.isAvailable);
        System.out.println("The shelfType is : " + shelf4.shelfType);
        System.out.println("The numberOfShelves is : " + shelf4.numberOfShelves);
        System.out.println("The weight is : " + shelf4.weight);
        System.out.println("The isPortable is : " + shelf4.isPortable);
        System.out.println("The material is : " + shelf4.material);
        System.out.println("The warrantyYears is : " + shelf4.warrantyYears);
        System.out.println("The height is : " + shelf4.height);
        System.out.println("The hasGlassDoor is : " + shelf4.hasGlassDoor);
        System.out.println("The color is : " + shelf4.color);
        System.out.println("The stockQuantity is : " + shelf4.stockQuantity);
        System.out.println("The width is : " + shelf4.width);
        System.out.println("The isEcoFriendly is : " + shelf4.isEcoFriendly);
        System.out.println("The finishType is : " + shelf4.finishType);
        System.out.println("The rating is : " + shelf4.rating);
        System.out.println("The maxLoad is : " + shelf4.maxLoad);
        System.out.println("The isCertified is : " + shelf4.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf4.manufacturingYear);
        System.out.println("The depth is : " + shelf4.depth);
        System.out.println("The isFoldable is : " + shelf4.isFoldable);
        System.out.println("The certificationType is : " + shelf4.certificationType);

        shelf4.shelfBrand = "WoodCraft";
        shelf4.shelfId = 4;
        shelf4.shelfPrice = 450.75;
        shelf4.isAvailable = true;
        shelf4.shelfType = "Wall Mounted";
        shelf4.numberOfShelves = 5;
        shelf4.weight = 25.0;
        shelf4.isPortable = false;
        shelf4.material = "Wood";
        shelf4.warrantyYears = 2;
        shelf4.height = 180.0;
        shelf4.hasGlassDoor = false;
        shelf4.color = "Brown";
        shelf4.stockQuantity = 12;
        shelf4.width = 80.0;
        shelf4.isEcoFriendly = true;
        shelf4.finishType = "Matte";
        shelf4.rating = 4;
        shelf4.maxLoad = 120.0;
        shelf4.isCertified = true;
        shelf4.countryOfOrigin = "India";
        shelf4.manufacturingYear = 2025;
        shelf4.depth = 30.0;
        shelf4.isFoldable = false;
        shelf4.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf4.shelfBrand);
        System.out.println("The shelfId is : " + shelf4.shelfId);
        System.out.println("The shelfPrice is : " + shelf4.shelfPrice);
        System.out.println("The isAvailable is : " + shelf4.isAvailable);
        System.out.println("The shelfType is : " + shelf4.shelfType);
        System.out.println("The numberOfShelves is : " + shelf4.numberOfShelves);
        System.out.println("The weight is : " + shelf4.weight);
        System.out.println("The isPortable is : " + shelf4.isPortable);
        System.out.println("The material is : " + shelf4.material);
        System.out.println("The warrantyYears is : " + shelf4.warrantyYears);
        System.out.println("The height is : " + shelf4.height);
        System.out.println("The hasGlassDoor is : " + shelf4.hasGlassDoor);
        System.out.println("The color is : " + shelf4.color);
        System.out.println("The stockQuantity is : " + shelf4.stockQuantity);
        System.out.println("The width is : " + shelf4.width);
        System.out.println("The isEcoFriendly is : " + shelf4.isEcoFriendly);
        System.out.println("The finishType is : " + shelf4.finishType);
        System.out.println("The rating is : " + shelf4.rating);
        System.out.println("The maxLoad is : " + shelf4.maxLoad);
        System.out.println("The isCertified is : " + shelf4.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf4.manufacturingYear);
        System.out.println("The depth is : " + shelf4.depth);
        System.out.println("The isFoldable is : " + shelf4.isFoldable);
        System.out.println("The certificationType is : " + shelf4.certificationType);


        Bookshelf shelf5 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf5.shelfBrand);
        System.out.println("The shelfId is : " + shelf5.shelfId);
        System.out.println("The shelfPrice is : " + shelf5.shelfPrice);
        System.out.println("The isAvailable is : " + shelf5.isAvailable);
        System.out.println("The shelfType is : " + shelf5.shelfType);
        System.out.println("The numberOfShelves is : " + shelf5.numberOfShelves);
        System.out.println("The weight is : " + shelf5.weight);
        System.out.println("The isPortable is : " + shelf5.isPortable);
        System.out.println("The material is : " + shelf5.material);
        System.out.println("The warrantyYears is : " + shelf5.warrantyYears);
        System.out.println("The height is : " + shelf5.height);
        System.out.println("The hasGlassDoor is : " + shelf5.hasGlassDoor);
        System.out.println("The color is : " + shelf5.color);
        System.out.println("The stockQuantity is : " + shelf5.stockQuantity);
        System.out.println("The width is : " + shelf5.width);
        System.out.println("The isEcoFriendly is : " + shelf5.isEcoFriendly);
        System.out.println("The finishType is : " + shelf5.finishType);
        System.out.println("The rating is : " + shelf5.rating);
        System.out.println("The maxLoad is : " + shelf5.maxLoad);
        System.out.println("The isCertified is : " + shelf5.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf5.manufacturingYear);
        System.out.println("The depth is : " + shelf5.depth);
        System.out.println("The isFoldable is : " + shelf5.isFoldable);
        System.out.println("The certificationType is : " + shelf5.certificationType);

        shelf5.shelfBrand = "WoodCraft";
        shelf5.shelfId = 5;
        shelf5.shelfPrice = 550.75;
        shelf5.isAvailable = true;
        shelf5.shelfType = "Wall Mounted";
        shelf5.numberOfShelves = 5;
        shelf5.weight = 25.0;
        shelf5.isPortable = false;
        shelf5.material = "Wood";
        shelf5.warrantyYears = 2;
        shelf5.height = 180.0;
        shelf5.hasGlassDoor = false;
        shelf5.color = "Brown";
        shelf5.stockQuantity = 12;
        shelf5.width = 80.0;
        shelf5.isEcoFriendly = true;
        shelf5.finishType = "Matte";
        shelf5.rating = 4;
        shelf5.maxLoad = 120.0;
        shelf5.isCertified = true;
        shelf5.countryOfOrigin = "India";
        shelf5.manufacturingYear = 2025;
        shelf5.depth = 30.0;
        shelf5.isFoldable = false;
        shelf5.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf5.shelfBrand);
        System.out.println("The shelfId is : " + shelf5.shelfId);
        System.out.println("The shelfPrice is : " + shelf5.shelfPrice);
        System.out.println("The isAvailable is : " + shelf5.isAvailable);
        System.out.println("The shelfType is : " + shelf5.shelfType);
        System.out.println("The numberOfShelves is : " + shelf5.numberOfShelves);
        System.out.println("The weight is : " + shelf5.weight);
        System.out.println("The isPortable is : " + shelf5.isPortable);
        System.out.println("The material is : " + shelf5.material);
        System.out.println("The warrantyYears is : " + shelf5.warrantyYears);
        System.out.println("The height is : " + shelf5.height);
        System.out.println("The hasGlassDoor is : " + shelf5.hasGlassDoor);
        System.out.println("The color is : " + shelf5.color);
        System.out.println("The stockQuantity is : " + shelf5.stockQuantity);
        System.out.println("The width is : " + shelf5.width);
        System.out.println("The isEcoFriendly is : " + shelf5.isEcoFriendly);
        System.out.println("The finishType is : " + shelf5.finishType);
        System.out.println("The rating is : " + shelf5.rating);
        System.out.println("The maxLoad is : " + shelf5.maxLoad);
        System.out.println("The isCertified is : " + shelf5.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf5.manufacturingYear);
        System.out.println("The depth is : " + shelf5.depth);
        System.out.println("The isFoldable is : " + shelf5.isFoldable);
        System.out.println("The certificationType is : " + shelf5.certificationType);


        Bookshelf shelf6 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf6.shelfBrand);
        System.out.println("The shelfId is : " + shelf6.shelfId);
        System.out.println("The shelfPrice is : " + shelf6.shelfPrice);
        System.out.println("The isAvailable is : " + shelf6.isAvailable);
        System.out.println("The shelfType is : " + shelf6.shelfType);
        System.out.println("The numberOfShelves is : " + shelf6.numberOfShelves);
        System.out.println("The weight is : " + shelf6.weight);
        System.out.println("The isPortable is : " + shelf6.isPortable);
        System.out.println("The material is : " + shelf6.material);
        System.out.println("The warrantyYears is : " + shelf6.warrantyYears);
        System.out.println("The height is : " + shelf6.height);
        System.out.println("The hasGlassDoor is : " + shelf6.hasGlassDoor);
        System.out.println("The color is : " + shelf6.color);
        System.out.println("The stockQuantity is : " + shelf6.stockQuantity);
        System.out.println("The width is : " + shelf6.width);
        System.out.println("The isEcoFriendly is : " + shelf6.isEcoFriendly);
        System.out.println("The finishType is : " + shelf6.finishType);
        System.out.println("The rating is : " + shelf6.rating);
        System.out.println("The maxLoad is : " + shelf6.maxLoad);
        System.out.println("The isCertified is : " + shelf6.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf6.manufacturingYear);
        System.out.println("The depth is : " + shelf6.depth);
        System.out.println("The isFoldable is : " + shelf6.isFoldable);
        System.out.println("The certificationType is : " + shelf6.certificationType);

        shelf6.shelfBrand = "WoodCraft";
        shelf6.shelfId = 6;
        shelf6.shelfPrice = 650.75;
        shelf6.isAvailable = true;
        shelf6.shelfType = "Wall Mounted";
        shelf6.numberOfShelves = 5;
        shelf6.weight = 25.0;
        shelf6.isPortable = false;
        shelf6.material = "Wood";
        shelf6.warrantyYears = 2;
        shelf6.height = 180.0;
        shelf6.hasGlassDoor = false;
        shelf6.color = "Brown";
        shelf6.stockQuantity = 12;
        shelf6.width = 80.0;
        shelf6.isEcoFriendly = true;
        shelf6.finishType = "Matte";
        shelf6.rating = 4;
        shelf6.maxLoad = 120.0;
        shelf6.isCertified = true;
        shelf6.countryOfOrigin = "India";
        shelf6.manufacturingYear = 2025;
        shelf6.depth = 30.0;
        shelf6.isFoldable = false;
        shelf6.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf6.shelfBrand);
        System.out.println("The shelfId is : " + shelf6.shelfId);
        System.out.println("The shelfPrice is : " + shelf6.shelfPrice);
        System.out.println("The isAvailable is : " + shelf6.isAvailable);
        System.out.println("The shelfType is : " + shelf6.shelfType);
        System.out.println("The numberOfShelves is : " + shelf6.numberOfShelves);
        System.out.println("The weight is : " + shelf6.weight);
        System.out.println("The isPortable is : " + shelf6.isPortable);
        System.out.println("The material is : " + shelf6.material);
        System.out.println("The warrantyYears is : " + shelf6.warrantyYears);
        System.out.println("The height is : " + shelf6.height);
        System.out.println("The hasGlassDoor is : " + shelf6.hasGlassDoor);
        System.out.println("The color is : " + shelf6.color);
        System.out.println("The stockQuantity is : " + shelf6.stockQuantity);
        System.out.println("The width is : " + shelf6.width);
        System.out.println("The isEcoFriendly is : " + shelf6.isEcoFriendly);
        System.out.println("The finishType is : " + shelf6.finishType);
        System.out.println("The rating is : " + shelf6.rating);
        System.out.println("The maxLoad is : " + shelf6.maxLoad);
        System.out.println("The isCertified is : " + shelf6.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf6.manufacturingYear);
        System.out.println("The depth is : " + shelf6.depth);
        System.out.println("The isFoldable is : " + shelf6.isFoldable);
        System.out.println("The certificationType is : " + shelf6.certificationType);


        Bookshelf shelf7 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf7.shelfBrand);
        System.out.println("The shelfId is : " + shelf7.shelfId);
        System.out.println("The shelfPrice is : " + shelf7.shelfPrice);
        System.out.println("The isAvailable is : " + shelf7.isAvailable);
        System.out.println("The shelfType is : " + shelf7.shelfType);
        System.out.println("The numberOfShelves is : " + shelf7.numberOfShelves);
        System.out.println("The weight is : " + shelf7.weight);
        System.out.println("The isPortable is : " + shelf7.isPortable);
        System.out.println("The material is : " + shelf7.material);
        System.out.println("The warrantyYears is : " + shelf7.warrantyYears);
        System.out.println("The height is : " + shelf7.height);
        System.out.println("The hasGlassDoor is : " + shelf7.hasGlassDoor);
        System.out.println("The color is : " + shelf7.color);
        System.out.println("The stockQuantity is : " + shelf7.stockQuantity);
        System.out.println("The width is : " + shelf7.width);
        System.out.println("The isEcoFriendly is : " + shelf7.isEcoFriendly);
        System.out.println("The finishType is : " + shelf7.finishType);
        System.out.println("The rating is : " + shelf7.rating);
        System.out.println("The maxLoad is : " + shelf7.maxLoad);
        System.out.println("The isCertified is : " + shelf7.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf7.manufacturingYear);
        System.out.println("The depth is : " + shelf7.depth);
        System.out.println("The isFoldable is : " + shelf7.isFoldable);
        System.out.println("The certificationType is : " + shelf7.certificationType);

        shelf7.shelfBrand = "WoodCraft";
        shelf7.shelfId = 7;
        shelf7.shelfPrice = 750.75;
        shelf7.isAvailable = true;
        shelf7.shelfType = "Wall Mounted";
        shelf7.numberOfShelves = 5;
        shelf7.weight = 25.0;
        shelf7.isPortable = false;
        shelf7.material = "Wood";
        shelf7.warrantyYears = 2;
        shelf7.height = 180.0;
        shelf7.hasGlassDoor = false;
        shelf7.color = "Brown";
        shelf7.stockQuantity = 12;
        shelf7.width = 80.0;
        shelf7.isEcoFriendly = true;
        shelf7.finishType = "Matte";
        shelf7.rating = 4;
        shelf7.maxLoad = 120.0;
        shelf7.isCertified = true;
        shelf7.countryOfOrigin = "India";
        shelf7.manufacturingYear = 2025;
        shelf7.depth = 30.0;
        shelf7.isFoldable = false;
        shelf7.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf7.shelfBrand);
        System.out.println("The shelfId is : " + shelf7.shelfId);
        System.out.println("The shelfPrice is : " + shelf7.shelfPrice);
        System.out.println("The isAvailable is : " + shelf7.isAvailable);
        System.out.println("The shelfType is : " + shelf7.shelfType);
        System.out.println("The numberOfShelves is : " + shelf7.numberOfShelves);
        System.out.println("The weight is : " + shelf7.weight);
        System.out.println("The isPortable is : " + shelf7.isPortable);
        System.out.println("The material is : " + shelf7.material);
        System.out.println("The warrantyYears is : " + shelf7.warrantyYears);
        System.out.println("The height is : " + shelf7.height);
        System.out.println("The hasGlassDoor is : " + shelf7.hasGlassDoor);
        System.out.println("The color is : " + shelf7.color);
        System.out.println("The stockQuantity is : " + shelf7.stockQuantity);
        System.out.println("The width is : " + shelf7.width);
        System.out.println("The isEcoFriendly is : " + shelf7.isEcoFriendly);
        System.out.println("The finishType is : " + shelf7.finishType);
        System.out.println("The rating is : " + shelf7.rating);
        System.out.println("The maxLoad is : " + shelf7.maxLoad);
        System.out.println("The isCertified is : " + shelf7.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf7.manufacturingYear);
        System.out.println("The depth is : " + shelf7.depth);
        System.out.println("The isFoldable is : " + shelf7.isFoldable);
        System.out.println("The certificationType is : " + shelf7.certificationType);


        Bookshelf shelf8 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf8.shelfBrand);
        System.out.println("The shelfId is : " + shelf8.shelfId);
        System.out.println("The shelfPrice is : " + shelf8.shelfPrice);
        System.out.println("The isAvailable is : " + shelf8.isAvailable);
        System.out.println("The shelfType is : " + shelf8.shelfType);
        System.out.println("The numberOfShelves is : " + shelf8.numberOfShelves);
        System.out.println("The weight is : " + shelf8.weight);
        System.out.println("The isPortable is : " + shelf8.isPortable);
        System.out.println("The material is : " + shelf8.material);
        System.out.println("The warrantyYears is : " + shelf8.warrantyYears);
        System.out.println("The height is : " + shelf8.height);
        System.out.println("The hasGlassDoor is : " + shelf8.hasGlassDoor);
        System.out.println("The color is : " + shelf8.color);
        System.out.println("The stockQuantity is : " + shelf8.stockQuantity);
        System.out.println("The width is : " + shelf8.width);
        System.out.println("The isEcoFriendly is : " + shelf8.isEcoFriendly);
        System.out.println("The finishType is : " + shelf8.finishType);
        System.out.println("The rating is : " + shelf8.rating);
        System.out.println("The maxLoad is : " + shelf8.maxLoad);
        System.out.println("The isCertified is : " + shelf8.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf8.manufacturingYear);
        System.out.println("The depth is : " + shelf8.depth);
        System.out.println("The isFoldable is : " + shelf8.isFoldable);
        System.out.println("The certificationType is : " + shelf8.certificationType);

        shelf8.shelfBrand = "WoodCraft";
        shelf8.shelfId = 8;
        shelf8.shelfPrice = 850.75;
        shelf8.isAvailable = true;
        shelf8.shelfType = "Wall Mounted";
        shelf8.numberOfShelves = 5;
        shelf8.weight = 25.0;
        shelf8.isPortable = false;
        shelf8.material = "Wood";
        shelf8.warrantyYears = 2;
        shelf8.height = 180.0;
        shelf8.hasGlassDoor = false;
        shelf8.color = "Brown";
        shelf8.stockQuantity = 12;
        shelf8.width = 80.0;
        shelf8.isEcoFriendly = true;
        shelf8.finishType = "Matte";
        shelf8.rating = 4;
        shelf8.maxLoad = 120.0;
        shelf8.isCertified = true;
        shelf8.countryOfOrigin = "India";
        shelf8.manufacturingYear = 2025;
        shelf8.depth = 30.0;
        shelf8.isFoldable = false;
        shelf8.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf8.shelfBrand);
        System.out.println("The shelfId is : " + shelf8.shelfId);
        System.out.println("The shelfPrice is : " + shelf8.shelfPrice);
        System.out.println("The isAvailable is : " + shelf8.isAvailable);
        System.out.println("The shelfType is : " + shelf8.shelfType);
        System.out.println("The numberOfShelves is : " + shelf8.numberOfShelves);
        System.out.println("The weight is : " + shelf8.weight);
        System.out.println("The isPortable is : " + shelf8.isPortable);
        System.out.println("The material is : " + shelf8.material);
        System.out.println("The warrantyYears is : " + shelf8.warrantyYears);
        System.out.println("The height is : " + shelf8.height);
        System.out.println("The hasGlassDoor is : " + shelf8.hasGlassDoor);
        System.out.println("The color is : " + shelf8.color);
        System.out.println("The stockQuantity is : " + shelf8.stockQuantity);
        System.out.println("The width is : " + shelf8.width);
        System.out.println("The isEcoFriendly is : " + shelf8.isEcoFriendly);
        System.out.println("The finishType is : " + shelf8.finishType);
        System.out.println("The rating is : " + shelf8.rating);
        System.out.println("The maxLoad is : " + shelf8.maxLoad);
        System.out.println("The isCertified is : " + shelf8.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf8.manufacturingYear);
        System.out.println("The depth is : " + shelf8.depth);
        System.out.println("The isFoldable is : " + shelf8.isFoldable);
        System.out.println("The certificationType is : " + shelf8.certificationType);


        Bookshelf shelf9 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf9.shelfBrand);
        System.out.println("The shelfId is : " + shelf9.shelfId);
        System.out.println("The shelfPrice is : " + shelf9.shelfPrice);
        System.out.println("The isAvailable is : " + shelf9.isAvailable);
        System.out.println("The shelfType is : " + shelf9.shelfType);
        System.out.println("The numberOfShelves is : " + shelf9.numberOfShelves);
        System.out.println("The weight is : " + shelf9.weight);
        System.out.println("The isPortable is : " + shelf9.isPortable);
        System.out.println("The material is : " + shelf9.material);
        System.out.println("The warrantyYears is : " + shelf9.warrantyYears);
        System.out.println("The height is : " + shelf9.height);
        System.out.println("The hasGlassDoor is : " + shelf9.hasGlassDoor);
        System.out.println("The color is : " + shelf9.color);
        System.out.println("The stockQuantity is : " + shelf9.stockQuantity);
        System.out.println("The width is : " + shelf9.width);
        System.out.println("The isEcoFriendly is : " + shelf9.isEcoFriendly);
        System.out.println("The finishType is : " + shelf9.finishType);
        System.out.println("The rating is : " + shelf9.rating);
        System.out.println("The maxLoad is : " + shelf9.maxLoad);
        System.out.println("The isCertified is : " + shelf9.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf9.manufacturingYear);
        System.out.println("The depth is : " + shelf9.depth);
        System.out.println("The isFoldable is : " + shelf9.isFoldable);
        System.out.println("The certificationType is : " + shelf9.certificationType);

        shelf9.shelfBrand = "WoodCraft";
        shelf9.shelfId = 9;
        shelf9.shelfPrice = 950.75;
        shelf9.isAvailable = true;
        shelf9.shelfType = "Wall Mounted";
        shelf9.numberOfShelves = 5;
        shelf9.weight = 25.0;
        shelf9.isPortable = false;
        shelf9.material = "Wood";
        shelf9.warrantyYears = 2;
        shelf9.height = 180.0;
        shelf9.hasGlassDoor = false;
        shelf9.color = "Brown";
        shelf9.stockQuantity = 12;
        shelf9.width = 80.0;
        shelf9.isEcoFriendly = true;
        shelf9.finishType = "Matte";
        shelf9.rating = 4;
        shelf9.maxLoad = 120.0;
        shelf9.isCertified = true;
        shelf9.countryOfOrigin = "India";
        shelf9.manufacturingYear = 2025;
        shelf9.depth = 30.0;
        shelf9.isFoldable = false;
        shelf9.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf9.shelfBrand);
        System.out.println("The shelfId is : " + shelf9.shelfId);
        System.out.println("The shelfPrice is : " + shelf9.shelfPrice);
        System.out.println("The isAvailable is : " + shelf9.isAvailable);
        System.out.println("The shelfType is : " + shelf9.shelfType);
        System.out.println("The numberOfShelves is : " + shelf9.numberOfShelves);
        System.out.println("The weight is : " + shelf9.weight);
        System.out.println("The isPortable is : " + shelf9.isPortable);
        System.out.println("The material is : " + shelf9.material);
        System.out.println("The warrantyYears is : " + shelf9.warrantyYears);
        System.out.println("The height is : " + shelf9.height);
        System.out.println("The hasGlassDoor is : " + shelf9.hasGlassDoor);
        System.out.println("The color is : " + shelf9.color);
        System.out.println("The stockQuantity is : " + shelf9.stockQuantity);
        System.out.println("The width is : " + shelf9.width);
        System.out.println("The isEcoFriendly is : " + shelf9.isEcoFriendly);
        System.out.println("The finishType is : " + shelf9.finishType);
        System.out.println("The rating is : " + shelf9.rating);
        System.out.println("The maxLoad is : " + shelf9.maxLoad);
        System.out.println("The isCertified is : " + shelf9.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf9.manufacturingYear);
        System.out.println("The depth is : " + shelf9.depth);
        System.out.println("The isFoldable is : " + shelf9.isFoldable);
        System.out.println("The certificationType is : " + shelf9.certificationType);


        Bookshelf shelf10 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf10.shelfBrand);
        System.out.println("The shelfId is : " + shelf10.shelfId);
        System.out.println("The shelfPrice is : " + shelf10.shelfPrice);
        System.out.println("The isAvailable is : " + shelf10.isAvailable);
        System.out.println("The shelfType is : " + shelf10.shelfType);
        System.out.println("The numberOfShelves is : " + shelf10.numberOfShelves);
        System.out.println("The weight is : " + shelf10.weight);
        System.out.println("The isPortable is : " + shelf10.isPortable);
        System.out.println("The material is : " + shelf10.material);
        System.out.println("The warrantyYears is : " + shelf10.warrantyYears);
        System.out.println("The height is : " + shelf10.height);
        System.out.println("The hasGlassDoor is : " + shelf10.hasGlassDoor);
        System.out.println("The color is : " + shelf10.color);
        System.out.println("The stockQuantity is : " + shelf10.stockQuantity);
        System.out.println("The width is : " + shelf10.width);
        System.out.println("The isEcoFriendly is : " + shelf10.isEcoFriendly);
        System.out.println("The finishType is : " + shelf10.finishType);
        System.out.println("The rating is : " + shelf10.rating);
        System.out.println("The maxLoad is : " + shelf10.maxLoad);
        System.out.println("The isCertified is : " + shelf10.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf10.manufacturingYear);
        System.out.println("The depth is : " + shelf10.depth);
        System.out.println("The isFoldable is : " + shelf10.isFoldable);
        System.out.println("The certificationType is : " + shelf10.certificationType);

        shelf10.shelfBrand = "WoodCraft";
        shelf10.shelfId = 10;
        shelf10.shelfPrice = 1050.75;
        shelf10.isAvailable = true;
        shelf10.shelfType = "Wall Mounted";
        shelf10.numberOfShelves = 5;
        shelf10.weight = 25.0;
        shelf10.isPortable = false;
        shelf10.material = "Wood";
        shelf10.warrantyYears = 2;
        shelf10.height = 180.0;
        shelf10.hasGlassDoor = false;
        shelf10.color = "Brown";
        shelf10.stockQuantity = 12;
        shelf10.width = 80.0;
        shelf10.isEcoFriendly = true;
        shelf10.finishType = "Matte";
        shelf10.rating = 4;
        shelf10.maxLoad = 120.0;
        shelf10.isCertified = true;
        shelf10.countryOfOrigin = "India";
        shelf10.manufacturingYear = 2025;
        shelf10.depth = 30.0;
        shelf10.isFoldable = false;
        shelf10.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf10.shelfBrand);
        System.out.println("The shelfId is : " + shelf10.shelfId);
        System.out.println("The shelfPrice is : " + shelf10.shelfPrice);
        System.out.println("The isAvailable is : " + shelf10.isAvailable);
        System.out.println("The shelfType is : " + shelf10.shelfType);
        System.out.println("The numberOfShelves is : " + shelf10.numberOfShelves);
        System.out.println("The weight is : " + shelf10.weight);
        System.out.println("The isPortable is : " + shelf10.isPortable);
        System.out.println("The material is : " + shelf10.material);
        System.out.println("The warrantyYears is : " + shelf10.warrantyYears);
        System.out.println("The height is : " + shelf10.height);
        System.out.println("The hasGlassDoor is : " + shelf10.hasGlassDoor);
        System.out.println("The color is : " + shelf10.color);
        System.out.println("The stockQuantity is : " + shelf10.stockQuantity);
        System.out.println("The width is : " + shelf10.width);
        System.out.println("The isEcoFriendly is : " + shelf10.isEcoFriendly);
        System.out.println("The finishType is : " + shelf10.finishType);
        System.out.println("The rating is : " + shelf10.rating);
        System.out.println("The maxLoad is : " + shelf10.maxLoad);
        System.out.println("The isCertified is : " + shelf10.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf10.manufacturingYear);
        System.out.println("The depth is : " + shelf10.depth);
        System.out.println("The isFoldable is : " + shelf10.isFoldable);
        System.out.println("The certificationType is : " + shelf10.certificationType);


        Bookshelf shelf11 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf11.shelfBrand);
        System.out.println("The shelfId is : " + shelf11.shelfId);
        System.out.println("The shelfPrice is : " + shelf11.shelfPrice);
        System.out.println("The isAvailable is : " + shelf11.isAvailable);
        System.out.println("The shelfType is : " + shelf11.shelfType);
        System.out.println("The numberOfShelves is : " + shelf11.numberOfShelves);
        System.out.println("The weight is : " + shelf11.weight);
        System.out.println("The isPortable is : " + shelf11.isPortable);
        System.out.println("The material is : " + shelf11.material);
        System.out.println("The warrantyYears is : " + shelf11.warrantyYears);
        System.out.println("The height is : " + shelf11.height);
        System.out.println("The hasGlassDoor is : " + shelf11.hasGlassDoor);
        System.out.println("The color is : " + shelf11.color);
        System.out.println("The stockQuantity is : " + shelf11.stockQuantity);
        System.out.println("The width is : " + shelf11.width);
        System.out.println("The isEcoFriendly is : " + shelf11.isEcoFriendly);
        System.out.println("The finishType is : " + shelf11.finishType);
        System.out.println("The rating is : " + shelf11.rating);
        System.out.println("The maxLoad is : " + shelf11.maxLoad);
        System.out.println("The isCertified is : " + shelf11.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf11.manufacturingYear);
        System.out.println("The depth is : " + shelf11.depth);
        System.out.println("The isFoldable is : " + shelf11.isFoldable);
        System.out.println("The certificationType is : " + shelf11.certificationType);

        shelf11.shelfBrand = "WoodCraft";
        shelf11.shelfId = 11;
        shelf11.shelfPrice = 1150.75;
        shelf11.isAvailable = true;
        shelf11.shelfType = "Wall Mounted";
        shelf11.numberOfShelves = 5;
        shelf11.weight = 25.0;
        shelf11.isPortable = false;
        shelf11.material = "Wood";
        shelf11.warrantyYears = 2;
        shelf11.height = 180.0;
        shelf11.hasGlassDoor = false;
        shelf11.color = "Brown";
        shelf11.stockQuantity = 12;
        shelf11.width = 80.0;
        shelf11.isEcoFriendly = true;
        shelf11.finishType = "Matte";
        shelf11.rating = 4;
        shelf11.maxLoad = 120.0;
        shelf11.isCertified = true;
        shelf11.countryOfOrigin = "India";
        shelf11.manufacturingYear = 2025;
        shelf11.depth = 30.0;
        shelf11.isFoldable = false;
        shelf11.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf11.shelfBrand);
        System.out.println("The shelfId is : " + shelf11.shelfId);
        System.out.println("The shelfPrice is : " + shelf11.shelfPrice);
        System.out.println("The isAvailable is : " + shelf11.isAvailable);
        System.out.println("The shelfType is : " + shelf11.shelfType);
        System.out.println("The numberOfShelves is : " + shelf11.numberOfShelves);
        System.out.println("The weight is : " + shelf11.weight);
        System.out.println("The isPortable is : " + shelf11.isPortable);
        System.out.println("The material is : " + shelf11.material);
        System.out.println("The warrantyYears is : " + shelf11.warrantyYears);
        System.out.println("The height is : " + shelf11.height);
        System.out.println("The hasGlassDoor is : " + shelf11.hasGlassDoor);
        System.out.println("The color is : " + shelf11.color);
        System.out.println("The stockQuantity is : " + shelf11.stockQuantity);
        System.out.println("The width is : " + shelf11.width);
        System.out.println("The isEcoFriendly is : " + shelf11.isEcoFriendly);
        System.out.println("The finishType is : " + shelf11.finishType);
        System.out.println("The rating is : " + shelf11.rating);
        System.out.println("The maxLoad is : " + shelf11.maxLoad);
        System.out.println("The isCertified is : " + shelf11.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf11.manufacturingYear);
        System.out.println("The depth is : " + shelf11.depth);
        System.out.println("The isFoldable is : " + shelf11.isFoldable);
        System.out.println("The certificationType is : " + shelf11.certificationType);


        Bookshelf shelf12 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf12.shelfBrand);
        System.out.println("The shelfId is : " + shelf12.shelfId);
        System.out.println("The shelfPrice is : " + shelf12.shelfPrice);
        System.out.println("The isAvailable is : " + shelf12.isAvailable);
        System.out.println("The shelfType is : " + shelf12.shelfType);
        System.out.println("The numberOfShelves is : " + shelf12.numberOfShelves);
        System.out.println("The weight is : " + shelf12.weight);
        System.out.println("The isPortable is : " + shelf12.isPortable);
        System.out.println("The material is : " + shelf12.material);
        System.out.println("The warrantyYears is : " + shelf12.warrantyYears);
        System.out.println("The height is : " + shelf12.height);
        System.out.println("The hasGlassDoor is : " + shelf12.hasGlassDoor);
        System.out.println("The color is : " + shelf12.color);
        System.out.println("The stockQuantity is : " + shelf12.stockQuantity);
        System.out.println("The width is : " + shelf12.width);
        System.out.println("The isEcoFriendly is : " + shelf12.isEcoFriendly);
        System.out.println("The finishType is : " + shelf12.finishType);
        System.out.println("The rating is : " + shelf12.rating);
        System.out.println("The maxLoad is : " + shelf12.maxLoad);
        System.out.println("The isCertified is : " + shelf12.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf12.manufacturingYear);
        System.out.println("The depth is : " + shelf12.depth);
        System.out.println("The isFoldable is : " + shelf12.isFoldable);
        System.out.println("The certificationType is : " + shelf12.certificationType);

        shelf12.shelfBrand = "WoodCraft";
        shelf12.shelfId = 12;
        shelf12.shelfPrice = 1250.75;
        shelf12.isAvailable = true;
        shelf12.shelfType = "Wall Mounted";
        shelf12.numberOfShelves = 5;
        shelf12.weight = 25.0;
        shelf12.isPortable = false;
        shelf12.material = "Wood";
        shelf12.warrantyYears = 2;
        shelf12.height = 180.0;
        shelf12.hasGlassDoor = false;
        shelf12.color = "Brown";
        shelf12.stockQuantity = 12;
        shelf12.width = 80.0;
        shelf12.isEcoFriendly = true;
        shelf12.finishType = "Matte";
        shelf12.rating = 4;
        shelf12.maxLoad = 120.0;
        shelf12.isCertified = true;
        shelf12.countryOfOrigin = "India";
        shelf12.manufacturingYear = 2025;
        shelf12.depth = 30.0;
        shelf12.isFoldable = false;
        shelf12.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf12.shelfBrand);
        System.out.println("The shelfId is : " + shelf12.shelfId);
        System.out.println("The shelfPrice is : " + shelf12.shelfPrice);
        System.out.println("The isAvailable is : " + shelf12.isAvailable);
        System.out.println("The shelfType is : " + shelf12.shelfType);
        System.out.println("The numberOfShelves is : " + shelf12.numberOfShelves);
        System.out.println("The weight is : " + shelf12.weight);
        System.out.println("The isPortable is : " + shelf12.isPortable);
        System.out.println("The material is : " + shelf12.material);
        System.out.println("The warrantyYears is : " + shelf12.warrantyYears);
        System.out.println("The height is : " + shelf12.height);
        System.out.println("The hasGlassDoor is : " + shelf12.hasGlassDoor);
        System.out.println("The color is : " + shelf12.color);
        System.out.println("The stockQuantity is : " + shelf12.stockQuantity);
        System.out.println("The width is : " + shelf12.width);
        System.out.println("The isEcoFriendly is : " + shelf12.isEcoFriendly);
        System.out.println("The finishType is : " + shelf12.finishType);
        System.out.println("The rating is : " + shelf12.rating);
        System.out.println("The maxLoad is : " + shelf12.maxLoad);
        System.out.println("The isCertified is : " + shelf12.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf12.manufacturingYear);
        System.out.println("The depth is : " + shelf12.depth);
        System.out.println("The isFoldable is : " + shelf12.isFoldable);
        System.out.println("The certificationType is : " + shelf12.certificationType);


        Bookshelf shelf13 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf13.shelfBrand);
        System.out.println("The shelfId is : " + shelf13.shelfId);
        System.out.println("The shelfPrice is : " + shelf13.shelfPrice);
        System.out.println("The isAvailable is : " + shelf13.isAvailable);
        System.out.println("The shelfType is : " + shelf13.shelfType);
        System.out.println("The numberOfShelves is : " + shelf13.numberOfShelves);
        System.out.println("The weight is : " + shelf13.weight);
        System.out.println("The isPortable is : " + shelf13.isPortable);
        System.out.println("The material is : " + shelf13.material);
        System.out.println("The warrantyYears is : " + shelf13.warrantyYears);
        System.out.println("The height is : " + shelf13.height);
        System.out.println("The hasGlassDoor is : " + shelf13.hasGlassDoor);
        System.out.println("The color is : " + shelf13.color);
        System.out.println("The stockQuantity is : " + shelf13.stockQuantity);
        System.out.println("The width is : " + shelf13.width);
        System.out.println("The isEcoFriendly is : " + shelf13.isEcoFriendly);
        System.out.println("The finishType is : " + shelf13.finishType);
        System.out.println("The rating is : " + shelf13.rating);
        System.out.println("The maxLoad is : " + shelf13.maxLoad);
        System.out.println("The isCertified is : " + shelf13.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf13.manufacturingYear);
        System.out.println("The depth is : " + shelf13.depth);
        System.out.println("The isFoldable is : " + shelf13.isFoldable);
        System.out.println("The certificationType is : " + shelf13.certificationType);

        shelf13.shelfBrand = "WoodCraft";
        shelf13.shelfId = 13;
        shelf13.shelfPrice = 1350.75;
        shelf13.isAvailable = true;
        shelf13.shelfType = "Wall Mounted";
        shelf13.numberOfShelves = 5;
        shelf13.weight = 25.0;
        shelf13.isPortable = false;
        shelf13.material = "Wood";
        shelf13.warrantyYears = 2;
        shelf13.height = 180.0;
        shelf13.hasGlassDoor = false;
        shelf13.color = "Brown";
        shelf13.stockQuantity = 12;
        shelf13.width = 80.0;
        shelf13.isEcoFriendly = true;
        shelf13.finishType = "Matte";
        shelf13.rating = 4;
        shelf13.maxLoad = 120.0;
        shelf13.isCertified = true;
        shelf13.countryOfOrigin = "India";
        shelf13.manufacturingYear = 2025;
        shelf13.depth = 30.0;
        shelf13.isFoldable = false;
        shelf13.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf13.shelfBrand);
        System.out.println("The shelfId is : " + shelf13.shelfId);
        System.out.println("The shelfPrice is : " + shelf13.shelfPrice);
        System.out.println("The isAvailable is : " + shelf13.isAvailable);
        System.out.println("The shelfType is : " + shelf13.shelfType);
        System.out.println("The numberOfShelves is : " + shelf13.numberOfShelves);
        System.out.println("The weight is : " + shelf13.weight);
        System.out.println("The isPortable is : " + shelf13.isPortable);
        System.out.println("The material is : " + shelf13.material);
        System.out.println("The warrantyYears is : " + shelf13.warrantyYears);
        System.out.println("The height is : " + shelf13.height);
        System.out.println("The hasGlassDoor is : " + shelf13.hasGlassDoor);
        System.out.println("The color is : " + shelf13.color);
        System.out.println("The stockQuantity is : " + shelf13.stockQuantity);
        System.out.println("The width is : " + shelf13.width);
        System.out.println("The isEcoFriendly is : " + shelf13.isEcoFriendly);
        System.out.println("The finishType is : " + shelf13.finishType);
        System.out.println("The rating is : " + shelf13.rating);
        System.out.println("The maxLoad is : " + shelf13.maxLoad);
        System.out.println("The isCertified is : " + shelf13.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf13.manufacturingYear);
        System.out.println("The depth is : " + shelf13.depth);
        System.out.println("The isFoldable is : " + shelf13.isFoldable);
        System.out.println("The certificationType is : " + shelf13.certificationType);


        Bookshelf shelf14 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf14.shelfBrand);
        System.out.println("The shelfId is : " + shelf14.shelfId);
        System.out.println("The shelfPrice is : " + shelf14.shelfPrice);
        System.out.println("The isAvailable is : " + shelf14.isAvailable);
        System.out.println("The shelfType is : " + shelf14.shelfType);
        System.out.println("The numberOfShelves is : " + shelf14.numberOfShelves);
        System.out.println("The weight is : " + shelf14.weight);
        System.out.println("The isPortable is : " + shelf14.isPortable);
        System.out.println("The material is : " + shelf14.material);
        System.out.println("The warrantyYears is : " + shelf14.warrantyYears);
        System.out.println("The height is : " + shelf14.height);
        System.out.println("The hasGlassDoor is : " + shelf14.hasGlassDoor);
        System.out.println("The color is : " + shelf14.color);
        System.out.println("The stockQuantity is : " + shelf14.stockQuantity);
        System.out.println("The width is : " + shelf14.width);
        System.out.println("The isEcoFriendly is : " + shelf14.isEcoFriendly);
        System.out.println("The finishType is : " + shelf14.finishType);
        System.out.println("The rating is : " + shelf14.rating);
        System.out.println("The maxLoad is : " + shelf14.maxLoad);
        System.out.println("The isCertified is : " + shelf14.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf14.manufacturingYear);
        System.out.println("The depth is : " + shelf14.depth);
        System.out.println("The isFoldable is : " + shelf14.isFoldable);
        System.out.println("The certificationType is : " + shelf14.certificationType);

        shelf14.shelfBrand = "WoodCraft";
        shelf14.shelfId = 14;
        shelf14.shelfPrice = 1450.75;
        shelf14.isAvailable = true;
        shelf14.shelfType = "Wall Mounted";
        shelf14.numberOfShelves = 5;
        shelf14.weight = 25.0;
        shelf14.isPortable = false;
        shelf14.material = "Wood";
        shelf14.warrantyYears = 2;
        shelf14.height = 180.0;
        shelf14.hasGlassDoor = false;
        shelf14.color = "Brown";
        shelf14.stockQuantity = 12;
        shelf14.width = 80.0;
        shelf14.isEcoFriendly = true;
        shelf14.finishType = "Matte";
        shelf14.rating = 4;
        shelf14.maxLoad = 120.0;
        shelf14.isCertified = true;
        shelf14.countryOfOrigin = "India";
        shelf14.manufacturingYear = 2025;
        shelf14.depth = 30.0;
        shelf14.isFoldable = false;
        shelf14.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf14.shelfBrand);
        System.out.println("The shelfId is : " + shelf14.shelfId);
        System.out.println("The shelfPrice is : " + shelf14.shelfPrice);
        System.out.println("The isAvailable is : " + shelf14.isAvailable);
        System.out.println("The shelfType is : " + shelf14.shelfType);
        System.out.println("The numberOfShelves is : " + shelf14.numberOfShelves);
        System.out.println("The weight is : " + shelf14.weight);
        System.out.println("The isPortable is : " + shelf14.isPortable);
        System.out.println("The material is : " + shelf14.material);
        System.out.println("The warrantyYears is : " + shelf14.warrantyYears);
        System.out.println("The height is : " + shelf14.height);
        System.out.println("The hasGlassDoor is : " + shelf14.hasGlassDoor);
        System.out.println("The color is : " + shelf14.color);
        System.out.println("The stockQuantity is : " + shelf14.stockQuantity);
        System.out.println("The width is : " + shelf14.width);
        System.out.println("The isEcoFriendly is : " + shelf14.isEcoFriendly);
        System.out.println("The finishType is : " + shelf14.finishType);
        System.out.println("The rating is : " + shelf14.rating);
        System.out.println("The maxLoad is : " + shelf14.maxLoad);
        System.out.println("The isCertified is : " + shelf14.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf14.manufacturingYear);
        System.out.println("The depth is : " + shelf14.depth);
        System.out.println("The isFoldable is : " + shelf14.isFoldable);
        System.out.println("The certificationType is : " + shelf14.certificationType);


        Bookshelf shelf15 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf15.shelfBrand);
        System.out.println("The shelfId is : " + shelf15.shelfId);
        System.out.println("The shelfPrice is : " + shelf15.shelfPrice);
        System.out.println("The isAvailable is : " + shelf15.isAvailable);
        System.out.println("The shelfType is : " + shelf15.shelfType);
        System.out.println("The numberOfShelves is : " + shelf15.numberOfShelves);
        System.out.println("The weight is : " + shelf15.weight);
        System.out.println("The isPortable is : " + shelf15.isPortable);
        System.out.println("The material is : " + shelf15.material);
        System.out.println("The warrantyYears is : " + shelf15.warrantyYears);
        System.out.println("The height is : " + shelf15.height);
        System.out.println("The hasGlassDoor is : " + shelf15.hasGlassDoor);
        System.out.println("The color is : " + shelf15.color);
        System.out.println("The stockQuantity is : " + shelf15.stockQuantity);
        System.out.println("The width is : " + shelf15.width);
        System.out.println("The isEcoFriendly is : " + shelf15.isEcoFriendly);
        System.out.println("The finishType is : " + shelf15.finishType);
        System.out.println("The rating is : " + shelf15.rating);
        System.out.println("The maxLoad is : " + shelf15.maxLoad);
        System.out.println("The isCertified is : " + shelf15.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf15.manufacturingYear);
        System.out.println("The depth is : " + shelf15.depth);
        System.out.println("The isFoldable is : " + shelf15.isFoldable);
        System.out.println("The certificationType is : " + shelf15.certificationType);

        shelf15.shelfBrand = "WoodCraft";
        shelf15.shelfId = 15;
        shelf15.shelfPrice = 1550.75;
        shelf15.isAvailable = true;
        shelf15.shelfType = "Wall Mounted";
        shelf15.numberOfShelves = 5;
        shelf15.weight = 25.0;
        shelf15.isPortable = false;
        shelf15.material = "Wood";
        shelf15.warrantyYears = 2;
        shelf15.height = 180.0;
        shelf15.hasGlassDoor = false;
        shelf15.color = "Brown";
        shelf15.stockQuantity = 12;
        shelf15.width = 80.0;
        shelf15.isEcoFriendly = true;
        shelf15.finishType = "Matte";
        shelf15.rating = 4;
        shelf15.maxLoad = 120.0;
        shelf15.isCertified = true;
        shelf15.countryOfOrigin = "India";
        shelf15.manufacturingYear = 2025;
        shelf15.depth = 30.0;
        shelf15.isFoldable = false;
        shelf15.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf15.shelfBrand);
        System.out.println("The shelfId is : " + shelf15.shelfId);
        System.out.println("The shelfPrice is : " + shelf15.shelfPrice);
        System.out.println("The isAvailable is : " + shelf15.isAvailable);
        System.out.println("The shelfType is : " + shelf15.shelfType);
        System.out.println("The numberOfShelves is : " + shelf15.numberOfShelves);
        System.out.println("The weight is : " + shelf15.weight);
        System.out.println("The isPortable is : " + shelf15.isPortable);
        System.out.println("The material is : " + shelf15.material);
        System.out.println("The warrantyYears is : " + shelf15.warrantyYears);
        System.out.println("The height is : " + shelf15.height);
        System.out.println("The hasGlassDoor is : " + shelf15.hasGlassDoor);
        System.out.println("The color is : " + shelf15.color);
        System.out.println("The stockQuantity is : " + shelf15.stockQuantity);
        System.out.println("The width is : " + shelf15.width);
        System.out.println("The isEcoFriendly is : " + shelf15.isEcoFriendly);
        System.out.println("The finishType is : " + shelf15.finishType);
        System.out.println("The rating is : " + shelf15.rating);
        System.out.println("The maxLoad is : " + shelf15.maxLoad);
        System.out.println("The isCertified is : " + shelf15.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf15.manufacturingYear);
        System.out.println("The depth is : " + shelf15.depth);
        System.out.println("The isFoldable is : " + shelf15.isFoldable);
        System.out.println("The certificationType is : " + shelf15.certificationType);


        Bookshelf shelf16 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf16.shelfBrand);
        System.out.println("The shelfId is : " + shelf16.shelfId);
        System.out.println("The shelfPrice is : " + shelf16.shelfPrice);
        System.out.println("The isAvailable is : " + shelf16.isAvailable);
        System.out.println("The shelfType is : " + shelf16.shelfType);
        System.out.println("The numberOfShelves is : " + shelf16.numberOfShelves);
        System.out.println("The weight is : " + shelf16.weight);
        System.out.println("The isPortable is : " + shelf16.isPortable);
        System.out.println("The material is : " + shelf16.material);
        System.out.println("The warrantyYears is : " + shelf16.warrantyYears);
        System.out.println("The height is : " + shelf16.height);
        System.out.println("The hasGlassDoor is : " + shelf16.hasGlassDoor);
        System.out.println("The color is : " + shelf16.color);
        System.out.println("The stockQuantity is : " + shelf16.stockQuantity);
        System.out.println("The width is : " + shelf16.width);
        System.out.println("The isEcoFriendly is : " + shelf16.isEcoFriendly);
        System.out.println("The finishType is : " + shelf16.finishType);
        System.out.println("The rating is : " + shelf16.rating);
        System.out.println("The maxLoad is : " + shelf16.maxLoad);
        System.out.println("The isCertified is : " + shelf16.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf16.manufacturingYear);
        System.out.println("The depth is : " + shelf16.depth);
        System.out.println("The isFoldable is : " + shelf16.isFoldable);
        System.out.println("The certificationType is : " + shelf16.certificationType);

        shelf16.shelfBrand = "WoodCraft";
        shelf16.shelfId = 16;
        shelf16.shelfPrice = 1650.75;
        shelf16.isAvailable = true;
        shelf16.shelfType = "Wall Mounted";
        shelf16.numberOfShelves = 5;
        shelf16.weight = 25.0;
        shelf16.isPortable = false;
        shelf16.material = "Wood";
        shelf16.warrantyYears = 2;
        shelf16.height = 180.0;
        shelf16.hasGlassDoor = false;
        shelf16.color = "Brown";
        shelf16.stockQuantity = 12;
        shelf16.width = 80.0;
        shelf16.isEcoFriendly = true;
        shelf16.finishType = "Matte";
        shelf16.rating = 4;
        shelf16.maxLoad = 120.0;
        shelf16.isCertified = true;
        shelf16.countryOfOrigin = "India";
        shelf16.manufacturingYear = 2025;
        shelf16.depth = 30.0;
        shelf16.isFoldable = false;
        shelf16.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf16.shelfBrand);
        System.out.println("The shelfId is : " + shelf16.shelfId);
        System.out.println("The shelfPrice is : " + shelf16.shelfPrice);
        System.out.println("The isAvailable is : " + shelf16.isAvailable);
        System.out.println("The shelfType is : " + shelf16.shelfType);
        System.out.println("The numberOfShelves is : " + shelf16.numberOfShelves);
        System.out.println("The weight is : " + shelf16.weight);
        System.out.println("The isPortable is : " + shelf16.isPortable);
        System.out.println("The material is : " + shelf16.material);
        System.out.println("The warrantyYears is : " + shelf16.warrantyYears);
        System.out.println("The height is : " + shelf16.height);
        System.out.println("The hasGlassDoor is : " + shelf16.hasGlassDoor);
        System.out.println("The color is : " + shelf16.color);
        System.out.println("The stockQuantity is : " + shelf16.stockQuantity);
        System.out.println("The width is : " + shelf16.width);
        System.out.println("The isEcoFriendly is : " + shelf16.isEcoFriendly);
        System.out.println("The finishType is : " + shelf16.finishType);
        System.out.println("The rating is : " + shelf16.rating);
        System.out.println("The maxLoad is : " + shelf16.maxLoad);
        System.out.println("The isCertified is : " + shelf16.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf16.manufacturingYear);
        System.out.println("The depth is : " + shelf16.depth);
        System.out.println("The isFoldable is : " + shelf16.isFoldable);
        System.out.println("The certificationType is : " + shelf16.certificationType);


        Bookshelf shelf17 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf17.shelfBrand);
        System.out.println("The shelfId is : " + shelf17.shelfId);
        System.out.println("The shelfPrice is : " + shelf17.shelfPrice);
        System.out.println("The isAvailable is : " + shelf17.isAvailable);
        System.out.println("The shelfType is : " + shelf17.shelfType);
        System.out.println("The numberOfShelves is : " + shelf17.numberOfShelves);
        System.out.println("The weight is : " + shelf17.weight);
        System.out.println("The isPortable is : " + shelf17.isPortable);
        System.out.println("The material is : " + shelf17.material);
        System.out.println("The warrantyYears is : " + shelf17.warrantyYears);
        System.out.println("The height is : " + shelf17.height);
        System.out.println("The hasGlassDoor is : " + shelf17.hasGlassDoor);
        System.out.println("The color is : " + shelf17.color);
        System.out.println("The stockQuantity is : " + shelf17.stockQuantity);
        System.out.println("The width is : " + shelf17.width);
        System.out.println("The isEcoFriendly is : " + shelf17.isEcoFriendly);
        System.out.println("The finishType is : " + shelf17.finishType);
        System.out.println("The rating is : " + shelf17.rating);
        System.out.println("The maxLoad is : " + shelf17.maxLoad);
        System.out.println("The isCertified is : " + shelf17.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf17.manufacturingYear);
        System.out.println("The depth is : " + shelf17.depth);
        System.out.println("The isFoldable is : " + shelf17.isFoldable);
        System.out.println("The certificationType is : " + shelf17.certificationType);

        shelf17.shelfBrand = "WoodCraft";
        shelf17.shelfId = 17;
        shelf17.shelfPrice = 1750.75;
        shelf17.isAvailable = true;
        shelf17.shelfType = "Wall Mounted";
        shelf17.numberOfShelves = 5;
        shelf17.weight = 25.0;
        shelf17.isPortable = false;
        shelf17.material = "Wood";
        shelf17.warrantyYears = 2;
        shelf17.height = 180.0;
        shelf17.hasGlassDoor = false;
        shelf17.color = "Brown";
        shelf17.stockQuantity = 12;
        shelf17.width = 80.0;
        shelf17.isEcoFriendly = true;
        shelf17.finishType = "Matte";
        shelf17.rating = 4;
        shelf17.maxLoad = 120.0;
        shelf17.isCertified = true;
        shelf17.countryOfOrigin = "India";
        shelf17.manufacturingYear = 2025;
        shelf17.depth = 30.0;
        shelf17.isFoldable = false;
        shelf17.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf17.shelfBrand);
        System.out.println("The shelfId is : " + shelf17.shelfId);
        System.out.println("The shelfPrice is : " + shelf17.shelfPrice);
        System.out.println("The isAvailable is : " + shelf17.isAvailable);
        System.out.println("The shelfType is : " + shelf17.shelfType);
        System.out.println("The numberOfShelves is : " + shelf17.numberOfShelves);
        System.out.println("The weight is : " + shelf17.weight);
        System.out.println("The isPortable is : " + shelf17.isPortable);
        System.out.println("The material is : " + shelf17.material);
        System.out.println("The warrantyYears is : " + shelf17.warrantyYears);
        System.out.println("The height is : " + shelf17.height);
        System.out.println("The hasGlassDoor is : " + shelf17.hasGlassDoor);
        System.out.println("The color is : " + shelf17.color);
        System.out.println("The stockQuantity is : " + shelf17.stockQuantity);
        System.out.println("The width is : " + shelf17.width);
        System.out.println("The isEcoFriendly is : " + shelf17.isEcoFriendly);
        System.out.println("The finishType is : " + shelf17.finishType);
        System.out.println("The rating is : " + shelf17.rating);
        System.out.println("The maxLoad is : " + shelf17.maxLoad);
        System.out.println("The isCertified is : " + shelf17.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf17.manufacturingYear);
        System.out.println("The depth is : " + shelf17.depth);
        System.out.println("The isFoldable is : " + shelf17.isFoldable);
        System.out.println("The certificationType is : " + shelf17.certificationType);


        Bookshelf shelf18 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf18.shelfBrand);
        System.out.println("The shelfId is : " + shelf18.shelfId);
        System.out.println("The shelfPrice is : " + shelf18.shelfPrice);
        System.out.println("The isAvailable is : " + shelf18.isAvailable);
        System.out.println("The shelfType is : " + shelf18.shelfType);
        System.out.println("The numberOfShelves is : " + shelf18.numberOfShelves);
        System.out.println("The weight is : " + shelf18.weight);
        System.out.println("The isPortable is : " + shelf18.isPortable);
        System.out.println("The material is : " + shelf18.material);
        System.out.println("The warrantyYears is : " + shelf18.warrantyYears);
        System.out.println("The height is : " + shelf18.height);
        System.out.println("The hasGlassDoor is : " + shelf18.hasGlassDoor);
        System.out.println("The color is : " + shelf18.color);
        System.out.println("The stockQuantity is : " + shelf18.stockQuantity);
        System.out.println("The width is : " + shelf18.width);
        System.out.println("The isEcoFriendly is : " + shelf18.isEcoFriendly);
        System.out.println("The finishType is : " + shelf18.finishType);
        System.out.println("The rating is : " + shelf18.rating);
        System.out.println("The maxLoad is : " + shelf18.maxLoad);
        System.out.println("The isCertified is : " + shelf18.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf18.manufacturingYear);
        System.out.println("The depth is : " + shelf18.depth);
        System.out.println("The isFoldable is : " + shelf18.isFoldable);
        System.out.println("The certificationType is : " + shelf18.certificationType);

        shelf18.shelfBrand = "WoodCraft";
        shelf18.shelfId = 18;
        shelf18.shelfPrice = 1850.75;
        shelf18.isAvailable = true;
        shelf18.shelfType = "Wall Mounted";
        shelf18.numberOfShelves = 5;
        shelf18.weight = 25.0;
        shelf18.isPortable = false;
        shelf18.material = "Wood";
        shelf18.warrantyYears = 2;
        shelf18.height = 180.0;
        shelf18.hasGlassDoor = false;
        shelf18.color = "Brown";
        shelf18.stockQuantity = 12;
        shelf18.width = 80.0;
        shelf18.isEcoFriendly = true;
        shelf18.finishType = "Matte";
        shelf18.rating = 4;
        shelf18.maxLoad = 120.0;
        shelf18.isCertified = true;
        shelf18.countryOfOrigin = "India";
        shelf18.manufacturingYear = 2025;
        shelf18.depth = 30.0;
        shelf18.isFoldable = false;
        shelf18.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf18.shelfBrand);
        System.out.println("The shelfId is : " + shelf18.shelfId);
        System.out.println("The shelfPrice is : " + shelf18.shelfPrice);
        System.out.println("The isAvailable is : " + shelf18.isAvailable);
        System.out.println("The shelfType is : " + shelf18.shelfType);
        System.out.println("The numberOfShelves is : " + shelf18.numberOfShelves);
        System.out.println("The weight is : " + shelf18.weight);
        System.out.println("The isPortable is : " + shelf18.isPortable);
        System.out.println("The material is : " + shelf18.material);
        System.out.println("The warrantyYears is : " + shelf18.warrantyYears);
        System.out.println("The height is : " + shelf18.height);
        System.out.println("The hasGlassDoor is : " + shelf18.hasGlassDoor);
        System.out.println("The color is : " + shelf18.color);
        System.out.println("The stockQuantity is : " + shelf18.stockQuantity);
        System.out.println("The width is : " + shelf18.width);
        System.out.println("The isEcoFriendly is : " + shelf18.isEcoFriendly);
        System.out.println("The finishType is : " + shelf18.finishType);
        System.out.println("The rating is : " + shelf18.rating);
        System.out.println("The maxLoad is : " + shelf18.maxLoad);
        System.out.println("The isCertified is : " + shelf18.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf18.manufacturingYear);
        System.out.println("The depth is : " + shelf18.depth);
        System.out.println("The isFoldable is : " + shelf18.isFoldable);
        System.out.println("The certificationType is : " + shelf18.certificationType);


        Bookshelf shelf19 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf19.shelfBrand);
        System.out.println("The shelfId is : " + shelf19.shelfId);
        System.out.println("The shelfPrice is : " + shelf19.shelfPrice);
        System.out.println("The isAvailable is : " + shelf19.isAvailable);
        System.out.println("The shelfType is : " + shelf19.shelfType);
        System.out.println("The numberOfShelves is : " + shelf19.numberOfShelves);
        System.out.println("The weight is : " + shelf19.weight);
        System.out.println("The isPortable is : " + shelf19.isPortable);
        System.out.println("The material is : " + shelf19.material);
        System.out.println("The warrantyYears is : " + shelf19.warrantyYears);
        System.out.println("The height is : " + shelf19.height);
        System.out.println("The hasGlassDoor is : " + shelf19.hasGlassDoor);
        System.out.println("The color is : " + shelf19.color);
        System.out.println("The stockQuantity is : " + shelf19.stockQuantity);
        System.out.println("The width is : " + shelf19.width);
        System.out.println("The isEcoFriendly is : " + shelf19.isEcoFriendly);
        System.out.println("The finishType is : " + shelf19.finishType);
        System.out.println("The rating is : " + shelf19.rating);
        System.out.println("The maxLoad is : " + shelf19.maxLoad);
        System.out.println("The isCertified is : " + shelf19.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf19.manufacturingYear);
        System.out.println("The depth is : " + shelf19.depth);
        System.out.println("The isFoldable is : " + shelf19.isFoldable);
        System.out.println("The certificationType is : " + shelf19.certificationType);

        shelf19.shelfBrand = "WoodCraft";
        shelf19.shelfId = 19;
        shelf19.shelfPrice = 1950.75;
        shelf19.isAvailable = true;
        shelf19.shelfType = "Wall Mounted";
        shelf19.numberOfShelves = 5;
        shelf19.weight = 25.0;
        shelf19.isPortable = false;
        shelf19.material = "Wood";
        shelf19.warrantyYears = 2;
        shelf19.height = 180.0;
        shelf19.hasGlassDoor = false;
        shelf19.color = "Brown";
        shelf19.stockQuantity = 12;
        shelf19.width = 80.0;
        shelf19.isEcoFriendly = true;
        shelf19.finishType = "Matte";
        shelf19.rating = 4;
        shelf19.maxLoad = 120.0;
        shelf19.isCertified = true;
        shelf19.countryOfOrigin = "India";
        shelf19.manufacturingYear = 2025;
        shelf19.depth = 30.0;
        shelf19.isFoldable = false;
        shelf19.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf19.shelfBrand);
        System.out.println("The shelfId is : " + shelf19.shelfId);
        System.out.println("The shelfPrice is : " + shelf19.shelfPrice);
        System.out.println("The isAvailable is : " + shelf19.isAvailable);
        System.out.println("The shelfType is : " + shelf19.shelfType);
        System.out.println("The numberOfShelves is : " + shelf19.numberOfShelves);
        System.out.println("The weight is : " + shelf19.weight);
        System.out.println("The isPortable is : " + shelf19.isPortable);
        System.out.println("The material is : " + shelf19.material);
        System.out.println("The warrantyYears is : " + shelf19.warrantyYears);
        System.out.println("The height is : " + shelf19.height);
        System.out.println("The hasGlassDoor is : " + shelf19.hasGlassDoor);
        System.out.println("The color is : " + shelf19.color);
        System.out.println("The stockQuantity is : " + shelf19.stockQuantity);
        System.out.println("The width is : " + shelf19.width);
        System.out.println("The isEcoFriendly is : " + shelf19.isEcoFriendly);
        System.out.println("The finishType is : " + shelf19.finishType);
        System.out.println("The rating is : " + shelf19.rating);
        System.out.println("The maxLoad is : " + shelf19.maxLoad);
        System.out.println("The isCertified is : " + shelf19.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf19.manufacturingYear);
        System.out.println("The depth is : " + shelf19.depth);
        System.out.println("The isFoldable is : " + shelf19.isFoldable);
        System.out.println("The certificationType is : " + shelf19.certificationType);


        Bookshelf shelf20 = new Bookshelf();

        System.out.println("Before initialization");

        System.out.println("The shelfBrand is : " + shelf20.shelfBrand);
        System.out.println("The shelfId is : " + shelf20.shelfId);
        System.out.println("The shelfPrice is : " + shelf20.shelfPrice);
        System.out.println("The isAvailable is : " + shelf20.isAvailable);
        System.out.println("The shelfType is : " + shelf20.shelfType);
        System.out.println("The numberOfShelves is : " + shelf20.numberOfShelves);
        System.out.println("The weight is : " + shelf20.weight);
        System.out.println("The isPortable is : " + shelf20.isPortable);
        System.out.println("The material is : " + shelf20.material);
        System.out.println("The warrantyYears is : " + shelf20.warrantyYears);
        System.out.println("The height is : " + shelf20.height);
        System.out.println("The hasGlassDoor is : " + shelf20.hasGlassDoor);
        System.out.println("The color is : " + shelf20.color);
        System.out.println("The stockQuantity is : " + shelf20.stockQuantity);
        System.out.println("The width is : " + shelf20.width);
        System.out.println("The isEcoFriendly is : " + shelf20.isEcoFriendly);
        System.out.println("The finishType is : " + shelf20.finishType);
        System.out.println("The rating is : " + shelf20.rating);
        System.out.println("The maxLoad is : " + shelf20.maxLoad);
        System.out.println("The isCertified is : " + shelf20.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf20.manufacturingYear);
        System.out.println("The depth is : " + shelf20.depth);
        System.out.println("The isFoldable is : " + shelf20.isFoldable);
        System.out.println("The certificationType is : " + shelf20.certificationType);

        shelf20.shelfBrand = "WoodCraft";
        shelf20.shelfId = 20;
        shelf20.shelfPrice = 2050.75;
        shelf20.isAvailable = true;
        shelf20.shelfType = "Wall Mounted";
        shelf20.numberOfShelves = 5;
        shelf20.weight = 25.0;
        shelf20.isPortable = false;
        shelf20.material = "Wood";
        shelf20.warrantyYears = 2;
        shelf20.height = 180.0;
        shelf20.hasGlassDoor = false;
        shelf20.color = "Brown";
        shelf20.stockQuantity = 12;
        shelf20.width = 80.0;
        shelf20.isEcoFriendly = true;
        shelf20.finishType = "Matte";
        shelf20.rating = 4;
        shelf20.maxLoad = 120.0;
        shelf20.isCertified = true;
        shelf20.countryOfOrigin = "India";
        shelf20.manufacturingYear = 2025;
        shelf20.depth = 30.0;
        shelf20.isFoldable = false;
        shelf20.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The shelfBrand is : " + shelf20.shelfBrand);
        System.out.println("The shelfId is : " + shelf20.shelfId);
        System.out.println("The shelfPrice is : " + shelf20.shelfPrice);
        System.out.println("The isAvailable is : " + shelf20.isAvailable);
        System.out.println("The shelfType is : " + shelf20.shelfType);
        System.out.println("The numberOfShelves is : " + shelf20.numberOfShelves);
        System.out.println("The weight is : " + shelf20.weight);
        System.out.println("The isPortable is : " + shelf20.isPortable);
        System.out.println("The material is : " + shelf20.material);
        System.out.println("The warrantyYears is : " + shelf20.warrantyYears);
        System.out.println("The height is : " + shelf20.height);
        System.out.println("The hasGlassDoor is : " + shelf20.hasGlassDoor);
        System.out.println("The color is : " + shelf20.color);
        System.out.println("The stockQuantity is : " + shelf20.stockQuantity);
        System.out.println("The width is : " + shelf20.width);
        System.out.println("The isEcoFriendly is : " + shelf20.isEcoFriendly);
        System.out.println("The finishType is : " + shelf20.finishType);
        System.out.println("The rating is : " + shelf20.rating);
        System.out.println("The maxLoad is : " + shelf20.maxLoad);
        System.out.println("The isCertified is : " + shelf20.isCertified);
        System.out.println("The countryOfOrigin is : " + shelf20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + shelf20.manufacturingYear);
        System.out.println("The depth is : " + shelf20.depth);
        System.out.println("The isFoldable is : " + shelf20.isFoldable);
        System.out.println("The certificationType is : " + shelf20.certificationType);


    }
}
