
class BraceletRunner {
    public static void main(String[] args) {
        
        //  Default constructor
        
        Bracelet b1 = new Bracelet();
        b1.material = "Gold";
        b1.style = "Tennis";
        b1.color = "Yellow Gold";
        b1.gemstone = "Diamond";
        b1.length = 7.0;
        b1.weight = 15.5;
        b1.claspType = "Box Clasp";
        b1.price = 2500.00;
        b1.brand = "Cartier";
        b1.isEngraved = false;
        b1.isAdjustable = false;
        b1.hasCharms = false;
        b1.charmCount = 0;
        b1.finish = "Polished";
        b1.origin = "France";
        b1.karat = 18;
        b1.warrantyYears = 5;
        b1.targetGender = "Women";
        b1.collectionName = "Love";
        b1.stockQuantity = 10;

        Bracelet b2 = new Bracelet();
        b2.material = "Silver";
        b2.style = "Charm";
        b2.color = "Silver";
        b2.gemstone = "None";
        b2.length = 7.5;
        b2.weight = 22.0;
        b2.claspType = "Lobster";
        b2.price = 150.00;
        b2.brand = "Pandora";
        b2.isEngraved = false;
        b2.isAdjustable = true;
        b2.hasCharms = true;
        b2.charmCount = 5;
        b2.finish = "Matte";
        b2.origin = "Denmark";
        b2.karat = 0;
        b2.warrantyYears = 1;
        b2.targetGender = "Unisex";
        b2.collectionName = "Moments";
        b2.stockQuantity = 50;

        Bracelet b3 = new Bracelet();
        b3.material = "Leather";
        b3.style = "Cuff";
        b3.color = "Brown";
        b3.gemstone = "None";
        b3.length = 8.0;
        b3.weight = 30.0;
        b3.claspType = "Buckle";
        b3.price = 75.00;
        b3.brand = "Fossil";
        b3.isEngraved = true;
        b3.isAdjustable = true;
        b3.hasCharms = false;
        b3.charmCount = 0;
        b3.finish = "Distressed";
        b3.origin = "USA";
        b3.karat = 0;
        b3.warrantyYears = 2;
        b3.targetGender = "Men";
        b3.collectionName = "Vintage";
        b3.stockQuantity = 120;

        Bracelet b4 = new Bracelet();
        b4.material = "Platinum";
        b4.style = "Bangle";
        b4.color = "Silver";
        b4.gemstone = "Sapphire";
        b4.length = 6.5;
        b4.weight = 40.0;
        b4.claspType = "None";
        b4.price = 5000.00;
        b4.brand = "Tiffany & Co.";
        b4.isEngraved = true;
        b4.isAdjustable = false;
        b4.hasCharms = false;
        b4.charmCount = 0;
        b4.finish = "Polished";
        b4.origin = "USA";
        b4.karat = 0;
        b4.warrantyYears = 10;
        b4.targetGender = "Women";
        b4.collectionName = "T Collection";
        b4.stockQuantity = 5;

        Bracelet b5 = new Bracelet();
        b5.material = "Beads";
        b5.style = "Stretch";
        b5.color = "Multicolor";
        b5.gemstone = "Turquoise";
        b5.length = 7.0;
        b5.weight = 12.0;
        b5.claspType = "None";
        b5.price = 25.00;
        b5.brand = "Local Artisan";
        b5.isEngraved = false;
        b5.isAdjustable = true;
        b5.hasCharms = true;
        b5.charmCount = 1;
        b5.finish = "Natural";
        b5.origin = "Mexico";
        b5.karat = 0;
        b5.warrantyYears = 0;
        b5.targetGender = "Unisex";
        b5.collectionName = "Earth";
        b5.stockQuantity = 200;

        Bracelet b6 = new Bracelet();
        b6.material = "Rose Gold";
        b6.style = "Chain";
        b6.color = "Rose Gold";
        b6.gemstone = "Ruby";
        b6.length = 7.25;
        b6.weight = 10.0;
        b6.claspType = "Spring Ring";
        b6.price = 850.00;
        b6.brand = "Chopard";
        b6.isEngraved = false;
        b6.isAdjustable = false;
        b6.hasCharms = false;
        b6.charmCount = 0;
        b6.finish = "High Shine";
        b6.origin = "Switzerland";
        b6.karat = 14;
        b6.warrantyYears = 3;
        b6.targetGender = "Women";
        b6.collectionName = "Happy Hearts";
        b6.stockQuantity = 15;

        Bracelet b7 = new Bracelet();
        b7.material = "Stainless Steel";
        b7.style = "Link";
        b7.color = "Silver";
        b7.gemstone = "None";
        b7.length = 8.5;
        b7.weight = 55.0;
        b7.claspType = "Fold Over";
        b7.price = 95.00;
        b7.brand = "Diesel";
        b7.isEngraved = true;
        b7.isAdjustable = false;
        b7.hasCharms = false;
        b7.charmCount = 0;
        b7.finish = "Brushed";
        b7.origin = "Italy";
        b7.karat = 0;
        b7.warrantyYears = 2;
        b7.targetGender = "Men";
        b7.collectionName = "Industrial";
        b7.stockQuantity = 80;

        Bracelet b8 = new Bracelet();
        b8.material = "Titanium";
        b8.style = "Magnetic";
        b8.color = "Black";
        b8.gemstone = "None";
        b8.length = 8.0;
        b8.weight = 20.0;
        b8.claspType = "Toggle";
        b8.price = 60.00;
        b8.brand = "Smarter Life";
        b8.isEngraved = false;
        b8.isAdjustable = true;
        b8.hasCharms = false;
        b8.charmCount = 0;
        b8.finish = "Matte Black";
        b8.origin = "China";
        b8.karat = 0;
        b8.warrantyYears = 1;
        b8.targetGender = "Unisex";
        b8.collectionName = "Health";
        b8.stockQuantity = 300;

        Bracelet b9 = new Bracelet();
        b9.material = "Macrame";
        b9.style = "Woven";
        b9.color = "Red";
        b9.gemstone = "Onyx";
        b9.length = 7.0;
        b9.weight = 5.0;
        b9.claspType = "Sliding Knot";
        b9.price = 45.00;
        b9.brand = "Pura Vida";
        b9.isEngraved = false;
        b9.isAdjustable = true;
        b9.hasCharms = true;
        b9.charmCount = 1;
        b9.finish = "Waxed";
        b9.origin = "Costa Rica";
        b9.karat = 0;
        b9.warrantyYears = 0;
        b9.targetGender = "Unisex";
        b9.collectionName = "Original";
        b9.stockQuantity = 500;

        Bracelet b10 = new Bracelet();
        b10.material = "White Gold";
        b10.style = "Bolo";
        b10.color = "White Gold";
        b10.gemstone = "Emerald";
        b10.length = 9.0;
        b10.weight = 8.5;
        b10.claspType = "Slider";
        b10.price = 1200.00;
        b10.brand = "Kay Jewelers";
        b10.isEngraved = false;
        b10.isAdjustable = true;
        b10.hasCharms = false;
        b10.charmCount = 0;
        b10.finish = "Polished";
        b10.origin = "USA";
        b10.karat = 14;
        b10.warrantyYears = 2;
        b10.targetGender = "Women";
        b10.collectionName = "Elegance";
        b10.stockQuantity = 40;

        Bracelet b11 = new Bracelet();
        b11.material = "Brass";
        b11.style = "Cuff";
        b11.color = "Gold";
        b11.gemstone = "Malachite";
        b11.length = 6.0;
        b11.weight = 45.0;
        b11.claspType = "None";
        b11.price = 110.00;
        b11.brand = "Madewell";
        b11.isEngraved = false;
        b11.isAdjustable = true;
        b11.hasCharms = false;
        b11.charmCount = 0;
        b11.finish = "Antiqued";
        b11.origin = "India";
        b11.karat = 0;
        b11.warrantyYears = 1;
        b11.targetGender = "Women";
        b11.collectionName = "Boho";
        b11.stockQuantity = 60;

        Bracelet b12 = new Bracelet();
        b12.material = "Copper";
        b12.style = "Twisted";
        b12.color = "Copper";
        b12.gemstone = "None";
        b12.length = 7.5;
        b12.weight = 35.0;
        b12.claspType = "Hook";
        b12.price = 30.00;
        b12.brand = "Sabona";
        b12.isEngraved = true;
        b12.isAdjustable = false;
        b12.hasCharms = false;
        b12.charmCount = 0;
        b12.finish = "Polished";
        b12.origin = "UK";
        b12.karat = 0;
        b12.warrantyYears = 1;
        b12.targetGender = "Unisex";
        b12.collectionName = "Classic Copper";
        b12.stockQuantity = 150;

        Bracelet b13 = new Bracelet();
        b13.material = "Silicone";
        b13.style = "Band";
        b13.color = "Yellow";
        b13.gemstone = "None";
        b13.length = 8.0;
        b13.weight = 5.0;
        b13.claspType = "None";
        b13.price = 5.00;
        b13.brand = "Live Strong";
        b13.isEngraved = true;
        b13.isAdjustable = false;
        b13.hasCharms = false;
        b13.charmCount = 0;
        b13.finish = "Smooth";
        b13.origin = "China";
        b13.karat = 0;
        b13.warrantyYears = 0;
        b13.targetGender = "Unisex";
        b13.collectionName = "Charity";
        b13.stockQuantity = 1000;

        Bracelet b14 = new Bracelet();
        b14.material = "Paracord";
        b14.style = "Survival";
        b14.color = "Camo";
        b14.gemstone = "None";
        b14.length = 8.5;
        b14.weight = 15.0;
        b14.claspType = "Plastic Buckle";
        b14.price = 15.00;
        b14.brand = "Gerber";
        b14.isEngraved = false;
        b14.isAdjustable = false;
        b14.hasCharms = false;
        b14.charmCount = 0;
        b14.finish = "Braided";
        b14.origin = "USA";
        b14.karat = 0;
        b14.warrantyYears = 1;
        b14.targetGender = "Men";
        b14.collectionName = "Outdoors";
        b14.stockQuantity = 400;

        Bracelet b15 = new Bracelet();
        b15.material = "Wood";
        b15.style = "Beaded";
        b15.color = "Sandalwood";
        b15.gemstone = "None";
        b15.length = 7.0;
        b15.weight = 8.0;
        b15.claspType = "Elastic";
        b15.price = 20.00;
        b15.brand = "Mala Collective";
        b15.isEngraved = false;
        b15.isAdjustable = true;
        b15.hasCharms = true;
        b15.charmCount = 1;
        b15.finish = "Natural";
        b15.origin = "Bali";
        b15.karat = 0;
        b15.warrantyYears = 0;
        b15.targetGender = "Unisex";
        b15.collectionName = "Meditation";
        b15.stockQuantity = 250;

        Bracelet b16 = new Bracelet();
        b16.material = "Gold Plated";
        b16.style = "Rope";
        b16.color = "Gold";
        b16.gemstone = "None";
        b16.length = 7.5;
        b16.weight = 12.0;
        b16.claspType = "Lobster";
        b16.price = 65.00;
        b16.brand = "Mejuri";
        b16.isEngraved = false;
        b16.isAdjustable = false;
        b16.hasCharms = false;
        b16.charmCount = 0;
        b16.finish = "High Polish";
        b16.origin = "Canada";
        b16.karat = 14;
        b16.warrantyYears = 2;
        b16.targetGender = "Women";
        b16.collectionName = "Everyday";
        b16.stockQuantity = 90;

        Bracelet b17 = new Bracelet();
        b17.material = "Ceramic";
        b17.style = "Link";
        b17.color = "White";
        b17.gemstone = "None";
        b17.length = 7.0;
        b17.weight = 25.0;
        b17.claspType = "Butterfly";
        b17.price = 140.00;
        b17.brand = "Bulova";
        b17.isEngraved = false;
        b17.isAdjustable = false;
        b17.hasCharms = false;
        b17.charmCount = 0;
        b17.finish = "Glossy";
        b17.origin = "Japan";
        b17.karat = 0;
        b17.warrantyYears = 3;
        b17.targetGender = "Women";
        b17.collectionName = "Modern";
        b17.stockQuantity = 35;

        Bracelet b18 = new Bracelet();
        b18.material = "Sterling Silver";
        b18.style = "ID Bracelet";
        b18.color = "Silver";
        b18.gemstone = "None";
        b18.length = 8.0;
        b18.weight = 28.0;
        b18.claspType = "Lobster";
        b18.price = 110.00;
        b18.brand = "James Avery";
        b18.isEngraved = true;
        b18.isAdjustable = false;
        b18.hasCharms = false;
        b18.charmCount = 0;
        b18.finish = "Oxidized";
        b18.origin = "USA";
        b18.karat = 0;
        b18.warrantyYears = 5;
        b18.targetGender = "Men";
        b18.collectionName = "Heritage";
        b18.stockQuantity = 75;

        Bracelet b19 = new Bracelet();
        b19.material = "Tungsten";
        b19.style = "Heavy Link";
        b19.color = "Gunmetal";
        b19.gemstone = "Carbon Fiber";
        b19.length = 9.0;
        b19.weight = 80.0;
        b19.claspType = "Fold Over";
        b19.price = 180.00;
        b19.brand = "Triton";
        b19.isEngraved = false;
        b19.isAdjustable = false;
        b19.hasCharms = false;
        b19.charmCount = 0;
        b19.finish = "Brushed";
        b19.origin = "China";
        b19.karat = 0;
        b19.warrantyYears = 10;
        b19.targetGender = "Men";
        b19.collectionName = "Core";
        b19.stockQuantity = 25;

        Bracelet b20 = new Bracelet();
        b20.material = "Pearl";
        b20.style = "Strand";
        b20.color = "Cream";
        b20.gemstone = "Freshwater Pearl";
        b20.length = 7.0;
        b20.weight = 14.0;
        b20.claspType = "Fishhook";
        b20.price = 350.00;
        b20.brand = "Mikimoto";
        b20.isEngraved = false;
        b20.isAdjustable = false;
        b20.hasCharms = false;
        b20.charmCount = 0;
        b20.finish = "Lustrous";
        b20.origin = "Japan";
        b20.karat = 0;
        b20.warrantyYears = 5;
        b20.targetGender = "Women";
        b20.collectionName = "Ocean";
        b20.stockQuantity = 12;

        Bracelet b21 = new Bracelet();
        b21.material = "Nylon";
        b21.style = "Wrap";
        b21.color = "Navy/White";
        b21.gemstone = "None";
        b21.length = 14.0;
        b21.weight = 6.0;
        b21.claspType = "Anchor Anchor";
        b21.price = 50.00;
        b21.brand = "Kiel James Patrick";
        b21.isEngraved = false;
        b21.isAdjustable = true;
        b21.hasCharms = false;
        b21.charmCount = 0;
        b21.finish = "Braided";
        b21.origin = "USA";
        b21.karat = 0;
        b21.warrantyYears = 1;
        b21.targetGender = "Unisex";
        b21.collectionName = "Nautical";
        b21.stockQuantity = 110;

        Bracelet b22 = new Bracelet();
        b22.material = "Glass";
        b22.style = "Lampwork Beaded";
        b22.color = "Multicolor";
        b22.gemstone = "None";
        b22.length = 7.5;
        b22.weight = 18.0;
        b22.claspType = "Toggle";
        b22.price = 40.00;
        b22.brand = "Murano Glass";
        b22.isEngraved = false;
        b22.isAdjustable = false;
        b22.hasCharms = true;
        b22.charmCount = 2;
        b22.finish = "Glossy";
        b22.origin = "Italy";
        b22.karat = 0;
        b22.warrantyYears = 1;
        b22.targetGender = "Women";
        b22.collectionName = "Venice";
        b22.stockQuantity = 45;

        Bracelet b23 = new Bracelet();
        b23.material = "Resin";
        b23.style = "Bangle";
        b23.color = "Tortoiseshell";
        b23.gemstone = "None";
        b23.length = 8.0;
        b23.weight = 22.0;
        b23.claspType = "None";
        b23.price = 55.00;
        b23.brand = "Kenneth Jay Lane";
        b23.isEngraved = false;
        b23.isAdjustable = false;
        b23.hasCharms = false;
        b23.charmCount = 0;
        b23.finish = "Smooth";
        b23.origin = "USA";
        b23.karat = 0;
        b23.warrantyYears = 1;
        b23.targetGender = "Women";
        b23.collectionName = "Safari";
        b23.stockQuantity = 85;

        Bracelet b24 = new Bracelet();
        b24.material = "Gold Filled";
        b24.style = "Paperclip Chain";
        b24.color = "Gold";
        b24.gemstone = "None";
        b24.length = 7.0;
        b24.weight = 9.0;
        b24.claspType = "Lobster";
        b24.price = 80.00;
        b24.brand = "Gorjana";
        b24.isEngraved = false;
        b24.isAdjustable = true;
        b24.hasCharms = false;
        b24.charmCount = 0;
        b24.finish = "Shiny";
        b24.origin = "USA";
        b24.karat = 18;
        b24.warrantyYears = 1;
        b24.targetGender = "Women";
        b24.collectionName = "Layering";
        b24.stockQuantity = 200;

        Bracelet b25 = new Bracelet();
        b25.material = "Diamond";
        b25.style = "Rivière";
        b25.color = "White Gold";
        b25.gemstone = "Diamond";
        b25.length = 6.5;
        b25.weight = 20.0;
        b25.claspType = "Hidden Box";
        b25.price = 15000.00;
        b25.brand = "Harry Winston";
        b25.isEngraved = true;
        b25.isAdjustable = false;
        b25.hasCharms = false;
        b25.charmCount = 0;
        b25.finish = "Brilliant";
        b25.origin = "USA";
        b25.karat = 18;
        b25.warrantyYears = 20;
        b25.targetGender = "Women";
        b25.collectionName = "High Jewelry";
        b25.stockQuantity = 2;

        System.out.println("Bracelet 1: " + b1.brand + " " + b1.style + " | Material: " + b1.material + " | Price: $" + b1.price);
        System.out.println("Bracelet 2: " + b2.brand + " " + b2.style + " | Material: " + b2.material + " | Price: $" + b2.price);
        System.out.println("Bracelet 3: " + b3.brand + " " + b3.style + " | Material: " + b3.material + " | Price: $" + b3.price);
        System.out.println("Bracelet 4: " + b4.brand + " " + b4.style + " | Material: " + b4.material + " | Price: $" + b4.price);
        System.out.println("Bracelet 5: " + b5.brand + " " + b5.style + " | Material: " + b5.material + " | Price: $" + b5.price);
        System.out.println("Bracelet 6: " + b6.brand + " " + b6.style + " | Material: " + b6.material + " | Price: $" + b6.price);
        System.out.println("Bracelet 7: " + b7.brand + " " + b7.style + " | Material: " + b7.material + " | Price: $" + b7.price);
        System.out.println("Bracelet 8: " + b8.brand + " " + b8.style + " | Material: " + b8.material + " | Price: $" + b8.price);
        System.out.println("Bracelet 9: " + b9.brand + " " + b9.style + " | Material: " + b9.material + " | Price: $" + b9.price);
        System.out.println("Bracelet 10: " + b10.brand + " " + b10.style + " | Material: " + b10.material + " | Price: $" + b10.price);
        System.out.println("Bracelet 11: " + b11.brand + " " + b11.style + " | Material: " + b11.material + " | Price: $" + b11.price);
        System.out.println("Bracelet 12: " + b12.brand + " " + b12.style + " | Material: " + b12.material + " | Price: $" + b12.price);
        System.out.println("Bracelet 13: " + b13.brand + " " + b13.style + " | Material: " + b13.material + " | Price: $" + b13.price);
        System.out.println("Bracelet 14: " + b14.brand + " " + b14.style + " | Material: " + b14.material + " | Price: $" + b14.price);
        System.out.println("Bracelet 15: " + b15.brand + " " + b15.style + " | Material: " + b15.material + " | Price: $" + b15.price);
        System.out.println("Bracelet 16: " + b16.brand + " " + b16.style + " | Material: " + b16.material + " | Price: $" + b16.price);
        System.out.println("Bracelet 17: " + b17.brand + " " + b17.style + " | Material: " + b17.material + " | Price: $" + b17.price);
        System.out.println("Bracelet 18: " + b18.brand + " " + b18.style + " | Material: " + b18.material + " | Price: $" + b18.price);
        System.out.println("Bracelet 19: " + b19.brand + " " + b19.style + " | Material: " + b19.material + " | Price: $" + b19.price);
        System.out.println("Bracelet 20: " + b20.brand + " " + b20.style + " | Material: " + b20.material + " | Price: $" + b20.price);
        System.out.println("Bracelet 21: " + b21.brand + " " + b21.style + " | Material: " + b21.material + " | Price: $" + b21.price);
        System.out.println("Bracelet 22: " + b22.brand + " " + b22.style + " | Material: " + b22.material + " | Price: $" + b22.price);
        System.out.println("Bracelet 23: " + b23.brand + " " + b23.style + " | Material: " + b23.material + " | Price: $" + b23.price);
        System.out.println("Bracelet 24: " + b24.brand + " " + b24.style + " | Material: " + b24.material + " | Price: $" + b24.price);
        System.out.println("Bracelet 25: " + b25.brand + " " + b25.style + " | Material: " + b25.material + " | Price: $" + b25.price);

        // Parameterized constructor
        
        Bracelet p1 = new Bracelet("Sterling Silver", "Cuff", "Silver", "None", 6.5, 25.0, "None", 195.00, "David Yurman", true, false, false, 0, "Cable", "USA", 0, 1, "Women", "Cable Classics", 20);
        Bracelet p2 = new Bracelet("14k Gold", "Figaro Chain", "Gold", "None", 8.0, 12.0, "Lobster", 450.00, "Zales", false, false, false, 0, "Polished", "Italy", 14, 2, "Men", "Classics", 50);
        Bracelet p3 = new Bracelet("Leather", "Braided", "Black", "None", 8.5, 18.0, "Magnetic", 65.00, "Tommy Hilfiger", false, false, false, 0, "Matte", "China", 0, 1, "Men", "Casual", 100);
        Bracelet p4 = new Bracelet("Crystal", "Stretch", "Clear", "Swarovski", 7.0, 15.0, "None", 120.00, "Swarovski", false, true, false, 0, "Sparkle", "Austria", 0, 2, "Women", "Angelic", 60);
        Bracelet p5 = new Bracelet("Rose Gold Vermeil", "Beaded", "Rose Gold", "Opal", 7.5, 8.0, "Toggle", 95.00, "Kendra Scott", false, true, true, 1, "Shiny", "USA", 18, 1, "Women", "Elisa", 80);
        Bracelet p6 = new Bracelet("Stainless Steel", "Mesh", "Silver", "None", 7.5, 20.0, "Slide", 45.00, "Daniel Wellington", false, true, false, 0, "Mesh", "Sweden", 0, 2, "Unisex", "Classic", 150);
        Bracelet p7 = new Bracelet("Turquoise", "Heishi", "Blue", "Turquoise", 7.0, 10.0, "Lobster", 85.00, "Chan Luu", false, true, false, 0, "Natural", "Vietnam", 0, 0, "Women", "Summer", 40);
        Bracelet p8 = new Bracelet("Platinum", "Tennis", "Silver", "Diamond", 7.0, 18.0, "Box", 8500.00, "De Beers", true, false, false, 0, "Polished", "UK", 0, 10, "Women", "Aura", 3);
        Bracelet p9 = new Bracelet("Wood", "Mala", "Brown", "Tiger Eye", 7.5, 12.0, "Elastic", 35.00, "DharmaShop", false, true, false, 0, "Smooth", "Nepal", 0, 0, "Unisex", "Zen", 200);
        Bracelet p10 = new Bracelet("Silicon", "Sport", "Red", "None", 8.0, 5.0, "Buckle", 15.00, "Fitbit", false, true, false, 0, "Matte", "China", 0, 1, "Unisex", "Flex", 500);
        Bracelet p11 = new Bracelet("Vermeil", "Paperclip", "Gold", "None", 7.0, 7.0, "Spring Ring", 75.00, "BaubleBar", false, false, true, 3, "Shiny", "USA", 14, 1, "Women", "Essentials", 120);
        Bracelet p12 = new Bracelet("Brass", "Bangle Set", "Gold", "None", 8.0, 40.0, "None", 60.00, "Alex and Ani", false, true, true, 5, "Antiqued", "USA", 0, 1, "Women", "Energy", 300);
        Bracelet p13 = new Bracelet("Titanium", "Link", "Silver", "None", 8.5, 25.0, "Fold Over", 110.00, "Willis Judd", true, false, false, 0, "Brushed", "UK", 0, 2, "Men", "Magnetic", 90);
        Bracelet p14 = new Bracelet("Jade", "Solid Bangle", "Green", "Jade", 7.5, 50.0, "None", 300.00, "Macy's", false, false, false, 0, "Polished", "China", 0, 1, "Women", "Heritage", 20);
        Bracelet p15 = new Bracelet("Enamel", "Hinged", "Orange", "None", 7.0, 35.0, "Hinge", 650.00, "Hermès", false, false, false, 0, "Glossy", "France", 0, 5, "Women", "Clic Clac", 15);
        Bracelet p16 = new Bracelet("Nylon Cord", "Friendship", "Multicolor", "None", 8.0, 3.0, "Tie", 10.00, "Pura Vida", false, true, false, 0, "Woven", "Costa Rica", 0, 0, "Unisex", "Wanderlust", 800);
        Bracelet p17 = new Bracelet("18k Gold", "Cartouche", "Gold", "None", 7.5, 14.0, "Lobster", 900.00, "Nile Gems", true, false, false, 0, "Polished", "Egypt", 18, 3, "Unisex", "Pharaoh", 25);
        Bracelet p18 = new Bracelet("Silver Plated", "Charm", "Silver", "Glass", 7.5, 25.0, "Toggle", 125.00, "Brighton", false, false, true, 8, "Antiqued", "USA", 0, 1, "Women", "Heart", 60);
        Bracelet p19 = new Bracelet("Ceramic", "Link", "Black", "None", 8.5, 30.0, "Butterfly", 150.00, "Rado", false, false, false, 0, "High Tech", "Switzerland", 0, 5, "Men", "True", 40);
        Bracelet p20 = new Bracelet("Pearl", "Double Strand", "White", "Akoya Pearl", 7.0, 28.0, "Pearl Clasp", 850.00, "Blue Nile", false, false, false, 0, "Lustrous", "Japan", 14, 5, "Women", "Bridal", 10);
        Bracelet p21 = new Bracelet("Fabric", "Wrap", "Floral", "None", 15.0, 5.0, "Tie", 20.00, "Liberty London", false, true, false, 0, "Printed", "UK", 0, 0, "Women", "Spring", 150);
        Bracelet p22 = new Bracelet("Copper", "Magnetic Cuff", "Copper", "None", 7.5, 35.0, "None", 40.00, "Sergio Lub", false, true, false, 0, "Brushed", "USA", 0, 1, "Unisex", "Healing", 85);
        Bracelet p23 = new Bracelet("Resin", "Chunky", "Clear", "Gold Flakes", 8.0, 45.0, "None", 55.00, "Anthropologie", false, false, false, 0, "Smooth", "India", 0, 0, "Women", "Statement", 70);
        Bracelet p24 = new Bracelet("Onyx", "Beaded", "Black", "Onyx", 8.0, 15.0, "Elastic", 45.00, "Tateossian", false, true, false, 0, "Matte", "UK", 0, 2, "Men", "London", 55);
        Bracelet p25 = new Bracelet("White Gold", "Bangle", "Silver", "Diamond", 7.0, 22.0, "Push Button", 4200.00, "Bvlgari", true, false, false, 0, "Polished", "Italy", 18, 10, "Women", "B.zero1", 8);

        System.out.println("Param Bracelet 1: " + p1.brand + " " + p1.style + " | Material: " + p1.material + " | Price: $" + p1.price);
        System.out.println("Param Bracelet 2: " + p2.brand + " " + p2.style + " | Material: " + p2.material + " | Price: $" + p2.price);
        System.out.println("Param Bracelet 3: " + p3.brand + " " + p3.style + " | Material: " + p3.material + " | Price: $" + p3.price);
        System.out.println("Param Bracelet 4: " + p4.brand + " " + p4.style + " | Material: " + p4.material + " | Price: $" + p4.price);
        System.out.println("Param Bracelet 5: " + p5.brand + " " + p5.style + " | Material: " + p5.material + " | Price: $" + p5.price);
        System.out.println("Param Bracelet 6: " + p6.brand + " " + p6.style + " | Material: " + p6.material + " | Price: $" + p6.price);
        System.out.println("Param Bracelet 7: " + p7.brand + " " + p7.style + " | Material: " + p7.material + " | Price: $" + p7.price);
        System.out.println("Param Bracelet 8: " + p8.brand + " " + p8.style + " | Material: " + p8.material + " | Price: $" + p8.price);
        System.out.println("Param Bracelet 9: " + p9.brand + " " + p9.style + " | Material: " + p9.material + " | Price: $" + p9.price);
        System.out.println("Param Bracelet 10: " + p10.brand + " " + p10.style + " | Material: " + p10.material + " | Price: $" + p10.price);
        System.out.println("Param Bracelet 11: " + p11.brand + " " + p11.style + " | Material: " + p11.material + " | Price: $" + p11.price);
        System.out.println("Param Bracelet 12: " + p12.brand + " " + p12.style + " | Material: " + p12.material + " | Price: $" + p12.price);
        System.out.println("Param Bracelet 13: " + p13.brand + " " + p13.style + " | Material: " + p13.material + " | Price: $" + p13.price);
        System.out.println("Param Bracelet 14: " + p14.brand + " " + p14.style + " | Material: " + p14.material + " | Price: $" + p14.price);
        System.out.println("Param Bracelet 15: " + p15.brand + " " + p15.style + " | Material: " + p15.material + " | Price: $" + p15.price);
        System.out.println("Param Bracelet 16: " + p16.brand + " " + p16.style + " | Material: " + p16.material + " | Price: $" + p16.price);
        System.out.println("Param Bracelet 17: " + p17.brand + " " + p17.style + " | Material: " + p17.material + " | Price: $" + p17.price);
        System.out.println("Param Bracelet 18: " + p18.brand + " " + p18.style + " | Material: " + p18.material + " | Price: $" + p18.price);
        System.out.println("Param Bracelet 19: " + p19.brand + " " + p19.style + " | Material: " + p19.material + " | Price: $" + p19.price);
        System.out.println("Param Bracelet 20: " + p20.brand + " " + p20.style + " | Material: " + p20.material + " | Price: $" + p20.price);
        System.out.println("Param Bracelet 21: " + p21.brand + " " + p21.style + " | Material: " + p21.material + " | Price: $" + p21.price);
        System.out.println("Param Bracelet 22: " + p22.brand + " " + p22.style + " | Material: " + p22.material + " | Price: $" + p22.price);
        System.out.println("Param Bracelet 23: " + p23.brand + " " + p23.style + " | Material: " + p23.material + " | Price: $" + p23.price);
        System.out.println("Param Bracelet 24: " + p24.brand + " " + p24.style + " | Material: " + p24.material + " | Price: $" + p24.price);
        System.out.println("Param Bracelet 25: " + p25.brand + " " + p25.style + " | Material: " + p25.material + " | Price: $" + p25.price);
    }
}
