
class BucketRunner {
    public static void main(String[] args) {
        
        // Default constructor
        Bucket b1 = new Bucket(); 
        b1.material = "Plastic"; b1.color = "Red"; b1.capacity = 10.0; b1.useCase = "Cleaning"; b1.hasHandle = true;
        Bucket b2 = new Bucket(); 
        b2.material = "Metal"; b2.color = "Silver"; b2.capacity = 15.5; b2.useCase = "Construction"; b2.hasHandle = true;
        Bucket b3 = new Bucket(); 
        b3.material = "Wood"; b3.color = "Brown"; b3.capacity = 5.0; b3.useCase = "Sauna"; b3.hasHandle = false;
        Bucket b4 = new Bucket(); 
        b4.material = "Silicone"; b4.color = "Blue"; b4.capacity = 2.5; b4.useCase = "Beach Toy"; b4.hasHandle = true;
        Bucket b5 = new Bucket();
        b5.material = "Rubber"; b5.color = "Black"; b5.capacity = 20.0; b5.useCase = "Livestock Feeding"; b5.hasHandle = true;
        Bucket b6 = new Bucket(); 
        b6.material = "Galvanized Steel"; b6.color = "Grey"; b6.capacity = 12.0; b6.useCase = "Gardening"; b6.hasHandle = true;
        Bucket b7 = new Bucket(); 
        b7.material = "Canvas"; b7.color = "White"; b7.capacity = 8.0; b7.useCase = "Foraging"; b7.hasHandle = true;
        Bucket b8 = new Bucket(); 
        b8.material = "Tin"; b8.color = "Silver"; b8.capacity = 3.0; b8.useCase = "Decoration"; b8.hasHandle = false;
        Bucket b9 = new Bucket(); 
        b9.material = "Copper"; b9.color = "Copper"; b9.capacity = 4.5; b9.useCase = "Ash Storage"; b9.hasHandle = true;
        Bucket b10 = new Bucket(); 
        b10.material = "PVC"; b10.color = "Green"; b10.capacity = 18.0; b10.useCase = "Plumbing"; b10.hasHandle = false;
        Bucket b11 = new Bucket(); 
        b11.material = "Enamel"; b11.color = "White"; b11.capacity = 6.0; b11.useCase = "Composting"; b11.hasHandle = true;
        Bucket b12 = new Bucket(); 
        b12.material = "Nylon"; b12.color = "Yellow"; b12.capacity = 9.5; b12.useCase = "Car Wash"; b12.hasHandle = true;
        Bucket b13 = new Bucket(); 
        b13.material = "Ceramic"; b13.color = "Blue"; b13.capacity = 1.5; b13.useCase = "Planter"; b13.hasHandle = false;
        Bucket b14 = new Bucket(); 
        b14.material = "Brass"; b14.color = "Gold"; b14.capacity = 5.5; b14.useCase = "Ice Bucket"; b14.hasHandle = true;
        Bucket b15 = new Bucket(); 
        b15.material = "Bamboo"; b15.color = "Natural"; b15.capacity = 7.0; b15.useCase = "Spa"; b15.hasHandle = true;
        Bucket b16 = new Bucket(); 
        b16.material = "Fiberglass"; b16.color = "White"; b16.capacity = 25.0; b16.useCase = "Industrial"; b16.hasHandle = false;
        Bucket b17 = new Bucket(); 
        b17.material = "Aluminum"; b17.color = "Silver"; b17.capacity = 14.0; b17.useCase = "Brewing"; b17.hasHandle = true;
        Bucket b18 = new Bucket(); 
        b18.material = "Polyurethane"; b18.color = "Orange"; b18.capacity = 11.0; b18.useCase = "Paint"; b18.hasHandle = true;
        Bucket b19 = new Bucket(); 
        b19.material = "Glass"; b19.color = "Clear"; b19.capacity = 2.0; b19.useCase = "Centerpiece"; b19.hasHandle = false;
        Bucket b20 = new Bucket(); 
        b20.material = "Cardboard"; b20.color = "Brown"; b20.capacity = 4.0; b20.useCase = "Popcorn"; b20.hasHandle = false;
        Bucket b21 = new Bucket(); 
        b21.material = "Leather"; b21.color = "Tan"; b21.capacity = 3.5; b21.useCase = "Firewood"; b21.hasHandle = true;
        Bucket b22 = new Bucket(); 
        b22.material = "Wicker"; b22.color = "Beige"; b22.capacity = 8.5; b22.useCase = "Wastebasket"; b22.hasHandle = false;
        Bucket b23 = new Bucket(); 
        b23.material = "Stainless Steel"; b23.color = "Silver"; b23.capacity = 16.0; b23.useCase = "Milking"; b23.hasHandle = true;
        Bucket b24 = new Bucket(); 
        b24.material = "Acrylic"; b24.color = "Clear"; b24.capacity = 6.5; b24.useCase = "Wine Chiller"; b24.hasHandle = true;
        Bucket b25 = new Bucket(); 
        b25.material = "Cast Iron"; b25.color = "Black"; b25.capacity = 7.5; b25.useCase = "Coal"; b25.hasHandle = true;

        System.out.println("Bucket  b1 Details : " + b1.material + " | " + b1.color + " | " + b1.capacity + "L | " + b1.useCase + " | Handle: " + b1.hasHandle);
        System.out.println("Bucket b2 Details : " + b2.material + " | " + b2.color + " | " + b2.capacity + "L | " + b2.useCase + " | Handle: " + b2.hasHandle);
        System.out.println("Bucket b3 Details : " + b3.material + " | " + b3.color + " | " + b3.capacity + "L | " + b3.useCase + " | Handle: " + b3.hasHandle);
        System.out.println("Bucket b4 Details : " + b4.material + " | " + b4.color + " | " + b4.capacity + "L | " + b4.useCase + " | Handle: " + b4.hasHandle);
        System.out.println("Bucket b5  Details : " + b5.material + " | " + b5.color + " | " + b5.capacity + "L | " + b5.useCase + " | Handle: " + b5.hasHandle);
        System.out.println("Bucket b6 Details : " + b6.material + " | " + b6.color + " | " + b6.capacity + "L | " + b6.useCase + " | Handle: " + b6.hasHandle);
        System.out.println("Bucket b7 Details : " + b7.material + " | " + b7.color + " | " + b7.capacity + "L | " + b7.useCase + " | Handle: " + b7.hasHandle);
        System.out.println("Bucket b8 Details : " + b8.material + " | " + b8.color + " | " + b8.capacity + "L | " + b8.useCase + " | Handle: " + b8.hasHandle);
        System.out.println("Bucket b9 Details : " + b9.material + " | " + b9.color + " | " + b9.capacity + "L | " + b9.useCase + " | Handle: " + b9.hasHandle);
        System.out.println("Bucket b10 Details : " + b10.material + " | " + b10.color + " | " + b10.capacity + "L | " + b10.useCase + " | Handle: " + b10.hasHandle);
        System.out.println("Bucket b11 Details : " + b11.material + " | " + b11.color + " | " + b11.capacity + "L | " + b11.useCase + " | Handle: " + b11.hasHandle);
        System.out.println("Bucket b12 Details : " + b12.material + " | " + b12.color + " | " + b12.capacity + "L | " + b12.useCase + " | Handle: " + b12.hasHandle);
        System.out.println("Bucket b13 Details : " + b13.material + " | " + b13.color + " | " + b13.capacity + "L | " + b13.useCase + " | Handle: " + b13.hasHandle);
        System.out.println("Bucket b14 Details : " + b14.material + " | " + b14.color + " | " + b14.capacity + "L | " + b14.useCase + " | Handle: " + b14.hasHandle);
        System.out.println("Bucket b15 Details : " + b15.material + " | " + b15.color + " | " + b15.capacity + "L | " + b15.useCase + " | Handle: " + b15.hasHandle);
        System.out.println("Bucket b16 Details : " + b16.material + " | " + b16.color + " | " + b16.capacity + "L | " + b16.useCase + " | Handle: " + b16.hasHandle);
        System.out.println("Bucket b17 Details : " + b17.material + " | " + b17.color + " | " + b17.capacity + "L | " + b17.useCase + " | Handle: " + b17.hasHandle);
        System.out.println("Bucket b18 Details : " + b18.material + " | " + b18.color + " | " + b18.capacity + "L | " + b18.useCase + " | Handle: " + b18.hasHandle);
        System.out.println("Bucket b19 Details : " + b19.material + " | " + b19.color + " | " + b19.capacity + "L | " + b19.useCase + " | Handle: " + b19.hasHandle);
        System.out.println("Bucket b20 Details : " + b20.material + " | " + b20.color + " | " + b20.capacity + "L | " + b20.useCase + " | Handle: " + b20.hasHandle);
        System.out.println("Bucket b21 Details : " + b21.material + " | " + b21.color + " | " + b21.capacity + "L | " + b21.useCase + " | Handle: " + b21.hasHandle);
        System.out.println("Bucket b22 Details : " + b22.material + " | " + b22.color + " | " + b22.capacity + "L | " + b22.useCase + " | Handle: " + b22.hasHandle);
        System.out.println("Bucket b23 Details : " + b23.material + " | " + b23.color + " | " + b23.capacity + "L | " + b23.useCase + " | Handle: " + b23.hasHandle);
        System.out.println("Bucket b24 Details : " + b24.material + " | " + b24.color + " | " + b24.capacity + "L | " + b24.useCase + " | Handle: " + b24.hasHandle);
        System.out.println("Bucket b25 Details : " + b25.material + " | " + b25.color + " | " + b25.capacity + "L | " + b25.useCase + " | Handle: " + b25.hasHandle);

        // parametrized object eterized constructor
        Bucket p1 = new Bucket("HDPE Plastic", "White", 19.0, "Food Storage", true);
        Bucket p2 = new Bucket("Carbon Steel", "Black", 22.5, "Heavy Machinery", true);
        Bucket p3 = new Bucket("Cedar Wood", "Natural", 6.0, "Well Water", true);
        Bucket p4 = new Bucket("Collapsible Silicone", "Pink", 3.0, "Camping", true);
        Bucket p5 = new Bucket("Recycled Tire", "Black", 15.0, "Horse Feed", true);
        Bucket p6 = new Bucket("Zinc Plated", "Silver", 10.0, "Floral Display", false);
        Bucket p7 = new Bucket("Heavy Canvas", "Olive", 12.0, "Tool Carrier", true);
        Bucket p8 = new Bucket("Pewter", "Grey", 2.0, "Antique Display", false);
        Bucket p9 = new Bucket("Bronze", "Bronze", 5.0, "Ritual", true);
        Bucket p10 = new Bucket("Vinyl", "Blue", 25.0, "Pool Chemicals", false);
        Bucket p11 = new Bucket("Porcelain Enamel", "Red", 4.5, "Berry Picking", true);
        Bucket p12 = new Bucket("Mesh Nylon", "Black", 11.0, "Fishing Bait", true);
        Bucket p13 = new Bucket("Terracotta", "Rust", 3.5, "Plant Pot", false);
        Bucket p14 = new Bucket("Polished Brass", "Gold", 8.0, "Hotel Ice", true);
        Bucket p15 = new Bucket("Rattan", "Brown", 9.0, "Laundry", false);
        Bucket p16 = new Bucket("Resin", "Green", 18.5, "Rainwater Collection", false);
        Bucket p17 = new Bucket("Anodized Aluminum", "Red", 13.0, "Maple Syrup", true);
        Bucket p18 = new Bucket("Epoxy", "Clear", 7.0, "Crafts", false);
        Bucket p19 = new Bucket("Crystal", "Transparent", 1.0, "Champagne", true);
        Bucket p20 = new Bucket("Waxed Paper", "White", 5.5, "Fried Chicken", false);
        Bucket p21 = new Bucket("Faux Leather", "Black", 4.0, "Office Trash", false);
        Bucket p22 = new Bucket("Seagrass", "Natural", 10.0, "Blanket Storage", false);
        Bucket p23 = new Bucket("Surgical Steel", "Silver", 12.5, "Medical Use", true);
        Bucket p24 = new Bucket("Polycarbonate", "Clear", 20.0, "Restaurant Prep", true);
        Bucket p25 = new Bucket("Iron", "Rusty", 8.0, "Vintage Decor", true);

        System.out.println("parametrized object  Bucket 1: " + p1.material + " | " + p1.color + " | " + p1.capacity + "L | " + p1.useCase + " | Handle: " + p1.hasHandle);
        System.out.println("parametrized object  Bucket 2: " + p2.material + " | " + p2.color + " | " + p2.capacity + "L | " + p2.useCase + " | Handle: " + p2.hasHandle);
        System.out.println("parametrized object  Bucket 3: " + p3.material + " | " + p3.color + " | " + p3.capacity + "L | " + p3.useCase + " | Handle: " + p3.hasHandle);
        System.out.println("parametrized object  Bucket 4: " + p4.material + " | " + p4.color + " | " + p4.capacity + "L | " + p4.useCase + " | Handle: " + p4.hasHandle);
        System.out.println("parametrized object  Bucket 5: " + p5.material + " | " + p5.color + " | " + p5.capacity + "L | " + p5.useCase + " | Handle: " + p5.hasHandle);
        System.out.println("parametrized object  Bucket 6: " + p6.material + " | " + p6.color + " | " + p6.capacity + "L | " + p6.useCase + " | Handle: " + p6.hasHandle);
        System.out.println("parametrized object  Bucket 7: " + p7.material + " | " + p7.color + " | " + p7.capacity + "L | " + p7.useCase + " | Handle: " + p7.hasHandle);
        System.out.println("parametrized object  Bucket 8: " + p8.material + " | " + p8.color + " | " + p8.capacity + "L | " + p8.useCase + " | Handle: " + p8.hasHandle);
        System.out.println("parametrized object  Bucket 9: " + p9.material + " | " + p9.color + " | " + p9.capacity + "L | " + p9.useCase + " | Handle: " + p9.hasHandle);
        System.out.println("parametrized object  Bucket 10: " + p10.material + " | " + p10.color + " | " + p10.capacity + "L | " + p10.useCase + " | Handle: " + p10.hasHandle);
        System.out.println("parametrized object  Bucket 11: " + p11.material + " | " + p11.color + " | " + p11.capacity + "L | " + p11.useCase + " | Handle: " + p11.hasHandle);
        System.out.println("parametrized object  Bucket 12: " + p12.material + " | " + p12.color + " | " + p12.capacity + "L | " + p12.useCase + " | Handle: " + p12.hasHandle);
        System.out.println("parametrized object  Bucket 13: " + p13.material + " | " + p13.color + " | " + p13.capacity + "L | " + p13.useCase + " | Handle: " + p13.hasHandle);
        System.out.println("parametrized object  Bucket 14: " + p14.material + " | " + p14.color + " | " + p14.capacity + "L | " + p14.useCase + " | Handle: " + p14.hasHandle);
        System.out.println("parametrized object  Bucket 15: " + p15.material + " | " + p15.color + " | " + p15.capacity + "L | " + p15.useCase + " | Handle: " + p15.hasHandle);
        System.out.println("parametrized object  Bucket 16: " + p16.material + " | " + p16.color + " | " + p16.capacity + "L | " + p16.useCase + " | Handle: " + p16.hasHandle);
        System.out.println("parametrized object  Bucket 17: " + p17.material + " | " + p17.color + " | " + p17.capacity + "L | " + p17.useCase + " | Handle: " + p17.hasHandle);
        System.out.println("parametrized object  Bucket 18: " + p18.material + " | " + p18.color + " | " + p18.capacity + "L | " + p18.useCase + " | Handle: " + p18.hasHandle);
        System.out.println("parametrized object  Bucket 19: " + p19.material + " | " + p19.color + " | " + p19.capacity + "L | " + p19.useCase + " | Handle: " + p19.hasHandle);
        System.out.println("parametrized object  Bucket 20: " + p20.material + " | " + p20.color + " | " + p20.capacity + "L | " + p20.useCase + " | Handle: " + p20.hasHandle);
        System.out.println("parametrized object  Bucket 21: " + p21.material + " | " + p21.color + " | " + p21.capacity + "L | " + p21.useCase + " | Handle: " + p21.hasHandle);
        System.out.println("parametrized object  Bucket 22: " + p22.material + " | " + p22.color + " | " + p22.capacity + "L | " + p22.useCase + " | Handle: " + p22.hasHandle);
        System.out.println("parametrized object  Bucket 23: " + p23.material + " | " + p23.color + " | " + p23.capacity + "L | " + p23.useCase + " | Handle: " + p23.hasHandle);
        System.out.println("parametrized object  Bucket 24: " + p24.material + " | " + p24.color + " | " + p24.capacity + "L | " + p24.useCase + " | Handle: " + p24.hasHandle);
        System.out.println("parametrized object  Bucket 25: " + p25.material + " | " + p25.color + " | " + p25.capacity + "L | " + p25.useCase + " | Handle: " + p25.hasHandle);
    }
}
