class CoffeeMakerExecutor {

    public static void main(String[] args) {

        CoffeeMaker maker1 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker1.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker1.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker1.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker1.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker1.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker1.capacityLiters);
        System.out.println("The weight is : " + maker1.weight);
        System.out.println("The hasGrinder is : " + maker1.hasGrinder);
        System.out.println("The material is : " + maker1.material);
        System.out.println("The warrantyYears is : " + maker1.warrantyYears);
        System.out.println("The brewingTime is : " + maker1.brewingTime);
        System.out.println("The hasTimer is : " + maker1.hasTimer);
        System.out.println("The color is : " + maker1.color);
        System.out.println("The stockQuantity is : " + maker1.stockQuantity);
        System.out.println("The powerConsumption is : " + maker1.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker1.isEcoFriendly);
        System.out.println("The filterType is : " + maker1.filterType);
        System.out.println("The rating is : " + maker1.rating);
        System.out.println("The waterTankCapacity is : " + maker1.waterTankCapacity);
        System.out.println("The isCertified is : " + maker1.isCertified);
        System.out.println("The countryOfOrigin is : " + maker1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker1.manufacturingYear);
        System.out.println("The cordLength is : " + maker1.cordLength);
        System.out.println("The supportsSmartControl is : " + maker1.supportsSmartControl);
        System.out.println("The certificationType is : " + maker1.certificationType);

        maker1.coffeeMakerBrand = "BrewMaster";
        maker1.coffeeMakerId = 1;
        maker1.coffeeMakerPrice = 199.50;
        maker1.isAvailable = true;
        maker1.coffeeMakerType = "Automatic";
        maker1.capacityLiters = 1.5;
        maker1.weight = 3.2;
        maker1.hasGrinder = true;
        maker1.material = "Stainless Steel";
        maker1.warrantyYears = 2;
        maker1.brewingTime = 5.0;
        maker1.hasTimer = true;
        maker1.color = "Black";
        maker1.stockQuantity = 22;
        maker1.powerConsumption = 900.0;
        maker1.isEcoFriendly = true;
        maker1.filterType = "Reusable";
        maker1.rating = 4;
        maker1.waterTankCapacity = 1.2;
        maker1.isCertified = true;
        maker1.countryOfOrigin = "Italy";
        maker1.manufacturingYear = 2025;
        maker1.cordLength = 1.0;
        maker1.supportsSmartControl = false;
        maker1.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker1.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker1.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker1.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker1.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker1.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker1.capacityLiters);
        System.out.println("The weight is : " + maker1.weight);
        System.out.println("The hasGrinder is : " + maker1.hasGrinder);
        System.out.println("The material is : " + maker1.material);
        System.out.println("The warrantyYears is : " + maker1.warrantyYears);
        System.out.println("The brewingTime is : " + maker1.brewingTime);
        System.out.println("The hasTimer is : " + maker1.hasTimer);
        System.out.println("The color is : " + maker1.color);
        System.out.println("The stockQuantity is : " + maker1.stockQuantity);
        System.out.println("The powerConsumption is : " + maker1.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker1.isEcoFriendly);
        System.out.println("The filterType is : " + maker1.filterType);
        System.out.println("The rating is : " + maker1.rating);
        System.out.println("The waterTankCapacity is : " + maker1.waterTankCapacity);
        System.out.println("The isCertified is : " + maker1.isCertified);
        System.out.println("The countryOfOrigin is : " + maker1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker1.manufacturingYear);
        System.out.println("The cordLength is : " + maker1.cordLength);
        System.out.println("The supportsSmartControl is : " + maker1.supportsSmartControl);
        System.out.println("The certificationType is : " + maker1.certificationType);


        CoffeeMaker maker2 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker2.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker2.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker2.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker2.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker2.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker2.capacityLiters);
        System.out.println("The weight is : " + maker2.weight);
        System.out.println("The hasGrinder is : " + maker2.hasGrinder);
        System.out.println("The material is : " + maker2.material);
        System.out.println("The warrantyYears is : " + maker2.warrantyYears);
        System.out.println("The brewingTime is : " + maker2.brewingTime);
        System.out.println("The hasTimer is : " + maker2.hasTimer);
        System.out.println("The color is : " + maker2.color);
        System.out.println("The stockQuantity is : " + maker2.stockQuantity);
        System.out.println("The powerConsumption is : " + maker2.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker2.isEcoFriendly);
        System.out.println("The filterType is : " + maker2.filterType);
        System.out.println("The rating is : " + maker2.rating);
        System.out.println("The waterTankCapacity is : " + maker2.waterTankCapacity);
        System.out.println("The isCertified is : " + maker2.isCertified);
        System.out.println("The countryOfOrigin is : " + maker2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker2.manufacturingYear);
        System.out.println("The cordLength is : " + maker2.cordLength);
        System.out.println("The supportsSmartControl is : " + maker2.supportsSmartControl);
        System.out.println("The certificationType is : " + maker2.certificationType);

        maker2.coffeeMakerBrand = "BrewMaster";
        maker2.coffeeMakerId = 2;
        maker2.coffeeMakerPrice = 299.50;
        maker2.isAvailable = true;
        maker2.coffeeMakerType = "Automatic";
        maker2.capacityLiters = 1.5;
        maker2.weight = 3.2;
        maker2.hasGrinder = true;
        maker2.material = "Stainless Steel";
        maker2.warrantyYears = 2;
        maker2.brewingTime = 5.0;
        maker2.hasTimer = true;
        maker2.color = "Black";
        maker2.stockQuantity = 22;
        maker2.powerConsumption = 900.0;
        maker2.isEcoFriendly = true;
        maker2.filterType = "Reusable";
        maker2.rating = 4;
        maker2.waterTankCapacity = 1.2;
        maker2.isCertified = true;
        maker2.countryOfOrigin = "Italy";
        maker2.manufacturingYear = 2025;
        maker2.cordLength = 1.0;
        maker2.supportsSmartControl = false;
        maker2.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker2.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker2.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker2.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker2.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker2.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker2.capacityLiters);
        System.out.println("The weight is : " + maker2.weight);
        System.out.println("The hasGrinder is : " + maker2.hasGrinder);
        System.out.println("The material is : " + maker2.material);
        System.out.println("The warrantyYears is : " + maker2.warrantyYears);
        System.out.println("The brewingTime is : " + maker2.brewingTime);
        System.out.println("The hasTimer is : " + maker2.hasTimer);
        System.out.println("The color is : " + maker2.color);
        System.out.println("The stockQuantity is : " + maker2.stockQuantity);
        System.out.println("The powerConsumption is : " + maker2.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker2.isEcoFriendly);
        System.out.println("The filterType is : " + maker2.filterType);
        System.out.println("The rating is : " + maker2.rating);
        System.out.println("The waterTankCapacity is : " + maker2.waterTankCapacity);
        System.out.println("The isCertified is : " + maker2.isCertified);
        System.out.println("The countryOfOrigin is : " + maker2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker2.manufacturingYear);
        System.out.println("The cordLength is : " + maker2.cordLength);
        System.out.println("The supportsSmartControl is : " + maker2.supportsSmartControl);
        System.out.println("The certificationType is : " + maker2.certificationType);


        CoffeeMaker maker3 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker3.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker3.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker3.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker3.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker3.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker3.capacityLiters);
        System.out.println("The weight is : " + maker3.weight);
        System.out.println("The hasGrinder is : " + maker3.hasGrinder);
        System.out.println("The material is : " + maker3.material);
        System.out.println("The warrantyYears is : " + maker3.warrantyYears);
        System.out.println("The brewingTime is : " + maker3.brewingTime);
        System.out.println("The hasTimer is : " + maker3.hasTimer);
        System.out.println("The color is : " + maker3.color);
        System.out.println("The stockQuantity is : " + maker3.stockQuantity);
        System.out.println("The powerConsumption is : " + maker3.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker3.isEcoFriendly);
        System.out.println("The filterType is : " + maker3.filterType);
        System.out.println("The rating is : " + maker3.rating);
        System.out.println("The waterTankCapacity is : " + maker3.waterTankCapacity);
        System.out.println("The isCertified is : " + maker3.isCertified);
        System.out.println("The countryOfOrigin is : " + maker3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker3.manufacturingYear);
        System.out.println("The cordLength is : " + maker3.cordLength);
        System.out.println("The supportsSmartControl is : " + maker3.supportsSmartControl);
        System.out.println("The certificationType is : " + maker3.certificationType);

        maker3.coffeeMakerBrand = "BrewMaster";
        maker3.coffeeMakerId = 3;
        maker3.coffeeMakerPrice = 399.50;
        maker3.isAvailable = true;
        maker3.coffeeMakerType = "Automatic";
        maker3.capacityLiters = 1.5;
        maker3.weight = 3.2;
        maker3.hasGrinder = true;
        maker3.material = "Stainless Steel";
        maker3.warrantyYears = 2;
        maker3.brewingTime = 5.0;
        maker3.hasTimer = true;
        maker3.color = "Black";
        maker3.stockQuantity = 22;
        maker3.powerConsumption = 900.0;
        maker3.isEcoFriendly = true;
        maker3.filterType = "Reusable";
        maker3.rating = 4;
        maker3.waterTankCapacity = 1.2;
        maker3.isCertified = true;
        maker3.countryOfOrigin = "Italy";
        maker3.manufacturingYear = 2025;
        maker3.cordLength = 1.0;
        maker3.supportsSmartControl = false;
        maker3.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker3.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker3.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker3.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker3.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker3.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker3.capacityLiters);
        System.out.println("The weight is : " + maker3.weight);
        System.out.println("The hasGrinder is : " + maker3.hasGrinder);
        System.out.println("The material is : " + maker3.material);
        System.out.println("The warrantyYears is : " + maker3.warrantyYears);
        System.out.println("The brewingTime is : " + maker3.brewingTime);
        System.out.println("The hasTimer is : " + maker3.hasTimer);
        System.out.println("The color is : " + maker3.color);
        System.out.println("The stockQuantity is : " + maker3.stockQuantity);
        System.out.println("The powerConsumption is : " + maker3.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker3.isEcoFriendly);
        System.out.println("The filterType is : " + maker3.filterType);
        System.out.println("The rating is : " + maker3.rating);
        System.out.println("The waterTankCapacity is : " + maker3.waterTankCapacity);
        System.out.println("The isCertified is : " + maker3.isCertified);
        System.out.println("The countryOfOrigin is : " + maker3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker3.manufacturingYear);
        System.out.println("The cordLength is : " + maker3.cordLength);
        System.out.println("The supportsSmartControl is : " + maker3.supportsSmartControl);
        System.out.println("The certificationType is : " + maker3.certificationType);


        CoffeeMaker maker4 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker4.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker4.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker4.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker4.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker4.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker4.capacityLiters);
        System.out.println("The weight is : " + maker4.weight);
        System.out.println("The hasGrinder is : " + maker4.hasGrinder);
        System.out.println("The material is : " + maker4.material);
        System.out.println("The warrantyYears is : " + maker4.warrantyYears);
        System.out.println("The brewingTime is : " + maker4.brewingTime);
        System.out.println("The hasTimer is : " + maker4.hasTimer);
        System.out.println("The color is : " + maker4.color);
        System.out.println("The stockQuantity is : " + maker4.stockQuantity);
        System.out.println("The powerConsumption is : " + maker4.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker4.isEcoFriendly);
        System.out.println("The filterType is : " + maker4.filterType);
        System.out.println("The rating is : " + maker4.rating);
        System.out.println("The waterTankCapacity is : " + maker4.waterTankCapacity);
        System.out.println("The isCertified is : " + maker4.isCertified);
        System.out.println("The countryOfOrigin is : " + maker4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker4.manufacturingYear);
        System.out.println("The cordLength is : " + maker4.cordLength);
        System.out.println("The supportsSmartControl is : " + maker4.supportsSmartControl);
        System.out.println("The certificationType is : " + maker4.certificationType);

        maker4.coffeeMakerBrand = "BrewMaster";
        maker4.coffeeMakerId = 4;
        maker4.coffeeMakerPrice = 499.50;
        maker4.isAvailable = true;
        maker4.coffeeMakerType = "Automatic";
        maker4.capacityLiters = 1.5;
        maker4.weight = 3.2;
        maker4.hasGrinder = true;
        maker4.material = "Stainless Steel";
        maker4.warrantyYears = 2;
        maker4.brewingTime = 5.0;
        maker4.hasTimer = true;
        maker4.color = "Black";
        maker4.stockQuantity = 22;
        maker4.powerConsumption = 900.0;
        maker4.isEcoFriendly = true;
        maker4.filterType = "Reusable";
        maker4.rating = 4;
        maker4.waterTankCapacity = 1.2;
        maker4.isCertified = true;
        maker4.countryOfOrigin = "Italy";
        maker4.manufacturingYear = 2025;
        maker4.cordLength = 1.0;
        maker4.supportsSmartControl = false;
        maker4.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker4.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker4.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker4.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker4.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker4.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker4.capacityLiters);
        System.out.println("The weight is : " + maker4.weight);
        System.out.println("The hasGrinder is : " + maker4.hasGrinder);
        System.out.println("The material is : " + maker4.material);
        System.out.println("The warrantyYears is : " + maker4.warrantyYears);
        System.out.println("The brewingTime is : " + maker4.brewingTime);
        System.out.println("The hasTimer is : " + maker4.hasTimer);
        System.out.println("The color is : " + maker4.color);
        System.out.println("The stockQuantity is : " + maker4.stockQuantity);
        System.out.println("The powerConsumption is : " + maker4.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker4.isEcoFriendly);
        System.out.println("The filterType is : " + maker4.filterType);
        System.out.println("The rating is : " + maker4.rating);
        System.out.println("The waterTankCapacity is : " + maker4.waterTankCapacity);
        System.out.println("The isCertified is : " + maker4.isCertified);
        System.out.println("The countryOfOrigin is : " + maker4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker4.manufacturingYear);
        System.out.println("The cordLength is : " + maker4.cordLength);
        System.out.println("The supportsSmartControl is : " + maker4.supportsSmartControl);
        System.out.println("The certificationType is : " + maker4.certificationType);


        CoffeeMaker maker5 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker5.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker5.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker5.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker5.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker5.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker5.capacityLiters);
        System.out.println("The weight is : " + maker5.weight);
        System.out.println("The hasGrinder is : " + maker5.hasGrinder);
        System.out.println("The material is : " + maker5.material);
        System.out.println("The warrantyYears is : " + maker5.warrantyYears);
        System.out.println("The brewingTime is : " + maker5.brewingTime);
        System.out.println("The hasTimer is : " + maker5.hasTimer);
        System.out.println("The color is : " + maker5.color);
        System.out.println("The stockQuantity is : " + maker5.stockQuantity);
        System.out.println("The powerConsumption is : " + maker5.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker5.isEcoFriendly);
        System.out.println("The filterType is : " + maker5.filterType);
        System.out.println("The rating is : " + maker5.rating);
        System.out.println("The waterTankCapacity is : " + maker5.waterTankCapacity);
        System.out.println("The isCertified is : " + maker5.isCertified);
        System.out.println("The countryOfOrigin is : " + maker5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker5.manufacturingYear);
        System.out.println("The cordLength is : " + maker5.cordLength);
        System.out.println("The supportsSmartControl is : " + maker5.supportsSmartControl);
        System.out.println("The certificationType is : " + maker5.certificationType);

        maker5.coffeeMakerBrand = "BrewMaster";
        maker5.coffeeMakerId = 5;
        maker5.coffeeMakerPrice = 599.50;
        maker5.isAvailable = true;
        maker5.coffeeMakerType = "Automatic";
        maker5.capacityLiters = 1.5;
        maker5.weight = 3.2;
        maker5.hasGrinder = true;
        maker5.material = "Stainless Steel";
        maker5.warrantyYears = 2;
        maker5.brewingTime = 5.0;
        maker5.hasTimer = true;
        maker5.color = "Black";
        maker5.stockQuantity = 22;
        maker5.powerConsumption = 900.0;
        maker5.isEcoFriendly = true;
        maker5.filterType = "Reusable";
        maker5.rating = 4;
        maker5.waterTankCapacity = 1.2;
        maker5.isCertified = true;
        maker5.countryOfOrigin = "Italy";
        maker5.manufacturingYear = 2025;
        maker5.cordLength = 1.0;
        maker5.supportsSmartControl = false;
        maker5.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker5.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker5.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker5.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker5.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker5.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker5.capacityLiters);
        System.out.println("The weight is : " + maker5.weight);
        System.out.println("The hasGrinder is : " + maker5.hasGrinder);
        System.out.println("The material is : " + maker5.material);
        System.out.println("The warrantyYears is : " + maker5.warrantyYears);
        System.out.println("The brewingTime is : " + maker5.brewingTime);
        System.out.println("The hasTimer is : " + maker5.hasTimer);
        System.out.println("The color is : " + maker5.color);
        System.out.println("The stockQuantity is : " + maker5.stockQuantity);
        System.out.println("The powerConsumption is : " + maker5.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker5.isEcoFriendly);
        System.out.println("The filterType is : " + maker5.filterType);
        System.out.println("The rating is : " + maker5.rating);
        System.out.println("The waterTankCapacity is : " + maker5.waterTankCapacity);
        System.out.println("The isCertified is : " + maker5.isCertified);
        System.out.println("The countryOfOrigin is : " + maker5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker5.manufacturingYear);
        System.out.println("The cordLength is : " + maker5.cordLength);
        System.out.println("The supportsSmartControl is : " + maker5.supportsSmartControl);
        System.out.println("The certificationType is : " + maker5.certificationType);


        CoffeeMaker maker6 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker6.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker6.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker6.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker6.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker6.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker6.capacityLiters);
        System.out.println("The weight is : " + maker6.weight);
        System.out.println("The hasGrinder is : " + maker6.hasGrinder);
        System.out.println("The material is : " + maker6.material);
        System.out.println("The warrantyYears is : " + maker6.warrantyYears);
        System.out.println("The brewingTime is : " + maker6.brewingTime);
        System.out.println("The hasTimer is : " + maker6.hasTimer);
        System.out.println("The color is : " + maker6.color);
        System.out.println("The stockQuantity is : " + maker6.stockQuantity);
        System.out.println("The powerConsumption is : " + maker6.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker6.isEcoFriendly);
        System.out.println("The filterType is : " + maker6.filterType);
        System.out.println("The rating is : " + maker6.rating);
        System.out.println("The waterTankCapacity is : " + maker6.waterTankCapacity);
        System.out.println("The isCertified is : " + maker6.isCertified);
        System.out.println("The countryOfOrigin is : " + maker6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker6.manufacturingYear);
        System.out.println("The cordLength is : " + maker6.cordLength);
        System.out.println("The supportsSmartControl is : " + maker6.supportsSmartControl);
        System.out.println("The certificationType is : " + maker6.certificationType);

        maker6.coffeeMakerBrand = "BrewMaster";
        maker6.coffeeMakerId = 6;
        maker6.coffeeMakerPrice = 699.50;
        maker6.isAvailable = true;
        maker6.coffeeMakerType = "Automatic";
        maker6.capacityLiters = 1.5;
        maker6.weight = 3.2;
        maker6.hasGrinder = true;
        maker6.material = "Stainless Steel";
        maker6.warrantyYears = 2;
        maker6.brewingTime = 5.0;
        maker6.hasTimer = true;
        maker6.color = "Black";
        maker6.stockQuantity = 22;
        maker6.powerConsumption = 900.0;
        maker6.isEcoFriendly = true;
        maker6.filterType = "Reusable";
        maker6.rating = 4;
        maker6.waterTankCapacity = 1.2;
        maker6.isCertified = true;
        maker6.countryOfOrigin = "Italy";
        maker6.manufacturingYear = 2025;
        maker6.cordLength = 1.0;
        maker6.supportsSmartControl = false;
        maker6.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker6.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker6.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker6.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker6.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker6.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker6.capacityLiters);
        System.out.println("The weight is : " + maker6.weight);
        System.out.println("The hasGrinder is : " + maker6.hasGrinder);
        System.out.println("The material is : " + maker6.material);
        System.out.println("The warrantyYears is : " + maker6.warrantyYears);
        System.out.println("The brewingTime is : " + maker6.brewingTime);
        System.out.println("The hasTimer is : " + maker6.hasTimer);
        System.out.println("The color is : " + maker6.color);
        System.out.println("The stockQuantity is : " + maker6.stockQuantity);
        System.out.println("The powerConsumption is : " + maker6.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker6.isEcoFriendly);
        System.out.println("The filterType is : " + maker6.filterType);
        System.out.println("The rating is : " + maker6.rating);
        System.out.println("The waterTankCapacity is : " + maker6.waterTankCapacity);
        System.out.println("The isCertified is : " + maker6.isCertified);
        System.out.println("The countryOfOrigin is : " + maker6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker6.manufacturingYear);
        System.out.println("The cordLength is : " + maker6.cordLength);
        System.out.println("The supportsSmartControl is : " + maker6.supportsSmartControl);
        System.out.println("The certificationType is : " + maker6.certificationType);


        CoffeeMaker maker7 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker7.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker7.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker7.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker7.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker7.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker7.capacityLiters);
        System.out.println("The weight is : " + maker7.weight);
        System.out.println("The hasGrinder is : " + maker7.hasGrinder);
        System.out.println("The material is : " + maker7.material);
        System.out.println("The warrantyYears is : " + maker7.warrantyYears);
        System.out.println("The brewingTime is : " + maker7.brewingTime);
        System.out.println("The hasTimer is : " + maker7.hasTimer);
        System.out.println("The color is : " + maker7.color);
        System.out.println("The stockQuantity is : " + maker7.stockQuantity);
        System.out.println("The powerConsumption is : " + maker7.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker7.isEcoFriendly);
        System.out.println("The filterType is : " + maker7.filterType);
        System.out.println("The rating is : " + maker7.rating);
        System.out.println("The waterTankCapacity is : " + maker7.waterTankCapacity);
        System.out.println("The isCertified is : " + maker7.isCertified);
        System.out.println("The countryOfOrigin is : " + maker7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker7.manufacturingYear);
        System.out.println("The cordLength is : " + maker7.cordLength);
        System.out.println("The supportsSmartControl is : " + maker7.supportsSmartControl);
        System.out.println("The certificationType is : " + maker7.certificationType);

        maker7.coffeeMakerBrand = "BrewMaster";
        maker7.coffeeMakerId = 7;
        maker7.coffeeMakerPrice = 799.50;
        maker7.isAvailable = true;
        maker7.coffeeMakerType = "Automatic";
        maker7.capacityLiters = 1.5;
        maker7.weight = 3.2;
        maker7.hasGrinder = true;
        maker7.material = "Stainless Steel";
        maker7.warrantyYears = 2;
        maker7.brewingTime = 5.0;
        maker7.hasTimer = true;
        maker7.color = "Black";
        maker7.stockQuantity = 22;
        maker7.powerConsumption = 900.0;
        maker7.isEcoFriendly = true;
        maker7.filterType = "Reusable";
        maker7.rating = 4;
        maker7.waterTankCapacity = 1.2;
        maker7.isCertified = true;
        maker7.countryOfOrigin = "Italy";
        maker7.manufacturingYear = 2025;
        maker7.cordLength = 1.0;
        maker7.supportsSmartControl = false;
        maker7.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker7.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker7.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker7.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker7.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker7.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker7.capacityLiters);
        System.out.println("The weight is : " + maker7.weight);
        System.out.println("The hasGrinder is : " + maker7.hasGrinder);
        System.out.println("The material is : " + maker7.material);
        System.out.println("The warrantyYears is : " + maker7.warrantyYears);
        System.out.println("The brewingTime is : " + maker7.brewingTime);
        System.out.println("The hasTimer is : " + maker7.hasTimer);
        System.out.println("The color is : " + maker7.color);
        System.out.println("The stockQuantity is : " + maker7.stockQuantity);
        System.out.println("The powerConsumption is : " + maker7.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker7.isEcoFriendly);
        System.out.println("The filterType is : " + maker7.filterType);
        System.out.println("The rating is : " + maker7.rating);
        System.out.println("The waterTankCapacity is : " + maker7.waterTankCapacity);
        System.out.println("The isCertified is : " + maker7.isCertified);
        System.out.println("The countryOfOrigin is : " + maker7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker7.manufacturingYear);
        System.out.println("The cordLength is : " + maker7.cordLength);
        System.out.println("The supportsSmartControl is : " + maker7.supportsSmartControl);
        System.out.println("The certificationType is : " + maker7.certificationType);


        CoffeeMaker maker8 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker8.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker8.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker8.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker8.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker8.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker8.capacityLiters);
        System.out.println("The weight is : " + maker8.weight);
        System.out.println("The hasGrinder is : " + maker8.hasGrinder);
        System.out.println("The material is : " + maker8.material);
        System.out.println("The warrantyYears is : " + maker8.warrantyYears);
        System.out.println("The brewingTime is : " + maker8.brewingTime);
        System.out.println("The hasTimer is : " + maker8.hasTimer);
        System.out.println("The color is : " + maker8.color);
        System.out.println("The stockQuantity is : " + maker8.stockQuantity);
        System.out.println("The powerConsumption is : " + maker8.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker8.isEcoFriendly);
        System.out.println("The filterType is : " + maker8.filterType);
        System.out.println("The rating is : " + maker8.rating);
        System.out.println("The waterTankCapacity is : " + maker8.waterTankCapacity);
        System.out.println("The isCertified is : " + maker8.isCertified);
        System.out.println("The countryOfOrigin is : " + maker8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker8.manufacturingYear);
        System.out.println("The cordLength is : " + maker8.cordLength);
        System.out.println("The supportsSmartControl is : " + maker8.supportsSmartControl);
        System.out.println("The certificationType is : " + maker8.certificationType);

        maker8.coffeeMakerBrand = "BrewMaster";
        maker8.coffeeMakerId = 8;
        maker8.coffeeMakerPrice = 899.50;
        maker8.isAvailable = true;
        maker8.coffeeMakerType = "Automatic";
        maker8.capacityLiters = 1.5;
        maker8.weight = 3.2;
        maker8.hasGrinder = true;
        maker8.material = "Stainless Steel";
        maker8.warrantyYears = 2;
        maker8.brewingTime = 5.0;
        maker8.hasTimer = true;
        maker8.color = "Black";
        maker8.stockQuantity = 22;
        maker8.powerConsumption = 900.0;
        maker8.isEcoFriendly = true;
        maker8.filterType = "Reusable";
        maker8.rating = 4;
        maker8.waterTankCapacity = 1.2;
        maker8.isCertified = true;
        maker8.countryOfOrigin = "Italy";
        maker8.manufacturingYear = 2025;
        maker8.cordLength = 1.0;
        maker8.supportsSmartControl = false;
        maker8.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker8.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker8.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker8.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker8.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker8.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker8.capacityLiters);
        System.out.println("The weight is : " + maker8.weight);
        System.out.println("The hasGrinder is : " + maker8.hasGrinder);
        System.out.println("The material is : " + maker8.material);
        System.out.println("The warrantyYears is : " + maker8.warrantyYears);
        System.out.println("The brewingTime is : " + maker8.brewingTime);
        System.out.println("The hasTimer is : " + maker8.hasTimer);
        System.out.println("The color is : " + maker8.color);
        System.out.println("The stockQuantity is : " + maker8.stockQuantity);
        System.out.println("The powerConsumption is : " + maker8.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker8.isEcoFriendly);
        System.out.println("The filterType is : " + maker8.filterType);
        System.out.println("The rating is : " + maker8.rating);
        System.out.println("The waterTankCapacity is : " + maker8.waterTankCapacity);
        System.out.println("The isCertified is : " + maker8.isCertified);
        System.out.println("The countryOfOrigin is : " + maker8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker8.manufacturingYear);
        System.out.println("The cordLength is : " + maker8.cordLength);
        System.out.println("The supportsSmartControl is : " + maker8.supportsSmartControl);
        System.out.println("The certificationType is : " + maker8.certificationType);


        CoffeeMaker maker9 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker9.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker9.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker9.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker9.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker9.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker9.capacityLiters);
        System.out.println("The weight is : " + maker9.weight);
        System.out.println("The hasGrinder is : " + maker9.hasGrinder);
        System.out.println("The material is : " + maker9.material);
        System.out.println("The warrantyYears is : " + maker9.warrantyYears);
        System.out.println("The brewingTime is : " + maker9.brewingTime);
        System.out.println("The hasTimer is : " + maker9.hasTimer);
        System.out.println("The color is : " + maker9.color);
        System.out.println("The stockQuantity is : " + maker9.stockQuantity);
        System.out.println("The powerConsumption is : " + maker9.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker9.isEcoFriendly);
        System.out.println("The filterType is : " + maker9.filterType);
        System.out.println("The rating is : " + maker9.rating);
        System.out.println("The waterTankCapacity is : " + maker9.waterTankCapacity);
        System.out.println("The isCertified is : " + maker9.isCertified);
        System.out.println("The countryOfOrigin is : " + maker9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker9.manufacturingYear);
        System.out.println("The cordLength is : " + maker9.cordLength);
        System.out.println("The supportsSmartControl is : " + maker9.supportsSmartControl);
        System.out.println("The certificationType is : " + maker9.certificationType);

        maker9.coffeeMakerBrand = "BrewMaster";
        maker9.coffeeMakerId = 9;
        maker9.coffeeMakerPrice = 999.50;
        maker9.isAvailable = true;
        maker9.coffeeMakerType = "Automatic";
        maker9.capacityLiters = 1.5;
        maker9.weight = 3.2;
        maker9.hasGrinder = true;
        maker9.material = "Stainless Steel";
        maker9.warrantyYears = 2;
        maker9.brewingTime = 5.0;
        maker9.hasTimer = true;
        maker9.color = "Black";
        maker9.stockQuantity = 22;
        maker9.powerConsumption = 900.0;
        maker9.isEcoFriendly = true;
        maker9.filterType = "Reusable";
        maker9.rating = 4;
        maker9.waterTankCapacity = 1.2;
        maker9.isCertified = true;
        maker9.countryOfOrigin = "Italy";
        maker9.manufacturingYear = 2025;
        maker9.cordLength = 1.0;
        maker9.supportsSmartControl = false;
        maker9.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker9.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker9.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker9.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker9.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker9.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker9.capacityLiters);
        System.out.println("The weight is : " + maker9.weight);
        System.out.println("The hasGrinder is : " + maker9.hasGrinder);
        System.out.println("The material is : " + maker9.material);
        System.out.println("The warrantyYears is : " + maker9.warrantyYears);
        System.out.println("The brewingTime is : " + maker9.brewingTime);
        System.out.println("The hasTimer is : " + maker9.hasTimer);
        System.out.println("The color is : " + maker9.color);
        System.out.println("The stockQuantity is : " + maker9.stockQuantity);
        System.out.println("The powerConsumption is : " + maker9.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker9.isEcoFriendly);
        System.out.println("The filterType is : " + maker9.filterType);
        System.out.println("The rating is : " + maker9.rating);
        System.out.println("The waterTankCapacity is : " + maker9.waterTankCapacity);
        System.out.println("The isCertified is : " + maker9.isCertified);
        System.out.println("The countryOfOrigin is : " + maker9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker9.manufacturingYear);
        System.out.println("The cordLength is : " + maker9.cordLength);
        System.out.println("The supportsSmartControl is : " + maker9.supportsSmartControl);
        System.out.println("The certificationType is : " + maker9.certificationType);


        CoffeeMaker maker10 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker10.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker10.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker10.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker10.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker10.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker10.capacityLiters);
        System.out.println("The weight is : " + maker10.weight);
        System.out.println("The hasGrinder is : " + maker10.hasGrinder);
        System.out.println("The material is : " + maker10.material);
        System.out.println("The warrantyYears is : " + maker10.warrantyYears);
        System.out.println("The brewingTime is : " + maker10.brewingTime);
        System.out.println("The hasTimer is : " + maker10.hasTimer);
        System.out.println("The color is : " + maker10.color);
        System.out.println("The stockQuantity is : " + maker10.stockQuantity);
        System.out.println("The powerConsumption is : " + maker10.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker10.isEcoFriendly);
        System.out.println("The filterType is : " + maker10.filterType);
        System.out.println("The rating is : " + maker10.rating);
        System.out.println("The waterTankCapacity is : " + maker10.waterTankCapacity);
        System.out.println("The isCertified is : " + maker10.isCertified);
        System.out.println("The countryOfOrigin is : " + maker10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker10.manufacturingYear);
        System.out.println("The cordLength is : " + maker10.cordLength);
        System.out.println("The supportsSmartControl is : " + maker10.supportsSmartControl);
        System.out.println("The certificationType is : " + maker10.certificationType);

        maker10.coffeeMakerBrand = "BrewMaster";
        maker10.coffeeMakerId = 10;
        maker10.coffeeMakerPrice = 1099.50;
        maker10.isAvailable = true;
        maker10.coffeeMakerType = "Automatic";
        maker10.capacityLiters = 1.5;
        maker10.weight = 3.2;
        maker10.hasGrinder = true;
        maker10.material = "Stainless Steel";
        maker10.warrantyYears = 2;
        maker10.brewingTime = 5.0;
        maker10.hasTimer = true;
        maker10.color = "Black";
        maker10.stockQuantity = 22;
        maker10.powerConsumption = 900.0;
        maker10.isEcoFriendly = true;
        maker10.filterType = "Reusable";
        maker10.rating = 4;
        maker10.waterTankCapacity = 1.2;
        maker10.isCertified = true;
        maker10.countryOfOrigin = "Italy";
        maker10.manufacturingYear = 2025;
        maker10.cordLength = 1.0;
        maker10.supportsSmartControl = false;
        maker10.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker10.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker10.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker10.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker10.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker10.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker10.capacityLiters);
        System.out.println("The weight is : " + maker10.weight);
        System.out.println("The hasGrinder is : " + maker10.hasGrinder);
        System.out.println("The material is : " + maker10.material);
        System.out.println("The warrantyYears is : " + maker10.warrantyYears);
        System.out.println("The brewingTime is : " + maker10.brewingTime);
        System.out.println("The hasTimer is : " + maker10.hasTimer);
        System.out.println("The color is : " + maker10.color);
        System.out.println("The stockQuantity is : " + maker10.stockQuantity);
        System.out.println("The powerConsumption is : " + maker10.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker10.isEcoFriendly);
        System.out.println("The filterType is : " + maker10.filterType);
        System.out.println("The rating is : " + maker10.rating);
        System.out.println("The waterTankCapacity is : " + maker10.waterTankCapacity);
        System.out.println("The isCertified is : " + maker10.isCertified);
        System.out.println("The countryOfOrigin is : " + maker10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker10.manufacturingYear);
        System.out.println("The cordLength is : " + maker10.cordLength);
        System.out.println("The supportsSmartControl is : " + maker10.supportsSmartControl);
        System.out.println("The certificationType is : " + maker10.certificationType);


        CoffeeMaker maker11 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker11.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker11.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker11.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker11.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker11.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker11.capacityLiters);
        System.out.println("The weight is : " + maker11.weight);
        System.out.println("The hasGrinder is : " + maker11.hasGrinder);
        System.out.println("The material is : " + maker11.material);
        System.out.println("The warrantyYears is : " + maker11.warrantyYears);
        System.out.println("The brewingTime is : " + maker11.brewingTime);
        System.out.println("The hasTimer is : " + maker11.hasTimer);
        System.out.println("The color is : " + maker11.color);
        System.out.println("The stockQuantity is : " + maker11.stockQuantity);
        System.out.println("The powerConsumption is : " + maker11.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker11.isEcoFriendly);
        System.out.println("The filterType is : " + maker11.filterType);
        System.out.println("The rating is : " + maker11.rating);
        System.out.println("The waterTankCapacity is : " + maker11.waterTankCapacity);
        System.out.println("The isCertified is : " + maker11.isCertified);
        System.out.println("The countryOfOrigin is : " + maker11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker11.manufacturingYear);
        System.out.println("The cordLength is : " + maker11.cordLength);
        System.out.println("The supportsSmartControl is : " + maker11.supportsSmartControl);
        System.out.println("The certificationType is : " + maker11.certificationType);

        maker11.coffeeMakerBrand = "BrewMaster";
        maker11.coffeeMakerId = 11;
        maker11.coffeeMakerPrice = 1199.50;
        maker11.isAvailable = true;
        maker11.coffeeMakerType = "Automatic";
        maker11.capacityLiters = 1.5;
        maker11.weight = 3.2;
        maker11.hasGrinder = true;
        maker11.material = "Stainless Steel";
        maker11.warrantyYears = 2;
        maker11.brewingTime = 5.0;
        maker11.hasTimer = true;
        maker11.color = "Black";
        maker11.stockQuantity = 22;
        maker11.powerConsumption = 900.0;
        maker11.isEcoFriendly = true;
        maker11.filterType = "Reusable";
        maker11.rating = 4;
        maker11.waterTankCapacity = 1.2;
        maker11.isCertified = true;
        maker11.countryOfOrigin = "Italy";
        maker11.manufacturingYear = 2025;
        maker11.cordLength = 1.0;
        maker11.supportsSmartControl = false;
        maker11.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker11.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker11.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker11.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker11.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker11.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker11.capacityLiters);
        System.out.println("The weight is : " + maker11.weight);
        System.out.println("The hasGrinder is : " + maker11.hasGrinder);
        System.out.println("The material is : " + maker11.material);
        System.out.println("The warrantyYears is : " + maker11.warrantyYears);
        System.out.println("The brewingTime is : " + maker11.brewingTime);
        System.out.println("The hasTimer is : " + maker11.hasTimer);
        System.out.println("The color is : " + maker11.color);
        System.out.println("The stockQuantity is : " + maker11.stockQuantity);
        System.out.println("The powerConsumption is : " + maker11.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker11.isEcoFriendly);
        System.out.println("The filterType is : " + maker11.filterType);
        System.out.println("The rating is : " + maker11.rating);
        System.out.println("The waterTankCapacity is : " + maker11.waterTankCapacity);
        System.out.println("The isCertified is : " + maker11.isCertified);
        System.out.println("The countryOfOrigin is : " + maker11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker11.manufacturingYear);
        System.out.println("The cordLength is : " + maker11.cordLength);
        System.out.println("The supportsSmartControl is : " + maker11.supportsSmartControl);
        System.out.println("The certificationType is : " + maker11.certificationType);


        CoffeeMaker maker12 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker12.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker12.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker12.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker12.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker12.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker12.capacityLiters);
        System.out.println("The weight is : " + maker12.weight);
        System.out.println("The hasGrinder is : " + maker12.hasGrinder);
        System.out.println("The material is : " + maker12.material);
        System.out.println("The warrantyYears is : " + maker12.warrantyYears);
        System.out.println("The brewingTime is : " + maker12.brewingTime);
        System.out.println("The hasTimer is : " + maker12.hasTimer);
        System.out.println("The color is : " + maker12.color);
        System.out.println("The stockQuantity is : " + maker12.stockQuantity);
        System.out.println("The powerConsumption is : " + maker12.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker12.isEcoFriendly);
        System.out.println("The filterType is : " + maker12.filterType);
        System.out.println("The rating is : " + maker12.rating);
        System.out.println("The waterTankCapacity is : " + maker12.waterTankCapacity);
        System.out.println("The isCertified is : " + maker12.isCertified);
        System.out.println("The countryOfOrigin is : " + maker12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker12.manufacturingYear);
        System.out.println("The cordLength is : " + maker12.cordLength);
        System.out.println("The supportsSmartControl is : " + maker12.supportsSmartControl);
        System.out.println("The certificationType is : " + maker12.certificationType);

        maker12.coffeeMakerBrand = "BrewMaster";
        maker12.coffeeMakerId = 12;
        maker12.coffeeMakerPrice = 1299.50;
        maker12.isAvailable = true;
        maker12.coffeeMakerType = "Automatic";
        maker12.capacityLiters = 1.5;
        maker12.weight = 3.2;
        maker12.hasGrinder = true;
        maker12.material = "Stainless Steel";
        maker12.warrantyYears = 2;
        maker12.brewingTime = 5.0;
        maker12.hasTimer = true;
        maker12.color = "Black";
        maker12.stockQuantity = 22;
        maker12.powerConsumption = 900.0;
        maker12.isEcoFriendly = true;
        maker12.filterType = "Reusable";
        maker12.rating = 4;
        maker12.waterTankCapacity = 1.2;
        maker12.isCertified = true;
        maker12.countryOfOrigin = "Italy";
        maker12.manufacturingYear = 2025;
        maker12.cordLength = 1.0;
        maker12.supportsSmartControl = false;
        maker12.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker12.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker12.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker12.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker12.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker12.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker12.capacityLiters);
        System.out.println("The weight is : " + maker12.weight);
        System.out.println("The hasGrinder is : " + maker12.hasGrinder);
        System.out.println("The material is : " + maker12.material);
        System.out.println("The warrantyYears is : " + maker12.warrantyYears);
        System.out.println("The brewingTime is : " + maker12.brewingTime);
        System.out.println("The hasTimer is : " + maker12.hasTimer);
        System.out.println("The color is : " + maker12.color);
        System.out.println("The stockQuantity is : " + maker12.stockQuantity);
        System.out.println("The powerConsumption is : " + maker12.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker12.isEcoFriendly);
        System.out.println("The filterType is : " + maker12.filterType);
        System.out.println("The rating is : " + maker12.rating);
        System.out.println("The waterTankCapacity is : " + maker12.waterTankCapacity);
        System.out.println("The isCertified is : " + maker12.isCertified);
        System.out.println("The countryOfOrigin is : " + maker12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker12.manufacturingYear);
        System.out.println("The cordLength is : " + maker12.cordLength);
        System.out.println("The supportsSmartControl is : " + maker12.supportsSmartControl);
        System.out.println("The certificationType is : " + maker12.certificationType);


        CoffeeMaker maker13 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker13.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker13.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker13.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker13.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker13.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker13.capacityLiters);
        System.out.println("The weight is : " + maker13.weight);
        System.out.println("The hasGrinder is : " + maker13.hasGrinder);
        System.out.println("The material is : " + maker13.material);
        System.out.println("The warrantyYears is : " + maker13.warrantyYears);
        System.out.println("The brewingTime is : " + maker13.brewingTime);
        System.out.println("The hasTimer is : " + maker13.hasTimer);
        System.out.println("The color is : " + maker13.color);
        System.out.println("The stockQuantity is : " + maker13.stockQuantity);
        System.out.println("The powerConsumption is : " + maker13.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker13.isEcoFriendly);
        System.out.println("The filterType is : " + maker13.filterType);
        System.out.println("The rating is : " + maker13.rating);
        System.out.println("The waterTankCapacity is : " + maker13.waterTankCapacity);
        System.out.println("The isCertified is : " + maker13.isCertified);
        System.out.println("The countryOfOrigin is : " + maker13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker13.manufacturingYear);
        System.out.println("The cordLength is : " + maker13.cordLength);
        System.out.println("The supportsSmartControl is : " + maker13.supportsSmartControl);
        System.out.println("The certificationType is : " + maker13.certificationType);

        maker13.coffeeMakerBrand = "BrewMaster";
        maker13.coffeeMakerId = 13;
        maker13.coffeeMakerPrice = 1399.50;
        maker13.isAvailable = true;
        maker13.coffeeMakerType = "Automatic";
        maker13.capacityLiters = 1.5;
        maker13.weight = 3.2;
        maker13.hasGrinder = true;
        maker13.material = "Stainless Steel";
        maker13.warrantyYears = 2;
        maker13.brewingTime = 5.0;
        maker13.hasTimer = true;
        maker13.color = "Black";
        maker13.stockQuantity = 22;
        maker13.powerConsumption = 900.0;
        maker13.isEcoFriendly = true;
        maker13.filterType = "Reusable";
        maker13.rating = 4;
        maker13.waterTankCapacity = 1.2;
        maker13.isCertified = true;
        maker13.countryOfOrigin = "Italy";
        maker13.manufacturingYear = 2025;
        maker13.cordLength = 1.0;
        maker13.supportsSmartControl = false;
        maker13.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker13.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker13.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker13.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker13.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker13.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker13.capacityLiters);
        System.out.println("The weight is : " + maker13.weight);
        System.out.println("The hasGrinder is : " + maker13.hasGrinder);
        System.out.println("The material is : " + maker13.material);
        System.out.println("The warrantyYears is : " + maker13.warrantyYears);
        System.out.println("The brewingTime is : " + maker13.brewingTime);
        System.out.println("The hasTimer is : " + maker13.hasTimer);
        System.out.println("The color is : " + maker13.color);
        System.out.println("The stockQuantity is : " + maker13.stockQuantity);
        System.out.println("The powerConsumption is : " + maker13.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker13.isEcoFriendly);
        System.out.println("The filterType is : " + maker13.filterType);
        System.out.println("The rating is : " + maker13.rating);
        System.out.println("The waterTankCapacity is : " + maker13.waterTankCapacity);
        System.out.println("The isCertified is : " + maker13.isCertified);
        System.out.println("The countryOfOrigin is : " + maker13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker13.manufacturingYear);
        System.out.println("The cordLength is : " + maker13.cordLength);
        System.out.println("The supportsSmartControl is : " + maker13.supportsSmartControl);
        System.out.println("The certificationType is : " + maker13.certificationType);


        CoffeeMaker maker14 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker14.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker14.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker14.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker14.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker14.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker14.capacityLiters);
        System.out.println("The weight is : " + maker14.weight);
        System.out.println("The hasGrinder is : " + maker14.hasGrinder);
        System.out.println("The material is : " + maker14.material);
        System.out.println("The warrantyYears is : " + maker14.warrantyYears);
        System.out.println("The brewingTime is : " + maker14.brewingTime);
        System.out.println("The hasTimer is : " + maker14.hasTimer);
        System.out.println("The color is : " + maker14.color);
        System.out.println("The stockQuantity is : " + maker14.stockQuantity);
        System.out.println("The powerConsumption is : " + maker14.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker14.isEcoFriendly);
        System.out.println("The filterType is : " + maker14.filterType);
        System.out.println("The rating is : " + maker14.rating);
        System.out.println("The waterTankCapacity is : " + maker14.waterTankCapacity);
        System.out.println("The isCertified is : " + maker14.isCertified);
        System.out.println("The countryOfOrigin is : " + maker14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker14.manufacturingYear);
        System.out.println("The cordLength is : " + maker14.cordLength);
        System.out.println("The supportsSmartControl is : " + maker14.supportsSmartControl);
        System.out.println("The certificationType is : " + maker14.certificationType);

        maker14.coffeeMakerBrand = "BrewMaster";
        maker14.coffeeMakerId = 14;
        maker14.coffeeMakerPrice = 1499.50;
        maker14.isAvailable = true;
        maker14.coffeeMakerType = "Automatic";
        maker14.capacityLiters = 1.5;
        maker14.weight = 3.2;
        maker14.hasGrinder = true;
        maker14.material = "Stainless Steel";
        maker14.warrantyYears = 2;
        maker14.brewingTime = 5.0;
        maker14.hasTimer = true;
        maker14.color = "Black";
        maker14.stockQuantity = 22;
        maker14.powerConsumption = 900.0;
        maker14.isEcoFriendly = true;
        maker14.filterType = "Reusable";
        maker14.rating = 4;
        maker14.waterTankCapacity = 1.2;
        maker14.isCertified = true;
        maker14.countryOfOrigin = "Italy";
        maker14.manufacturingYear = 2025;
        maker14.cordLength = 1.0;
        maker14.supportsSmartControl = false;
        maker14.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker14.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker14.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker14.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker14.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker14.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker14.capacityLiters);
        System.out.println("The weight is : " + maker14.weight);
        System.out.println("The hasGrinder is : " + maker14.hasGrinder);
        System.out.println("The material is : " + maker14.material);
        System.out.println("The warrantyYears is : " + maker14.warrantyYears);
        System.out.println("The brewingTime is : " + maker14.brewingTime);
        System.out.println("The hasTimer is : " + maker14.hasTimer);
        System.out.println("The color is : " + maker14.color);
        System.out.println("The stockQuantity is : " + maker14.stockQuantity);
        System.out.println("The powerConsumption is : " + maker14.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker14.isEcoFriendly);
        System.out.println("The filterType is : " + maker14.filterType);
        System.out.println("The rating is : " + maker14.rating);
        System.out.println("The waterTankCapacity is : " + maker14.waterTankCapacity);
        System.out.println("The isCertified is : " + maker14.isCertified);
        System.out.println("The countryOfOrigin is : " + maker14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker14.manufacturingYear);
        System.out.println("The cordLength is : " + maker14.cordLength);
        System.out.println("The supportsSmartControl is : " + maker14.supportsSmartControl);
        System.out.println("The certificationType is : " + maker14.certificationType);


        CoffeeMaker maker15 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker15.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker15.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker15.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker15.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker15.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker15.capacityLiters);
        System.out.println("The weight is : " + maker15.weight);
        System.out.println("The hasGrinder is : " + maker15.hasGrinder);
        System.out.println("The material is : " + maker15.material);
        System.out.println("The warrantyYears is : " + maker15.warrantyYears);
        System.out.println("The brewingTime is : " + maker15.brewingTime);
        System.out.println("The hasTimer is : " + maker15.hasTimer);
        System.out.println("The color is : " + maker15.color);
        System.out.println("The stockQuantity is : " + maker15.stockQuantity);
        System.out.println("The powerConsumption is : " + maker15.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker15.isEcoFriendly);
        System.out.println("The filterType is : " + maker15.filterType);
        System.out.println("The rating is : " + maker15.rating);
        System.out.println("The waterTankCapacity is : " + maker15.waterTankCapacity);
        System.out.println("The isCertified is : " + maker15.isCertified);
        System.out.println("The countryOfOrigin is : " + maker15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker15.manufacturingYear);
        System.out.println("The cordLength is : " + maker15.cordLength);
        System.out.println("The supportsSmartControl is : " + maker15.supportsSmartControl);
        System.out.println("The certificationType is : " + maker15.certificationType);

        maker15.coffeeMakerBrand = "BrewMaster";
        maker15.coffeeMakerId = 15;
        maker15.coffeeMakerPrice = 1599.50;
        maker15.isAvailable = true;
        maker15.coffeeMakerType = "Automatic";
        maker15.capacityLiters = 1.5;
        maker15.weight = 3.2;
        maker15.hasGrinder = true;
        maker15.material = "Stainless Steel";
        maker15.warrantyYears = 2;
        maker15.brewingTime = 5.0;
        maker15.hasTimer = true;
        maker15.color = "Black";
        maker15.stockQuantity = 22;
        maker15.powerConsumption = 900.0;
        maker15.isEcoFriendly = true;
        maker15.filterType = "Reusable";
        maker15.rating = 4;
        maker15.waterTankCapacity = 1.2;
        maker15.isCertified = true;
        maker15.countryOfOrigin = "Italy";
        maker15.manufacturingYear = 2025;
        maker15.cordLength = 1.0;
        maker15.supportsSmartControl = false;
        maker15.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker15.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker15.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker15.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker15.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker15.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker15.capacityLiters);
        System.out.println("The weight is : " + maker15.weight);
        System.out.println("The hasGrinder is : " + maker15.hasGrinder);
        System.out.println("The material is : " + maker15.material);
        System.out.println("The warrantyYears is : " + maker15.warrantyYears);
        System.out.println("The brewingTime is : " + maker15.brewingTime);
        System.out.println("The hasTimer is : " + maker15.hasTimer);
        System.out.println("The color is : " + maker15.color);
        System.out.println("The stockQuantity is : " + maker15.stockQuantity);
        System.out.println("The powerConsumption is : " + maker15.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker15.isEcoFriendly);
        System.out.println("The filterType is : " + maker15.filterType);
        System.out.println("The rating is : " + maker15.rating);
        System.out.println("The waterTankCapacity is : " + maker15.waterTankCapacity);
        System.out.println("The isCertified is : " + maker15.isCertified);
        System.out.println("The countryOfOrigin is : " + maker15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker15.manufacturingYear);
        System.out.println("The cordLength is : " + maker15.cordLength);
        System.out.println("The supportsSmartControl is : " + maker15.supportsSmartControl);
        System.out.println("The certificationType is : " + maker15.certificationType);


        CoffeeMaker maker16 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker16.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker16.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker16.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker16.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker16.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker16.capacityLiters);
        System.out.println("The weight is : " + maker16.weight);
        System.out.println("The hasGrinder is : " + maker16.hasGrinder);
        System.out.println("The material is : " + maker16.material);
        System.out.println("The warrantyYears is : " + maker16.warrantyYears);
        System.out.println("The brewingTime is : " + maker16.brewingTime);
        System.out.println("The hasTimer is : " + maker16.hasTimer);
        System.out.println("The color is : " + maker16.color);
        System.out.println("The stockQuantity is : " + maker16.stockQuantity);
        System.out.println("The powerConsumption is : " + maker16.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker16.isEcoFriendly);
        System.out.println("The filterType is : " + maker16.filterType);
        System.out.println("The rating is : " + maker16.rating);
        System.out.println("The waterTankCapacity is : " + maker16.waterTankCapacity);
        System.out.println("The isCertified is : " + maker16.isCertified);
        System.out.println("The countryOfOrigin is : " + maker16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker16.manufacturingYear);
        System.out.println("The cordLength is : " + maker16.cordLength);
        System.out.println("The supportsSmartControl is : " + maker16.supportsSmartControl);
        System.out.println("The certificationType is : " + maker16.certificationType);

        maker16.coffeeMakerBrand = "BrewMaster";
        maker16.coffeeMakerId = 16;
        maker16.coffeeMakerPrice = 1699.50;
        maker16.isAvailable = true;
        maker16.coffeeMakerType = "Automatic";
        maker16.capacityLiters = 1.5;
        maker16.weight = 3.2;
        maker16.hasGrinder = true;
        maker16.material = "Stainless Steel";
        maker16.warrantyYears = 2;
        maker16.brewingTime = 5.0;
        maker16.hasTimer = true;
        maker16.color = "Black";
        maker16.stockQuantity = 22;
        maker16.powerConsumption = 900.0;
        maker16.isEcoFriendly = true;
        maker16.filterType = "Reusable";
        maker16.rating = 4;
        maker16.waterTankCapacity = 1.2;
        maker16.isCertified = true;
        maker16.countryOfOrigin = "Italy";
        maker16.manufacturingYear = 2025;
        maker16.cordLength = 1.0;
        maker16.supportsSmartControl = false;
        maker16.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker16.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker16.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker16.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker16.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker16.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker16.capacityLiters);
        System.out.println("The weight is : " + maker16.weight);
        System.out.println("The hasGrinder is : " + maker16.hasGrinder);
        System.out.println("The material is : " + maker16.material);
        System.out.println("The warrantyYears is : " + maker16.warrantyYears);
        System.out.println("The brewingTime is : " + maker16.brewingTime);
        System.out.println("The hasTimer is : " + maker16.hasTimer);
        System.out.println("The color is : " + maker16.color);
        System.out.println("The stockQuantity is : " + maker16.stockQuantity);
        System.out.println("The powerConsumption is : " + maker16.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker16.isEcoFriendly);
        System.out.println("The filterType is : " + maker16.filterType);
        System.out.println("The rating is : " + maker16.rating);
        System.out.println("The waterTankCapacity is : " + maker16.waterTankCapacity);
        System.out.println("The isCertified is : " + maker16.isCertified);
        System.out.println("The countryOfOrigin is : " + maker16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker16.manufacturingYear);
        System.out.println("The cordLength is : " + maker16.cordLength);
        System.out.println("The supportsSmartControl is : " + maker16.supportsSmartControl);
        System.out.println("The certificationType is : " + maker16.certificationType);


        CoffeeMaker maker17 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker17.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker17.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker17.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker17.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker17.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker17.capacityLiters);
        System.out.println("The weight is : " + maker17.weight);
        System.out.println("The hasGrinder is : " + maker17.hasGrinder);
        System.out.println("The material is : " + maker17.material);
        System.out.println("The warrantyYears is : " + maker17.warrantyYears);
        System.out.println("The brewingTime is : " + maker17.brewingTime);
        System.out.println("The hasTimer is : " + maker17.hasTimer);
        System.out.println("The color is : " + maker17.color);
        System.out.println("The stockQuantity is : " + maker17.stockQuantity);
        System.out.println("The powerConsumption is : " + maker17.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker17.isEcoFriendly);
        System.out.println("The filterType is : " + maker17.filterType);
        System.out.println("The rating is : " + maker17.rating);
        System.out.println("The waterTankCapacity is : " + maker17.waterTankCapacity);
        System.out.println("The isCertified is : " + maker17.isCertified);
        System.out.println("The countryOfOrigin is : " + maker17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker17.manufacturingYear);
        System.out.println("The cordLength is : " + maker17.cordLength);
        System.out.println("The supportsSmartControl is : " + maker17.supportsSmartControl);
        System.out.println("The certificationType is : " + maker17.certificationType);

        maker17.coffeeMakerBrand = "BrewMaster";
        maker17.coffeeMakerId = 17;
        maker17.coffeeMakerPrice = 1799.50;
        maker17.isAvailable = true;
        maker17.coffeeMakerType = "Automatic";
        maker17.capacityLiters = 1.5;
        maker17.weight = 3.2;
        maker17.hasGrinder = true;
        maker17.material = "Stainless Steel";
        maker17.warrantyYears = 2;
        maker17.brewingTime = 5.0;
        maker17.hasTimer = true;
        maker17.color = "Black";
        maker17.stockQuantity = 22;
        maker17.powerConsumption = 900.0;
        maker17.isEcoFriendly = true;
        maker17.filterType = "Reusable";
        maker17.rating = 4;
        maker17.waterTankCapacity = 1.2;
        maker17.isCertified = true;
        maker17.countryOfOrigin = "Italy";
        maker17.manufacturingYear = 2025;
        maker17.cordLength = 1.0;
        maker17.supportsSmartControl = false;
        maker17.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker17.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker17.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker17.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker17.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker17.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker17.capacityLiters);
        System.out.println("The weight is : " + maker17.weight);
        System.out.println("The hasGrinder is : " + maker17.hasGrinder);
        System.out.println("The material is : " + maker17.material);
        System.out.println("The warrantyYears is : " + maker17.warrantyYears);
        System.out.println("The brewingTime is : " + maker17.brewingTime);
        System.out.println("The hasTimer is : " + maker17.hasTimer);
        System.out.println("The color is : " + maker17.color);
        System.out.println("The stockQuantity is : " + maker17.stockQuantity);
        System.out.println("The powerConsumption is : " + maker17.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker17.isEcoFriendly);
        System.out.println("The filterType is : " + maker17.filterType);
        System.out.println("The rating is : " + maker17.rating);
        System.out.println("The waterTankCapacity is : " + maker17.waterTankCapacity);
        System.out.println("The isCertified is : " + maker17.isCertified);
        System.out.println("The countryOfOrigin is : " + maker17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker17.manufacturingYear);
        System.out.println("The cordLength is : " + maker17.cordLength);
        System.out.println("The supportsSmartControl is : " + maker17.supportsSmartControl);
        System.out.println("The certificationType is : " + maker17.certificationType);


        CoffeeMaker maker18 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker18.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker18.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker18.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker18.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker18.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker18.capacityLiters);
        System.out.println("The weight is : " + maker18.weight);
        System.out.println("The hasGrinder is : " + maker18.hasGrinder);
        System.out.println("The material is : " + maker18.material);
        System.out.println("The warrantyYears is : " + maker18.warrantyYears);
        System.out.println("The brewingTime is : " + maker18.brewingTime);
        System.out.println("The hasTimer is : " + maker18.hasTimer);
        System.out.println("The color is : " + maker18.color);
        System.out.println("The stockQuantity is : " + maker18.stockQuantity);
        System.out.println("The powerConsumption is : " + maker18.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker18.isEcoFriendly);
        System.out.println("The filterType is : " + maker18.filterType);
        System.out.println("The rating is : " + maker18.rating);
        System.out.println("The waterTankCapacity is : " + maker18.waterTankCapacity);
        System.out.println("The isCertified is : " + maker18.isCertified);
        System.out.println("The countryOfOrigin is : " + maker18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker18.manufacturingYear);
        System.out.println("The cordLength is : " + maker18.cordLength);
        System.out.println("The supportsSmartControl is : " + maker18.supportsSmartControl);
        System.out.println("The certificationType is : " + maker18.certificationType);

        maker18.coffeeMakerBrand = "BrewMaster";
        maker18.coffeeMakerId = 18;
        maker18.coffeeMakerPrice = 1899.50;
        maker18.isAvailable = true;
        maker18.coffeeMakerType = "Automatic";
        maker18.capacityLiters = 1.5;
        maker18.weight = 3.2;
        maker18.hasGrinder = true;
        maker18.material = "Stainless Steel";
        maker18.warrantyYears = 2;
        maker18.brewingTime = 5.0;
        maker18.hasTimer = true;
        maker18.color = "Black";
        maker18.stockQuantity = 22;
        maker18.powerConsumption = 900.0;
        maker18.isEcoFriendly = true;
        maker18.filterType = "Reusable";
        maker18.rating = 4;
        maker18.waterTankCapacity = 1.2;
        maker18.isCertified = true;
        maker18.countryOfOrigin = "Italy";
        maker18.manufacturingYear = 2025;
        maker18.cordLength = 1.0;
        maker18.supportsSmartControl = false;
        maker18.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker18.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker18.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker18.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker18.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker18.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker18.capacityLiters);
        System.out.println("The weight is : " + maker18.weight);
        System.out.println("The hasGrinder is : " + maker18.hasGrinder);
        System.out.println("The material is : " + maker18.material);
        System.out.println("The warrantyYears is : " + maker18.warrantyYears);
        System.out.println("The brewingTime is : " + maker18.brewingTime);
        System.out.println("The hasTimer is : " + maker18.hasTimer);
        System.out.println("The color is : " + maker18.color);
        System.out.println("The stockQuantity is : " + maker18.stockQuantity);
        System.out.println("The powerConsumption is : " + maker18.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker18.isEcoFriendly);
        System.out.println("The filterType is : " + maker18.filterType);
        System.out.println("The rating is : " + maker18.rating);
        System.out.println("The waterTankCapacity is : " + maker18.waterTankCapacity);
        System.out.println("The isCertified is : " + maker18.isCertified);
        System.out.println("The countryOfOrigin is : " + maker18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker18.manufacturingYear);
        System.out.println("The cordLength is : " + maker18.cordLength);
        System.out.println("The supportsSmartControl is : " + maker18.supportsSmartControl);
        System.out.println("The certificationType is : " + maker18.certificationType);


        CoffeeMaker maker19 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker19.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker19.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker19.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker19.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker19.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker19.capacityLiters);
        System.out.println("The weight is : " + maker19.weight);
        System.out.println("The hasGrinder is : " + maker19.hasGrinder);
        System.out.println("The material is : " + maker19.material);
        System.out.println("The warrantyYears is : " + maker19.warrantyYears);
        System.out.println("The brewingTime is : " + maker19.brewingTime);
        System.out.println("The hasTimer is : " + maker19.hasTimer);
        System.out.println("The color is : " + maker19.color);
        System.out.println("The stockQuantity is : " + maker19.stockQuantity);
        System.out.println("The powerConsumption is : " + maker19.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker19.isEcoFriendly);
        System.out.println("The filterType is : " + maker19.filterType);
        System.out.println("The rating is : " + maker19.rating);
        System.out.println("The waterTankCapacity is : " + maker19.waterTankCapacity);
        System.out.println("The isCertified is : " + maker19.isCertified);
        System.out.println("The countryOfOrigin is : " + maker19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker19.manufacturingYear);
        System.out.println("The cordLength is : " + maker19.cordLength);
        System.out.println("The supportsSmartControl is : " + maker19.supportsSmartControl);
        System.out.println("The certificationType is : " + maker19.certificationType);

        maker19.coffeeMakerBrand = "BrewMaster";
        maker19.coffeeMakerId = 19;
        maker19.coffeeMakerPrice = 1999.50;
        maker19.isAvailable = true;
        maker19.coffeeMakerType = "Automatic";
        maker19.capacityLiters = 1.5;
        maker19.weight = 3.2;
        maker19.hasGrinder = true;
        maker19.material = "Stainless Steel";
        maker19.warrantyYears = 2;
        maker19.brewingTime = 5.0;
        maker19.hasTimer = true;
        maker19.color = "Black";
        maker19.stockQuantity = 22;
        maker19.powerConsumption = 900.0;
        maker19.isEcoFriendly = true;
        maker19.filterType = "Reusable";
        maker19.rating = 4;
        maker19.waterTankCapacity = 1.2;
        maker19.isCertified = true;
        maker19.countryOfOrigin = "Italy";
        maker19.manufacturingYear = 2025;
        maker19.cordLength = 1.0;
        maker19.supportsSmartControl = false;
        maker19.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker19.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker19.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker19.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker19.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker19.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker19.capacityLiters);
        System.out.println("The weight is : " + maker19.weight);
        System.out.println("The hasGrinder is : " + maker19.hasGrinder);
        System.out.println("The material is : " + maker19.material);
        System.out.println("The warrantyYears is : " + maker19.warrantyYears);
        System.out.println("The brewingTime is : " + maker19.brewingTime);
        System.out.println("The hasTimer is : " + maker19.hasTimer);
        System.out.println("The color is : " + maker19.color);
        System.out.println("The stockQuantity is : " + maker19.stockQuantity);
        System.out.println("The powerConsumption is : " + maker19.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker19.isEcoFriendly);
        System.out.println("The filterType is : " + maker19.filterType);
        System.out.println("The rating is : " + maker19.rating);
        System.out.println("The waterTankCapacity is : " + maker19.waterTankCapacity);
        System.out.println("The isCertified is : " + maker19.isCertified);
        System.out.println("The countryOfOrigin is : " + maker19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker19.manufacturingYear);
        System.out.println("The cordLength is : " + maker19.cordLength);
        System.out.println("The supportsSmartControl is : " + maker19.supportsSmartControl);
        System.out.println("The certificationType is : " + maker19.certificationType);


        CoffeeMaker maker20 = new CoffeeMaker();

        System.out.println("Before initialization");

        System.out.println("The coffeeMakerBrand is : " + maker20.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker20.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker20.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker20.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker20.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker20.capacityLiters);
        System.out.println("The weight is : " + maker20.weight);
        System.out.println("The hasGrinder is : " + maker20.hasGrinder);
        System.out.println("The material is : " + maker20.material);
        System.out.println("The warrantyYears is : " + maker20.warrantyYears);
        System.out.println("The brewingTime is : " + maker20.brewingTime);
        System.out.println("The hasTimer is : " + maker20.hasTimer);
        System.out.println("The color is : " + maker20.color);
        System.out.println("The stockQuantity is : " + maker20.stockQuantity);
        System.out.println("The powerConsumption is : " + maker20.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker20.isEcoFriendly);
        System.out.println("The filterType is : " + maker20.filterType);
        System.out.println("The rating is : " + maker20.rating);
        System.out.println("The waterTankCapacity is : " + maker20.waterTankCapacity);
        System.out.println("The isCertified is : " + maker20.isCertified);
        System.out.println("The countryOfOrigin is : " + maker20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker20.manufacturingYear);
        System.out.println("The cordLength is : " + maker20.cordLength);
        System.out.println("The supportsSmartControl is : " + maker20.supportsSmartControl);
        System.out.println("The certificationType is : " + maker20.certificationType);

        maker20.coffeeMakerBrand = "BrewMaster";
        maker20.coffeeMakerId = 20;
        maker20.coffeeMakerPrice = 2099.50;
        maker20.isAvailable = true;
        maker20.coffeeMakerType = "Automatic";
        maker20.capacityLiters = 1.5;
        maker20.weight = 3.2;
        maker20.hasGrinder = true;
        maker20.material = "Stainless Steel";
        maker20.warrantyYears = 2;
        maker20.brewingTime = 5.0;
        maker20.hasTimer = true;
        maker20.color = "Black";
        maker20.stockQuantity = 22;
        maker20.powerConsumption = 900.0;
        maker20.isEcoFriendly = true;
        maker20.filterType = "Reusable";
        maker20.rating = 4;
        maker20.waterTankCapacity = 1.2;
        maker20.isCertified = true;
        maker20.countryOfOrigin = "Italy";
        maker20.manufacturingYear = 2025;
        maker20.cordLength = 1.0;
        maker20.supportsSmartControl = false;
        maker20.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The coffeeMakerBrand is : " + maker20.coffeeMakerBrand);
        System.out.println("The coffeeMakerId is : " + maker20.coffeeMakerId);
        System.out.println("The coffeeMakerPrice is : " + maker20.coffeeMakerPrice);
        System.out.println("The isAvailable is : " + maker20.isAvailable);
        System.out.println("The coffeeMakerType is : " + maker20.coffeeMakerType);
        System.out.println("The capacityLiters is : " + maker20.capacityLiters);
        System.out.println("The weight is : " + maker20.weight);
        System.out.println("The hasGrinder is : " + maker20.hasGrinder);
        System.out.println("The material is : " + maker20.material);
        System.out.println("The warrantyYears is : " + maker20.warrantyYears);
        System.out.println("The brewingTime is : " + maker20.brewingTime);
        System.out.println("The hasTimer is : " + maker20.hasTimer);
        System.out.println("The color is : " + maker20.color);
        System.out.println("The stockQuantity is : " + maker20.stockQuantity);
        System.out.println("The powerConsumption is : " + maker20.powerConsumption);
        System.out.println("The isEcoFriendly is : " + maker20.isEcoFriendly);
        System.out.println("The filterType is : " + maker20.filterType);
        System.out.println("The rating is : " + maker20.rating);
        System.out.println("The waterTankCapacity is : " + maker20.waterTankCapacity);
        System.out.println("The isCertified is : " + maker20.isCertified);
        System.out.println("The countryOfOrigin is : " + maker20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + maker20.manufacturingYear);
        System.out.println("The cordLength is : " + maker20.cordLength);
        System.out.println("The supportsSmartControl is : " + maker20.supportsSmartControl);
        System.out.println("The certificationType is : " + maker20.certificationType);


    }
}
