
class CoffeeRunner {
    public static void main(String[] args) {
        
        // Default constructor
        Coffee c1 = new Coffee(); 
        c1.name = "Starbucks"; 
		c1.roast = "Dark";
        Coffee c2 = new Coffee(); 
        c2.name = "Dunkin"; 
		c2.roast = "Medium";
        Coffee c3 = new Coffee(); 
        c3.name = "Peets"; 
		c3.roast = "Light";
        Coffee c4 = new Coffee(); 
        c4.name = "Lavazza"; 
		c4.roast = "Espresso";
        Coffee c5 = new Coffee();
        c5.name = "Folgers";
		c5.roast = "Classic";
        Coffee c6 = new Coffee(); 
        c6.name = "Maxwell"; 
		c6.roast = "Breakfast";
        Coffee c7 = new Coffee(); 
        c7.name = "Nescafe"; 
		c7.roast = "Instant";
        Coffee c8 = new Coffee(); 
        c8.name = "Tim Hortons"; 
		c8.roast = "Original";
        Coffee c9 = new Coffee(); 
        c9.name = "Costa"; 
		c9.roast = "Signature";
        Coffee c10 = new Coffee(); 
        c10.name = "Blue Bottle"; 
		c10.roast = "Single Origin";
        Coffee c11 = new Coffee(); 
        c11.name = "Illy"; 
		c11.roast = "Classico";
        Coffee c12 = new Coffee(); 
        c12.name = "Kicking Horse"; 
		c12.roast = "Dark";
        Coffee c13 = new Coffee(); 
        c13.name = "Death Wish"; 
		c13.roast = "Extra Dark";
        Coffee c14 = new Coffee(); 
        c14.name = "Gevalia"; 
		c14.roast = "Traditional";
        Coffee c15 = new Coffee(); 
        c15.name = "Caribou"; 
		c15.roast = "Blend";
        Coffee c16 = new Coffee(); 
        c16.name = "Seattle Best"; 
		c16.roast = "Post Alley";
        Coffee c17 = new Coffee(); 
        c17.name = "Eight OClock"; 
		c17.roast = "Original";
        Coffee c18 = new Coffee(); 
        c18.name = "Stumptown"; 
		c18.roast = "Hair Bender";
        Coffee c19 = new Coffee(); 
        c19.name = "Intelligentsia"; 
		c19.roast = "Black Cat";
        Coffee c20 = new Coffee(); 
        c20.name = "La Colombe"; 
		c20.roast = "Corsica";
        Coffee c21 = new Coffee(); 
        c21.name = "Counter Culture"; 
		c21.roast = "Apollo";
        Coffee c22 = new Coffee(); 
        c22.name = "Philz"; 
		c22.roast = "Mint Mojito";
        Coffee c23 = new Coffee(); 
        c23.name = "Green Mountain"; 
		c23.roast = "Nantucket";
        Coffee c24 = new Coffee(); 
        c24.name = "Cafe Bustelo"; 
		c24.roast = "Espresso";
        Coffee c25 = new Coffee(); 
        c25.name = "McCafe"; 
		c25.roast = "Premium";

        System.out.println("Coffee Name  : " + c1.name + " & roast is  " + c1.roast);
        System.out.println("Coffee Name  : " + c2.name + " & roast is  " + c2.roast);
        System.out.println("Coffee Name  : " + c3.name + " & roast is  " + c3.roast);
        System.out.println("Coffee Name  : " + c4.name + " & roast is  " + c4.roast);
        System.out.println("Coffee Name  : " + c5.name + " & roast is  " + c5.roast);
        System.out.println("Coffee Name  : " + c6.name + " & roast is  " + c6.roast);
        System.out.println("Coffee Name  : " + c7.name + " & roast is  " + c7.roast);
        System.out.println("Coffee Name  : " + c8.name + " & roast is  " + c8.roast);
        System.out.println("Coffee Name  : " + c9.name + " & roast is  " + c9.roast);
        System.out.println("Coffee Name  : " + c10.name + " & roast is  " + c10.roast);
        System.out.println("Coffee Name  : " + c11.name + " & roast is  " + c11.roast);
        System.out.println("Coffee Name  : " + c12.name + " & roast is  " + c12.roast);
        System.out.println("Coffee Name  : " + c13.name + " & roast is  " + c13.roast);
        System.out.println("Coffee Name  : " + c14.name + " & roast is  " + c14.roast);
        System.out.println("Coffee Name  : " + c15.name + " & roast is  " + c15.roast);
        System.out.println("Coffee Name  : " + c16.name + " & roast is  " + c16.roast);
        System.out.println("Coffee Name  : " + c17.name + " & roast is  " + c17.roast);
        System.out.println("Coffee Name  : " + c18.name + " & roast is  " + c18.roast);
        System.out.println("Coffee Name  : " + c19.name + " & roast is  " + c19.roast);
        System.out.println("Coffee Name  : " + c20.name + " & roast is  " + c20.roast);
        System.out.println("Coffee Name  : " + c21.name + " & roast is  " + c21.roast);
        System.out.println("Coffee Name  : " + c22.name + " & roast is  " + c22.roast);
        System.out.println("Coffee Name  : " + c23.name + " & roast is  " + c23.roast);
        System.out.println("Coffee Name  : " + c24.name + " & roast is  " + c24.roast);
        System.out.println("Coffee Name  : " + c25.name + " & roast is  " + c25.roast);

        // Name of theeterized constructor
        Coffee p1 = new Coffee("Espresso", "Hot");
        Coffee p2 = new Coffee("Americano", "Iced");
        Coffee p3 = new Coffee("Macchiato", "Hot");
        Coffee p4 = new Coffee("Cappuccino", "Warm");
        Coffee p5 = new Coffee("Latte", "Iced");
        Coffee p6 = new Coffee("Mocha", "Hot");
        Coffee p7 = new Coffee("Flat White", "Hot");
        Coffee p8 = new Coffee("Cortado", "Warm");
        Coffee p9 = new Coffee("Affogato", "Cold");
        Coffee p10 = new Coffee("Cold Brew", "Iced");
        Coffee p11 = new Coffee("Nitro", "Cold");
        Coffee p12 = new Coffee("Frappuccino", "Blended");
        Coffee p13 = new Coffee("Irish Coffee", "Hot");
        Coffee p14 = new Coffee("Turkish Coffee", "Hot");
        Coffee p15 = new Coffee("Pour Over", "Hot");
        Coffee p16 = new Coffee("French Press", "Hot");
        Coffee p17 = new Coffee("Aeropress", "Warm");
        Coffee p18 = new Coffee("Ristretto", "Hot");
        Coffee p19 = new Coffee("Lungo", "Hot");
        Coffee p20 = new Coffee("Piccolo", "Warm");
        Coffee p21 = new Coffee("Breve", "Hot");
        Coffee p22 = new Coffee("Red Eye", "Hot");
        Coffee p23 = new Coffee("Black Eye", "Hot");
        Coffee p24 = new Coffee("Dead Eye", "Hot");
        Coffee p25 = new Coffee("Drip", "Hot");

        System.out.println("Name of the Coffee 1: " + p1.name + " & roast is  " + p1.roast);
        System.out.println("Name of the Coffee 2: " + p2.name + " & roast is  " + p2.roast);
        System.out.println("Name of the Coffee 3: " + p3.name + " & roast is  " + p3.roast);
        System.out.println("Name of the Coffee 4: " + p4.name + " & roast is  " + p4.roast);
        System.out.println("Name of the Coffee 5: " + p5.name + " & roast is  " + p5.roast);
        System.out.println("Name of the Coffee 6: " + p6.name + " & roast is  " + p6.roast);
        System.out.println("Name of the Coffee 7: " + p7.name + " & roast is  " + p7.roast);
        System.out.println("Name of the Coffee 8: " + p8.name + " & roast is  " + p8.roast);
        System.out.println("Name of the Coffee 9: " + p9.name + " & roast is  " + p9.roast);
        System.out.println("Name of the Coffee 10: " + p10.name + " & roast is  " + p10.roast);
        System.out.println("Name of the Coffee 11: " + p11.name + " & roast is  " + p11.roast);
        System.out.println("Name of the Coffee 12: " + p12.name + " & roast is  " + p12.roast);
        System.out.println("Name of the Coffee 13: " + p13.name + " & roast is  " + p13.roast);
        System.out.println("Name of the Coffee 14: " + p14.name + " & roast is  " + p14.roast);
        System.out.println("Name of the Coffee 15: " + p15.name + " & roast is  " + p15.roast);
        System.out.println("Name of the Coffee 16: " + p16.name + " & roast is  " + p16.roast);
        System.out.println("Name of the Coffee 17: " + p17.name + " & roast is  " + p17.roast);
        System.out.println("Name of the Coffee 18: " + p18.name + " & roast is  " + p18.roast);
        System.out.println("Name of the Coffee 19: " + p19.name + " & roast is  " + p19.roast);
        System.out.println("Name of the Coffee 20: " + p20.name + " & roast is  " + p20.roast);
        System.out.println("Name of the Coffee 21: " + p21.name + " & roast is  " + p21.roast);
        System.out.println("Name of the Coffee 22: " + p22.name + " & roast is  " + p22.roast);
        System.out.println("Name of the Coffee 23: " + p23.name + " & roast is  " + p23.roast);
        System.out.println("Name of the Coffee 24: " + p24.name + " & roast is  " + p24.roast);
        System.out.println("Name of the Coffee 25: " + p25.name + " & roast is  " + p25.roast);
    }
}
