class FilterExecutor {

public static void main(String[] args) {

Filter filter1 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter1.filterName);
System.out.println("The filter id is : " + filter1.filterId);
System.out.println("The filter price is : " + filter1.filterPrice);
System.out.println("The filter availability is : " + filter1.isAvailable);
System.out.println("The filter type is : " + filter1.filterType);
System.out.println("The filter size is : " + filter1.filterSize);
System.out.println("The filter efficiency rate is : " + filter1.efficiencyRate);
System.out.println("The filter reusable status is : " + filter1.isReusable);
System.out.println("The filter manufacturer name is : " + filter1.manufacturerName);
System.out.println("The filter production year is : " + filter1.productionYear);
System.out.println("The filter flow rate is : " + filter1.flowRate);
System.out.println("The filter eco friendly status is : " + filter1.isEcoFriendly);
System.out.println("The filter material type is : " + filter1.materialType);
System.out.println("The filter warranty years is : " + filter1.warrantyYears);
System.out.println("The filter weight is : " + filter1.filterWeight);
System.out.println("The filter washable status is : " + filter1.isWashable);
System.out.println("The filter color is : " + filter1.color);
System.out.println("The filter stock quantity is : " + filter1.stockQuantity);
System.out.println("The filter thickness is : " + filter1.thickness);
System.out.println("The filter certified status is : " + filter1.isCertified);
System.out.println("The filter country of origin is : " + filter1.countryOfOrigin);
System.out.println("The filter rating is : " + filter1.rating);
System.out.println("The filter temperature resistance is : " + filter1.temperatureResistance);
System.out.println("The filter high performance status is : " + filter1.isHighPerformance);
System.out.println("The filter certification type is : " + filter1.certificationType);


filter1.filterName = "AirClean";
filter1.filterId = 101;
filter1.filterPrice = 450.5;
filter1.isAvailable = true;
filter1.filterType = "Air";
filter1.filterSize = 10;
filter1.efficiencyRate = 95.5;
filter1.isReusable = true;
filter1.manufacturerName = "CleanTech";
filter1.productionYear = 2024;
filter1.flowRate = 20.5;
filter1.isEcoFriendly = true;
filter1.materialType = "Carbon";
filter1.warrantyYears = 2;
filter1.filterWeight = 1.5;
filter1.isWashable = false;
filter1.color = "Black";
filter1.stockQuantity = 50;
filter1.thickness = 0.5;
filter1.isCertified = true;
filter1.countryOfOrigin = "India";
filter1.rating = 5;
filter1.temperatureResistance = 100.5;
filter1.isHighPerformance = true;
filter1.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter1.filterName);
System.out.println("The filter id is : " + filter1.filterId);
System.out.println("The filter price is : " + filter1.filterPrice);
System.out.println("The filter availability is : " + filter1.isAvailable);
System.out.println("The filter type is : " + filter1.filterType);
System.out.println("The filter size is : " + filter1.filterSize);
System.out.println("The filter efficiency rate is : " + filter1.efficiencyRate);
System.out.println("The filter reusable status is : " + filter1.isReusable);
System.out.println("The filter manufacturer name is : " + filter1.manufacturerName);
System.out.println("The filter production year is : " + filter1.productionYear);
System.out.println("The filter flow rate is : " + filter1.flowRate);
System.out.println("The filter eco friendly status is : " + filter1.isEcoFriendly);
System.out.println("The filter material type is : " + filter1.materialType);
System.out.println("The filter warranty years is : " + filter1.warrantyYears);
System.out.println("The filter weight is : " + filter1.filterWeight);
System.out.println("The filter washable status is : " + filter1.isWashable);
System.out.println("The filter color is : " + filter1.color);
System.out.println("The filter stock quantity is : " + filter1.stockQuantity);
System.out.println("The filter thickness is : " + filter1.thickness);
System.out.println("The filter certified status is : " + filter1.isCertified);
System.out.println("The filter country of origin is : " + filter1.countryOfOrigin);
System.out.println("The filter rating is : " + filter1.rating);
System.out.println("The filter temperature resistance is : " + filter1.temperatureResistance);
System.out.println("The filter high performance status is : " + filter1.isHighPerformance);
System.out.println("The filter certification type is : " + filter1.certificationType);
		
		
Filter filter2 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter2.filterName);
System.out.println("The filter id is : " + filter2.filterId);
System.out.println("The filter price is : " + filter2.filterPrice);
System.out.println("The filter availability is : " + filter2.isAvailable);
System.out.println("The filter type is : " + filter2.filterType);
System.out.println("The filter size is : " + filter2.filterSize);
System.out.println("The filter efficiency rate is : " + filter2.efficiencyRate);
System.out.println("The filter reusable status is : " + filter2.isReusable);
System.out.println("The filter manufacturer name is : " + filter2.manufacturerName);
System.out.println("The filter production year is : " + filter2.productionYear);
System.out.println("The filter flow rate is : " + filter2.flowRate);
System.out.println("The filter eco friendly status is : " + filter2.isEcoFriendly);
System.out.println("The filter material type is : " + filter2.materialType);
System.out.println("The filter warranty years is : " + filter2.warrantyYears);
System.out.println("The filter weight is : " + filter2.filterWeight);
System.out.println("The filter washable status is : " + filter2.isWashable);
System.out.println("The filter color is : " + filter2.color);
System.out.println("The filter stock quantity is : " + filter2.stockQuantity);
System.out.println("The filter thickness is : " + filter2.thickness);
System.out.println("The filter certified status is : " + filter2.isCertified);
System.out.println("The filter country of origin is : " + filter2.countryOfOrigin);
System.out.println("The filter rating is : " + filter2.rating);
System.out.println("The filter temperature resistance is : " + filter2.temperatureResistance);
System.out.println("The filter high performance status is : " + filter2.isHighPerformance);
System.out.println("The filter certification type is : " + filter2.certificationType);

filter2.filterName = "PureAir";
filter2.filterId = 102;
filter2.filterPrice = 520.75;
filter2.isAvailable = true;
filter2.filterType = "Water";
filter2.filterSize = 12;
filter2.efficiencyRate = 90.5;
filter2.isReusable = false;
filter2.manufacturerName = "AquaTech";
filter2.productionYear = 2023;
filter2.flowRate = 15.4;
filter2.isEcoFriendly = true;
filter2.materialType = "Fiber";
filter2.warrantyYears = 3;
filter2.filterWeight = 1.2;
filter2.isWashable = true;
filter2.color = "Blue";
filter2.stockQuantity = 40;
filter2.thickness = 0.7;
filter2.isCertified = true;
filter2.countryOfOrigin = "Germany";
filter2.rating = 4;
filter2.temperatureResistance = 95.0;
filter2.isHighPerformance = true;
filter2.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter2.filterName);
System.out.println("The filter id is : " + filter2.filterId);
System.out.println("The filter price is : " + filter2.filterPrice);
System.out.println("The filter availability is : " + filter2.isAvailable);
System.out.println("The filter type is : " + filter2.filterType);
System.out.println("The filter size is : " + filter2.filterSize);
System.out.println("The filter efficiency rate is : " + filter2.efficiencyRate);
System.out.println("The filter reusable status is : " + filter2.isReusable);
System.out.println("The filter manufacturer name is : " + filter2.manufacturerName);
System.out.println("The filter production year is : " + filter2.productionYear);
System.out.println("The filter flow rate is : " + filter2.flowRate);
System.out.println("The filter eco friendly status is : " + filter2.isEcoFriendly);
System.out.println("The filter material type is : " + filter2.materialType);
System.out.println("The filter warranty years is : " + filter2.warrantyYears);
System.out.println("The filter weight is : " + filter2.filterWeight);
System.out.println("The filter washable status is : " + filter2.isWashable);
System.out.println("The filter color is : " + filter2.color);
System.out.println("The filter stock quantity is : " + filter2.stockQuantity);
System.out.println("The filter thickness is : " + filter2.thickness);
System.out.println("The filter certified status is : " + filter2.isCertified);
System.out.println("The filter country of origin is : " + filter2.countryOfOrigin);
System.out.println("The filter rating is : " + filter2.rating);
System.out.println("The filter temperature resistance is : " + filter2.temperatureResistance);
System.out.println("The filter high performance status is : " + filter2.isHighPerformance);
System.out.println("The filter certification type is : " + filter2.certificationType);


Filter filter3 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter3.filterName);
System.out.println("The filter id is : " + filter3.filterId);
System.out.println("The filter price is : " + filter3.filterPrice);
System.out.println("The filter availability is : " + filter3.isAvailable);
System.out.println("The filter type is : " + filter3.filterType);
System.out.println("The filter size is : " + filter3.filterSize);
System.out.println("The filter efficiency rate is : " + filter3.efficiencyRate);
System.out.println("The filter reusable status is : " + filter3.isReusable);
System.out.println("The filter manufacturer name is : " + filter3.manufacturerName);
System.out.println("The filter production year is : " + filter3.productionYear);
System.out.println("The filter flow rate is : " + filter3.flowRate);
System.out.println("The filter eco friendly status is : " + filter3.isEcoFriendly);
System.out.println("The filter material type is : " + filter3.materialType);
System.out.println("The filter warranty years is : " + filter3.warrantyYears);
System.out.println("The filter weight is : " + filter3.filterWeight);
System.out.println("The filter washable status is : " + filter3.isWashable);
System.out.println("The filter color is : " + filter3.color);
System.out.println("The filter stock quantity is : " + filter3.stockQuantity);
System.out.println("The filter thickness is : " + filter3.thickness);
System.out.println("The filter certified status is : " + filter3.isCertified);
System.out.println("The filter country of origin is : " + filter3.countryOfOrigin);
System.out.println("The filter rating is : " + filter3.rating);
System.out.println("The filter temperature resistance is : " + filter3.temperatureResistance);
System.out.println("The filter high performance status is : " + filter3.isHighPerformance);
System.out.println("The filter certification type is : " + filter3.certificationType);

filter3.filterName = "DustGuard";
filter3.filterId = 103;
filter3.filterPrice = 399.99;
filter3.isAvailable = true;
filter3.filterType = "Air";
filter3.filterSize = 9;
filter3.efficiencyRate = 88.3;
filter3.isReusable = true;
filter3.manufacturerName = "DustTech";
filter3.productionYear = 2022;
filter3.flowRate = 18.3;
filter3.isEcoFriendly = false;
filter3.materialType = "Foam";
filter3.warrantyYears = 1;
filter3.filterWeight = 0.9;
filter3.isWashable = false;
filter3.color = "Gray";
filter3.stockQuantity = 60;
filter3.thickness = 0.4;
filter3.isCertified = true;
filter3.countryOfOrigin = "USA";
filter3.rating = 3;
filter3.temperatureResistance = 85.2;
filter3.isHighPerformance = false;
filter3.certificationType = "CE";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter3.filterName);
System.out.println("The filter id is : " + filter3.filterId);
System.out.println("The filter price is : " + filter3.filterPrice);
System.out.println("The filter availability is : " + filter3.isAvailable);
System.out.println("The filter type is : " + filter3.filterType);
System.out.println("The filter size is : " + filter3.filterSize);
System.out.println("The filter efficiency rate is : " + filter3.efficiencyRate);
System.out.println("The filter reusable status is : " + filter3.isReusable);
System.out.println("The filter manufacturer name is : " + filter3.manufacturerName);
System.out.println("The filter production year is : " + filter3.productionYear);
System.out.println("The filter flow rate is : " + filter3.flowRate);
System.out.println("The filter eco friendly status is : " + filter3.isEcoFriendly);
System.out.println("The filter material type is : " + filter3.materialType);
System.out.println("The filter warranty years is : " + filter3.warrantyYears);
System.out.println("The filter weight is : " + filter3.filterWeight);
System.out.println("The filter washable status is : " + filter3.isWashable);
System.out.println("The filter color is : " + filter3.color);
System.out.println("The filter stock quantity is : " + filter3.stockQuantity);
System.out.println("The filter thickness is : " + filter3.thickness);
System.out.println("The filter certified status is : " + filter3.isCertified);
System.out.println("The filter country of origin is : " + filter3.countryOfOrigin);
System.out.println("The filter rating is : " + filter3.rating);
System.out.println("The filter temperature resistance is : " + filter3.temperatureResistance);
System.out.println("The filter high performance status is : " + filter3.isHighPerformance);
System.out.println("The filter certification type is : " + filter3.certificationType);


Filter filter4 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter4.filterName);
System.out.println("The filter id is : " + filter4.filterId);
System.out.println("The filter price is : " + filter4.filterPrice);
System.out.println("The filter availability is : " + filter4.isAvailable);
System.out.println("The filter type is : " + filter4.filterType);
System.out.println("The filter size is : " + filter4.filterSize);
System.out.println("The filter efficiency rate is : " + filter4.efficiencyRate);
System.out.println("The filter reusable status is : " + filter4.isReusable);
System.out.println("The filter manufacturer name is : " + filter4.manufacturerName);
System.out.println("The filter production year is : " + filter4.productionYear);
System.out.println("The filter flow rate is : " + filter4.flowRate);
System.out.println("The filter eco friendly status is : " + filter4.isEcoFriendly);
System.out.println("The filter material type is : " + filter4.materialType);
System.out.println("The filter warranty years is : " + filter4.warrantyYears);
System.out.println("The filter weight is : " + filter4.filterWeight);
System.out.println("The filter washable status is : " + filter4.isWashable);
System.out.println("The filter color is : " + filter4.color);
System.out.println("The filter stock quantity is : " + filter4.stockQuantity);
System.out.println("The filter thickness is : " + filter4.thickness);
System.out.println("The filter certified status is : " + filter4.isCertified);
System.out.println("The filter country of origin is : " + filter4.countryOfOrigin);
System.out.println("The filter rating is : " + filter4.rating);
System.out.println("The filter temperature resistance is : " + filter4.temperatureResistance);
System.out.println("The filter high performance status is : " + filter4.isHighPerformance);
System.out.println("The filter certification type is : " + filter4.certificationType);

filter4.filterName = "SafeFlow";
filter4.filterId = 104;
filter4.filterPrice = 610.50;
filter4.isAvailable = true;
filter4.filterType = "Oil";
filter4.filterSize = 14;
filter4.efficiencyRate = 92.1;
filter4.isReusable = false;
filter4.manufacturerName = "SafeTech";
filter4.productionYear = 2025;
filter4.flowRate = 21.2;
filter4.isEcoFriendly = true;
filter4.materialType = "Steel";
filter4.warrantyYears = 4;
filter4.filterWeight = 2.0;
filter4.isWashable = true;
filter4.color = "Silver";
filter4.stockQuantity = 30;
filter4.thickness = 0.8;
filter4.isCertified = true;
filter4.countryOfOrigin = "Japan";
filter4.rating = 5;
filter4.temperatureResistance = 120.5;
filter4.isHighPerformance = true;
filter4.certificationType = "ISI";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter4.filterName);
System.out.println("The filter id is : " + filter4.filterId);
System.out.println("The filter price is : " + filter4.filterPrice);
System.out.println("The filter availability is : " + filter4.isAvailable);
System.out.println("The filter type is : " + filter4.filterType);
System.out.println("The filter size is : " + filter4.filterSize);
System.out.println("The filter efficiency rate is : " + filter4.efficiencyRate);
System.out.println("The filter reusable status is : " + filter4.isReusable);
System.out.println("The filter manufacturer name is : " + filter4.manufacturerName);
System.out.println("The filter production year is : " + filter4.productionYear);
System.out.println("The filter flow rate is : " + filter4.flowRate);
System.out.println("The filter eco friendly status is : " + filter4.isEcoFriendly);
System.out.println("The filter material type is : " + filter4.materialType);
System.out.println("The filter warranty years is : " + filter4.warrantyYears);
System.out.println("The filter weight is : " + filter4.filterWeight);
System.out.println("The filter washable status is : " + filter4.isWashable);
System.out.println("The filter color is : " + filter4.color);
System.out.println("The filter stock quantity is : " + filter4.stockQuantity);
System.out.println("The filter thickness is : " + filter4.thickness);
System.out.println("The filter certified status is : " + filter4.isCertified);
System.out.println("The filter country of origin is : " + filter4.countryOfOrigin);
System.out.println("The filter rating is : " + filter4.rating);
System.out.println("The filter temperature resistance is : " + filter4.temperatureResistance);
System.out.println("The filter high performance status is : " + filter4.isHighPerformance);
System.out.println("The filter certification type is : " + filter4.certificationType);

Filter filter5 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter5.filterName);
System.out.println("The filter id is : " + filter5.filterId);
System.out.println("The filter price is : " + filter5.filterPrice);
System.out.println("The filter availability is : " + filter5.isAvailable);
System.out.println("The filter type is : " + filter5.filterType);
System.out.println("The filter size is : " + filter5.filterSize);
System.out.println("The filter efficiency rate is : " + filter5.efficiencyRate);
System.out.println("The filter reusable status is : " + filter5.isReusable);
System.out.println("The filter manufacturer name is : " + filter5.manufacturerName);
System.out.println("The filter production year is : " + filter5.productionYear);
System.out.println("The filter flow rate is : " + filter5.flowRate);
System.out.println("The filter eco friendly status is : " + filter5.isEcoFriendly);
System.out.println("The filter material type is : " + filter5.materialType);
System.out.println("The filter warranty years is : " + filter5.warrantyYears);
System.out.println("The filter weight is : " + filter5.filterWeight);
System.out.println("The filter washable status is : " + filter5.isWashable);
System.out.println("The filter color is : " + filter5.color);
System.out.println("The filter stock quantity is : " + filter5.stockQuantity);
System.out.println("The filter thickness is : " + filter5.thickness);
System.out.println("The filter certified status is : " + filter5.isCertified);
System.out.println("The filter country of origin is : " + filter5.countryOfOrigin);
System.out.println("The filter rating is : " + filter5.rating);
System.out.println("The filter temperature resistance is : " + filter5.temperatureResistance);
System.out.println("The filter high performance status is : " + filter5.isHighPerformance);
System.out.println("The filter certification type is : " + filter5.certificationType);

filter5.filterName = "UltraFilter";
filter5.filterId = 105;
filter5.filterPrice = 720.25;
filter5.isAvailable = true;
filter5.filterType = "Air";
filter5.filterSize = 15;
filter5.efficiencyRate = 96.4;
filter5.isReusable = true;
filter5.manufacturerName = "UltraTech";
filter5.productionYear = 2024;
filter5.flowRate = 25.5;
filter5.isEcoFriendly = true;
filter5.materialType = "Carbon";
filter5.warrantyYears = 5;
filter5.filterWeight = 1.7;
filter5.isWashable = true;
filter5.color = "Black";
filter5.stockQuantity = 25;
filter5.thickness = 0.6;
filter5.isCertified = true;
filter5.countryOfOrigin = "India";
filter5.rating = 5;
filter5.temperatureResistance = 130.0;
filter5.isHighPerformance = true;
filter5.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter5.filterName);
System.out.println("The filter id is : " + filter5.filterId);
System.out.println("The filter price is : " + filter5.filterPrice);
System.out.println("The filter availability is : " + filter5.isAvailable);
System.out.println("The filter type is : " + filter5.filterType);
System.out.println("The filter size is : " + filter5.filterSize);
System.out.println("The filter efficiency rate is : " + filter5.efficiencyRate);
System.out.println("The filter reusable status is : " + filter5.isReusable);
System.out.println("The filter manufacturer name is : " + filter5.manufacturerName);
System.out.println("The filter production year is : " + filter5.productionYear);
System.out.println("The filter flow rate is : " + filter5.flowRate);
System.out.println("The filter eco friendly status is : " + filter5.isEcoFriendly);
System.out.println("The filter material type is : " + filter5.materialType);
System.out.println("The filter warranty years is : " + filter5.warrantyYears);
System.out.println("The filter weight is : " + filter5.filterWeight);
System.out.println("The filter washable status is : " + filter5.isWashable);
System.out.println("The filter color is : " + filter5.color);
System.out.println("The filter stock quantity is : " + filter5.stockQuantity);
System.out.println("The filter thickness is : " + filter5.thickness);
System.out.println("The filter certified status is : " + filter5.isCertified);
System.out.println("The filter country of origin is : " + filter5.countryOfOrigin);
System.out.println("The filter rating is : " + filter5.rating);
System.out.println("The filter temperature resistance is : " + filter5.temperatureResistance);
System.out.println("The filter high performance status is : " + filter5.isHighPerformance);
System.out.println("The filter certification type is : " + filter5.certificationType);

Filter filter6 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter6.filterName);
System.out.println("The filter id is : " + filter6.filterId);
System.out.println("The filter price is : " + filter6.filterPrice);
System.out.println("The filter availability is : " + filter6.isAvailable);
System.out.println("The filter type is : " + filter6.filterType);
System.out.println("The filter size is : " + filter6.filterSize);
System.out.println("The filter efficiency rate is : " + filter6.efficiencyRate);
System.out.println("The filter reusable status is : " + filter6.isReusable);
System.out.println("The filter manufacturer name is : " + filter6.manufacturerName);
System.out.println("The filter production year is : " + filter6.productionYear);
System.out.println("The filter flow rate is : " + filter6.flowRate);
System.out.println("The filter eco friendly status is : " + filter6.isEcoFriendly);
System.out.println("The filter material type is : " + filter6.materialType);
System.out.println("The filter warranty years is : " + filter6.warrantyYears);
System.out.println("The filter weight is : " + filter6.filterWeight);
System.out.println("The filter washable status is : " + filter6.isWashable);
System.out.println("The filter color is : " + filter6.color);
System.out.println("The filter stock quantity is : " + filter6.stockQuantity);
System.out.println("The filter thickness is : " + filter6.thickness);
System.out.println("The filter certified status is : " + filter6.isCertified);
System.out.println("The filter country of origin is : " + filter6.countryOfOrigin);
System.out.println("The filter rating is : " + filter6.rating);
System.out.println("The filter temperature resistance is : " + filter6.temperatureResistance);
System.out.println("The filter high performance status is : " + filter6.isHighPerformance);
System.out.println("The filter certification type is : " + filter6.certificationType);

filter6.filterName = "ClearAir";
filter6.filterId = 106;
filter6.filterPrice = 480.50;
filter6.isAvailable = true;
filter6.filterType = "Air";
filter6.filterSize = 11;
filter6.efficiencyRate = 91.5;
filter6.isReusable = true;
filter6.manufacturerName = "AirTech";
filter6.productionYear = 2023;
filter6.flowRate = 19.5;
filter6.isEcoFriendly = true;
filter6.materialType = "Carbon";
filter6.warrantyYears = 2;
filter6.filterWeight = 1.3;
filter6.isWashable = false;
filter6.color = "White";
filter6.stockQuantity = 35;
filter6.thickness = 0.55;
filter6.isCertified = true;
filter6.countryOfOrigin = "India";
filter6.rating = 4;
filter6.temperatureResistance = 105.5;
filter6.isHighPerformance = true;
filter6.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter6.filterName);
System.out.println("The filter id is : " + filter6.filterId);
System.out.println("The filter price is : " + filter6.filterPrice);
System.out.println("The filter availability is : " + filter6.isAvailable);
System.out.println("The filter type is : " + filter6.filterType);
System.out.println("The filter size is : " + filter6.filterSize);
System.out.println("The filter efficiency rate is : " + filter6.efficiencyRate);
System.out.println("The filter reusable status is : " + filter6.isReusable);
System.out.println("The filter manufacturer name is : " + filter6.manufacturerName);
System.out.println("The filter production year is : " + filter6.productionYear);
System.out.println("The filter flow rate is : " + filter6.flowRate);
System.out.println("The filter eco friendly status is : " + filter6.isEcoFriendly);
System.out.println("The filter material type is : " + filter6.materialType);
System.out.println("The filter warranty years is : " + filter6.warrantyYears);
System.out.println("The filter weight is : " + filter6.filterWeight);
System.out.println("The filter washable status is : " + filter6.isWashable);
System.out.println("The filter color is : " + filter6.color);
System.out.println("The filter stock quantity is : " + filter6.stockQuantity);
System.out.println("The filter thickness is : " + filter6.thickness);
System.out.println("The filter certified status is : " + filter6.isCertified);
System.out.println("The filter country of origin is : " + filter6.countryOfOrigin);
System.out.println("The filter rating is : " + filter6.rating);
System.out.println("The filter temperature resistance is : " + filter6.temperatureResistance);
System.out.println("The filter high performance status is : " + filter6.isHighPerformance);
System.out.println("The filter certification type is : " + filter6.certificationType);

Filter filter7 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter7.filterName);
System.out.println("The filter id is : " + filter7.filterId);
System.out.println("The filter price is : " + filter7.filterPrice);
System.out.println("The filter availability is : " + filter7.isAvailable);
System.out.println("The filter type is : " + filter7.filterType);
System.out.println("The filter size is : " + filter7.filterSize);
System.out.println("The filter efficiency rate is : " + filter7.efficiencyRate);
System.out.println("The filter reusable status is : " + filter7.isReusable);
System.out.println("The filter manufacturer name is : " + filter7.manufacturerName);
System.out.println("The filter production year is : " + filter7.productionYear);
System.out.println("The filter flow rate is : " + filter7.flowRate);
System.out.println("The filter eco friendly status is : " + filter7.isEcoFriendly);
System.out.println("The filter material type is : " + filter7.materialType);
System.out.println("The filter warranty years is : " + filter7.warrantyYears);
System.out.println("The filter weight is : " + filter7.filterWeight);
System.out.println("The filter washable status is : " + filter7.isWashable);
System.out.println("The filter color is : " + filter7.color);
System.out.println("The filter stock quantity is : " + filter7.stockQuantity);
System.out.println("The filter thickness is : " + filter7.thickness);
System.out.println("The filter certified status is : " + filter7.isCertified);
System.out.println("The filter country of origin is : " + filter7.countryOfOrigin);
System.out.println("The filter rating is : " + filter7.rating);
System.out.println("The filter temperature resistance is : " + filter7.temperatureResistance);
System.out.println("The filter high performance status is : " + filter7.isHighPerformance);
System.out.println("The filter certification type is : " + filter7.certificationType);

filter7.filterName = "AquaPure";
filter7.filterId = 107;
filter7.filterPrice = 530.75;
filter7.isAvailable = true;
filter7.filterType = "Water";
filter7.filterSize = 13;
filter7.efficiencyRate = 93.2;
filter7.isReusable = false;
filter7.manufacturerName = "WaterTech";
filter7.productionYear = 2022;
filter7.flowRate = 16.4;
filter7.isEcoFriendly = true;
filter7.materialType = "Fiber";
filter7.warrantyYears = 3;
filter7.filterWeight = 1.4;
filter7.isWashable = true;
filter7.color = "Blue";
filter7.stockQuantity = 45;
filter7.thickness = 0.65;
filter7.isCertified = true;
filter7.countryOfOrigin = "USA";
filter7.rating = 4;
filter7.temperatureResistance = 98.0;
filter7.isHighPerformance = true;
filter7.certificationType = "CE";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter7.filterName);
System.out.println("The filter id is : " + filter7.filterId);
System.out.println("The filter price is : " + filter7.filterPrice);
System.out.println("The filter availability is : " + filter7.isAvailable);
System.out.println("The filter type is : " + filter7.filterType);
System.out.println("The filter size is : " + filter7.filterSize);
System.out.println("The filter efficiency rate is : " + filter7.efficiencyRate);
System.out.println("The filter reusable status is : " + filter7.isReusable);
System.out.println("The filter manufacturer name is : " + filter7.manufacturerName);
System.out.println("The filter production year is : " + filter7.productionYear);
System.out.println("The filter flow rate is : " + filter7.flowRate);
System.out.println("The filter eco friendly status is : " + filter7.isEcoFriendly);
System.out.println("The filter material type is : " + filter7.materialType);
System.out.println("The filter warranty years is : " + filter7.warrantyYears);
System.out.println("The filter weight is : " + filter7.filterWeight);
System.out.println("The filter washable status is : " + filter7.isWashable);
System.out.println("The filter color is : " + filter7.color);
System.out.println("The filter stock quantity is : " + filter7.stockQuantity);
System.out.println("The filter thickness is : " + filter7.thickness);
System.out.println("The filter certified status is : " + filter7.isCertified);
System.out.println("The filter country of origin is : " + filter7.countryOfOrigin);
System.out.println("The filter rating is : " + filter7.rating);
System.out.println("The filter temperature resistance is : " + filter7.temperatureResistance);
System.out.println("The filter high performance status is : " + filter7.isHighPerformance);
System.out.println("The filter certification type is : " + filter7.certificationType);

Filter filter8 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter8.filterName);
System.out.println("The filter id is : " + filter8.filterId);
System.out.println("The filter price is : " + filter8.filterPrice);
System.out.println("The filter availability is : " + filter8.isAvailable);
System.out.println("The filter type is : " + filter8.filterType);
System.out.println("The filter size is : " + filter8.filterSize);
System.out.println("The filter efficiency rate is : " + filter8.efficiencyRate);
System.out.println("The filter reusable status is : " + filter8.isReusable);
System.out.println("The filter manufacturer name is : " + filter8.manufacturerName);
System.out.println("The filter production year is : " + filter8.productionYear);
System.out.println("The filter flow rate is : " + filter8.flowRate);
System.out.println("The filter eco friendly status is : " + filter8.isEcoFriendly);
System.out.println("The filter material type is : " + filter8.materialType);
System.out.println("The filter warranty years is : " + filter8.warrantyYears);
System.out.println("The filter weight is : " + filter8.filterWeight);
System.out.println("The filter washable status is : " + filter8.isWashable);
System.out.println("The filter color is : " + filter8.color);
System.out.println("The filter stock quantity is : " + filter8.stockQuantity);
System.out.println("The filter thickness is : " + filter8.thickness);
System.out.println("The filter certified status is : " + filter8.isCertified);
System.out.println("The filter country of origin is : " + filter8.countryOfOrigin);
System.out.println("The filter rating is : " + filter8.rating);
System.out.println("The filter temperature resistance is : " + filter8.temperatureResistance);
System.out.println("The filter high performance status is : " + filter8.isHighPerformance);
System.out.println("The filter certification type is : " + filter8.certificationType);

filter8.filterName = "DustShield";
filter8.filterId = 108;
filter8.filterPrice = 410.25;
filter8.isAvailable = true;
filter8.filterType = "Air";
filter8.filterSize = 10;
filter8.efficiencyRate = 87.9;
filter8.isReusable = true;
filter8.manufacturerName = "DustTech";
filter8.productionYear = 2021;
filter8.flowRate = 17.3;
filter8.isEcoFriendly = false;
filter8.materialType = "Foam";
filter8.warrantyYears = 1;
filter8.filterWeight = 0.95;
filter8.isWashable = false;
filter8.color = "Gray";
filter8.stockQuantity = 55;
filter8.thickness = 0.45;
filter8.isCertified = true;
filter8.countryOfOrigin = "Germany";
filter8.rating = 3;
filter8.temperatureResistance = 90.3;
filter8.isHighPerformance = false;
filter8.certificationType = "ISI";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter8.filterName);
System.out.println("The filter id is : " + filter8.filterId);
System.out.println("The filter price is : " + filter8.filterPrice);
System.out.println("The filter availability is : " + filter8.isAvailable);
System.out.println("The filter type is : " + filter8.filterType);
System.out.println("The filter size is : " + filter8.filterSize);
System.out.println("The filter efficiency rate is : " + filter8.efficiencyRate);
System.out.println("The filter reusable status is : " + filter8.isReusable);
System.out.println("The filter manufacturer name is : " + filter8.manufacturerName);
System.out.println("The filter production year is : " + filter8.productionYear);
System.out.println("The filter flow rate is : " + filter8.flowRate);
System.out.println("The filter eco friendly status is : " + filter8.isEcoFriendly);
System.out.println("The filter material type is : " + filter8.materialType);
System.out.println("The filter warranty years is : " + filter8.warrantyYears);
System.out.println("The filter weight is : " + filter8.filterWeight);
System.out.println("The filter washable status is : " + filter8.isWashable);
System.out.println("The filter color is : " + filter8.color);
System.out.println("The filter stock quantity is : " + filter8.stockQuantity);
System.out.println("The filter thickness is : " + filter8.thickness);
System.out.println("The filter certified status is : " + filter8.isCertified);
System.out.println("The filter country of origin is : " + filter8.countryOfOrigin);
System.out.println("The filter rating is : " + filter8.rating);
System.out.println("The filter temperature resistance is : " + filter8.temperatureResistance);
System.out.println("The filter high performance status is : " + filter8.isHighPerformance);
System.out.println("The filter certification type is : " + filter8.certificationType);

Filter filter9 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter9.filterName);
System.out.println("The filter id is : " + filter9.filterId);
System.out.println("The filter price is : " + filter9.filterPrice);
System.out.println("The filter availability is : " + filter9.isAvailable);
System.out.println("The filter type is : " + filter9.filterType);
System.out.println("The filter size is : " + filter9.filterSize);
System.out.println("The filter efficiency rate is : " + filter9.efficiencyRate);
System.out.println("The filter reusable status is : " + filter9.isReusable);
System.out.println("The filter manufacturer name is : " + filter9.manufacturerName);
System.out.println("The filter production year is : " + filter9.productionYear);
System.out.println("The filter flow rate is : " + filter9.flowRate);
System.out.println("The filter eco friendly status is : " + filter9.isEcoFriendly);
System.out.println("The filter material type is : " + filter9.materialType);
System.out.println("The filter warranty years is : " + filter9.warrantyYears);
System.out.println("The filter weight is : " + filter9.filterWeight);
System.out.println("The filter washable status is : " + filter9.isWashable);
System.out.println("The filter color is : " + filter9.color);
System.out.println("The filter stock quantity is : " + filter9.stockQuantity);
System.out.println("The filter thickness is : " + filter9.thickness);
System.out.println("The filter certified status is : " + filter9.isCertified);
System.out.println("The filter country of origin is : " + filter9.countryOfOrigin);
System.out.println("The filter rating is : " + filter9.rating);
System.out.println("The filter temperature resistance is : " + filter9.temperatureResistance);
System.out.println("The filter high performance status is : " + filter9.isHighPerformance);
System.out.println("The filter certification type is : " + filter9.certificationType);

filter9.filterName = "OilGuard";
filter9.filterId = 109;
filter9.filterPrice = 620.60;
filter9.isAvailable = true;
filter9.filterType = "Oil";
filter9.filterSize = 14;
filter9.efficiencyRate = 94.6;
filter9.isReusable = false;
filter9.manufacturerName = "OilTech";
filter9.productionYear = 2024;
filter9.flowRate = 22.5;
filter9.isEcoFriendly = true;
filter9.materialType = "Steel";
filter9.warrantyYears = 4;
filter9.filterWeight = 2.1;
filter9.isWashable = true;
filter9.color = "Silver";
filter9.stockQuantity = 28;
filter9.thickness = 0.85;
filter9.isCertified = true;
filter9.countryOfOrigin = "Japan";
filter9.rating = 5;
filter9.temperatureResistance = 125.8;
filter9.isHighPerformance = true;
filter9.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter9.filterName);
System.out.println("The filter id is : " + filter9.filterId);
System.out.println("The filter price is : " + filter9.filterPrice);
System.out.println("The filter availability is : " + filter9.isAvailable);
System.out.println("The filter type is : " + filter9.filterType);
System.out.println("The filter size is : " + filter9.filterSize);
System.out.println("The filter efficiency rate is : " + filter9.efficiencyRate);
System.out.println("The filter reusable status is : " + filter9.isReusable);
System.out.println("The filter manufacturer name is : " + filter9.manufacturerName);
System.out.println("The filter production year is : " + filter9.productionYear);
System.out.println("The filter flow rate is : " + filter9.flowRate);
System.out.println("The filter eco friendly status is : " + filter9.isEcoFriendly);
System.out.println("The filter material type is : " + filter9.materialType);
System.out.println("The filter warranty years is : " + filter9.warrantyYears);
System.out.println("The filter weight is : " + filter9.filterWeight);
System.out.println("The filter washable status is : " + filter9.isWashable);
System.out.println("The filter color is : " + filter9.color);
System.out.println("The filter stock quantity is : " + filter9.stockQuantity);
System.out.println("The filter thickness is : " + filter9.thickness);
System.out.println("The filter certified status is : " + filter9.isCertified);
System.out.println("The filter country of origin is : " + filter9.countryOfOrigin);
System.out.println("The filter rating is : " + filter9.rating);
System.out.println("The filter temperature resistance is : " + filter9.temperatureResistance);
System.out.println("The filter high performance status is : " + filter9.isHighPerformance);
System.out.println("The filter certification type is : " + filter9.certificationType);

Filter filter10 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter10.filterName);
System.out.println("The filter id is : " + filter10.filterId);
System.out.println("The filter price is : " + filter10.filterPrice);
System.out.println("The filter availability is : " + filter10.isAvailable);
System.out.println("The filter type is : " + filter10.filterType);
System.out.println("The filter size is : " + filter10.filterSize);
System.out.println("The filter efficiency rate is : " + filter10.efficiencyRate);
System.out.println("The filter reusable status is : " + filter10.isReusable);
System.out.println("The filter manufacturer name is : " + filter10.manufacturerName);
System.out.println("The filter production year is : " + filter10.productionYear);
System.out.println("The filter flow rate is : " + filter10.flowRate);
System.out.println("The filter eco friendly status is : " + filter10.isEcoFriendly);
System.out.println("The filter material type is : " + filter10.materialType);
System.out.println("The filter warranty years is : " + filter10.warrantyYears);
System.out.println("The filter weight is : " + filter10.filterWeight);
System.out.println("The filter washable status is : " + filter10.isWashable);
System.out.println("The filter color is : " + filter10.color);
System.out.println("The filter stock quantity is : " + filter10.stockQuantity);
System.out.println("The filter thickness is : " + filter10.thickness);
System.out.println("The filter certified status is : " + filter10.isCertified);
System.out.println("The filter country of origin is : " + filter10.countryOfOrigin);
System.out.println("The filter rating is : " + filter10.rating);
System.out.println("The filter temperature resistance is : " + filter10.temperatureResistance);
System.out.println("The filter high performance status is : " + filter10.isHighPerformance);
System.out.println("The filter certification type is : " + filter10.certificationType);

filter10.filterName = "UltraClean";
filter10.filterId = 110;
filter10.filterPrice = 710.90;
filter10.isAvailable = true;
filter10.filterType = "Air";
filter10.filterSize = 16;
filter10.efficiencyRate = 97.2;
filter10.isReusable = true;
filter10.manufacturerName = "UltraTech";
filter10.productionYear = 2025;
filter10.flowRate = 26.8;
filter10.isEcoFriendly = true;
filter10.materialType = "Carbon";
filter10.warrantyYears = 5;
filter10.filterWeight = 1.8;
filter10.isWashable = true;
filter10.color = "Black";
filter10.stockQuantity = 20;
filter10.thickness = 0.7;
filter10.isCertified = true;
filter10.countryOfOrigin = "India";
filter10.rating = 5;
filter10.temperatureResistance = 135.2;
filter10.isHighPerformance = true;
filter10.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter10.filterName);
System.out.println("The filter id is : " + filter10.filterId);
System.out.println("The filter price is : " + filter10.filterPrice);
System.out.println("The filter availability is : " + filter10.isAvailable);
System.out.println("The filter type is : " + filter10.filterType);
System.out.println("The filter size is : " + filter10.filterSize);
System.out.println("The filter efficiency rate is : " + filter10.efficiencyRate);
System.out.println("The filter reusable status is : " + filter10.isReusable);
System.out.println("The filter manufacturer name is : " + filter10.manufacturerName);
System.out.println("The filter production year is : " + filter10.productionYear);
System.out.println("The filter flow rate is : " + filter10.flowRate);
System.out.println("The filter eco friendly status is : " + filter10.isEcoFriendly);
System.out.println("The filter material type is : " + filter10.materialType);
System.out.println("The filter warranty years is : " + filter10.warrantyYears);
System.out.println("The filter weight is : " + filter10.filterWeight);
System.out.println("The filter washable status is : " + filter10.isWashable);
System.out.println("The filter color is : " + filter10.color);
System.out.println("The filter stock quantity is : " + filter10.stockQuantity);
System.out.println("The filter thickness is : " + filter10.thickness);
System.out.println("The filter certified status is : " + filter10.isCertified);
System.out.println("The filter country of origin is : " + filter10.countryOfOrigin);
System.out.println("The filter rating is : " + filter10.rating);
System.out.println("The filter temperature resistance is : " + filter10.temperatureResistance);
System.out.println("The filter high performance status is : " + filter10.isHighPerformance);
System.out.println("The filter certification type is : " + filter10.certificationType);

Filter filter11 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter11.filterName);
System.out.println("The filter id is : " + filter11.filterId);
System.out.println("The filter price is : " + filter11.filterPrice);
System.out.println("The filter availability is : " + filter11.isAvailable);
System.out.println("The filter type is : " + filter11.filterType);
System.out.println("The filter size is : " + filter11.filterSize);
System.out.println("The filter efficiency rate is : " + filter11.efficiencyRate);
System.out.println("The filter reusable status is : " + filter11.isReusable);
System.out.println("The filter manufacturer name is : " + filter11.manufacturerName);
System.out.println("The filter production year is : " + filter11.productionYear);
System.out.println("The filter flow rate is : " + filter11.flowRate);
System.out.println("The filter eco friendly status is : " + filter11.isEcoFriendly);
System.out.println("The filter material type is : " + filter11.materialType);
System.out.println("The filter warranty years is : " + filter11.warrantyYears);
System.out.println("The filter weight is : " + filter11.filterWeight);
System.out.println("The filter washable status is : " + filter11.isWashable);
System.out.println("The filter color is : " + filter11.color);
System.out.println("The filter stock quantity is : " + filter11.stockQuantity);
System.out.println("The filter thickness is : " + filter11.thickness);
System.out.println("The filter certified status is : " + filter11.isCertified);
System.out.println("The filter country of origin is : " + filter11.countryOfOrigin);
System.out.println("The filter rating is : " + filter11.rating);
System.out.println("The filter temperature resistance is : " + filter11.temperatureResistance);
System.out.println("The filter high performance status is : " + filter11.isHighPerformance);
System.out.println("The filter certification type is : " + filter11.certificationType);

filter11.filterName = "MegaAir";
filter11.filterId = 111;
filter11.filterPrice = 455.80;
filter11.isAvailable = true;
filter11.filterType = "Air";
filter11.filterSize = 12;
filter11.efficiencyRate = 90.8;
filter11.isReusable = true;
filter11.manufacturerName = "MegaTech";
filter11.productionYear = 2023;
filter11.flowRate = 18.7;
filter11.isEcoFriendly = true;
filter11.materialType = "Carbon";
filter11.warrantyYears = 2;
filter11.filterWeight = 1.4;
filter11.isWashable = false;
filter11.color = "White";
filter11.stockQuantity = 42;
filter11.thickness = 0.52;
filter11.isCertified = true;
filter11.countryOfOrigin = "India";
filter11.rating = 4;
filter11.temperatureResistance = 104.6;
filter11.isHighPerformance = true;
filter11.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter11.filterName);
System.out.println("The filter id is : " + filter11.filterId);
System.out.println("The filter price is : " + filter11.filterPrice);
System.out.println("The filter availability is : " + filter11.isAvailable);
System.out.println("The filter type is : " + filter11.filterType);
System.out.println("The filter size is : " + filter11.filterSize);
System.out.println("The filter efficiency rate is : " + filter11.efficiencyRate);
System.out.println("The filter reusable status is : " + filter11.isReusable);
System.out.println("The filter manufacturer name is : " + filter11.manufacturerName);
System.out.println("The filter production year is : " + filter11.productionYear);
System.out.println("The filter flow rate is : " + filter11.flowRate);
System.out.println("The filter eco friendly status is : " + filter11.isEcoFriendly);
System.out.println("The filter material type is : " + filter11.materialType);
System.out.println("The filter warranty years is : " + filter11.warrantyYears);
System.out.println("The filter weight is : " + filter11.filterWeight);
System.out.println("The filter washable status is : " + filter11.isWashable);
System.out.println("The filter color is : " + filter11.color);
System.out.println("The filter stock quantity is : " + filter11.stockQuantity);
System.out.println("The filter thickness is : " + filter11.thickness);
System.out.println("The filter certified status is : " + filter11.isCertified);
System.out.println("The filter country of origin is : " + filter11.countryOfOrigin);
System.out.println("The filter rating is : " + filter11.rating);
System.out.println("The filter temperature resistance is : " + filter11.temperatureResistance);
System.out.println("The filter high performance status is : " + filter11.isHighPerformance);
System.out.println("The filter certification type is : " + filter11.certificationType);

Filter filter12 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter12.filterName);
System.out.println("The filter id is : " + filter12.filterId);
System.out.println("The filter price is : " + filter12.filterPrice);
System.out.println("The filter availability is : " + filter12.isAvailable);
System.out.println("The filter type is : " + filter12.filterType);
System.out.println("The filter size is : " + filter12.filterSize);
System.out.println("The filter efficiency rate is : " + filter12.efficiencyRate);
System.out.println("The filter reusable status is : " + filter12.isReusable);
System.out.println("The filter manufacturer name is : " + filter12.manufacturerName);
System.out.println("The filter production year is : " + filter12.productionYear);
System.out.println("The filter flow rate is : " + filter12.flowRate);
System.out.println("The filter eco friendly status is : " + filter12.isEcoFriendly);
System.out.println("The filter material type is : " + filter12.materialType);
System.out.println("The filter warranty years is : " + filter12.warrantyYears);
System.out.println("The filter weight is : " + filter12.filterWeight);
System.out.println("The filter washable status is : " + filter12.isWashable);
System.out.println("The filter color is : " + filter12.color);
System.out.println("The filter stock quantity is : " + filter12.stockQuantity);
System.out.println("The filter thickness is : " + filter12.thickness);
System.out.println("The filter certified status is : " + filter12.isCertified);
System.out.println("The filter country of origin is : " + filter12.countryOfOrigin);
System.out.println("The filter rating is : " + filter12.rating);
System.out.println("The filter temperature resistance is : " + filter12.temperatureResistance);
System.out.println("The filter high performance status is : " + filter12.isHighPerformance);
System.out.println("The filter certification type is : " + filter12.certificationType);

filter12.filterName = "HydroClear";
filter12.filterId = 112;
filter12.filterPrice = 540.40;
filter12.isAvailable = true;
filter12.filterType = "Water";
filter12.filterSize = 13;
filter12.efficiencyRate = 92.5;
filter12.isReusable = false;
filter12.manufacturerName = "HydroTech";
filter12.productionYear = 2022;
filter12.flowRate = 17.6;
filter12.isEcoFriendly = true;
filter12.materialType = "Fiber";
filter12.warrantyYears = 3;
filter12.filterWeight = 1.5;
filter12.isWashable = true;
filter12.color = "Blue";
filter12.stockQuantity = 38;
filter12.thickness = 0.63;
filter12.isCertified = true;
filter12.countryOfOrigin = "USA";
filter12.rating = 4;
filter12.temperatureResistance = 97.3;
filter12.isHighPerformance = true;
filter12.certificationType = "CE";
System.out.println("After initialization");

System.out.println("The filter name is : " + filter12.filterName);
System.out.println("The filter id is : " + filter12.filterId);
System.out.println("The filter price is : " + filter12.filterPrice);
System.out.println("The filter availability is : " + filter12.isAvailable);
System.out.println("The filter type is : " + filter12.filterType);
System.out.println("The filter size is : " + filter12.filterSize);
System.out.println("The filter efficiency rate is : " + filter12.efficiencyRate);
System.out.println("The filter reusable status is : " + filter12.isReusable);
System.out.println("The filter manufacturer name is : " + filter12.manufacturerName);
System.out.println("The filter production year is : " + filter12.productionYear);
System.out.println("The filter flow rate is : " + filter12.flowRate);
System.out.println("The filter eco friendly status is : " + filter12.isEcoFriendly);
System.out.println("The filter material type is : " + filter12.materialType);
System.out.println("The filter warranty years is : " + filter12.warrantyYears);
System.out.println("The filter weight is : " + filter12.filterWeight);
System.out.println("The filter washable status is : " + filter12.isWashable);
System.out.println("The filter color is : " + filter12.color);
System.out.println("The filter stock quantity is : " + filter12.stockQuantity);
System.out.println("The filter thickness is : " + filter12.thickness);
System.out.println("The filter certified status is : " + filter12.isCertified);
System.out.println("The filter country of origin is : " + filter12.countryOfOrigin);
System.out.println("The filter rating is : " + filter12.rating);
System.out.println("The filter temperature resistance is : " + filter12.temperatureResistance);
System.out.println("The filter high performance status is : " + filter12.isHighPerformance);
System.out.println("The filter certification type is : " + filter12.certificationType);

Filter filter13 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter13.filterName);
System.out.println("The filter id is : " + filter13.filterId);
System.out.println("The filter price is : " + filter13.filterPrice);
System.out.println("The filter availability is : " + filter13.isAvailable);
System.out.println("The filter type is : " + filter13.filterType);
System.out.println("The filter size is : " + filter13.filterSize);
System.out.println("The filter efficiency rate is : " + filter13.efficiencyRate);
System.out.println("The filter reusable status is : " + filter13.isReusable);
System.out.println("The filter manufacturer name is : " + filter13.manufacturerName);
System.out.println("The filter production year is : " + filter13.productionYear);
System.out.println("The filter flow rate is : " + filter13.flowRate);
System.out.println("The filter eco friendly status is : " + filter13.isEcoFriendly);
System.out.println("The filter material type is : " + filter13.materialType);
System.out.println("The filter warranty years is : " + filter13.warrantyYears);
System.out.println("The filter weight is : " + filter13.filterWeight);
System.out.println("The filter washable status is : " + filter13.isWashable);
System.out.println("The filter color is : " + filter13.color);
System.out.println("The filter stock quantity is : " + filter13.stockQuantity);
System.out.println("The filter thickness is : " + filter13.thickness);
System.out.println("The filter certified status is : " + filter13.isCertified);
System.out.println("The filter country of origin is : " + filter13.countryOfOrigin);
System.out.println("The filter rating is : " + filter13.rating);
System.out.println("The filter temperature resistance is : " + filter13.temperatureResistance);
System.out.println("The filter high performance status is : " + filter13.isHighPerformance);
System.out.println("The filter certification type is : " + filter13.certificationType);

filter13.filterName = "DustBlock";
filter13.filterId = 113;
filter13.filterPrice = 395.60;
filter13.isAvailable = true;
filter13.filterType = "Air";
filter13.filterSize = 9;
filter13.efficiencyRate = 86.7;
filter13.isReusable = true;
filter13.manufacturerName = "DustControl";
filter13.productionYear = 2021;
filter13.flowRate = 16.9;
filter13.isEcoFriendly = false;
filter13.materialType = "Foam";
filter13.warrantyYears = 1;
filter13.filterWeight = 0.88;
filter13.isWashable = false;
filter13.color = "Gray";
filter13.stockQuantity = 65;
filter13.thickness = 0.43;
filter13.isCertified = true;
filter13.countryOfOrigin = "Germany";
filter13.rating = 3;
filter13.temperatureResistance = 88.9;
filter13.isHighPerformance = false;
filter13.certificationType = "ISI";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter13.filterName);
System.out.println("The filter id is : " + filter13.filterId);
System.out.println("The filter price is : " + filter13.filterPrice);
System.out.println("The filter availability is : " + filter13.isAvailable);
System.out.println("The filter type is : " + filter13.filterType);
System.out.println("The filter size is : " + filter13.filterSize);
System.out.println("The filter efficiency rate is : " + filter13.efficiencyRate);
System.out.println("The filter reusable status is : " + filter13.isReusable);
System.out.println("The filter manufacturer name is : " + filter13.manufacturerName);
System.out.println("The filter production year is : " + filter13.productionYear);
System.out.println("The filter flow rate is : " + filter13.flowRate);
System.out.println("The filter eco friendly status is : " + filter13.isEcoFriendly);
System.out.println("The filter material type is : " + filter13.materialType);
System.out.println("The filter warranty years is : " + filter13.warrantyYears);
System.out.println("The filter weight is : " + filter13.filterWeight);
System.out.println("The filter washable status is : " + filter13.isWashable);
System.out.println("The filter color is : " + filter13.color);
System.out.println("The filter stock quantity is : " + filter13.stockQuantity);
System.out.println("The filter thickness is : " + filter13.thickness);
System.out.println("The filter certified status is : " + filter13.isCertified);
System.out.println("The filter country of origin is : " + filter13.countryOfOrigin);
System.out.println("The filter rating is : " + filter13.rating);
System.out.println("The filter temperature resistance is : " + filter13.temperatureResistance);
System.out.println("The filter high performance status is : " + filter13.isHighPerformance);
System.out.println("The filter certification type is : " + filter13.certificationType);

Filter filter14 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter14.filterName);
System.out.println("The filter id is : " + filter14.filterId);
System.out.println("The filter price is : " + filter14.filterPrice);
System.out.println("The filter availability is : " + filter14.isAvailable);
System.out.println("The filter type is : " + filter14.filterType);
System.out.println("The filter size is : " + filter14.filterSize);
System.out.println("The filter efficiency rate is : " + filter14.efficiencyRate);
System.out.println("The filter reusable status is : " + filter14.isReusable);
System.out.println("The filter manufacturer name is : " + filter14.manufacturerName);
System.out.println("The filter production year is : " + filter14.productionYear);
System.out.println("The filter flow rate is : " + filter14.flowRate);
System.out.println("The filter eco friendly status is : " + filter14.isEcoFriendly);
System.out.println("The filter material type is : " + filter14.materialType);
System.out.println("The filter warranty years is : " + filter14.warrantyYears);
System.out.println("The filter weight is : " + filter14.filterWeight);
System.out.println("The filter washable status is : " + filter14.isWashable);
System.out.println("The filter color is : " + filter14.color);
System.out.println("The filter stock quantity is : " + filter14.stockQuantity);
System.out.println("The filter thickness is : " + filter14.thickness);
System.out.println("The filter certified status is : " + filter14.isCertified);
System.out.println("The filter country of origin is : " + filter14.countryOfOrigin);
System.out.println("The filter rating is : " + filter14.rating);
System.out.println("The filter temperature resistance is : " + filter14.temperatureResistance);
System.out.println("The filter high performance status is : " + filter14.isHighPerformance);
System.out.println("The filter certification type is : " + filter14.certificationType);

filter14.filterName = "TurboFlow";
filter14.filterId = 114;
filter14.filterPrice = 635.20;
filter14.isAvailable = true;
filter14.filterType = "Oil";
filter14.filterSize = 15;
filter14.efficiencyRate = 94.9;
filter14.isReusable = false;
filter14.manufacturerName = "TurboTech";
filter14.productionYear = 2024;
filter14.flowRate = 23.8;
filter14.isEcoFriendly = true;
filter14.materialType = "Steel";
filter14.warrantyYears = 4;
filter14.filterWeight = 2.3;
filter14.isWashable = true;
filter14.color = "Silver";
filter14.stockQuantity = 27;
filter14.thickness = 0.82;
filter14.isCertified = true;
filter14.countryOfOrigin = "Japan";
filter14.rating = 5;
filter14.temperatureResistance = 128.7;
filter14.isHighPerformance = true;
filter14.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter14.filterName);
System.out.println("The filter id is : " + filter14.filterId);
System.out.println("The filter price is : " + filter14.filterPrice);
System.out.println("The filter availability is : " + filter14.isAvailable);
System.out.println("The filter type is : " + filter14.filterType);
System.out.println("The filter size is : " + filter14.filterSize);
System.out.println("The filter efficiency rate is : " + filter14.efficiencyRate);
System.out.println("The filter reusable status is : " + filter14.isReusable);
System.out.println("The filter manufacturer name is : " + filter14.manufacturerName);
System.out.println("The filter production year is : " + filter14.productionYear);
System.out.println("The filter flow rate is : " + filter14.flowRate);
System.out.println("The filter eco friendly status is : " + filter14.isEcoFriendly);
System.out.println("The filter material type is : " + filter14.materialType);
System.out.println("The filter warranty years is : " + filter14.warrantyYears);
System.out.println("The filter weight is : " + filter14.filterWeight);
System.out.println("The filter washable status is : " + filter14.isWashable);
System.out.println("The filter color is : " + filter14.color);
System.out.println("The filter stock quantity is : " + filter14.stockQuantity);
System.out.println("The filter thickness is : " + filter14.thickness);
System.out.println("The filter certified status is : " + filter14.isCertified);
System.out.println("The filter country of origin is : " + filter14.countryOfOrigin);
System.out.println("The filter rating is : " + filter14.rating);
System.out.println("The filter temperature resistance is : " + filter14.temperatureResistance);
System.out.println("The filter high performance status is : " + filter14.isHighPerformance);
System.out.println("The filter certification type is : " + filter14.certificationType);

Filter filter15 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter15.filterName);
System.out.println("The filter id is : " + filter15.filterId);
System.out.println("The filter price is : " + filter15.filterPrice);
System.out.println("The filter availability is : " + filter15.isAvailable);
System.out.println("The filter type is : " + filter15.filterType);
System.out.println("The filter size is : " + filter15.filterSize);
System.out.println("The filter efficiency rate is : " + filter15.efficiencyRate);
System.out.println("The filter reusable status is : " + filter15.isReusable);
System.out.println("The filter manufacturer name is : " + filter15.manufacturerName);
System.out.println("The filter production year is : " + filter15.productionYear);
System.out.println("The filter flow rate is : " + filter15.flowRate);
System.out.println("The filter eco friendly status is : " + filter15.isEcoFriendly);
System.out.println("The filter material type is : " + filter15.materialType);
System.out.println("The filter warranty years is : " + filter15.warrantyYears);
System.out.println("The filter weight is : " + filter15.filterWeight);
System.out.println("The filter washable status is : " + filter15.isWashable);
System.out.println("The filter color is : " + filter15.color);
System.out.println("The filter stock quantity is : " + filter15.stockQuantity);
System.out.println("The filter thickness is : " + filter15.thickness);
System.out.println("The filter certified status is : " + filter15.isCertified);
System.out.println("The filter country of origin is : " + filter15.countryOfOrigin);
System.out.println("The filter rating is : " + filter15.rating);
System.out.println("The filter temperature resistance is : " + filter15.temperatureResistance);
System.out.println("The filter high performance status is : " + filter15.isHighPerformance);
System.out.println("The filter certification type is : " + filter15.certificationType);

filter15.filterName = "UltraShield";
filter15.filterId = 115;
filter15.filterPrice = 745.90;
filter15.isAvailable = true;
filter15.filterType = "Air";
filter15.filterSize = 17;
filter15.efficiencyRate = 97.8;
filter15.isReusable = true;
filter15.manufacturerName = "UltraTech";
filter15.productionYear = 2025;
filter15.flowRate = 27.6;
filter15.isEcoFriendly = true;
filter15.materialType = "Carbon";
filter15.warrantyYears = 5;
filter15.filterWeight = 1.9;
filter15.isWashable = true;
filter15.color = "Black";
filter15.stockQuantity = 22;
filter15.thickness = 0.74;
filter15.isCertified = true;
filter15.countryOfOrigin = "India";
filter15.rating = 5;
filter15.temperatureResistance = 138.4;
filter15.isHighPerformance = true;
filter15.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter15.filterName);
System.out.println("The filter id is : " + filter15.filterId);
System.out.println("The filter price is : " + filter15.filterPrice);
System.out.println("The filter availability is : " + filter15.isAvailable);
System.out.println("The filter type is : " + filter15.filterType);
System.out.println("The filter size is : " + filter15.filterSize);
System.out.println("The filter efficiency rate is : " + filter15.efficiencyRate);
System.out.println("The filter reusable status is : " + filter15.isReusable);
System.out.println("The filter manufacturer name is : " + filter15.manufacturerName);
System.out.println("The filter production year is : " + filter15.productionYear);
System.out.println("The filter flow rate is : " + filter15.flowRate);
System.out.println("The filter eco friendly status is : " + filter15.isEcoFriendly);
System.out.println("The filter material type is : " + filter15.materialType);
System.out.println("The filter warranty years is : " + filter15.warrantyYears);
System.out.println("The filter weight is : " + filter15.filterWeight);
System.out.println("The filter washable status is : " + filter15.isWashable);
System.out.println("The filter color is : " + filter15.color);
System.out.println("The filter stock quantity is : " + filter15.stockQuantity);
System.out.println("The filter thickness is : " + filter15.thickness);
System.out.println("The filter certified status is : " + filter15.isCertified);
System.out.println("The filter country of origin is : " + filter15.countryOfOrigin);
System.out.println("The filter rating is : " + filter15.rating);
System.out.println("The filter temperature resistance is : " + filter15.temperatureResistance);
System.out.println("The filter high performance status is : " + filter15.isHighPerformance);
System.out.println("The filter certification type is : " + filter15.certificationType);

Filter filter16 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter16.filterName);
System.out.println("The filter id is : " + filter16.filterId);
System.out.println("The filter price is : " + filter16.filterPrice);
System.out.println("The filter availability is : " + filter16.isAvailable);
System.out.println("The filter type is : " + filter16.filterType);
System.out.println("The filter size is : " + filter16.filterSize);
System.out.println("The filter efficiency rate is : " + filter16.efficiencyRate);
System.out.println("The filter reusable status is : " + filter16.isReusable);
System.out.println("The filter manufacturer name is : " + filter16.manufacturerName);
System.out.println("The filter production year is : " + filter16.productionYear);
System.out.println("The filter flow rate is : " + filter16.flowRate);
System.out.println("The filter eco friendly status is : " + filter16.isEcoFriendly);
System.out.println("The filter material type is : " + filter16.materialType);
System.out.println("The filter warranty years is : " + filter16.warrantyYears);
System.out.println("The filter weight is : " + filter16.filterWeight);
System.out.println("The filter washable status is : " + filter16.isWashable);
System.out.println("The filter color is : " + filter16.color);
System.out.println("The filter stock quantity is : " + filter16.stockQuantity);
System.out.println("The filter thickness is : " + filter16.thickness);
System.out.println("The filter certified status is : " + filter16.isCertified);
System.out.println("The filter country of origin is : " + filter16.countryOfOrigin);
System.out.println("The filter rating is : " + filter16.rating);
System.out.println("The filter temperature resistance is : " + filter16.temperatureResistance);
System.out.println("The filter high performance status is : " + filter16.isHighPerformance);
System.out.println("The filter certification type is : " + filter16.certificationType);

filter16.filterName = "AirMax";
filter16.filterId = 116;
filter16.filterPrice = 470.25;
filter16.isAvailable = true;
filter16.filterType = "Air";
filter16.filterSize = 11;
filter16.efficiencyRate = 89.4;
filter16.isReusable = true;
filter16.manufacturerName = "MaxTech";
filter16.productionYear = 2023;
filter16.flowRate = 18.2;
filter16.isEcoFriendly = true;
filter16.materialType = "Carbon";
filter16.warrantyYears = 2;
filter16.filterWeight = 1.35;
filter16.isWashable = false;
filter16.color = "White";
filter16.stockQuantity = 37;
filter16.thickness = 0.58;
filter16.isCertified = true;
filter16.countryOfOrigin = "India";
filter16.rating = 4;
filter16.temperatureResistance = 103.2;
filter16.isHighPerformance = true;
filter16.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter16.filterName);
System.out.println("The filter id is : " + filter16.filterId);
System.out.println("The filter price is : " + filter16.filterPrice);
System.out.println("The filter availability is : " + filter16.isAvailable);
System.out.println("The filter type is : " + filter16.filterType);
System.out.println("The filter size is : " + filter16.filterSize);
System.out.println("The filter efficiency rate is : " + filter16.efficiencyRate);
System.out.println("The filter reusable status is : " + filter16.isReusable);
System.out.println("The filter manufacturer name is : " + filter16.manufacturerName);
System.out.println("The filter production year is : " + filter16.productionYear);
System.out.println("The filter flow rate is : " + filter16.flowRate);
System.out.println("The filter eco friendly status is : " + filter16.isEcoFriendly);
System.out.println("The filter material type is : " + filter16.materialType);
System.out.println("The filter warranty years is : " + filter16.warrantyYears);
System.out.println("The filter weight is : " + filter16.filterWeight);
System.out.println("The filter washable status is : " + filter16.isWashable);
System.out.println("The filter color is : " + filter16.color);
System.out.println("The filter stock quantity is : " + filter16.stockQuantity);
System.out.println("The filter thickness is : " + filter16.thickness);
System.out.println("The filter certified status is : " + filter16.isCertified);
System.out.println("The filter country of origin is : " + filter16.countryOfOrigin);
System.out.println("The filter rating is : " + filter16.rating);
System.out.println("The filter temperature resistance is : " + filter16.temperatureResistance);
System.out.println("The filter high performance status is : " + filter16.isHighPerformance);
System.out.println("The filter certification type is : " + filter16.certificationType);

Filter filter17 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter17.filterName);
System.out.println("The filter id is : " + filter17.filterId);
System.out.println("The filter price is : " + filter17.filterPrice);
System.out.println("The filter availability is : " + filter17.isAvailable);
System.out.println("The filter type is : " + filter17.filterType);
System.out.println("The filter size is : " + filter17.filterSize);
System.out.println("The filter efficiency rate is : " + filter17.efficiencyRate);
System.out.println("The filter reusable status is : " + filter17.isReusable);
System.out.println("The filter manufacturer name is : " + filter17.manufacturerName);
System.out.println("The filter production year is : " + filter17.productionYear);
System.out.println("The filter flow rate is : " + filter17.flowRate);
System.out.println("The filter eco friendly status is : " + filter17.isEcoFriendly);
System.out.println("The filter material type is : " + filter17.materialType);
System.out.println("The filter warranty years is : " + filter17.warrantyYears);
System.out.println("The filter weight is : " + filter17.filterWeight);
System.out.println("The filter washable status is : " + filter17.isWashable);
System.out.println("The filter color is : " + filter17.color);
System.out.println("The filter stock quantity is : " + filter17.stockQuantity);
System.out.println("The filter thickness is : " + filter17.thickness);
System.out.println("The filter certified status is : " + filter17.isCertified);
System.out.println("The filter country of origin is : " + filter17.countryOfOrigin);
System.out.println("The filter rating is : " + filter17.rating);
System.out.println("The filter temperature resistance is : " + filter17.temperatureResistance);
System.out.println("The filter high performance status is : " + filter17.isHighPerformance);
System.out.println("The filter certification type is : " + filter17.certificationType);

filter17.filterName = "HydroFlow";
filter17.filterId = 117;
filter17.filterPrice = 555.60;
filter17.isAvailable = true;
filter17.filterType = "Water";
filter17.filterSize = 13;
filter17.efficiencyRate = 91.9;
filter17.isReusable = false;
filter17.manufacturerName = "HydroTech";
filter17.productionYear = 2022;
filter17.flowRate = 17.8;
filter17.isEcoFriendly = true;
filter17.materialType = "Fiber";
filter17.warrantyYears = 3;
filter17.filterWeight = 1.6;
filter17.isWashable = true;
filter17.color = "Blue";
filter17.stockQuantity = 41;
filter17.thickness = 0.66;
filter17.isCertified = true;
filter17.countryOfOrigin = "USA";
filter17.rating = 4;
filter17.temperatureResistance = 99.7;
filter17.isHighPerformance = true;
filter17.certificationType = "CE";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter17.filterName);
System.out.println("The filter id is : " + filter17.filterId);
System.out.println("The filter price is : " + filter17.filterPrice);
System.out.println("The filter availability is : " + filter17.isAvailable);
System.out.println("The filter type is : " + filter17.filterType);
System.out.println("The filter size is : " + filter17.filterSize);
System.out.println("The filter efficiency rate is : " + filter17.efficiencyRate);
System.out.println("The filter reusable status is : " + filter17.isReusable);
System.out.println("The filter manufacturer name is : " + filter17.manufacturerName);
System.out.println("The filter production year is : " + filter17.productionYear);
System.out.println("The filter flow rate is : " + filter17.flowRate);
System.out.println("The filter eco friendly status is : " + filter17.isEcoFriendly);
System.out.println("The filter material type is : " + filter17.materialType);
System.out.println("The filter warranty years is : " + filter17.warrantyYears);
System.out.println("The filter weight is : " + filter17.filterWeight);
System.out.println("The filter washable status is : " + filter17.isWashable);
System.out.println("The filter color is : " + filter17.color);
System.out.println("The filter stock quantity is : " + filter17.stockQuantity);
System.out.println("The filter thickness is : " + filter17.thickness);
System.out.println("The filter certified status is : " + filter17.isCertified);
System.out.println("The filter country of origin is : " + filter17.countryOfOrigin);
System.out.println("The filter rating is : " + filter17.rating);
System.out.println("The filter temperature resistance is : " + filter17.temperatureResistance);
System.out.println("The filter high performance status is : " + filter17.isHighPerformance);
System.out.println("The filter certification type is : " + filter17.certificationType);

Filter filter18 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter18.filterName);
System.out.println("The filter id is : " + filter18.filterId);
System.out.println("The filter price is : " + filter18.filterPrice);
System.out.println("The filter availability is : " + filter18.isAvailable);
System.out.println("The filter type is : " + filter18.filterType);
System.out.println("The filter size is : " + filter18.filterSize);
System.out.println("The filter efficiency rate is : " + filter18.efficiencyRate);
System.out.println("The filter reusable status is : " + filter18.isReusable);
System.out.println("The filter manufacturer name is : " + filter18.manufacturerName);
System.out.println("The filter production year is : " + filter18.productionYear);
System.out.println("The filter flow rate is : " + filter18.flowRate);
System.out.println("The filter eco friendly status is : " + filter18.isEcoFriendly);
System.out.println("The filter material type is : " + filter18.materialType);
System.out.println("The filter warranty years is : " + filter18.warrantyYears);
System.out.println("The filter weight is : " + filter18.filterWeight);
System.out.println("The filter washable status is : " + filter18.isWashable);
System.out.println("The filter color is : " + filter18.color);
System.out.println("The filter stock quantity is : " + filter18.stockQuantity);
System.out.println("The filter thickness is : " + filter18.thickness);
System.out.println("The filter certified status is : " + filter18.isCertified);
System.out.println("The filter country of origin is : " + filter18.countryOfOrigin);
System.out.println("The filter rating is : " + filter18.rating);
System.out.println("The filter temperature resistance is : " + filter18.temperatureResistance);
System.out.println("The filter high performance status is : " + filter18.isHighPerformance);
System.out.println("The filter certification type is : " + filter18.certificationType);

filter18.filterName = "DustFree";
filter18.filterId = 118;
filter18.filterPrice = 405.40;
filter18.isAvailable = true;
filter18.filterType = "Air";
filter18.filterSize = 10;
filter18.efficiencyRate = 87.2;
filter18.isReusable = true;
filter18.manufacturerName = "DustTech";
filter18.productionYear = 2021;
filter18.flowRate = 16.5;
filter18.isEcoFriendly = false;
filter18.materialType = "Foam";
filter18.warrantyYears = 1;
filter18.filterWeight = 0.92;
filter18.isWashable = false;
filter18.color = "Gray";
filter18.stockQuantity = 58;
filter18.thickness = 0.47;
filter18.isCertified = true;
filter18.countryOfOrigin = "Germany";
filter18.rating = 3;
filter18.temperatureResistance = 89.5;
filter18.isHighPerformance = false;
filter18.certificationType = "ISI";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter18.filterName);
System.out.println("The filter id is : " + filter18.filterId);
System.out.println("The filter price is : " + filter18.filterPrice);
System.out.println("The filter availability is : " + filter18.isAvailable);
System.out.println("The filter type is : " + filter18.filterType);
System.out.println("The filter size is : " + filter18.filterSize);
System.out.println("The filter efficiency rate is : " + filter18.efficiencyRate);
System.out.println("The filter reusable status is : " + filter18.isReusable);
System.out.println("The filter manufacturer name is : " + filter18.manufacturerName);
System.out.println("The filter production year is : " + filter18.productionYear);
System.out.println("The filter flow rate is : " + filter18.flowRate);
System.out.println("The filter eco friendly status is : " + filter18.isEcoFriendly);
System.out.println("The filter material type is : " + filter18.materialType);
System.out.println("The filter warranty years is : " + filter18.warrantyYears);
System.out.println("The filter weight is : " + filter18.filterWeight);
System.out.println("The filter washable status is : " + filter18.isWashable);
System.out.println("The filter color is : " + filter18.color);
System.out.println("The filter stock quantity is : " + filter18.stockQuantity);
System.out.println("The filter thickness is : " + filter18.thickness);
System.out.println("The filter certified status is : " + filter18.isCertified);
System.out.println("The filter country of origin is : " + filter18.countryOfOrigin);
System.out.println("The filter rating is : " + filter18.rating);
System.out.println("The filter temperature resistance is : " + filter18.temperatureResistance);
System.out.println("The filter high performance status is : " + filter18.isHighPerformance);
System.out.println("The filter certification type is : " + filter18.certificationType);

Filter filter19 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter19.filterName);
System.out.println("The filter id is : " + filter19.filterId);
System.out.println("The filter price is : " + filter19.filterPrice);
System.out.println("The filter availability is : " + filter19.isAvailable);
System.out.println("The filter type is : " + filter19.filterType);
System.out.println("The filter size is : " + filter19.filterSize);
System.out.println("The filter efficiency rate is : " + filter19.efficiencyRate);
System.out.println("The filter reusable status is : " + filter19.isReusable);
System.out.println("The filter manufacturer name is : " + filter19.manufacturerName);
System.out.println("The filter production year is : " + filter19.productionYear);
System.out.println("The filter flow rate is : " + filter19.flowRate);
System.out.println("The filter eco friendly status is : " + filter19.isEcoFriendly);
System.out.println("The filter material type is : " + filter19.materialType);
System.out.println("The filter warranty years is : " + filter19.warrantyYears);
System.out.println("The filter weight is : " + filter19.filterWeight);
System.out.println("The filter washable status is : " + filter19.isWashable);
System.out.println("The filter color is : " + filter19.color);
System.out.println("The filter stock quantity is : " + filter19.stockQuantity);
System.out.println("The filter thickness is : " + filter19.thickness);
System.out.println("The filter certified status is : " + filter19.isCertified);
System.out.println("The filter country of origin is : " + filter19.countryOfOrigin);
System.out.println("The filter rating is : " + filter19.rating);
System.out.println("The filter temperature resistance is : " + filter19.temperatureResistance);
System.out.println("The filter high performance status is : " + filter19.isHighPerformance);
System.out.println("The filter certification type is : " + filter19.certificationType);

filter19.filterName = "OilMaster";
filter19.filterId = 119;
filter19.filterPrice = 640.80;
filter19.isAvailable = true;
filter19.filterType = "Oil";
filter19.filterSize = 15;
filter19.efficiencyRate = 95.3;
filter19.isReusable = false;
filter19.manufacturerName = "OilTech";
filter19.productionYear = 2024;
filter19.flowRate = 24.6;
filter19.isEcoFriendly = true;
filter19.materialType = "Steel";
filter19.warrantyYears = 4;
filter19.filterWeight = 2.4;
filter19.isWashable = true;
filter19.color = "Silver";
filter19.stockQuantity = 26;
filter19.thickness = 0.84;
filter19.isCertified = true;
filter19.countryOfOrigin = "Japan";
filter19.rating = 5;
filter19.temperatureResistance = 130.6;
filter19.isHighPerformance = true;
filter19.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter19.filterName);
System.out.println("The filter id is : " + filter19.filterId);
System.out.println("The filter price is : " + filter19.filterPrice);
System.out.println("The filter availability is : " + filter19.isAvailable);
System.out.println("The filter type is : " + filter19.filterType);
System.out.println("The filter size is : " + filter19.filterSize);
System.out.println("The filter efficiency rate is : " + filter19.efficiencyRate);
System.out.println("The filter reusable status is : " + filter19.isReusable);
System.out.println("The filter manufacturer name is : " + filter19.manufacturerName);
System.out.println("The filter production year is : " + filter19.productionYear);
System.out.println("The filter flow rate is : " + filter19.flowRate);
System.out.println("The filter eco friendly status is : " + filter19.isEcoFriendly);
System.out.println("The filter material type is : " + filter19.materialType);
System.out.println("The filter warranty years is : " + filter19.warrantyYears);
System.out.println("The filter weight is : " + filter19.filterWeight);
System.out.println("The filter washable status is : " + filter19.isWashable);
System.out.println("The filter color is : " + filter19.color);
System.out.println("The filter stock quantity is : " + filter19.stockQuantity);
System.out.println("The filter thickness is : " + filter19.thickness);
System.out.println("The filter certified status is : " + filter19.isCertified);
System.out.println("The filter country of origin is : " + filter19.countryOfOrigin);
System.out.println("The filter rating is : " + filter19.rating);
System.out.println("The filter temperature resistance is : " + filter19.temperatureResistance);
System.out.println("The filter high performance status is : " + filter19.isHighPerformance);
System.out.println("The filter certification type is : " + filter19.certificationType);

Filter filter20 = new Filter();

System.out.println("Before initialization");

System.out.println("The filter name is : " + filter20.filterName);
System.out.println("The filter id is : " + filter20.filterId);
System.out.println("The filter price is : " + filter20.filterPrice);
System.out.println("The filter availability is : " + filter20.isAvailable);
System.out.println("The filter type is : " + filter20.filterType);
System.out.println("The filter size is : " + filter20.filterSize);
System.out.println("The filter efficiency rate is : " + filter20.efficiencyRate);
System.out.println("The filter reusable status is : " + filter20.isReusable);
System.out.println("The filter manufacturer name is : " + filter20.manufacturerName);
System.out.println("The filter production year is : " + filter20.productionYear);
System.out.println("The filter flow rate is : " + filter20.flowRate);
System.out.println("The filter eco friendly status is : " + filter20.isEcoFriendly);
System.out.println("The filter material type is : " + filter20.materialType);
System.out.println("The filter warranty years is : " + filter20.warrantyYears);
System.out.println("The filter weight is : " + filter20.filterWeight);
System.out.println("The filter washable status is : " + filter20.isWashable);
System.out.println("The filter color is : " + filter20.color);
System.out.println("The filter stock quantity is : " + filter20.stockQuantity);
System.out.println("The filter thickness is : " + filter20.thickness);
System.out.println("The filter certified status is : " + filter20.isCertified);
System.out.println("The filter country of origin is : " + filter20.countryOfOrigin);
System.out.println("The filter rating is : " + filter20.rating);
System.out.println("The filter temperature resistance is : " + filter20.temperatureResistance);
System.out.println("The filter high performance status is : " + filter20.isHighPerformance);
System.out.println("The filter certification type is : " + filter20.certificationType);

filter20.filterName = "UltraMax";
filter20.filterId = 120;
filter20.filterPrice = 760.50;
filter20.isAvailable = true;
filter20.filterType = "Air";
filter20.filterSize = 18;
filter20.efficiencyRate = 98.1;
filter20.isReusable = true;
filter20.manufacturerName = "UltraTech";
filter20.productionYear = 2025;
filter20.flowRate = 28.4;
filter20.isEcoFriendly = true;
filter20.materialType = "Carbon";
filter20.warrantyYears = 5;
filter20.filterWeight = 2.0;
filter20.isWashable = true;
filter20.color = "Black";
filter20.stockQuantity = 19;
filter20.thickness = 0.78;
filter20.isCertified = true;
filter20.countryOfOrigin = "India";
filter20.rating = 5;
filter20.temperatureResistance = 140.3;
filter20.isHighPerformance = true;
filter20.certificationType = "ISO";

System.out.println("After initialization");

System.out.println("The filter name is : " + filter20.filterName);
System.out.println("The filter id is : " + filter20.filterId);
System.out.println("The filter price is : " + filter20.filterPrice);
System.out.println("The filter availability is : " + filter20.isAvailable);
System.out.println("The filter type is : " + filter20.filterType);
System.out.println("The filter size is : " + filter20.filterSize);
System.out.println("The filter efficiency rate is : " + filter20.efficiencyRate);
System.out.println("The filter reusable status is : " + filter20.isReusable);
System.out.println("The filter manufacturer name is : " + filter20.manufacturerName);
System.out.println("The filter production year is : " + filter20.productionYear);
System.out.println("The filter flow rate is : " + filter20.flowRate);
System.out.println("The filter eco friendly status is : " + filter20.isEcoFriendly);
System.out.println("The filter material type is : " + filter20.materialType);
System.out.println("The filter warranty years is : " + filter20.warrantyYears);
System.out.println("The filter weight is : " + filter20.filterWeight);
System.out.println("The filter washable status is : " + filter20.isWashable);
System.out.println("The filter color is : " + filter20.color);
System.out.println("The filter stock quantity is : " + filter20.stockQuantity);
System.out.println("The filter thickness is : " + filter20.thickness);
System.out.println("The filter certified status is : " + filter20.isCertified);
System.out.println("The filter country of origin is : " + filter20.countryOfOrigin);
System.out.println("The filter rating is : " + filter20.rating);
System.out.println("The filter temperature resistance is : " + filter20.temperatureResistance);
System.out.println("The filter high performance status is : " + filter20.isHighPerformance);
System.out.println("The filter certification type is : " + filter20.certificationType);

		
	}
}