class HoverBoardExecutor {

    public static void main(String[] args) {

        HoverBoard board1 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board1.boardBrand);
        System.out.println("The boardId is : " + board1.boardId);
        System.out.println("The boardPrice is : " + board1.boardPrice);
        System.out.println("The isAvailable is : " + board1.isAvailable);
        System.out.println("The boardType is : " + board1.boardType);
        System.out.println("The maxSpeed is : " + board1.maxSpeed);
        System.out.println("The weight is : " + board1.weight);
        System.out.println("The isBluetoothEnabled is : " + board1.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board1.batteryType);
        System.out.println("The warrantyYears is : " + board1.warrantyYears);
        System.out.println("The rangeKm is : " + board1.rangeKm);
        System.out.println("The hasLEDLights is : " + board1.hasLEDLights);
        System.out.println("The color is : " + board1.color);
        System.out.println("The stockQuantity is : " + board1.stockQuantity);
        System.out.println("The chargingTime is : " + board1.chargingTime);
        System.out.println("The isEcoFriendly is : " + board1.isEcoFriendly);
        System.out.println("The wheelType is : " + board1.wheelType);
        System.out.println("The rating is : " + board1.rating);
        System.out.println("The motorPower is : " + board1.motorPower);
        System.out.println("The isCertified is : " + board1.isCertified);
        System.out.println("The countryOfOrigin is : " + board1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board1.manufacturingYear);
        System.out.println("The wheelSize is : " + board1.wheelSize);
        System.out.println("The supportsAppControl is : " + board1.supportsAppControl);
        System.out.println("The certificationType is : " + board1.certificationType);

        board1.boardBrand = "SmartRide";
        board1.boardId = 1;
        board1.boardPrice = 1000.50;
        board1.isAvailable = true;
        board1.boardType = "Self Balancing";
        board1.maxSpeed = 15.0;
        board1.weight = 10.5;
        board1.isBluetoothEnabled = true;
        board1.batteryType = "Lithium Ion";
        board1.warrantyYears = 1;
        board1.rangeKm = 20.0;
        board1.hasLEDLights = true;
        board1.color = "Black";
        board1.stockQuantity = 18;
        board1.chargingTime = 2.5;
        board1.isEcoFriendly = true;
        board1.wheelType = "Rubber";
        board1.rating = 4;
        board1.motorPower = 700.0;
        board1.isCertified = true;
        board1.countryOfOrigin = "China";
        board1.manufacturingYear = 2025;
        board1.wheelSize = 6.5;
        board1.supportsAppControl = true;
        board1.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board1.boardBrand);
        System.out.println("The boardId is : " + board1.boardId);
        System.out.println("The boardPrice is : " + board1.boardPrice);
        System.out.println("The isAvailable is : " + board1.isAvailable);
        System.out.println("The boardType is : " + board1.boardType);
        System.out.println("The maxSpeed is : " + board1.maxSpeed);
        System.out.println("The weight is : " + board1.weight);
        System.out.println("The isBluetoothEnabled is : " + board1.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board1.batteryType);
        System.out.println("The warrantyYears is : " + board1.warrantyYears);
        System.out.println("The rangeKm is : " + board1.rangeKm);
        System.out.println("The hasLEDLights is : " + board1.hasLEDLights);
        System.out.println("The color is : " + board1.color);
        System.out.println("The stockQuantity is : " + board1.stockQuantity);
        System.out.println("The chargingTime is : " + board1.chargingTime);
        System.out.println("The isEcoFriendly is : " + board1.isEcoFriendly);
        System.out.println("The wheelType is : " + board1.wheelType);
        System.out.println("The rating is : " + board1.rating);
        System.out.println("The motorPower is : " + board1.motorPower);
        System.out.println("The isCertified is : " + board1.isCertified);
        System.out.println("The countryOfOrigin is : " + board1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board1.manufacturingYear);
        System.out.println("The wheelSize is : " + board1.wheelSize);
        System.out.println("The supportsAppControl is : " + board1.supportsAppControl);
        System.out.println("The certificationType is : " + board1.certificationType);


        HoverBoard board2 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board2.boardBrand);
        System.out.println("The boardId is : " + board2.boardId);
        System.out.println("The boardPrice is : " + board2.boardPrice);
        System.out.println("The isAvailable is : " + board2.isAvailable);
        System.out.println("The boardType is : " + board2.boardType);
        System.out.println("The maxSpeed is : " + board2.maxSpeed);
        System.out.println("The weight is : " + board2.weight);
        System.out.println("The isBluetoothEnabled is : " + board2.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board2.batteryType);
        System.out.println("The warrantyYears is : " + board2.warrantyYears);
        System.out.println("The rangeKm is : " + board2.rangeKm);
        System.out.println("The hasLEDLights is : " + board2.hasLEDLights);
        System.out.println("The color is : " + board2.color);
        System.out.println("The stockQuantity is : " + board2.stockQuantity);
        System.out.println("The chargingTime is : " + board2.chargingTime);
        System.out.println("The isEcoFriendly is : " + board2.isEcoFriendly);
        System.out.println("The wheelType is : " + board2.wheelType);
        System.out.println("The rating is : " + board2.rating);
        System.out.println("The motorPower is : " + board2.motorPower);
        System.out.println("The isCertified is : " + board2.isCertified);
        System.out.println("The countryOfOrigin is : " + board2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board2.manufacturingYear);
        System.out.println("The wheelSize is : " + board2.wheelSize);
        System.out.println("The supportsAppControl is : " + board2.supportsAppControl);
        System.out.println("The certificationType is : " + board2.certificationType);

        board2.boardBrand = "SmartRide";
        board2.boardId = 2;
        board2.boardPrice = 2000.50;
        board2.isAvailable = true;
        board2.boardType = "Self Balancing";
        board2.maxSpeed = 15.0;
        board2.weight = 10.5;
        board2.isBluetoothEnabled = true;
        board2.batteryType = "Lithium Ion";
        board2.warrantyYears = 1;
        board2.rangeKm = 20.0;
        board2.hasLEDLights = true;
        board2.color = "Black";
        board2.stockQuantity = 18;
        board2.chargingTime = 2.5;
        board2.isEcoFriendly = true;
        board2.wheelType = "Rubber";
        board2.rating = 4;
        board2.motorPower = 700.0;
        board2.isCertified = true;
        board2.countryOfOrigin = "China";
        board2.manufacturingYear = 2025;
        board2.wheelSize = 6.5;
        board2.supportsAppControl = true;
        board2.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board2.boardBrand);
        System.out.println("The boardId is : " + board2.boardId);
        System.out.println("The boardPrice is : " + board2.boardPrice);
        System.out.println("The isAvailable is : " + board2.isAvailable);
        System.out.println("The boardType is : " + board2.boardType);
        System.out.println("The maxSpeed is : " + board2.maxSpeed);
        System.out.println("The weight is : " + board2.weight);
        System.out.println("The isBluetoothEnabled is : " + board2.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board2.batteryType);
        System.out.println("The warrantyYears is : " + board2.warrantyYears);
        System.out.println("The rangeKm is : " + board2.rangeKm);
        System.out.println("The hasLEDLights is : " + board2.hasLEDLights);
        System.out.println("The color is : " + board2.color);
        System.out.println("The stockQuantity is : " + board2.stockQuantity);
        System.out.println("The chargingTime is : " + board2.chargingTime);
        System.out.println("The isEcoFriendly is : " + board2.isEcoFriendly);
        System.out.println("The wheelType is : " + board2.wheelType);
        System.out.println("The rating is : " + board2.rating);
        System.out.println("The motorPower is : " + board2.motorPower);
        System.out.println("The isCertified is : " + board2.isCertified);
        System.out.println("The countryOfOrigin is : " + board2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board2.manufacturingYear);
        System.out.println("The wheelSize is : " + board2.wheelSize);
        System.out.println("The supportsAppControl is : " + board2.supportsAppControl);
        System.out.println("The certificationType is : " + board2.certificationType);


        HoverBoard board3 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board3.boardBrand);
        System.out.println("The boardId is : " + board3.boardId);
        System.out.println("The boardPrice is : " + board3.boardPrice);
        System.out.println("The isAvailable is : " + board3.isAvailable);
        System.out.println("The boardType is : " + board3.boardType);
        System.out.println("The maxSpeed is : " + board3.maxSpeed);
        System.out.println("The weight is : " + board3.weight);
        System.out.println("The isBluetoothEnabled is : " + board3.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board3.batteryType);
        System.out.println("The warrantyYears is : " + board3.warrantyYears);
        System.out.println("The rangeKm is : " + board3.rangeKm);
        System.out.println("The hasLEDLights is : " + board3.hasLEDLights);
        System.out.println("The color is : " + board3.color);
        System.out.println("The stockQuantity is : " + board3.stockQuantity);
        System.out.println("The chargingTime is : " + board3.chargingTime);
        System.out.println("The isEcoFriendly is : " + board3.isEcoFriendly);
        System.out.println("The wheelType is : " + board3.wheelType);
        System.out.println("The rating is : " + board3.rating);
        System.out.println("The motorPower is : " + board3.motorPower);
        System.out.println("The isCertified is : " + board3.isCertified);
        System.out.println("The countryOfOrigin is : " + board3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board3.manufacturingYear);
        System.out.println("The wheelSize is : " + board3.wheelSize);
        System.out.println("The supportsAppControl is : " + board3.supportsAppControl);
        System.out.println("The certificationType is : " + board3.certificationType);

        board3.boardBrand = "SmartRide";
        board3.boardId = 3;
        board3.boardPrice = 3000.50;
        board3.isAvailable = true;
        board3.boardType = "Self Balancing";
        board3.maxSpeed = 15.0;
        board3.weight = 10.5;
        board3.isBluetoothEnabled = true;
        board3.batteryType = "Lithium Ion";
        board3.warrantyYears = 1;
        board3.rangeKm = 20.0;
        board3.hasLEDLights = true;
        board3.color = "Black";
        board3.stockQuantity = 18;
        board3.chargingTime = 2.5;
        board3.isEcoFriendly = true;
        board3.wheelType = "Rubber";
        board3.rating = 4;
        board3.motorPower = 700.0;
        board3.isCertified = true;
        board3.countryOfOrigin = "China";
        board3.manufacturingYear = 2025;
        board3.wheelSize = 6.5;
        board3.supportsAppControl = true;
        board3.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board3.boardBrand);
        System.out.println("The boardId is : " + board3.boardId);
        System.out.println("The boardPrice is : " + board3.boardPrice);
        System.out.println("The isAvailable is : " + board3.isAvailable);
        System.out.println("The boardType is : " + board3.boardType);
        System.out.println("The maxSpeed is : " + board3.maxSpeed);
        System.out.println("The weight is : " + board3.weight);
        System.out.println("The isBluetoothEnabled is : " + board3.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board3.batteryType);
        System.out.println("The warrantyYears is : " + board3.warrantyYears);
        System.out.println("The rangeKm is : " + board3.rangeKm);
        System.out.println("The hasLEDLights is : " + board3.hasLEDLights);
        System.out.println("The color is : " + board3.color);
        System.out.println("The stockQuantity is : " + board3.stockQuantity);
        System.out.println("The chargingTime is : " + board3.chargingTime);
        System.out.println("The isEcoFriendly is : " + board3.isEcoFriendly);
        System.out.println("The wheelType is : " + board3.wheelType);
        System.out.println("The rating is : " + board3.rating);
        System.out.println("The motorPower is : " + board3.motorPower);
        System.out.println("The isCertified is : " + board3.isCertified);
        System.out.println("The countryOfOrigin is : " + board3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board3.manufacturingYear);
        System.out.println("The wheelSize is : " + board3.wheelSize);
        System.out.println("The supportsAppControl is : " + board3.supportsAppControl);
        System.out.println("The certificationType is : " + board3.certificationType);


        HoverBoard board4 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board4.boardBrand);
        System.out.println("The boardId is : " + board4.boardId);
        System.out.println("The boardPrice is : " + board4.boardPrice);
        System.out.println("The isAvailable is : " + board4.isAvailable);
        System.out.println("The boardType is : " + board4.boardType);
        System.out.println("The maxSpeed is : " + board4.maxSpeed);
        System.out.println("The weight is : " + board4.weight);
        System.out.println("The isBluetoothEnabled is : " + board4.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board4.batteryType);
        System.out.println("The warrantyYears is : " + board4.warrantyYears);
        System.out.println("The rangeKm is : " + board4.rangeKm);
        System.out.println("The hasLEDLights is : " + board4.hasLEDLights);
        System.out.println("The color is : " + board4.color);
        System.out.println("The stockQuantity is : " + board4.stockQuantity);
        System.out.println("The chargingTime is : " + board4.chargingTime);
        System.out.println("The isEcoFriendly is : " + board4.isEcoFriendly);
        System.out.println("The wheelType is : " + board4.wheelType);
        System.out.println("The rating is : " + board4.rating);
        System.out.println("The motorPower is : " + board4.motorPower);
        System.out.println("The isCertified is : " + board4.isCertified);
        System.out.println("The countryOfOrigin is : " + board4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board4.manufacturingYear);
        System.out.println("The wheelSize is : " + board4.wheelSize);
        System.out.println("The supportsAppControl is : " + board4.supportsAppControl);
        System.out.println("The certificationType is : " + board4.certificationType);

        board4.boardBrand = "SmartRide";
        board4.boardId = 4;
        board4.boardPrice = 4000.50;
        board4.isAvailable = true;
        board4.boardType = "Self Balancing";
        board4.maxSpeed = 15.0;
        board4.weight = 10.5;
        board4.isBluetoothEnabled = true;
        board4.batteryType = "Lithium Ion";
        board4.warrantyYears = 1;
        board4.rangeKm = 20.0;
        board4.hasLEDLights = true;
        board4.color = "Black";
        board4.stockQuantity = 18;
        board4.chargingTime = 2.5;
        board4.isEcoFriendly = true;
        board4.wheelType = "Rubber";
        board4.rating = 4;
        board4.motorPower = 700.0;
        board4.isCertified = true;
        board4.countryOfOrigin = "China";
        board4.manufacturingYear = 2025;
        board4.wheelSize = 6.5;
        board4.supportsAppControl = true;
        board4.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board4.boardBrand);
        System.out.println("The boardId is : " + board4.boardId);
        System.out.println("The boardPrice is : " + board4.boardPrice);
        System.out.println("The isAvailable is : " + board4.isAvailable);
        System.out.println("The boardType is : " + board4.boardType);
        System.out.println("The maxSpeed is : " + board4.maxSpeed);
        System.out.println("The weight is : " + board4.weight);
        System.out.println("The isBluetoothEnabled is : " + board4.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board4.batteryType);
        System.out.println("The warrantyYears is : " + board4.warrantyYears);
        System.out.println("The rangeKm is : " + board4.rangeKm);
        System.out.println("The hasLEDLights is : " + board4.hasLEDLights);
        System.out.println("The color is : " + board4.color);
        System.out.println("The stockQuantity is : " + board4.stockQuantity);
        System.out.println("The chargingTime is : " + board4.chargingTime);
        System.out.println("The isEcoFriendly is : " + board4.isEcoFriendly);
        System.out.println("The wheelType is : " + board4.wheelType);
        System.out.println("The rating is : " + board4.rating);
        System.out.println("The motorPower is : " + board4.motorPower);
        System.out.println("The isCertified is : " + board4.isCertified);
        System.out.println("The countryOfOrigin is : " + board4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board4.manufacturingYear);
        System.out.println("The wheelSize is : " + board4.wheelSize);
        System.out.println("The supportsAppControl is : " + board4.supportsAppControl);
        System.out.println("The certificationType is : " + board4.certificationType);


        HoverBoard board5 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board5.boardBrand);
        System.out.println("The boardId is : " + board5.boardId);
        System.out.println("The boardPrice is : " + board5.boardPrice);
        System.out.println("The isAvailable is : " + board5.isAvailable);
        System.out.println("The boardType is : " + board5.boardType);
        System.out.println("The maxSpeed is : " + board5.maxSpeed);
        System.out.println("The weight is : " + board5.weight);
        System.out.println("The isBluetoothEnabled is : " + board5.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board5.batteryType);
        System.out.println("The warrantyYears is : " + board5.warrantyYears);
        System.out.println("The rangeKm is : " + board5.rangeKm);
        System.out.println("The hasLEDLights is : " + board5.hasLEDLights);
        System.out.println("The color is : " + board5.color);
        System.out.println("The stockQuantity is : " + board5.stockQuantity);
        System.out.println("The chargingTime is : " + board5.chargingTime);
        System.out.println("The isEcoFriendly is : " + board5.isEcoFriendly);
        System.out.println("The wheelType is : " + board5.wheelType);
        System.out.println("The rating is : " + board5.rating);
        System.out.println("The motorPower is : " + board5.motorPower);
        System.out.println("The isCertified is : " + board5.isCertified);
        System.out.println("The countryOfOrigin is : " + board5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board5.manufacturingYear);
        System.out.println("The wheelSize is : " + board5.wheelSize);
        System.out.println("The supportsAppControl is : " + board5.supportsAppControl);
        System.out.println("The certificationType is : " + board5.certificationType);

        board5.boardBrand = "SmartRide";
        board5.boardId = 5;
        board5.boardPrice = 5000.50;
        board5.isAvailable = true;
        board5.boardType = "Self Balancing";
        board5.maxSpeed = 15.0;
        board5.weight = 10.5;
        board5.isBluetoothEnabled = true;
        board5.batteryType = "Lithium Ion";
        board5.warrantyYears = 1;
        board5.rangeKm = 20.0;
        board5.hasLEDLights = true;
        board5.color = "Black";
        board5.stockQuantity = 18;
        board5.chargingTime = 2.5;
        board5.isEcoFriendly = true;
        board5.wheelType = "Rubber";
        board5.rating = 4;
        board5.motorPower = 700.0;
        board5.isCertified = true;
        board5.countryOfOrigin = "China";
        board5.manufacturingYear = 2025;
        board5.wheelSize = 6.5;
        board5.supportsAppControl = true;
        board5.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board5.boardBrand);
        System.out.println("The boardId is : " + board5.boardId);
        System.out.println("The boardPrice is : " + board5.boardPrice);
        System.out.println("The isAvailable is : " + board5.isAvailable);
        System.out.println("The boardType is : " + board5.boardType);
        System.out.println("The maxSpeed is : " + board5.maxSpeed);
        System.out.println("The weight is : " + board5.weight);
        System.out.println("The isBluetoothEnabled is : " + board5.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board5.batteryType);
        System.out.println("The warrantyYears is : " + board5.warrantyYears);
        System.out.println("The rangeKm is : " + board5.rangeKm);
        System.out.println("The hasLEDLights is : " + board5.hasLEDLights);
        System.out.println("The color is : " + board5.color);
        System.out.println("The stockQuantity is : " + board5.stockQuantity);
        System.out.println("The chargingTime is : " + board5.chargingTime);
        System.out.println("The isEcoFriendly is : " + board5.isEcoFriendly);
        System.out.println("The wheelType is : " + board5.wheelType);
        System.out.println("The rating is : " + board5.rating);
        System.out.println("The motorPower is : " + board5.motorPower);
        System.out.println("The isCertified is : " + board5.isCertified);
        System.out.println("The countryOfOrigin is : " + board5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board5.manufacturingYear);
        System.out.println("The wheelSize is : " + board5.wheelSize);
        System.out.println("The supportsAppControl is : " + board5.supportsAppControl);
        System.out.println("The certificationType is : " + board5.certificationType);


        HoverBoard board6 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board6.boardBrand);
        System.out.println("The boardId is : " + board6.boardId);
        System.out.println("The boardPrice is : " + board6.boardPrice);
        System.out.println("The isAvailable is : " + board6.isAvailable);
        System.out.println("The boardType is : " + board6.boardType);
        System.out.println("The maxSpeed is : " + board6.maxSpeed);
        System.out.println("The weight is : " + board6.weight);
        System.out.println("The isBluetoothEnabled is : " + board6.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board6.batteryType);
        System.out.println("The warrantyYears is : " + board6.warrantyYears);
        System.out.println("The rangeKm is : " + board6.rangeKm);
        System.out.println("The hasLEDLights is : " + board6.hasLEDLights);
        System.out.println("The color is : " + board6.color);
        System.out.println("The stockQuantity is : " + board6.stockQuantity);
        System.out.println("The chargingTime is : " + board6.chargingTime);
        System.out.println("The isEcoFriendly is : " + board6.isEcoFriendly);
        System.out.println("The wheelType is : " + board6.wheelType);
        System.out.println("The rating is : " + board6.rating);
        System.out.println("The motorPower is : " + board6.motorPower);
        System.out.println("The isCertified is : " + board6.isCertified);
        System.out.println("The countryOfOrigin is : " + board6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board6.manufacturingYear);
        System.out.println("The wheelSize is : " + board6.wheelSize);
        System.out.println("The supportsAppControl is : " + board6.supportsAppControl);
        System.out.println("The certificationType is : " + board6.certificationType);

        board6.boardBrand = "SmartRide";
        board6.boardId = 6;
        board6.boardPrice = 6000.50;
        board6.isAvailable = true;
        board6.boardType = "Self Balancing";
        board6.maxSpeed = 15.0;
        board6.weight = 10.5;
        board6.isBluetoothEnabled = true;
        board6.batteryType = "Lithium Ion";
        board6.warrantyYears = 1;
        board6.rangeKm = 20.0;
        board6.hasLEDLights = true;
        board6.color = "Black";
        board6.stockQuantity = 18;
        board6.chargingTime = 2.5;
        board6.isEcoFriendly = true;
        board6.wheelType = "Rubber";
        board6.rating = 4;
        board6.motorPower = 700.0;
        board6.isCertified = true;
        board6.countryOfOrigin = "China";
        board6.manufacturingYear = 2025;
        board6.wheelSize = 6.5;
        board6.supportsAppControl = true;
        board6.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board6.boardBrand);
        System.out.println("The boardId is : " + board6.boardId);
        System.out.println("The boardPrice is : " + board6.boardPrice);
        System.out.println("The isAvailable is : " + board6.isAvailable);
        System.out.println("The boardType is : " + board6.boardType);
        System.out.println("The maxSpeed is : " + board6.maxSpeed);
        System.out.println("The weight is : " + board6.weight);
        System.out.println("The isBluetoothEnabled is : " + board6.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board6.batteryType);
        System.out.println("The warrantyYears is : " + board6.warrantyYears);
        System.out.println("The rangeKm is : " + board6.rangeKm);
        System.out.println("The hasLEDLights is : " + board6.hasLEDLights);
        System.out.println("The color is : " + board6.color);
        System.out.println("The stockQuantity is : " + board6.stockQuantity);
        System.out.println("The chargingTime is : " + board6.chargingTime);
        System.out.println("The isEcoFriendly is : " + board6.isEcoFriendly);
        System.out.println("The wheelType is : " + board6.wheelType);
        System.out.println("The rating is : " + board6.rating);
        System.out.println("The motorPower is : " + board6.motorPower);
        System.out.println("The isCertified is : " + board6.isCertified);
        System.out.println("The countryOfOrigin is : " + board6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board6.manufacturingYear);
        System.out.println("The wheelSize is : " + board6.wheelSize);
        System.out.println("The supportsAppControl is : " + board6.supportsAppControl);
        System.out.println("The certificationType is : " + board6.certificationType);


        HoverBoard board7 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board7.boardBrand);
        System.out.println("The boardId is : " + board7.boardId);
        System.out.println("The boardPrice is : " + board7.boardPrice);
        System.out.println("The isAvailable is : " + board7.isAvailable);
        System.out.println("The boardType is : " + board7.boardType);
        System.out.println("The maxSpeed is : " + board7.maxSpeed);
        System.out.println("The weight is : " + board7.weight);
        System.out.println("The isBluetoothEnabled is : " + board7.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board7.batteryType);
        System.out.println("The warrantyYears is : " + board7.warrantyYears);
        System.out.println("The rangeKm is : " + board7.rangeKm);
        System.out.println("The hasLEDLights is : " + board7.hasLEDLights);
        System.out.println("The color is : " + board7.color);
        System.out.println("The stockQuantity is : " + board7.stockQuantity);
        System.out.println("The chargingTime is : " + board7.chargingTime);
        System.out.println("The isEcoFriendly is : " + board7.isEcoFriendly);
        System.out.println("The wheelType is : " + board7.wheelType);
        System.out.println("The rating is : " + board7.rating);
        System.out.println("The motorPower is : " + board7.motorPower);
        System.out.println("The isCertified is : " + board7.isCertified);
        System.out.println("The countryOfOrigin is : " + board7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board7.manufacturingYear);
        System.out.println("The wheelSize is : " + board7.wheelSize);
        System.out.println("The supportsAppControl is : " + board7.supportsAppControl);
        System.out.println("The certificationType is : " + board7.certificationType);

        board7.boardBrand = "SmartRide";
        board7.boardId = 7;
        board7.boardPrice = 7000.50;
        board7.isAvailable = true;
        board7.boardType = "Self Balancing";
        board7.maxSpeed = 15.0;
        board7.weight = 10.5;
        board7.isBluetoothEnabled = true;
        board7.batteryType = "Lithium Ion";
        board7.warrantyYears = 1;
        board7.rangeKm = 20.0;
        board7.hasLEDLights = true;
        board7.color = "Black";
        board7.stockQuantity = 18;
        board7.chargingTime = 2.5;
        board7.isEcoFriendly = true;
        board7.wheelType = "Rubber";
        board7.rating = 4;
        board7.motorPower = 700.0;
        board7.isCertified = true;
        board7.countryOfOrigin = "China";
        board7.manufacturingYear = 2025;
        board7.wheelSize = 6.5;
        board7.supportsAppControl = true;
        board7.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board7.boardBrand);
        System.out.println("The boardId is : " + board7.boardId);
        System.out.println("The boardPrice is : " + board7.boardPrice);
        System.out.println("The isAvailable is : " + board7.isAvailable);
        System.out.println("The boardType is : " + board7.boardType);
        System.out.println("The maxSpeed is : " + board7.maxSpeed);
        System.out.println("The weight is : " + board7.weight);
        System.out.println("The isBluetoothEnabled is : " + board7.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board7.batteryType);
        System.out.println("The warrantyYears is : " + board7.warrantyYears);
        System.out.println("The rangeKm is : " + board7.rangeKm);
        System.out.println("The hasLEDLights is : " + board7.hasLEDLights);
        System.out.println("The color is : " + board7.color);
        System.out.println("The stockQuantity is : " + board7.stockQuantity);
        System.out.println("The chargingTime is : " + board7.chargingTime);
        System.out.println("The isEcoFriendly is : " + board7.isEcoFriendly);
        System.out.println("The wheelType is : " + board7.wheelType);
        System.out.println("The rating is : " + board7.rating);
        System.out.println("The motorPower is : " + board7.motorPower);
        System.out.println("The isCertified is : " + board7.isCertified);
        System.out.println("The countryOfOrigin is : " + board7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board7.manufacturingYear);
        System.out.println("The wheelSize is : " + board7.wheelSize);
        System.out.println("The supportsAppControl is : " + board7.supportsAppControl);
        System.out.println("The certificationType is : " + board7.certificationType);


        HoverBoard board8 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board8.boardBrand);
        System.out.println("The boardId is : " + board8.boardId);
        System.out.println("The boardPrice is : " + board8.boardPrice);
        System.out.println("The isAvailable is : " + board8.isAvailable);
        System.out.println("The boardType is : " + board8.boardType);
        System.out.println("The maxSpeed is : " + board8.maxSpeed);
        System.out.println("The weight is : " + board8.weight);
        System.out.println("The isBluetoothEnabled is : " + board8.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board8.batteryType);
        System.out.println("The warrantyYears is : " + board8.warrantyYears);
        System.out.println("The rangeKm is : " + board8.rangeKm);
        System.out.println("The hasLEDLights is : " + board8.hasLEDLights);
        System.out.println("The color is : " + board8.color);
        System.out.println("The stockQuantity is : " + board8.stockQuantity);
        System.out.println("The chargingTime is : " + board8.chargingTime);
        System.out.println("The isEcoFriendly is : " + board8.isEcoFriendly);
        System.out.println("The wheelType is : " + board8.wheelType);
        System.out.println("The rating is : " + board8.rating);
        System.out.println("The motorPower is : " + board8.motorPower);
        System.out.println("The isCertified is : " + board8.isCertified);
        System.out.println("The countryOfOrigin is : " + board8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board8.manufacturingYear);
        System.out.println("The wheelSize is : " + board8.wheelSize);
        System.out.println("The supportsAppControl is : " + board8.supportsAppControl);
        System.out.println("The certificationType is : " + board8.certificationType);

        board8.boardBrand = "SmartRide";
        board8.boardId = 8;
        board8.boardPrice = 8000.50;
        board8.isAvailable = true;
        board8.boardType = "Self Balancing";
        board8.maxSpeed = 15.0;
        board8.weight = 10.5;
        board8.isBluetoothEnabled = true;
        board8.batteryType = "Lithium Ion";
        board8.warrantyYears = 1;
        board8.rangeKm = 20.0;
        board8.hasLEDLights = true;
        board8.color = "Black";
        board8.stockQuantity = 18;
        board8.chargingTime = 2.5;
        board8.isEcoFriendly = true;
        board8.wheelType = "Rubber";
        board8.rating = 4;
        board8.motorPower = 700.0;
        board8.isCertified = true;
        board8.countryOfOrigin = "China";
        board8.manufacturingYear = 2025;
        board8.wheelSize = 6.5;
        board8.supportsAppControl = true;
        board8.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board8.boardBrand);
        System.out.println("The boardId is : " + board8.boardId);
        System.out.println("The boardPrice is : " + board8.boardPrice);
        System.out.println("The isAvailable is : " + board8.isAvailable);
        System.out.println("The boardType is : " + board8.boardType);
        System.out.println("The maxSpeed is : " + board8.maxSpeed);
        System.out.println("The weight is : " + board8.weight);
        System.out.println("The isBluetoothEnabled is : " + board8.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board8.batteryType);
        System.out.println("The warrantyYears is : " + board8.warrantyYears);
        System.out.println("The rangeKm is : " + board8.rangeKm);
        System.out.println("The hasLEDLights is : " + board8.hasLEDLights);
        System.out.println("The color is : " + board8.color);
        System.out.println("The stockQuantity is : " + board8.stockQuantity);
        System.out.println("The chargingTime is : " + board8.chargingTime);
        System.out.println("The isEcoFriendly is : " + board8.isEcoFriendly);
        System.out.println("The wheelType is : " + board8.wheelType);
        System.out.println("The rating is : " + board8.rating);
        System.out.println("The motorPower is : " + board8.motorPower);
        System.out.println("The isCertified is : " + board8.isCertified);
        System.out.println("The countryOfOrigin is : " + board8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board8.manufacturingYear);
        System.out.println("The wheelSize is : " + board8.wheelSize);
        System.out.println("The supportsAppControl is : " + board8.supportsAppControl);
        System.out.println("The certificationType is : " + board8.certificationType);


        HoverBoard board9 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board9.boardBrand);
        System.out.println("The boardId is : " + board9.boardId);
        System.out.println("The boardPrice is : " + board9.boardPrice);
        System.out.println("The isAvailable is : " + board9.isAvailable);
        System.out.println("The boardType is : " + board9.boardType);
        System.out.println("The maxSpeed is : " + board9.maxSpeed);
        System.out.println("The weight is : " + board9.weight);
        System.out.println("The isBluetoothEnabled is : " + board9.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board9.batteryType);
        System.out.println("The warrantyYears is : " + board9.warrantyYears);
        System.out.println("The rangeKm is : " + board9.rangeKm);
        System.out.println("The hasLEDLights is : " + board9.hasLEDLights);
        System.out.println("The color is : " + board9.color);
        System.out.println("The stockQuantity is : " + board9.stockQuantity);
        System.out.println("The chargingTime is : " + board9.chargingTime);
        System.out.println("The isEcoFriendly is : " + board9.isEcoFriendly);
        System.out.println("The wheelType is : " + board9.wheelType);
        System.out.println("The rating is : " + board9.rating);
        System.out.println("The motorPower is : " + board9.motorPower);
        System.out.println("The isCertified is : " + board9.isCertified);
        System.out.println("The countryOfOrigin is : " + board9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board9.manufacturingYear);
        System.out.println("The wheelSize is : " + board9.wheelSize);
        System.out.println("The supportsAppControl is : " + board9.supportsAppControl);
        System.out.println("The certificationType is : " + board9.certificationType);

        board9.boardBrand = "SmartRide";
        board9.boardId = 9;
        board9.boardPrice = 9000.50;
        board9.isAvailable = true;
        board9.boardType = "Self Balancing";
        board9.maxSpeed = 15.0;
        board9.weight = 10.5;
        board9.isBluetoothEnabled = true;
        board9.batteryType = "Lithium Ion";
        board9.warrantyYears = 1;
        board9.rangeKm = 20.0;
        board9.hasLEDLights = true;
        board9.color = "Black";
        board9.stockQuantity = 18;
        board9.chargingTime = 2.5;
        board9.isEcoFriendly = true;
        board9.wheelType = "Rubber";
        board9.rating = 4;
        board9.motorPower = 700.0;
        board9.isCertified = true;
        board9.countryOfOrigin = "China";
        board9.manufacturingYear = 2025;
        board9.wheelSize = 6.5;
        board9.supportsAppControl = true;
        board9.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board9.boardBrand);
        System.out.println("The boardId is : " + board9.boardId);
        System.out.println("The boardPrice is : " + board9.boardPrice);
        System.out.println("The isAvailable is : " + board9.isAvailable);
        System.out.println("The boardType is : " + board9.boardType);
        System.out.println("The maxSpeed is : " + board9.maxSpeed);
        System.out.println("The weight is : " + board9.weight);
        System.out.println("The isBluetoothEnabled is : " + board9.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board9.batteryType);
        System.out.println("The warrantyYears is : " + board9.warrantyYears);
        System.out.println("The rangeKm is : " + board9.rangeKm);
        System.out.println("The hasLEDLights is : " + board9.hasLEDLights);
        System.out.println("The color is : " + board9.color);
        System.out.println("The stockQuantity is : " + board9.stockQuantity);
        System.out.println("The chargingTime is : " + board9.chargingTime);
        System.out.println("The isEcoFriendly is : " + board9.isEcoFriendly);
        System.out.println("The wheelType is : " + board9.wheelType);
        System.out.println("The rating is : " + board9.rating);
        System.out.println("The motorPower is : " + board9.motorPower);
        System.out.println("The isCertified is : " + board9.isCertified);
        System.out.println("The countryOfOrigin is : " + board9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board9.manufacturingYear);
        System.out.println("The wheelSize is : " + board9.wheelSize);
        System.out.println("The supportsAppControl is : " + board9.supportsAppControl);
        System.out.println("The certificationType is : " + board9.certificationType);


        HoverBoard board10 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board10.boardBrand);
        System.out.println("The boardId is : " + board10.boardId);
        System.out.println("The boardPrice is : " + board10.boardPrice);
        System.out.println("The isAvailable is : " + board10.isAvailable);
        System.out.println("The boardType is : " + board10.boardType);
        System.out.println("The maxSpeed is : " + board10.maxSpeed);
        System.out.println("The weight is : " + board10.weight);
        System.out.println("The isBluetoothEnabled is : " + board10.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board10.batteryType);
        System.out.println("The warrantyYears is : " + board10.warrantyYears);
        System.out.println("The rangeKm is : " + board10.rangeKm);
        System.out.println("The hasLEDLights is : " + board10.hasLEDLights);
        System.out.println("The color is : " + board10.color);
        System.out.println("The stockQuantity is : " + board10.stockQuantity);
        System.out.println("The chargingTime is : " + board10.chargingTime);
        System.out.println("The isEcoFriendly is : " + board10.isEcoFriendly);
        System.out.println("The wheelType is : " + board10.wheelType);
        System.out.println("The rating is : " + board10.rating);
        System.out.println("The motorPower is : " + board10.motorPower);
        System.out.println("The isCertified is : " + board10.isCertified);
        System.out.println("The countryOfOrigin is : " + board10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board10.manufacturingYear);
        System.out.println("The wheelSize is : " + board10.wheelSize);
        System.out.println("The supportsAppControl is : " + board10.supportsAppControl);
        System.out.println("The certificationType is : " + board10.certificationType);

        board10.boardBrand = "SmartRide";
        board10.boardId = 10;
        board10.boardPrice = 10000.50;
        board10.isAvailable = true;
        board10.boardType = "Self Balancing";
        board10.maxSpeed = 15.0;
        board10.weight = 10.5;
        board10.isBluetoothEnabled = true;
        board10.batteryType = "Lithium Ion";
        board10.warrantyYears = 1;
        board10.rangeKm = 20.0;
        board10.hasLEDLights = true;
        board10.color = "Black";
        board10.stockQuantity = 18;
        board10.chargingTime = 2.5;
        board10.isEcoFriendly = true;
        board10.wheelType = "Rubber";
        board10.rating = 4;
        board10.motorPower = 700.0;
        board10.isCertified = true;
        board10.countryOfOrigin = "China";
        board10.manufacturingYear = 2025;
        board10.wheelSize = 6.5;
        board10.supportsAppControl = true;
        board10.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board10.boardBrand);
        System.out.println("The boardId is : " + board10.boardId);
        System.out.println("The boardPrice is : " + board10.boardPrice);
        System.out.println("The isAvailable is : " + board10.isAvailable);
        System.out.println("The boardType is : " + board10.boardType);
        System.out.println("The maxSpeed is : " + board10.maxSpeed);
        System.out.println("The weight is : " + board10.weight);
        System.out.println("The isBluetoothEnabled is : " + board10.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board10.batteryType);
        System.out.println("The warrantyYears is : " + board10.warrantyYears);
        System.out.println("The rangeKm is : " + board10.rangeKm);
        System.out.println("The hasLEDLights is : " + board10.hasLEDLights);
        System.out.println("The color is : " + board10.color);
        System.out.println("The stockQuantity is : " + board10.stockQuantity);
        System.out.println("The chargingTime is : " + board10.chargingTime);
        System.out.println("The isEcoFriendly is : " + board10.isEcoFriendly);
        System.out.println("The wheelType is : " + board10.wheelType);
        System.out.println("The rating is : " + board10.rating);
        System.out.println("The motorPower is : " + board10.motorPower);
        System.out.println("The isCertified is : " + board10.isCertified);
        System.out.println("The countryOfOrigin is : " + board10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board10.manufacturingYear);
        System.out.println("The wheelSize is : " + board10.wheelSize);
        System.out.println("The supportsAppControl is : " + board10.supportsAppControl);
        System.out.println("The certificationType is : " + board10.certificationType);


        HoverBoard board11 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board11.boardBrand);
        System.out.println("The boardId is : " + board11.boardId);
        System.out.println("The boardPrice is : " + board11.boardPrice);
        System.out.println("The isAvailable is : " + board11.isAvailable);
        System.out.println("The boardType is : " + board11.boardType);
        System.out.println("The maxSpeed is : " + board11.maxSpeed);
        System.out.println("The weight is : " + board11.weight);
        System.out.println("The isBluetoothEnabled is : " + board11.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board11.batteryType);
        System.out.println("The warrantyYears is : " + board11.warrantyYears);
        System.out.println("The rangeKm is : " + board11.rangeKm);
        System.out.println("The hasLEDLights is : " + board11.hasLEDLights);
        System.out.println("The color is : " + board11.color);
        System.out.println("The stockQuantity is : " + board11.stockQuantity);
        System.out.println("The chargingTime is : " + board11.chargingTime);
        System.out.println("The isEcoFriendly is : " + board11.isEcoFriendly);
        System.out.println("The wheelType is : " + board11.wheelType);
        System.out.println("The rating is : " + board11.rating);
        System.out.println("The motorPower is : " + board11.motorPower);
        System.out.println("The isCertified is : " + board11.isCertified);
        System.out.println("The countryOfOrigin is : " + board11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board11.manufacturingYear);
        System.out.println("The wheelSize is : " + board11.wheelSize);
        System.out.println("The supportsAppControl is : " + board11.supportsAppControl);
        System.out.println("The certificationType is : " + board11.certificationType);

        board11.boardBrand = "SmartRide";
        board11.boardId = 11;
        board11.boardPrice = 11000.50;
        board11.isAvailable = true;
        board11.boardType = "Self Balancing";
        board11.maxSpeed = 15.0;
        board11.weight = 10.5;
        board11.isBluetoothEnabled = true;
        board11.batteryType = "Lithium Ion";
        board11.warrantyYears = 1;
        board11.rangeKm = 20.0;
        board11.hasLEDLights = true;
        board11.color = "Black";
        board11.stockQuantity = 18;
        board11.chargingTime = 2.5;
        board11.isEcoFriendly = true;
        board11.wheelType = "Rubber";
        board11.rating = 4;
        board11.motorPower = 700.0;
        board11.isCertified = true;
        board11.countryOfOrigin = "China";
        board11.manufacturingYear = 2025;
        board11.wheelSize = 6.5;
        board11.supportsAppControl = true;
        board11.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board11.boardBrand);
        System.out.println("The boardId is : " + board11.boardId);
        System.out.println("The boardPrice is : " + board11.boardPrice);
        System.out.println("The isAvailable is : " + board11.isAvailable);
        System.out.println("The boardType is : " + board11.boardType);
        System.out.println("The maxSpeed is : " + board11.maxSpeed);
        System.out.println("The weight is : " + board11.weight);
        System.out.println("The isBluetoothEnabled is : " + board11.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board11.batteryType);
        System.out.println("The warrantyYears is : " + board11.warrantyYears);
        System.out.println("The rangeKm is : " + board11.rangeKm);
        System.out.println("The hasLEDLights is : " + board11.hasLEDLights);
        System.out.println("The color is : " + board11.color);
        System.out.println("The stockQuantity is : " + board11.stockQuantity);
        System.out.println("The chargingTime is : " + board11.chargingTime);
        System.out.println("The isEcoFriendly is : " + board11.isEcoFriendly);
        System.out.println("The wheelType is : " + board11.wheelType);
        System.out.println("The rating is : " + board11.rating);
        System.out.println("The motorPower is : " + board11.motorPower);
        System.out.println("The isCertified is : " + board11.isCertified);
        System.out.println("The countryOfOrigin is : " + board11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board11.manufacturingYear);
        System.out.println("The wheelSize is : " + board11.wheelSize);
        System.out.println("The supportsAppControl is : " + board11.supportsAppControl);
        System.out.println("The certificationType is : " + board11.certificationType);


        HoverBoard board12 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board12.boardBrand);
        System.out.println("The boardId is : " + board12.boardId);
        System.out.println("The boardPrice is : " + board12.boardPrice);
        System.out.println("The isAvailable is : " + board12.isAvailable);
        System.out.println("The boardType is : " + board12.boardType);
        System.out.println("The maxSpeed is : " + board12.maxSpeed);
        System.out.println("The weight is : " + board12.weight);
        System.out.println("The isBluetoothEnabled is : " + board12.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board12.batteryType);
        System.out.println("The warrantyYears is : " + board12.warrantyYears);
        System.out.println("The rangeKm is : " + board12.rangeKm);
        System.out.println("The hasLEDLights is : " + board12.hasLEDLights);
        System.out.println("The color is : " + board12.color);
        System.out.println("The stockQuantity is : " + board12.stockQuantity);
        System.out.println("The chargingTime is : " + board12.chargingTime);
        System.out.println("The isEcoFriendly is : " + board12.isEcoFriendly);
        System.out.println("The wheelType is : " + board12.wheelType);
        System.out.println("The rating is : " + board12.rating);
        System.out.println("The motorPower is : " + board12.motorPower);
        System.out.println("The isCertified is : " + board12.isCertified);
        System.out.println("The countryOfOrigin is : " + board12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board12.manufacturingYear);
        System.out.println("The wheelSize is : " + board12.wheelSize);
        System.out.println("The supportsAppControl is : " + board12.supportsAppControl);
        System.out.println("The certificationType is : " + board12.certificationType);

        board12.boardBrand = "SmartRide";
        board12.boardId = 12;
        board12.boardPrice = 12000.50;
        board12.isAvailable = true;
        board12.boardType = "Self Balancing";
        board12.maxSpeed = 15.0;
        board12.weight = 10.5;
        board12.isBluetoothEnabled = true;
        board12.batteryType = "Lithium Ion";
        board12.warrantyYears = 1;
        board12.rangeKm = 20.0;
        board12.hasLEDLights = true;
        board12.color = "Black";
        board12.stockQuantity = 18;
        board12.chargingTime = 2.5;
        board12.isEcoFriendly = true;
        board12.wheelType = "Rubber";
        board12.rating = 4;
        board12.motorPower = 700.0;
        board12.isCertified = true;
        board12.countryOfOrigin = "China";
        board12.manufacturingYear = 2025;
        board12.wheelSize = 6.5;
        board12.supportsAppControl = true;
        board12.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board12.boardBrand);
        System.out.println("The boardId is : " + board12.boardId);
        System.out.println("The boardPrice is : " + board12.boardPrice);
        System.out.println("The isAvailable is : " + board12.isAvailable);
        System.out.println("The boardType is : " + board12.boardType);
        System.out.println("The maxSpeed is : " + board12.maxSpeed);
        System.out.println("The weight is : " + board12.weight);
        System.out.println("The isBluetoothEnabled is : " + board12.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board12.batteryType);
        System.out.println("The warrantyYears is : " + board12.warrantyYears);
        System.out.println("The rangeKm is : " + board12.rangeKm);
        System.out.println("The hasLEDLights is : " + board12.hasLEDLights);
        System.out.println("The color is : " + board12.color);
        System.out.println("The stockQuantity is : " + board12.stockQuantity);
        System.out.println("The chargingTime is : " + board12.chargingTime);
        System.out.println("The isEcoFriendly is : " + board12.isEcoFriendly);
        System.out.println("The wheelType is : " + board12.wheelType);
        System.out.println("The rating is : " + board12.rating);
        System.out.println("The motorPower is : " + board12.motorPower);
        System.out.println("The isCertified is : " + board12.isCertified);
        System.out.println("The countryOfOrigin is : " + board12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board12.manufacturingYear);
        System.out.println("The wheelSize is : " + board12.wheelSize);
        System.out.println("The supportsAppControl is : " + board12.supportsAppControl);
        System.out.println("The certificationType is : " + board12.certificationType);


        HoverBoard board13 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board13.boardBrand);
        System.out.println("The boardId is : " + board13.boardId);
        System.out.println("The boardPrice is : " + board13.boardPrice);
        System.out.println("The isAvailable is : " + board13.isAvailable);
        System.out.println("The boardType is : " + board13.boardType);
        System.out.println("The maxSpeed is : " + board13.maxSpeed);
        System.out.println("The weight is : " + board13.weight);
        System.out.println("The isBluetoothEnabled is : " + board13.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board13.batteryType);
        System.out.println("The warrantyYears is : " + board13.warrantyYears);
        System.out.println("The rangeKm is : " + board13.rangeKm);
        System.out.println("The hasLEDLights is : " + board13.hasLEDLights);
        System.out.println("The color is : " + board13.color);
        System.out.println("The stockQuantity is : " + board13.stockQuantity);
        System.out.println("The chargingTime is : " + board13.chargingTime);
        System.out.println("The isEcoFriendly is : " + board13.isEcoFriendly);
        System.out.println("The wheelType is : " + board13.wheelType);
        System.out.println("The rating is : " + board13.rating);
        System.out.println("The motorPower is : " + board13.motorPower);
        System.out.println("The isCertified is : " + board13.isCertified);
        System.out.println("The countryOfOrigin is : " + board13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board13.manufacturingYear);
        System.out.println("The wheelSize is : " + board13.wheelSize);
        System.out.println("The supportsAppControl is : " + board13.supportsAppControl);
        System.out.println("The certificationType is : " + board13.certificationType);

        board13.boardBrand = "SmartRide";
        board13.boardId = 13;
        board13.boardPrice = 13000.50;
        board13.isAvailable = true;
        board13.boardType = "Self Balancing";
        board13.maxSpeed = 15.0;
        board13.weight = 10.5;
        board13.isBluetoothEnabled = true;
        board13.batteryType = "Lithium Ion";
        board13.warrantyYears = 1;
        board13.rangeKm = 20.0;
        board13.hasLEDLights = true;
        board13.color = "Black";
        board13.stockQuantity = 18;
        board13.chargingTime = 2.5;
        board13.isEcoFriendly = true;
        board13.wheelType = "Rubber";
        board13.rating = 4;
        board13.motorPower = 700.0;
        board13.isCertified = true;
        board13.countryOfOrigin = "China";
        board13.manufacturingYear = 2025;
        board13.wheelSize = 6.5;
        board13.supportsAppControl = true;
        board13.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board13.boardBrand);
        System.out.println("The boardId is : " + board13.boardId);
        System.out.println("The boardPrice is : " + board13.boardPrice);
        System.out.println("The isAvailable is : " + board13.isAvailable);
        System.out.println("The boardType is : " + board13.boardType);
        System.out.println("The maxSpeed is : " + board13.maxSpeed);
        System.out.println("The weight is : " + board13.weight);
        System.out.println("The isBluetoothEnabled is : " + board13.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board13.batteryType);
        System.out.println("The warrantyYears is : " + board13.warrantyYears);
        System.out.println("The rangeKm is : " + board13.rangeKm);
        System.out.println("The hasLEDLights is : " + board13.hasLEDLights);
        System.out.println("The color is : " + board13.color);
        System.out.println("The stockQuantity is : " + board13.stockQuantity);
        System.out.println("The chargingTime is : " + board13.chargingTime);
        System.out.println("The isEcoFriendly is : " + board13.isEcoFriendly);
        System.out.println("The wheelType is : " + board13.wheelType);
        System.out.println("The rating is : " + board13.rating);
        System.out.println("The motorPower is : " + board13.motorPower);
        System.out.println("The isCertified is : " + board13.isCertified);
        System.out.println("The countryOfOrigin is : " + board13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board13.manufacturingYear);
        System.out.println("The wheelSize is : " + board13.wheelSize);
        System.out.println("The supportsAppControl is : " + board13.supportsAppControl);
        System.out.println("The certificationType is : " + board13.certificationType);


        HoverBoard board14 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board14.boardBrand);
        System.out.println("The boardId is : " + board14.boardId);
        System.out.println("The boardPrice is : " + board14.boardPrice);
        System.out.println("The isAvailable is : " + board14.isAvailable);
        System.out.println("The boardType is : " + board14.boardType);
        System.out.println("The maxSpeed is : " + board14.maxSpeed);
        System.out.println("The weight is : " + board14.weight);
        System.out.println("The isBluetoothEnabled is : " + board14.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board14.batteryType);
        System.out.println("The warrantyYears is : " + board14.warrantyYears);
        System.out.println("The rangeKm is : " + board14.rangeKm);
        System.out.println("The hasLEDLights is : " + board14.hasLEDLights);
        System.out.println("The color is : " + board14.color);
        System.out.println("The stockQuantity is : " + board14.stockQuantity);
        System.out.println("The chargingTime is : " + board14.chargingTime);
        System.out.println("The isEcoFriendly is : " + board14.isEcoFriendly);
        System.out.println("The wheelType is : " + board14.wheelType);
        System.out.println("The rating is : " + board14.rating);
        System.out.println("The motorPower is : " + board14.motorPower);
        System.out.println("The isCertified is : " + board14.isCertified);
        System.out.println("The countryOfOrigin is : " + board14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board14.manufacturingYear);
        System.out.println("The wheelSize is : " + board14.wheelSize);
        System.out.println("The supportsAppControl is : " + board14.supportsAppControl);
        System.out.println("The certificationType is : " + board14.certificationType);

        board14.boardBrand = "SmartRide";
        board14.boardId = 14;
        board14.boardPrice = 14000.50;
        board14.isAvailable = true;
        board14.boardType = "Self Balancing";
        board14.maxSpeed = 15.0;
        board14.weight = 10.5;
        board14.isBluetoothEnabled = true;
        board14.batteryType = "Lithium Ion";
        board14.warrantyYears = 1;
        board14.rangeKm = 20.0;
        board14.hasLEDLights = true;
        board14.color = "Black";
        board14.stockQuantity = 18;
        board14.chargingTime = 2.5;
        board14.isEcoFriendly = true;
        board14.wheelType = "Rubber";
        board14.rating = 4;
        board14.motorPower = 700.0;
        board14.isCertified = true;
        board14.countryOfOrigin = "China";
        board14.manufacturingYear = 2025;
        board14.wheelSize = 6.5;
        board14.supportsAppControl = true;
        board14.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board14.boardBrand);
        System.out.println("The boardId is : " + board14.boardId);
        System.out.println("The boardPrice is : " + board14.boardPrice);
        System.out.println("The isAvailable is : " + board14.isAvailable);
        System.out.println("The boardType is : " + board14.boardType);
        System.out.println("The maxSpeed is : " + board14.maxSpeed);
        System.out.println("The weight is : " + board14.weight);
        System.out.println("The isBluetoothEnabled is : " + board14.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board14.batteryType);
        System.out.println("The warrantyYears is : " + board14.warrantyYears);
        System.out.println("The rangeKm is : " + board14.rangeKm);
        System.out.println("The hasLEDLights is : " + board14.hasLEDLights);
        System.out.println("The color is : " + board14.color);
        System.out.println("The stockQuantity is : " + board14.stockQuantity);
        System.out.println("The chargingTime is : " + board14.chargingTime);
        System.out.println("The isEcoFriendly is : " + board14.isEcoFriendly);
        System.out.println("The wheelType is : " + board14.wheelType);
        System.out.println("The rating is : " + board14.rating);
        System.out.println("The motorPower is : " + board14.motorPower);
        System.out.println("The isCertified is : " + board14.isCertified);
        System.out.println("The countryOfOrigin is : " + board14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board14.manufacturingYear);
        System.out.println("The wheelSize is : " + board14.wheelSize);
        System.out.println("The supportsAppControl is : " + board14.supportsAppControl);
        System.out.println("The certificationType is : " + board14.certificationType);


        HoverBoard board15 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board15.boardBrand);
        System.out.println("The boardId is : " + board15.boardId);
        System.out.println("The boardPrice is : " + board15.boardPrice);
        System.out.println("The isAvailable is : " + board15.isAvailable);
        System.out.println("The boardType is : " + board15.boardType);
        System.out.println("The maxSpeed is : " + board15.maxSpeed);
        System.out.println("The weight is : " + board15.weight);
        System.out.println("The isBluetoothEnabled is : " + board15.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board15.batteryType);
        System.out.println("The warrantyYears is : " + board15.warrantyYears);
        System.out.println("The rangeKm is : " + board15.rangeKm);
        System.out.println("The hasLEDLights is : " + board15.hasLEDLights);
        System.out.println("The color is : " + board15.color);
        System.out.println("The stockQuantity is : " + board15.stockQuantity);
        System.out.println("The chargingTime is : " + board15.chargingTime);
        System.out.println("The isEcoFriendly is : " + board15.isEcoFriendly);
        System.out.println("The wheelType is : " + board15.wheelType);
        System.out.println("The rating is : " + board15.rating);
        System.out.println("The motorPower is : " + board15.motorPower);
        System.out.println("The isCertified is : " + board15.isCertified);
        System.out.println("The countryOfOrigin is : " + board15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board15.manufacturingYear);
        System.out.println("The wheelSize is : " + board15.wheelSize);
        System.out.println("The supportsAppControl is : " + board15.supportsAppControl);
        System.out.println("The certificationType is : " + board15.certificationType);

        board15.boardBrand = "SmartRide";
        board15.boardId = 15;
        board15.boardPrice = 15000.50;
        board15.isAvailable = true;
        board15.boardType = "Self Balancing";
        board15.maxSpeed = 15.0;
        board15.weight = 10.5;
        board15.isBluetoothEnabled = true;
        board15.batteryType = "Lithium Ion";
        board15.warrantyYears = 1;
        board15.rangeKm = 20.0;
        board15.hasLEDLights = true;
        board15.color = "Black";
        board15.stockQuantity = 18;
        board15.chargingTime = 2.5;
        board15.isEcoFriendly = true;
        board15.wheelType = "Rubber";
        board15.rating = 4;
        board15.motorPower = 700.0;
        board15.isCertified = true;
        board15.countryOfOrigin = "China";
        board15.manufacturingYear = 2025;
        board15.wheelSize = 6.5;
        board15.supportsAppControl = true;
        board15.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board15.boardBrand);
        System.out.println("The boardId is : " + board15.boardId);
        System.out.println("The boardPrice is : " + board15.boardPrice);
        System.out.println("The isAvailable is : " + board15.isAvailable);
        System.out.println("The boardType is : " + board15.boardType);
        System.out.println("The maxSpeed is : " + board15.maxSpeed);
        System.out.println("The weight is : " + board15.weight);
        System.out.println("The isBluetoothEnabled is : " + board15.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board15.batteryType);
        System.out.println("The warrantyYears is : " + board15.warrantyYears);
        System.out.println("The rangeKm is : " + board15.rangeKm);
        System.out.println("The hasLEDLights is : " + board15.hasLEDLights);
        System.out.println("The color is : " + board15.color);
        System.out.println("The stockQuantity is : " + board15.stockQuantity);
        System.out.println("The chargingTime is : " + board15.chargingTime);
        System.out.println("The isEcoFriendly is : " + board15.isEcoFriendly);
        System.out.println("The wheelType is : " + board15.wheelType);
        System.out.println("The rating is : " + board15.rating);
        System.out.println("The motorPower is : " + board15.motorPower);
        System.out.println("The isCertified is : " + board15.isCertified);
        System.out.println("The countryOfOrigin is : " + board15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board15.manufacturingYear);
        System.out.println("The wheelSize is : " + board15.wheelSize);
        System.out.println("The supportsAppControl is : " + board15.supportsAppControl);
        System.out.println("The certificationType is : " + board15.certificationType);


        HoverBoard board16 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board16.boardBrand);
        System.out.println("The boardId is : " + board16.boardId);
        System.out.println("The boardPrice is : " + board16.boardPrice);
        System.out.println("The isAvailable is : " + board16.isAvailable);
        System.out.println("The boardType is : " + board16.boardType);
        System.out.println("The maxSpeed is : " + board16.maxSpeed);
        System.out.println("The weight is : " + board16.weight);
        System.out.println("The isBluetoothEnabled is : " + board16.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board16.batteryType);
        System.out.println("The warrantyYears is : " + board16.warrantyYears);
        System.out.println("The rangeKm is : " + board16.rangeKm);
        System.out.println("The hasLEDLights is : " + board16.hasLEDLights);
        System.out.println("The color is : " + board16.color);
        System.out.println("The stockQuantity is : " + board16.stockQuantity);
        System.out.println("The chargingTime is : " + board16.chargingTime);
        System.out.println("The isEcoFriendly is : " + board16.isEcoFriendly);
        System.out.println("The wheelType is : " + board16.wheelType);
        System.out.println("The rating is : " + board16.rating);
        System.out.println("The motorPower is : " + board16.motorPower);
        System.out.println("The isCertified is : " + board16.isCertified);
        System.out.println("The countryOfOrigin is : " + board16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board16.manufacturingYear);
        System.out.println("The wheelSize is : " + board16.wheelSize);
        System.out.println("The supportsAppControl is : " + board16.supportsAppControl);
        System.out.println("The certificationType is : " + board16.certificationType);

        board16.boardBrand = "SmartRide";
        board16.boardId = 16;
        board16.boardPrice = 16000.50;
        board16.isAvailable = true;
        board16.boardType = "Self Balancing";
        board16.maxSpeed = 15.0;
        board16.weight = 10.5;
        board16.isBluetoothEnabled = true;
        board16.batteryType = "Lithium Ion";
        board16.warrantyYears = 1;
        board16.rangeKm = 20.0;
        board16.hasLEDLights = true;
        board16.color = "Black";
        board16.stockQuantity = 18;
        board16.chargingTime = 2.5;
        board16.isEcoFriendly = true;
        board16.wheelType = "Rubber";
        board16.rating = 4;
        board16.motorPower = 700.0;
        board16.isCertified = true;
        board16.countryOfOrigin = "China";
        board16.manufacturingYear = 2025;
        board16.wheelSize = 6.5;
        board16.supportsAppControl = true;
        board16.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board16.boardBrand);
        System.out.println("The boardId is : " + board16.boardId);
        System.out.println("The boardPrice is : " + board16.boardPrice);
        System.out.println("The isAvailable is : " + board16.isAvailable);
        System.out.println("The boardType is : " + board16.boardType);
        System.out.println("The maxSpeed is : " + board16.maxSpeed);
        System.out.println("The weight is : " + board16.weight);
        System.out.println("The isBluetoothEnabled is : " + board16.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board16.batteryType);
        System.out.println("The warrantyYears is : " + board16.warrantyYears);
        System.out.println("The rangeKm is : " + board16.rangeKm);
        System.out.println("The hasLEDLights is : " + board16.hasLEDLights);
        System.out.println("The color is : " + board16.color);
        System.out.println("The stockQuantity is : " + board16.stockQuantity);
        System.out.println("The chargingTime is : " + board16.chargingTime);
        System.out.println("The isEcoFriendly is : " + board16.isEcoFriendly);
        System.out.println("The wheelType is : " + board16.wheelType);
        System.out.println("The rating is : " + board16.rating);
        System.out.println("The motorPower is : " + board16.motorPower);
        System.out.println("The isCertified is : " + board16.isCertified);
        System.out.println("The countryOfOrigin is : " + board16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board16.manufacturingYear);
        System.out.println("The wheelSize is : " + board16.wheelSize);
        System.out.println("The supportsAppControl is : " + board16.supportsAppControl);
        System.out.println("The certificationType is : " + board16.certificationType);


        HoverBoard board17 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board17.boardBrand);
        System.out.println("The boardId is : " + board17.boardId);
        System.out.println("The boardPrice is : " + board17.boardPrice);
        System.out.println("The isAvailable is : " + board17.isAvailable);
        System.out.println("The boardType is : " + board17.boardType);
        System.out.println("The maxSpeed is : " + board17.maxSpeed);
        System.out.println("The weight is : " + board17.weight);
        System.out.println("The isBluetoothEnabled is : " + board17.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board17.batteryType);
        System.out.println("The warrantyYears is : " + board17.warrantyYears);
        System.out.println("The rangeKm is : " + board17.rangeKm);
        System.out.println("The hasLEDLights is : " + board17.hasLEDLights);
        System.out.println("The color is : " + board17.color);
        System.out.println("The stockQuantity is : " + board17.stockQuantity);
        System.out.println("The chargingTime is : " + board17.chargingTime);
        System.out.println("The isEcoFriendly is : " + board17.isEcoFriendly);
        System.out.println("The wheelType is : " + board17.wheelType);
        System.out.println("The rating is : " + board17.rating);
        System.out.println("The motorPower is : " + board17.motorPower);
        System.out.println("The isCertified is : " + board17.isCertified);
        System.out.println("The countryOfOrigin is : " + board17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board17.manufacturingYear);
        System.out.println("The wheelSize is : " + board17.wheelSize);
        System.out.println("The supportsAppControl is : " + board17.supportsAppControl);
        System.out.println("The certificationType is : " + board17.certificationType);

        board17.boardBrand = "SmartRide";
        board17.boardId = 17;
        board17.boardPrice = 17000.50;
        board17.isAvailable = true;
        board17.boardType = "Self Balancing";
        board17.maxSpeed = 15.0;
        board17.weight = 10.5;
        board17.isBluetoothEnabled = true;
        board17.batteryType = "Lithium Ion";
        board17.warrantyYears = 1;
        board17.rangeKm = 20.0;
        board17.hasLEDLights = true;
        board17.color = "Black";
        board17.stockQuantity = 18;
        board17.chargingTime = 2.5;
        board17.isEcoFriendly = true;
        board17.wheelType = "Rubber";
        board17.rating = 4;
        board17.motorPower = 700.0;
        board17.isCertified = true;
        board17.countryOfOrigin = "China";
        board17.manufacturingYear = 2025;
        board17.wheelSize = 6.5;
        board17.supportsAppControl = true;
        board17.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board17.boardBrand);
        System.out.println("The boardId is : " + board17.boardId);
        System.out.println("The boardPrice is : " + board17.boardPrice);
        System.out.println("The isAvailable is : " + board17.isAvailable);
        System.out.println("The boardType is : " + board17.boardType);
        System.out.println("The maxSpeed is : " + board17.maxSpeed);
        System.out.println("The weight is : " + board17.weight);
        System.out.println("The isBluetoothEnabled is : " + board17.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board17.batteryType);
        System.out.println("The warrantyYears is : " + board17.warrantyYears);
        System.out.println("The rangeKm is : " + board17.rangeKm);
        System.out.println("The hasLEDLights is : " + board17.hasLEDLights);
        System.out.println("The color is : " + board17.color);
        System.out.println("The stockQuantity is : " + board17.stockQuantity);
        System.out.println("The chargingTime is : " + board17.chargingTime);
        System.out.println("The isEcoFriendly is : " + board17.isEcoFriendly);
        System.out.println("The wheelType is : " + board17.wheelType);
        System.out.println("The rating is : " + board17.rating);
        System.out.println("The motorPower is : " + board17.motorPower);
        System.out.println("The isCertified is : " + board17.isCertified);
        System.out.println("The countryOfOrigin is : " + board17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board17.manufacturingYear);
        System.out.println("The wheelSize is : " + board17.wheelSize);
        System.out.println("The supportsAppControl is : " + board17.supportsAppControl);
        System.out.println("The certificationType is : " + board17.certificationType);


        HoverBoard board18 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board18.boardBrand);
        System.out.println("The boardId is : " + board18.boardId);
        System.out.println("The boardPrice is : " + board18.boardPrice);
        System.out.println("The isAvailable is : " + board18.isAvailable);
        System.out.println("The boardType is : " + board18.boardType);
        System.out.println("The maxSpeed is : " + board18.maxSpeed);
        System.out.println("The weight is : " + board18.weight);
        System.out.println("The isBluetoothEnabled is : " + board18.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board18.batteryType);
        System.out.println("The warrantyYears is : " + board18.warrantyYears);
        System.out.println("The rangeKm is : " + board18.rangeKm);
        System.out.println("The hasLEDLights is : " + board18.hasLEDLights);
        System.out.println("The color is : " + board18.color);
        System.out.println("The stockQuantity is : " + board18.stockQuantity);
        System.out.println("The chargingTime is : " + board18.chargingTime);
        System.out.println("The isEcoFriendly is : " + board18.isEcoFriendly);
        System.out.println("The wheelType is : " + board18.wheelType);
        System.out.println("The rating is : " + board18.rating);
        System.out.println("The motorPower is : " + board18.motorPower);
        System.out.println("The isCertified is : " + board18.isCertified);
        System.out.println("The countryOfOrigin is : " + board18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board18.manufacturingYear);
        System.out.println("The wheelSize is : " + board18.wheelSize);
        System.out.println("The supportsAppControl is : " + board18.supportsAppControl);
        System.out.println("The certificationType is : " + board18.certificationType);

        board18.boardBrand = "SmartRide";
        board18.boardId = 18;
        board18.boardPrice = 18000.50;
        board18.isAvailable = true;
        board18.boardType = "Self Balancing";
        board18.maxSpeed = 15.0;
        board18.weight = 10.5;
        board18.isBluetoothEnabled = true;
        board18.batteryType = "Lithium Ion";
        board18.warrantyYears = 1;
        board18.rangeKm = 20.0;
        board18.hasLEDLights = true;
        board18.color = "Black";
        board18.stockQuantity = 18;
        board18.chargingTime = 2.5;
        board18.isEcoFriendly = true;
        board18.wheelType = "Rubber";
        board18.rating = 4;
        board18.motorPower = 700.0;
        board18.isCertified = true;
        board18.countryOfOrigin = "China";
        board18.manufacturingYear = 2025;
        board18.wheelSize = 6.5;
        board18.supportsAppControl = true;
        board18.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board18.boardBrand);
        System.out.println("The boardId is : " + board18.boardId);
        System.out.println("The boardPrice is : " + board18.boardPrice);
        System.out.println("The isAvailable is : " + board18.isAvailable);
        System.out.println("The boardType is : " + board18.boardType);
        System.out.println("The maxSpeed is : " + board18.maxSpeed);
        System.out.println("The weight is : " + board18.weight);
        System.out.println("The isBluetoothEnabled is : " + board18.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board18.batteryType);
        System.out.println("The warrantyYears is : " + board18.warrantyYears);
        System.out.println("The rangeKm is : " + board18.rangeKm);
        System.out.println("The hasLEDLights is : " + board18.hasLEDLights);
        System.out.println("The color is : " + board18.color);
        System.out.println("The stockQuantity is : " + board18.stockQuantity);
        System.out.println("The chargingTime is : " + board18.chargingTime);
        System.out.println("The isEcoFriendly is : " + board18.isEcoFriendly);
        System.out.println("The wheelType is : " + board18.wheelType);
        System.out.println("The rating is : " + board18.rating);
        System.out.println("The motorPower is : " + board18.motorPower);
        System.out.println("The isCertified is : " + board18.isCertified);
        System.out.println("The countryOfOrigin is : " + board18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board18.manufacturingYear);
        System.out.println("The wheelSize is : " + board18.wheelSize);
        System.out.println("The supportsAppControl is : " + board18.supportsAppControl);
        System.out.println("The certificationType is : " + board18.certificationType);


        HoverBoard board19 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board19.boardBrand);
        System.out.println("The boardId is : " + board19.boardId);
        System.out.println("The boardPrice is : " + board19.boardPrice);
        System.out.println("The isAvailable is : " + board19.isAvailable);
        System.out.println("The boardType is : " + board19.boardType);
        System.out.println("The maxSpeed is : " + board19.maxSpeed);
        System.out.println("The weight is : " + board19.weight);
        System.out.println("The isBluetoothEnabled is : " + board19.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board19.batteryType);
        System.out.println("The warrantyYears is : " + board19.warrantyYears);
        System.out.println("The rangeKm is : " + board19.rangeKm);
        System.out.println("The hasLEDLights is : " + board19.hasLEDLights);
        System.out.println("The color is : " + board19.color);
        System.out.println("The stockQuantity is : " + board19.stockQuantity);
        System.out.println("The chargingTime is : " + board19.chargingTime);
        System.out.println("The isEcoFriendly is : " + board19.isEcoFriendly);
        System.out.println("The wheelType is : " + board19.wheelType);
        System.out.println("The rating is : " + board19.rating);
        System.out.println("The motorPower is : " + board19.motorPower);
        System.out.println("The isCertified is : " + board19.isCertified);
        System.out.println("The countryOfOrigin is : " + board19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board19.manufacturingYear);
        System.out.println("The wheelSize is : " + board19.wheelSize);
        System.out.println("The supportsAppControl is : " + board19.supportsAppControl);
        System.out.println("The certificationType is : " + board19.certificationType);

        board19.boardBrand = "SmartRide";
        board19.boardId = 19;
        board19.boardPrice = 19000.50;
        board19.isAvailable = true;
        board19.boardType = "Self Balancing";
        board19.maxSpeed = 15.0;
        board19.weight = 10.5;
        board19.isBluetoothEnabled = true;
        board19.batteryType = "Lithium Ion";
        board19.warrantyYears = 1;
        board19.rangeKm = 20.0;
        board19.hasLEDLights = true;
        board19.color = "Black";
        board19.stockQuantity = 18;
        board19.chargingTime = 2.5;
        board19.isEcoFriendly = true;
        board19.wheelType = "Rubber";
        board19.rating = 4;
        board19.motorPower = 700.0;
        board19.isCertified = true;
        board19.countryOfOrigin = "China";
        board19.manufacturingYear = 2025;
        board19.wheelSize = 6.5;
        board19.supportsAppControl = true;
        board19.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board19.boardBrand);
        System.out.println("The boardId is : " + board19.boardId);
        System.out.println("The boardPrice is : " + board19.boardPrice);
        System.out.println("The isAvailable is : " + board19.isAvailable);
        System.out.println("The boardType is : " + board19.boardType);
        System.out.println("The maxSpeed is : " + board19.maxSpeed);
        System.out.println("The weight is : " + board19.weight);
        System.out.println("The isBluetoothEnabled is : " + board19.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board19.batteryType);
        System.out.println("The warrantyYears is : " + board19.warrantyYears);
        System.out.println("The rangeKm is : " + board19.rangeKm);
        System.out.println("The hasLEDLights is : " + board19.hasLEDLights);
        System.out.println("The color is : " + board19.color);
        System.out.println("The stockQuantity is : " + board19.stockQuantity);
        System.out.println("The chargingTime is : " + board19.chargingTime);
        System.out.println("The isEcoFriendly is : " + board19.isEcoFriendly);
        System.out.println("The wheelType is : " + board19.wheelType);
        System.out.println("The rating is : " + board19.rating);
        System.out.println("The motorPower is : " + board19.motorPower);
        System.out.println("The isCertified is : " + board19.isCertified);
        System.out.println("The countryOfOrigin is : " + board19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board19.manufacturingYear);
        System.out.println("The wheelSize is : " + board19.wheelSize);
        System.out.println("The supportsAppControl is : " + board19.supportsAppControl);
        System.out.println("The certificationType is : " + board19.certificationType);


        HoverBoard board20 = new HoverBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board20.boardBrand);
        System.out.println("The boardId is : " + board20.boardId);
        System.out.println("The boardPrice is : " + board20.boardPrice);
        System.out.println("The isAvailable is : " + board20.isAvailable);
        System.out.println("The boardType is : " + board20.boardType);
        System.out.println("The maxSpeed is : " + board20.maxSpeed);
        System.out.println("The weight is : " + board20.weight);
        System.out.println("The isBluetoothEnabled is : " + board20.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board20.batteryType);
        System.out.println("The warrantyYears is : " + board20.warrantyYears);
        System.out.println("The rangeKm is : " + board20.rangeKm);
        System.out.println("The hasLEDLights is : " + board20.hasLEDLights);
        System.out.println("The color is : " + board20.color);
        System.out.println("The stockQuantity is : " + board20.stockQuantity);
        System.out.println("The chargingTime is : " + board20.chargingTime);
        System.out.println("The isEcoFriendly is : " + board20.isEcoFriendly);
        System.out.println("The wheelType is : " + board20.wheelType);
        System.out.println("The rating is : " + board20.rating);
        System.out.println("The motorPower is : " + board20.motorPower);
        System.out.println("The isCertified is : " + board20.isCertified);
        System.out.println("The countryOfOrigin is : " + board20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board20.manufacturingYear);
        System.out.println("The wheelSize is : " + board20.wheelSize);
        System.out.println("The supportsAppControl is : " + board20.supportsAppControl);
        System.out.println("The certificationType is : " + board20.certificationType);

        board20.boardBrand = "SmartRide";
        board20.boardId = 20;
        board20.boardPrice = 20000.50;
        board20.isAvailable = true;
        board20.boardType = "Self Balancing";
        board20.maxSpeed = 15.0;
        board20.weight = 10.5;
        board20.isBluetoothEnabled = true;
        board20.batteryType = "Lithium Ion";
        board20.warrantyYears = 1;
        board20.rangeKm = 20.0;
        board20.hasLEDLights = true;
        board20.color = "Black";
        board20.stockQuantity = 18;
        board20.chargingTime = 2.5;
        board20.isEcoFriendly = true;
        board20.wheelType = "Rubber";
        board20.rating = 4;
        board20.motorPower = 700.0;
        board20.isCertified = true;
        board20.countryOfOrigin = "China";
        board20.manufacturingYear = 2025;
        board20.wheelSize = 6.5;
        board20.supportsAppControl = true;
        board20.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board20.boardBrand);
        System.out.println("The boardId is : " + board20.boardId);
        System.out.println("The boardPrice is : " + board20.boardPrice);
        System.out.println("The isAvailable is : " + board20.isAvailable);
        System.out.println("The boardType is : " + board20.boardType);
        System.out.println("The maxSpeed is : " + board20.maxSpeed);
        System.out.println("The weight is : " + board20.weight);
        System.out.println("The isBluetoothEnabled is : " + board20.isBluetoothEnabled);
        System.out.println("The batteryType is : " + board20.batteryType);
        System.out.println("The warrantyYears is : " + board20.warrantyYears);
        System.out.println("The rangeKm is : " + board20.rangeKm);
        System.out.println("The hasLEDLights is : " + board20.hasLEDLights);
        System.out.println("The color is : " + board20.color);
        System.out.println("The stockQuantity is : " + board20.stockQuantity);
        System.out.println("The chargingTime is : " + board20.chargingTime);
        System.out.println("The isEcoFriendly is : " + board20.isEcoFriendly);
        System.out.println("The wheelType is : " + board20.wheelType);
        System.out.println("The rating is : " + board20.rating);
        System.out.println("The motorPower is : " + board20.motorPower);
        System.out.println("The isCertified is : " + board20.isCertified);
        System.out.println("The countryOfOrigin is : " + board20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board20.manufacturingYear);
        System.out.println("The wheelSize is : " + board20.wheelSize);
        System.out.println("The supportsAppControl is : " + board20.supportsAppControl);
        System.out.println("The certificationType is : " + board20.certificationType);


    }
}
