class IpadExecutor {

    public static void main(String[] args) {

        Ipad ipad1 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad1.ipadBrand);
        System.out.println("The ipadId is : " + ipad1.ipadId);
        System.out.println("The ipadPrice is : " + ipad1.ipadPrice);
        System.out.println("The isAvailable is : " + ipad1.isAvailable);
        System.out.println("The modelName is : " + ipad1.modelName);
        System.out.println("The storageGB is : " + ipad1.storageGB);
        System.out.println("The weight is : " + ipad1.weight);
        System.out.println("The isWifiOnly is : " + ipad1.isWifiOnly);
        System.out.println("The processor is : " + ipad1.processor);
        System.out.println("The warrantyYears is : " + ipad1.warrantyYears);
        System.out.println("The screenSize is : " + ipad1.screenSize);
        System.out.println("The hasFaceID is : " + ipad1.hasFaceID);
        System.out.println("The color is : " + ipad1.color);
        System.out.println("The stockQuantity is : " + ipad1.stockQuantity);
        System.out.println("The thickness is : " + ipad1.thickness);
        System.out.println("The isEcoFriendly is : " + ipad1.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad1.osVersion);
        System.out.println("The rating is : " + ipad1.rating);
        System.out.println("The batteryCapacity is : " + ipad1.batteryCapacity);
        System.out.println("The isCertified is : " + ipad1.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad1.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad1.cameraMP);
        System.out.println("The supportsPencil is : " + ipad1.supportsPencil);
        System.out.println("The certificationType is : " + ipad1.certificationType);

        ipad1.ipadBrand = "Apple";
        ipad1.ipadId = 1;
        ipad1.ipadPrice = 1000.75;
        ipad1.isAvailable = true;
        ipad1.modelName = "iPad Pro";
        ipad1.storageGB = 128;
        ipad1.weight = 0.47;
        ipad1.isWifiOnly = false;
        ipad1.processor = "M2";
        ipad1.warrantyYears = 1;
        ipad1.screenSize = 11.0;
        ipad1.hasFaceID = true;
        ipad1.color = "Space Gray";
        ipad1.stockQuantity = 25;
        ipad1.thickness = 0.59;
        ipad1.isEcoFriendly = true;
        ipad1.osVersion = "iPadOS";
        ipad1.rating = 5;
        ipad1.batteryCapacity = 7538.0;
        ipad1.isCertified = true;
        ipad1.countryOfOrigin = "China";
        ipad1.manufacturingYear = 2025;
        ipad1.cameraMP = 12.0;
        ipad1.supportsPencil = true;
        ipad1.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad1.ipadBrand);
        System.out.println("The ipadId is : " + ipad1.ipadId);
        System.out.println("The ipadPrice is : " + ipad1.ipadPrice);
        System.out.println("The isAvailable is : " + ipad1.isAvailable);
        System.out.println("The modelName is : " + ipad1.modelName);
        System.out.println("The storageGB is : " + ipad1.storageGB);
        System.out.println("The weight is : " + ipad1.weight);
        System.out.println("The isWifiOnly is : " + ipad1.isWifiOnly);
        System.out.println("The processor is : " + ipad1.processor);
        System.out.println("The warrantyYears is : " + ipad1.warrantyYears);
        System.out.println("The screenSize is : " + ipad1.screenSize);
        System.out.println("The hasFaceID is : " + ipad1.hasFaceID);
        System.out.println("The color is : " + ipad1.color);
        System.out.println("The stockQuantity is : " + ipad1.stockQuantity);
        System.out.println("The thickness is : " + ipad1.thickness);
        System.out.println("The isEcoFriendly is : " + ipad1.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad1.osVersion);
        System.out.println("The rating is : " + ipad1.rating);
        System.out.println("The batteryCapacity is : " + ipad1.batteryCapacity);
        System.out.println("The isCertified is : " + ipad1.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad1.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad1.cameraMP);
        System.out.println("The supportsPencil is : " + ipad1.supportsPencil);
        System.out.println("The certificationType is : " + ipad1.certificationType);


        Ipad ipad2 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad2.ipadBrand);
        System.out.println("The ipadId is : " + ipad2.ipadId);
        System.out.println("The ipadPrice is : " + ipad2.ipadPrice);
        System.out.println("The isAvailable is : " + ipad2.isAvailable);
        System.out.println("The modelName is : " + ipad2.modelName);
        System.out.println("The storageGB is : " + ipad2.storageGB);
        System.out.println("The weight is : " + ipad2.weight);
        System.out.println("The isWifiOnly is : " + ipad2.isWifiOnly);
        System.out.println("The processor is : " + ipad2.processor);
        System.out.println("The warrantyYears is : " + ipad2.warrantyYears);
        System.out.println("The screenSize is : " + ipad2.screenSize);
        System.out.println("The hasFaceID is : " + ipad2.hasFaceID);
        System.out.println("The color is : " + ipad2.color);
        System.out.println("The stockQuantity is : " + ipad2.stockQuantity);
        System.out.println("The thickness is : " + ipad2.thickness);
        System.out.println("The isEcoFriendly is : " + ipad2.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad2.osVersion);
        System.out.println("The rating is : " + ipad2.rating);
        System.out.println("The batteryCapacity is : " + ipad2.batteryCapacity);
        System.out.println("The isCertified is : " + ipad2.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad2.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad2.cameraMP);
        System.out.println("The supportsPencil is : " + ipad2.supportsPencil);
        System.out.println("The certificationType is : " + ipad2.certificationType);

        ipad2.ipadBrand = "Apple";
        ipad2.ipadId = 2;
        ipad2.ipadPrice = 2000.75;
        ipad2.isAvailable = true;
        ipad2.modelName = "iPad Pro";
        ipad2.storageGB = 128;
        ipad2.weight = 0.47;
        ipad2.isWifiOnly = false;
        ipad2.processor = "M2";
        ipad2.warrantyYears = 1;
        ipad2.screenSize = 11.0;
        ipad2.hasFaceID = true;
        ipad2.color = "Space Gray";
        ipad2.stockQuantity = 25;
        ipad2.thickness = 0.59;
        ipad2.isEcoFriendly = true;
        ipad2.osVersion = "iPadOS";
        ipad2.rating = 5;
        ipad2.batteryCapacity = 7538.0;
        ipad2.isCertified = true;
        ipad2.countryOfOrigin = "China";
        ipad2.manufacturingYear = 2025;
        ipad2.cameraMP = 12.0;
        ipad2.supportsPencil = true;
        ipad2.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad2.ipadBrand);
        System.out.println("The ipadId is : " + ipad2.ipadId);
        System.out.println("The ipadPrice is : " + ipad2.ipadPrice);
        System.out.println("The isAvailable is : " + ipad2.isAvailable);
        System.out.println("The modelName is : " + ipad2.modelName);
        System.out.println("The storageGB is : " + ipad2.storageGB);
        System.out.println("The weight is : " + ipad2.weight);
        System.out.println("The isWifiOnly is : " + ipad2.isWifiOnly);
        System.out.println("The processor is : " + ipad2.processor);
        System.out.println("The warrantyYears is : " + ipad2.warrantyYears);
        System.out.println("The screenSize is : " + ipad2.screenSize);
        System.out.println("The hasFaceID is : " + ipad2.hasFaceID);
        System.out.println("The color is : " + ipad2.color);
        System.out.println("The stockQuantity is : " + ipad2.stockQuantity);
        System.out.println("The thickness is : " + ipad2.thickness);
        System.out.println("The isEcoFriendly is : " + ipad2.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad2.osVersion);
        System.out.println("The rating is : " + ipad2.rating);
        System.out.println("The batteryCapacity is : " + ipad2.batteryCapacity);
        System.out.println("The isCertified is : " + ipad2.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad2.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad2.cameraMP);
        System.out.println("The supportsPencil is : " + ipad2.supportsPencil);
        System.out.println("The certificationType is : " + ipad2.certificationType);


        Ipad ipad3 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad3.ipadBrand);
        System.out.println("The ipadId is : " + ipad3.ipadId);
        System.out.println("The ipadPrice is : " + ipad3.ipadPrice);
        System.out.println("The isAvailable is : " + ipad3.isAvailable);
        System.out.println("The modelName is : " + ipad3.modelName);
        System.out.println("The storageGB is : " + ipad3.storageGB);
        System.out.println("The weight is : " + ipad3.weight);
        System.out.println("The isWifiOnly is : " + ipad3.isWifiOnly);
        System.out.println("The processor is : " + ipad3.processor);
        System.out.println("The warrantyYears is : " + ipad3.warrantyYears);
        System.out.println("The screenSize is : " + ipad3.screenSize);
        System.out.println("The hasFaceID is : " + ipad3.hasFaceID);
        System.out.println("The color is : " + ipad3.color);
        System.out.println("The stockQuantity is : " + ipad3.stockQuantity);
        System.out.println("The thickness is : " + ipad3.thickness);
        System.out.println("The isEcoFriendly is : " + ipad3.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad3.osVersion);
        System.out.println("The rating is : " + ipad3.rating);
        System.out.println("The batteryCapacity is : " + ipad3.batteryCapacity);
        System.out.println("The isCertified is : " + ipad3.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad3.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad3.cameraMP);
        System.out.println("The supportsPencil is : " + ipad3.supportsPencil);
        System.out.println("The certificationType is : " + ipad3.certificationType);

        ipad3.ipadBrand = "Apple";
        ipad3.ipadId = 3;
        ipad3.ipadPrice = 3000.75;
        ipad3.isAvailable = true;
        ipad3.modelName = "iPad Pro";
        ipad3.storageGB = 128;
        ipad3.weight = 0.47;
        ipad3.isWifiOnly = false;
        ipad3.processor = "M2";
        ipad3.warrantyYears = 1;
        ipad3.screenSize = 11.0;
        ipad3.hasFaceID = true;
        ipad3.color = "Space Gray";
        ipad3.stockQuantity = 25;
        ipad3.thickness = 0.59;
        ipad3.isEcoFriendly = true;
        ipad3.osVersion = "iPadOS";
        ipad3.rating = 5;
        ipad3.batteryCapacity = 7538.0;
        ipad3.isCertified = true;
        ipad3.countryOfOrigin = "China";
        ipad3.manufacturingYear = 2025;
        ipad3.cameraMP = 12.0;
        ipad3.supportsPencil = true;
        ipad3.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad3.ipadBrand);
        System.out.println("The ipadId is : " + ipad3.ipadId);
        System.out.println("The ipadPrice is : " + ipad3.ipadPrice);
        System.out.println("The isAvailable is : " + ipad3.isAvailable);
        System.out.println("The modelName is : " + ipad3.modelName);
        System.out.println("The storageGB is : " + ipad3.storageGB);
        System.out.println("The weight is : " + ipad3.weight);
        System.out.println("The isWifiOnly is : " + ipad3.isWifiOnly);
        System.out.println("The processor is : " + ipad3.processor);
        System.out.println("The warrantyYears is : " + ipad3.warrantyYears);
        System.out.println("The screenSize is : " + ipad3.screenSize);
        System.out.println("The hasFaceID is : " + ipad3.hasFaceID);
        System.out.println("The color is : " + ipad3.color);
        System.out.println("The stockQuantity is : " + ipad3.stockQuantity);
        System.out.println("The thickness is : " + ipad3.thickness);
        System.out.println("The isEcoFriendly is : " + ipad3.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad3.osVersion);
        System.out.println("The rating is : " + ipad3.rating);
        System.out.println("The batteryCapacity is : " + ipad3.batteryCapacity);
        System.out.println("The isCertified is : " + ipad3.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad3.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad3.cameraMP);
        System.out.println("The supportsPencil is : " + ipad3.supportsPencil);
        System.out.println("The certificationType is : " + ipad3.certificationType);


        Ipad ipad4 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad4.ipadBrand);
        System.out.println("The ipadId is : " + ipad4.ipadId);
        System.out.println("The ipadPrice is : " + ipad4.ipadPrice);
        System.out.println("The isAvailable is : " + ipad4.isAvailable);
        System.out.println("The modelName is : " + ipad4.modelName);
        System.out.println("The storageGB is : " + ipad4.storageGB);
        System.out.println("The weight is : " + ipad4.weight);
        System.out.println("The isWifiOnly is : " + ipad4.isWifiOnly);
        System.out.println("The processor is : " + ipad4.processor);
        System.out.println("The warrantyYears is : " + ipad4.warrantyYears);
        System.out.println("The screenSize is : " + ipad4.screenSize);
        System.out.println("The hasFaceID is : " + ipad4.hasFaceID);
        System.out.println("The color is : " + ipad4.color);
        System.out.println("The stockQuantity is : " + ipad4.stockQuantity);
        System.out.println("The thickness is : " + ipad4.thickness);
        System.out.println("The isEcoFriendly is : " + ipad4.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad4.osVersion);
        System.out.println("The rating is : " + ipad4.rating);
        System.out.println("The batteryCapacity is : " + ipad4.batteryCapacity);
        System.out.println("The isCertified is : " + ipad4.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad4.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad4.cameraMP);
        System.out.println("The supportsPencil is : " + ipad4.supportsPencil);
        System.out.println("The certificationType is : " + ipad4.certificationType);

        ipad4.ipadBrand = "Apple";
        ipad4.ipadId = 4;
        ipad4.ipadPrice = 4000.75;
        ipad4.isAvailable = true;
        ipad4.modelName = "iPad Pro";
        ipad4.storageGB = 128;
        ipad4.weight = 0.47;
        ipad4.isWifiOnly = false;
        ipad4.processor = "M2";
        ipad4.warrantyYears = 1;
        ipad4.screenSize = 11.0;
        ipad4.hasFaceID = true;
        ipad4.color = "Space Gray";
        ipad4.stockQuantity = 25;
        ipad4.thickness = 0.59;
        ipad4.isEcoFriendly = true;
        ipad4.osVersion = "iPadOS";
        ipad4.rating = 5;
        ipad4.batteryCapacity = 7538.0;
        ipad4.isCertified = true;
        ipad4.countryOfOrigin = "China";
        ipad4.manufacturingYear = 2025;
        ipad4.cameraMP = 12.0;
        ipad4.supportsPencil = true;
        ipad4.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad4.ipadBrand);
        System.out.println("The ipadId is : " + ipad4.ipadId);
        System.out.println("The ipadPrice is : " + ipad4.ipadPrice);
        System.out.println("The isAvailable is : " + ipad4.isAvailable);
        System.out.println("The modelName is : " + ipad4.modelName);
        System.out.println("The storageGB is : " + ipad4.storageGB);
        System.out.println("The weight is : " + ipad4.weight);
        System.out.println("The isWifiOnly is : " + ipad4.isWifiOnly);
        System.out.println("The processor is : " + ipad4.processor);
        System.out.println("The warrantyYears is : " + ipad4.warrantyYears);
        System.out.println("The screenSize is : " + ipad4.screenSize);
        System.out.println("The hasFaceID is : " + ipad4.hasFaceID);
        System.out.println("The color is : " + ipad4.color);
        System.out.println("The stockQuantity is : " + ipad4.stockQuantity);
        System.out.println("The thickness is : " + ipad4.thickness);
        System.out.println("The isEcoFriendly is : " + ipad4.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad4.osVersion);
        System.out.println("The rating is : " + ipad4.rating);
        System.out.println("The batteryCapacity is : " + ipad4.batteryCapacity);
        System.out.println("The isCertified is : " + ipad4.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad4.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad4.cameraMP);
        System.out.println("The supportsPencil is : " + ipad4.supportsPencil);
        System.out.println("The certificationType is : " + ipad4.certificationType);


        Ipad ipad5 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad5.ipadBrand);
        System.out.println("The ipadId is : " + ipad5.ipadId);
        System.out.println("The ipadPrice is : " + ipad5.ipadPrice);
        System.out.println("The isAvailable is : " + ipad5.isAvailable);
        System.out.println("The modelName is : " + ipad5.modelName);
        System.out.println("The storageGB is : " + ipad5.storageGB);
        System.out.println("The weight is : " + ipad5.weight);
        System.out.println("The isWifiOnly is : " + ipad5.isWifiOnly);
        System.out.println("The processor is : " + ipad5.processor);
        System.out.println("The warrantyYears is : " + ipad5.warrantyYears);
        System.out.println("The screenSize is : " + ipad5.screenSize);
        System.out.println("The hasFaceID is : " + ipad5.hasFaceID);
        System.out.println("The color is : " + ipad5.color);
        System.out.println("The stockQuantity is : " + ipad5.stockQuantity);
        System.out.println("The thickness is : " + ipad5.thickness);
        System.out.println("The isEcoFriendly is : " + ipad5.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad5.osVersion);
        System.out.println("The rating is : " + ipad5.rating);
        System.out.println("The batteryCapacity is : " + ipad5.batteryCapacity);
        System.out.println("The isCertified is : " + ipad5.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad5.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad5.cameraMP);
        System.out.println("The supportsPencil is : " + ipad5.supportsPencil);
        System.out.println("The certificationType is : " + ipad5.certificationType);

        ipad5.ipadBrand = "Apple";
        ipad5.ipadId = 5;
        ipad5.ipadPrice = 5000.75;
        ipad5.isAvailable = true;
        ipad5.modelName = "iPad Pro";
        ipad5.storageGB = 128;
        ipad5.weight = 0.47;
        ipad5.isWifiOnly = false;
        ipad5.processor = "M2";
        ipad5.warrantyYears = 1;
        ipad5.screenSize = 11.0;
        ipad5.hasFaceID = true;
        ipad5.color = "Space Gray";
        ipad5.stockQuantity = 25;
        ipad5.thickness = 0.59;
        ipad5.isEcoFriendly = true;
        ipad5.osVersion = "iPadOS";
        ipad5.rating = 5;
        ipad5.batteryCapacity = 7538.0;
        ipad5.isCertified = true;
        ipad5.countryOfOrigin = "China";
        ipad5.manufacturingYear = 2025;
        ipad5.cameraMP = 12.0;
        ipad5.supportsPencil = true;
        ipad5.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad5.ipadBrand);
        System.out.println("The ipadId is : " + ipad5.ipadId);
        System.out.println("The ipadPrice is : " + ipad5.ipadPrice);
        System.out.println("The isAvailable is : " + ipad5.isAvailable);
        System.out.println("The modelName is : " + ipad5.modelName);
        System.out.println("The storageGB is : " + ipad5.storageGB);
        System.out.println("The weight is : " + ipad5.weight);
        System.out.println("The isWifiOnly is : " + ipad5.isWifiOnly);
        System.out.println("The processor is : " + ipad5.processor);
        System.out.println("The warrantyYears is : " + ipad5.warrantyYears);
        System.out.println("The screenSize is : " + ipad5.screenSize);
        System.out.println("The hasFaceID is : " + ipad5.hasFaceID);
        System.out.println("The color is : " + ipad5.color);
        System.out.println("The stockQuantity is : " + ipad5.stockQuantity);
        System.out.println("The thickness is : " + ipad5.thickness);
        System.out.println("The isEcoFriendly is : " + ipad5.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad5.osVersion);
        System.out.println("The rating is : " + ipad5.rating);
        System.out.println("The batteryCapacity is : " + ipad5.batteryCapacity);
        System.out.println("The isCertified is : " + ipad5.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad5.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad5.cameraMP);
        System.out.println("The supportsPencil is : " + ipad5.supportsPencil);
        System.out.println("The certificationType is : " + ipad5.certificationType);


        Ipad ipad6 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad6.ipadBrand);
        System.out.println("The ipadId is : " + ipad6.ipadId);
        System.out.println("The ipadPrice is : " + ipad6.ipadPrice);
        System.out.println("The isAvailable is : " + ipad6.isAvailable);
        System.out.println("The modelName is : " + ipad6.modelName);
        System.out.println("The storageGB is : " + ipad6.storageGB);
        System.out.println("The weight is : " + ipad6.weight);
        System.out.println("The isWifiOnly is : " + ipad6.isWifiOnly);
        System.out.println("The processor is : " + ipad6.processor);
        System.out.println("The warrantyYears is : " + ipad6.warrantyYears);
        System.out.println("The screenSize is : " + ipad6.screenSize);
        System.out.println("The hasFaceID is : " + ipad6.hasFaceID);
        System.out.println("The color is : " + ipad6.color);
        System.out.println("The stockQuantity is : " + ipad6.stockQuantity);
        System.out.println("The thickness is : " + ipad6.thickness);
        System.out.println("The isEcoFriendly is : " + ipad6.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad6.osVersion);
        System.out.println("The rating is : " + ipad6.rating);
        System.out.println("The batteryCapacity is : " + ipad6.batteryCapacity);
        System.out.println("The isCertified is : " + ipad6.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad6.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad6.cameraMP);
        System.out.println("The supportsPencil is : " + ipad6.supportsPencil);
        System.out.println("The certificationType is : " + ipad6.certificationType);

        ipad6.ipadBrand = "Apple";
        ipad6.ipadId = 6;
        ipad6.ipadPrice = 6000.75;
        ipad6.isAvailable = true;
        ipad6.modelName = "iPad Pro";
        ipad6.storageGB = 128;
        ipad6.weight = 0.47;
        ipad6.isWifiOnly = false;
        ipad6.processor = "M2";
        ipad6.warrantyYears = 1;
        ipad6.screenSize = 11.0;
        ipad6.hasFaceID = true;
        ipad6.color = "Space Gray";
        ipad6.stockQuantity = 25;
        ipad6.thickness = 0.59;
        ipad6.isEcoFriendly = true;
        ipad6.osVersion = "iPadOS";
        ipad6.rating = 5;
        ipad6.batteryCapacity = 7538.0;
        ipad6.isCertified = true;
        ipad6.countryOfOrigin = "China";
        ipad6.manufacturingYear = 2025;
        ipad6.cameraMP = 12.0;
        ipad6.supportsPencil = true;
        ipad6.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad6.ipadBrand);
        System.out.println("The ipadId is : " + ipad6.ipadId);
        System.out.println("The ipadPrice is : " + ipad6.ipadPrice);
        System.out.println("The isAvailable is : " + ipad6.isAvailable);
        System.out.println("The modelName is : " + ipad6.modelName);
        System.out.println("The storageGB is : " + ipad6.storageGB);
        System.out.println("The weight is : " + ipad6.weight);
        System.out.println("The isWifiOnly is : " + ipad6.isWifiOnly);
        System.out.println("The processor is : " + ipad6.processor);
        System.out.println("The warrantyYears is : " + ipad6.warrantyYears);
        System.out.println("The screenSize is : " + ipad6.screenSize);
        System.out.println("The hasFaceID is : " + ipad6.hasFaceID);
        System.out.println("The color is : " + ipad6.color);
        System.out.println("The stockQuantity is : " + ipad6.stockQuantity);
        System.out.println("The thickness is : " + ipad6.thickness);
        System.out.println("The isEcoFriendly is : " + ipad6.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad6.osVersion);
        System.out.println("The rating is : " + ipad6.rating);
        System.out.println("The batteryCapacity is : " + ipad6.batteryCapacity);
        System.out.println("The isCertified is : " + ipad6.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad6.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad6.cameraMP);
        System.out.println("The supportsPencil is : " + ipad6.supportsPencil);
        System.out.println("The certificationType is : " + ipad6.certificationType);


        Ipad ipad7 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad7.ipadBrand);
        System.out.println("The ipadId is : " + ipad7.ipadId);
        System.out.println("The ipadPrice is : " + ipad7.ipadPrice);
        System.out.println("The isAvailable is : " + ipad7.isAvailable);
        System.out.println("The modelName is : " + ipad7.modelName);
        System.out.println("The storageGB is : " + ipad7.storageGB);
        System.out.println("The weight is : " + ipad7.weight);
        System.out.println("The isWifiOnly is : " + ipad7.isWifiOnly);
        System.out.println("The processor is : " + ipad7.processor);
        System.out.println("The warrantyYears is : " + ipad7.warrantyYears);
        System.out.println("The screenSize is : " + ipad7.screenSize);
        System.out.println("The hasFaceID is : " + ipad7.hasFaceID);
        System.out.println("The color is : " + ipad7.color);
        System.out.println("The stockQuantity is : " + ipad7.stockQuantity);
        System.out.println("The thickness is : " + ipad7.thickness);
        System.out.println("The isEcoFriendly is : " + ipad7.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad7.osVersion);
        System.out.println("The rating is : " + ipad7.rating);
        System.out.println("The batteryCapacity is : " + ipad7.batteryCapacity);
        System.out.println("The isCertified is : " + ipad7.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad7.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad7.cameraMP);
        System.out.println("The supportsPencil is : " + ipad7.supportsPencil);
        System.out.println("The certificationType is : " + ipad7.certificationType);

        ipad7.ipadBrand = "Apple";
        ipad7.ipadId = 7;
        ipad7.ipadPrice = 7000.75;
        ipad7.isAvailable = true;
        ipad7.modelName = "iPad Pro";
        ipad7.storageGB = 128;
        ipad7.weight = 0.47;
        ipad7.isWifiOnly = false;
        ipad7.processor = "M2";
        ipad7.warrantyYears = 1;
        ipad7.screenSize = 11.0;
        ipad7.hasFaceID = true;
        ipad7.color = "Space Gray";
        ipad7.stockQuantity = 25;
        ipad7.thickness = 0.59;
        ipad7.isEcoFriendly = true;
        ipad7.osVersion = "iPadOS";
        ipad7.rating = 5;
        ipad7.batteryCapacity = 7538.0;
        ipad7.isCertified = true;
        ipad7.countryOfOrigin = "China";
        ipad7.manufacturingYear = 2025;
        ipad7.cameraMP = 12.0;
        ipad7.supportsPencil = true;
        ipad7.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad7.ipadBrand);
        System.out.println("The ipadId is : " + ipad7.ipadId);
        System.out.println("The ipadPrice is : " + ipad7.ipadPrice);
        System.out.println("The isAvailable is : " + ipad7.isAvailable);
        System.out.println("The modelName is : " + ipad7.modelName);
        System.out.println("The storageGB is : " + ipad7.storageGB);
        System.out.println("The weight is : " + ipad7.weight);
        System.out.println("The isWifiOnly is : " + ipad7.isWifiOnly);
        System.out.println("The processor is : " + ipad7.processor);
        System.out.println("The warrantyYears is : " + ipad7.warrantyYears);
        System.out.println("The screenSize is : " + ipad7.screenSize);
        System.out.println("The hasFaceID is : " + ipad7.hasFaceID);
        System.out.println("The color is : " + ipad7.color);
        System.out.println("The stockQuantity is : " + ipad7.stockQuantity);
        System.out.println("The thickness is : " + ipad7.thickness);
        System.out.println("The isEcoFriendly is : " + ipad7.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad7.osVersion);
        System.out.println("The rating is : " + ipad7.rating);
        System.out.println("The batteryCapacity is : " + ipad7.batteryCapacity);
        System.out.println("The isCertified is : " + ipad7.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad7.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad7.cameraMP);
        System.out.println("The supportsPencil is : " + ipad7.supportsPencil);
        System.out.println("The certificationType is : " + ipad7.certificationType);


        Ipad ipad8 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad8.ipadBrand);
        System.out.println("The ipadId is : " + ipad8.ipadId);
        System.out.println("The ipadPrice is : " + ipad8.ipadPrice);
        System.out.println("The isAvailable is : " + ipad8.isAvailable);
        System.out.println("The modelName is : " + ipad8.modelName);
        System.out.println("The storageGB is : " + ipad8.storageGB);
        System.out.println("The weight is : " + ipad8.weight);
        System.out.println("The isWifiOnly is : " + ipad8.isWifiOnly);
        System.out.println("The processor is : " + ipad8.processor);
        System.out.println("The warrantyYears is : " + ipad8.warrantyYears);
        System.out.println("The screenSize is : " + ipad8.screenSize);
        System.out.println("The hasFaceID is : " + ipad8.hasFaceID);
        System.out.println("The color is : " + ipad8.color);
        System.out.println("The stockQuantity is : " + ipad8.stockQuantity);
        System.out.println("The thickness is : " + ipad8.thickness);
        System.out.println("The isEcoFriendly is : " + ipad8.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad8.osVersion);
        System.out.println("The rating is : " + ipad8.rating);
        System.out.println("The batteryCapacity is : " + ipad8.batteryCapacity);
        System.out.println("The isCertified is : " + ipad8.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad8.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad8.cameraMP);
        System.out.println("The supportsPencil is : " + ipad8.supportsPencil);
        System.out.println("The certificationType is : " + ipad8.certificationType);

        ipad8.ipadBrand = "Apple";
        ipad8.ipadId = 8;
        ipad8.ipadPrice = 8000.75;
        ipad8.isAvailable = true;
        ipad8.modelName = "iPad Pro";
        ipad8.storageGB = 128;
        ipad8.weight = 0.47;
        ipad8.isWifiOnly = false;
        ipad8.processor = "M2";
        ipad8.warrantyYears = 1;
        ipad8.screenSize = 11.0;
        ipad8.hasFaceID = true;
        ipad8.color = "Space Gray";
        ipad8.stockQuantity = 25;
        ipad8.thickness = 0.59;
        ipad8.isEcoFriendly = true;
        ipad8.osVersion = "iPadOS";
        ipad8.rating = 5;
        ipad8.batteryCapacity = 7538.0;
        ipad8.isCertified = true;
        ipad8.countryOfOrigin = "China";
        ipad8.manufacturingYear = 2025;
        ipad8.cameraMP = 12.0;
        ipad8.supportsPencil = true;
        ipad8.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad8.ipadBrand);
        System.out.println("The ipadId is : " + ipad8.ipadId);
        System.out.println("The ipadPrice is : " + ipad8.ipadPrice);
        System.out.println("The isAvailable is : " + ipad8.isAvailable);
        System.out.println("The modelName is : " + ipad8.modelName);
        System.out.println("The storageGB is : " + ipad8.storageGB);
        System.out.println("The weight is : " + ipad8.weight);
        System.out.println("The isWifiOnly is : " + ipad8.isWifiOnly);
        System.out.println("The processor is : " + ipad8.processor);
        System.out.println("The warrantyYears is : " + ipad8.warrantyYears);
        System.out.println("The screenSize is : " + ipad8.screenSize);
        System.out.println("The hasFaceID is : " + ipad8.hasFaceID);
        System.out.println("The color is : " + ipad8.color);
        System.out.println("The stockQuantity is : " + ipad8.stockQuantity);
        System.out.println("The thickness is : " + ipad8.thickness);
        System.out.println("The isEcoFriendly is : " + ipad8.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad8.osVersion);
        System.out.println("The rating is : " + ipad8.rating);
        System.out.println("The batteryCapacity is : " + ipad8.batteryCapacity);
        System.out.println("The isCertified is : " + ipad8.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad8.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad8.cameraMP);
        System.out.println("The supportsPencil is : " + ipad8.supportsPencil);
        System.out.println("The certificationType is : " + ipad8.certificationType);


        Ipad ipad9 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad9.ipadBrand);
        System.out.println("The ipadId is : " + ipad9.ipadId);
        System.out.println("The ipadPrice is : " + ipad9.ipadPrice);
        System.out.println("The isAvailable is : " + ipad9.isAvailable);
        System.out.println("The modelName is : " + ipad9.modelName);
        System.out.println("The storageGB is : " + ipad9.storageGB);
        System.out.println("The weight is : " + ipad9.weight);
        System.out.println("The isWifiOnly is : " + ipad9.isWifiOnly);
        System.out.println("The processor is : " + ipad9.processor);
        System.out.println("The warrantyYears is : " + ipad9.warrantyYears);
        System.out.println("The screenSize is : " + ipad9.screenSize);
        System.out.println("The hasFaceID is : " + ipad9.hasFaceID);
        System.out.println("The color is : " + ipad9.color);
        System.out.println("The stockQuantity is : " + ipad9.stockQuantity);
        System.out.println("The thickness is : " + ipad9.thickness);
        System.out.println("The isEcoFriendly is : " + ipad9.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad9.osVersion);
        System.out.println("The rating is : " + ipad9.rating);
        System.out.println("The batteryCapacity is : " + ipad9.batteryCapacity);
        System.out.println("The isCertified is : " + ipad9.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad9.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad9.cameraMP);
        System.out.println("The supportsPencil is : " + ipad9.supportsPencil);
        System.out.println("The certificationType is : " + ipad9.certificationType);

        ipad9.ipadBrand = "Apple";
        ipad9.ipadId = 9;
        ipad9.ipadPrice = 9000.75;
        ipad9.isAvailable = true;
        ipad9.modelName = "iPad Pro";
        ipad9.storageGB = 128;
        ipad9.weight = 0.47;
        ipad9.isWifiOnly = false;
        ipad9.processor = "M2";
        ipad9.warrantyYears = 1;
        ipad9.screenSize = 11.0;
        ipad9.hasFaceID = true;
        ipad9.color = "Space Gray";
        ipad9.stockQuantity = 25;
        ipad9.thickness = 0.59;
        ipad9.isEcoFriendly = true;
        ipad9.osVersion = "iPadOS";
        ipad9.rating = 5;
        ipad9.batteryCapacity = 7538.0;
        ipad9.isCertified = true;
        ipad9.countryOfOrigin = "China";
        ipad9.manufacturingYear = 2025;
        ipad9.cameraMP = 12.0;
        ipad9.supportsPencil = true;
        ipad9.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad9.ipadBrand);
        System.out.println("The ipadId is : " + ipad9.ipadId);
        System.out.println("The ipadPrice is : " + ipad9.ipadPrice);
        System.out.println("The isAvailable is : " + ipad9.isAvailable);
        System.out.println("The modelName is : " + ipad9.modelName);
        System.out.println("The storageGB is : " + ipad9.storageGB);
        System.out.println("The weight is : " + ipad9.weight);
        System.out.println("The isWifiOnly is : " + ipad9.isWifiOnly);
        System.out.println("The processor is : " + ipad9.processor);
        System.out.println("The warrantyYears is : " + ipad9.warrantyYears);
        System.out.println("The screenSize is : " + ipad9.screenSize);
        System.out.println("The hasFaceID is : " + ipad9.hasFaceID);
        System.out.println("The color is : " + ipad9.color);
        System.out.println("The stockQuantity is : " + ipad9.stockQuantity);
        System.out.println("The thickness is : " + ipad9.thickness);
        System.out.println("The isEcoFriendly is : " + ipad9.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad9.osVersion);
        System.out.println("The rating is : " + ipad9.rating);
        System.out.println("The batteryCapacity is : " + ipad9.batteryCapacity);
        System.out.println("The isCertified is : " + ipad9.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad9.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad9.cameraMP);
        System.out.println("The supportsPencil is : " + ipad9.supportsPencil);
        System.out.println("The certificationType is : " + ipad9.certificationType);


        Ipad ipad10 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad10.ipadBrand);
        System.out.println("The ipadId is : " + ipad10.ipadId);
        System.out.println("The ipadPrice is : " + ipad10.ipadPrice);
        System.out.println("The isAvailable is : " + ipad10.isAvailable);
        System.out.println("The modelName is : " + ipad10.modelName);
        System.out.println("The storageGB is : " + ipad10.storageGB);
        System.out.println("The weight is : " + ipad10.weight);
        System.out.println("The isWifiOnly is : " + ipad10.isWifiOnly);
        System.out.println("The processor is : " + ipad10.processor);
        System.out.println("The warrantyYears is : " + ipad10.warrantyYears);
        System.out.println("The screenSize is : " + ipad10.screenSize);
        System.out.println("The hasFaceID is : " + ipad10.hasFaceID);
        System.out.println("The color is : " + ipad10.color);
        System.out.println("The stockQuantity is : " + ipad10.stockQuantity);
        System.out.println("The thickness is : " + ipad10.thickness);
        System.out.println("The isEcoFriendly is : " + ipad10.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad10.osVersion);
        System.out.println("The rating is : " + ipad10.rating);
        System.out.println("The batteryCapacity is : " + ipad10.batteryCapacity);
        System.out.println("The isCertified is : " + ipad10.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad10.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad10.cameraMP);
        System.out.println("The supportsPencil is : " + ipad10.supportsPencil);
        System.out.println("The certificationType is : " + ipad10.certificationType);

        ipad10.ipadBrand = "Apple";
        ipad10.ipadId = 10;
        ipad10.ipadPrice = 10000.75;
        ipad10.isAvailable = true;
        ipad10.modelName = "iPad Pro";
        ipad10.storageGB = 128;
        ipad10.weight = 0.47;
        ipad10.isWifiOnly = false;
        ipad10.processor = "M2";
        ipad10.warrantyYears = 1;
        ipad10.screenSize = 11.0;
        ipad10.hasFaceID = true;
        ipad10.color = "Space Gray";
        ipad10.stockQuantity = 25;
        ipad10.thickness = 0.59;
        ipad10.isEcoFriendly = true;
        ipad10.osVersion = "iPadOS";
        ipad10.rating = 5;
        ipad10.batteryCapacity = 7538.0;
        ipad10.isCertified = true;
        ipad10.countryOfOrigin = "China";
        ipad10.manufacturingYear = 2025;
        ipad10.cameraMP = 12.0;
        ipad10.supportsPencil = true;
        ipad10.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad10.ipadBrand);
        System.out.println("The ipadId is : " + ipad10.ipadId);
        System.out.println("The ipadPrice is : " + ipad10.ipadPrice);
        System.out.println("The isAvailable is : " + ipad10.isAvailable);
        System.out.println("The modelName is : " + ipad10.modelName);
        System.out.println("The storageGB is : " + ipad10.storageGB);
        System.out.println("The weight is : " + ipad10.weight);
        System.out.println("The isWifiOnly is : " + ipad10.isWifiOnly);
        System.out.println("The processor is : " + ipad10.processor);
        System.out.println("The warrantyYears is : " + ipad10.warrantyYears);
        System.out.println("The screenSize is : " + ipad10.screenSize);
        System.out.println("The hasFaceID is : " + ipad10.hasFaceID);
        System.out.println("The color is : " + ipad10.color);
        System.out.println("The stockQuantity is : " + ipad10.stockQuantity);
        System.out.println("The thickness is : " + ipad10.thickness);
        System.out.println("The isEcoFriendly is : " + ipad10.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad10.osVersion);
        System.out.println("The rating is : " + ipad10.rating);
        System.out.println("The batteryCapacity is : " + ipad10.batteryCapacity);
        System.out.println("The isCertified is : " + ipad10.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad10.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad10.cameraMP);
        System.out.println("The supportsPencil is : " + ipad10.supportsPencil);
        System.out.println("The certificationType is : " + ipad10.certificationType);


        Ipad ipad11 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad11.ipadBrand);
        System.out.println("The ipadId is : " + ipad11.ipadId);
        System.out.println("The ipadPrice is : " + ipad11.ipadPrice);
        System.out.println("The isAvailable is : " + ipad11.isAvailable);
        System.out.println("The modelName is : " + ipad11.modelName);
        System.out.println("The storageGB is : " + ipad11.storageGB);
        System.out.println("The weight is : " + ipad11.weight);
        System.out.println("The isWifiOnly is : " + ipad11.isWifiOnly);
        System.out.println("The processor is : " + ipad11.processor);
        System.out.println("The warrantyYears is : " + ipad11.warrantyYears);
        System.out.println("The screenSize is : " + ipad11.screenSize);
        System.out.println("The hasFaceID is : " + ipad11.hasFaceID);
        System.out.println("The color is : " + ipad11.color);
        System.out.println("The stockQuantity is : " + ipad11.stockQuantity);
        System.out.println("The thickness is : " + ipad11.thickness);
        System.out.println("The isEcoFriendly is : " + ipad11.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad11.osVersion);
        System.out.println("The rating is : " + ipad11.rating);
        System.out.println("The batteryCapacity is : " + ipad11.batteryCapacity);
        System.out.println("The isCertified is : " + ipad11.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad11.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad11.cameraMP);
        System.out.println("The supportsPencil is : " + ipad11.supportsPencil);
        System.out.println("The certificationType is : " + ipad11.certificationType);

        ipad11.ipadBrand = "Apple";
        ipad11.ipadId = 11;
        ipad11.ipadPrice = 11000.75;
        ipad11.isAvailable = true;
        ipad11.modelName = "iPad Pro";
        ipad11.storageGB = 128;
        ipad11.weight = 0.47;
        ipad11.isWifiOnly = false;
        ipad11.processor = "M2";
        ipad11.warrantyYears = 1;
        ipad11.screenSize = 11.0;
        ipad11.hasFaceID = true;
        ipad11.color = "Space Gray";
        ipad11.stockQuantity = 25;
        ipad11.thickness = 0.59;
        ipad11.isEcoFriendly = true;
        ipad11.osVersion = "iPadOS";
        ipad11.rating = 5;
        ipad11.batteryCapacity = 7538.0;
        ipad11.isCertified = true;
        ipad11.countryOfOrigin = "China";
        ipad11.manufacturingYear = 2025;
        ipad11.cameraMP = 12.0;
        ipad11.supportsPencil = true;
        ipad11.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad11.ipadBrand);
        System.out.println("The ipadId is : " + ipad11.ipadId);
        System.out.println("The ipadPrice is : " + ipad11.ipadPrice);
        System.out.println("The isAvailable is : " + ipad11.isAvailable);
        System.out.println("The modelName is : " + ipad11.modelName);
        System.out.println("The storageGB is : " + ipad11.storageGB);
        System.out.println("The weight is : " + ipad11.weight);
        System.out.println("The isWifiOnly is : " + ipad11.isWifiOnly);
        System.out.println("The processor is : " + ipad11.processor);
        System.out.println("The warrantyYears is : " + ipad11.warrantyYears);
        System.out.println("The screenSize is : " + ipad11.screenSize);
        System.out.println("The hasFaceID is : " + ipad11.hasFaceID);
        System.out.println("The color is : " + ipad11.color);
        System.out.println("The stockQuantity is : " + ipad11.stockQuantity);
        System.out.println("The thickness is : " + ipad11.thickness);
        System.out.println("The isEcoFriendly is : " + ipad11.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad11.osVersion);
        System.out.println("The rating is : " + ipad11.rating);
        System.out.println("The batteryCapacity is : " + ipad11.batteryCapacity);
        System.out.println("The isCertified is : " + ipad11.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad11.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad11.cameraMP);
        System.out.println("The supportsPencil is : " + ipad11.supportsPencil);
        System.out.println("The certificationType is : " + ipad11.certificationType);


        Ipad ipad12 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad12.ipadBrand);
        System.out.println("The ipadId is : " + ipad12.ipadId);
        System.out.println("The ipadPrice is : " + ipad12.ipadPrice);
        System.out.println("The isAvailable is : " + ipad12.isAvailable);
        System.out.println("The modelName is : " + ipad12.modelName);
        System.out.println("The storageGB is : " + ipad12.storageGB);
        System.out.println("The weight is : " + ipad12.weight);
        System.out.println("The isWifiOnly is : " + ipad12.isWifiOnly);
        System.out.println("The processor is : " + ipad12.processor);
        System.out.println("The warrantyYears is : " + ipad12.warrantyYears);
        System.out.println("The screenSize is : " + ipad12.screenSize);
        System.out.println("The hasFaceID is : " + ipad12.hasFaceID);
        System.out.println("The color is : " + ipad12.color);
        System.out.println("The stockQuantity is : " + ipad12.stockQuantity);
        System.out.println("The thickness is : " + ipad12.thickness);
        System.out.println("The isEcoFriendly is : " + ipad12.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad12.osVersion);
        System.out.println("The rating is : " + ipad12.rating);
        System.out.println("The batteryCapacity is : " + ipad12.batteryCapacity);
        System.out.println("The isCertified is : " + ipad12.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad12.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad12.cameraMP);
        System.out.println("The supportsPencil is : " + ipad12.supportsPencil);
        System.out.println("The certificationType is : " + ipad12.certificationType);

        ipad12.ipadBrand = "Apple";
        ipad12.ipadId = 12;
        ipad12.ipadPrice = 12000.75;
        ipad12.isAvailable = true;
        ipad12.modelName = "iPad Pro";
        ipad12.storageGB = 128;
        ipad12.weight = 0.47;
        ipad12.isWifiOnly = false;
        ipad12.processor = "M2";
        ipad12.warrantyYears = 1;
        ipad12.screenSize = 11.0;
        ipad12.hasFaceID = true;
        ipad12.color = "Space Gray";
        ipad12.stockQuantity = 25;
        ipad12.thickness = 0.59;
        ipad12.isEcoFriendly = true;
        ipad12.osVersion = "iPadOS";
        ipad12.rating = 5;
        ipad12.batteryCapacity = 7538.0;
        ipad12.isCertified = true;
        ipad12.countryOfOrigin = "China";
        ipad12.manufacturingYear = 2025;
        ipad12.cameraMP = 12.0;
        ipad12.supportsPencil = true;
        ipad12.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad12.ipadBrand);
        System.out.println("The ipadId is : " + ipad12.ipadId);
        System.out.println("The ipadPrice is : " + ipad12.ipadPrice);
        System.out.println("The isAvailable is : " + ipad12.isAvailable);
        System.out.println("The modelName is : " + ipad12.modelName);
        System.out.println("The storageGB is : " + ipad12.storageGB);
        System.out.println("The weight is : " + ipad12.weight);
        System.out.println("The isWifiOnly is : " + ipad12.isWifiOnly);
        System.out.println("The processor is : " + ipad12.processor);
        System.out.println("The warrantyYears is : " + ipad12.warrantyYears);
        System.out.println("The screenSize is : " + ipad12.screenSize);
        System.out.println("The hasFaceID is : " + ipad12.hasFaceID);
        System.out.println("The color is : " + ipad12.color);
        System.out.println("The stockQuantity is : " + ipad12.stockQuantity);
        System.out.println("The thickness is : " + ipad12.thickness);
        System.out.println("The isEcoFriendly is : " + ipad12.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad12.osVersion);
        System.out.println("The rating is : " + ipad12.rating);
        System.out.println("The batteryCapacity is : " + ipad12.batteryCapacity);
        System.out.println("The isCertified is : " + ipad12.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad12.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad12.cameraMP);
        System.out.println("The supportsPencil is : " + ipad12.supportsPencil);
        System.out.println("The certificationType is : " + ipad12.certificationType);


        Ipad ipad13 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad13.ipadBrand);
        System.out.println("The ipadId is : " + ipad13.ipadId);
        System.out.println("The ipadPrice is : " + ipad13.ipadPrice);
        System.out.println("The isAvailable is : " + ipad13.isAvailable);
        System.out.println("The modelName is : " + ipad13.modelName);
        System.out.println("The storageGB is : " + ipad13.storageGB);
        System.out.println("The weight is : " + ipad13.weight);
        System.out.println("The isWifiOnly is : " + ipad13.isWifiOnly);
        System.out.println("The processor is : " + ipad13.processor);
        System.out.println("The warrantyYears is : " + ipad13.warrantyYears);
        System.out.println("The screenSize is : " + ipad13.screenSize);
        System.out.println("The hasFaceID is : " + ipad13.hasFaceID);
        System.out.println("The color is : " + ipad13.color);
        System.out.println("The stockQuantity is : " + ipad13.stockQuantity);
        System.out.println("The thickness is : " + ipad13.thickness);
        System.out.println("The isEcoFriendly is : " + ipad13.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad13.osVersion);
        System.out.println("The rating is : " + ipad13.rating);
        System.out.println("The batteryCapacity is : " + ipad13.batteryCapacity);
        System.out.println("The isCertified is : " + ipad13.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad13.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad13.cameraMP);
        System.out.println("The supportsPencil is : " + ipad13.supportsPencil);
        System.out.println("The certificationType is : " + ipad13.certificationType);

        ipad13.ipadBrand = "Apple";
        ipad13.ipadId = 13;
        ipad13.ipadPrice = 13000.75;
        ipad13.isAvailable = true;
        ipad13.modelName = "iPad Pro";
        ipad13.storageGB = 128;
        ipad13.weight = 0.47;
        ipad13.isWifiOnly = false;
        ipad13.processor = "M2";
        ipad13.warrantyYears = 1;
        ipad13.screenSize = 11.0;
        ipad13.hasFaceID = true;
        ipad13.color = "Space Gray";
        ipad13.stockQuantity = 25;
        ipad13.thickness = 0.59;
        ipad13.isEcoFriendly = true;
        ipad13.osVersion = "iPadOS";
        ipad13.rating = 5;
        ipad13.batteryCapacity = 7538.0;
        ipad13.isCertified = true;
        ipad13.countryOfOrigin = "China";
        ipad13.manufacturingYear = 2025;
        ipad13.cameraMP = 12.0;
        ipad13.supportsPencil = true;
        ipad13.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad13.ipadBrand);
        System.out.println("The ipadId is : " + ipad13.ipadId);
        System.out.println("The ipadPrice is : " + ipad13.ipadPrice);
        System.out.println("The isAvailable is : " + ipad13.isAvailable);
        System.out.println("The modelName is : " + ipad13.modelName);
        System.out.println("The storageGB is : " + ipad13.storageGB);
        System.out.println("The weight is : " + ipad13.weight);
        System.out.println("The isWifiOnly is : " + ipad13.isWifiOnly);
        System.out.println("The processor is : " + ipad13.processor);
        System.out.println("The warrantyYears is : " + ipad13.warrantyYears);
        System.out.println("The screenSize is : " + ipad13.screenSize);
        System.out.println("The hasFaceID is : " + ipad13.hasFaceID);
        System.out.println("The color is : " + ipad13.color);
        System.out.println("The stockQuantity is : " + ipad13.stockQuantity);
        System.out.println("The thickness is : " + ipad13.thickness);
        System.out.println("The isEcoFriendly is : " + ipad13.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad13.osVersion);
        System.out.println("The rating is : " + ipad13.rating);
        System.out.println("The batteryCapacity is : " + ipad13.batteryCapacity);
        System.out.println("The isCertified is : " + ipad13.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad13.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad13.cameraMP);
        System.out.println("The supportsPencil is : " + ipad13.supportsPencil);
        System.out.println("The certificationType is : " + ipad13.certificationType);


        Ipad ipad14 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad14.ipadBrand);
        System.out.println("The ipadId is : " + ipad14.ipadId);
        System.out.println("The ipadPrice is : " + ipad14.ipadPrice);
        System.out.println("The isAvailable is : " + ipad14.isAvailable);
        System.out.println("The modelName is : " + ipad14.modelName);
        System.out.println("The storageGB is : " + ipad14.storageGB);
        System.out.println("The weight is : " + ipad14.weight);
        System.out.println("The isWifiOnly is : " + ipad14.isWifiOnly);
        System.out.println("The processor is : " + ipad14.processor);
        System.out.println("The warrantyYears is : " + ipad14.warrantyYears);
        System.out.println("The screenSize is : " + ipad14.screenSize);
        System.out.println("The hasFaceID is : " + ipad14.hasFaceID);
        System.out.println("The color is : " + ipad14.color);
        System.out.println("The stockQuantity is : " + ipad14.stockQuantity);
        System.out.println("The thickness is : " + ipad14.thickness);
        System.out.println("The isEcoFriendly is : " + ipad14.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad14.osVersion);
        System.out.println("The rating is : " + ipad14.rating);
        System.out.println("The batteryCapacity is : " + ipad14.batteryCapacity);
        System.out.println("The isCertified is : " + ipad14.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad14.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad14.cameraMP);
        System.out.println("The supportsPencil is : " + ipad14.supportsPencil);
        System.out.println("The certificationType is : " + ipad14.certificationType);

        ipad14.ipadBrand = "Apple";
        ipad14.ipadId = 14;
        ipad14.ipadPrice = 14000.75;
        ipad14.isAvailable = true;
        ipad14.modelName = "iPad Pro";
        ipad14.storageGB = 128;
        ipad14.weight = 0.47;
        ipad14.isWifiOnly = false;
        ipad14.processor = "M2";
        ipad14.warrantyYears = 1;
        ipad14.screenSize = 11.0;
        ipad14.hasFaceID = true;
        ipad14.color = "Space Gray";
        ipad14.stockQuantity = 25;
        ipad14.thickness = 0.59;
        ipad14.isEcoFriendly = true;
        ipad14.osVersion = "iPadOS";
        ipad14.rating = 5;
        ipad14.batteryCapacity = 7538.0;
        ipad14.isCertified = true;
        ipad14.countryOfOrigin = "China";
        ipad14.manufacturingYear = 2025;
        ipad14.cameraMP = 12.0;
        ipad14.supportsPencil = true;
        ipad14.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad14.ipadBrand);
        System.out.println("The ipadId is : " + ipad14.ipadId);
        System.out.println("The ipadPrice is : " + ipad14.ipadPrice);
        System.out.println("The isAvailable is : " + ipad14.isAvailable);
        System.out.println("The modelName is : " + ipad14.modelName);
        System.out.println("The storageGB is : " + ipad14.storageGB);
        System.out.println("The weight is : " + ipad14.weight);
        System.out.println("The isWifiOnly is : " + ipad14.isWifiOnly);
        System.out.println("The processor is : " + ipad14.processor);
        System.out.println("The warrantyYears is : " + ipad14.warrantyYears);
        System.out.println("The screenSize is : " + ipad14.screenSize);
        System.out.println("The hasFaceID is : " + ipad14.hasFaceID);
        System.out.println("The color is : " + ipad14.color);
        System.out.println("The stockQuantity is : " + ipad14.stockQuantity);
        System.out.println("The thickness is : " + ipad14.thickness);
        System.out.println("The isEcoFriendly is : " + ipad14.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad14.osVersion);
        System.out.println("The rating is : " + ipad14.rating);
        System.out.println("The batteryCapacity is : " + ipad14.batteryCapacity);
        System.out.println("The isCertified is : " + ipad14.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad14.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad14.cameraMP);
        System.out.println("The supportsPencil is : " + ipad14.supportsPencil);
        System.out.println("The certificationType is : " + ipad14.certificationType);


        Ipad ipad15 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad15.ipadBrand);
        System.out.println("The ipadId is : " + ipad15.ipadId);
        System.out.println("The ipadPrice is : " + ipad15.ipadPrice);
        System.out.println("The isAvailable is : " + ipad15.isAvailable);
        System.out.println("The modelName is : " + ipad15.modelName);
        System.out.println("The storageGB is : " + ipad15.storageGB);
        System.out.println("The weight is : " + ipad15.weight);
        System.out.println("The isWifiOnly is : " + ipad15.isWifiOnly);
        System.out.println("The processor is : " + ipad15.processor);
        System.out.println("The warrantyYears is : " + ipad15.warrantyYears);
        System.out.println("The screenSize is : " + ipad15.screenSize);
        System.out.println("The hasFaceID is : " + ipad15.hasFaceID);
        System.out.println("The color is : " + ipad15.color);
        System.out.println("The stockQuantity is : " + ipad15.stockQuantity);
        System.out.println("The thickness is : " + ipad15.thickness);
        System.out.println("The isEcoFriendly is : " + ipad15.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad15.osVersion);
        System.out.println("The rating is : " + ipad15.rating);
        System.out.println("The batteryCapacity is : " + ipad15.batteryCapacity);
        System.out.println("The isCertified is : " + ipad15.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad15.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad15.cameraMP);
        System.out.println("The supportsPencil is : " + ipad15.supportsPencil);
        System.out.println("The certificationType is : " + ipad15.certificationType);

        ipad15.ipadBrand = "Apple";
        ipad15.ipadId = 15;
        ipad15.ipadPrice = 15000.75;
        ipad15.isAvailable = true;
        ipad15.modelName = "iPad Pro";
        ipad15.storageGB = 128;
        ipad15.weight = 0.47;
        ipad15.isWifiOnly = false;
        ipad15.processor = "M2";
        ipad15.warrantyYears = 1;
        ipad15.screenSize = 11.0;
        ipad15.hasFaceID = true;
        ipad15.color = "Space Gray";
        ipad15.stockQuantity = 25;
        ipad15.thickness = 0.59;
        ipad15.isEcoFriendly = true;
        ipad15.osVersion = "iPadOS";
        ipad15.rating = 5;
        ipad15.batteryCapacity = 7538.0;
        ipad15.isCertified = true;
        ipad15.countryOfOrigin = "China";
        ipad15.manufacturingYear = 2025;
        ipad15.cameraMP = 12.0;
        ipad15.supportsPencil = true;
        ipad15.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad15.ipadBrand);
        System.out.println("The ipadId is : " + ipad15.ipadId);
        System.out.println("The ipadPrice is : " + ipad15.ipadPrice);
        System.out.println("The isAvailable is : " + ipad15.isAvailable);
        System.out.println("The modelName is : " + ipad15.modelName);
        System.out.println("The storageGB is : " + ipad15.storageGB);
        System.out.println("The weight is : " + ipad15.weight);
        System.out.println("The isWifiOnly is : " + ipad15.isWifiOnly);
        System.out.println("The processor is : " + ipad15.processor);
        System.out.println("The warrantyYears is : " + ipad15.warrantyYears);
        System.out.println("The screenSize is : " + ipad15.screenSize);
        System.out.println("The hasFaceID is : " + ipad15.hasFaceID);
        System.out.println("The color is : " + ipad15.color);
        System.out.println("The stockQuantity is : " + ipad15.stockQuantity);
        System.out.println("The thickness is : " + ipad15.thickness);
        System.out.println("The isEcoFriendly is : " + ipad15.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad15.osVersion);
        System.out.println("The rating is : " + ipad15.rating);
        System.out.println("The batteryCapacity is : " + ipad15.batteryCapacity);
        System.out.println("The isCertified is : " + ipad15.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad15.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad15.cameraMP);
        System.out.println("The supportsPencil is : " + ipad15.supportsPencil);
        System.out.println("The certificationType is : " + ipad15.certificationType);


        Ipad ipad16 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad16.ipadBrand);
        System.out.println("The ipadId is : " + ipad16.ipadId);
        System.out.println("The ipadPrice is : " + ipad16.ipadPrice);
        System.out.println("The isAvailable is : " + ipad16.isAvailable);
        System.out.println("The modelName is : " + ipad16.modelName);
        System.out.println("The storageGB is : " + ipad16.storageGB);
        System.out.println("The weight is : " + ipad16.weight);
        System.out.println("The isWifiOnly is : " + ipad16.isWifiOnly);
        System.out.println("The processor is : " + ipad16.processor);
        System.out.println("The warrantyYears is : " + ipad16.warrantyYears);
        System.out.println("The screenSize is : " + ipad16.screenSize);
        System.out.println("The hasFaceID is : " + ipad16.hasFaceID);
        System.out.println("The color is : " + ipad16.color);
        System.out.println("The stockQuantity is : " + ipad16.stockQuantity);
        System.out.println("The thickness is : " + ipad16.thickness);
        System.out.println("The isEcoFriendly is : " + ipad16.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad16.osVersion);
        System.out.println("The rating is : " + ipad16.rating);
        System.out.println("The batteryCapacity is : " + ipad16.batteryCapacity);
        System.out.println("The isCertified is : " + ipad16.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad16.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad16.cameraMP);
        System.out.println("The supportsPencil is : " + ipad16.supportsPencil);
        System.out.println("The certificationType is : " + ipad16.certificationType);

        ipad16.ipadBrand = "Apple";
        ipad16.ipadId = 16;
        ipad16.ipadPrice = 16000.75;
        ipad16.isAvailable = true;
        ipad16.modelName = "iPad Pro";
        ipad16.storageGB = 128;
        ipad16.weight = 0.47;
        ipad16.isWifiOnly = false;
        ipad16.processor = "M2";
        ipad16.warrantyYears = 1;
        ipad16.screenSize = 11.0;
        ipad16.hasFaceID = true;
        ipad16.color = "Space Gray";
        ipad16.stockQuantity = 25;
        ipad16.thickness = 0.59;
        ipad16.isEcoFriendly = true;
        ipad16.osVersion = "iPadOS";
        ipad16.rating = 5;
        ipad16.batteryCapacity = 7538.0;
        ipad16.isCertified = true;
        ipad16.countryOfOrigin = "China";
        ipad16.manufacturingYear = 2025;
        ipad16.cameraMP = 12.0;
        ipad16.supportsPencil = true;
        ipad16.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad16.ipadBrand);
        System.out.println("The ipadId is : " + ipad16.ipadId);
        System.out.println("The ipadPrice is : " + ipad16.ipadPrice);
        System.out.println("The isAvailable is : " + ipad16.isAvailable);
        System.out.println("The modelName is : " + ipad16.modelName);
        System.out.println("The storageGB is : " + ipad16.storageGB);
        System.out.println("The weight is : " + ipad16.weight);
        System.out.println("The isWifiOnly is : " + ipad16.isWifiOnly);
        System.out.println("The processor is : " + ipad16.processor);
        System.out.println("The warrantyYears is : " + ipad16.warrantyYears);
        System.out.println("The screenSize is : " + ipad16.screenSize);
        System.out.println("The hasFaceID is : " + ipad16.hasFaceID);
        System.out.println("The color is : " + ipad16.color);
        System.out.println("The stockQuantity is : " + ipad16.stockQuantity);
        System.out.println("The thickness is : " + ipad16.thickness);
        System.out.println("The isEcoFriendly is : " + ipad16.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad16.osVersion);
        System.out.println("The rating is : " + ipad16.rating);
        System.out.println("The batteryCapacity is : " + ipad16.batteryCapacity);
        System.out.println("The isCertified is : " + ipad16.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad16.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad16.cameraMP);
        System.out.println("The supportsPencil is : " + ipad16.supportsPencil);
        System.out.println("The certificationType is : " + ipad16.certificationType);


        Ipad ipad17 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad17.ipadBrand);
        System.out.println("The ipadId is : " + ipad17.ipadId);
        System.out.println("The ipadPrice is : " + ipad17.ipadPrice);
        System.out.println("The isAvailable is : " + ipad17.isAvailable);
        System.out.println("The modelName is : " + ipad17.modelName);
        System.out.println("The storageGB is : " + ipad17.storageGB);
        System.out.println("The weight is : " + ipad17.weight);
        System.out.println("The isWifiOnly is : " + ipad17.isWifiOnly);
        System.out.println("The processor is : " + ipad17.processor);
        System.out.println("The warrantyYears is : " + ipad17.warrantyYears);
        System.out.println("The screenSize is : " + ipad17.screenSize);
        System.out.println("The hasFaceID is : " + ipad17.hasFaceID);
        System.out.println("The color is : " + ipad17.color);
        System.out.println("The stockQuantity is : " + ipad17.stockQuantity);
        System.out.println("The thickness is : " + ipad17.thickness);
        System.out.println("The isEcoFriendly is : " + ipad17.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad17.osVersion);
        System.out.println("The rating is : " + ipad17.rating);
        System.out.println("The batteryCapacity is : " + ipad17.batteryCapacity);
        System.out.println("The isCertified is : " + ipad17.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad17.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad17.cameraMP);
        System.out.println("The supportsPencil is : " + ipad17.supportsPencil);
        System.out.println("The certificationType is : " + ipad17.certificationType);

        ipad17.ipadBrand = "Apple";
        ipad17.ipadId = 17;
        ipad17.ipadPrice = 17000.75;
        ipad17.isAvailable = true;
        ipad17.modelName = "iPad Pro";
        ipad17.storageGB = 128;
        ipad17.weight = 0.47;
        ipad17.isWifiOnly = false;
        ipad17.processor = "M2";
        ipad17.warrantyYears = 1;
        ipad17.screenSize = 11.0;
        ipad17.hasFaceID = true;
        ipad17.color = "Space Gray";
        ipad17.stockQuantity = 25;
        ipad17.thickness = 0.59;
        ipad17.isEcoFriendly = true;
        ipad17.osVersion = "iPadOS";
        ipad17.rating = 5;
        ipad17.batteryCapacity = 7538.0;
        ipad17.isCertified = true;
        ipad17.countryOfOrigin = "China";
        ipad17.manufacturingYear = 2025;
        ipad17.cameraMP = 12.0;
        ipad17.supportsPencil = true;
        ipad17.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad17.ipadBrand);
        System.out.println("The ipadId is : " + ipad17.ipadId);
        System.out.println("The ipadPrice is : " + ipad17.ipadPrice);
        System.out.println("The isAvailable is : " + ipad17.isAvailable);
        System.out.println("The modelName is : " + ipad17.modelName);
        System.out.println("The storageGB is : " + ipad17.storageGB);
        System.out.println("The weight is : " + ipad17.weight);
        System.out.println("The isWifiOnly is : " + ipad17.isWifiOnly);
        System.out.println("The processor is : " + ipad17.processor);
        System.out.println("The warrantyYears is : " + ipad17.warrantyYears);
        System.out.println("The screenSize is : " + ipad17.screenSize);
        System.out.println("The hasFaceID is : " + ipad17.hasFaceID);
        System.out.println("The color is : " + ipad17.color);
        System.out.println("The stockQuantity is : " + ipad17.stockQuantity);
        System.out.println("The thickness is : " + ipad17.thickness);
        System.out.println("The isEcoFriendly is : " + ipad17.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad17.osVersion);
        System.out.println("The rating is : " + ipad17.rating);
        System.out.println("The batteryCapacity is : " + ipad17.batteryCapacity);
        System.out.println("The isCertified is : " + ipad17.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad17.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad17.cameraMP);
        System.out.println("The supportsPencil is : " + ipad17.supportsPencil);
        System.out.println("The certificationType is : " + ipad17.certificationType);


        Ipad ipad18 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad18.ipadBrand);
        System.out.println("The ipadId is : " + ipad18.ipadId);
        System.out.println("The ipadPrice is : " + ipad18.ipadPrice);
        System.out.println("The isAvailable is : " + ipad18.isAvailable);
        System.out.println("The modelName is : " + ipad18.modelName);
        System.out.println("The storageGB is : " + ipad18.storageGB);
        System.out.println("The weight is : " + ipad18.weight);
        System.out.println("The isWifiOnly is : " + ipad18.isWifiOnly);
        System.out.println("The processor is : " + ipad18.processor);
        System.out.println("The warrantyYears is : " + ipad18.warrantyYears);
        System.out.println("The screenSize is : " + ipad18.screenSize);
        System.out.println("The hasFaceID is : " + ipad18.hasFaceID);
        System.out.println("The color is : " + ipad18.color);
        System.out.println("The stockQuantity is : " + ipad18.stockQuantity);
        System.out.println("The thickness is : " + ipad18.thickness);
        System.out.println("The isEcoFriendly is : " + ipad18.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad18.osVersion);
        System.out.println("The rating is : " + ipad18.rating);
        System.out.println("The batteryCapacity is : " + ipad18.batteryCapacity);
        System.out.println("The isCertified is : " + ipad18.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad18.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad18.cameraMP);
        System.out.println("The supportsPencil is : " + ipad18.supportsPencil);
        System.out.println("The certificationType is : " + ipad18.certificationType);

        ipad18.ipadBrand = "Apple";
        ipad18.ipadId = 18;
        ipad18.ipadPrice = 18000.75;
        ipad18.isAvailable = true;
        ipad18.modelName = "iPad Pro";
        ipad18.storageGB = 128;
        ipad18.weight = 0.47;
        ipad18.isWifiOnly = false;
        ipad18.processor = "M2";
        ipad18.warrantyYears = 1;
        ipad18.screenSize = 11.0;
        ipad18.hasFaceID = true;
        ipad18.color = "Space Gray";
        ipad18.stockQuantity = 25;
        ipad18.thickness = 0.59;
        ipad18.isEcoFriendly = true;
        ipad18.osVersion = "iPadOS";
        ipad18.rating = 5;
        ipad18.batteryCapacity = 7538.0;
        ipad18.isCertified = true;
        ipad18.countryOfOrigin = "China";
        ipad18.manufacturingYear = 2025;
        ipad18.cameraMP = 12.0;
        ipad18.supportsPencil = true;
        ipad18.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad18.ipadBrand);
        System.out.println("The ipadId is : " + ipad18.ipadId);
        System.out.println("The ipadPrice is : " + ipad18.ipadPrice);
        System.out.println("The isAvailable is : " + ipad18.isAvailable);
        System.out.println("The modelName is : " + ipad18.modelName);
        System.out.println("The storageGB is : " + ipad18.storageGB);
        System.out.println("The weight is : " + ipad18.weight);
        System.out.println("The isWifiOnly is : " + ipad18.isWifiOnly);
        System.out.println("The processor is : " + ipad18.processor);
        System.out.println("The warrantyYears is : " + ipad18.warrantyYears);
        System.out.println("The screenSize is : " + ipad18.screenSize);
        System.out.println("The hasFaceID is : " + ipad18.hasFaceID);
        System.out.println("The color is : " + ipad18.color);
        System.out.println("The stockQuantity is : " + ipad18.stockQuantity);
        System.out.println("The thickness is : " + ipad18.thickness);
        System.out.println("The isEcoFriendly is : " + ipad18.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad18.osVersion);
        System.out.println("The rating is : " + ipad18.rating);
        System.out.println("The batteryCapacity is : " + ipad18.batteryCapacity);
        System.out.println("The isCertified is : " + ipad18.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad18.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad18.cameraMP);
        System.out.println("The supportsPencil is : " + ipad18.supportsPencil);
        System.out.println("The certificationType is : " + ipad18.certificationType);


        Ipad ipad19 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad19.ipadBrand);
        System.out.println("The ipadId is : " + ipad19.ipadId);
        System.out.println("The ipadPrice is : " + ipad19.ipadPrice);
        System.out.println("The isAvailable is : " + ipad19.isAvailable);
        System.out.println("The modelName is : " + ipad19.modelName);
        System.out.println("The storageGB is : " + ipad19.storageGB);
        System.out.println("The weight is : " + ipad19.weight);
        System.out.println("The isWifiOnly is : " + ipad19.isWifiOnly);
        System.out.println("The processor is : " + ipad19.processor);
        System.out.println("The warrantyYears is : " + ipad19.warrantyYears);
        System.out.println("The screenSize is : " + ipad19.screenSize);
        System.out.println("The hasFaceID is : " + ipad19.hasFaceID);
        System.out.println("The color is : " + ipad19.color);
        System.out.println("The stockQuantity is : " + ipad19.stockQuantity);
        System.out.println("The thickness is : " + ipad19.thickness);
        System.out.println("The isEcoFriendly is : " + ipad19.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad19.osVersion);
        System.out.println("The rating is : " + ipad19.rating);
        System.out.println("The batteryCapacity is : " + ipad19.batteryCapacity);
        System.out.println("The isCertified is : " + ipad19.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad19.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad19.cameraMP);
        System.out.println("The supportsPencil is : " + ipad19.supportsPencil);
        System.out.println("The certificationType is : " + ipad19.certificationType);

        ipad19.ipadBrand = "Apple";
        ipad19.ipadId = 19;
        ipad19.ipadPrice = 19000.75;
        ipad19.isAvailable = true;
        ipad19.modelName = "iPad Pro";
        ipad19.storageGB = 128;
        ipad19.weight = 0.47;
        ipad19.isWifiOnly = false;
        ipad19.processor = "M2";
        ipad19.warrantyYears = 1;
        ipad19.screenSize = 11.0;
        ipad19.hasFaceID = true;
        ipad19.color = "Space Gray";
        ipad19.stockQuantity = 25;
        ipad19.thickness = 0.59;
        ipad19.isEcoFriendly = true;
        ipad19.osVersion = "iPadOS";
        ipad19.rating = 5;
        ipad19.batteryCapacity = 7538.0;
        ipad19.isCertified = true;
        ipad19.countryOfOrigin = "China";
        ipad19.manufacturingYear = 2025;
        ipad19.cameraMP = 12.0;
        ipad19.supportsPencil = true;
        ipad19.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad19.ipadBrand);
        System.out.println("The ipadId is : " + ipad19.ipadId);
        System.out.println("The ipadPrice is : " + ipad19.ipadPrice);
        System.out.println("The isAvailable is : " + ipad19.isAvailable);
        System.out.println("The modelName is : " + ipad19.modelName);
        System.out.println("The storageGB is : " + ipad19.storageGB);
        System.out.println("The weight is : " + ipad19.weight);
        System.out.println("The isWifiOnly is : " + ipad19.isWifiOnly);
        System.out.println("The processor is : " + ipad19.processor);
        System.out.println("The warrantyYears is : " + ipad19.warrantyYears);
        System.out.println("The screenSize is : " + ipad19.screenSize);
        System.out.println("The hasFaceID is : " + ipad19.hasFaceID);
        System.out.println("The color is : " + ipad19.color);
        System.out.println("The stockQuantity is : " + ipad19.stockQuantity);
        System.out.println("The thickness is : " + ipad19.thickness);
        System.out.println("The isEcoFriendly is : " + ipad19.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad19.osVersion);
        System.out.println("The rating is : " + ipad19.rating);
        System.out.println("The batteryCapacity is : " + ipad19.batteryCapacity);
        System.out.println("The isCertified is : " + ipad19.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad19.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad19.cameraMP);
        System.out.println("The supportsPencil is : " + ipad19.supportsPencil);
        System.out.println("The certificationType is : " + ipad19.certificationType);


        Ipad ipad20 = new Ipad();

        System.out.println("Before initialization");

        System.out.println("The ipadBrand is : " + ipad20.ipadBrand);
        System.out.println("The ipadId is : " + ipad20.ipadId);
        System.out.println("The ipadPrice is : " + ipad20.ipadPrice);
        System.out.println("The isAvailable is : " + ipad20.isAvailable);
        System.out.println("The modelName is : " + ipad20.modelName);
        System.out.println("The storageGB is : " + ipad20.storageGB);
        System.out.println("The weight is : " + ipad20.weight);
        System.out.println("The isWifiOnly is : " + ipad20.isWifiOnly);
        System.out.println("The processor is : " + ipad20.processor);
        System.out.println("The warrantyYears is : " + ipad20.warrantyYears);
        System.out.println("The screenSize is : " + ipad20.screenSize);
        System.out.println("The hasFaceID is : " + ipad20.hasFaceID);
        System.out.println("The color is : " + ipad20.color);
        System.out.println("The stockQuantity is : " + ipad20.stockQuantity);
        System.out.println("The thickness is : " + ipad20.thickness);
        System.out.println("The isEcoFriendly is : " + ipad20.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad20.osVersion);
        System.out.println("The rating is : " + ipad20.rating);
        System.out.println("The batteryCapacity is : " + ipad20.batteryCapacity);
        System.out.println("The isCertified is : " + ipad20.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad20.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad20.cameraMP);
        System.out.println("The supportsPencil is : " + ipad20.supportsPencil);
        System.out.println("The certificationType is : " + ipad20.certificationType);

        ipad20.ipadBrand = "Apple";
        ipad20.ipadId = 20;
        ipad20.ipadPrice = 20000.75;
        ipad20.isAvailable = true;
        ipad20.modelName = "iPad Pro";
        ipad20.storageGB = 128;
        ipad20.weight = 0.47;
        ipad20.isWifiOnly = false;
        ipad20.processor = "M2";
        ipad20.warrantyYears = 1;
        ipad20.screenSize = 11.0;
        ipad20.hasFaceID = true;
        ipad20.color = "Space Gray";
        ipad20.stockQuantity = 25;
        ipad20.thickness = 0.59;
        ipad20.isEcoFriendly = true;
        ipad20.osVersion = "iPadOS";
        ipad20.rating = 5;
        ipad20.batteryCapacity = 7538.0;
        ipad20.isCertified = true;
        ipad20.countryOfOrigin = "China";
        ipad20.manufacturingYear = 2025;
        ipad20.cameraMP = 12.0;
        ipad20.supportsPencil = true;
        ipad20.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The ipadBrand is : " + ipad20.ipadBrand);
        System.out.println("The ipadId is : " + ipad20.ipadId);
        System.out.println("The ipadPrice is : " + ipad20.ipadPrice);
        System.out.println("The isAvailable is : " + ipad20.isAvailable);
        System.out.println("The modelName is : " + ipad20.modelName);
        System.out.println("The storageGB is : " + ipad20.storageGB);
        System.out.println("The weight is : " + ipad20.weight);
        System.out.println("The isWifiOnly is : " + ipad20.isWifiOnly);
        System.out.println("The processor is : " + ipad20.processor);
        System.out.println("The warrantyYears is : " + ipad20.warrantyYears);
        System.out.println("The screenSize is : " + ipad20.screenSize);
        System.out.println("The hasFaceID is : " + ipad20.hasFaceID);
        System.out.println("The color is : " + ipad20.color);
        System.out.println("The stockQuantity is : " + ipad20.stockQuantity);
        System.out.println("The thickness is : " + ipad20.thickness);
        System.out.println("The isEcoFriendly is : " + ipad20.isEcoFriendly);
        System.out.println("The osVersion is : " + ipad20.osVersion);
        System.out.println("The rating is : " + ipad20.rating);
        System.out.println("The batteryCapacity is : " + ipad20.batteryCapacity);
        System.out.println("The isCertified is : " + ipad20.isCertified);
        System.out.println("The countryOfOrigin is : " + ipad20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ipad20.manufacturingYear);
        System.out.println("The cameraMP is : " + ipad20.cameraMP);
        System.out.println("The supportsPencil is : " + ipad20.supportsPencil);
        System.out.println("The certificationType is : " + ipad20.certificationType);


    }
}
