class MultimeterExecutor {

    public static void main(String[] args) {

        Multimeter meter1 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter1.meterBrand);
        System.out.println("The meterId is : " + meter1.meterId);
        System.out.println("The meterPrice is : " + meter1.meterPrice);
        System.out.println("The isAvailable is : " + meter1.isAvailable);
        System.out.println("The meterType is : " + meter1.meterType);
        System.out.println("The maxVoltage is : " + meter1.maxVoltage);
        System.out.println("The weight is : " + meter1.weight);
        System.out.println("The isPortable is : " + meter1.isPortable);
        System.out.println("The displayType is : " + meter1.displayType);
        System.out.println("The warrantyYears is : " + meter1.warrantyYears);
        System.out.println("The maxCurrent is : " + meter1.maxCurrent);
        System.out.println("The hasBacklight is : " + meter1.hasBacklight);
        System.out.println("The color is : " + meter1.color);
        System.out.println("The stockQuantity is : " + meter1.stockQuantity);
        System.out.println("The accuracy is : " + meter1.accuracy);
        System.out.println("The isEcoFriendly is : " + meter1.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter1.measurementMode);
        System.out.println("The rating is : " + meter1.rating);
        System.out.println("The batteryVoltage is : " + meter1.batteryVoltage);
        System.out.println("The isCertified is : " + meter1.isCertified);
        System.out.println("The countryOfOrigin is : " + meter1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter1.manufacturingYear);
        System.out.println("The probeLength is : " + meter1.probeLength);
        System.out.println("The supportsTemperature is : " + meter1.supportsTemperature);
        System.out.println("The certificationType is : " + meter1.certificationType);

        meter1.meterBrand = "Fluke";
        meter1.meterId = 1;
        meter1.meterPrice = 150.25;
        meter1.isAvailable = true;
        meter1.meterType = "Digital";
        meter1.maxVoltage = 1000.0;
        meter1.weight = 0.45;
        meter1.isPortable = true;
        meter1.displayType = "LCD";
        meter1.warrantyYears = 3;
        meter1.maxCurrent = 10.0;
        meter1.hasBacklight = true;
        meter1.color = "Yellow";
        meter1.stockQuantity = 18;
        meter1.accuracy = 0.5;
        meter1.isEcoFriendly = true;
        meter1.measurementMode = "Auto Range";
        meter1.rating = 5;
        meter1.batteryVoltage = 9.0;
        meter1.isCertified = true;
        meter1.countryOfOrigin = "USA";
        meter1.manufacturingYear = 2025;
        meter1.probeLength = 1.2;
        meter1.supportsTemperature = true;
        meter1.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter1.meterBrand);
        System.out.println("The meterId is : " + meter1.meterId);
        System.out.println("The meterPrice is : " + meter1.meterPrice);
        System.out.println("The isAvailable is : " + meter1.isAvailable);
        System.out.println("The meterType is : " + meter1.meterType);
        System.out.println("The maxVoltage is : " + meter1.maxVoltage);
        System.out.println("The weight is : " + meter1.weight);
        System.out.println("The isPortable is : " + meter1.isPortable);
        System.out.println("The displayType is : " + meter1.displayType);
        System.out.println("The warrantyYears is : " + meter1.warrantyYears);
        System.out.println("The maxCurrent is : " + meter1.maxCurrent);
        System.out.println("The hasBacklight is : " + meter1.hasBacklight);
        System.out.println("The color is : " + meter1.color);
        System.out.println("The stockQuantity is : " + meter1.stockQuantity);
        System.out.println("The accuracy is : " + meter1.accuracy);
        System.out.println("The isEcoFriendly is : " + meter1.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter1.measurementMode);
        System.out.println("The rating is : " + meter1.rating);
        System.out.println("The batteryVoltage is : " + meter1.batteryVoltage);
        System.out.println("The isCertified is : " + meter1.isCertified);
        System.out.println("The countryOfOrigin is : " + meter1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter1.manufacturingYear);
        System.out.println("The probeLength is : " + meter1.probeLength);
        System.out.println("The supportsTemperature is : " + meter1.supportsTemperature);
        System.out.println("The certificationType is : " + meter1.certificationType);


        Multimeter meter2 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter2.meterBrand);
        System.out.println("The meterId is : " + meter2.meterId);
        System.out.println("The meterPrice is : " + meter2.meterPrice);
        System.out.println("The isAvailable is : " + meter2.isAvailable);
        System.out.println("The meterType is : " + meter2.meterType);
        System.out.println("The maxVoltage is : " + meter2.maxVoltage);
        System.out.println("The weight is : " + meter2.weight);
        System.out.println("The isPortable is : " + meter2.isPortable);
        System.out.println("The displayType is : " + meter2.displayType);
        System.out.println("The warrantyYears is : " + meter2.warrantyYears);
        System.out.println("The maxCurrent is : " + meter2.maxCurrent);
        System.out.println("The hasBacklight is : " + meter2.hasBacklight);
        System.out.println("The color is : " + meter2.color);
        System.out.println("The stockQuantity is : " + meter2.stockQuantity);
        System.out.println("The accuracy is : " + meter2.accuracy);
        System.out.println("The isEcoFriendly is : " + meter2.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter2.measurementMode);
        System.out.println("The rating is : " + meter2.rating);
        System.out.println("The batteryVoltage is : " + meter2.batteryVoltage);
        System.out.println("The isCertified is : " + meter2.isCertified);
        System.out.println("The countryOfOrigin is : " + meter2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter2.manufacturingYear);
        System.out.println("The probeLength is : " + meter2.probeLength);
        System.out.println("The supportsTemperature is : " + meter2.supportsTemperature);
        System.out.println("The certificationType is : " + meter2.certificationType);

        meter2.meterBrand = "Fluke";
        meter2.meterId = 2;
        meter2.meterPrice = 250.25;
        meter2.isAvailable = true;
        meter2.meterType = "Digital";
        meter2.maxVoltage = 1000.0;
        meter2.weight = 0.45;
        meter2.isPortable = true;
        meter2.displayType = "LCD";
        meter2.warrantyYears = 3;
        meter2.maxCurrent = 10.0;
        meter2.hasBacklight = true;
        meter2.color = "Yellow";
        meter2.stockQuantity = 18;
        meter2.accuracy = 0.5;
        meter2.isEcoFriendly = true;
        meter2.measurementMode = "Auto Range";
        meter2.rating = 5;
        meter2.batteryVoltage = 9.0;
        meter2.isCertified = true;
        meter2.countryOfOrigin = "USA";
        meter2.manufacturingYear = 2025;
        meter2.probeLength = 1.2;
        meter2.supportsTemperature = true;
        meter2.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter2.meterBrand);
        System.out.println("The meterId is : " + meter2.meterId);
        System.out.println("The meterPrice is : " + meter2.meterPrice);
        System.out.println("The isAvailable is : " + meter2.isAvailable);
        System.out.println("The meterType is : " + meter2.meterType);
        System.out.println("The maxVoltage is : " + meter2.maxVoltage);
        System.out.println("The weight is : " + meter2.weight);
        System.out.println("The isPortable is : " + meter2.isPortable);
        System.out.println("The displayType is : " + meter2.displayType);
        System.out.println("The warrantyYears is : " + meter2.warrantyYears);
        System.out.println("The maxCurrent is : " + meter2.maxCurrent);
        System.out.println("The hasBacklight is : " + meter2.hasBacklight);
        System.out.println("The color is : " + meter2.color);
        System.out.println("The stockQuantity is : " + meter2.stockQuantity);
        System.out.println("The accuracy is : " + meter2.accuracy);
        System.out.println("The isEcoFriendly is : " + meter2.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter2.measurementMode);
        System.out.println("The rating is : " + meter2.rating);
        System.out.println("The batteryVoltage is : " + meter2.batteryVoltage);
        System.out.println("The isCertified is : " + meter2.isCertified);
        System.out.println("The countryOfOrigin is : " + meter2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter2.manufacturingYear);
        System.out.println("The probeLength is : " + meter2.probeLength);
        System.out.println("The supportsTemperature is : " + meter2.supportsTemperature);
        System.out.println("The certificationType is : " + meter2.certificationType);


        Multimeter meter3 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter3.meterBrand);
        System.out.println("The meterId is : " + meter3.meterId);
        System.out.println("The meterPrice is : " + meter3.meterPrice);
        System.out.println("The isAvailable is : " + meter3.isAvailable);
        System.out.println("The meterType is : " + meter3.meterType);
        System.out.println("The maxVoltage is : " + meter3.maxVoltage);
        System.out.println("The weight is : " + meter3.weight);
        System.out.println("The isPortable is : " + meter3.isPortable);
        System.out.println("The displayType is : " + meter3.displayType);
        System.out.println("The warrantyYears is : " + meter3.warrantyYears);
        System.out.println("The maxCurrent is : " + meter3.maxCurrent);
        System.out.println("The hasBacklight is : " + meter3.hasBacklight);
        System.out.println("The color is : " + meter3.color);
        System.out.println("The stockQuantity is : " + meter3.stockQuantity);
        System.out.println("The accuracy is : " + meter3.accuracy);
        System.out.println("The isEcoFriendly is : " + meter3.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter3.measurementMode);
        System.out.println("The rating is : " + meter3.rating);
        System.out.println("The batteryVoltage is : " + meter3.batteryVoltage);
        System.out.println("The isCertified is : " + meter3.isCertified);
        System.out.println("The countryOfOrigin is : " + meter3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter3.manufacturingYear);
        System.out.println("The probeLength is : " + meter3.probeLength);
        System.out.println("The supportsTemperature is : " + meter3.supportsTemperature);
        System.out.println("The certificationType is : " + meter3.certificationType);

        meter3.meterBrand = "Fluke";
        meter3.meterId = 3;
        meter3.meterPrice = 350.25;
        meter3.isAvailable = true;
        meter3.meterType = "Digital";
        meter3.maxVoltage = 1000.0;
        meter3.weight = 0.45;
        meter3.isPortable = true;
        meter3.displayType = "LCD";
        meter3.warrantyYears = 3;
        meter3.maxCurrent = 10.0;
        meter3.hasBacklight = true;
        meter3.color = "Yellow";
        meter3.stockQuantity = 18;
        meter3.accuracy = 0.5;
        meter3.isEcoFriendly = true;
        meter3.measurementMode = "Auto Range";
        meter3.rating = 5;
        meter3.batteryVoltage = 9.0;
        meter3.isCertified = true;
        meter3.countryOfOrigin = "USA";
        meter3.manufacturingYear = 2025;
        meter3.probeLength = 1.2;
        meter3.supportsTemperature = true;
        meter3.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter3.meterBrand);
        System.out.println("The meterId is : " + meter3.meterId);
        System.out.println("The meterPrice is : " + meter3.meterPrice);
        System.out.println("The isAvailable is : " + meter3.isAvailable);
        System.out.println("The meterType is : " + meter3.meterType);
        System.out.println("The maxVoltage is : " + meter3.maxVoltage);
        System.out.println("The weight is : " + meter3.weight);
        System.out.println("The isPortable is : " + meter3.isPortable);
        System.out.println("The displayType is : " + meter3.displayType);
        System.out.println("The warrantyYears is : " + meter3.warrantyYears);
        System.out.println("The maxCurrent is : " + meter3.maxCurrent);
        System.out.println("The hasBacklight is : " + meter3.hasBacklight);
        System.out.println("The color is : " + meter3.color);
        System.out.println("The stockQuantity is : " + meter3.stockQuantity);
        System.out.println("The accuracy is : " + meter3.accuracy);
        System.out.println("The isEcoFriendly is : " + meter3.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter3.measurementMode);
        System.out.println("The rating is : " + meter3.rating);
        System.out.println("The batteryVoltage is : " + meter3.batteryVoltage);
        System.out.println("The isCertified is : " + meter3.isCertified);
        System.out.println("The countryOfOrigin is : " + meter3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter3.manufacturingYear);
        System.out.println("The probeLength is : " + meter3.probeLength);
        System.out.println("The supportsTemperature is : " + meter3.supportsTemperature);
        System.out.println("The certificationType is : " + meter3.certificationType);


        Multimeter meter4 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter4.meterBrand);
        System.out.println("The meterId is : " + meter4.meterId);
        System.out.println("The meterPrice is : " + meter4.meterPrice);
        System.out.println("The isAvailable is : " + meter4.isAvailable);
        System.out.println("The meterType is : " + meter4.meterType);
        System.out.println("The maxVoltage is : " + meter4.maxVoltage);
        System.out.println("The weight is : " + meter4.weight);
        System.out.println("The isPortable is : " + meter4.isPortable);
        System.out.println("The displayType is : " + meter4.displayType);
        System.out.println("The warrantyYears is : " + meter4.warrantyYears);
        System.out.println("The maxCurrent is : " + meter4.maxCurrent);
        System.out.println("The hasBacklight is : " + meter4.hasBacklight);
        System.out.println("The color is : " + meter4.color);
        System.out.println("The stockQuantity is : " + meter4.stockQuantity);
        System.out.println("The accuracy is : " + meter4.accuracy);
        System.out.println("The isEcoFriendly is : " + meter4.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter4.measurementMode);
        System.out.println("The rating is : " + meter4.rating);
        System.out.println("The batteryVoltage is : " + meter4.batteryVoltage);
        System.out.println("The isCertified is : " + meter4.isCertified);
        System.out.println("The countryOfOrigin is : " + meter4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter4.manufacturingYear);
        System.out.println("The probeLength is : " + meter4.probeLength);
        System.out.println("The supportsTemperature is : " + meter4.supportsTemperature);
        System.out.println("The certificationType is : " + meter4.certificationType);

        meter4.meterBrand = "Fluke";
        meter4.meterId = 4;
        meter4.meterPrice = 450.25;
        meter4.isAvailable = true;
        meter4.meterType = "Digital";
        meter4.maxVoltage = 1000.0;
        meter4.weight = 0.45;
        meter4.isPortable = true;
        meter4.displayType = "LCD";
        meter4.warrantyYears = 3;
        meter4.maxCurrent = 10.0;
        meter4.hasBacklight = true;
        meter4.color = "Yellow";
        meter4.stockQuantity = 18;
        meter4.accuracy = 0.5;
        meter4.isEcoFriendly = true;
        meter4.measurementMode = "Auto Range";
        meter4.rating = 5;
        meter4.batteryVoltage = 9.0;
        meter4.isCertified = true;
        meter4.countryOfOrigin = "USA";
        meter4.manufacturingYear = 2025;
        meter4.probeLength = 1.2;
        meter4.supportsTemperature = true;
        meter4.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter4.meterBrand);
        System.out.println("The meterId is : " + meter4.meterId);
        System.out.println("The meterPrice is : " + meter4.meterPrice);
        System.out.println("The isAvailable is : " + meter4.isAvailable);
        System.out.println("The meterType is : " + meter4.meterType);
        System.out.println("The maxVoltage is : " + meter4.maxVoltage);
        System.out.println("The weight is : " + meter4.weight);
        System.out.println("The isPortable is : " + meter4.isPortable);
        System.out.println("The displayType is : " + meter4.displayType);
        System.out.println("The warrantyYears is : " + meter4.warrantyYears);
        System.out.println("The maxCurrent is : " + meter4.maxCurrent);
        System.out.println("The hasBacklight is : " + meter4.hasBacklight);
        System.out.println("The color is : " + meter4.color);
        System.out.println("The stockQuantity is : " + meter4.stockQuantity);
        System.out.println("The accuracy is : " + meter4.accuracy);
        System.out.println("The isEcoFriendly is : " + meter4.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter4.measurementMode);
        System.out.println("The rating is : " + meter4.rating);
        System.out.println("The batteryVoltage is : " + meter4.batteryVoltage);
        System.out.println("The isCertified is : " + meter4.isCertified);
        System.out.println("The countryOfOrigin is : " + meter4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter4.manufacturingYear);
        System.out.println("The probeLength is : " + meter4.probeLength);
        System.out.println("The supportsTemperature is : " + meter4.supportsTemperature);
        System.out.println("The certificationType is : " + meter4.certificationType);


        Multimeter meter5 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter5.meterBrand);
        System.out.println("The meterId is : " + meter5.meterId);
        System.out.println("The meterPrice is : " + meter5.meterPrice);
        System.out.println("The isAvailable is : " + meter5.isAvailable);
        System.out.println("The meterType is : " + meter5.meterType);
        System.out.println("The maxVoltage is : " + meter5.maxVoltage);
        System.out.println("The weight is : " + meter5.weight);
        System.out.println("The isPortable is : " + meter5.isPortable);
        System.out.println("The displayType is : " + meter5.displayType);
        System.out.println("The warrantyYears is : " + meter5.warrantyYears);
        System.out.println("The maxCurrent is : " + meter5.maxCurrent);
        System.out.println("The hasBacklight is : " + meter5.hasBacklight);
        System.out.println("The color is : " + meter5.color);
        System.out.println("The stockQuantity is : " + meter5.stockQuantity);
        System.out.println("The accuracy is : " + meter5.accuracy);
        System.out.println("The isEcoFriendly is : " + meter5.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter5.measurementMode);
        System.out.println("The rating is : " + meter5.rating);
        System.out.println("The batteryVoltage is : " + meter5.batteryVoltage);
        System.out.println("The isCertified is : " + meter5.isCertified);
        System.out.println("The countryOfOrigin is : " + meter5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter5.manufacturingYear);
        System.out.println("The probeLength is : " + meter5.probeLength);
        System.out.println("The supportsTemperature is : " + meter5.supportsTemperature);
        System.out.println("The certificationType is : " + meter5.certificationType);

        meter5.meterBrand = "Fluke";
        meter5.meterId = 5;
        meter5.meterPrice = 550.25;
        meter5.isAvailable = true;
        meter5.meterType = "Digital";
        meter5.maxVoltage = 1000.0;
        meter5.weight = 0.45;
        meter5.isPortable = true;
        meter5.displayType = "LCD";
        meter5.warrantyYears = 3;
        meter5.maxCurrent = 10.0;
        meter5.hasBacklight = true;
        meter5.color = "Yellow";
        meter5.stockQuantity = 18;
        meter5.accuracy = 0.5;
        meter5.isEcoFriendly = true;
        meter5.measurementMode = "Auto Range";
        meter5.rating = 5;
        meter5.batteryVoltage = 9.0;
        meter5.isCertified = true;
        meter5.countryOfOrigin = "USA";
        meter5.manufacturingYear = 2025;
        meter5.probeLength = 1.2;
        meter5.supportsTemperature = true;
        meter5.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter5.meterBrand);
        System.out.println("The meterId is : " + meter5.meterId);
        System.out.println("The meterPrice is : " + meter5.meterPrice);
        System.out.println("The isAvailable is : " + meter5.isAvailable);
        System.out.println("The meterType is : " + meter5.meterType);
        System.out.println("The maxVoltage is : " + meter5.maxVoltage);
        System.out.println("The weight is : " + meter5.weight);
        System.out.println("The isPortable is : " + meter5.isPortable);
        System.out.println("The displayType is : " + meter5.displayType);
        System.out.println("The warrantyYears is : " + meter5.warrantyYears);
        System.out.println("The maxCurrent is : " + meter5.maxCurrent);
        System.out.println("The hasBacklight is : " + meter5.hasBacklight);
        System.out.println("The color is : " + meter5.color);
        System.out.println("The stockQuantity is : " + meter5.stockQuantity);
        System.out.println("The accuracy is : " + meter5.accuracy);
        System.out.println("The isEcoFriendly is : " + meter5.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter5.measurementMode);
        System.out.println("The rating is : " + meter5.rating);
        System.out.println("The batteryVoltage is : " + meter5.batteryVoltage);
        System.out.println("The isCertified is : " + meter5.isCertified);
        System.out.println("The countryOfOrigin is : " + meter5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter5.manufacturingYear);
        System.out.println("The probeLength is : " + meter5.probeLength);
        System.out.println("The supportsTemperature is : " + meter5.supportsTemperature);
        System.out.println("The certificationType is : " + meter5.certificationType);


        Multimeter meter6 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter6.meterBrand);
        System.out.println("The meterId is : " + meter6.meterId);
        System.out.println("The meterPrice is : " + meter6.meterPrice);
        System.out.println("The isAvailable is : " + meter6.isAvailable);
        System.out.println("The meterType is : " + meter6.meterType);
        System.out.println("The maxVoltage is : " + meter6.maxVoltage);
        System.out.println("The weight is : " + meter6.weight);
        System.out.println("The isPortable is : " + meter6.isPortable);
        System.out.println("The displayType is : " + meter6.displayType);
        System.out.println("The warrantyYears is : " + meter6.warrantyYears);
        System.out.println("The maxCurrent is : " + meter6.maxCurrent);
        System.out.println("The hasBacklight is : " + meter6.hasBacklight);
        System.out.println("The color is : " + meter6.color);
        System.out.println("The stockQuantity is : " + meter6.stockQuantity);
        System.out.println("The accuracy is : " + meter6.accuracy);
        System.out.println("The isEcoFriendly is : " + meter6.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter6.measurementMode);
        System.out.println("The rating is : " + meter6.rating);
        System.out.println("The batteryVoltage is : " + meter6.batteryVoltage);
        System.out.println("The isCertified is : " + meter6.isCertified);
        System.out.println("The countryOfOrigin is : " + meter6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter6.manufacturingYear);
        System.out.println("The probeLength is : " + meter6.probeLength);
        System.out.println("The supportsTemperature is : " + meter6.supportsTemperature);
        System.out.println("The certificationType is : " + meter6.certificationType);

        meter6.meterBrand = "Fluke";
        meter6.meterId = 6;
        meter6.meterPrice = 650.25;
        meter6.isAvailable = true;
        meter6.meterType = "Digital";
        meter6.maxVoltage = 1000.0;
        meter6.weight = 0.45;
        meter6.isPortable = true;
        meter6.displayType = "LCD";
        meter6.warrantyYears = 3;
        meter6.maxCurrent = 10.0;
        meter6.hasBacklight = true;
        meter6.color = "Yellow";
        meter6.stockQuantity = 18;
        meter6.accuracy = 0.5;
        meter6.isEcoFriendly = true;
        meter6.measurementMode = "Auto Range";
        meter6.rating = 5;
        meter6.batteryVoltage = 9.0;
        meter6.isCertified = true;
        meter6.countryOfOrigin = "USA";
        meter6.manufacturingYear = 2025;
        meter6.probeLength = 1.2;
        meter6.supportsTemperature = true;
        meter6.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter6.meterBrand);
        System.out.println("The meterId is : " + meter6.meterId);
        System.out.println("The meterPrice is : " + meter6.meterPrice);
        System.out.println("The isAvailable is : " + meter6.isAvailable);
        System.out.println("The meterType is : " + meter6.meterType);
        System.out.println("The maxVoltage is : " + meter6.maxVoltage);
        System.out.println("The weight is : " + meter6.weight);
        System.out.println("The isPortable is : " + meter6.isPortable);
        System.out.println("The displayType is : " + meter6.displayType);
        System.out.println("The warrantyYears is : " + meter6.warrantyYears);
        System.out.println("The maxCurrent is : " + meter6.maxCurrent);
        System.out.println("The hasBacklight is : " + meter6.hasBacklight);
        System.out.println("The color is : " + meter6.color);
        System.out.println("The stockQuantity is : " + meter6.stockQuantity);
        System.out.println("The accuracy is : " + meter6.accuracy);
        System.out.println("The isEcoFriendly is : " + meter6.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter6.measurementMode);
        System.out.println("The rating is : " + meter6.rating);
        System.out.println("The batteryVoltage is : " + meter6.batteryVoltage);
        System.out.println("The isCertified is : " + meter6.isCertified);
        System.out.println("The countryOfOrigin is : " + meter6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter6.manufacturingYear);
        System.out.println("The probeLength is : " + meter6.probeLength);
        System.out.println("The supportsTemperature is : " + meter6.supportsTemperature);
        System.out.println("The certificationType is : " + meter6.certificationType);


        Multimeter meter7 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter7.meterBrand);
        System.out.println("The meterId is : " + meter7.meterId);
        System.out.println("The meterPrice is : " + meter7.meterPrice);
        System.out.println("The isAvailable is : " + meter7.isAvailable);
        System.out.println("The meterType is : " + meter7.meterType);
        System.out.println("The maxVoltage is : " + meter7.maxVoltage);
        System.out.println("The weight is : " + meter7.weight);
        System.out.println("The isPortable is : " + meter7.isPortable);
        System.out.println("The displayType is : " + meter7.displayType);
        System.out.println("The warrantyYears is : " + meter7.warrantyYears);
        System.out.println("The maxCurrent is : " + meter7.maxCurrent);
        System.out.println("The hasBacklight is : " + meter7.hasBacklight);
        System.out.println("The color is : " + meter7.color);
        System.out.println("The stockQuantity is : " + meter7.stockQuantity);
        System.out.println("The accuracy is : " + meter7.accuracy);
        System.out.println("The isEcoFriendly is : " + meter7.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter7.measurementMode);
        System.out.println("The rating is : " + meter7.rating);
        System.out.println("The batteryVoltage is : " + meter7.batteryVoltage);
        System.out.println("The isCertified is : " + meter7.isCertified);
        System.out.println("The countryOfOrigin is : " + meter7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter7.manufacturingYear);
        System.out.println("The probeLength is : " + meter7.probeLength);
        System.out.println("The supportsTemperature is : " + meter7.supportsTemperature);
        System.out.println("The certificationType is : " + meter7.certificationType);

        meter7.meterBrand = "Fluke";
        meter7.meterId = 7;
        meter7.meterPrice = 750.25;
        meter7.isAvailable = true;
        meter7.meterType = "Digital";
        meter7.maxVoltage = 1000.0;
        meter7.weight = 0.45;
        meter7.isPortable = true;
        meter7.displayType = "LCD";
        meter7.warrantyYears = 3;
        meter7.maxCurrent = 10.0;
        meter7.hasBacklight = true;
        meter7.color = "Yellow";
        meter7.stockQuantity = 18;
        meter7.accuracy = 0.5;
        meter7.isEcoFriendly = true;
        meter7.measurementMode = "Auto Range";
        meter7.rating = 5;
        meter7.batteryVoltage = 9.0;
        meter7.isCertified = true;
        meter7.countryOfOrigin = "USA";
        meter7.manufacturingYear = 2025;
        meter7.probeLength = 1.2;
        meter7.supportsTemperature = true;
        meter7.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter7.meterBrand);
        System.out.println("The meterId is : " + meter7.meterId);
        System.out.println("The meterPrice is : " + meter7.meterPrice);
        System.out.println("The isAvailable is : " + meter7.isAvailable);
        System.out.println("The meterType is : " + meter7.meterType);
        System.out.println("The maxVoltage is : " + meter7.maxVoltage);
        System.out.println("The weight is : " + meter7.weight);
        System.out.println("The isPortable is : " + meter7.isPortable);
        System.out.println("The displayType is : " + meter7.displayType);
        System.out.println("The warrantyYears is : " + meter7.warrantyYears);
        System.out.println("The maxCurrent is : " + meter7.maxCurrent);
        System.out.println("The hasBacklight is : " + meter7.hasBacklight);
        System.out.println("The color is : " + meter7.color);
        System.out.println("The stockQuantity is : " + meter7.stockQuantity);
        System.out.println("The accuracy is : " + meter7.accuracy);
        System.out.println("The isEcoFriendly is : " + meter7.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter7.measurementMode);
        System.out.println("The rating is : " + meter7.rating);
        System.out.println("The batteryVoltage is : " + meter7.batteryVoltage);
        System.out.println("The isCertified is : " + meter7.isCertified);
        System.out.println("The countryOfOrigin is : " + meter7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter7.manufacturingYear);
        System.out.println("The probeLength is : " + meter7.probeLength);
        System.out.println("The supportsTemperature is : " + meter7.supportsTemperature);
        System.out.println("The certificationType is : " + meter7.certificationType);


        Multimeter meter8 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter8.meterBrand);
        System.out.println("The meterId is : " + meter8.meterId);
        System.out.println("The meterPrice is : " + meter8.meterPrice);
        System.out.println("The isAvailable is : " + meter8.isAvailable);
        System.out.println("The meterType is : " + meter8.meterType);
        System.out.println("The maxVoltage is : " + meter8.maxVoltage);
        System.out.println("The weight is : " + meter8.weight);
        System.out.println("The isPortable is : " + meter8.isPortable);
        System.out.println("The displayType is : " + meter8.displayType);
        System.out.println("The warrantyYears is : " + meter8.warrantyYears);
        System.out.println("The maxCurrent is : " + meter8.maxCurrent);
        System.out.println("The hasBacklight is : " + meter8.hasBacklight);
        System.out.println("The color is : " + meter8.color);
        System.out.println("The stockQuantity is : " + meter8.stockQuantity);
        System.out.println("The accuracy is : " + meter8.accuracy);
        System.out.println("The isEcoFriendly is : " + meter8.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter8.measurementMode);
        System.out.println("The rating is : " + meter8.rating);
        System.out.println("The batteryVoltage is : " + meter8.batteryVoltage);
        System.out.println("The isCertified is : " + meter8.isCertified);
        System.out.println("The countryOfOrigin is : " + meter8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter8.manufacturingYear);
        System.out.println("The probeLength is : " + meter8.probeLength);
        System.out.println("The supportsTemperature is : " + meter8.supportsTemperature);
        System.out.println("The certificationType is : " + meter8.certificationType);

        meter8.meterBrand = "Fluke";
        meter8.meterId = 8;
        meter8.meterPrice = 850.25;
        meter8.isAvailable = true;
        meter8.meterType = "Digital";
        meter8.maxVoltage = 1000.0;
        meter8.weight = 0.45;
        meter8.isPortable = true;
        meter8.displayType = "LCD";
        meter8.warrantyYears = 3;
        meter8.maxCurrent = 10.0;
        meter8.hasBacklight = true;
        meter8.color = "Yellow";
        meter8.stockQuantity = 18;
        meter8.accuracy = 0.5;
        meter8.isEcoFriendly = true;
        meter8.measurementMode = "Auto Range";
        meter8.rating = 5;
        meter8.batteryVoltage = 9.0;
        meter8.isCertified = true;
        meter8.countryOfOrigin = "USA";
        meter8.manufacturingYear = 2025;
        meter8.probeLength = 1.2;
        meter8.supportsTemperature = true;
        meter8.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter8.meterBrand);
        System.out.println("The meterId is : " + meter8.meterId);
        System.out.println("The meterPrice is : " + meter8.meterPrice);
        System.out.println("The isAvailable is : " + meter8.isAvailable);
        System.out.println("The meterType is : " + meter8.meterType);
        System.out.println("The maxVoltage is : " + meter8.maxVoltage);
        System.out.println("The weight is : " + meter8.weight);
        System.out.println("The isPortable is : " + meter8.isPortable);
        System.out.println("The displayType is : " + meter8.displayType);
        System.out.println("The warrantyYears is : " + meter8.warrantyYears);
        System.out.println("The maxCurrent is : " + meter8.maxCurrent);
        System.out.println("The hasBacklight is : " + meter8.hasBacklight);
        System.out.println("The color is : " + meter8.color);
        System.out.println("The stockQuantity is : " + meter8.stockQuantity);
        System.out.println("The accuracy is : " + meter8.accuracy);
        System.out.println("The isEcoFriendly is : " + meter8.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter8.measurementMode);
        System.out.println("The rating is : " + meter8.rating);
        System.out.println("The batteryVoltage is : " + meter8.batteryVoltage);
        System.out.println("The isCertified is : " + meter8.isCertified);
        System.out.println("The countryOfOrigin is : " + meter8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter8.manufacturingYear);
        System.out.println("The probeLength is : " + meter8.probeLength);
        System.out.println("The supportsTemperature is : " + meter8.supportsTemperature);
        System.out.println("The certificationType is : " + meter8.certificationType);


        Multimeter meter9 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter9.meterBrand);
        System.out.println("The meterId is : " + meter9.meterId);
        System.out.println("The meterPrice is : " + meter9.meterPrice);
        System.out.println("The isAvailable is : " + meter9.isAvailable);
        System.out.println("The meterType is : " + meter9.meterType);
        System.out.println("The maxVoltage is : " + meter9.maxVoltage);
        System.out.println("The weight is : " + meter9.weight);
        System.out.println("The isPortable is : " + meter9.isPortable);
        System.out.println("The displayType is : " + meter9.displayType);
        System.out.println("The warrantyYears is : " + meter9.warrantyYears);
        System.out.println("The maxCurrent is : " + meter9.maxCurrent);
        System.out.println("The hasBacklight is : " + meter9.hasBacklight);
        System.out.println("The color is : " + meter9.color);
        System.out.println("The stockQuantity is : " + meter9.stockQuantity);
        System.out.println("The accuracy is : " + meter9.accuracy);
        System.out.println("The isEcoFriendly is : " + meter9.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter9.measurementMode);
        System.out.println("The rating is : " + meter9.rating);
        System.out.println("The batteryVoltage is : " + meter9.batteryVoltage);
        System.out.println("The isCertified is : " + meter9.isCertified);
        System.out.println("The countryOfOrigin is : " + meter9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter9.manufacturingYear);
        System.out.println("The probeLength is : " + meter9.probeLength);
        System.out.println("The supportsTemperature is : " + meter9.supportsTemperature);
        System.out.println("The certificationType is : " + meter9.certificationType);

        meter9.meterBrand = "Fluke";
        meter9.meterId = 9;
        meter9.meterPrice = 950.25;
        meter9.isAvailable = true;
        meter9.meterType = "Digital";
        meter9.maxVoltage = 1000.0;
        meter9.weight = 0.45;
        meter9.isPortable = true;
        meter9.displayType = "LCD";
        meter9.warrantyYears = 3;
        meter9.maxCurrent = 10.0;
        meter9.hasBacklight = true;
        meter9.color = "Yellow";
        meter9.stockQuantity = 18;
        meter9.accuracy = 0.5;
        meter9.isEcoFriendly = true;
        meter9.measurementMode = "Auto Range";
        meter9.rating = 5;
        meter9.batteryVoltage = 9.0;
        meter9.isCertified = true;
        meter9.countryOfOrigin = "USA";
        meter9.manufacturingYear = 2025;
        meter9.probeLength = 1.2;
        meter9.supportsTemperature = true;
        meter9.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter9.meterBrand);
        System.out.println("The meterId is : " + meter9.meterId);
        System.out.println("The meterPrice is : " + meter9.meterPrice);
        System.out.println("The isAvailable is : " + meter9.isAvailable);
        System.out.println("The meterType is : " + meter9.meterType);
        System.out.println("The maxVoltage is : " + meter9.maxVoltage);
        System.out.println("The weight is : " + meter9.weight);
        System.out.println("The isPortable is : " + meter9.isPortable);
        System.out.println("The displayType is : " + meter9.displayType);
        System.out.println("The warrantyYears is : " + meter9.warrantyYears);
        System.out.println("The maxCurrent is : " + meter9.maxCurrent);
        System.out.println("The hasBacklight is : " + meter9.hasBacklight);
        System.out.println("The color is : " + meter9.color);
        System.out.println("The stockQuantity is : " + meter9.stockQuantity);
        System.out.println("The accuracy is : " + meter9.accuracy);
        System.out.println("The isEcoFriendly is : " + meter9.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter9.measurementMode);
        System.out.println("The rating is : " + meter9.rating);
        System.out.println("The batteryVoltage is : " + meter9.batteryVoltage);
        System.out.println("The isCertified is : " + meter9.isCertified);
        System.out.println("The countryOfOrigin is : " + meter9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter9.manufacturingYear);
        System.out.println("The probeLength is : " + meter9.probeLength);
        System.out.println("The supportsTemperature is : " + meter9.supportsTemperature);
        System.out.println("The certificationType is : " + meter9.certificationType);


        Multimeter meter10 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter10.meterBrand);
        System.out.println("The meterId is : " + meter10.meterId);
        System.out.println("The meterPrice is : " + meter10.meterPrice);
        System.out.println("The isAvailable is : " + meter10.isAvailable);
        System.out.println("The meterType is : " + meter10.meterType);
        System.out.println("The maxVoltage is : " + meter10.maxVoltage);
        System.out.println("The weight is : " + meter10.weight);
        System.out.println("The isPortable is : " + meter10.isPortable);
        System.out.println("The displayType is : " + meter10.displayType);
        System.out.println("The warrantyYears is : " + meter10.warrantyYears);
        System.out.println("The maxCurrent is : " + meter10.maxCurrent);
        System.out.println("The hasBacklight is : " + meter10.hasBacklight);
        System.out.println("The color is : " + meter10.color);
        System.out.println("The stockQuantity is : " + meter10.stockQuantity);
        System.out.println("The accuracy is : " + meter10.accuracy);
        System.out.println("The isEcoFriendly is : " + meter10.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter10.measurementMode);
        System.out.println("The rating is : " + meter10.rating);
        System.out.println("The batteryVoltage is : " + meter10.batteryVoltage);
        System.out.println("The isCertified is : " + meter10.isCertified);
        System.out.println("The countryOfOrigin is : " + meter10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter10.manufacturingYear);
        System.out.println("The probeLength is : " + meter10.probeLength);
        System.out.println("The supportsTemperature is : " + meter10.supportsTemperature);
        System.out.println("The certificationType is : " + meter10.certificationType);

        meter10.meterBrand = "Fluke";
        meter10.meterId = 10;
        meter10.meterPrice = 1050.25;
        meter10.isAvailable = true;
        meter10.meterType = "Digital";
        meter10.maxVoltage = 1000.0;
        meter10.weight = 0.45;
        meter10.isPortable = true;
        meter10.displayType = "LCD";
        meter10.warrantyYears = 3;
        meter10.maxCurrent = 10.0;
        meter10.hasBacklight = true;
        meter10.color = "Yellow";
        meter10.stockQuantity = 18;
        meter10.accuracy = 0.5;
        meter10.isEcoFriendly = true;
        meter10.measurementMode = "Auto Range";
        meter10.rating = 5;
        meter10.batteryVoltage = 9.0;
        meter10.isCertified = true;
        meter10.countryOfOrigin = "USA";
        meter10.manufacturingYear = 2025;
        meter10.probeLength = 1.2;
        meter10.supportsTemperature = true;
        meter10.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter10.meterBrand);
        System.out.println("The meterId is : " + meter10.meterId);
        System.out.println("The meterPrice is : " + meter10.meterPrice);
        System.out.println("The isAvailable is : " + meter10.isAvailable);
        System.out.println("The meterType is : " + meter10.meterType);
        System.out.println("The maxVoltage is : " + meter10.maxVoltage);
        System.out.println("The weight is : " + meter10.weight);
        System.out.println("The isPortable is : " + meter10.isPortable);
        System.out.println("The displayType is : " + meter10.displayType);
        System.out.println("The warrantyYears is : " + meter10.warrantyYears);
        System.out.println("The maxCurrent is : " + meter10.maxCurrent);
        System.out.println("The hasBacklight is : " + meter10.hasBacklight);
        System.out.println("The color is : " + meter10.color);
        System.out.println("The stockQuantity is : " + meter10.stockQuantity);
        System.out.println("The accuracy is : " + meter10.accuracy);
        System.out.println("The isEcoFriendly is : " + meter10.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter10.measurementMode);
        System.out.println("The rating is : " + meter10.rating);
        System.out.println("The batteryVoltage is : " + meter10.batteryVoltage);
        System.out.println("The isCertified is : " + meter10.isCertified);
        System.out.println("The countryOfOrigin is : " + meter10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter10.manufacturingYear);
        System.out.println("The probeLength is : " + meter10.probeLength);
        System.out.println("The supportsTemperature is : " + meter10.supportsTemperature);
        System.out.println("The certificationType is : " + meter10.certificationType);


        Multimeter meter11 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter11.meterBrand);
        System.out.println("The meterId is : " + meter11.meterId);
        System.out.println("The meterPrice is : " + meter11.meterPrice);
        System.out.println("The isAvailable is : " + meter11.isAvailable);
        System.out.println("The meterType is : " + meter11.meterType);
        System.out.println("The maxVoltage is : " + meter11.maxVoltage);
        System.out.println("The weight is : " + meter11.weight);
        System.out.println("The isPortable is : " + meter11.isPortable);
        System.out.println("The displayType is : " + meter11.displayType);
        System.out.println("The warrantyYears is : " + meter11.warrantyYears);
        System.out.println("The maxCurrent is : " + meter11.maxCurrent);
        System.out.println("The hasBacklight is : " + meter11.hasBacklight);
        System.out.println("The color is : " + meter11.color);
        System.out.println("The stockQuantity is : " + meter11.stockQuantity);
        System.out.println("The accuracy is : " + meter11.accuracy);
        System.out.println("The isEcoFriendly is : " + meter11.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter11.measurementMode);
        System.out.println("The rating is : " + meter11.rating);
        System.out.println("The batteryVoltage is : " + meter11.batteryVoltage);
        System.out.println("The isCertified is : " + meter11.isCertified);
        System.out.println("The countryOfOrigin is : " + meter11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter11.manufacturingYear);
        System.out.println("The probeLength is : " + meter11.probeLength);
        System.out.println("The supportsTemperature is : " + meter11.supportsTemperature);
        System.out.println("The certificationType is : " + meter11.certificationType);

        meter11.meterBrand = "Fluke";
        meter11.meterId = 11;
        meter11.meterPrice = 1150.25;
        meter11.isAvailable = true;
        meter11.meterType = "Digital";
        meter11.maxVoltage = 1000.0;
        meter11.weight = 0.45;
        meter11.isPortable = true;
        meter11.displayType = "LCD";
        meter11.warrantyYears = 3;
        meter11.maxCurrent = 10.0;
        meter11.hasBacklight = true;
        meter11.color = "Yellow";
        meter11.stockQuantity = 18;
        meter11.accuracy = 0.5;
        meter11.isEcoFriendly = true;
        meter11.measurementMode = "Auto Range";
        meter11.rating = 5;
        meter11.batteryVoltage = 9.0;
        meter11.isCertified = true;
        meter11.countryOfOrigin = "USA";
        meter11.manufacturingYear = 2025;
        meter11.probeLength = 1.2;
        meter11.supportsTemperature = true;
        meter11.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter11.meterBrand);
        System.out.println("The meterId is : " + meter11.meterId);
        System.out.println("The meterPrice is : " + meter11.meterPrice);
        System.out.println("The isAvailable is : " + meter11.isAvailable);
        System.out.println("The meterType is : " + meter11.meterType);
        System.out.println("The maxVoltage is : " + meter11.maxVoltage);
        System.out.println("The weight is : " + meter11.weight);
        System.out.println("The isPortable is : " + meter11.isPortable);
        System.out.println("The displayType is : " + meter11.displayType);
        System.out.println("The warrantyYears is : " + meter11.warrantyYears);
        System.out.println("The maxCurrent is : " + meter11.maxCurrent);
        System.out.println("The hasBacklight is : " + meter11.hasBacklight);
        System.out.println("The color is : " + meter11.color);
        System.out.println("The stockQuantity is : " + meter11.stockQuantity);
        System.out.println("The accuracy is : " + meter11.accuracy);
        System.out.println("The isEcoFriendly is : " + meter11.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter11.measurementMode);
        System.out.println("The rating is : " + meter11.rating);
        System.out.println("The batteryVoltage is : " + meter11.batteryVoltage);
        System.out.println("The isCertified is : " + meter11.isCertified);
        System.out.println("The countryOfOrigin is : " + meter11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter11.manufacturingYear);
        System.out.println("The probeLength is : " + meter11.probeLength);
        System.out.println("The supportsTemperature is : " + meter11.supportsTemperature);
        System.out.println("The certificationType is : " + meter11.certificationType);


        Multimeter meter12 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter12.meterBrand);
        System.out.println("The meterId is : " + meter12.meterId);
        System.out.println("The meterPrice is : " + meter12.meterPrice);
        System.out.println("The isAvailable is : " + meter12.isAvailable);
        System.out.println("The meterType is : " + meter12.meterType);
        System.out.println("The maxVoltage is : " + meter12.maxVoltage);
        System.out.println("The weight is : " + meter12.weight);
        System.out.println("The isPortable is : " + meter12.isPortable);
        System.out.println("The displayType is : " + meter12.displayType);
        System.out.println("The warrantyYears is : " + meter12.warrantyYears);
        System.out.println("The maxCurrent is : " + meter12.maxCurrent);
        System.out.println("The hasBacklight is : " + meter12.hasBacklight);
        System.out.println("The color is : " + meter12.color);
        System.out.println("The stockQuantity is : " + meter12.stockQuantity);
        System.out.println("The accuracy is : " + meter12.accuracy);
        System.out.println("The isEcoFriendly is : " + meter12.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter12.measurementMode);
        System.out.println("The rating is : " + meter12.rating);
        System.out.println("The batteryVoltage is : " + meter12.batteryVoltage);
        System.out.println("The isCertified is : " + meter12.isCertified);
        System.out.println("The countryOfOrigin is : " + meter12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter12.manufacturingYear);
        System.out.println("The probeLength is : " + meter12.probeLength);
        System.out.println("The supportsTemperature is : " + meter12.supportsTemperature);
        System.out.println("The certificationType is : " + meter12.certificationType);

        meter12.meterBrand = "Fluke";
        meter12.meterId = 12;
        meter12.meterPrice = 1250.25;
        meter12.isAvailable = true;
        meter12.meterType = "Digital";
        meter12.maxVoltage = 1000.0;
        meter12.weight = 0.45;
        meter12.isPortable = true;
        meter12.displayType = "LCD";
        meter12.warrantyYears = 3;
        meter12.maxCurrent = 10.0;
        meter12.hasBacklight = true;
        meter12.color = "Yellow";
        meter12.stockQuantity = 18;
        meter12.accuracy = 0.5;
        meter12.isEcoFriendly = true;
        meter12.measurementMode = "Auto Range";
        meter12.rating = 5;
        meter12.batteryVoltage = 9.0;
        meter12.isCertified = true;
        meter12.countryOfOrigin = "USA";
        meter12.manufacturingYear = 2025;
        meter12.probeLength = 1.2;
        meter12.supportsTemperature = true;
        meter12.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter12.meterBrand);
        System.out.println("The meterId is : " + meter12.meterId);
        System.out.println("The meterPrice is : " + meter12.meterPrice);
        System.out.println("The isAvailable is : " + meter12.isAvailable);
        System.out.println("The meterType is : " + meter12.meterType);
        System.out.println("The maxVoltage is : " + meter12.maxVoltage);
        System.out.println("The weight is : " + meter12.weight);
        System.out.println("The isPortable is : " + meter12.isPortable);
        System.out.println("The displayType is : " + meter12.displayType);
        System.out.println("The warrantyYears is : " + meter12.warrantyYears);
        System.out.println("The maxCurrent is : " + meter12.maxCurrent);
        System.out.println("The hasBacklight is : " + meter12.hasBacklight);
        System.out.println("The color is : " + meter12.color);
        System.out.println("The stockQuantity is : " + meter12.stockQuantity);
        System.out.println("The accuracy is : " + meter12.accuracy);
        System.out.println("The isEcoFriendly is : " + meter12.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter12.measurementMode);
        System.out.println("The rating is : " + meter12.rating);
        System.out.println("The batteryVoltage is : " + meter12.batteryVoltage);
        System.out.println("The isCertified is : " + meter12.isCertified);
        System.out.println("The countryOfOrigin is : " + meter12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter12.manufacturingYear);
        System.out.println("The probeLength is : " + meter12.probeLength);
        System.out.println("The supportsTemperature is : " + meter12.supportsTemperature);
        System.out.println("The certificationType is : " + meter12.certificationType);


        Multimeter meter13 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter13.meterBrand);
        System.out.println("The meterId is : " + meter13.meterId);
        System.out.println("The meterPrice is : " + meter13.meterPrice);
        System.out.println("The isAvailable is : " + meter13.isAvailable);
        System.out.println("The meterType is : " + meter13.meterType);
        System.out.println("The maxVoltage is : " + meter13.maxVoltage);
        System.out.println("The weight is : " + meter13.weight);
        System.out.println("The isPortable is : " + meter13.isPortable);
        System.out.println("The displayType is : " + meter13.displayType);
        System.out.println("The warrantyYears is : " + meter13.warrantyYears);
        System.out.println("The maxCurrent is : " + meter13.maxCurrent);
        System.out.println("The hasBacklight is : " + meter13.hasBacklight);
        System.out.println("The color is : " + meter13.color);
        System.out.println("The stockQuantity is : " + meter13.stockQuantity);
        System.out.println("The accuracy is : " + meter13.accuracy);
        System.out.println("The isEcoFriendly is : " + meter13.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter13.measurementMode);
        System.out.println("The rating is : " + meter13.rating);
        System.out.println("The batteryVoltage is : " + meter13.batteryVoltage);
        System.out.println("The isCertified is : " + meter13.isCertified);
        System.out.println("The countryOfOrigin is : " + meter13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter13.manufacturingYear);
        System.out.println("The probeLength is : " + meter13.probeLength);
        System.out.println("The supportsTemperature is : " + meter13.supportsTemperature);
        System.out.println("The certificationType is : " + meter13.certificationType);

        meter13.meterBrand = "Fluke";
        meter13.meterId = 13;
        meter13.meterPrice = 1350.25;
        meter13.isAvailable = true;
        meter13.meterType = "Digital";
        meter13.maxVoltage = 1000.0;
        meter13.weight = 0.45;
        meter13.isPortable = true;
        meter13.displayType = "LCD";
        meter13.warrantyYears = 3;
        meter13.maxCurrent = 10.0;
        meter13.hasBacklight = true;
        meter13.color = "Yellow";
        meter13.stockQuantity = 18;
        meter13.accuracy = 0.5;
        meter13.isEcoFriendly = true;
        meter13.measurementMode = "Auto Range";
        meter13.rating = 5;
        meter13.batteryVoltage = 9.0;
        meter13.isCertified = true;
        meter13.countryOfOrigin = "USA";
        meter13.manufacturingYear = 2025;
        meter13.probeLength = 1.2;
        meter13.supportsTemperature = true;
        meter13.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter13.meterBrand);
        System.out.println("The meterId is : " + meter13.meterId);
        System.out.println("The meterPrice is : " + meter13.meterPrice);
        System.out.println("The isAvailable is : " + meter13.isAvailable);
        System.out.println("The meterType is : " + meter13.meterType);
        System.out.println("The maxVoltage is : " + meter13.maxVoltage);
        System.out.println("The weight is : " + meter13.weight);
        System.out.println("The isPortable is : " + meter13.isPortable);
        System.out.println("The displayType is : " + meter13.displayType);
        System.out.println("The warrantyYears is : " + meter13.warrantyYears);
        System.out.println("The maxCurrent is : " + meter13.maxCurrent);
        System.out.println("The hasBacklight is : " + meter13.hasBacklight);
        System.out.println("The color is : " + meter13.color);
        System.out.println("The stockQuantity is : " + meter13.stockQuantity);
        System.out.println("The accuracy is : " + meter13.accuracy);
        System.out.println("The isEcoFriendly is : " + meter13.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter13.measurementMode);
        System.out.println("The rating is : " + meter13.rating);
        System.out.println("The batteryVoltage is : " + meter13.batteryVoltage);
        System.out.println("The isCertified is : " + meter13.isCertified);
        System.out.println("The countryOfOrigin is : " + meter13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter13.manufacturingYear);
        System.out.println("The probeLength is : " + meter13.probeLength);
        System.out.println("The supportsTemperature is : " + meter13.supportsTemperature);
        System.out.println("The certificationType is : " + meter13.certificationType);


        Multimeter meter14 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter14.meterBrand);
        System.out.println("The meterId is : " + meter14.meterId);
        System.out.println("The meterPrice is : " + meter14.meterPrice);
        System.out.println("The isAvailable is : " + meter14.isAvailable);
        System.out.println("The meterType is : " + meter14.meterType);
        System.out.println("The maxVoltage is : " + meter14.maxVoltage);
        System.out.println("The weight is : " + meter14.weight);
        System.out.println("The isPortable is : " + meter14.isPortable);
        System.out.println("The displayType is : " + meter14.displayType);
        System.out.println("The warrantyYears is : " + meter14.warrantyYears);
        System.out.println("The maxCurrent is : " + meter14.maxCurrent);
        System.out.println("The hasBacklight is : " + meter14.hasBacklight);
        System.out.println("The color is : " + meter14.color);
        System.out.println("The stockQuantity is : " + meter14.stockQuantity);
        System.out.println("The accuracy is : " + meter14.accuracy);
        System.out.println("The isEcoFriendly is : " + meter14.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter14.measurementMode);
        System.out.println("The rating is : " + meter14.rating);
        System.out.println("The batteryVoltage is : " + meter14.batteryVoltage);
        System.out.println("The isCertified is : " + meter14.isCertified);
        System.out.println("The countryOfOrigin is : " + meter14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter14.manufacturingYear);
        System.out.println("The probeLength is : " + meter14.probeLength);
        System.out.println("The supportsTemperature is : " + meter14.supportsTemperature);
        System.out.println("The certificationType is : " + meter14.certificationType);

        meter14.meterBrand = "Fluke";
        meter14.meterId = 14;
        meter14.meterPrice = 1450.25;
        meter14.isAvailable = true;
        meter14.meterType = "Digital";
        meter14.maxVoltage = 1000.0;
        meter14.weight = 0.45;
        meter14.isPortable = true;
        meter14.displayType = "LCD";
        meter14.warrantyYears = 3;
        meter14.maxCurrent = 10.0;
        meter14.hasBacklight = true;
        meter14.color = "Yellow";
        meter14.stockQuantity = 18;
        meter14.accuracy = 0.5;
        meter14.isEcoFriendly = true;
        meter14.measurementMode = "Auto Range";
        meter14.rating = 5;
        meter14.batteryVoltage = 9.0;
        meter14.isCertified = true;
        meter14.countryOfOrigin = "USA";
        meter14.manufacturingYear = 2025;
        meter14.probeLength = 1.2;
        meter14.supportsTemperature = true;
        meter14.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter14.meterBrand);
        System.out.println("The meterId is : " + meter14.meterId);
        System.out.println("The meterPrice is : " + meter14.meterPrice);
        System.out.println("The isAvailable is : " + meter14.isAvailable);
        System.out.println("The meterType is : " + meter14.meterType);
        System.out.println("The maxVoltage is : " + meter14.maxVoltage);
        System.out.println("The weight is : " + meter14.weight);
        System.out.println("The isPortable is : " + meter14.isPortable);
        System.out.println("The displayType is : " + meter14.displayType);
        System.out.println("The warrantyYears is : " + meter14.warrantyYears);
        System.out.println("The maxCurrent is : " + meter14.maxCurrent);
        System.out.println("The hasBacklight is : " + meter14.hasBacklight);
        System.out.println("The color is : " + meter14.color);
        System.out.println("The stockQuantity is : " + meter14.stockQuantity);
        System.out.println("The accuracy is : " + meter14.accuracy);
        System.out.println("The isEcoFriendly is : " + meter14.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter14.measurementMode);
        System.out.println("The rating is : " + meter14.rating);
        System.out.println("The batteryVoltage is : " + meter14.batteryVoltage);
        System.out.println("The isCertified is : " + meter14.isCertified);
        System.out.println("The countryOfOrigin is : " + meter14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter14.manufacturingYear);
        System.out.println("The probeLength is : " + meter14.probeLength);
        System.out.println("The supportsTemperature is : " + meter14.supportsTemperature);
        System.out.println("The certificationType is : " + meter14.certificationType);


        Multimeter meter15 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter15.meterBrand);
        System.out.println("The meterId is : " + meter15.meterId);
        System.out.println("The meterPrice is : " + meter15.meterPrice);
        System.out.println("The isAvailable is : " + meter15.isAvailable);
        System.out.println("The meterType is : " + meter15.meterType);
        System.out.println("The maxVoltage is : " + meter15.maxVoltage);
        System.out.println("The weight is : " + meter15.weight);
        System.out.println("The isPortable is : " + meter15.isPortable);
        System.out.println("The displayType is : " + meter15.displayType);
        System.out.println("The warrantyYears is : " + meter15.warrantyYears);
        System.out.println("The maxCurrent is : " + meter15.maxCurrent);
        System.out.println("The hasBacklight is : " + meter15.hasBacklight);
        System.out.println("The color is : " + meter15.color);
        System.out.println("The stockQuantity is : " + meter15.stockQuantity);
        System.out.println("The accuracy is : " + meter15.accuracy);
        System.out.println("The isEcoFriendly is : " + meter15.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter15.measurementMode);
        System.out.println("The rating is : " + meter15.rating);
        System.out.println("The batteryVoltage is : " + meter15.batteryVoltage);
        System.out.println("The isCertified is : " + meter15.isCertified);
        System.out.println("The countryOfOrigin is : " + meter15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter15.manufacturingYear);
        System.out.println("The probeLength is : " + meter15.probeLength);
        System.out.println("The supportsTemperature is : " + meter15.supportsTemperature);
        System.out.println("The certificationType is : " + meter15.certificationType);

        meter15.meterBrand = "Fluke";
        meter15.meterId = 15;
        meter15.meterPrice = 1550.25;
        meter15.isAvailable = true;
        meter15.meterType = "Digital";
        meter15.maxVoltage = 1000.0;
        meter15.weight = 0.45;
        meter15.isPortable = true;
        meter15.displayType = "LCD";
        meter15.warrantyYears = 3;
        meter15.maxCurrent = 10.0;
        meter15.hasBacklight = true;
        meter15.color = "Yellow";
        meter15.stockQuantity = 18;
        meter15.accuracy = 0.5;
        meter15.isEcoFriendly = true;
        meter15.measurementMode = "Auto Range";
        meter15.rating = 5;
        meter15.batteryVoltage = 9.0;
        meter15.isCertified = true;
        meter15.countryOfOrigin = "USA";
        meter15.manufacturingYear = 2025;
        meter15.probeLength = 1.2;
        meter15.supportsTemperature = true;
        meter15.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter15.meterBrand);
        System.out.println("The meterId is : " + meter15.meterId);
        System.out.println("The meterPrice is : " + meter15.meterPrice);
        System.out.println("The isAvailable is : " + meter15.isAvailable);
        System.out.println("The meterType is : " + meter15.meterType);
        System.out.println("The maxVoltage is : " + meter15.maxVoltage);
        System.out.println("The weight is : " + meter15.weight);
        System.out.println("The isPortable is : " + meter15.isPortable);
        System.out.println("The displayType is : " + meter15.displayType);
        System.out.println("The warrantyYears is : " + meter15.warrantyYears);
        System.out.println("The maxCurrent is : " + meter15.maxCurrent);
        System.out.println("The hasBacklight is : " + meter15.hasBacklight);
        System.out.println("The color is : " + meter15.color);
        System.out.println("The stockQuantity is : " + meter15.stockQuantity);
        System.out.println("The accuracy is : " + meter15.accuracy);
        System.out.println("The isEcoFriendly is : " + meter15.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter15.measurementMode);
        System.out.println("The rating is : " + meter15.rating);
        System.out.println("The batteryVoltage is : " + meter15.batteryVoltage);
        System.out.println("The isCertified is : " + meter15.isCertified);
        System.out.println("The countryOfOrigin is : " + meter15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter15.manufacturingYear);
        System.out.println("The probeLength is : " + meter15.probeLength);
        System.out.println("The supportsTemperature is : " + meter15.supportsTemperature);
        System.out.println("The certificationType is : " + meter15.certificationType);


        Multimeter meter16 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter16.meterBrand);
        System.out.println("The meterId is : " + meter16.meterId);
        System.out.println("The meterPrice is : " + meter16.meterPrice);
        System.out.println("The isAvailable is : " + meter16.isAvailable);
        System.out.println("The meterType is : " + meter16.meterType);
        System.out.println("The maxVoltage is : " + meter16.maxVoltage);
        System.out.println("The weight is : " + meter16.weight);
        System.out.println("The isPortable is : " + meter16.isPortable);
        System.out.println("The displayType is : " + meter16.displayType);
        System.out.println("The warrantyYears is : " + meter16.warrantyYears);
        System.out.println("The maxCurrent is : " + meter16.maxCurrent);
        System.out.println("The hasBacklight is : " + meter16.hasBacklight);
        System.out.println("The color is : " + meter16.color);
        System.out.println("The stockQuantity is : " + meter16.stockQuantity);
        System.out.println("The accuracy is : " + meter16.accuracy);
        System.out.println("The isEcoFriendly is : " + meter16.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter16.measurementMode);
        System.out.println("The rating is : " + meter16.rating);
        System.out.println("The batteryVoltage is : " + meter16.batteryVoltage);
        System.out.println("The isCertified is : " + meter16.isCertified);
        System.out.println("The countryOfOrigin is : " + meter16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter16.manufacturingYear);
        System.out.println("The probeLength is : " + meter16.probeLength);
        System.out.println("The supportsTemperature is : " + meter16.supportsTemperature);
        System.out.println("The certificationType is : " + meter16.certificationType);

        meter16.meterBrand = "Fluke";
        meter16.meterId = 16;
        meter16.meterPrice = 1650.25;
        meter16.isAvailable = true;
        meter16.meterType = "Digital";
        meter16.maxVoltage = 1000.0;
        meter16.weight = 0.45;
        meter16.isPortable = true;
        meter16.displayType = "LCD";
        meter16.warrantyYears = 3;
        meter16.maxCurrent = 10.0;
        meter16.hasBacklight = true;
        meter16.color = "Yellow";
        meter16.stockQuantity = 18;
        meter16.accuracy = 0.5;
        meter16.isEcoFriendly = true;
        meter16.measurementMode = "Auto Range";
        meter16.rating = 5;
        meter16.batteryVoltage = 9.0;
        meter16.isCertified = true;
        meter16.countryOfOrigin = "USA";
        meter16.manufacturingYear = 2025;
        meter16.probeLength = 1.2;
        meter16.supportsTemperature = true;
        meter16.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter16.meterBrand);
        System.out.println("The meterId is : " + meter16.meterId);
        System.out.println("The meterPrice is : " + meter16.meterPrice);
        System.out.println("The isAvailable is : " + meter16.isAvailable);
        System.out.println("The meterType is : " + meter16.meterType);
        System.out.println("The maxVoltage is : " + meter16.maxVoltage);
        System.out.println("The weight is : " + meter16.weight);
        System.out.println("The isPortable is : " + meter16.isPortable);
        System.out.println("The displayType is : " + meter16.displayType);
        System.out.println("The warrantyYears is : " + meter16.warrantyYears);
        System.out.println("The maxCurrent is : " + meter16.maxCurrent);
        System.out.println("The hasBacklight is : " + meter16.hasBacklight);
        System.out.println("The color is : " + meter16.color);
        System.out.println("The stockQuantity is : " + meter16.stockQuantity);
        System.out.println("The accuracy is : " + meter16.accuracy);
        System.out.println("The isEcoFriendly is : " + meter16.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter16.measurementMode);
        System.out.println("The rating is : " + meter16.rating);
        System.out.println("The batteryVoltage is : " + meter16.batteryVoltage);
        System.out.println("The isCertified is : " + meter16.isCertified);
        System.out.println("The countryOfOrigin is : " + meter16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter16.manufacturingYear);
        System.out.println("The probeLength is : " + meter16.probeLength);
        System.out.println("The supportsTemperature is : " + meter16.supportsTemperature);
        System.out.println("The certificationType is : " + meter16.certificationType);


        Multimeter meter17 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter17.meterBrand);
        System.out.println("The meterId is : " + meter17.meterId);
        System.out.println("The meterPrice is : " + meter17.meterPrice);
        System.out.println("The isAvailable is : " + meter17.isAvailable);
        System.out.println("The meterType is : " + meter17.meterType);
        System.out.println("The maxVoltage is : " + meter17.maxVoltage);
        System.out.println("The weight is : " + meter17.weight);
        System.out.println("The isPortable is : " + meter17.isPortable);
        System.out.println("The displayType is : " + meter17.displayType);
        System.out.println("The warrantyYears is : " + meter17.warrantyYears);
        System.out.println("The maxCurrent is : " + meter17.maxCurrent);
        System.out.println("The hasBacklight is : " + meter17.hasBacklight);
        System.out.println("The color is : " + meter17.color);
        System.out.println("The stockQuantity is : " + meter17.stockQuantity);
        System.out.println("The accuracy is : " + meter17.accuracy);
        System.out.println("The isEcoFriendly is : " + meter17.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter17.measurementMode);
        System.out.println("The rating is : " + meter17.rating);
        System.out.println("The batteryVoltage is : " + meter17.batteryVoltage);
        System.out.println("The isCertified is : " + meter17.isCertified);
        System.out.println("The countryOfOrigin is : " + meter17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter17.manufacturingYear);
        System.out.println("The probeLength is : " + meter17.probeLength);
        System.out.println("The supportsTemperature is : " + meter17.supportsTemperature);
        System.out.println("The certificationType is : " + meter17.certificationType);

        meter17.meterBrand = "Fluke";
        meter17.meterId = 17;
        meter17.meterPrice = 1750.25;
        meter17.isAvailable = true;
        meter17.meterType = "Digital";
        meter17.maxVoltage = 1000.0;
        meter17.weight = 0.45;
        meter17.isPortable = true;
        meter17.displayType = "LCD";
        meter17.warrantyYears = 3;
        meter17.maxCurrent = 10.0;
        meter17.hasBacklight = true;
        meter17.color = "Yellow";
        meter17.stockQuantity = 18;
        meter17.accuracy = 0.5;
        meter17.isEcoFriendly = true;
        meter17.measurementMode = "Auto Range";
        meter17.rating = 5;
        meter17.batteryVoltage = 9.0;
        meter17.isCertified = true;
        meter17.countryOfOrigin = "USA";
        meter17.manufacturingYear = 2025;
        meter17.probeLength = 1.2;
        meter17.supportsTemperature = true;
        meter17.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter17.meterBrand);
        System.out.println("The meterId is : " + meter17.meterId);
        System.out.println("The meterPrice is : " + meter17.meterPrice);
        System.out.println("The isAvailable is : " + meter17.isAvailable);
        System.out.println("The meterType is : " + meter17.meterType);
        System.out.println("The maxVoltage is : " + meter17.maxVoltage);
        System.out.println("The weight is : " + meter17.weight);
        System.out.println("The isPortable is : " + meter17.isPortable);
        System.out.println("The displayType is : " + meter17.displayType);
        System.out.println("The warrantyYears is : " + meter17.warrantyYears);
        System.out.println("The maxCurrent is : " + meter17.maxCurrent);
        System.out.println("The hasBacklight is : " + meter17.hasBacklight);
        System.out.println("The color is : " + meter17.color);
        System.out.println("The stockQuantity is : " + meter17.stockQuantity);
        System.out.println("The accuracy is : " + meter17.accuracy);
        System.out.println("The isEcoFriendly is : " + meter17.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter17.measurementMode);
        System.out.println("The rating is : " + meter17.rating);
        System.out.println("The batteryVoltage is : " + meter17.batteryVoltage);
        System.out.println("The isCertified is : " + meter17.isCertified);
        System.out.println("The countryOfOrigin is : " + meter17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter17.manufacturingYear);
        System.out.println("The probeLength is : " + meter17.probeLength);
        System.out.println("The supportsTemperature is : " + meter17.supportsTemperature);
        System.out.println("The certificationType is : " + meter17.certificationType);


        Multimeter meter18 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter18.meterBrand);
        System.out.println("The meterId is : " + meter18.meterId);
        System.out.println("The meterPrice is : " + meter18.meterPrice);
        System.out.println("The isAvailable is : " + meter18.isAvailable);
        System.out.println("The meterType is : " + meter18.meterType);
        System.out.println("The maxVoltage is : " + meter18.maxVoltage);
        System.out.println("The weight is : " + meter18.weight);
        System.out.println("The isPortable is : " + meter18.isPortable);
        System.out.println("The displayType is : " + meter18.displayType);
        System.out.println("The warrantyYears is : " + meter18.warrantyYears);
        System.out.println("The maxCurrent is : " + meter18.maxCurrent);
        System.out.println("The hasBacklight is : " + meter18.hasBacklight);
        System.out.println("The color is : " + meter18.color);
        System.out.println("The stockQuantity is : " + meter18.stockQuantity);
        System.out.println("The accuracy is : " + meter18.accuracy);
        System.out.println("The isEcoFriendly is : " + meter18.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter18.measurementMode);
        System.out.println("The rating is : " + meter18.rating);
        System.out.println("The batteryVoltage is : " + meter18.batteryVoltage);
        System.out.println("The isCertified is : " + meter18.isCertified);
        System.out.println("The countryOfOrigin is : " + meter18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter18.manufacturingYear);
        System.out.println("The probeLength is : " + meter18.probeLength);
        System.out.println("The supportsTemperature is : " + meter18.supportsTemperature);
        System.out.println("The certificationType is : " + meter18.certificationType);

        meter18.meterBrand = "Fluke";
        meter18.meterId = 18;
        meter18.meterPrice = 1850.25;
        meter18.isAvailable = true;
        meter18.meterType = "Digital";
        meter18.maxVoltage = 1000.0;
        meter18.weight = 0.45;
        meter18.isPortable = true;
        meter18.displayType = "LCD";
        meter18.warrantyYears = 3;
        meter18.maxCurrent = 10.0;
        meter18.hasBacklight = true;
        meter18.color = "Yellow";
        meter18.stockQuantity = 18;
        meter18.accuracy = 0.5;
        meter18.isEcoFriendly = true;
        meter18.measurementMode = "Auto Range";
        meter18.rating = 5;
        meter18.batteryVoltage = 9.0;
        meter18.isCertified = true;
        meter18.countryOfOrigin = "USA";
        meter18.manufacturingYear = 2025;
        meter18.probeLength = 1.2;
        meter18.supportsTemperature = true;
        meter18.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter18.meterBrand);
        System.out.println("The meterId is : " + meter18.meterId);
        System.out.println("The meterPrice is : " + meter18.meterPrice);
        System.out.println("The isAvailable is : " + meter18.isAvailable);
        System.out.println("The meterType is : " + meter18.meterType);
        System.out.println("The maxVoltage is : " + meter18.maxVoltage);
        System.out.println("The weight is : " + meter18.weight);
        System.out.println("The isPortable is : " + meter18.isPortable);
        System.out.println("The displayType is : " + meter18.displayType);
        System.out.println("The warrantyYears is : " + meter18.warrantyYears);
        System.out.println("The maxCurrent is : " + meter18.maxCurrent);
        System.out.println("The hasBacklight is : " + meter18.hasBacklight);
        System.out.println("The color is : " + meter18.color);
        System.out.println("The stockQuantity is : " + meter18.stockQuantity);
        System.out.println("The accuracy is : " + meter18.accuracy);
        System.out.println("The isEcoFriendly is : " + meter18.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter18.measurementMode);
        System.out.println("The rating is : " + meter18.rating);
        System.out.println("The batteryVoltage is : " + meter18.batteryVoltage);
        System.out.println("The isCertified is : " + meter18.isCertified);
        System.out.println("The countryOfOrigin is : " + meter18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter18.manufacturingYear);
        System.out.println("The probeLength is : " + meter18.probeLength);
        System.out.println("The supportsTemperature is : " + meter18.supportsTemperature);
        System.out.println("The certificationType is : " + meter18.certificationType);


        Multimeter meter19 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter19.meterBrand);
        System.out.println("The meterId is : " + meter19.meterId);
        System.out.println("The meterPrice is : " + meter19.meterPrice);
        System.out.println("The isAvailable is : " + meter19.isAvailable);
        System.out.println("The meterType is : " + meter19.meterType);
        System.out.println("The maxVoltage is : " + meter19.maxVoltage);
        System.out.println("The weight is : " + meter19.weight);
        System.out.println("The isPortable is : " + meter19.isPortable);
        System.out.println("The displayType is : " + meter19.displayType);
        System.out.println("The warrantyYears is : " + meter19.warrantyYears);
        System.out.println("The maxCurrent is : " + meter19.maxCurrent);
        System.out.println("The hasBacklight is : " + meter19.hasBacklight);
        System.out.println("The color is : " + meter19.color);
        System.out.println("The stockQuantity is : " + meter19.stockQuantity);
        System.out.println("The accuracy is : " + meter19.accuracy);
        System.out.println("The isEcoFriendly is : " + meter19.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter19.measurementMode);
        System.out.println("The rating is : " + meter19.rating);
        System.out.println("The batteryVoltage is : " + meter19.batteryVoltage);
        System.out.println("The isCertified is : " + meter19.isCertified);
        System.out.println("The countryOfOrigin is : " + meter19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter19.manufacturingYear);
        System.out.println("The probeLength is : " + meter19.probeLength);
        System.out.println("The supportsTemperature is : " + meter19.supportsTemperature);
        System.out.println("The certificationType is : " + meter19.certificationType);

        meter19.meterBrand = "Fluke";
        meter19.meterId = 19;
        meter19.meterPrice = 1950.25;
        meter19.isAvailable = true;
        meter19.meterType = "Digital";
        meter19.maxVoltage = 1000.0;
        meter19.weight = 0.45;
        meter19.isPortable = true;
        meter19.displayType = "LCD";
        meter19.warrantyYears = 3;
        meter19.maxCurrent = 10.0;
        meter19.hasBacklight = true;
        meter19.color = "Yellow";
        meter19.stockQuantity = 18;
        meter19.accuracy = 0.5;
        meter19.isEcoFriendly = true;
        meter19.measurementMode = "Auto Range";
        meter19.rating = 5;
        meter19.batteryVoltage = 9.0;
        meter19.isCertified = true;
        meter19.countryOfOrigin = "USA";
        meter19.manufacturingYear = 2025;
        meter19.probeLength = 1.2;
        meter19.supportsTemperature = true;
        meter19.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter19.meterBrand);
        System.out.println("The meterId is : " + meter19.meterId);
        System.out.println("The meterPrice is : " + meter19.meterPrice);
        System.out.println("The isAvailable is : " + meter19.isAvailable);
        System.out.println("The meterType is : " + meter19.meterType);
        System.out.println("The maxVoltage is : " + meter19.maxVoltage);
        System.out.println("The weight is : " + meter19.weight);
        System.out.println("The isPortable is : " + meter19.isPortable);
        System.out.println("The displayType is : " + meter19.displayType);
        System.out.println("The warrantyYears is : " + meter19.warrantyYears);
        System.out.println("The maxCurrent is : " + meter19.maxCurrent);
        System.out.println("The hasBacklight is : " + meter19.hasBacklight);
        System.out.println("The color is : " + meter19.color);
        System.out.println("The stockQuantity is : " + meter19.stockQuantity);
        System.out.println("The accuracy is : " + meter19.accuracy);
        System.out.println("The isEcoFriendly is : " + meter19.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter19.measurementMode);
        System.out.println("The rating is : " + meter19.rating);
        System.out.println("The batteryVoltage is : " + meter19.batteryVoltage);
        System.out.println("The isCertified is : " + meter19.isCertified);
        System.out.println("The countryOfOrigin is : " + meter19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter19.manufacturingYear);
        System.out.println("The probeLength is : " + meter19.probeLength);
        System.out.println("The supportsTemperature is : " + meter19.supportsTemperature);
        System.out.println("The certificationType is : " + meter19.certificationType);


        Multimeter meter20 = new Multimeter();

        System.out.println("Before initialization");

        System.out.println("The meterBrand is : " + meter20.meterBrand);
        System.out.println("The meterId is : " + meter20.meterId);
        System.out.println("The meterPrice is : " + meter20.meterPrice);
        System.out.println("The isAvailable is : " + meter20.isAvailable);
        System.out.println("The meterType is : " + meter20.meterType);
        System.out.println("The maxVoltage is : " + meter20.maxVoltage);
        System.out.println("The weight is : " + meter20.weight);
        System.out.println("The isPortable is : " + meter20.isPortable);
        System.out.println("The displayType is : " + meter20.displayType);
        System.out.println("The warrantyYears is : " + meter20.warrantyYears);
        System.out.println("The maxCurrent is : " + meter20.maxCurrent);
        System.out.println("The hasBacklight is : " + meter20.hasBacklight);
        System.out.println("The color is : " + meter20.color);
        System.out.println("The stockQuantity is : " + meter20.stockQuantity);
        System.out.println("The accuracy is : " + meter20.accuracy);
        System.out.println("The isEcoFriendly is : " + meter20.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter20.measurementMode);
        System.out.println("The rating is : " + meter20.rating);
        System.out.println("The batteryVoltage is : " + meter20.batteryVoltage);
        System.out.println("The isCertified is : " + meter20.isCertified);
        System.out.println("The countryOfOrigin is : " + meter20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter20.manufacturingYear);
        System.out.println("The probeLength is : " + meter20.probeLength);
        System.out.println("The supportsTemperature is : " + meter20.supportsTemperature);
        System.out.println("The certificationType is : " + meter20.certificationType);

        meter20.meterBrand = "Fluke";
        meter20.meterId = 20;
        meter20.meterPrice = 2050.25;
        meter20.isAvailable = true;
        meter20.meterType = "Digital";
        meter20.maxVoltage = 1000.0;
        meter20.weight = 0.45;
        meter20.isPortable = true;
        meter20.displayType = "LCD";
        meter20.warrantyYears = 3;
        meter20.maxCurrent = 10.0;
        meter20.hasBacklight = true;
        meter20.color = "Yellow";
        meter20.stockQuantity = 18;
        meter20.accuracy = 0.5;
        meter20.isEcoFriendly = true;
        meter20.measurementMode = "Auto Range";
        meter20.rating = 5;
        meter20.batteryVoltage = 9.0;
        meter20.isCertified = true;
        meter20.countryOfOrigin = "USA";
        meter20.manufacturingYear = 2025;
        meter20.probeLength = 1.2;
        meter20.supportsTemperature = true;
        meter20.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The meterBrand is : " + meter20.meterBrand);
        System.out.println("The meterId is : " + meter20.meterId);
        System.out.println("The meterPrice is : " + meter20.meterPrice);
        System.out.println("The isAvailable is : " + meter20.isAvailable);
        System.out.println("The meterType is : " + meter20.meterType);
        System.out.println("The maxVoltage is : " + meter20.maxVoltage);
        System.out.println("The weight is : " + meter20.weight);
        System.out.println("The isPortable is : " + meter20.isPortable);
        System.out.println("The displayType is : " + meter20.displayType);
        System.out.println("The warrantyYears is : " + meter20.warrantyYears);
        System.out.println("The maxCurrent is : " + meter20.maxCurrent);
        System.out.println("The hasBacklight is : " + meter20.hasBacklight);
        System.out.println("The color is : " + meter20.color);
        System.out.println("The stockQuantity is : " + meter20.stockQuantity);
        System.out.println("The accuracy is : " + meter20.accuracy);
        System.out.println("The isEcoFriendly is : " + meter20.isEcoFriendly);
        System.out.println("The measurementMode is : " + meter20.measurementMode);
        System.out.println("The rating is : " + meter20.rating);
        System.out.println("The batteryVoltage is : " + meter20.batteryVoltage);
        System.out.println("The isCertified is : " + meter20.isCertified);
        System.out.println("The countryOfOrigin is : " + meter20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + meter20.manufacturingYear);
        System.out.println("The probeLength is : " + meter20.probeLength);
        System.out.println("The supportsTemperature is : " + meter20.supportsTemperature);
        System.out.println("The certificationType is : " + meter20.certificationType);


    }
}
