
class NecklaceRunner {
    public static void main(String[] args) {
        
        //  Default constructor 
        
        Necklace n1 = new Necklace();
        n1.material = "Gold";
        n1.style = "Pendant";
        n1.gemstone = "Diamond";
        n1.chainLength = 18.0;
        n1.weight = 12.5;
        n1.claspType = "Lobster";
        n1.price = 1200.00;
        n1.brand = "Tiffany & Co.";
        n1.isEngraved = false;
        n1.isAdjustable = true;
        n1.hasPendant = true;
        n1.karat = 18;
        n1.finish = "Polished";
        n1.origin = "USA";
        n1.warrantyYears = 5;
        n1.targetGender = "Women";
        n1.collectionName = "Keys";
        n1.stockQuantity = 15;
        n1.chainType = "Cable";
        n1.color = "Yellow Gold";

        Necklace n2 = new Necklace();
        n2.material = "Silver";
        n2.style = "Choker";
        n2.gemstone = "None";
        n2.chainLength = 14.0;
        n2.weight = 25.0;
        n2.claspType = "Spring Ring";
        n2.price = 150.00;
        n2.brand = "Pandora";
        n2.isEngraved = false;
        n2.isAdjustable = true;
        n2.hasPendant = false;
        n2.karat = 0;
        n2.finish = "Matte";
        n2.origin = "Denmark";
        n2.warrantyYears = 1;
        n2.targetGender = "Women";
        n2.collectionName = "Moments";
        n2.stockQuantity = 40;
        n2.chainType = "Snake";
        n2.color = "Silver";

        Necklace n3 = new Necklace();
        n3.material = "Platinum";
        n3.style = "Solitaire";
        n3.gemstone = "Sapphire";
        n3.chainLength = 16.0;
        n3.weight = 18.0;
        n3.claspType = "Box";
        n3.price = 4500.00;
        n3.brand = "Cartier";
        n3.isEngraved = true;
        n3.isAdjustable = false;
        n3.hasPendant = true;
        n3.karat = 0;
        n3.finish = "High Shine";
        n3.origin = "France";
        n3.warrantyYears = 10;
        n3.targetGender = "Women";
        n3.collectionName = "Destinée";
        n3.stockQuantity = 5;
        n3.chainType = "Rope";
        n3.color = "Silver";

        Necklace n4 = new Necklace();
        n4.material = "Stainless Steel";
        n4.style = "Chain";
        n4.gemstone = "None";
        n4.chainLength = 24.0;
        n4.weight = 45.0;
        n4.claspType = "Lobster";
        n4.price = 65.00;
        n4.brand = "Diesel";
        n4.isEngraved = false;
        n4.isAdjustable = false;
        n4.hasPendant = false;
        n4.karat = 0;
        n4.finish = "Brushed";
        n4.origin = "Italy";
        n4.warrantyYears = 2;
        n4.targetGender = "Men";
        n4.collectionName = "Industrial";
        n4.stockQuantity = 100;
        n4.chainType = "Cuban";
        n4.color = "Silver";

        Necklace n5 = new Necklace();
        n5.material = "Rose Gold";
        n5.style = "Locket";
        n5.gemstone = "Ruby";
        n5.chainLength = 20.0;
        n5.weight = 15.0;
        n5.claspType = "Spring Ring";
        n5.price = 850.00;
        n5.brand = "Kay Jewelers";
        n5.isEngraved = true;
        n5.isAdjustable = true;
        n5.hasPendant = true;
        n5.karat = 14;
        n5.finish = "Polished";
        n5.origin = "USA";
        n5.warrantyYears = 3;
        n5.targetGender = "Women";
        n5.collectionName = "Family";
        n5.stockQuantity = 25;
        n5.chainType = "Box";
        n5.color = "Rose Gold";

        Necklace n6 = new Necklace();
        n6.material = "Pearl";
        n6.style = "Strand";
        n6.gemstone = "Pearl";
        n6.chainLength = 18.0;
        n6.weight = 35.0;
        n6.claspType = "Fishhook";
        n6.price = 2200.00;
        n6.brand = "Mikimoto";
        n6.isEngraved = false;
        n6.isAdjustable = false;
        n6.hasPendant = false;
        n6.karat = 0;
        n6.finish = "Lustrous";
        n6.origin = "Japan";
        n6.warrantyYears = 5;
        n6.targetGender = "Women";
        n6.collectionName = "Classic";
        n6.stockQuantity = 10;
        n6.chainType = "Thread";
        n6.color = "White";

        Necklace n7 = new Necklace();
        n7.material = "Leather";
        n7.style = "Cord";
        n7.gemstone = "Turquoise";
        n7.chainLength = 22.0;
        n7.weight = 10.0;
        n7.claspType = "Tie";
        n7.price = 45.00;
        n7.brand = "Fossil";
        n7.isEngraved = false;
        n7.isAdjustable = true;
        n7.hasPendant = true;
        n7.karat = 0;
        n7.finish = "Natural";
        n7.origin = "India";
        n7.warrantyYears = 1;
        n7.targetGender = "Unisex";
        n7.collectionName = "Boho";
        n7.stockQuantity = 60;
        n7.chainType = "Leather Braided";
        n7.color = "Brown";

        Necklace n8 = new Necklace();
        n8.material = "White Gold";
        n8.style = "Halo Pendant";
        n8.gemstone = "Emerald";
        n8.chainLength = 18.0;
        n8.weight = 11.0;
        n8.claspType = "Lobster";
        n8.price = 3200.00;
        n8.brand = "Zales";
        n8.isEngraved = false;
        n8.isAdjustable = true;
        n8.hasPendant = true;
        n8.karat = 14;
        n8.finish = "Polished";
        n8.origin = "USA";
        n8.warrantyYears = 4;
        n8.targetGender = "Women";
        n8.collectionName = "Vera Wang";
        n8.stockQuantity = 12;
        n8.chainType = "Wheat";
        n8.color = "White Gold";

        Necklace n9 = new Necklace();
        n9.material = "Brass";
        n9.style = "Collar";
        n9.gemstone = "None";
        n9.chainLength = 15.0;
        n9.weight = 55.0;
        n9.claspType = "Hook";
        n9.price = 90.00;
        n9.brand = "Madewell";
        n9.isEngraved = false;
        n9.isAdjustable = false;
        n9.hasPendant = false;
        n9.karat = 0;
        n9.finish = "Antiqued";
        n9.origin = "China";
        n9.warrantyYears = 1;
        n9.targetGender = "Women";
        n9.collectionName = "Vintage";
        n9.stockQuantity = 35;
        n9.chainType = "Solid";
        n9.color = "Gold";

        Necklace n10 = new Necklace();
        n10.material = "Crystal";
        n10.style = "Statement";
        n10.gemstone = "Swarovski";
        n10.chainLength = 17.0;
        n10.weight = 40.0;
        n10.claspType = "Fold Over";
        n10.price = 350.00;
        n10.brand = "Swarovski";
        n10.isEngraved = false;
        n10.isAdjustable = true;
        n10.hasPendant = false;
        n10.karat = 0;
        n10.finish = "Sparkle";
        n10.origin = "Austria";
        n10.warrantyYears = 2;
        n10.targetGender = "Women";
        n10.collectionName = "Millenia";
        n10.stockQuantity = 50;
        n10.chainType = "Link";
        n10.color = "Clear";

        Necklace n11 = new Necklace();
        n11.material = "Titanium";
        n11.style = "Dog Tag";
        n11.gemstone = "None";
        n11.chainLength = 26.0;
        n11.weight = 20.0;
        n11.claspType = "Ball Chain Connector";
        n11.price = 55.00;
        n11.brand = "Spikes";
        n11.isEngraved = true;
        n11.isAdjustable = false;
        n11.hasPendant = true;
        n11.karat = 0;
        n11.finish = "Matte";
        n11.origin = "USA";
        n11.warrantyYears = 1;
        n11.targetGender = "Men";
        n11.collectionName = "Military";
        n11.stockQuantity = 200;
        n11.chainType = "Ball";
        n11.color = "Grey";

        Necklace n12 = new Necklace();
        n12.material = "Wood";
        n12.style = "Beaded";
        n12.gemstone = "Onyx";
        n12.chainLength = 30.0;
        n12.weight = 30.0;
        n12.claspType = "None";
        n12.price = 35.00;
        n12.brand = "Local Artisan";
        n12.isEngraved = false;
        n12.isAdjustable = false;
        n12.hasPendant = false;
        n12.karat = 0;
        n12.finish = "Smooth";
        n12.origin = "Bali";
        n12.warrantyYears = 0;
        n12.targetGender = "Unisex";
        n12.collectionName = "Mala";
        n12.stockQuantity = 80;
        n12.chainType = "String";
        n12.color = "Brown/Black";

        Necklace n13 = new Necklace();
        n13.material = "Tungsten";
        n13.style = "Heavy Chain";
        n13.gemstone = "None";
        n13.chainLength = 22.0;
        n13.weight = 80.0;
        n13.claspType = "Lobster";
        n13.price = 120.00;
        n13.brand = "Triton";
        n13.isEngraved = false;
        n13.isAdjustable = false;
        n13.hasPendant = false;
        n13.karat = 0;
        n13.finish = "Polished";
        n13.origin = "China";
        n13.warrantyYears = 5;
        n13.targetGender = "Men";
        n13.collectionName = "Core";
        n13.stockQuantity = 20;
        n13.chainType = "Byzantine";
        n13.color = "Gunmetal";

        Necklace n14 = new Necklace();
        n14.material = "Gold Plated";
        n14.style = "Layered";
        n14.gemstone = "Cubic Zirconia";
        n14.chainLength = 16.0;
        n14.weight = 14.0;
        n14.claspType = "Lobster";
        n14.price = 45.00;
        n14.brand = "BaubleBar";
        n14.isEngraved = false;
        n14.isAdjustable = true;
        n14.hasPendant = true;
        n14.karat = 14;
        n14.finish = "Shiny";
        n14.origin = "China";
        n14.warrantyYears = 1;
        n14.targetGender = "Women";
        n14.collectionName = "Essentials";
        n14.stockQuantity = 150;
        n14.chainType = "Paperclip";
        n14.color = "Gold";

        Necklace n15 = new Necklace();
        n15.material = "Enamel";
        n15.style = "Pendant";
        n15.gemstone = "None";
        n15.chainLength = 18.0;
        n15.weight = 10.0;
        n15.claspType = "Spring Ring";
        n15.price = 85.00;
        n15.brand = "Kate Spade";
        n15.isEngraved = true;
        n15.isAdjustable = true;
        n15.hasPendant = true;
        n15.karat = 0;
        n15.finish = "Glossy";
        n15.origin = "USA";
        n15.warrantyYears = 1;
        n15.targetGender = "Women";
        n15.collectionName = "Initial";
        n15.stockQuantity = 90;
        n15.chainType = "Cable";
        n15.color = "Pink/Gold";

        Necklace n16 = new Necklace();
        n16.material = "Copper";
        n16.style = "Wire Wrapped";
        n16.gemstone = "Amethyst";
        n16.chainLength = 20.0;
        n16.weight = 18.0;
        n16.claspType = "Toggle";
        n16.price = 60.00;
        n16.brand = "Etsy Artist";
        n16.isEngraved = false;
        n16.isAdjustable = false;
        n16.hasPendant = true;
        n16.karat = 0;
        n16.finish = "Oxidized";
        n16.origin = "Canada";
        n16.warrantyYears = 0;
        n16.targetGender = "Unisex";
        n16.collectionName = "Healing";
        n16.stockQuantity = 5;
        n16.chainType = "Rolo";
        n16.color = "Copper";

        Necklace n17 = new Necklace();
        n17.material = "Resin";
        n17.style = "Chunky Chain";
        n17.gemstone = "None";
        n17.chainLength = 18.0;
        n17.weight = 35.0;
        n17.claspType = "Magnetic";
        n17.price = 45.00;
        n17.brand = "Anthropologie";
        n17.isEngraved = false;
        n17.isAdjustable = false;
        n17.hasPendant = false;
        n17.karat = 0;
        n17.finish = "Matte";
        n17.origin = "India";
        n17.warrantyYears = 1;
        n17.targetGender = "Women";
        n17.collectionName = "Statement";
        n17.stockQuantity = 30;
        n17.chainType = "Resin Link";
        n17.color = "Tortoiseshell";

        Necklace n18 = new Necklace();
        n18.material = "Sterling Silver";
        n18.style = "Y-Necklace";
        n18.gemstone = "Diamond";
        n18.chainLength = 20.0;
        n18.weight = 8.5;
        n18.claspType = "Lobster";
        n18.price = 250.00;
        n18.brand = "Kendra Scott";
        n18.isEngraved = false;
        n18.isAdjustable = true;
        n18.hasPendant = true;
        n18.karat = 0;
        n18.finish = "Shiny";
        n18.origin = "USA";
        n18.warrantyYears = 2;
        n18.targetGender = "Women";
        n18.collectionName = "Fine Jewelry";
        n18.stockQuantity = 25;
        n18.chainType = "Cable";
        n18.color = "Silver";

        Necklace n19 = new Necklace();
        n19.material = "Glass";
        n19.style = "Pendant";
        n19.gemstone = "None";
        n19.chainLength = 18.0;
        n19.weight = 12.0;
        n19.claspType = "Spring Ring";
        n19.price = 55.00;
        n19.brand = "Murano";
        n19.isEngraved = false;
        n19.isAdjustable = false;
        n19.hasPendant = true;
        n19.karat = 0;
        n19.finish = "Glossy";
        n19.origin = "Italy";
        n19.warrantyYears = 1;
        n19.targetGender = "Women";
        n19.collectionName = "Venice";
        n19.stockQuantity = 45;
        n19.chainType = "Cord";
        n19.color = "Blue/Gold";

        Necklace n20 = new Necklace();
        n20.material = "Gold";
        n20.style = "Nameplate";
        n20.gemstone = "None";
        n20.chainLength = 16.0;
        n20.weight = 5.5;
        n20.claspType = "Spring Ring";
        n20.price = 350.00;
        n20.brand = "CustomJewelers";
        n20.isEngraved = true;
        n20.isAdjustable = true;
        n20.hasPendant = true;
        n20.karat = 14;
        n20.finish = "Polished";
        n20.origin = "USA";
        n20.warrantyYears = 2;
        n20.targetGender = "Women";
        n20.collectionName = "Personalized";
        n20.stockQuantity = 100;
        n20.chainType = "Cable";
        n20.color = "Yellow Gold";

        Necklace n21 = new Necklace();
        n21.material = "Silk Thread";
        n21.style = "Tassel";
        n21.gemstone = "Agate";
        n21.chainLength = 32.0;
        n21.weight = 20.0;
        n21.claspType = "None";
        n21.price = 45.00;
        n21.brand = "Stella & Dot";
        n21.isEngraved = false;
        n21.isAdjustable = false;
        n21.hasPendant = true;
        n21.karat = 0;
        n21.finish = "Soft";
        n21.origin = "China";
        n21.warrantyYears = 1;
        n21.targetGender = "Women";
        n21.collectionName = "Bohemian";
        n21.stockQuantity = 75;
        n21.chainType = "Beaded";
        n21.color = "Mint Green";

        Necklace n22 = new Necklace();
        n22.material = "Bronze";
        n22.style = "Coin Pendant";
        n22.gemstone = "None";
        n22.chainLength = 20.0;
        n22.weight = 15.0;
        n22.claspType = "Lobster";
        n22.price = 85.00;
        n22.brand = "Alighieri";
        n22.isEngraved = true;
        n22.isAdjustable = true;
        n22.hasPendant = true;
        n22.karat = 0;
        n22.finish = "Textured";
        n22.origin = "UK";
        n22.warrantyYears = 2;
        n22.targetGender = "Unisex";
        n22.collectionName = "Dante";
        n22.stockQuantity = 20;
        n22.chainType = "Rolo";
        n22.color = "Gold";

        Necklace n23 = new Necklace();
        n23.material = "Silver";
        n23.style = "Lariat";
        n23.gemstone = "Pearl";
        n23.chainLength = 24.0;
        n23.weight = 10.0;
        n23.claspType = "Toggle";
        n23.price = 120.00;
        n23.brand = "Gorjana";
        n23.isEngraved = false;
        n23.isAdjustable = true;
        n23.hasPendant = false;
        n23.karat = 0;
        n23.finish = "Shiny";
        n23.origin = "USA";
        n23.warrantyYears = 1;
        n23.targetGender = "Women";
        n23.collectionName = "Laguna";
        n23.stockQuantity = 65;
        n23.chainType = "Cable";
        n23.color = "Silver";

        Necklace n24 = new Necklace();
        n24.material = "Ceramic";
        n24.style = "Beaded Collar";
        n24.gemstone = "None";
        n24.chainLength = 16.0;
        n24.weight = 40.0;
        n24.claspType = "Hook";
        n24.price = 65.00;
        n24.brand = "Marni";
        n24.isEngraved = false;
        n24.isAdjustable = true;
        n24.hasPendant = false;
        n24.karat = 0;
        n24.finish = "Glazed";
        n24.origin = "Italy";
        n24.warrantyYears = 1;
        n24.targetGender = "Women";
        n24.collectionName = "Abstract";
        n24.stockQuantity = 15;
        n24.chainType = "Cord";
        n24.color = "Red/White/Blue";

        Necklace n25 = new Necklace();
        n25.material = "Diamond";
        n25.style = "Rivière";
        n25.gemstone = "Diamond";
        n25.chainLength = 16.0;
        n25.weight = 30.0;
        n25.claspType = "Hidden Box";
        n25.price = 25000.00;
        n25.brand = "Harry Winston";
        n25.isEngraved = false;
        n25.isAdjustable = false;
        n25.hasPendant = false;
        n25.karat = 18;
        n25.finish = "Brilliant";
        n25.origin = "USA";
        n25.warrantyYears = 20;
        n25.targetGender = "Women";
        n25.collectionName = "High Jewelry";
        n25.stockQuantity = 2;
        n25.chainType = "Tennis";
        n25.color = "White Gold";

        System.out.println("Necklace 1: " + n1.brand + " " + n1.style + " | Gemstone: " + n1.gemstone + " | Price: $" + n1.price);
        System.out.println("Necklace 2: " + n2.brand + " " + n2.style + " | Gemstone: " + n2.gemstone + " | Price: $" + n2.price);
        System.out.println("Necklace 3: " + n3.brand + " " + n3.style + " | Gemstone: " + n3.gemstone + " | Price: $" + n3.price);
        System.out.println("Necklace 4: " + n4.brand + " " + n4.style + " | Gemstone: " + n4.gemstone + " | Price: $" + n4.price);
        System.out.println("Necklace 5: " + n5.brand + " " + n5.style + " | Gemstone: " + n5.gemstone + " | Price: $" + n5.price);
        System.out.println("Necklace 6: " + n6.brand + " " + n6.style + " | Gemstone: " + n6.gemstone + " | Price: $" + n6.price);
        System.out.println("Necklace 7: " + n7.brand + " " + n7.style + " | Gemstone: " + n7.gemstone + " | Price: $" + n7.price);
        System.out.println("Necklace 8: " + n8.brand + " " + n8.style + " | Gemstone: " + n8.gemstone + " | Price: $" + n8.price);
        System.out.println("Necklace 9: " + n9.brand + " " + n9.style + " | Gemstone: " + n9.gemstone + " | Price: $" + n9.price);
        System.out.println("Necklace 10: " + n10.brand + " " + n10.style + " | Gemstone: " + n10.gemstone + " | Price: $" + n10.price);
        System.out.println("Necklace 11: " + n11.brand + " " + n11.style + " | Gemstone: " + n11.gemstone + " | Price: $" + n11.price);
        System.out.println("Necklace 12: " + n12.brand + " " + n12.style + " | Gemstone: " + n12.gemstone + " | Price: $" + n12.price);
        System.out.println("Necklace 13: " + n13.brand + " " + n13.style + " | Gemstone: " + n13.gemstone + " | Price: $" + n13.price);
        System.out.println("Necklace 14: " + n14.brand + " " + n14.style + " | Gemstone: " + n14.gemstone + " | Price: $" + n14.price);
        System.out.println("Necklace 15: " + n15.brand + " " + n15.style + " | Gemstone: " + n15.gemstone + " | Price: $" + n15.price);
        System.out.println("Necklace 16: " + n16.brand + " " + n16.style + " | Gemstone: " + n16.gemstone + " | Price: $" + n16.price);
        System.out.println("Necklace 17: " + n17.brand + " " + n17.style + " | Gemstone: " + n17.gemstone + " | Price: $" + n17.price);
        System.out.println("Necklace 18: " + n18.brand + " " + n18.style + " | Gemstone: " + n18.gemstone + " | Price: $" + n18.price);
        System.out.println("Necklace 19: " + n19.brand + " " + n19.style + " | Gemstone: " + n19.gemstone + " | Price: $" + n19.price);
        System.out.println("Necklace 20: " + n20.brand + " " + n20.style + " | Gemstone: " + n20.gemstone + " | Price: $" + n20.price);
        System.out.println("Necklace 21: " + n21.brand + " " + n21.style + " | Gemstone: " + n21.gemstone + " | Price: $" + n21.price);
        System.out.println("Necklace 22: " + n22.brand + " " + n22.style + " | Gemstone: " + n22.gemstone + " | Price: $" + n22.price);
        System.out.println("Necklace 23: " + n23.brand + " " + n23.style + " | Gemstone: " + n23.gemstone + " | Price: $" + n23.price);
        System.out.println("Necklace 24: " + n24.brand + " " + n24.style + " | Gemstone: " + n24.gemstone + " | Price: $" + n24.price);
        System.out.println("Necklace 25: " + n25.brand + " " + n25.style + " | Gemstone: " + n25.gemstone + " | Price: $" + n25.price);


        // Parameterized constructor
        Necklace p1 = new Necklace("White Gold", "Cross Pendant", "Diamond", 18.0, 6.0, "Spring Ring", 850.00, "Zales", false, false, true, 14, "Polished", "USA", 2, "Women", "Faith", 40, "Cable", "Silver");
        Necklace p2 = new Necklace("Rose Gold", "Bar", "None", 16.0, 4.5, "Lobster", 250.00, "Mejuri", true, true, true, 14, "Shiny", "Canada", 2, "Women", "Minimalist", 100, "Rolo", "Rose Gold");
        Necklace p3 = new Necklace("Silver", "Compass", "Onyx", 22.0, 15.0, "Lobster", 180.00, "David Yurman", false, false, true, 0, "Oxidized", "USA", 5, "Men", "Maritime", 30, "Box", "Silver");
        Necklace p4 = new Necklace("Leather", "Choker", "None", 13.0, 5.0, "Buckle", 45.00, "Free People", false, true, false, 0, "Matte", "India", 0, "Women", "Festival", 80, "Strap", "Black");
        Necklace p5 = new Necklace("Gold", "Station", "Diamond", 36.0, 18.0, "Lobster", 3500.00, "Tiffany & Co.", false, false, false, 18, "Polished", "USA", 10, "Women", "Diamonds by the Yard", 10, "Cable", "Yellow Gold");
        Necklace p6 = new Necklace("Tungsten", "Cuban", "None", 24.0, 65.0, "Fold Over", 130.00, "Spikes", false, false, false, 0, "Brushed", "China", 2, "Men", "Heavy Duty", 50, "Cuban Link", "Grey");
        Necklace p7 = new Necklace("Stainless Steel", "Dog Tag", "None", 26.0, 22.0, "Ball", 35.00, "Fossil", true, false, true, 0, "Matte", "China", 1, "Men", "Military", 150, "Ball Chain", "Silver");
        Necklace p8 = new Necklace("Platinum", "Cluster", "Ruby", 16.0, 9.0, "Lobster", 4200.00, "Harry Winston", false, false, true, 0, "Brilliant", "USA", 10, "Women", "Winston Cluster", 4, "Cable", "Silver");
        Necklace p9 = new Necklace("Pearl", "Graduated", "Akoya Pearl", 18.0, 40.0, "Pearl Clasp", 3000.00, "Mikimoto", false, false, false, 18, "Lustrous", "Japan", 5, "Women", "Classic Pearl", 8, "Silk Thread", "White");
        Necklace p10 = new Necklace("Brass", "Statement", "Tiger Eye", 18.0, 50.0, "Toggle", 120.00, "Anthropologie", false, true, false, 0, "Antiqued", "India", 1, "Women", "Boho Statement", 25, "Chunky Link", "Gold");
        Necklace p11 = new Necklace("Crystal", "Collar", "Swarovski", 15.0, 45.0, "Fold Over", 400.00, "Swarovski", false, false, false, 0, "Sparkle", "Austria", 2, "Women", "Matrix", 35, "Link", "Clear");
        Necklace p12 = new Necklace("Gold Plated", "Coin", "None", 20.0, 8.0, "Spring Ring", 65.00, "Gorjana", false, true, true, 18, "Shiny", "USA", 1, "Women", "Layering", 200, "Cable", "Gold");
        Necklace p13 = new Necklace("Resin", "Beaded", "None", 22.0, 18.0, "Magnetic", 40.00, "J.Crew", false, false, false, 0, "Glossy", "China", 0, "Women", "Summer Colors", 60, "Cord", "Multicolor");
        Necklace p14 = new Necklace("Copper", "Mala", "Turquoise", 30.0, 28.0, "None", 55.00, "Yoga Outlet", false, false, false, 0, "Natural", "Nepal", 0, "Unisex", "Meditation", 85, "Thread", "Copper/Blue");
        Necklace p15 = new Necklace("Silver", "Heart Pendant", "None", 18.0, 6.5, "Spring Ring", 150.00, "Return to Tiffany", true, false, true, 0, "Polished", "USA", 5, "Women", "Return to Tiffany", 50, "Bead", "Silver");
        Necklace p16 = new Necklace("White Gold", "Tennis", "Diamond", 16.0, 25.0, "Box", 12000.00, "Blue Nile", false, false, false, 18, "Brilliant", "USA", 10, "Women", "Red Carpet", 5, "Tennis", "White Gold");
        Necklace p17 = new Necklace("Gold", "Initial", "None", 16.0, 4.0, "Spring Ring", 200.00, "Catbird", false, true, true, 14, "Polished", "USA", 2, "Women", "Alphabet", 150, "Cable", "Yellow Gold");
        Necklace p18 = new Necklace("Titanium", "Rope", "None", 22.0, 30.0, "Lobster", 85.00, "Titanium Kay", false, false, false, 0, "Brushed", "USA", 3, "Men", "Durable", 70, "Rope", "Grey");
        Necklace p19 = new Necklace("Silk", "Cord Pendant", "Jade", 24.0, 10.0, "Tie", 80.00, "Local Artist", false, true, true, 0, "Soft", "China", 0, "Unisex", "Zen", 30, "Silk Cord", "Green");
        Necklace p20 = new Necklace("Bronze", "Medallion", "None", 20.0, 18.0, "Lobster", 110.00, "Alighieri", true, true, true, 0, "Textured", "UK", 2, "Unisex", "Relic", 40, "Rolo", "Gold");
        Necklace p21 = new Necklace("Enamel", "Floral Pendant", "None", 18.0, 7.0, "Lobster", 95.00, "Kate Spade", false, true, true, 0, "Glossy", "USA", 1, "Women", "Garden", 90, "Cable", "Pink");
        Necklace p22 = new Necklace("Wood", "Chunky Bead", "None", 22.0, 25.0, "None", 35.00, "Ten Thousand Villages", false, false, false, 0, "Smooth", "Kenya", 0, "Women", "Fair Trade", 45, "Cord", "Brown");
        Necklace p23 = new Necklace("Vermeil", "Lariat", "Cubic Zirconia", 24.0, 9.0, "Toggle", 125.00, "Kendra Scott", false, true, false, 14, "Shiny", "USA", 1, "Women", "Evening", 55, "Cable", "Gold");
        Necklace p24 = new Necklace("Stainless Steel", "Cross", "None", 24.0, 15.0, "Lobster", 45.00, "Inox", false, false, true, 0, "Polished", "India", 1, "Men", "Faith", 120, "Box", "Silver");
        Necklace p25 = new Necklace("Platinum", "Three Stone", "Diamond", 18.0, 12.0, "Lobster", 8500.00, "De Beers", false, false, true, 0, "Brilliant", "UK", 10, "Women", "Past Present Future", 6, "Cable", "Silver");

        System.out.println("Param Necklace 1: " + p1.brand + " " + p1.style + " | Gemstone: " + p1.gemstone + " | Price: $" + p1.price);
        System.out.println("Param Necklace 2: " + p2.brand + " " + p2.style + " | Gemstone: " + p2.gemstone + " | Price: $" + p2.price);
        System.out.println("Param Necklace 3: " + p3.brand + " " + p3.style + " | Gemstone: " + p3.gemstone + " | Price: $" + p3.price);
        System.out.println("Param Necklace 4: " + p4.brand + " " + p4.style + " | Gemstone: " + p4.gemstone + " | Price: $" + p4.price);
        System.out.println("Param Necklace 5: " + p5.brand + " " + p5.style + " | Gemstone: " + p5.gemstone + " | Price: $" + p5.price);
        System.out.println("Param Necklace 6: " + p6.brand + " " + p6.style + " | Gemstone: " + p6.gemstone + " | Price: $" + p6.price);
        System.out.println("Param Necklace 7: " + p7.brand + " " + p7.style + " | Gemstone: " + p7.gemstone + " | Price: $" + p7.price);
        System.out.println("Param Necklace 8: " + p8.brand + " " + p8.style + " | Gemstone: " + p8.gemstone + " | Price: $" + p8.price);
        System.out.println("Param Necklace 9: " + p9.brand + " " + p9.style + " | Gemstone: " + p9.gemstone + " | Price: $" + p9.price);
        System.out.println("Param Necklace 10: " + p10.brand + " " + p10.style + " | Gemstone: " + p10.gemstone + " | Price: $" + p10.price);
        System.out.println("Param Necklace 11: " + p11.brand + " " + p11.style + " | Gemstone: " + p11.gemstone + " | Price: $" + p11.price);
        System.out.println("Param Necklace 12: " + p12.brand + " " + p12.style + " | Gemstone: " + p12.gemstone + " | Price: $" + p12.price);
        System.out.println("Param Necklace 13: " + p13.brand + " " + p13.style + " | Gemstone: " + p13.gemstone + " | Price: $" + p13.price);
        System.out.println("Param Necklace 14: " + p14.brand + " " + p14.style + " | Gemstone: " + p14.gemstone + " | Price: $" + p14.price);
        System.out.println("Param Necklace 15: " + p15.brand + " " + p15.style + " | Gemstone: " + p15.gemstone + " | Price: $" + p15.price);
        System.out.println("Param Necklace 16: " + p16.brand + " " + p16.style + " | Gemstone: " + p16.gemstone + " | Price: $" + p16.price);
        System.out.println("Param Necklace 17: " + p17.brand + " " + p17.style + " | Gemstone: " + p17.gemstone + " | Price: $" + p17.price);
        System.out.println("Param Necklace 18: " + p18.brand + " " + p18.style + " | Gemstone: " + p18.gemstone + " | Price: $" + p18.price);
        System.out.println("Param Necklace 19: " + p19.brand + " " + p19.style + " | Gemstone: " + p19.gemstone + " | Price: $" + p19.price);
        System.out.println("Param Necklace 20: " + p20.brand + " " + p20.style + " | Gemstone: " + p20.gemstone + " | Price: $" + p20.price);
        System.out.println("Param Necklace 21: " + p21.brand + " " + p21.style + " | Gemstone: " + p21.gemstone + " | Price: $" + p21.price);
        System.out.println("Param Necklace 22: " + p22.brand + " " + p22.style + " | Gemstone: " + p22.gemstone + " | Price: $" + p22.price);
        System.out.println("Param Necklace 23: " + p23.brand + " " + p23.style + " | Gemstone: " + p23.gemstone + " | Price: $" + p23.price);
        System.out.println("Param Necklace 24: " + p24.brand + " " + p24.style + " | Gemstone: " + p24.gemstone + " | Price: $" + p24.price);
        System.out.println("Param Necklace 25: " + p25.brand + " " + p25.style + " | Gemstone: " + p25.gemstone + " | Price: $" + p25.price);
    }
}
