
class PocketRunner {
    public static void main(String[] args) {
        
        // Default constructor
        Pocket p1 = new Pocket(); 
        p1.style = "Patch"; p1.placement = "Front Right"; p1.depth = 15;
        Pocket p2 = new Pocket(); 
        p2.style = "Flap"; p2.placement = "Back Left"; p2.depth = 12;
        Pocket p3 = new Pocket(); 
        p3.style = "Slit"; p3.placement = "Inside Breast"; p3.depth = 18;
        Pocket p4 = new Pocket(); 
        p4.style = "Welt"; p4.placement = "Front Left"; p4.depth = 14;
        Pocket p5 = new Pocket();
        p5.style = "Zippered"; p5.placement = "Sleeve"; p5.depth = 10;
        Pocket p6 = new Pocket(); 
        p6.style = "Cargo"; p6.placement = "Side Leg"; p6.depth = 20;
        Pocket p7 = new Pocket(); 
        p7.style = "Coin"; p7.placement = "Front Right Inner"; p7.depth = 5;
        Pocket p8 = new Pocket(); 
        p8.style = "Kangaroo"; p8.placement = "Front Center"; p8.depth = 25;
        Pocket p9 = new Pocket(); 
        p9.style = "Seam"; p9.placement = "Side Hip"; p9.depth = 16;
        Pocket p10 = new Pocket(); 
        p10.style = "Ticket"; p10.placement = "Waistband"; p10.depth = 8;
        Pocket p11 = new Pocket(); 
        p11.style = "Hidden"; p11.placement = "Inside Lining"; p11.depth = 15;
        Pocket p12 = new Pocket(); 
        p12.style = "Bellows"; p12.placement = "Lower Front Jacket"; p12.depth = 18;
        Pocket p13 = new Pocket(); 
        p13.style = "Besom"; p13.placement = "Chest"; p13.depth = 12;
        Pocket p14 = new Pocket(); 
        p14.style = "Slash"; p14.placement = "Hip"; p14.depth = 16;
        Pocket p15 = new Pocket(); 
        p15.style = "Pen"; p15.placement = "Upper Arm"; p15.depth = 14;
        Pocket p16 = new Pocket(); 
        p16.style = "Key"; p16.placement = "Back Inner"; p16.depth = 6;
        Pocket p17 = new Pocket(); 
        p17.style = "Mesh"; p17.placement = "Backpack Side"; p17.depth = 22;
        Pocket p18 = new Pocket(); 
        p18.style = "Gusseted"; p18.placement = "Thigh"; p18.depth = 19;
        Pocket p19 = new Pocket(); 
        p19.style = "Patch with Button"; p19.placement = "Chest Left"; p19.depth = 13;
        Pocket p20 = new Pocket(); 
        p20.style = "Faux"; p20.placement = "Decorative Front"; p20.depth = 0;
        Pocket p21 = new Pocket(); 
        p21.style = "Drop-in"; p21.placement = "Tote Inside"; p21.depth = 15;
        Pocket p22 = new Pocket(); 
        p22.style = "Security"; p22.placement = "Hidden Back"; p22.depth = 14;
        Pocket p23 = new Pocket(); 
        p23.style = "Media"; p23.placement = "Thigh Zipper"; p23.depth = 17;
        Pocket p24 = new Pocket(); 
        p24.style = "Pass"; p24.placement = "Forearm"; p24.depth = 9;
        Pocket p25 = new Pocket(); 
        p25.style = "Utility"; p25.placement = "Chest Right"; p25.depth = 16;

        System.out.println("Pocket Details : " + p1.style + " | " + p1.placement + " | Depth: " + p1.depth + "cm");
        System.out.println("Pocket Details : " + p2.style + " | " + p2.placement + " | Depth: " + p2.depth + "cm");
        System.out.println("Pocket Details : " + p3.style + " | " + p3.placement + " | Depth: " + p3.depth + "cm");
        System.out.println("Pocket Details : " + p4.style + " | " + p4.placement + " | Depth: " + p4.depth + "cm");
        System.out.println("Pocket Details : " + p5.style + " | " + p5.placement + " | Depth: " + p5.depth + "cm");
        System.out.println("Pocket Details : " + p6.style + " | " + p6.placement + " | Depth: " + p6.depth + "cm");
        System.out.println("Pocket Details : " + p7.style + " | " + p7.placement + " | Depth: " + p7.depth + "cm");
        System.out.println("Pocket Details : " + p8.style + " | " + p8.placement + " | Depth: " + p8.depth + "cm");
        System.out.println("Pocket Details : " + p9.style + " | " + p9.placement + " | Depth: " + p9.depth + "cm");
        System.out.println("Pocket Details : " + p10.style + " | " + p10.placement + " | Depth: " + p10.depth + "cm");
        System.out.println("Pocket Details : " + p11.style + " | " + p11.placement + " | Depth: " + p11.depth + "cm");
        System.out.println("Pocket Details : " + p12.style + " | " + p12.placement + " | Depth: " + p12.depth + "cm");
        System.out.println("Pocket Details : " + p13.style + " | " + p13.placement + " | Depth: " + p13.depth + "cm");
        System.out.println("Pocket Details : " + p14.style + " | " + p14.placement + " | Depth: " + p14.depth + "cm");
        System.out.println("Pocket Details : " + p15.style + " | " + p15.placement + " | Depth: " + p15.depth + "cm");
        System.out.println("Pocket Details : " + p16.style + " | " + p16.placement + " | Depth: " + p16.depth + "cm");
        System.out.println("Pocket Details : " + p17.style + " | " + p17.placement + " | Depth: " + p17.depth + "cm");
        System.out.println("Pocket Details : " + p18.style + " | " + p18.placement + " | Depth: " + p18.depth + "cm");
        System.out.println("Pocket Details : " + p19.style + " | " + p19.placement + " | Depth: " + p19.depth + "cm");
        System.out.println("Pocket Details : " + p20.style + " | " + p20.placement + " | Depth: " + p20.depth + "cm");
        System.out.println("Pocket Details : " + p21.style + " | " + p21.placement + " | Depth: " + p21.depth + "cm");
        System.out.println("Pocket Details : " + p22.style + " | " + p22.placement + " | Depth: " + p22.depth + "cm");
        System.out.println("Pocket Details : " + p23.style + " | " + p23.placement + " | Depth: " + p23.depth + "cm");
        System.out.println("Pocket Details : " + p24.style + " | " + p24.placement + " | Depth: " + p24.depth + "cm");
        System.out.println("Pocket Details : " + p25.style + " | " + p25.placement + " | Depth: " + p25.depth + "cm");

        // Parameterized constructor
        Pocket param1 = new Pocket("Magnetic Flap", "Chest Right", 14);
        Pocket param2 = new Pocket("Velcro Cargo", "Knee Side", 18);
        Pocket param3 = new Pocket("RFID Blocking", "Inner Wallet", 12);
        Pocket param4 = new Pocket("Fleece Lined", "Hand Warmer", 20);
        Pocket param5 = new Pocket("Clear ID", "Left Bicep", 9);
        Pocket param6 = new Pocket("Accordion", "Backpack Front", 16);
        Pocket param7 = new Pocket("Stash", "Under Collar", 7);
        Pocket param8 = new Pocket("Double Welt", "Suit Trousers Rear", 13);
        Pocket param9 = new Pocket("Curved Slash", "Jeans Front", 15);
        Pocket param10 = new Pocket("Tool Slip", "Overalls Side", 22);
        Pocket param11 = new Pocket("Expansion", "Duffel Bag End", 25);
        Pocket param12 = new Pocket("Laptop Sleeve", "Backpack Interior", 35);
        Pocket param13 = new Pocket("Bottle Holder", "Bag Exterior", 24);
        Pocket param14 = new Pocket("Concealed Carry", "Jacket Interior", 18);
        Pocket param15 = new Pocket("Ticket Slip", "Suit Jacket Left", 10);
        Pocket param16 = new Pocket("Goggle", "Ski Jacket Inner", 22);
        Pocket param17 = new Pocket("Snap Button Patch", "Work Shirt", 14);
        Pocket param18 = new Pocket("Waterproof Zip", "Raincoat Outer", 16);
        Pocket param19 = new Pocket("Chalk", "Climbing Harness", 12);
        Pocket param20 = new Pocket("Card Slot", "Phone Case Back", 8);
        Pocket param21 = new Pocket("Hidden Seam", "Skirt Side", 15);
        Pocket param22 = new Pocket("Poacher", "Hunting Vest Rear", 30);
        Pocket param23 = new Pocket("Knife", "Work Pants Front Right", 11);
        Pocket param24 = new Pocket("Sunglasses", "Jacket Upper Left", 15);
        Pocket param25 = new Pocket("Watch", "Waistcoat", 6);

        System.out.println("Param Pocket 1: " + param1.style + " | " + param1.placement + " | Depth: " + param1.depth + "cm");
        System.out.println("Param Pocket 2: " + param2.style + " | " + param2.placement + " | Depth: " + param2.depth + "cm");
        System.out.println("Param Pocket 3: " + param3.style + " | " + param3.placement + " | Depth: " + param3.depth + "cm");
        System.out.println("Param Pocket 4: " + param4.style + " | " + param4.placement + " | Depth: " + param4.depth + "cm");
        System.out.println("Param Pocket 5: " + param5.style + " | " + param5.placement + " | Depth: " + param5.depth + "cm");
        System.out.println("Param Pocket 6: " + param6.style + " | " + param6.placement + " | Depth: " + param6.depth + "cm");
        System.out.println("Param Pocket 7: " + param7.style + " | " + param7.placement + " | Depth: " + param7.depth + "cm");
        System.out.println("Param Pocket 8: " + param8.style + " | " + param8.placement + " | Depth: " + param8.depth + "cm");
        System.out.println("Param Pocket 9: " + param9.style + " | " + param9.placement + " | Depth: " + param9.depth + "cm");
        System.out.println("Param Pocket 10: " + param10.style + " | " + param10.placement + " | Depth: " + param10.depth + "cm");
        System.out.println("Param Pocket 11: " + param11.style + " | " + param11.placement + " | Depth: " + param11.depth + "cm");
        System.out.println("Param Pocket 12: " + param12.style + " | " + param12.placement + " | Depth: " + param12.depth + "cm");
        System.out.println("Param Pocket 13: " + param13.style + " | " + param13.placement + " | Depth: " + param13.depth + "cm");
        System.out.println("Param Pocket 14: " + param14.style + " | " + param14.placement + " | Depth: " + param14.depth + "cm");
        System.out.println("Param Pocket 15: " + param15.style + " | " + param15.placement + " | Depth: " + param15.depth + "cm");
        System.out.println("Param Pocket 16: " + param16.style + " | " + param16.placement + " | Depth: " + param16.depth + "cm");
        System.out.println("Param Pocket 17: " + param17.style + " | " + param17.placement + " | Depth: " + param17.depth + "cm");
        System.out.println("Param Pocket 18: " + param18.style + " | " + param18.placement + " | Depth: " + param18.depth + "cm");
        System.out.println("Param Pocket 19: " + param19.style + " | " + param19.placement + " | Depth: " + param19.depth + "cm");
        System.out.println("Param Pocket 20: " + param20.style + " | " + param20.placement + " | Depth: " + param20.depth + "cm");
        System.out.println("Param Pocket 21: " + param21.style + " | " + param21.placement + " | Depth: " + param21.depth + "cm");
        System.out.println("Param Pocket 22: " + param22.style + " | " + param22.placement + " | Depth: " + param22.depth + "cm");
        System.out.println("Param Pocket 23: " + param23.style + " | " + param23.placement + " | Depth: " + param23.depth + "cm");
        System.out.println("Param Pocket 24: " + param24.style + " | " + param24.placement + " | Depth: " + param24.depth + "cm");
        System.out.println("Param Pocket 25: " + param25.style + " | " + param25.placement + " | Depth: " + param25.depth + "cm");
    }
}
