
class RacketRunner {
    public static void main(String[] args) {
        
        // --- Default constructor ---
        
        Racket r1 = new Racket();
        r1.brand = "Wilson";
        r1.model = "Pro Staff";
        r1.weight = 315;
        r1.headSize = 97;
        r1.stringPattern = "16x19";
        r1.gripSize = 3;
        r1.balance = "Head Light";
        r1.stiffness = 68;
        r1.length = 27.0;
        r1.color = "Black";

        Racket r2 = new Racket();
        r2.brand = "Babolat";
        r2.model = "Pure Drive";
        r2.weight = 300;
        r2.headSize = 100;
        r2.stringPattern = "16x19";
        r2.gripSize = 2;
        r2.balance = "Even";
        r2.stiffness = 71;
        r2.length = 27.0;
        r2.color = "Blue";

        Racket r3 = new Racket();
        r3.brand = "Head";
        r3.model = "Speed Pro";
        r3.weight = 310;
        r3.headSize = 100;
        r3.stringPattern = "18x20";
        r3.gripSize = 4;
        r3.balance = "Head Light";
        r3.stiffness = 62;
        r3.length = 27.0;
        r3.color = "White/Black";

        Racket r4 = new Racket();
        r4.brand = "Yonex";
        r4.model = "EZONE";
        r4.weight = 285;
        r4.headSize = 98;
        r4.stringPattern = "16x19";
        r4.gripSize = 1;
        r4.balance = "Head Heavy";
        r4.stiffness = 65;
        r4.length = 27.0;
        r4.color = "Blue/Green";

        Racket r5 = new Racket();
        r5.brand = "Dunlop";
        r5.model = "CX 200";
        r5.weight = 305;
        r5.headSize = 98;
        r5.stringPattern = "16x19";
        r5.gripSize = 3;
        r5.balance = "Head Light";
        r5.stiffness = 64;
        r5.length = 27.0;
        r5.color = "Red/Black";

        Racket r6 = new Racket();
        r6.brand = "Prince";
        r6.model = "Phantom";
        r6.weight = 320;
        r6.headSize = 93;
        r6.stringPattern = "18x20";
        r6.gripSize = 4;
        r6.balance = "Head Light";
        r6.stiffness = 59;
        r6.length = 27.0;
        r6.color = "Green";

        Racket r7 = new Racket();
        r7.brand = "Tecnifibre";
        r7.model = "T-Fight";
        r7.weight = 305;
        r7.headSize = 98;
        r7.stringPattern = "18x19";
        r7.gripSize = 2;
        r7.balance = "Even";
        r7.stiffness = 67;
        r7.length = 27.0;
        r7.color = "White/Red/Blue";

        Racket r8 = new Racket();
        r8.brand = "Volkl";
        r8.model = "V-Cell 8";
        r8.weight = 300;
        r8.headSize = 100;
        r8.stringPattern = "16x18";
        r8.gripSize = 3;
        r8.balance = "Head Light";
        r8.stiffness = 68;
        r8.length = 27.0;
        r8.color = "Yellow";

        Racket r9 = new Racket();
        r9.brand = "ProKennex";
        r9.model = "Black Ace";
        r9.weight = 315;
        r9.headSize = 100;
        r9.stringPattern = "16x19";
        r9.gripSize = 3;
        r9.balance = "Head Light";
        r9.stiffness = 55;
        r9.length = 27.0;
        r9.color = "Black/Red";

        Racket r10 = new Racket();
        r10.brand = "Solinco";
        r10.model = "Whiteout";
        r10.weight = 305;
        r10.headSize = 98;
        r10.stringPattern = "16x19";
        r10.gripSize = 2;
        r10.balance = "Head Light";
        r10.stiffness = 65;
        r10.length = 27.0;
        r10.color = "White";

        Racket r11 = new Racket();
        r11.brand = "Wilson";
        r11.model = "Blade";
        r11.weight = 305;
        r11.headSize = 98;
        r11.stringPattern = "18x20";
        r11.gripSize = 3;
        r11.balance = "Head Light";
        r11.stiffness = 62;
        r11.length = 27.0;
        r11.color = "Green/Silver";

        Racket r12 = new Racket();
        r12.brand = "Babolat";
        r12.model = "Pure Aero";
        r12.weight = 300;
        r12.headSize = 100;
        r12.stringPattern = "16x19";
        r12.gripSize = 3;
        r12.balance = "Even";
        r12.stiffness = 67;
        r12.length = 27.0;
        r12.color = "Yellow/Black";

        Racket r13 = new Racket();
        r13.brand = "Head";
        r13.model = "Radical MP";
        r13.weight = 300;
        r13.headSize = 98;
        r13.stringPattern = "16x19";
        r13.gripSize = 2;
        r13.balance = "Head Light";
        r13.stiffness = 65;
        r13.length = 27.0;
        r13.color = "Orange";

        Racket r14 = new Racket();
        r14.brand = "Yonex";
        r14.model = "VCORE";
        r14.weight = 300;
        r14.headSize = 98;
        r14.stringPattern = "16x19";
        r14.gripSize = 3;
        r14.balance = "Head Light";
        r14.stiffness = 66;
        r14.length = 27.0;
        r14.color = "Red";

        Racket r15 = new Racket();
        r15.brand = "Dunlop";
        r15.model = "FX 500";
        r15.weight = 300;
        r15.headSize = 100;
        r15.stringPattern = "16x19";
        r15.gripSize = 4;
        r15.balance = "Even";
        r15.stiffness = 71;
        r15.length = 27.0;
        r15.color = "Blue/Black";

        Racket r16 = new Racket();
        r16.brand = "Prince";
        r16.model = "Textreme Tour";
        r16.weight = 310;
        r16.headSize = 95;
        r16.stringPattern = "16x19";
        r16.gripSize = 2;
        r16.balance = "Head Light";
        r16.stiffness = 60;
        r16.length = 27.0;
        r16.color = "White/Green";

        Racket r17 = new Racket();
        r17.brand = "Tecnifibre";
        r17.model = "TF40";
        r17.weight = 315;
        r17.headSize = 98;
        r17.stringPattern = "18x20";
        r17.gripSize = 3;
        r17.balance = "Head Light";
        r17.stiffness = 64;
        r17.length = 27.0;
        r17.color = "White/Black";

        Racket r18 = new Racket();
        r18.brand = "Volkl";
        r18.model = "V1 Classic";
        r18.weight = 285;
        r18.headSize = 102;
        r18.stringPattern = "16x19";
        r18.gripSize = 1;
        r18.balance = "Even";
        r18.stiffness = 68;
        r18.length = 27.0;
        r18.color = "Silver";

        Racket r19 = new Racket();
        r19.brand = "ProKennex";
        r19.model = "Ki Q+ Tour";
        r19.weight = 300;
        r19.headSize = 98;
        r19.stringPattern = "16x19";
        r19.gripSize = 4;
        r19.balance = "Head Light";
        r19.stiffness = 63;
        r19.length = 27.0;
        r19.color = "Green/Black";

        Racket r20 = new Racket();
        r20.brand = "Solinco";
        r20.model = "Blackout";
        r20.weight = 300;
        r20.headSize = 100;
        r20.stringPattern = "16x19";
        r20.gripSize = 3;
        r20.balance = "Head Light";
        r20.stiffness = 70;
        r20.length = 27.0;
        r20.color = "Black";

        Racket r21 = new Racket();
        r21.brand = "Slazenger";
        r21.model = "Pro Braided";
        r21.weight = 320;
        r21.headSize = 95;
        r21.stringPattern = "18x20";
        r21.gripSize = 3;
        r21.balance = "Head Light";
        r21.stiffness = 66;
        r21.length = 27.0;
        r21.color = "Black/White";

        Racket r22 = new Racket();
        r22.brand = "Donnay";
        r22.model = "Pro One";
        r22.weight = 310;
        r22.headSize = 97;
        r22.stringPattern = "16x19";
        r22.gripSize = 2;
        r22.balance = "Head Light";
        r22.stiffness = 58;
        r22.length = 27.0;
        r22.color = "Grey/Orange";

        Racket r23 = new Racket();
        r23.brand = "Snauwaert";
        r23.model = "Grinta";
        r23.weight = 295;
        r23.headSize = 100;
        r23.stringPattern = "16x18";
        r23.gripSize = 3;
        r23.balance = "Even";
        r23.stiffness = 64;
        r23.length = 27.0;
        r23.color = "Green/Yellow";

        Racket r24 = new Racket();
        r24.brand = "Pacific";
        r24.model = "X Force Pro";
        r24.weight = 320;
        r24.headSize = 98;
        r24.stringPattern = "16x20";
        r24.gripSize = 4;
        r24.balance = "Head Light";
        r24.stiffness = 62;
        r24.length = 27.0;
        r24.color = "Orange/Black";

        Racket r25 = new Racket();
        r25.brand = "Gamma";
        r25.model = "RZR";
        r25.weight = 300;
        r25.headSize = 100;
        r25.stringPattern = "16x18";
        r25.gripSize = 2;
        r25.balance = "Even";
        r25.stiffness = 72;
        r25.length = 27.0;
        r25.color = "Black/Yellow";

        System.out.println("Racket Details : " + r1.brand + " " + r1.model + " | Weight: " + r1.weight + "g | Color: " + r1.color);
        System.out.println("Racket Details : " + r2.brand + " " + r2.model + " | Weight: " + r2.weight + "g | Color: " + r2.color);
        System.out.println("Racket Details : " + r3.brand + " " + r3.model + " | Weight: " + r3.weight + "g | Color: " + r3.color);
        System.out.println("Racket Details : " + r4.brand + " " + r4.model + " | Weight: " + r4.weight + "g | Color: " + r4.color);
        System.out.println("Racket Details : " + r5.brand + " " + r5.model + " | Weight: " + r5.weight + "g | Color: " + r5.color);
        System.out.println("Racket Details : " + r6.brand + " " + r6.model + " | Weight: " + r6.weight + "g | Color: " + r6.color);
        System.out.println("Racket Details : " + r7.brand + " " + r7.model + " | Weight: " + r7.weight + "g | Color: " + r7.color);
        System.out.println("Racket Details : " + r8.brand + " " + r8.model + " | Weight: " + r8.weight + "g | Color: " + r8.color);
        System.out.println("Racket Details : " + r9.brand + " " + r9.model + " | Weight: " + r9.weight + "g | Color: " + r9.color);
        System.out.println("Racket Details : " + r10.brand + " " + r10.model + " | Weight: " + r10.weight + "g | Color: " + r10.color);
        System.out.println("Racket Details : " + r11.brand + " " + r11.model + " | Weight: " + r11.weight + "g | Color: " + r11.color);
        System.out.println("Racket Details : " + r12.brand + " " + r12.model + " | Weight: " + r12.weight + "g | Color: " + r12.color);
        System.out.println("Racket Details : " + r13.brand + " " + r13.model + " | Weight: " + r13.weight + "g | Color: " + r13.color);
        System.out.println("Racket Details : " + r14.brand + " " + r14.model + " | Weight: " + r14.weight + "g | Color: " + r14.color);
        System.out.println("Racket Details : " + r15.brand + " " + r15.model + " | Weight: " + r15.weight + "g | Color: " + r15.color);
        System.out.println("Racket Details : " + r16.brand + " " + r16.model + " | Weight: " + r16.weight + "g | Color: " + r16.color);
        System.out.println("Racket Details : " + r17.brand + " " + r17.model + " | Weight: " + r17.weight + "g | Color: " + r17.color);
        System.out.println("Racket Details : " + r18.brand + " " + r18.model + " | Weight: " + r18.weight + "g | Color: " + r18.color);
        System.out.println("Racket Details : " + r19.brand + " " + r19.model + " | Weight: " + r19.weight + "g | Color: " + r19.color);
        System.out.println("Racket Details : " + r20.brand + " " + r20.model + " | Weight: " + r20.weight + "g | Color: " + r20.color);
        System.out.println("Racket Details : " + r21.brand + " " + r21.model + " | Weight: " + r21.weight + "g | Color: " + r21.color);
        System.out.println("Racket Details : " + r22.brand + " " + r22.model + " | Weight: " + r22.weight + "g | Color: " + r22.color);
        System.out.println("Racket Details : " + r23.brand + " " + r23.model + " | Weight: " + r23.weight + "g | Color: " + r23.color);
        System.out.println("Racket Details : " + r24.brand + " " + r24.model + " | Weight: " + r24.weight + "g | Color: " + r24.color);
        System.out.println("Racket Details : " + r25.brand + " " + r25.model + " | Weight: " + r25.weight + "g | Color: " + r25.color);

        // --- Parameterized constructor ---
        Racket p1 = new Racket("Wilson", "Clash", 295, 100, "16x19", 3, "Head Light", 55, 27.0, "Red/Grey");
        Racket p2 = new Racket("Babolat", "Pure Strike", 305, 98, "16x19", 3, "Head Light", 66, 27.0, "White/Red");
        Racket p3 = new Racket("Head", "Extreme", 300, 100, "16x19", 2, "Even", 66, 27.0, "Yellow");
        Racket p4 = new Racket("Yonex", "VCORE Pro", 310, 97, "16x19", 3, "Head Light", 60, 27.0, "Green/Purple");
        Racket p5 = new Racket("Dunlop", "SX 300", 300, 100, "16x19", 4, "Even", 68, 27.0, "Yellow/Black");
        Racket p6 = new Racket("Prince", "Ripstick", 300, 100, "16x18", 2, "Even", 70, 27.0, "Yellow/Black");
        Racket p7 = new Racket("Tecnifibre", "T-Rebound", 270, 100, "16x19", 1, "Even", 65, 26.5, "White/Teal");
        Racket p8 = new Racket("Volkl", "V-Feel 9", 310, 100, "16x19", 3, "Head Light", 69, 27.0, "Black/Red");
        Racket p9 = new Racket("ProKennex", "Ki Q+ 5", 300, 100, "16x20", 3, "Head Light", 64, 27.0, "Blue");
        Racket p10 = new Racket("Solinco", "Shadow", 305, 98, "18x20", 3, "Head Light", 64, 27.0, "Black/Silver");
        Racket p11 = new Racket("Wilson", "Ultra", 300, 100, "16x19", 2, "Even", 73, 27.0, "Blue/Silver");
        Racket p12 = new Racket("Babolat", "AeroPro Drive", 300, 100, "16x19", 4, "Even", 69, 27.0, "Yellow");
        Racket p13 = new Racket("Head", "Gravity", 295, 104, "16x20", 2, "Head Light", 61, 27.0, "Teal/Red");
        Racket p14 = new Racket("Yonex", "Astrel", 270, 105, "16x18", 1, "Even", 68, 27.0, "Mint");
        Racket p15 = new Racket("Dunlop", "LX 800", 255, 110, "16x18", 2, "Head Heavy", 72, 27.5, "Silver");
        Racket p16 = new Racket("Prince", "Synergy", 305, 98, "18x18", 3, "Head Light", 60, 27.0, "Black");
        Racket p17 = new Racket("Tecnifibre", "Slash", 300, 100, "16x19", 3, "Even", 66, 27.0, "White/Green");
        Racket p18 = new Racket("Volkl", "C10 Pro", 330, 98, "16x19", 4, "Head Light", 64, 27.0, "Yellow/Black");
        Racket p19 = new Racket("ProKennex", "Kinetic", 295, 105, "16x19", 2, "Even", 68, 27.0, "Grey");
        Racket p20 = new Racket("Solinco", "Protocol", 300, 100, "16x19", 3, "Even", 67, 27.0, "Red");
        Racket p21 = new Racket("Slazenger", "Aero", 280, 100, "16x19", 2, "Even", 65, 27.0, "Black/Blue");
        Racket p22 = new Racket("Donnay", "X-Dual", 300, 99, "16x19", 3, "Head Light", 60, 27.0, "Black/Silver");
        Racket p23 = new Racket("Snauwaert", "Vitas", 305, 100, "16x19", 3, "Head Light", 65, 27.0, "Blue/Yellow");
        Racket p24 = new Racket("Pacific", "BXT X", 295, 100, "16x19", 2, "Even", 64, 27.0, "Orange");
        Racket p25 = new Racket("Gamma", "Bubba", 275, 117, "18x21", 3, "Head Heavy", 70, 27.5, "Black/Orange");

        System.out.println("Param Racket 1: " + p1.brand + " " + p1.model + " | Weight: " + p1.weight + "g | Color: " + p1.color);
        System.out.println("Param Racket 2: " + p2.brand + " " + p2.model + " | Weight: " + p2.weight + "g | Color: " + p2.color);
        System.out.println("Param Racket 3: " + p3.brand + " " + p3.model + " | Weight: " + p3.weight + "g | Color: " + p3.color);
        System.out.println("Param Racket 4: " + p4.brand + " " + p4.model + " | Weight: " + p4.weight + "g | Color: " + p4.color);
        System.out.println("Param Racket 5: " + p5.brand + " " + p5.model + " | Weight: " + p5.weight + "g | Color: " + p5.color);
        System.out.println("Param Racket 6: " + p6.brand + " " + p6.model + " | Weight: " + p6.weight + "g | Color: " + p6.color);
        System.out.println("Param Racket 7: " + p7.brand + " " + p7.model + " | Weight: " + p7.weight + "g | Color: " + p7.color);
        System.out.println("Param Racket 8: " + p8.brand + " " + p8.model + " | Weight: " + p8.weight + "g | Color: " + p8.color);
        System.out.println("Param Racket 9: " + p9.brand + " " + p9.model + " | Weight: " + p9.weight + "g | Color: " + p9.color);
        System.out.println("Param Racket 10: " + p10.brand + " " + p10.model + " | Weight: " + p10.weight + "g | Color: " + p10.color);
        System.out.println("Param Racket 11: " + p11.brand + " " + p11.model + " | Weight: " + p11.weight + "g | Color: " + p11.color);
        System.out.println("Param Racket 12: " + p12.brand + " " + p12.model + " | Weight: " + p12.weight + "g | Color: " + p12.color);
        System.out.println("Param Racket 13: " + p13.brand + " " + p13.model + " | Weight: " + p13.weight + "g | Color: " + p13.color);
        System.out.println("Param Racket 14: " + p14.brand + " " + p14.model + " | Weight: " + p14.weight + "g | Color: " + p14.color);
        System.out.println("Param Racket 15: " + p15.brand + " " + p15.model + " | Weight: " + p15.weight + "g | Color: " + p15.color);
        System.out.println("Param Racket 16: " + p16.brand + " " + p16.model + " | Weight: " + p16.weight + "g | Color: " + p16.color);
        System.out.println("Param Racket 17: " + p17.brand + " " + p17.model + " | Weight: " + p17.weight + "g | Color: " + p17.color);
        System.out.println("Param Racket 18: " + p18.brand + " " + p18.model + " | Weight: " + p18.weight + "g | Color: " + p18.color);
        System.out.println("Param Racket 19: " + p19.brand + " " + p19.model + " | Weight: " + p19.weight + "g | Color: " + p19.color);
        System.out.println("Param Racket 20: " + p20.brand + " " + p20.model + " | Weight: " + p20.weight + "g | Color: " + p20.color);
        System.out.println("Param Racket 21: " + p21.brand + " " + p21.model + " | Weight: " + p21.weight + "g | Color: " + p21.color);
        System.out.println("Param Racket 22: " + p22.brand + " " + p22.model + " | Weight: " + p22.weight + "g | Color: " + p22.color);
        System.out.println("Param Racket 23: " + p23.brand + " " + p23.model + " | Weight: " + p23.weight + "g | Color: " + p23.color);
        System.out.println("Param Racket 24: " + p24.brand + " " + p24.model + " | Weight: " + p24.weight + "g | Color: " + p24.color);
        System.out.println("Param Racket 25: " + p25.brand + " " + p25.model + " | Weight: " + p25.weight + "g | Color: " + p25.color);
    }
}
