class SkateBoardExecutor {

    public static void main(String[] args) {

        SkateBoard board1 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board1.boardBrand);
        System.out.println("The boardId is : " + board1.boardId);
        System.out.println("The boardPrice is : " + board1.boardPrice);
        System.out.println("The isAvailable is : " + board1.isAvailable);
        System.out.println("The boardType is : " + board1.boardType);
        System.out.println("The deckLength is : " + board1.deckLength);
        System.out.println("The weight is : " + board1.weight);
        System.out.println("The isElectric is : " + board1.isElectric);
        System.out.println("The material is : " + board1.material);
        System.out.println("The warrantyYears is : " + board1.warrantyYears);
        System.out.println("The wheelSize is : " + board1.wheelSize);
        System.out.println("The hasGripTape is : " + board1.hasGripTape);
        System.out.println("The color is : " + board1.color);
        System.out.println("The stockQuantity is : " + board1.stockQuantity);
        System.out.println("The deckWidth is : " + board1.deckWidth);
        System.out.println("The isEcoFriendly is : " + board1.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board1.wheelMaterial);
        System.out.println("The rating is : " + board1.rating);
        System.out.println("The maxLoad is : " + board1.maxLoad);
        System.out.println("The isCertified is : " + board1.isCertified);
        System.out.println("The countryOfOrigin is : " + board1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board1.manufacturingYear);
        System.out.println("The bearingType is : " + board1.bearingType);
        System.out.println("The isFoldable is : " + board1.isFoldable);
        System.out.println("The certificationType is : " + board1.certificationType);

        board1.boardBrand = "ProSkate";
        board1.boardId = 1;
        board1.boardPrice = 100.75;
        board1.isAvailable = true;
        board1.boardType = "Street";
        board1.deckLength = 31.5;
        board1.weight = 2.8;
        board1.isElectric = false;
        board1.material = "Maple Wood";
        board1.warrantyYears = 1;
        board1.wheelSize = 52.0;
        board1.hasGripTape = true;
        board1.color = "Black";
        board1.stockQuantity = 20;
        board1.deckWidth = 8.0;
        board1.isEcoFriendly = true;
        board1.wheelMaterial = "Polyurethane";
        board1.rating = 4;
        board1.maxLoad = 100.0;
        board1.isCertified = true;
        board1.countryOfOrigin = "USA";
        board1.manufacturingYear = 2025;
        board1.bearingType = "ABEC-7";
        board1.isFoldable = false;
        board1.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board1.boardBrand);
        System.out.println("The boardId is : " + board1.boardId);
        System.out.println("The boardPrice is : " + board1.boardPrice);
        System.out.println("The isAvailable is : " + board1.isAvailable);
        System.out.println("The boardType is : " + board1.boardType);
        System.out.println("The deckLength is : " + board1.deckLength);
        System.out.println("The weight is : " + board1.weight);
        System.out.println("The isElectric is : " + board1.isElectric);
        System.out.println("The material is : " + board1.material);
        System.out.println("The warrantyYears is : " + board1.warrantyYears);
        System.out.println("The wheelSize is : " + board1.wheelSize);
        System.out.println("The hasGripTape is : " + board1.hasGripTape);
        System.out.println("The color is : " + board1.color);
        System.out.println("The stockQuantity is : " + board1.stockQuantity);
        System.out.println("The deckWidth is : " + board1.deckWidth);
        System.out.println("The isEcoFriendly is : " + board1.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board1.wheelMaterial);
        System.out.println("The rating is : " + board1.rating);
        System.out.println("The maxLoad is : " + board1.maxLoad);
        System.out.println("The isCertified is : " + board1.isCertified);
        System.out.println("The countryOfOrigin is : " + board1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board1.manufacturingYear);
        System.out.println("The bearingType is : " + board1.bearingType);
        System.out.println("The isFoldable is : " + board1.isFoldable);
        System.out.println("The certificationType is : " + board1.certificationType);


        SkateBoard board2 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board2.boardBrand);
        System.out.println("The boardId is : " + board2.boardId);
        System.out.println("The boardPrice is : " + board2.boardPrice);
        System.out.println("The isAvailable is : " + board2.isAvailable);
        System.out.println("The boardType is : " + board2.boardType);
        System.out.println("The deckLength is : " + board2.deckLength);
        System.out.println("The weight is : " + board2.weight);
        System.out.println("The isElectric is : " + board2.isElectric);
        System.out.println("The material is : " + board2.material);
        System.out.println("The warrantyYears is : " + board2.warrantyYears);
        System.out.println("The wheelSize is : " + board2.wheelSize);
        System.out.println("The hasGripTape is : " + board2.hasGripTape);
        System.out.println("The color is : " + board2.color);
        System.out.println("The stockQuantity is : " + board2.stockQuantity);
        System.out.println("The deckWidth is : " + board2.deckWidth);
        System.out.println("The isEcoFriendly is : " + board2.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board2.wheelMaterial);
        System.out.println("The rating is : " + board2.rating);
        System.out.println("The maxLoad is : " + board2.maxLoad);
        System.out.println("The isCertified is : " + board2.isCertified);
        System.out.println("The countryOfOrigin is : " + board2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board2.manufacturingYear);
        System.out.println("The bearingType is : " + board2.bearingType);
        System.out.println("The isFoldable is : " + board2.isFoldable);
        System.out.println("The certificationType is : " + board2.certificationType);

        board2.boardBrand = "ProSkate";
        board2.boardId = 2;
        board2.boardPrice = 200.75;
        board2.isAvailable = true;
        board2.boardType = "Street";
        board2.deckLength = 31.5;
        board2.weight = 2.8;
        board2.isElectric = false;
        board2.material = "Maple Wood";
        board2.warrantyYears = 1;
        board2.wheelSize = 52.0;
        board2.hasGripTape = true;
        board2.color = "Black";
        board2.stockQuantity = 20;
        board2.deckWidth = 8.0;
        board2.isEcoFriendly = true;
        board2.wheelMaterial = "Polyurethane";
        board2.rating = 4;
        board2.maxLoad = 100.0;
        board2.isCertified = true;
        board2.countryOfOrigin = "USA";
        board2.manufacturingYear = 2025;
        board2.bearingType = "ABEC-7";
        board2.isFoldable = false;
        board2.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board2.boardBrand);
        System.out.println("The boardId is : " + board2.boardId);
        System.out.println("The boardPrice is : " + board2.boardPrice);
        System.out.println("The isAvailable is : " + board2.isAvailable);
        System.out.println("The boardType is : " + board2.boardType);
        System.out.println("The deckLength is : " + board2.deckLength);
        System.out.println("The weight is : " + board2.weight);
        System.out.println("The isElectric is : " + board2.isElectric);
        System.out.println("The material is : " + board2.material);
        System.out.println("The warrantyYears is : " + board2.warrantyYears);
        System.out.println("The wheelSize is : " + board2.wheelSize);
        System.out.println("The hasGripTape is : " + board2.hasGripTape);
        System.out.println("The color is : " + board2.color);
        System.out.println("The stockQuantity is : " + board2.stockQuantity);
        System.out.println("The deckWidth is : " + board2.deckWidth);
        System.out.println("The isEcoFriendly is : " + board2.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board2.wheelMaterial);
        System.out.println("The rating is : " + board2.rating);
        System.out.println("The maxLoad is : " + board2.maxLoad);
        System.out.println("The isCertified is : " + board2.isCertified);
        System.out.println("The countryOfOrigin is : " + board2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board2.manufacturingYear);
        System.out.println("The bearingType is : " + board2.bearingType);
        System.out.println("The isFoldable is : " + board2.isFoldable);
        System.out.println("The certificationType is : " + board2.certificationType);


        SkateBoard board3 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board3.boardBrand);
        System.out.println("The boardId is : " + board3.boardId);
        System.out.println("The boardPrice is : " + board3.boardPrice);
        System.out.println("The isAvailable is : " + board3.isAvailable);
        System.out.println("The boardType is : " + board3.boardType);
        System.out.println("The deckLength is : " + board3.deckLength);
        System.out.println("The weight is : " + board3.weight);
        System.out.println("The isElectric is : " + board3.isElectric);
        System.out.println("The material is : " + board3.material);
        System.out.println("The warrantyYears is : " + board3.warrantyYears);
        System.out.println("The wheelSize is : " + board3.wheelSize);
        System.out.println("The hasGripTape is : " + board3.hasGripTape);
        System.out.println("The color is : " + board3.color);
        System.out.println("The stockQuantity is : " + board3.stockQuantity);
        System.out.println("The deckWidth is : " + board3.deckWidth);
        System.out.println("The isEcoFriendly is : " + board3.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board3.wheelMaterial);
        System.out.println("The rating is : " + board3.rating);
        System.out.println("The maxLoad is : " + board3.maxLoad);
        System.out.println("The isCertified is : " + board3.isCertified);
        System.out.println("The countryOfOrigin is : " + board3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board3.manufacturingYear);
        System.out.println("The bearingType is : " + board3.bearingType);
        System.out.println("The isFoldable is : " + board3.isFoldable);
        System.out.println("The certificationType is : " + board3.certificationType);

        board3.boardBrand = "ProSkate";
        board3.boardId = 3;
        board3.boardPrice = 300.75;
        board3.isAvailable = true;
        board3.boardType = "Street";
        board3.deckLength = 31.5;
        board3.weight = 2.8;
        board3.isElectric = false;
        board3.material = "Maple Wood";
        board3.warrantyYears = 1;
        board3.wheelSize = 52.0;
        board3.hasGripTape = true;
        board3.color = "Black";
        board3.stockQuantity = 20;
        board3.deckWidth = 8.0;
        board3.isEcoFriendly = true;
        board3.wheelMaterial = "Polyurethane";
        board3.rating = 4;
        board3.maxLoad = 100.0;
        board3.isCertified = true;
        board3.countryOfOrigin = "USA";
        board3.manufacturingYear = 2025;
        board3.bearingType = "ABEC-7";
        board3.isFoldable = false;
        board3.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board3.boardBrand);
        System.out.println("The boardId is : " + board3.boardId);
        System.out.println("The boardPrice is : " + board3.boardPrice);
        System.out.println("The isAvailable is : " + board3.isAvailable);
        System.out.println("The boardType is : " + board3.boardType);
        System.out.println("The deckLength is : " + board3.deckLength);
        System.out.println("The weight is : " + board3.weight);
        System.out.println("The isElectric is : " + board3.isElectric);
        System.out.println("The material is : " + board3.material);
        System.out.println("The warrantyYears is : " + board3.warrantyYears);
        System.out.println("The wheelSize is : " + board3.wheelSize);
        System.out.println("The hasGripTape is : " + board3.hasGripTape);
        System.out.println("The color is : " + board3.color);
        System.out.println("The stockQuantity is : " + board3.stockQuantity);
        System.out.println("The deckWidth is : " + board3.deckWidth);
        System.out.println("The isEcoFriendly is : " + board3.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board3.wheelMaterial);
        System.out.println("The rating is : " + board3.rating);
        System.out.println("The maxLoad is : " + board3.maxLoad);
        System.out.println("The isCertified is : " + board3.isCertified);
        System.out.println("The countryOfOrigin is : " + board3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board3.manufacturingYear);
        System.out.println("The bearingType is : " + board3.bearingType);
        System.out.println("The isFoldable is : " + board3.isFoldable);
        System.out.println("The certificationType is : " + board3.certificationType);


        SkateBoard board4 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board4.boardBrand);
        System.out.println("The boardId is : " + board4.boardId);
        System.out.println("The boardPrice is : " + board4.boardPrice);
        System.out.println("The isAvailable is : " + board4.isAvailable);
        System.out.println("The boardType is : " + board4.boardType);
        System.out.println("The deckLength is : " + board4.deckLength);
        System.out.println("The weight is : " + board4.weight);
        System.out.println("The isElectric is : " + board4.isElectric);
        System.out.println("The material is : " + board4.material);
        System.out.println("The warrantyYears is : " + board4.warrantyYears);
        System.out.println("The wheelSize is : " + board4.wheelSize);
        System.out.println("The hasGripTape is : " + board4.hasGripTape);
        System.out.println("The color is : " + board4.color);
        System.out.println("The stockQuantity is : " + board4.stockQuantity);
        System.out.println("The deckWidth is : " + board4.deckWidth);
        System.out.println("The isEcoFriendly is : " + board4.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board4.wheelMaterial);
        System.out.println("The rating is : " + board4.rating);
        System.out.println("The maxLoad is : " + board4.maxLoad);
        System.out.println("The isCertified is : " + board4.isCertified);
        System.out.println("The countryOfOrigin is : " + board4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board4.manufacturingYear);
        System.out.println("The bearingType is : " + board4.bearingType);
        System.out.println("The isFoldable is : " + board4.isFoldable);
        System.out.println("The certificationType is : " + board4.certificationType);

        board4.boardBrand = "ProSkate";
        board4.boardId = 4;
        board4.boardPrice = 400.75;
        board4.isAvailable = true;
        board4.boardType = "Street";
        board4.deckLength = 31.5;
        board4.weight = 2.8;
        board4.isElectric = false;
        board4.material = "Maple Wood";
        board4.warrantyYears = 1;
        board4.wheelSize = 52.0;
        board4.hasGripTape = true;
        board4.color = "Black";
        board4.stockQuantity = 20;
        board4.deckWidth = 8.0;
        board4.isEcoFriendly = true;
        board4.wheelMaterial = "Polyurethane";
        board4.rating = 4;
        board4.maxLoad = 100.0;
        board4.isCertified = true;
        board4.countryOfOrigin = "USA";
        board4.manufacturingYear = 2025;
        board4.bearingType = "ABEC-7";
        board4.isFoldable = false;
        board4.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board4.boardBrand);
        System.out.println("The boardId is : " + board4.boardId);
        System.out.println("The boardPrice is : " + board4.boardPrice);
        System.out.println("The isAvailable is : " + board4.isAvailable);
        System.out.println("The boardType is : " + board4.boardType);
        System.out.println("The deckLength is : " + board4.deckLength);
        System.out.println("The weight is : " + board4.weight);
        System.out.println("The isElectric is : " + board4.isElectric);
        System.out.println("The material is : " + board4.material);
        System.out.println("The warrantyYears is : " + board4.warrantyYears);
        System.out.println("The wheelSize is : " + board4.wheelSize);
        System.out.println("The hasGripTape is : " + board4.hasGripTape);
        System.out.println("The color is : " + board4.color);
        System.out.println("The stockQuantity is : " + board4.stockQuantity);
        System.out.println("The deckWidth is : " + board4.deckWidth);
        System.out.println("The isEcoFriendly is : " + board4.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board4.wheelMaterial);
        System.out.println("The rating is : " + board4.rating);
        System.out.println("The maxLoad is : " + board4.maxLoad);
        System.out.println("The isCertified is : " + board4.isCertified);
        System.out.println("The countryOfOrigin is : " + board4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board4.manufacturingYear);
        System.out.println("The bearingType is : " + board4.bearingType);
        System.out.println("The isFoldable is : " + board4.isFoldable);
        System.out.println("The certificationType is : " + board4.certificationType);


        SkateBoard board5 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board5.boardBrand);
        System.out.println("The boardId is : " + board5.boardId);
        System.out.println("The boardPrice is : " + board5.boardPrice);
        System.out.println("The isAvailable is : " + board5.isAvailable);
        System.out.println("The boardType is : " + board5.boardType);
        System.out.println("The deckLength is : " + board5.deckLength);
        System.out.println("The weight is : " + board5.weight);
        System.out.println("The isElectric is : " + board5.isElectric);
        System.out.println("The material is : " + board5.material);
        System.out.println("The warrantyYears is : " + board5.warrantyYears);
        System.out.println("The wheelSize is : " + board5.wheelSize);
        System.out.println("The hasGripTape is : " + board5.hasGripTape);
        System.out.println("The color is : " + board5.color);
        System.out.println("The stockQuantity is : " + board5.stockQuantity);
        System.out.println("The deckWidth is : " + board5.deckWidth);
        System.out.println("The isEcoFriendly is : " + board5.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board5.wheelMaterial);
        System.out.println("The rating is : " + board5.rating);
        System.out.println("The maxLoad is : " + board5.maxLoad);
        System.out.println("The isCertified is : " + board5.isCertified);
        System.out.println("The countryOfOrigin is : " + board5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board5.manufacturingYear);
        System.out.println("The bearingType is : " + board5.bearingType);
        System.out.println("The isFoldable is : " + board5.isFoldable);
        System.out.println("The certificationType is : " + board5.certificationType);

        board5.boardBrand = "ProSkate";
        board5.boardId = 5;
        board5.boardPrice = 500.75;
        board5.isAvailable = true;
        board5.boardType = "Street";
        board5.deckLength = 31.5;
        board5.weight = 2.8;
        board5.isElectric = false;
        board5.material = "Maple Wood";
        board5.warrantyYears = 1;
        board5.wheelSize = 52.0;
        board5.hasGripTape = true;
        board5.color = "Black";
        board5.stockQuantity = 20;
        board5.deckWidth = 8.0;
        board5.isEcoFriendly = true;
        board5.wheelMaterial = "Polyurethane";
        board5.rating = 4;
        board5.maxLoad = 100.0;
        board5.isCertified = true;
        board5.countryOfOrigin = "USA";
        board5.manufacturingYear = 2025;
        board5.bearingType = "ABEC-7";
        board5.isFoldable = false;
        board5.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board5.boardBrand);
        System.out.println("The boardId is : " + board5.boardId);
        System.out.println("The boardPrice is : " + board5.boardPrice);
        System.out.println("The isAvailable is : " + board5.isAvailable);
        System.out.println("The boardType is : " + board5.boardType);
        System.out.println("The deckLength is : " + board5.deckLength);
        System.out.println("The weight is : " + board5.weight);
        System.out.println("The isElectric is : " + board5.isElectric);
        System.out.println("The material is : " + board5.material);
        System.out.println("The warrantyYears is : " + board5.warrantyYears);
        System.out.println("The wheelSize is : " + board5.wheelSize);
        System.out.println("The hasGripTape is : " + board5.hasGripTape);
        System.out.println("The color is : " + board5.color);
        System.out.println("The stockQuantity is : " + board5.stockQuantity);
        System.out.println("The deckWidth is : " + board5.deckWidth);
        System.out.println("The isEcoFriendly is : " + board5.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board5.wheelMaterial);
        System.out.println("The rating is : " + board5.rating);
        System.out.println("The maxLoad is : " + board5.maxLoad);
        System.out.println("The isCertified is : " + board5.isCertified);
        System.out.println("The countryOfOrigin is : " + board5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board5.manufacturingYear);
        System.out.println("The bearingType is : " + board5.bearingType);
        System.out.println("The isFoldable is : " + board5.isFoldable);
        System.out.println("The certificationType is : " + board5.certificationType);


        SkateBoard board6 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board6.boardBrand);
        System.out.println("The boardId is : " + board6.boardId);
        System.out.println("The boardPrice is : " + board6.boardPrice);
        System.out.println("The isAvailable is : " + board6.isAvailable);
        System.out.println("The boardType is : " + board6.boardType);
        System.out.println("The deckLength is : " + board6.deckLength);
        System.out.println("The weight is : " + board6.weight);
        System.out.println("The isElectric is : " + board6.isElectric);
        System.out.println("The material is : " + board6.material);
        System.out.println("The warrantyYears is : " + board6.warrantyYears);
        System.out.println("The wheelSize is : " + board6.wheelSize);
        System.out.println("The hasGripTape is : " + board6.hasGripTape);
        System.out.println("The color is : " + board6.color);
        System.out.println("The stockQuantity is : " + board6.stockQuantity);
        System.out.println("The deckWidth is : " + board6.deckWidth);
        System.out.println("The isEcoFriendly is : " + board6.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board6.wheelMaterial);
        System.out.println("The rating is : " + board6.rating);
        System.out.println("The maxLoad is : " + board6.maxLoad);
        System.out.println("The isCertified is : " + board6.isCertified);
        System.out.println("The countryOfOrigin is : " + board6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board6.manufacturingYear);
        System.out.println("The bearingType is : " + board6.bearingType);
        System.out.println("The isFoldable is : " + board6.isFoldable);
        System.out.println("The certificationType is : " + board6.certificationType);

        board6.boardBrand = "ProSkate";
        board6.boardId = 6;
        board6.boardPrice = 600.75;
        board6.isAvailable = true;
        board6.boardType = "Street";
        board6.deckLength = 31.5;
        board6.weight = 2.8;
        board6.isElectric = false;
        board6.material = "Maple Wood";
        board6.warrantyYears = 1;
        board6.wheelSize = 52.0;
        board6.hasGripTape = true;
        board6.color = "Black";
        board6.stockQuantity = 20;
        board6.deckWidth = 8.0;
        board6.isEcoFriendly = true;
        board6.wheelMaterial = "Polyurethane";
        board6.rating = 4;
        board6.maxLoad = 100.0;
        board6.isCertified = true;
        board6.countryOfOrigin = "USA";
        board6.manufacturingYear = 2025;
        board6.bearingType = "ABEC-7";
        board6.isFoldable = false;
        board6.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board6.boardBrand);
        System.out.println("The boardId is : " + board6.boardId);
        System.out.println("The boardPrice is : " + board6.boardPrice);
        System.out.println("The isAvailable is : " + board6.isAvailable);
        System.out.println("The boardType is : " + board6.boardType);
        System.out.println("The deckLength is : " + board6.deckLength);
        System.out.println("The weight is : " + board6.weight);
        System.out.println("The isElectric is : " + board6.isElectric);
        System.out.println("The material is : " + board6.material);
        System.out.println("The warrantyYears is : " + board6.warrantyYears);
        System.out.println("The wheelSize is : " + board6.wheelSize);
        System.out.println("The hasGripTape is : " + board6.hasGripTape);
        System.out.println("The color is : " + board6.color);
        System.out.println("The stockQuantity is : " + board6.stockQuantity);
        System.out.println("The deckWidth is : " + board6.deckWidth);
        System.out.println("The isEcoFriendly is : " + board6.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board6.wheelMaterial);
        System.out.println("The rating is : " + board6.rating);
        System.out.println("The maxLoad is : " + board6.maxLoad);
        System.out.println("The isCertified is : " + board6.isCertified);
        System.out.println("The countryOfOrigin is : " + board6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board6.manufacturingYear);
        System.out.println("The bearingType is : " + board6.bearingType);
        System.out.println("The isFoldable is : " + board6.isFoldable);
        System.out.println("The certificationType is : " + board6.certificationType);


        SkateBoard board7 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board7.boardBrand);
        System.out.println("The boardId is : " + board7.boardId);
        System.out.println("The boardPrice is : " + board7.boardPrice);
        System.out.println("The isAvailable is : " + board7.isAvailable);
        System.out.println("The boardType is : " + board7.boardType);
        System.out.println("The deckLength is : " + board7.deckLength);
        System.out.println("The weight is : " + board7.weight);
        System.out.println("The isElectric is : " + board7.isElectric);
        System.out.println("The material is : " + board7.material);
        System.out.println("The warrantyYears is : " + board7.warrantyYears);
        System.out.println("The wheelSize is : " + board7.wheelSize);
        System.out.println("The hasGripTape is : " + board7.hasGripTape);
        System.out.println("The color is : " + board7.color);
        System.out.println("The stockQuantity is : " + board7.stockQuantity);
        System.out.println("The deckWidth is : " + board7.deckWidth);
        System.out.println("The isEcoFriendly is : " + board7.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board7.wheelMaterial);
        System.out.println("The rating is : " + board7.rating);
        System.out.println("The maxLoad is : " + board7.maxLoad);
        System.out.println("The isCertified is : " + board7.isCertified);
        System.out.println("The countryOfOrigin is : " + board7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board7.manufacturingYear);
        System.out.println("The bearingType is : " + board7.bearingType);
        System.out.println("The isFoldable is : " + board7.isFoldable);
        System.out.println("The certificationType is : " + board7.certificationType);

        board7.boardBrand = "ProSkate";
        board7.boardId = 7;
        board7.boardPrice = 700.75;
        board7.isAvailable = true;
        board7.boardType = "Street";
        board7.deckLength = 31.5;
        board7.weight = 2.8;
        board7.isElectric = false;
        board7.material = "Maple Wood";
        board7.warrantyYears = 1;
        board7.wheelSize = 52.0;
        board7.hasGripTape = true;
        board7.color = "Black";
        board7.stockQuantity = 20;
        board7.deckWidth = 8.0;
        board7.isEcoFriendly = true;
        board7.wheelMaterial = "Polyurethane";
        board7.rating = 4;
        board7.maxLoad = 100.0;
        board7.isCertified = true;
        board7.countryOfOrigin = "USA";
        board7.manufacturingYear = 2025;
        board7.bearingType = "ABEC-7";
        board7.isFoldable = false;
        board7.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board7.boardBrand);
        System.out.println("The boardId is : " + board7.boardId);
        System.out.println("The boardPrice is : " + board7.boardPrice);
        System.out.println("The isAvailable is : " + board7.isAvailable);
        System.out.println("The boardType is : " + board7.boardType);
        System.out.println("The deckLength is : " + board7.deckLength);
        System.out.println("The weight is : " + board7.weight);
        System.out.println("The isElectric is : " + board7.isElectric);
        System.out.println("The material is : " + board7.material);
        System.out.println("The warrantyYears is : " + board7.warrantyYears);
        System.out.println("The wheelSize is : " + board7.wheelSize);
        System.out.println("The hasGripTape is : " + board7.hasGripTape);
        System.out.println("The color is : " + board7.color);
        System.out.println("The stockQuantity is : " + board7.stockQuantity);
        System.out.println("The deckWidth is : " + board7.deckWidth);
        System.out.println("The isEcoFriendly is : " + board7.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board7.wheelMaterial);
        System.out.println("The rating is : " + board7.rating);
        System.out.println("The maxLoad is : " + board7.maxLoad);
        System.out.println("The isCertified is : " + board7.isCertified);
        System.out.println("The countryOfOrigin is : " + board7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board7.manufacturingYear);
        System.out.println("The bearingType is : " + board7.bearingType);
        System.out.println("The isFoldable is : " + board7.isFoldable);
        System.out.println("The certificationType is : " + board7.certificationType);


        SkateBoard board8 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board8.boardBrand);
        System.out.println("The boardId is : " + board8.boardId);
        System.out.println("The boardPrice is : " + board8.boardPrice);
        System.out.println("The isAvailable is : " + board8.isAvailable);
        System.out.println("The boardType is : " + board8.boardType);
        System.out.println("The deckLength is : " + board8.deckLength);
        System.out.println("The weight is : " + board8.weight);
        System.out.println("The isElectric is : " + board8.isElectric);
        System.out.println("The material is : " + board8.material);
        System.out.println("The warrantyYears is : " + board8.warrantyYears);
        System.out.println("The wheelSize is : " + board8.wheelSize);
        System.out.println("The hasGripTape is : " + board8.hasGripTape);
        System.out.println("The color is : " + board8.color);
        System.out.println("The stockQuantity is : " + board8.stockQuantity);
        System.out.println("The deckWidth is : " + board8.deckWidth);
        System.out.println("The isEcoFriendly is : " + board8.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board8.wheelMaterial);
        System.out.println("The rating is : " + board8.rating);
        System.out.println("The maxLoad is : " + board8.maxLoad);
        System.out.println("The isCertified is : " + board8.isCertified);
        System.out.println("The countryOfOrigin is : " + board8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board8.manufacturingYear);
        System.out.println("The bearingType is : " + board8.bearingType);
        System.out.println("The isFoldable is : " + board8.isFoldable);
        System.out.println("The certificationType is : " + board8.certificationType);

        board8.boardBrand = "ProSkate";
        board8.boardId = 8;
        board8.boardPrice = 800.75;
        board8.isAvailable = true;
        board8.boardType = "Street";
        board8.deckLength = 31.5;
        board8.weight = 2.8;
        board8.isElectric = false;
        board8.material = "Maple Wood";
        board8.warrantyYears = 1;
        board8.wheelSize = 52.0;
        board8.hasGripTape = true;
        board8.color = "Black";
        board8.stockQuantity = 20;
        board8.deckWidth = 8.0;
        board8.isEcoFriendly = true;
        board8.wheelMaterial = "Polyurethane";
        board8.rating = 4;
        board8.maxLoad = 100.0;
        board8.isCertified = true;
        board8.countryOfOrigin = "USA";
        board8.manufacturingYear = 2025;
        board8.bearingType = "ABEC-7";
        board8.isFoldable = false;
        board8.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board8.boardBrand);
        System.out.println("The boardId is : " + board8.boardId);
        System.out.println("The boardPrice is : " + board8.boardPrice);
        System.out.println("The isAvailable is : " + board8.isAvailable);
        System.out.println("The boardType is : " + board8.boardType);
        System.out.println("The deckLength is : " + board8.deckLength);
        System.out.println("The weight is : " + board8.weight);
        System.out.println("The isElectric is : " + board8.isElectric);
        System.out.println("The material is : " + board8.material);
        System.out.println("The warrantyYears is : " + board8.warrantyYears);
        System.out.println("The wheelSize is : " + board8.wheelSize);
        System.out.println("The hasGripTape is : " + board8.hasGripTape);
        System.out.println("The color is : " + board8.color);
        System.out.println("The stockQuantity is : " + board8.stockQuantity);
        System.out.println("The deckWidth is : " + board8.deckWidth);
        System.out.println("The isEcoFriendly is : " + board8.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board8.wheelMaterial);
        System.out.println("The rating is : " + board8.rating);
        System.out.println("The maxLoad is : " + board8.maxLoad);
        System.out.println("The isCertified is : " + board8.isCertified);
        System.out.println("The countryOfOrigin is : " + board8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board8.manufacturingYear);
        System.out.println("The bearingType is : " + board8.bearingType);
        System.out.println("The isFoldable is : " + board8.isFoldable);
        System.out.println("The certificationType is : " + board8.certificationType);


        SkateBoard board9 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board9.boardBrand);
        System.out.println("The boardId is : " + board9.boardId);
        System.out.println("The boardPrice is : " + board9.boardPrice);
        System.out.println("The isAvailable is : " + board9.isAvailable);
        System.out.println("The boardType is : " + board9.boardType);
        System.out.println("The deckLength is : " + board9.deckLength);
        System.out.println("The weight is : " + board9.weight);
        System.out.println("The isElectric is : " + board9.isElectric);
        System.out.println("The material is : " + board9.material);
        System.out.println("The warrantyYears is : " + board9.warrantyYears);
        System.out.println("The wheelSize is : " + board9.wheelSize);
        System.out.println("The hasGripTape is : " + board9.hasGripTape);
        System.out.println("The color is : " + board9.color);
        System.out.println("The stockQuantity is : " + board9.stockQuantity);
        System.out.println("The deckWidth is : " + board9.deckWidth);
        System.out.println("The isEcoFriendly is : " + board9.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board9.wheelMaterial);
        System.out.println("The rating is : " + board9.rating);
        System.out.println("The maxLoad is : " + board9.maxLoad);
        System.out.println("The isCertified is : " + board9.isCertified);
        System.out.println("The countryOfOrigin is : " + board9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board9.manufacturingYear);
        System.out.println("The bearingType is : " + board9.bearingType);
        System.out.println("The isFoldable is : " + board9.isFoldable);
        System.out.println("The certificationType is : " + board9.certificationType);

        board9.boardBrand = "ProSkate";
        board9.boardId = 9;
        board9.boardPrice = 900.75;
        board9.isAvailable = true;
        board9.boardType = "Street";
        board9.deckLength = 31.5;
        board9.weight = 2.8;
        board9.isElectric = false;
        board9.material = "Maple Wood";
        board9.warrantyYears = 1;
        board9.wheelSize = 52.0;
        board9.hasGripTape = true;
        board9.color = "Black";
        board9.stockQuantity = 20;
        board9.deckWidth = 8.0;
        board9.isEcoFriendly = true;
        board9.wheelMaterial = "Polyurethane";
        board9.rating = 4;
        board9.maxLoad = 100.0;
        board9.isCertified = true;
        board9.countryOfOrigin = "USA";
        board9.manufacturingYear = 2025;
        board9.bearingType = "ABEC-7";
        board9.isFoldable = false;
        board9.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board9.boardBrand);
        System.out.println("The boardId is : " + board9.boardId);
        System.out.println("The boardPrice is : " + board9.boardPrice);
        System.out.println("The isAvailable is : " + board9.isAvailable);
        System.out.println("The boardType is : " + board9.boardType);
        System.out.println("The deckLength is : " + board9.deckLength);
        System.out.println("The weight is : " + board9.weight);
        System.out.println("The isElectric is : " + board9.isElectric);
        System.out.println("The material is : " + board9.material);
        System.out.println("The warrantyYears is : " + board9.warrantyYears);
        System.out.println("The wheelSize is : " + board9.wheelSize);
        System.out.println("The hasGripTape is : " + board9.hasGripTape);
        System.out.println("The color is : " + board9.color);
        System.out.println("The stockQuantity is : " + board9.stockQuantity);
        System.out.println("The deckWidth is : " + board9.deckWidth);
        System.out.println("The isEcoFriendly is : " + board9.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board9.wheelMaterial);
        System.out.println("The rating is : " + board9.rating);
        System.out.println("The maxLoad is : " + board9.maxLoad);
        System.out.println("The isCertified is : " + board9.isCertified);
        System.out.println("The countryOfOrigin is : " + board9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board9.manufacturingYear);
        System.out.println("The bearingType is : " + board9.bearingType);
        System.out.println("The isFoldable is : " + board9.isFoldable);
        System.out.println("The certificationType is : " + board9.certificationType);


        SkateBoard board10 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board10.boardBrand);
        System.out.println("The boardId is : " + board10.boardId);
        System.out.println("The boardPrice is : " + board10.boardPrice);
        System.out.println("The isAvailable is : " + board10.isAvailable);
        System.out.println("The boardType is : " + board10.boardType);
        System.out.println("The deckLength is : " + board10.deckLength);
        System.out.println("The weight is : " + board10.weight);
        System.out.println("The isElectric is : " + board10.isElectric);
        System.out.println("The material is : " + board10.material);
        System.out.println("The warrantyYears is : " + board10.warrantyYears);
        System.out.println("The wheelSize is : " + board10.wheelSize);
        System.out.println("The hasGripTape is : " + board10.hasGripTape);
        System.out.println("The color is : " + board10.color);
        System.out.println("The stockQuantity is : " + board10.stockQuantity);
        System.out.println("The deckWidth is : " + board10.deckWidth);
        System.out.println("The isEcoFriendly is : " + board10.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board10.wheelMaterial);
        System.out.println("The rating is : " + board10.rating);
        System.out.println("The maxLoad is : " + board10.maxLoad);
        System.out.println("The isCertified is : " + board10.isCertified);
        System.out.println("The countryOfOrigin is : " + board10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board10.manufacturingYear);
        System.out.println("The bearingType is : " + board10.bearingType);
        System.out.println("The isFoldable is : " + board10.isFoldable);
        System.out.println("The certificationType is : " + board10.certificationType);

        board10.boardBrand = "ProSkate";
        board10.boardId = 10;
        board10.boardPrice = 1000.75;
        board10.isAvailable = true;
        board10.boardType = "Street";
        board10.deckLength = 31.5;
        board10.weight = 2.8;
        board10.isElectric = false;
        board10.material = "Maple Wood";
        board10.warrantyYears = 1;
        board10.wheelSize = 52.0;
        board10.hasGripTape = true;
        board10.color = "Black";
        board10.stockQuantity = 20;
        board10.deckWidth = 8.0;
        board10.isEcoFriendly = true;
        board10.wheelMaterial = "Polyurethane";
        board10.rating = 4;
        board10.maxLoad = 100.0;
        board10.isCertified = true;
        board10.countryOfOrigin = "USA";
        board10.manufacturingYear = 2025;
        board10.bearingType = "ABEC-7";
        board10.isFoldable = false;
        board10.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board10.boardBrand);
        System.out.println("The boardId is : " + board10.boardId);
        System.out.println("The boardPrice is : " + board10.boardPrice);
        System.out.println("The isAvailable is : " + board10.isAvailable);
        System.out.println("The boardType is : " + board10.boardType);
        System.out.println("The deckLength is : " + board10.deckLength);
        System.out.println("The weight is : " + board10.weight);
        System.out.println("The isElectric is : " + board10.isElectric);
        System.out.println("The material is : " + board10.material);
        System.out.println("The warrantyYears is : " + board10.warrantyYears);
        System.out.println("The wheelSize is : " + board10.wheelSize);
        System.out.println("The hasGripTape is : " + board10.hasGripTape);
        System.out.println("The color is : " + board10.color);
        System.out.println("The stockQuantity is : " + board10.stockQuantity);
        System.out.println("The deckWidth is : " + board10.deckWidth);
        System.out.println("The isEcoFriendly is : " + board10.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board10.wheelMaterial);
        System.out.println("The rating is : " + board10.rating);
        System.out.println("The maxLoad is : " + board10.maxLoad);
        System.out.println("The isCertified is : " + board10.isCertified);
        System.out.println("The countryOfOrigin is : " + board10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board10.manufacturingYear);
        System.out.println("The bearingType is : " + board10.bearingType);
        System.out.println("The isFoldable is : " + board10.isFoldable);
        System.out.println("The certificationType is : " + board10.certificationType);


        SkateBoard board11 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board11.boardBrand);
        System.out.println("The boardId is : " + board11.boardId);
        System.out.println("The boardPrice is : " + board11.boardPrice);
        System.out.println("The isAvailable is : " + board11.isAvailable);
        System.out.println("The boardType is : " + board11.boardType);
        System.out.println("The deckLength is : " + board11.deckLength);
        System.out.println("The weight is : " + board11.weight);
        System.out.println("The isElectric is : " + board11.isElectric);
        System.out.println("The material is : " + board11.material);
        System.out.println("The warrantyYears is : " + board11.warrantyYears);
        System.out.println("The wheelSize is : " + board11.wheelSize);
        System.out.println("The hasGripTape is : " + board11.hasGripTape);
        System.out.println("The color is : " + board11.color);
        System.out.println("The stockQuantity is : " + board11.stockQuantity);
        System.out.println("The deckWidth is : " + board11.deckWidth);
        System.out.println("The isEcoFriendly is : " + board11.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board11.wheelMaterial);
        System.out.println("The rating is : " + board11.rating);
        System.out.println("The maxLoad is : " + board11.maxLoad);
        System.out.println("The isCertified is : " + board11.isCertified);
        System.out.println("The countryOfOrigin is : " + board11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board11.manufacturingYear);
        System.out.println("The bearingType is : " + board11.bearingType);
        System.out.println("The isFoldable is : " + board11.isFoldable);
        System.out.println("The certificationType is : " + board11.certificationType);

        board11.boardBrand = "ProSkate";
        board11.boardId = 11;
        board11.boardPrice = 1100.75;
        board11.isAvailable = true;
        board11.boardType = "Street";
        board11.deckLength = 31.5;
        board11.weight = 2.8;
        board11.isElectric = false;
        board11.material = "Maple Wood";
        board11.warrantyYears = 1;
        board11.wheelSize = 52.0;
        board11.hasGripTape = true;
        board11.color = "Black";
        board11.stockQuantity = 20;
        board11.deckWidth = 8.0;
        board11.isEcoFriendly = true;
        board11.wheelMaterial = "Polyurethane";
        board11.rating = 4;
        board11.maxLoad = 100.0;
        board11.isCertified = true;
        board11.countryOfOrigin = "USA";
        board11.manufacturingYear = 2025;
        board11.bearingType = "ABEC-7";
        board11.isFoldable = false;
        board11.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board11.boardBrand);
        System.out.println("The boardId is : " + board11.boardId);
        System.out.println("The boardPrice is : " + board11.boardPrice);
        System.out.println("The isAvailable is : " + board11.isAvailable);
        System.out.println("The boardType is : " + board11.boardType);
        System.out.println("The deckLength is : " + board11.deckLength);
        System.out.println("The weight is : " + board11.weight);
        System.out.println("The isElectric is : " + board11.isElectric);
        System.out.println("The material is : " + board11.material);
        System.out.println("The warrantyYears is : " + board11.warrantyYears);
        System.out.println("The wheelSize is : " + board11.wheelSize);
        System.out.println("The hasGripTape is : " + board11.hasGripTape);
        System.out.println("The color is : " + board11.color);
        System.out.println("The stockQuantity is : " + board11.stockQuantity);
        System.out.println("The deckWidth is : " + board11.deckWidth);
        System.out.println("The isEcoFriendly is : " + board11.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board11.wheelMaterial);
        System.out.println("The rating is : " + board11.rating);
        System.out.println("The maxLoad is : " + board11.maxLoad);
        System.out.println("The isCertified is : " + board11.isCertified);
        System.out.println("The countryOfOrigin is : " + board11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board11.manufacturingYear);
        System.out.println("The bearingType is : " + board11.bearingType);
        System.out.println("The isFoldable is : " + board11.isFoldable);
        System.out.println("The certificationType is : " + board11.certificationType);


        SkateBoard board12 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board12.boardBrand);
        System.out.println("The boardId is : " + board12.boardId);
        System.out.println("The boardPrice is : " + board12.boardPrice);
        System.out.println("The isAvailable is : " + board12.isAvailable);
        System.out.println("The boardType is : " + board12.boardType);
        System.out.println("The deckLength is : " + board12.deckLength);
        System.out.println("The weight is : " + board12.weight);
        System.out.println("The isElectric is : " + board12.isElectric);
        System.out.println("The material is : " + board12.material);
        System.out.println("The warrantyYears is : " + board12.warrantyYears);
        System.out.println("The wheelSize is : " + board12.wheelSize);
        System.out.println("The hasGripTape is : " + board12.hasGripTape);
        System.out.println("The color is : " + board12.color);
        System.out.println("The stockQuantity is : " + board12.stockQuantity);
        System.out.println("The deckWidth is : " + board12.deckWidth);
        System.out.println("The isEcoFriendly is : " + board12.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board12.wheelMaterial);
        System.out.println("The rating is : " + board12.rating);
        System.out.println("The maxLoad is : " + board12.maxLoad);
        System.out.println("The isCertified is : " + board12.isCertified);
        System.out.println("The countryOfOrigin is : " + board12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board12.manufacturingYear);
        System.out.println("The bearingType is : " + board12.bearingType);
        System.out.println("The isFoldable is : " + board12.isFoldable);
        System.out.println("The certificationType is : " + board12.certificationType);

        board12.boardBrand = "ProSkate";
        board12.boardId = 12;
        board12.boardPrice = 1200.75;
        board12.isAvailable = true;
        board12.boardType = "Street";
        board12.deckLength = 31.5;
        board12.weight = 2.8;
        board12.isElectric = false;
        board12.material = "Maple Wood";
        board12.warrantyYears = 1;
        board12.wheelSize = 52.0;
        board12.hasGripTape = true;
        board12.color = "Black";
        board12.stockQuantity = 20;
        board12.deckWidth = 8.0;
        board12.isEcoFriendly = true;
        board12.wheelMaterial = "Polyurethane";
        board12.rating = 4;
        board12.maxLoad = 100.0;
        board12.isCertified = true;
        board12.countryOfOrigin = "USA";
        board12.manufacturingYear = 2025;
        board12.bearingType = "ABEC-7";
        board12.isFoldable = false;
        board12.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board12.boardBrand);
        System.out.println("The boardId is : " + board12.boardId);
        System.out.println("The boardPrice is : " + board12.boardPrice);
        System.out.println("The isAvailable is : " + board12.isAvailable);
        System.out.println("The boardType is : " + board12.boardType);
        System.out.println("The deckLength is : " + board12.deckLength);
        System.out.println("The weight is : " + board12.weight);
        System.out.println("The isElectric is : " + board12.isElectric);
        System.out.println("The material is : " + board12.material);
        System.out.println("The warrantyYears is : " + board12.warrantyYears);
        System.out.println("The wheelSize is : " + board12.wheelSize);
        System.out.println("The hasGripTape is : " + board12.hasGripTape);
        System.out.println("The color is : " + board12.color);
        System.out.println("The stockQuantity is : " + board12.stockQuantity);
        System.out.println("The deckWidth is : " + board12.deckWidth);
        System.out.println("The isEcoFriendly is : " + board12.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board12.wheelMaterial);
        System.out.println("The rating is : " + board12.rating);
        System.out.println("The maxLoad is : " + board12.maxLoad);
        System.out.println("The isCertified is : " + board12.isCertified);
        System.out.println("The countryOfOrigin is : " + board12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board12.manufacturingYear);
        System.out.println("The bearingType is : " + board12.bearingType);
        System.out.println("The isFoldable is : " + board12.isFoldable);
        System.out.println("The certificationType is : " + board12.certificationType);


        SkateBoard board13 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board13.boardBrand);
        System.out.println("The boardId is : " + board13.boardId);
        System.out.println("The boardPrice is : " + board13.boardPrice);
        System.out.println("The isAvailable is : " + board13.isAvailable);
        System.out.println("The boardType is : " + board13.boardType);
        System.out.println("The deckLength is : " + board13.deckLength);
        System.out.println("The weight is : " + board13.weight);
        System.out.println("The isElectric is : " + board13.isElectric);
        System.out.println("The material is : " + board13.material);
        System.out.println("The warrantyYears is : " + board13.warrantyYears);
        System.out.println("The wheelSize is : " + board13.wheelSize);
        System.out.println("The hasGripTape is : " + board13.hasGripTape);
        System.out.println("The color is : " + board13.color);
        System.out.println("The stockQuantity is : " + board13.stockQuantity);
        System.out.println("The deckWidth is : " + board13.deckWidth);
        System.out.println("The isEcoFriendly is : " + board13.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board13.wheelMaterial);
        System.out.println("The rating is : " + board13.rating);
        System.out.println("The maxLoad is : " + board13.maxLoad);
        System.out.println("The isCertified is : " + board13.isCertified);
        System.out.println("The countryOfOrigin is : " + board13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board13.manufacturingYear);
        System.out.println("The bearingType is : " + board13.bearingType);
        System.out.println("The isFoldable is : " + board13.isFoldable);
        System.out.println("The certificationType is : " + board13.certificationType);

        board13.boardBrand = "ProSkate";
        board13.boardId = 13;
        board13.boardPrice = 1300.75;
        board13.isAvailable = true;
        board13.boardType = "Street";
        board13.deckLength = 31.5;
        board13.weight = 2.8;
        board13.isElectric = false;
        board13.material = "Maple Wood";
        board13.warrantyYears = 1;
        board13.wheelSize = 52.0;
        board13.hasGripTape = true;
        board13.color = "Black";
        board13.stockQuantity = 20;
        board13.deckWidth = 8.0;
        board13.isEcoFriendly = true;
        board13.wheelMaterial = "Polyurethane";
        board13.rating = 4;
        board13.maxLoad = 100.0;
        board13.isCertified = true;
        board13.countryOfOrigin = "USA";
        board13.manufacturingYear = 2025;
        board13.bearingType = "ABEC-7";
        board13.isFoldable = false;
        board13.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board13.boardBrand);
        System.out.println("The boardId is : " + board13.boardId);
        System.out.println("The boardPrice is : " + board13.boardPrice);
        System.out.println("The isAvailable is : " + board13.isAvailable);
        System.out.println("The boardType is : " + board13.boardType);
        System.out.println("The deckLength is : " + board13.deckLength);
        System.out.println("The weight is : " + board13.weight);
        System.out.println("The isElectric is : " + board13.isElectric);
        System.out.println("The material is : " + board13.material);
        System.out.println("The warrantyYears is : " + board13.warrantyYears);
        System.out.println("The wheelSize is : " + board13.wheelSize);
        System.out.println("The hasGripTape is : " + board13.hasGripTape);
        System.out.println("The color is : " + board13.color);
        System.out.println("The stockQuantity is : " + board13.stockQuantity);
        System.out.println("The deckWidth is : " + board13.deckWidth);
        System.out.println("The isEcoFriendly is : " + board13.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board13.wheelMaterial);
        System.out.println("The rating is : " + board13.rating);
        System.out.println("The maxLoad is : " + board13.maxLoad);
        System.out.println("The isCertified is : " + board13.isCertified);
        System.out.println("The countryOfOrigin is : " + board13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board13.manufacturingYear);
        System.out.println("The bearingType is : " + board13.bearingType);
        System.out.println("The isFoldable is : " + board13.isFoldable);
        System.out.println("The certificationType is : " + board13.certificationType);


        SkateBoard board14 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board14.boardBrand);
        System.out.println("The boardId is : " + board14.boardId);
        System.out.println("The boardPrice is : " + board14.boardPrice);
        System.out.println("The isAvailable is : " + board14.isAvailable);
        System.out.println("The boardType is : " + board14.boardType);
        System.out.println("The deckLength is : " + board14.deckLength);
        System.out.println("The weight is : " + board14.weight);
        System.out.println("The isElectric is : " + board14.isElectric);
        System.out.println("The material is : " + board14.material);
        System.out.println("The warrantyYears is : " + board14.warrantyYears);
        System.out.println("The wheelSize is : " + board14.wheelSize);
        System.out.println("The hasGripTape is : " + board14.hasGripTape);
        System.out.println("The color is : " + board14.color);
        System.out.println("The stockQuantity is : " + board14.stockQuantity);
        System.out.println("The deckWidth is : " + board14.deckWidth);
        System.out.println("The isEcoFriendly is : " + board14.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board14.wheelMaterial);
        System.out.println("The rating is : " + board14.rating);
        System.out.println("The maxLoad is : " + board14.maxLoad);
        System.out.println("The isCertified is : " + board14.isCertified);
        System.out.println("The countryOfOrigin is : " + board14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board14.manufacturingYear);
        System.out.println("The bearingType is : " + board14.bearingType);
        System.out.println("The isFoldable is : " + board14.isFoldable);
        System.out.println("The certificationType is : " + board14.certificationType);

        board14.boardBrand = "ProSkate";
        board14.boardId = 14;
        board14.boardPrice = 1400.75;
        board14.isAvailable = true;
        board14.boardType = "Street";
        board14.deckLength = 31.5;
        board14.weight = 2.8;
        board14.isElectric = false;
        board14.material = "Maple Wood";
        board14.warrantyYears = 1;
        board14.wheelSize = 52.0;
        board14.hasGripTape = true;
        board14.color = "Black";
        board14.stockQuantity = 20;
        board14.deckWidth = 8.0;
        board14.isEcoFriendly = true;
        board14.wheelMaterial = "Polyurethane";
        board14.rating = 4;
        board14.maxLoad = 100.0;
        board14.isCertified = true;
        board14.countryOfOrigin = "USA";
        board14.manufacturingYear = 2025;
        board14.bearingType = "ABEC-7";
        board14.isFoldable = false;
        board14.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board14.boardBrand);
        System.out.println("The boardId is : " + board14.boardId);
        System.out.println("The boardPrice is : " + board14.boardPrice);
        System.out.println("The isAvailable is : " + board14.isAvailable);
        System.out.println("The boardType is : " + board14.boardType);
        System.out.println("The deckLength is : " + board14.deckLength);
        System.out.println("The weight is : " + board14.weight);
        System.out.println("The isElectric is : " + board14.isElectric);
        System.out.println("The material is : " + board14.material);
        System.out.println("The warrantyYears is : " + board14.warrantyYears);
        System.out.println("The wheelSize is : " + board14.wheelSize);
        System.out.println("The hasGripTape is : " + board14.hasGripTape);
        System.out.println("The color is : " + board14.color);
        System.out.println("The stockQuantity is : " + board14.stockQuantity);
        System.out.println("The deckWidth is : " + board14.deckWidth);
        System.out.println("The isEcoFriendly is : " + board14.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board14.wheelMaterial);
        System.out.println("The rating is : " + board14.rating);
        System.out.println("The maxLoad is : " + board14.maxLoad);
        System.out.println("The isCertified is : " + board14.isCertified);
        System.out.println("The countryOfOrigin is : " + board14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board14.manufacturingYear);
        System.out.println("The bearingType is : " + board14.bearingType);
        System.out.println("The isFoldable is : " + board14.isFoldable);
        System.out.println("The certificationType is : " + board14.certificationType);


        SkateBoard board15 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board15.boardBrand);
        System.out.println("The boardId is : " + board15.boardId);
        System.out.println("The boardPrice is : " + board15.boardPrice);
        System.out.println("The isAvailable is : " + board15.isAvailable);
        System.out.println("The boardType is : " + board15.boardType);
        System.out.println("The deckLength is : " + board15.deckLength);
        System.out.println("The weight is : " + board15.weight);
        System.out.println("The isElectric is : " + board15.isElectric);
        System.out.println("The material is : " + board15.material);
        System.out.println("The warrantyYears is : " + board15.warrantyYears);
        System.out.println("The wheelSize is : " + board15.wheelSize);
        System.out.println("The hasGripTape is : " + board15.hasGripTape);
        System.out.println("The color is : " + board15.color);
        System.out.println("The stockQuantity is : " + board15.stockQuantity);
        System.out.println("The deckWidth is : " + board15.deckWidth);
        System.out.println("The isEcoFriendly is : " + board15.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board15.wheelMaterial);
        System.out.println("The rating is : " + board15.rating);
        System.out.println("The maxLoad is : " + board15.maxLoad);
        System.out.println("The isCertified is : " + board15.isCertified);
        System.out.println("The countryOfOrigin is : " + board15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board15.manufacturingYear);
        System.out.println("The bearingType is : " + board15.bearingType);
        System.out.println("The isFoldable is : " + board15.isFoldable);
        System.out.println("The certificationType is : " + board15.certificationType);

        board15.boardBrand = "ProSkate";
        board15.boardId = 15;
        board15.boardPrice = 1500.75;
        board15.isAvailable = true;
        board15.boardType = "Street";
        board15.deckLength = 31.5;
        board15.weight = 2.8;
        board15.isElectric = false;
        board15.material = "Maple Wood";
        board15.warrantyYears = 1;
        board15.wheelSize = 52.0;
        board15.hasGripTape = true;
        board15.color = "Black";
        board15.stockQuantity = 20;
        board15.deckWidth = 8.0;
        board15.isEcoFriendly = true;
        board15.wheelMaterial = "Polyurethane";
        board15.rating = 4;
        board15.maxLoad = 100.0;
        board15.isCertified = true;
        board15.countryOfOrigin = "USA";
        board15.manufacturingYear = 2025;
        board15.bearingType = "ABEC-7";
        board15.isFoldable = false;
        board15.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board15.boardBrand);
        System.out.println("The boardId is : " + board15.boardId);
        System.out.println("The boardPrice is : " + board15.boardPrice);
        System.out.println("The isAvailable is : " + board15.isAvailable);
        System.out.println("The boardType is : " + board15.boardType);
        System.out.println("The deckLength is : " + board15.deckLength);
        System.out.println("The weight is : " + board15.weight);
        System.out.println("The isElectric is : " + board15.isElectric);
        System.out.println("The material is : " + board15.material);
        System.out.println("The warrantyYears is : " + board15.warrantyYears);
        System.out.println("The wheelSize is : " + board15.wheelSize);
        System.out.println("The hasGripTape is : " + board15.hasGripTape);
        System.out.println("The color is : " + board15.color);
        System.out.println("The stockQuantity is : " + board15.stockQuantity);
        System.out.println("The deckWidth is : " + board15.deckWidth);
        System.out.println("The isEcoFriendly is : " + board15.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board15.wheelMaterial);
        System.out.println("The rating is : " + board15.rating);
        System.out.println("The maxLoad is : " + board15.maxLoad);
        System.out.println("The isCertified is : " + board15.isCertified);
        System.out.println("The countryOfOrigin is : " + board15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board15.manufacturingYear);
        System.out.println("The bearingType is : " + board15.bearingType);
        System.out.println("The isFoldable is : " + board15.isFoldable);
        System.out.println("The certificationType is : " + board15.certificationType);


        SkateBoard board16 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board16.boardBrand);
        System.out.println("The boardId is : " + board16.boardId);
        System.out.println("The boardPrice is : " + board16.boardPrice);
        System.out.println("The isAvailable is : " + board16.isAvailable);
        System.out.println("The boardType is : " + board16.boardType);
        System.out.println("The deckLength is : " + board16.deckLength);
        System.out.println("The weight is : " + board16.weight);
        System.out.println("The isElectric is : " + board16.isElectric);
        System.out.println("The material is : " + board16.material);
        System.out.println("The warrantyYears is : " + board16.warrantyYears);
        System.out.println("The wheelSize is : " + board16.wheelSize);
        System.out.println("The hasGripTape is : " + board16.hasGripTape);
        System.out.println("The color is : " + board16.color);
        System.out.println("The stockQuantity is : " + board16.stockQuantity);
        System.out.println("The deckWidth is : " + board16.deckWidth);
        System.out.println("The isEcoFriendly is : " + board16.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board16.wheelMaterial);
        System.out.println("The rating is : " + board16.rating);
        System.out.println("The maxLoad is : " + board16.maxLoad);
        System.out.println("The isCertified is : " + board16.isCertified);
        System.out.println("The countryOfOrigin is : " + board16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board16.manufacturingYear);
        System.out.println("The bearingType is : " + board16.bearingType);
        System.out.println("The isFoldable is : " + board16.isFoldable);
        System.out.println("The certificationType is : " + board16.certificationType);

        board16.boardBrand = "ProSkate";
        board16.boardId = 16;
        board16.boardPrice = 1600.75;
        board16.isAvailable = true;
        board16.boardType = "Street";
        board16.deckLength = 31.5;
        board16.weight = 2.8;
        board16.isElectric = false;
        board16.material = "Maple Wood";
        board16.warrantyYears = 1;
        board16.wheelSize = 52.0;
        board16.hasGripTape = true;
        board16.color = "Black";
        board16.stockQuantity = 20;
        board16.deckWidth = 8.0;
        board16.isEcoFriendly = true;
        board16.wheelMaterial = "Polyurethane";
        board16.rating = 4;
        board16.maxLoad = 100.0;
        board16.isCertified = true;
        board16.countryOfOrigin = "USA";
        board16.manufacturingYear = 2025;
        board16.bearingType = "ABEC-7";
        board16.isFoldable = false;
        board16.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board16.boardBrand);
        System.out.println("The boardId is : " + board16.boardId);
        System.out.println("The boardPrice is : " + board16.boardPrice);
        System.out.println("The isAvailable is : " + board16.isAvailable);
        System.out.println("The boardType is : " + board16.boardType);
        System.out.println("The deckLength is : " + board16.deckLength);
        System.out.println("The weight is : " + board16.weight);
        System.out.println("The isElectric is : " + board16.isElectric);
        System.out.println("The material is : " + board16.material);
        System.out.println("The warrantyYears is : " + board16.warrantyYears);
        System.out.println("The wheelSize is : " + board16.wheelSize);
        System.out.println("The hasGripTape is : " + board16.hasGripTape);
        System.out.println("The color is : " + board16.color);
        System.out.println("The stockQuantity is : " + board16.stockQuantity);
        System.out.println("The deckWidth is : " + board16.deckWidth);
        System.out.println("The isEcoFriendly is : " + board16.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board16.wheelMaterial);
        System.out.println("The rating is : " + board16.rating);
        System.out.println("The maxLoad is : " + board16.maxLoad);
        System.out.println("The isCertified is : " + board16.isCertified);
        System.out.println("The countryOfOrigin is : " + board16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board16.manufacturingYear);
        System.out.println("The bearingType is : " + board16.bearingType);
        System.out.println("The isFoldable is : " + board16.isFoldable);
        System.out.println("The certificationType is : " + board16.certificationType);


        SkateBoard board17 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board17.boardBrand);
        System.out.println("The boardId is : " + board17.boardId);
        System.out.println("The boardPrice is : " + board17.boardPrice);
        System.out.println("The isAvailable is : " + board17.isAvailable);
        System.out.println("The boardType is : " + board17.boardType);
        System.out.println("The deckLength is : " + board17.deckLength);
        System.out.println("The weight is : " + board17.weight);
        System.out.println("The isElectric is : " + board17.isElectric);
        System.out.println("The material is : " + board17.material);
        System.out.println("The warrantyYears is : " + board17.warrantyYears);
        System.out.println("The wheelSize is : " + board17.wheelSize);
        System.out.println("The hasGripTape is : " + board17.hasGripTape);
        System.out.println("The color is : " + board17.color);
        System.out.println("The stockQuantity is : " + board17.stockQuantity);
        System.out.println("The deckWidth is : " + board17.deckWidth);
        System.out.println("The isEcoFriendly is : " + board17.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board17.wheelMaterial);
        System.out.println("The rating is : " + board17.rating);
        System.out.println("The maxLoad is : " + board17.maxLoad);
        System.out.println("The isCertified is : " + board17.isCertified);
        System.out.println("The countryOfOrigin is : " + board17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board17.manufacturingYear);
        System.out.println("The bearingType is : " + board17.bearingType);
        System.out.println("The isFoldable is : " + board17.isFoldable);
        System.out.println("The certificationType is : " + board17.certificationType);

        board17.boardBrand = "ProSkate";
        board17.boardId = 17;
        board17.boardPrice = 1700.75;
        board17.isAvailable = true;
        board17.boardType = "Street";
        board17.deckLength = 31.5;
        board17.weight = 2.8;
        board17.isElectric = false;
        board17.material = "Maple Wood";
        board17.warrantyYears = 1;
        board17.wheelSize = 52.0;
        board17.hasGripTape = true;
        board17.color = "Black";
        board17.stockQuantity = 20;
        board17.deckWidth = 8.0;
        board17.isEcoFriendly = true;
        board17.wheelMaterial = "Polyurethane";
        board17.rating = 4;
        board17.maxLoad = 100.0;
        board17.isCertified = true;
        board17.countryOfOrigin = "USA";
        board17.manufacturingYear = 2025;
        board17.bearingType = "ABEC-7";
        board17.isFoldable = false;
        board17.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board17.boardBrand);
        System.out.println("The boardId is : " + board17.boardId);
        System.out.println("The boardPrice is : " + board17.boardPrice);
        System.out.println("The isAvailable is : " + board17.isAvailable);
        System.out.println("The boardType is : " + board17.boardType);
        System.out.println("The deckLength is : " + board17.deckLength);
        System.out.println("The weight is : " + board17.weight);
        System.out.println("The isElectric is : " + board17.isElectric);
        System.out.println("The material is : " + board17.material);
        System.out.println("The warrantyYears is : " + board17.warrantyYears);
        System.out.println("The wheelSize is : " + board17.wheelSize);
        System.out.println("The hasGripTape is : " + board17.hasGripTape);
        System.out.println("The color is : " + board17.color);
        System.out.println("The stockQuantity is : " + board17.stockQuantity);
        System.out.println("The deckWidth is : " + board17.deckWidth);
        System.out.println("The isEcoFriendly is : " + board17.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board17.wheelMaterial);
        System.out.println("The rating is : " + board17.rating);
        System.out.println("The maxLoad is : " + board17.maxLoad);
        System.out.println("The isCertified is : " + board17.isCertified);
        System.out.println("The countryOfOrigin is : " + board17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board17.manufacturingYear);
        System.out.println("The bearingType is : " + board17.bearingType);
        System.out.println("The isFoldable is : " + board17.isFoldable);
        System.out.println("The certificationType is : " + board17.certificationType);


        SkateBoard board18 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board18.boardBrand);
        System.out.println("The boardId is : " + board18.boardId);
        System.out.println("The boardPrice is : " + board18.boardPrice);
        System.out.println("The isAvailable is : " + board18.isAvailable);
        System.out.println("The boardType is : " + board18.boardType);
        System.out.println("The deckLength is : " + board18.deckLength);
        System.out.println("The weight is : " + board18.weight);
        System.out.println("The isElectric is : " + board18.isElectric);
        System.out.println("The material is : " + board18.material);
        System.out.println("The warrantyYears is : " + board18.warrantyYears);
        System.out.println("The wheelSize is : " + board18.wheelSize);
        System.out.println("The hasGripTape is : " + board18.hasGripTape);
        System.out.println("The color is : " + board18.color);
        System.out.println("The stockQuantity is : " + board18.stockQuantity);
        System.out.println("The deckWidth is : " + board18.deckWidth);
        System.out.println("The isEcoFriendly is : " + board18.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board18.wheelMaterial);
        System.out.println("The rating is : " + board18.rating);
        System.out.println("The maxLoad is : " + board18.maxLoad);
        System.out.println("The isCertified is : " + board18.isCertified);
        System.out.println("The countryOfOrigin is : " + board18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board18.manufacturingYear);
        System.out.println("The bearingType is : " + board18.bearingType);
        System.out.println("The isFoldable is : " + board18.isFoldable);
        System.out.println("The certificationType is : " + board18.certificationType);

        board18.boardBrand = "ProSkate";
        board18.boardId = 18;
        board18.boardPrice = 1800.75;
        board18.isAvailable = true;
        board18.boardType = "Street";
        board18.deckLength = 31.5;
        board18.weight = 2.8;
        board18.isElectric = false;
        board18.material = "Maple Wood";
        board18.warrantyYears = 1;
        board18.wheelSize = 52.0;
        board18.hasGripTape = true;
        board18.color = "Black";
        board18.stockQuantity = 20;
        board18.deckWidth = 8.0;
        board18.isEcoFriendly = true;
        board18.wheelMaterial = "Polyurethane";
        board18.rating = 4;
        board18.maxLoad = 100.0;
        board18.isCertified = true;
        board18.countryOfOrigin = "USA";
        board18.manufacturingYear = 2025;
        board18.bearingType = "ABEC-7";
        board18.isFoldable = false;
        board18.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board18.boardBrand);
        System.out.println("The boardId is : " + board18.boardId);
        System.out.println("The boardPrice is : " + board18.boardPrice);
        System.out.println("The isAvailable is : " + board18.isAvailable);
        System.out.println("The boardType is : " + board18.boardType);
        System.out.println("The deckLength is : " + board18.deckLength);
        System.out.println("The weight is : " + board18.weight);
        System.out.println("The isElectric is : " + board18.isElectric);
        System.out.println("The material is : " + board18.material);
        System.out.println("The warrantyYears is : " + board18.warrantyYears);
        System.out.println("The wheelSize is : " + board18.wheelSize);
        System.out.println("The hasGripTape is : " + board18.hasGripTape);
        System.out.println("The color is : " + board18.color);
        System.out.println("The stockQuantity is : " + board18.stockQuantity);
        System.out.println("The deckWidth is : " + board18.deckWidth);
        System.out.println("The isEcoFriendly is : " + board18.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board18.wheelMaterial);
        System.out.println("The rating is : " + board18.rating);
        System.out.println("The maxLoad is : " + board18.maxLoad);
        System.out.println("The isCertified is : " + board18.isCertified);
        System.out.println("The countryOfOrigin is : " + board18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board18.manufacturingYear);
        System.out.println("The bearingType is : " + board18.bearingType);
        System.out.println("The isFoldable is : " + board18.isFoldable);
        System.out.println("The certificationType is : " + board18.certificationType);


        SkateBoard board19 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board19.boardBrand);
        System.out.println("The boardId is : " + board19.boardId);
        System.out.println("The boardPrice is : " + board19.boardPrice);
        System.out.println("The isAvailable is : " + board19.isAvailable);
        System.out.println("The boardType is : " + board19.boardType);
        System.out.println("The deckLength is : " + board19.deckLength);
        System.out.println("The weight is : " + board19.weight);
        System.out.println("The isElectric is : " + board19.isElectric);
        System.out.println("The material is : " + board19.material);
        System.out.println("The warrantyYears is : " + board19.warrantyYears);
        System.out.println("The wheelSize is : " + board19.wheelSize);
        System.out.println("The hasGripTape is : " + board19.hasGripTape);
        System.out.println("The color is : " + board19.color);
        System.out.println("The stockQuantity is : " + board19.stockQuantity);
        System.out.println("The deckWidth is : " + board19.deckWidth);
        System.out.println("The isEcoFriendly is : " + board19.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board19.wheelMaterial);
        System.out.println("The rating is : " + board19.rating);
        System.out.println("The maxLoad is : " + board19.maxLoad);
        System.out.println("The isCertified is : " + board19.isCertified);
        System.out.println("The countryOfOrigin is : " + board19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board19.manufacturingYear);
        System.out.println("The bearingType is : " + board19.bearingType);
        System.out.println("The isFoldable is : " + board19.isFoldable);
        System.out.println("The certificationType is : " + board19.certificationType);

        board19.boardBrand = "ProSkate";
        board19.boardId = 19;
        board19.boardPrice = 1900.75;
        board19.isAvailable = true;
        board19.boardType = "Street";
        board19.deckLength = 31.5;
        board19.weight = 2.8;
        board19.isElectric = false;
        board19.material = "Maple Wood";
        board19.warrantyYears = 1;
        board19.wheelSize = 52.0;
        board19.hasGripTape = true;
        board19.color = "Black";
        board19.stockQuantity = 20;
        board19.deckWidth = 8.0;
        board19.isEcoFriendly = true;
        board19.wheelMaterial = "Polyurethane";
        board19.rating = 4;
        board19.maxLoad = 100.0;
        board19.isCertified = true;
        board19.countryOfOrigin = "USA";
        board19.manufacturingYear = 2025;
        board19.bearingType = "ABEC-7";
        board19.isFoldable = false;
        board19.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board19.boardBrand);
        System.out.println("The boardId is : " + board19.boardId);
        System.out.println("The boardPrice is : " + board19.boardPrice);
        System.out.println("The isAvailable is : " + board19.isAvailable);
        System.out.println("The boardType is : " + board19.boardType);
        System.out.println("The deckLength is : " + board19.deckLength);
        System.out.println("The weight is : " + board19.weight);
        System.out.println("The isElectric is : " + board19.isElectric);
        System.out.println("The material is : " + board19.material);
        System.out.println("The warrantyYears is : " + board19.warrantyYears);
        System.out.println("The wheelSize is : " + board19.wheelSize);
        System.out.println("The hasGripTape is : " + board19.hasGripTape);
        System.out.println("The color is : " + board19.color);
        System.out.println("The stockQuantity is : " + board19.stockQuantity);
        System.out.println("The deckWidth is : " + board19.deckWidth);
        System.out.println("The isEcoFriendly is : " + board19.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board19.wheelMaterial);
        System.out.println("The rating is : " + board19.rating);
        System.out.println("The maxLoad is : " + board19.maxLoad);
        System.out.println("The isCertified is : " + board19.isCertified);
        System.out.println("The countryOfOrigin is : " + board19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board19.manufacturingYear);
        System.out.println("The bearingType is : " + board19.bearingType);
        System.out.println("The isFoldable is : " + board19.isFoldable);
        System.out.println("The certificationType is : " + board19.certificationType);


        SkateBoard board20 = new SkateBoard();

        System.out.println("Before initialization");

        System.out.println("The boardBrand is : " + board20.boardBrand);
        System.out.println("The boardId is : " + board20.boardId);
        System.out.println("The boardPrice is : " + board20.boardPrice);
        System.out.println("The isAvailable is : " + board20.isAvailable);
        System.out.println("The boardType is : " + board20.boardType);
        System.out.println("The deckLength is : " + board20.deckLength);
        System.out.println("The weight is : " + board20.weight);
        System.out.println("The isElectric is : " + board20.isElectric);
        System.out.println("The material is : " + board20.material);
        System.out.println("The warrantyYears is : " + board20.warrantyYears);
        System.out.println("The wheelSize is : " + board20.wheelSize);
        System.out.println("The hasGripTape is : " + board20.hasGripTape);
        System.out.println("The color is : " + board20.color);
        System.out.println("The stockQuantity is : " + board20.stockQuantity);
        System.out.println("The deckWidth is : " + board20.deckWidth);
        System.out.println("The isEcoFriendly is : " + board20.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board20.wheelMaterial);
        System.out.println("The rating is : " + board20.rating);
        System.out.println("The maxLoad is : " + board20.maxLoad);
        System.out.println("The isCertified is : " + board20.isCertified);
        System.out.println("The countryOfOrigin is : " + board20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board20.manufacturingYear);
        System.out.println("The bearingType is : " + board20.bearingType);
        System.out.println("The isFoldable is : " + board20.isFoldable);
        System.out.println("The certificationType is : " + board20.certificationType);

        board20.boardBrand = "ProSkate";
        board20.boardId = 20;
        board20.boardPrice = 2000.75;
        board20.isAvailable = true;
        board20.boardType = "Street";
        board20.deckLength = 31.5;
        board20.weight = 2.8;
        board20.isElectric = false;
        board20.material = "Maple Wood";
        board20.warrantyYears = 1;
        board20.wheelSize = 52.0;
        board20.hasGripTape = true;
        board20.color = "Black";
        board20.stockQuantity = 20;
        board20.deckWidth = 8.0;
        board20.isEcoFriendly = true;
        board20.wheelMaterial = "Polyurethane";
        board20.rating = 4;
        board20.maxLoad = 100.0;
        board20.isCertified = true;
        board20.countryOfOrigin = "USA";
        board20.manufacturingYear = 2025;
        board20.bearingType = "ABEC-7";
        board20.isFoldable = false;
        board20.certificationType = "CE";

        System.out.println("After initialization");

        System.out.println("The boardBrand is : " + board20.boardBrand);
        System.out.println("The boardId is : " + board20.boardId);
        System.out.println("The boardPrice is : " + board20.boardPrice);
        System.out.println("The isAvailable is : " + board20.isAvailable);
        System.out.println("The boardType is : " + board20.boardType);
        System.out.println("The deckLength is : " + board20.deckLength);
        System.out.println("The weight is : " + board20.weight);
        System.out.println("The isElectric is : " + board20.isElectric);
        System.out.println("The material is : " + board20.material);
        System.out.println("The warrantyYears is : " + board20.warrantyYears);
        System.out.println("The wheelSize is : " + board20.wheelSize);
        System.out.println("The hasGripTape is : " + board20.hasGripTape);
        System.out.println("The color is : " + board20.color);
        System.out.println("The stockQuantity is : " + board20.stockQuantity);
        System.out.println("The deckWidth is : " + board20.deckWidth);
        System.out.println("The isEcoFriendly is : " + board20.isEcoFriendly);
        System.out.println("The wheelMaterial is : " + board20.wheelMaterial);
        System.out.println("The rating is : " + board20.rating);
        System.out.println("The maxLoad is : " + board20.maxLoad);
        System.out.println("The isCertified is : " + board20.isCertified);
        System.out.println("The countryOfOrigin is : " + board20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + board20.manufacturingYear);
        System.out.println("The bearingType is : " + board20.bearingType);
        System.out.println("The isFoldable is : " + board20.isFoldable);
        System.out.println("The certificationType is : " + board20.certificationType);


    }
}
