class SolarPanelExecutor {

    public static void main(String[] args) {

        SolarPanel panel1 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel1.panelBrand);
        System.out.println("The panelId is : " + panel1.panelId);
        System.out.println("The panelPrice is : " + panel1.panelPrice);
        System.out.println("The isAvailable is : " + panel1.isAvailable);
        System.out.println("The panelType is : " + panel1.panelType);
        System.out.println("The powerOutputWatts is : " + panel1.powerOutputWatts);
        System.out.println("The weight is : " + panel1.weight);
        System.out.println("The isPortable is : " + panel1.isPortable);
        System.out.println("The cellType is : " + panel1.cellType);
        System.out.println("The warrantyYears is : " + panel1.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel1.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel1.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel1.color);
        System.out.println("The stockQuantity is : " + panel1.stockQuantity);
        System.out.println("The panelLength is : " + panel1.panelLength);
        System.out.println("The isEcoFriendly is : " + panel1.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel1.frameMaterial);
        System.out.println("The rating is : " + panel1.rating);
        System.out.println("The voltage is : " + panel1.voltage);
        System.out.println("The isCertified is : " + panel1.isCertified);
        System.out.println("The countryOfOrigin is : " + panel1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel1.manufacturingYear);
        System.out.println("The panelWidth is : " + panel1.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel1.supportsOffGrid);
        System.out.println("The certificationType is : " + panel1.certificationType);

        panel1.panelBrand = "SunPower";
        panel1.panelId = 1;
        panel1.panelPrice = 1000.75;
        panel1.isAvailable = true;
        panel1.panelType = "Monocrystalline";
        panel1.powerOutputWatts = 450.0;
        panel1.weight = 22.5;
        panel1.isPortable = false;
        panel1.cellType = "Mono";
        panel1.warrantyYears = 25;
        panel1.panelEfficiency = 21.5;
        panel1.hasAntiReflectiveCoating = true;
        panel1.color = "Blue";
        panel1.stockQuantity = 35;
        panel1.panelLength = 200.0;
        panel1.isEcoFriendly = true;
        panel1.frameMaterial = "Aluminum";
        panel1.rating = 5;
        panel1.voltage = 40.5;
        panel1.isCertified = true;
        panel1.countryOfOrigin = "China";
        panel1.manufacturingYear = 2025;
        panel1.panelWidth = 100.0;
        panel1.supportsOffGrid = true;
        panel1.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel1.panelBrand);
        System.out.println("The panelId is : " + panel1.panelId);
        System.out.println("The panelPrice is : " + panel1.panelPrice);
        System.out.println("The isAvailable is : " + panel1.isAvailable);
        System.out.println("The panelType is : " + panel1.panelType);
        System.out.println("The powerOutputWatts is : " + panel1.powerOutputWatts);
        System.out.println("The weight is : " + panel1.weight);
        System.out.println("The isPortable is : " + panel1.isPortable);
        System.out.println("The cellType is : " + panel1.cellType);
        System.out.println("The warrantyYears is : " + panel1.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel1.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel1.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel1.color);
        System.out.println("The stockQuantity is : " + panel1.stockQuantity);
        System.out.println("The panelLength is : " + panel1.panelLength);
        System.out.println("The isEcoFriendly is : " + panel1.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel1.frameMaterial);
        System.out.println("The rating is : " + panel1.rating);
        System.out.println("The voltage is : " + panel1.voltage);
        System.out.println("The isCertified is : " + panel1.isCertified);
        System.out.println("The countryOfOrigin is : " + panel1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel1.manufacturingYear);
        System.out.println("The panelWidth is : " + panel1.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel1.supportsOffGrid);
        System.out.println("The certificationType is : " + panel1.certificationType);


        SolarPanel panel2 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel2.panelBrand);
        System.out.println("The panelId is : " + panel2.panelId);
        System.out.println("The panelPrice is : " + panel2.panelPrice);
        System.out.println("The isAvailable is : " + panel2.isAvailable);
        System.out.println("The panelType is : " + panel2.panelType);
        System.out.println("The powerOutputWatts is : " + panel2.powerOutputWatts);
        System.out.println("The weight is : " + panel2.weight);
        System.out.println("The isPortable is : " + panel2.isPortable);
        System.out.println("The cellType is : " + panel2.cellType);
        System.out.println("The warrantyYears is : " + panel2.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel2.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel2.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel2.color);
        System.out.println("The stockQuantity is : " + panel2.stockQuantity);
        System.out.println("The panelLength is : " + panel2.panelLength);
        System.out.println("The isEcoFriendly is : " + panel2.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel2.frameMaterial);
        System.out.println("The rating is : " + panel2.rating);
        System.out.println("The voltage is : " + panel2.voltage);
        System.out.println("The isCertified is : " + panel2.isCertified);
        System.out.println("The countryOfOrigin is : " + panel2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel2.manufacturingYear);
        System.out.println("The panelWidth is : " + panel2.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel2.supportsOffGrid);
        System.out.println("The certificationType is : " + panel2.certificationType);

        panel2.panelBrand = "SunPower";
        panel2.panelId = 2;
        panel2.panelPrice = 2000.75;
        panel2.isAvailable = true;
        panel2.panelType = "Monocrystalline";
        panel2.powerOutputWatts = 450.0;
        panel2.weight = 22.5;
        panel2.isPortable = false;
        panel2.cellType = "Mono";
        panel2.warrantyYears = 25;
        panel2.panelEfficiency = 21.5;
        panel2.hasAntiReflectiveCoating = true;
        panel2.color = "Blue";
        panel2.stockQuantity = 35;
        panel2.panelLength = 200.0;
        panel2.isEcoFriendly = true;
        panel2.frameMaterial = "Aluminum";
        panel2.rating = 5;
        panel2.voltage = 40.5;
        panel2.isCertified = true;
        panel2.countryOfOrigin = "China";
        panel2.manufacturingYear = 2025;
        panel2.panelWidth = 100.0;
        panel2.supportsOffGrid = true;
        panel2.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel2.panelBrand);
        System.out.println("The panelId is : " + panel2.panelId);
        System.out.println("The panelPrice is : " + panel2.panelPrice);
        System.out.println("The isAvailable is : " + panel2.isAvailable);
        System.out.println("The panelType is : " + panel2.panelType);
        System.out.println("The powerOutputWatts is : " + panel2.powerOutputWatts);
        System.out.println("The weight is : " + panel2.weight);
        System.out.println("The isPortable is : " + panel2.isPortable);
        System.out.println("The cellType is : " + panel2.cellType);
        System.out.println("The warrantyYears is : " + panel2.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel2.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel2.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel2.color);
        System.out.println("The stockQuantity is : " + panel2.stockQuantity);
        System.out.println("The panelLength is : " + panel2.panelLength);
        System.out.println("The isEcoFriendly is : " + panel2.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel2.frameMaterial);
        System.out.println("The rating is : " + panel2.rating);
        System.out.println("The voltage is : " + panel2.voltage);
        System.out.println("The isCertified is : " + panel2.isCertified);
        System.out.println("The countryOfOrigin is : " + panel2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel2.manufacturingYear);
        System.out.println("The panelWidth is : " + panel2.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel2.supportsOffGrid);
        System.out.println("The certificationType is : " + panel2.certificationType);


        SolarPanel panel3 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel3.panelBrand);
        System.out.println("The panelId is : " + panel3.panelId);
        System.out.println("The panelPrice is : " + panel3.panelPrice);
        System.out.println("The isAvailable is : " + panel3.isAvailable);
        System.out.println("The panelType is : " + panel3.panelType);
        System.out.println("The powerOutputWatts is : " + panel3.powerOutputWatts);
        System.out.println("The weight is : " + panel3.weight);
        System.out.println("The isPortable is : " + panel3.isPortable);
        System.out.println("The cellType is : " + panel3.cellType);
        System.out.println("The warrantyYears is : " + panel3.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel3.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel3.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel3.color);
        System.out.println("The stockQuantity is : " + panel3.stockQuantity);
        System.out.println("The panelLength is : " + panel3.panelLength);
        System.out.println("The isEcoFriendly is : " + panel3.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel3.frameMaterial);
        System.out.println("The rating is : " + panel3.rating);
        System.out.println("The voltage is : " + panel3.voltage);
        System.out.println("The isCertified is : " + panel3.isCertified);
        System.out.println("The countryOfOrigin is : " + panel3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel3.manufacturingYear);
        System.out.println("The panelWidth is : " + panel3.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel3.supportsOffGrid);
        System.out.println("The certificationType is : " + panel3.certificationType);

        panel3.panelBrand = "SunPower";
        panel3.panelId = 3;
        panel3.panelPrice = 3000.75;
        panel3.isAvailable = true;
        panel3.panelType = "Monocrystalline";
        panel3.powerOutputWatts = 450.0;
        panel3.weight = 22.5;
        panel3.isPortable = false;
        panel3.cellType = "Mono";
        panel3.warrantyYears = 25;
        panel3.panelEfficiency = 21.5;
        panel3.hasAntiReflectiveCoating = true;
        panel3.color = "Blue";
        panel3.stockQuantity = 35;
        panel3.panelLength = 200.0;
        panel3.isEcoFriendly = true;
        panel3.frameMaterial = "Aluminum";
        panel3.rating = 5;
        panel3.voltage = 40.5;
        panel3.isCertified = true;
        panel3.countryOfOrigin = "China";
        panel3.manufacturingYear = 2025;
        panel3.panelWidth = 100.0;
        panel3.supportsOffGrid = true;
        panel3.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel3.panelBrand);
        System.out.println("The panelId is : " + panel3.panelId);
        System.out.println("The panelPrice is : " + panel3.panelPrice);
        System.out.println("The isAvailable is : " + panel3.isAvailable);
        System.out.println("The panelType is : " + panel3.panelType);
        System.out.println("The powerOutputWatts is : " + panel3.powerOutputWatts);
        System.out.println("The weight is : " + panel3.weight);
        System.out.println("The isPortable is : " + panel3.isPortable);
        System.out.println("The cellType is : " + panel3.cellType);
        System.out.println("The warrantyYears is : " + panel3.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel3.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel3.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel3.color);
        System.out.println("The stockQuantity is : " + panel3.stockQuantity);
        System.out.println("The panelLength is : " + panel3.panelLength);
        System.out.println("The isEcoFriendly is : " + panel3.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel3.frameMaterial);
        System.out.println("The rating is : " + panel3.rating);
        System.out.println("The voltage is : " + panel3.voltage);
        System.out.println("The isCertified is : " + panel3.isCertified);
        System.out.println("The countryOfOrigin is : " + panel3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel3.manufacturingYear);
        System.out.println("The panelWidth is : " + panel3.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel3.supportsOffGrid);
        System.out.println("The certificationType is : " + panel3.certificationType);


        SolarPanel panel4 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel4.panelBrand);
        System.out.println("The panelId is : " + panel4.panelId);
        System.out.println("The panelPrice is : " + panel4.panelPrice);
        System.out.println("The isAvailable is : " + panel4.isAvailable);
        System.out.println("The panelType is : " + panel4.panelType);
        System.out.println("The powerOutputWatts is : " + panel4.powerOutputWatts);
        System.out.println("The weight is : " + panel4.weight);
        System.out.println("The isPortable is : " + panel4.isPortable);
        System.out.println("The cellType is : " + panel4.cellType);
        System.out.println("The warrantyYears is : " + panel4.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel4.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel4.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel4.color);
        System.out.println("The stockQuantity is : " + panel4.stockQuantity);
        System.out.println("The panelLength is : " + panel4.panelLength);
        System.out.println("The isEcoFriendly is : " + panel4.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel4.frameMaterial);
        System.out.println("The rating is : " + panel4.rating);
        System.out.println("The voltage is : " + panel4.voltage);
        System.out.println("The isCertified is : " + panel4.isCertified);
        System.out.println("The countryOfOrigin is : " + panel4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel4.manufacturingYear);
        System.out.println("The panelWidth is : " + panel4.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel4.supportsOffGrid);
        System.out.println("The certificationType is : " + panel4.certificationType);

        panel4.panelBrand = "SunPower";
        panel4.panelId = 4;
        panel4.panelPrice = 4000.75;
        panel4.isAvailable = true;
        panel4.panelType = "Monocrystalline";
        panel4.powerOutputWatts = 450.0;
        panel4.weight = 22.5;
        panel4.isPortable = false;
        panel4.cellType = "Mono";
        panel4.warrantyYears = 25;
        panel4.panelEfficiency = 21.5;
        panel4.hasAntiReflectiveCoating = true;
        panel4.color = "Blue";
        panel4.stockQuantity = 35;
        panel4.panelLength = 200.0;
        panel4.isEcoFriendly = true;
        panel4.frameMaterial = "Aluminum";
        panel4.rating = 5;
        panel4.voltage = 40.5;
        panel4.isCertified = true;
        panel4.countryOfOrigin = "China";
        panel4.manufacturingYear = 2025;
        panel4.panelWidth = 100.0;
        panel4.supportsOffGrid = true;
        panel4.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel4.panelBrand);
        System.out.println("The panelId is : " + panel4.panelId);
        System.out.println("The panelPrice is : " + panel4.panelPrice);
        System.out.println("The isAvailable is : " + panel4.isAvailable);
        System.out.println("The panelType is : " + panel4.panelType);
        System.out.println("The powerOutputWatts is : " + panel4.powerOutputWatts);
        System.out.println("The weight is : " + panel4.weight);
        System.out.println("The isPortable is : " + panel4.isPortable);
        System.out.println("The cellType is : " + panel4.cellType);
        System.out.println("The warrantyYears is : " + panel4.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel4.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel4.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel4.color);
        System.out.println("The stockQuantity is : " + panel4.stockQuantity);
        System.out.println("The panelLength is : " + panel4.panelLength);
        System.out.println("The isEcoFriendly is : " + panel4.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel4.frameMaterial);
        System.out.println("The rating is : " + panel4.rating);
        System.out.println("The voltage is : " + panel4.voltage);
        System.out.println("The isCertified is : " + panel4.isCertified);
        System.out.println("The countryOfOrigin is : " + panel4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel4.manufacturingYear);
        System.out.println("The panelWidth is : " + panel4.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel4.supportsOffGrid);
        System.out.println("The certificationType is : " + panel4.certificationType);


        SolarPanel panel5 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel5.panelBrand);
        System.out.println("The panelId is : " + panel5.panelId);
        System.out.println("The panelPrice is : " + panel5.panelPrice);
        System.out.println("The isAvailable is : " + panel5.isAvailable);
        System.out.println("The panelType is : " + panel5.panelType);
        System.out.println("The powerOutputWatts is : " + panel5.powerOutputWatts);
        System.out.println("The weight is : " + panel5.weight);
        System.out.println("The isPortable is : " + panel5.isPortable);
        System.out.println("The cellType is : " + panel5.cellType);
        System.out.println("The warrantyYears is : " + panel5.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel5.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel5.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel5.color);
        System.out.println("The stockQuantity is : " + panel5.stockQuantity);
        System.out.println("The panelLength is : " + panel5.panelLength);
        System.out.println("The isEcoFriendly is : " + panel5.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel5.frameMaterial);
        System.out.println("The rating is : " + panel5.rating);
        System.out.println("The voltage is : " + panel5.voltage);
        System.out.println("The isCertified is : " + panel5.isCertified);
        System.out.println("The countryOfOrigin is : " + panel5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel5.manufacturingYear);
        System.out.println("The panelWidth is : " + panel5.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel5.supportsOffGrid);
        System.out.println("The certificationType is : " + panel5.certificationType);

        panel5.panelBrand = "SunPower";
        panel5.panelId = 5;
        panel5.panelPrice = 5000.75;
        panel5.isAvailable = true;
        panel5.panelType = "Monocrystalline";
        panel5.powerOutputWatts = 450.0;
        panel5.weight = 22.5;
        panel5.isPortable = false;
        panel5.cellType = "Mono";
        panel5.warrantyYears = 25;
        panel5.panelEfficiency = 21.5;
        panel5.hasAntiReflectiveCoating = true;
        panel5.color = "Blue";
        panel5.stockQuantity = 35;
        panel5.panelLength = 200.0;
        panel5.isEcoFriendly = true;
        panel5.frameMaterial = "Aluminum";
        panel5.rating = 5;
        panel5.voltage = 40.5;
        panel5.isCertified = true;
        panel5.countryOfOrigin = "China";
        panel5.manufacturingYear = 2025;
        panel5.panelWidth = 100.0;
        panel5.supportsOffGrid = true;
        panel5.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel5.panelBrand);
        System.out.println("The panelId is : " + panel5.panelId);
        System.out.println("The panelPrice is : " + panel5.panelPrice);
        System.out.println("The isAvailable is : " + panel5.isAvailable);
        System.out.println("The panelType is : " + panel5.panelType);
        System.out.println("The powerOutputWatts is : " + panel5.powerOutputWatts);
        System.out.println("The weight is : " + panel5.weight);
        System.out.println("The isPortable is : " + panel5.isPortable);
        System.out.println("The cellType is : " + panel5.cellType);
        System.out.println("The warrantyYears is : " + panel5.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel5.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel5.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel5.color);
        System.out.println("The stockQuantity is : " + panel5.stockQuantity);
        System.out.println("The panelLength is : " + panel5.panelLength);
        System.out.println("The isEcoFriendly is : " + panel5.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel5.frameMaterial);
        System.out.println("The rating is : " + panel5.rating);
        System.out.println("The voltage is : " + panel5.voltage);
        System.out.println("The isCertified is : " + panel5.isCertified);
        System.out.println("The countryOfOrigin is : " + panel5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel5.manufacturingYear);
        System.out.println("The panelWidth is : " + panel5.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel5.supportsOffGrid);
        System.out.println("The certificationType is : " + panel5.certificationType);


        SolarPanel panel6 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel6.panelBrand);
        System.out.println("The panelId is : " + panel6.panelId);
        System.out.println("The panelPrice is : " + panel6.panelPrice);
        System.out.println("The isAvailable is : " + panel6.isAvailable);
        System.out.println("The panelType is : " + panel6.panelType);
        System.out.println("The powerOutputWatts is : " + panel6.powerOutputWatts);
        System.out.println("The weight is : " + panel6.weight);
        System.out.println("The isPortable is : " + panel6.isPortable);
        System.out.println("The cellType is : " + panel6.cellType);
        System.out.println("The warrantyYears is : " + panel6.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel6.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel6.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel6.color);
        System.out.println("The stockQuantity is : " + panel6.stockQuantity);
        System.out.println("The panelLength is : " + panel6.panelLength);
        System.out.println("The isEcoFriendly is : " + panel6.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel6.frameMaterial);
        System.out.println("The rating is : " + panel6.rating);
        System.out.println("The voltage is : " + panel6.voltage);
        System.out.println("The isCertified is : " + panel6.isCertified);
        System.out.println("The countryOfOrigin is : " + panel6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel6.manufacturingYear);
        System.out.println("The panelWidth is : " + panel6.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel6.supportsOffGrid);
        System.out.println("The certificationType is : " + panel6.certificationType);

        panel6.panelBrand = "SunPower";
        panel6.panelId = 6;
        panel6.panelPrice = 6000.75;
        panel6.isAvailable = true;
        panel6.panelType = "Monocrystalline";
        panel6.powerOutputWatts = 450.0;
        panel6.weight = 22.5;
        panel6.isPortable = false;
        panel6.cellType = "Mono";
        panel6.warrantyYears = 25;
        panel6.panelEfficiency = 21.5;
        panel6.hasAntiReflectiveCoating = true;
        panel6.color = "Blue";
        panel6.stockQuantity = 35;
        panel6.panelLength = 200.0;
        panel6.isEcoFriendly = true;
        panel6.frameMaterial = "Aluminum";
        panel6.rating = 5;
        panel6.voltage = 40.5;
        panel6.isCertified = true;
        panel6.countryOfOrigin = "China";
        panel6.manufacturingYear = 2025;
        panel6.panelWidth = 100.0;
        panel6.supportsOffGrid = true;
        panel6.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel6.panelBrand);
        System.out.println("The panelId is : " + panel6.panelId);
        System.out.println("The panelPrice is : " + panel6.panelPrice);
        System.out.println("The isAvailable is : " + panel6.isAvailable);
        System.out.println("The panelType is : " + panel6.panelType);
        System.out.println("The powerOutputWatts is : " + panel6.powerOutputWatts);
        System.out.println("The weight is : " + panel6.weight);
        System.out.println("The isPortable is : " + panel6.isPortable);
        System.out.println("The cellType is : " + panel6.cellType);
        System.out.println("The warrantyYears is : " + panel6.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel6.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel6.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel6.color);
        System.out.println("The stockQuantity is : " + panel6.stockQuantity);
        System.out.println("The panelLength is : " + panel6.panelLength);
        System.out.println("The isEcoFriendly is : " + panel6.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel6.frameMaterial);
        System.out.println("The rating is : " + panel6.rating);
        System.out.println("The voltage is : " + panel6.voltage);
        System.out.println("The isCertified is : " + panel6.isCertified);
        System.out.println("The countryOfOrigin is : " + panel6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel6.manufacturingYear);
        System.out.println("The panelWidth is : " + panel6.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel6.supportsOffGrid);
        System.out.println("The certificationType is : " + panel6.certificationType);


        SolarPanel panel7 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel7.panelBrand);
        System.out.println("The panelId is : " + panel7.panelId);
        System.out.println("The panelPrice is : " + panel7.panelPrice);
        System.out.println("The isAvailable is : " + panel7.isAvailable);
        System.out.println("The panelType is : " + panel7.panelType);
        System.out.println("The powerOutputWatts is : " + panel7.powerOutputWatts);
        System.out.println("The weight is : " + panel7.weight);
        System.out.println("The isPortable is : " + panel7.isPortable);
        System.out.println("The cellType is : " + panel7.cellType);
        System.out.println("The warrantyYears is : " + panel7.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel7.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel7.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel7.color);
        System.out.println("The stockQuantity is : " + panel7.stockQuantity);
        System.out.println("The panelLength is : " + panel7.panelLength);
        System.out.println("The isEcoFriendly is : " + panel7.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel7.frameMaterial);
        System.out.println("The rating is : " + panel7.rating);
        System.out.println("The voltage is : " + panel7.voltage);
        System.out.println("The isCertified is : " + panel7.isCertified);
        System.out.println("The countryOfOrigin is : " + panel7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel7.manufacturingYear);
        System.out.println("The panelWidth is : " + panel7.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel7.supportsOffGrid);
        System.out.println("The certificationType is : " + panel7.certificationType);

        panel7.panelBrand = "SunPower";
        panel7.panelId = 7;
        panel7.panelPrice = 7000.75;
        panel7.isAvailable = true;
        panel7.panelType = "Monocrystalline";
        panel7.powerOutputWatts = 450.0;
        panel7.weight = 22.5;
        panel7.isPortable = false;
        panel7.cellType = "Mono";
        panel7.warrantyYears = 25;
        panel7.panelEfficiency = 21.5;
        panel7.hasAntiReflectiveCoating = true;
        panel7.color = "Blue";
        panel7.stockQuantity = 35;
        panel7.panelLength = 200.0;
        panel7.isEcoFriendly = true;
        panel7.frameMaterial = "Aluminum";
        panel7.rating = 5;
        panel7.voltage = 40.5;
        panel7.isCertified = true;
        panel7.countryOfOrigin = "China";
        panel7.manufacturingYear = 2025;
        panel7.panelWidth = 100.0;
        panel7.supportsOffGrid = true;
        panel7.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel7.panelBrand);
        System.out.println("The panelId is : " + panel7.panelId);
        System.out.println("The panelPrice is : " + panel7.panelPrice);
        System.out.println("The isAvailable is : " + panel7.isAvailable);
        System.out.println("The panelType is : " + panel7.panelType);
        System.out.println("The powerOutputWatts is : " + panel7.powerOutputWatts);
        System.out.println("The weight is : " + panel7.weight);
        System.out.println("The isPortable is : " + panel7.isPortable);
        System.out.println("The cellType is : " + panel7.cellType);
        System.out.println("The warrantyYears is : " + panel7.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel7.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel7.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel7.color);
        System.out.println("The stockQuantity is : " + panel7.stockQuantity);
        System.out.println("The panelLength is : " + panel7.panelLength);
        System.out.println("The isEcoFriendly is : " + panel7.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel7.frameMaterial);
        System.out.println("The rating is : " + panel7.rating);
        System.out.println("The voltage is : " + panel7.voltage);
        System.out.println("The isCertified is : " + panel7.isCertified);
        System.out.println("The countryOfOrigin is : " + panel7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel7.manufacturingYear);
        System.out.println("The panelWidth is : " + panel7.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel7.supportsOffGrid);
        System.out.println("The certificationType is : " + panel7.certificationType);


        SolarPanel panel8 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel8.panelBrand);
        System.out.println("The panelId is : " + panel8.panelId);
        System.out.println("The panelPrice is : " + panel8.panelPrice);
        System.out.println("The isAvailable is : " + panel8.isAvailable);
        System.out.println("The panelType is : " + panel8.panelType);
        System.out.println("The powerOutputWatts is : " + panel8.powerOutputWatts);
        System.out.println("The weight is : " + panel8.weight);
        System.out.println("The isPortable is : " + panel8.isPortable);
        System.out.println("The cellType is : " + panel8.cellType);
        System.out.println("The warrantyYears is : " + panel8.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel8.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel8.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel8.color);
        System.out.println("The stockQuantity is : " + panel8.stockQuantity);
        System.out.println("The panelLength is : " + panel8.panelLength);
        System.out.println("The isEcoFriendly is : " + panel8.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel8.frameMaterial);
        System.out.println("The rating is : " + panel8.rating);
        System.out.println("The voltage is : " + panel8.voltage);
        System.out.println("The isCertified is : " + panel8.isCertified);
        System.out.println("The countryOfOrigin is : " + panel8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel8.manufacturingYear);
        System.out.println("The panelWidth is : " + panel8.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel8.supportsOffGrid);
        System.out.println("The certificationType is : " + panel8.certificationType);

        panel8.panelBrand = "SunPower";
        panel8.panelId = 8;
        panel8.panelPrice = 8000.75;
        panel8.isAvailable = true;
        panel8.panelType = "Monocrystalline";
        panel8.powerOutputWatts = 450.0;
        panel8.weight = 22.5;
        panel8.isPortable = false;
        panel8.cellType = "Mono";
        panel8.warrantyYears = 25;
        panel8.panelEfficiency = 21.5;
        panel8.hasAntiReflectiveCoating = true;
        panel8.color = "Blue";
        panel8.stockQuantity = 35;
        panel8.panelLength = 200.0;
        panel8.isEcoFriendly = true;
        panel8.frameMaterial = "Aluminum";
        panel8.rating = 5;
        panel8.voltage = 40.5;
        panel8.isCertified = true;
        panel8.countryOfOrigin = "China";
        panel8.manufacturingYear = 2025;
        panel8.panelWidth = 100.0;
        panel8.supportsOffGrid = true;
        panel8.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel8.panelBrand);
        System.out.println("The panelId is : " + panel8.panelId);
        System.out.println("The panelPrice is : " + panel8.panelPrice);
        System.out.println("The isAvailable is : " + panel8.isAvailable);
        System.out.println("The panelType is : " + panel8.panelType);
        System.out.println("The powerOutputWatts is : " + panel8.powerOutputWatts);
        System.out.println("The weight is : " + panel8.weight);
        System.out.println("The isPortable is : " + panel8.isPortable);
        System.out.println("The cellType is : " + panel8.cellType);
        System.out.println("The warrantyYears is : " + panel8.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel8.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel8.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel8.color);
        System.out.println("The stockQuantity is : " + panel8.stockQuantity);
        System.out.println("The panelLength is : " + panel8.panelLength);
        System.out.println("The isEcoFriendly is : " + panel8.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel8.frameMaterial);
        System.out.println("The rating is : " + panel8.rating);
        System.out.println("The voltage is : " + panel8.voltage);
        System.out.println("The isCertified is : " + panel8.isCertified);
        System.out.println("The countryOfOrigin is : " + panel8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel8.manufacturingYear);
        System.out.println("The panelWidth is : " + panel8.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel8.supportsOffGrid);
        System.out.println("The certificationType is : " + panel8.certificationType);


        SolarPanel panel9 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel9.panelBrand);
        System.out.println("The panelId is : " + panel9.panelId);
        System.out.println("The panelPrice is : " + panel9.panelPrice);
        System.out.println("The isAvailable is : " + panel9.isAvailable);
        System.out.println("The panelType is : " + panel9.panelType);
        System.out.println("The powerOutputWatts is : " + panel9.powerOutputWatts);
        System.out.println("The weight is : " + panel9.weight);
        System.out.println("The isPortable is : " + panel9.isPortable);
        System.out.println("The cellType is : " + panel9.cellType);
        System.out.println("The warrantyYears is : " + panel9.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel9.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel9.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel9.color);
        System.out.println("The stockQuantity is : " + panel9.stockQuantity);
        System.out.println("The panelLength is : " + panel9.panelLength);
        System.out.println("The isEcoFriendly is : " + panel9.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel9.frameMaterial);
        System.out.println("The rating is : " + panel9.rating);
        System.out.println("The voltage is : " + panel9.voltage);
        System.out.println("The isCertified is : " + panel9.isCertified);
        System.out.println("The countryOfOrigin is : " + panel9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel9.manufacturingYear);
        System.out.println("The panelWidth is : " + panel9.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel9.supportsOffGrid);
        System.out.println("The certificationType is : " + panel9.certificationType);

        panel9.panelBrand = "SunPower";
        panel9.panelId = 9;
        panel9.panelPrice = 9000.75;
        panel9.isAvailable = true;
        panel9.panelType = "Monocrystalline";
        panel9.powerOutputWatts = 450.0;
        panel9.weight = 22.5;
        panel9.isPortable = false;
        panel9.cellType = "Mono";
        panel9.warrantyYears = 25;
        panel9.panelEfficiency = 21.5;
        panel9.hasAntiReflectiveCoating = true;
        panel9.color = "Blue";
        panel9.stockQuantity = 35;
        panel9.panelLength = 200.0;
        panel9.isEcoFriendly = true;
        panel9.frameMaterial = "Aluminum";
        panel9.rating = 5;
        panel9.voltage = 40.5;
        panel9.isCertified = true;
        panel9.countryOfOrigin = "China";
        panel9.manufacturingYear = 2025;
        panel9.panelWidth = 100.0;
        panel9.supportsOffGrid = true;
        panel9.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel9.panelBrand);
        System.out.println("The panelId is : " + panel9.panelId);
        System.out.println("The panelPrice is : " + panel9.panelPrice);
        System.out.println("The isAvailable is : " + panel9.isAvailable);
        System.out.println("The panelType is : " + panel9.panelType);
        System.out.println("The powerOutputWatts is : " + panel9.powerOutputWatts);
        System.out.println("The weight is : " + panel9.weight);
        System.out.println("The isPortable is : " + panel9.isPortable);
        System.out.println("The cellType is : " + panel9.cellType);
        System.out.println("The warrantyYears is : " + panel9.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel9.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel9.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel9.color);
        System.out.println("The stockQuantity is : " + panel9.stockQuantity);
        System.out.println("The panelLength is : " + panel9.panelLength);
        System.out.println("The isEcoFriendly is : " + panel9.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel9.frameMaterial);
        System.out.println("The rating is : " + panel9.rating);
        System.out.println("The voltage is : " + panel9.voltage);
        System.out.println("The isCertified is : " + panel9.isCertified);
        System.out.println("The countryOfOrigin is : " + panel9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel9.manufacturingYear);
        System.out.println("The panelWidth is : " + panel9.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel9.supportsOffGrid);
        System.out.println("The certificationType is : " + panel9.certificationType);


        SolarPanel panel10 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel10.panelBrand);
        System.out.println("The panelId is : " + panel10.panelId);
        System.out.println("The panelPrice is : " + panel10.panelPrice);
        System.out.println("The isAvailable is : " + panel10.isAvailable);
        System.out.println("The panelType is : " + panel10.panelType);
        System.out.println("The powerOutputWatts is : " + panel10.powerOutputWatts);
        System.out.println("The weight is : " + panel10.weight);
        System.out.println("The isPortable is : " + panel10.isPortable);
        System.out.println("The cellType is : " + panel10.cellType);
        System.out.println("The warrantyYears is : " + panel10.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel10.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel10.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel10.color);
        System.out.println("The stockQuantity is : " + panel10.stockQuantity);
        System.out.println("The panelLength is : " + panel10.panelLength);
        System.out.println("The isEcoFriendly is : " + panel10.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel10.frameMaterial);
        System.out.println("The rating is : " + panel10.rating);
        System.out.println("The voltage is : " + panel10.voltage);
        System.out.println("The isCertified is : " + panel10.isCertified);
        System.out.println("The countryOfOrigin is : " + panel10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel10.manufacturingYear);
        System.out.println("The panelWidth is : " + panel10.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel10.supportsOffGrid);
        System.out.println("The certificationType is : " + panel10.certificationType);

        panel10.panelBrand = "SunPower";
        panel10.panelId = 10;
        panel10.panelPrice = 10000.75;
        panel10.isAvailable = true;
        panel10.panelType = "Monocrystalline";
        panel10.powerOutputWatts = 450.0;
        panel10.weight = 22.5;
        panel10.isPortable = false;
        panel10.cellType = "Mono";
        panel10.warrantyYears = 25;
        panel10.panelEfficiency = 21.5;
        panel10.hasAntiReflectiveCoating = true;
        panel10.color = "Blue";
        panel10.stockQuantity = 35;
        panel10.panelLength = 200.0;
        panel10.isEcoFriendly = true;
        panel10.frameMaterial = "Aluminum";
        panel10.rating = 5;
        panel10.voltage = 40.5;
        panel10.isCertified = true;
        panel10.countryOfOrigin = "China";
        panel10.manufacturingYear = 2025;
        panel10.panelWidth = 100.0;
        panel10.supportsOffGrid = true;
        panel10.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel10.panelBrand);
        System.out.println("The panelId is : " + panel10.panelId);
        System.out.println("The panelPrice is : " + panel10.panelPrice);
        System.out.println("The isAvailable is : " + panel10.isAvailable);
        System.out.println("The panelType is : " + panel10.panelType);
        System.out.println("The powerOutputWatts is : " + panel10.powerOutputWatts);
        System.out.println("The weight is : " + panel10.weight);
        System.out.println("The isPortable is : " + panel10.isPortable);
        System.out.println("The cellType is : " + panel10.cellType);
        System.out.println("The warrantyYears is : " + panel10.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel10.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel10.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel10.color);
        System.out.println("The stockQuantity is : " + panel10.stockQuantity);
        System.out.println("The panelLength is : " + panel10.panelLength);
        System.out.println("The isEcoFriendly is : " + panel10.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel10.frameMaterial);
        System.out.println("The rating is : " + panel10.rating);
        System.out.println("The voltage is : " + panel10.voltage);
        System.out.println("The isCertified is : " + panel10.isCertified);
        System.out.println("The countryOfOrigin is : " + panel10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel10.manufacturingYear);
        System.out.println("The panelWidth is : " + panel10.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel10.supportsOffGrid);
        System.out.println("The certificationType is : " + panel10.certificationType);


        SolarPanel panel11 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel11.panelBrand);
        System.out.println("The panelId is : " + panel11.panelId);
        System.out.println("The panelPrice is : " + panel11.panelPrice);
        System.out.println("The isAvailable is : " + panel11.isAvailable);
        System.out.println("The panelType is : " + panel11.panelType);
        System.out.println("The powerOutputWatts is : " + panel11.powerOutputWatts);
        System.out.println("The weight is : " + panel11.weight);
        System.out.println("The isPortable is : " + panel11.isPortable);
        System.out.println("The cellType is : " + panel11.cellType);
        System.out.println("The warrantyYears is : " + panel11.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel11.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel11.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel11.color);
        System.out.println("The stockQuantity is : " + panel11.stockQuantity);
        System.out.println("The panelLength is : " + panel11.panelLength);
        System.out.println("The isEcoFriendly is : " + panel11.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel11.frameMaterial);
        System.out.println("The rating is : " + panel11.rating);
        System.out.println("The voltage is : " + panel11.voltage);
        System.out.println("The isCertified is : " + panel11.isCertified);
        System.out.println("The countryOfOrigin is : " + panel11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel11.manufacturingYear);
        System.out.println("The panelWidth is : " + panel11.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel11.supportsOffGrid);
        System.out.println("The certificationType is : " + panel11.certificationType);

        panel11.panelBrand = "SunPower";
        panel11.panelId = 11;
        panel11.panelPrice = 11000.75;
        panel11.isAvailable = true;
        panel11.panelType = "Monocrystalline";
        panel11.powerOutputWatts = 450.0;
        panel11.weight = 22.5;
        panel11.isPortable = false;
        panel11.cellType = "Mono";
        panel11.warrantyYears = 25;
        panel11.panelEfficiency = 21.5;
        panel11.hasAntiReflectiveCoating = true;
        panel11.color = "Blue";
        panel11.stockQuantity = 35;
        panel11.panelLength = 200.0;
        panel11.isEcoFriendly = true;
        panel11.frameMaterial = "Aluminum";
        panel11.rating = 5;
        panel11.voltage = 40.5;
        panel11.isCertified = true;
        panel11.countryOfOrigin = "China";
        panel11.manufacturingYear = 2025;
        panel11.panelWidth = 100.0;
        panel11.supportsOffGrid = true;
        panel11.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel11.panelBrand);
        System.out.println("The panelId is : " + panel11.panelId);
        System.out.println("The panelPrice is : " + panel11.panelPrice);
        System.out.println("The isAvailable is : " + panel11.isAvailable);
        System.out.println("The panelType is : " + panel11.panelType);
        System.out.println("The powerOutputWatts is : " + panel11.powerOutputWatts);
        System.out.println("The weight is : " + panel11.weight);
        System.out.println("The isPortable is : " + panel11.isPortable);
        System.out.println("The cellType is : " + panel11.cellType);
        System.out.println("The warrantyYears is : " + panel11.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel11.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel11.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel11.color);
        System.out.println("The stockQuantity is : " + panel11.stockQuantity);
        System.out.println("The panelLength is : " + panel11.panelLength);
        System.out.println("The isEcoFriendly is : " + panel11.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel11.frameMaterial);
        System.out.println("The rating is : " + panel11.rating);
        System.out.println("The voltage is : " + panel11.voltage);
        System.out.println("The isCertified is : " + panel11.isCertified);
        System.out.println("The countryOfOrigin is : " + panel11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel11.manufacturingYear);
        System.out.println("The panelWidth is : " + panel11.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel11.supportsOffGrid);
        System.out.println("The certificationType is : " + panel11.certificationType);


        SolarPanel panel12 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel12.panelBrand);
        System.out.println("The panelId is : " + panel12.panelId);
        System.out.println("The panelPrice is : " + panel12.panelPrice);
        System.out.println("The isAvailable is : " + panel12.isAvailable);
        System.out.println("The panelType is : " + panel12.panelType);
        System.out.println("The powerOutputWatts is : " + panel12.powerOutputWatts);
        System.out.println("The weight is : " + panel12.weight);
        System.out.println("The isPortable is : " + panel12.isPortable);
        System.out.println("The cellType is : " + panel12.cellType);
        System.out.println("The warrantyYears is : " + panel12.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel12.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel12.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel12.color);
        System.out.println("The stockQuantity is : " + panel12.stockQuantity);
        System.out.println("The panelLength is : " + panel12.panelLength);
        System.out.println("The isEcoFriendly is : " + panel12.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel12.frameMaterial);
        System.out.println("The rating is : " + panel12.rating);
        System.out.println("The voltage is : " + panel12.voltage);
        System.out.println("The isCertified is : " + panel12.isCertified);
        System.out.println("The countryOfOrigin is : " + panel12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel12.manufacturingYear);
        System.out.println("The panelWidth is : " + panel12.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel12.supportsOffGrid);
        System.out.println("The certificationType is : " + panel12.certificationType);

        panel12.panelBrand = "SunPower";
        panel12.panelId = 12;
        panel12.panelPrice = 12000.75;
        panel12.isAvailable = true;
        panel12.panelType = "Monocrystalline";
        panel12.powerOutputWatts = 450.0;
        panel12.weight = 22.5;
        panel12.isPortable = false;
        panel12.cellType = "Mono";
        panel12.warrantyYears = 25;
        panel12.panelEfficiency = 21.5;
        panel12.hasAntiReflectiveCoating = true;
        panel12.color = "Blue";
        panel12.stockQuantity = 35;
        panel12.panelLength = 200.0;
        panel12.isEcoFriendly = true;
        panel12.frameMaterial = "Aluminum";
        panel12.rating = 5;
        panel12.voltage = 40.5;
        panel12.isCertified = true;
        panel12.countryOfOrigin = "China";
        panel12.manufacturingYear = 2025;
        panel12.panelWidth = 100.0;
        panel12.supportsOffGrid = true;
        panel12.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel12.panelBrand);
        System.out.println("The panelId is : " + panel12.panelId);
        System.out.println("The panelPrice is : " + panel12.panelPrice);
        System.out.println("The isAvailable is : " + panel12.isAvailable);
        System.out.println("The panelType is : " + panel12.panelType);
        System.out.println("The powerOutputWatts is : " + panel12.powerOutputWatts);
        System.out.println("The weight is : " + panel12.weight);
        System.out.println("The isPortable is : " + panel12.isPortable);
        System.out.println("The cellType is : " + panel12.cellType);
        System.out.println("The warrantyYears is : " + panel12.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel12.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel12.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel12.color);
        System.out.println("The stockQuantity is : " + panel12.stockQuantity);
        System.out.println("The panelLength is : " + panel12.panelLength);
        System.out.println("The isEcoFriendly is : " + panel12.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel12.frameMaterial);
        System.out.println("The rating is : " + panel12.rating);
        System.out.println("The voltage is : " + panel12.voltage);
        System.out.println("The isCertified is : " + panel12.isCertified);
        System.out.println("The countryOfOrigin is : " + panel12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel12.manufacturingYear);
        System.out.println("The panelWidth is : " + panel12.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel12.supportsOffGrid);
        System.out.println("The certificationType is : " + panel12.certificationType);


        SolarPanel panel13 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel13.panelBrand);
        System.out.println("The panelId is : " + panel13.panelId);
        System.out.println("The panelPrice is : " + panel13.panelPrice);
        System.out.println("The isAvailable is : " + panel13.isAvailable);
        System.out.println("The panelType is : " + panel13.panelType);
        System.out.println("The powerOutputWatts is : " + panel13.powerOutputWatts);
        System.out.println("The weight is : " + panel13.weight);
        System.out.println("The isPortable is : " + panel13.isPortable);
        System.out.println("The cellType is : " + panel13.cellType);
        System.out.println("The warrantyYears is : " + panel13.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel13.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel13.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel13.color);
        System.out.println("The stockQuantity is : " + panel13.stockQuantity);
        System.out.println("The panelLength is : " + panel13.panelLength);
        System.out.println("The isEcoFriendly is : " + panel13.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel13.frameMaterial);
        System.out.println("The rating is : " + panel13.rating);
        System.out.println("The voltage is : " + panel13.voltage);
        System.out.println("The isCertified is : " + panel13.isCertified);
        System.out.println("The countryOfOrigin is : " + panel13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel13.manufacturingYear);
        System.out.println("The panelWidth is : " + panel13.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel13.supportsOffGrid);
        System.out.println("The certificationType is : " + panel13.certificationType);

        panel13.panelBrand = "SunPower";
        panel13.panelId = 13;
        panel13.panelPrice = 13000.75;
        panel13.isAvailable = true;
        panel13.panelType = "Monocrystalline";
        panel13.powerOutputWatts = 450.0;
        panel13.weight = 22.5;
        panel13.isPortable = false;
        panel13.cellType = "Mono";
        panel13.warrantyYears = 25;
        panel13.panelEfficiency = 21.5;
        panel13.hasAntiReflectiveCoating = true;
        panel13.color = "Blue";
        panel13.stockQuantity = 35;
        panel13.panelLength = 200.0;
        panel13.isEcoFriendly = true;
        panel13.frameMaterial = "Aluminum";
        panel13.rating = 5;
        panel13.voltage = 40.5;
        panel13.isCertified = true;
        panel13.countryOfOrigin = "China";
        panel13.manufacturingYear = 2025;
        panel13.panelWidth = 100.0;
        panel13.supportsOffGrid = true;
        panel13.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel13.panelBrand);
        System.out.println("The panelId is : " + panel13.panelId);
        System.out.println("The panelPrice is : " + panel13.panelPrice);
        System.out.println("The isAvailable is : " + panel13.isAvailable);
        System.out.println("The panelType is : " + panel13.panelType);
        System.out.println("The powerOutputWatts is : " + panel13.powerOutputWatts);
        System.out.println("The weight is : " + panel13.weight);
        System.out.println("The isPortable is : " + panel13.isPortable);
        System.out.println("The cellType is : " + panel13.cellType);
        System.out.println("The warrantyYears is : " + panel13.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel13.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel13.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel13.color);
        System.out.println("The stockQuantity is : " + panel13.stockQuantity);
        System.out.println("The panelLength is : " + panel13.panelLength);
        System.out.println("The isEcoFriendly is : " + panel13.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel13.frameMaterial);
        System.out.println("The rating is : " + panel13.rating);
        System.out.println("The voltage is : " + panel13.voltage);
        System.out.println("The isCertified is : " + panel13.isCertified);
        System.out.println("The countryOfOrigin is : " + panel13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel13.manufacturingYear);
        System.out.println("The panelWidth is : " + panel13.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel13.supportsOffGrid);
        System.out.println("The certificationType is : " + panel13.certificationType);


        SolarPanel panel14 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel14.panelBrand);
        System.out.println("The panelId is : " + panel14.panelId);
        System.out.println("The panelPrice is : " + panel14.panelPrice);
        System.out.println("The isAvailable is : " + panel14.isAvailable);
        System.out.println("The panelType is : " + panel14.panelType);
        System.out.println("The powerOutputWatts is : " + panel14.powerOutputWatts);
        System.out.println("The weight is : " + panel14.weight);
        System.out.println("The isPortable is : " + panel14.isPortable);
        System.out.println("The cellType is : " + panel14.cellType);
        System.out.println("The warrantyYears is : " + panel14.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel14.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel14.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel14.color);
        System.out.println("The stockQuantity is : " + panel14.stockQuantity);
        System.out.println("The panelLength is : " + panel14.panelLength);
        System.out.println("The isEcoFriendly is : " + panel14.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel14.frameMaterial);
        System.out.println("The rating is : " + panel14.rating);
        System.out.println("The voltage is : " + panel14.voltage);
        System.out.println("The isCertified is : " + panel14.isCertified);
        System.out.println("The countryOfOrigin is : " + panel14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel14.manufacturingYear);
        System.out.println("The panelWidth is : " + panel14.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel14.supportsOffGrid);
        System.out.println("The certificationType is : " + panel14.certificationType);

        panel14.panelBrand = "SunPower";
        panel14.panelId = 14;
        panel14.panelPrice = 14000.75;
        panel14.isAvailable = true;
        panel14.panelType = "Monocrystalline";
        panel14.powerOutputWatts = 450.0;
        panel14.weight = 22.5;
        panel14.isPortable = false;
        panel14.cellType = "Mono";
        panel14.warrantyYears = 25;
        panel14.panelEfficiency = 21.5;
        panel14.hasAntiReflectiveCoating = true;
        panel14.color = "Blue";
        panel14.stockQuantity = 35;
        panel14.panelLength = 200.0;
        panel14.isEcoFriendly = true;
        panel14.frameMaterial = "Aluminum";
        panel14.rating = 5;
        panel14.voltage = 40.5;
        panel14.isCertified = true;
        panel14.countryOfOrigin = "China";
        panel14.manufacturingYear = 2025;
        panel14.panelWidth = 100.0;
        panel14.supportsOffGrid = true;
        panel14.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel14.panelBrand);
        System.out.println("The panelId is : " + panel14.panelId);
        System.out.println("The panelPrice is : " + panel14.panelPrice);
        System.out.println("The isAvailable is : " + panel14.isAvailable);
        System.out.println("The panelType is : " + panel14.panelType);
        System.out.println("The powerOutputWatts is : " + panel14.powerOutputWatts);
        System.out.println("The weight is : " + panel14.weight);
        System.out.println("The isPortable is : " + panel14.isPortable);
        System.out.println("The cellType is : " + panel14.cellType);
        System.out.println("The warrantyYears is : " + panel14.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel14.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel14.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel14.color);
        System.out.println("The stockQuantity is : " + panel14.stockQuantity);
        System.out.println("The panelLength is : " + panel14.panelLength);
        System.out.println("The isEcoFriendly is : " + panel14.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel14.frameMaterial);
        System.out.println("The rating is : " + panel14.rating);
        System.out.println("The voltage is : " + panel14.voltage);
        System.out.println("The isCertified is : " + panel14.isCertified);
        System.out.println("The countryOfOrigin is : " + panel14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel14.manufacturingYear);
        System.out.println("The panelWidth is : " + panel14.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel14.supportsOffGrid);
        System.out.println("The certificationType is : " + panel14.certificationType);


        SolarPanel panel15 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel15.panelBrand);
        System.out.println("The panelId is : " + panel15.panelId);
        System.out.println("The panelPrice is : " + panel15.panelPrice);
        System.out.println("The isAvailable is : " + panel15.isAvailable);
        System.out.println("The panelType is : " + panel15.panelType);
        System.out.println("The powerOutputWatts is : " + panel15.powerOutputWatts);
        System.out.println("The weight is : " + panel15.weight);
        System.out.println("The isPortable is : " + panel15.isPortable);
        System.out.println("The cellType is : " + panel15.cellType);
        System.out.println("The warrantyYears is : " + panel15.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel15.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel15.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel15.color);
        System.out.println("The stockQuantity is : " + panel15.stockQuantity);
        System.out.println("The panelLength is : " + panel15.panelLength);
        System.out.println("The isEcoFriendly is : " + panel15.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel15.frameMaterial);
        System.out.println("The rating is : " + panel15.rating);
        System.out.println("The voltage is : " + panel15.voltage);
        System.out.println("The isCertified is : " + panel15.isCertified);
        System.out.println("The countryOfOrigin is : " + panel15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel15.manufacturingYear);
        System.out.println("The panelWidth is : " + panel15.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel15.supportsOffGrid);
        System.out.println("The certificationType is : " + panel15.certificationType);

        panel15.panelBrand = "SunPower";
        panel15.panelId = 15;
        panel15.panelPrice = 15000.75;
        panel15.isAvailable = true;
        panel15.panelType = "Monocrystalline";
        panel15.powerOutputWatts = 450.0;
        panel15.weight = 22.5;
        panel15.isPortable = false;
        panel15.cellType = "Mono";
        panel15.warrantyYears = 25;
        panel15.panelEfficiency = 21.5;
        panel15.hasAntiReflectiveCoating = true;
        panel15.color = "Blue";
        panel15.stockQuantity = 35;
        panel15.panelLength = 200.0;
        panel15.isEcoFriendly = true;
        panel15.frameMaterial = "Aluminum";
        panel15.rating = 5;
        panel15.voltage = 40.5;
        panel15.isCertified = true;
        panel15.countryOfOrigin = "China";
        panel15.manufacturingYear = 2025;
        panel15.panelWidth = 100.0;
        panel15.supportsOffGrid = true;
        panel15.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel15.panelBrand);
        System.out.println("The panelId is : " + panel15.panelId);
        System.out.println("The panelPrice is : " + panel15.panelPrice);
        System.out.println("The isAvailable is : " + panel15.isAvailable);
        System.out.println("The panelType is : " + panel15.panelType);
        System.out.println("The powerOutputWatts is : " + panel15.powerOutputWatts);
        System.out.println("The weight is : " + panel15.weight);
        System.out.println("The isPortable is : " + panel15.isPortable);
        System.out.println("The cellType is : " + panel15.cellType);
        System.out.println("The warrantyYears is : " + panel15.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel15.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel15.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel15.color);
        System.out.println("The stockQuantity is : " + panel15.stockQuantity);
        System.out.println("The panelLength is : " + panel15.panelLength);
        System.out.println("The isEcoFriendly is : " + panel15.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel15.frameMaterial);
        System.out.println("The rating is : " + panel15.rating);
        System.out.println("The voltage is : " + panel15.voltage);
        System.out.println("The isCertified is : " + panel15.isCertified);
        System.out.println("The countryOfOrigin is : " + panel15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel15.manufacturingYear);
        System.out.println("The panelWidth is : " + panel15.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel15.supportsOffGrid);
        System.out.println("The certificationType is : " + panel15.certificationType);


        SolarPanel panel16 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel16.panelBrand);
        System.out.println("The panelId is : " + panel16.panelId);
        System.out.println("The panelPrice is : " + panel16.panelPrice);
        System.out.println("The isAvailable is : " + panel16.isAvailable);
        System.out.println("The panelType is : " + panel16.panelType);
        System.out.println("The powerOutputWatts is : " + panel16.powerOutputWatts);
        System.out.println("The weight is : " + panel16.weight);
        System.out.println("The isPortable is : " + panel16.isPortable);
        System.out.println("The cellType is : " + panel16.cellType);
        System.out.println("The warrantyYears is : " + panel16.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel16.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel16.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel16.color);
        System.out.println("The stockQuantity is : " + panel16.stockQuantity);
        System.out.println("The panelLength is : " + panel16.panelLength);
        System.out.println("The isEcoFriendly is : " + panel16.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel16.frameMaterial);
        System.out.println("The rating is : " + panel16.rating);
        System.out.println("The voltage is : " + panel16.voltage);
        System.out.println("The isCertified is : " + panel16.isCertified);
        System.out.println("The countryOfOrigin is : " + panel16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel16.manufacturingYear);
        System.out.println("The panelWidth is : " + panel16.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel16.supportsOffGrid);
        System.out.println("The certificationType is : " + panel16.certificationType);

        panel16.panelBrand = "SunPower";
        panel16.panelId = 16;
        panel16.panelPrice = 16000.75;
        panel16.isAvailable = true;
        panel16.panelType = "Monocrystalline";
        panel16.powerOutputWatts = 450.0;
        panel16.weight = 22.5;
        panel16.isPortable = false;
        panel16.cellType = "Mono";
        panel16.warrantyYears = 25;
        panel16.panelEfficiency = 21.5;
        panel16.hasAntiReflectiveCoating = true;
        panel16.color = "Blue";
        panel16.stockQuantity = 35;
        panel16.panelLength = 200.0;
        panel16.isEcoFriendly = true;
        panel16.frameMaterial = "Aluminum";
        panel16.rating = 5;
        panel16.voltage = 40.5;
        panel16.isCertified = true;
        panel16.countryOfOrigin = "China";
        panel16.manufacturingYear = 2025;
        panel16.panelWidth = 100.0;
        panel16.supportsOffGrid = true;
        panel16.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel16.panelBrand);
        System.out.println("The panelId is : " + panel16.panelId);
        System.out.println("The panelPrice is : " + panel16.panelPrice);
        System.out.println("The isAvailable is : " + panel16.isAvailable);
        System.out.println("The panelType is : " + panel16.panelType);
        System.out.println("The powerOutputWatts is : " + panel16.powerOutputWatts);
        System.out.println("The weight is : " + panel16.weight);
        System.out.println("The isPortable is : " + panel16.isPortable);
        System.out.println("The cellType is : " + panel16.cellType);
        System.out.println("The warrantyYears is : " + panel16.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel16.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel16.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel16.color);
        System.out.println("The stockQuantity is : " + panel16.stockQuantity);
        System.out.println("The panelLength is : " + panel16.panelLength);
        System.out.println("The isEcoFriendly is : " + panel16.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel16.frameMaterial);
        System.out.println("The rating is : " + panel16.rating);
        System.out.println("The voltage is : " + panel16.voltage);
        System.out.println("The isCertified is : " + panel16.isCertified);
        System.out.println("The countryOfOrigin is : " + panel16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel16.manufacturingYear);
        System.out.println("The panelWidth is : " + panel16.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel16.supportsOffGrid);
        System.out.println("The certificationType is : " + panel16.certificationType);


        SolarPanel panel17 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel17.panelBrand);
        System.out.println("The panelId is : " + panel17.panelId);
        System.out.println("The panelPrice is : " + panel17.panelPrice);
        System.out.println("The isAvailable is : " + panel17.isAvailable);
        System.out.println("The panelType is : " + panel17.panelType);
        System.out.println("The powerOutputWatts is : " + panel17.powerOutputWatts);
        System.out.println("The weight is : " + panel17.weight);
        System.out.println("The isPortable is : " + panel17.isPortable);
        System.out.println("The cellType is : " + panel17.cellType);
        System.out.println("The warrantyYears is : " + panel17.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel17.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel17.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel17.color);
        System.out.println("The stockQuantity is : " + panel17.stockQuantity);
        System.out.println("The panelLength is : " + panel17.panelLength);
        System.out.println("The isEcoFriendly is : " + panel17.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel17.frameMaterial);
        System.out.println("The rating is : " + panel17.rating);
        System.out.println("The voltage is : " + panel17.voltage);
        System.out.println("The isCertified is : " + panel17.isCertified);
        System.out.println("The countryOfOrigin is : " + panel17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel17.manufacturingYear);
        System.out.println("The panelWidth is : " + panel17.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel17.supportsOffGrid);
        System.out.println("The certificationType is : " + panel17.certificationType);

        panel17.panelBrand = "SunPower";
        panel17.panelId = 17;
        panel17.panelPrice = 17000.75;
        panel17.isAvailable = true;
        panel17.panelType = "Monocrystalline";
        panel17.powerOutputWatts = 450.0;
        panel17.weight = 22.5;
        panel17.isPortable = false;
        panel17.cellType = "Mono";
        panel17.warrantyYears = 25;
        panel17.panelEfficiency = 21.5;
        panel17.hasAntiReflectiveCoating = true;
        panel17.color = "Blue";
        panel17.stockQuantity = 35;
        panel17.panelLength = 200.0;
        panel17.isEcoFriendly = true;
        panel17.frameMaterial = "Aluminum";
        panel17.rating = 5;
        panel17.voltage = 40.5;
        panel17.isCertified = true;
        panel17.countryOfOrigin = "China";
        panel17.manufacturingYear = 2025;
        panel17.panelWidth = 100.0;
        panel17.supportsOffGrid = true;
        panel17.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel17.panelBrand);
        System.out.println("The panelId is : " + panel17.panelId);
        System.out.println("The panelPrice is : " + panel17.panelPrice);
        System.out.println("The isAvailable is : " + panel17.isAvailable);
        System.out.println("The panelType is : " + panel17.panelType);
        System.out.println("The powerOutputWatts is : " + panel17.powerOutputWatts);
        System.out.println("The weight is : " + panel17.weight);
        System.out.println("The isPortable is : " + panel17.isPortable);
        System.out.println("The cellType is : " + panel17.cellType);
        System.out.println("The warrantyYears is : " + panel17.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel17.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel17.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel17.color);
        System.out.println("The stockQuantity is : " + panel17.stockQuantity);
        System.out.println("The panelLength is : " + panel17.panelLength);
        System.out.println("The isEcoFriendly is : " + panel17.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel17.frameMaterial);
        System.out.println("The rating is : " + panel17.rating);
        System.out.println("The voltage is : " + panel17.voltage);
        System.out.println("The isCertified is : " + panel17.isCertified);
        System.out.println("The countryOfOrigin is : " + panel17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel17.manufacturingYear);
        System.out.println("The panelWidth is : " + panel17.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel17.supportsOffGrid);
        System.out.println("The certificationType is : " + panel17.certificationType);


        SolarPanel panel18 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel18.panelBrand);
        System.out.println("The panelId is : " + panel18.panelId);
        System.out.println("The panelPrice is : " + panel18.panelPrice);
        System.out.println("The isAvailable is : " + panel18.isAvailable);
        System.out.println("The panelType is : " + panel18.panelType);
        System.out.println("The powerOutputWatts is : " + panel18.powerOutputWatts);
        System.out.println("The weight is : " + panel18.weight);
        System.out.println("The isPortable is : " + panel18.isPortable);
        System.out.println("The cellType is : " + panel18.cellType);
        System.out.println("The warrantyYears is : " + panel18.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel18.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel18.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel18.color);
        System.out.println("The stockQuantity is : " + panel18.stockQuantity);
        System.out.println("The panelLength is : " + panel18.panelLength);
        System.out.println("The isEcoFriendly is : " + panel18.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel18.frameMaterial);
        System.out.println("The rating is : " + panel18.rating);
        System.out.println("The voltage is : " + panel18.voltage);
        System.out.println("The isCertified is : " + panel18.isCertified);
        System.out.println("The countryOfOrigin is : " + panel18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel18.manufacturingYear);
        System.out.println("The panelWidth is : " + panel18.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel18.supportsOffGrid);
        System.out.println("The certificationType is : " + panel18.certificationType);

        panel18.panelBrand = "SunPower";
        panel18.panelId = 18;
        panel18.panelPrice = 18000.75;
        panel18.isAvailable = true;
        panel18.panelType = "Monocrystalline";
        panel18.powerOutputWatts = 450.0;
        panel18.weight = 22.5;
        panel18.isPortable = false;
        panel18.cellType = "Mono";
        panel18.warrantyYears = 25;
        panel18.panelEfficiency = 21.5;
        panel18.hasAntiReflectiveCoating = true;
        panel18.color = "Blue";
        panel18.stockQuantity = 35;
        panel18.panelLength = 200.0;
        panel18.isEcoFriendly = true;
        panel18.frameMaterial = "Aluminum";
        panel18.rating = 5;
        panel18.voltage = 40.5;
        panel18.isCertified = true;
        panel18.countryOfOrigin = "China";
        panel18.manufacturingYear = 2025;
        panel18.panelWidth = 100.0;
        panel18.supportsOffGrid = true;
        panel18.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel18.panelBrand);
        System.out.println("The panelId is : " + panel18.panelId);
        System.out.println("The panelPrice is : " + panel18.panelPrice);
        System.out.println("The isAvailable is : " + panel18.isAvailable);
        System.out.println("The panelType is : " + panel18.panelType);
        System.out.println("The powerOutputWatts is : " + panel18.powerOutputWatts);
        System.out.println("The weight is : " + panel18.weight);
        System.out.println("The isPortable is : " + panel18.isPortable);
        System.out.println("The cellType is : " + panel18.cellType);
        System.out.println("The warrantyYears is : " + panel18.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel18.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel18.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel18.color);
        System.out.println("The stockQuantity is : " + panel18.stockQuantity);
        System.out.println("The panelLength is : " + panel18.panelLength);
        System.out.println("The isEcoFriendly is : " + panel18.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel18.frameMaterial);
        System.out.println("The rating is : " + panel18.rating);
        System.out.println("The voltage is : " + panel18.voltage);
        System.out.println("The isCertified is : " + panel18.isCertified);
        System.out.println("The countryOfOrigin is : " + panel18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel18.manufacturingYear);
        System.out.println("The panelWidth is : " + panel18.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel18.supportsOffGrid);
        System.out.println("The certificationType is : " + panel18.certificationType);


        SolarPanel panel19 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel19.panelBrand);
        System.out.println("The panelId is : " + panel19.panelId);
        System.out.println("The panelPrice is : " + panel19.panelPrice);
        System.out.println("The isAvailable is : " + panel19.isAvailable);
        System.out.println("The panelType is : " + panel19.panelType);
        System.out.println("The powerOutputWatts is : " + panel19.powerOutputWatts);
        System.out.println("The weight is : " + panel19.weight);
        System.out.println("The isPortable is : " + panel19.isPortable);
        System.out.println("The cellType is : " + panel19.cellType);
        System.out.println("The warrantyYears is : " + panel19.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel19.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel19.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel19.color);
        System.out.println("The stockQuantity is : " + panel19.stockQuantity);
        System.out.println("The panelLength is : " + panel19.panelLength);
        System.out.println("The isEcoFriendly is : " + panel19.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel19.frameMaterial);
        System.out.println("The rating is : " + panel19.rating);
        System.out.println("The voltage is : " + panel19.voltage);
        System.out.println("The isCertified is : " + panel19.isCertified);
        System.out.println("The countryOfOrigin is : " + panel19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel19.manufacturingYear);
        System.out.println("The panelWidth is : " + panel19.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel19.supportsOffGrid);
        System.out.println("The certificationType is : " + panel19.certificationType);

        panel19.panelBrand = "SunPower";
        panel19.panelId = 19;
        panel19.panelPrice = 19000.75;
        panel19.isAvailable = true;
        panel19.panelType = "Monocrystalline";
        panel19.powerOutputWatts = 450.0;
        panel19.weight = 22.5;
        panel19.isPortable = false;
        panel19.cellType = "Mono";
        panel19.warrantyYears = 25;
        panel19.panelEfficiency = 21.5;
        panel19.hasAntiReflectiveCoating = true;
        panel19.color = "Blue";
        panel19.stockQuantity = 35;
        panel19.panelLength = 200.0;
        panel19.isEcoFriendly = true;
        panel19.frameMaterial = "Aluminum";
        panel19.rating = 5;
        panel19.voltage = 40.5;
        panel19.isCertified = true;
        panel19.countryOfOrigin = "China";
        panel19.manufacturingYear = 2025;
        panel19.panelWidth = 100.0;
        panel19.supportsOffGrid = true;
        panel19.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel19.panelBrand);
        System.out.println("The panelId is : " + panel19.panelId);
        System.out.println("The panelPrice is : " + panel19.panelPrice);
        System.out.println("The isAvailable is : " + panel19.isAvailable);
        System.out.println("The panelType is : " + panel19.panelType);
        System.out.println("The powerOutputWatts is : " + panel19.powerOutputWatts);
        System.out.println("The weight is : " + panel19.weight);
        System.out.println("The isPortable is : " + panel19.isPortable);
        System.out.println("The cellType is : " + panel19.cellType);
        System.out.println("The warrantyYears is : " + panel19.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel19.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel19.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel19.color);
        System.out.println("The stockQuantity is : " + panel19.stockQuantity);
        System.out.println("The panelLength is : " + panel19.panelLength);
        System.out.println("The isEcoFriendly is : " + panel19.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel19.frameMaterial);
        System.out.println("The rating is : " + panel19.rating);
        System.out.println("The voltage is : " + panel19.voltage);
        System.out.println("The isCertified is : " + panel19.isCertified);
        System.out.println("The countryOfOrigin is : " + panel19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel19.manufacturingYear);
        System.out.println("The panelWidth is : " + panel19.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel19.supportsOffGrid);
        System.out.println("The certificationType is : " + panel19.certificationType);


        SolarPanel panel20 = new SolarPanel();

        System.out.println("Before initialization");

        System.out.println("The panelBrand is : " + panel20.panelBrand);
        System.out.println("The panelId is : " + panel20.panelId);
        System.out.println("The panelPrice is : " + panel20.panelPrice);
        System.out.println("The isAvailable is : " + panel20.isAvailable);
        System.out.println("The panelType is : " + panel20.panelType);
        System.out.println("The powerOutputWatts is : " + panel20.powerOutputWatts);
        System.out.println("The weight is : " + panel20.weight);
        System.out.println("The isPortable is : " + panel20.isPortable);
        System.out.println("The cellType is : " + panel20.cellType);
        System.out.println("The warrantyYears is : " + panel20.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel20.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel20.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel20.color);
        System.out.println("The stockQuantity is : " + panel20.stockQuantity);
        System.out.println("The panelLength is : " + panel20.panelLength);
        System.out.println("The isEcoFriendly is : " + panel20.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel20.frameMaterial);
        System.out.println("The rating is : " + panel20.rating);
        System.out.println("The voltage is : " + panel20.voltage);
        System.out.println("The isCertified is : " + panel20.isCertified);
        System.out.println("The countryOfOrigin is : " + panel20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel20.manufacturingYear);
        System.out.println("The panelWidth is : " + panel20.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel20.supportsOffGrid);
        System.out.println("The certificationType is : " + panel20.certificationType);

        panel20.panelBrand = "SunPower";
        panel20.panelId = 20;
        panel20.panelPrice = 20000.75;
        panel20.isAvailable = true;
        panel20.panelType = "Monocrystalline";
        panel20.powerOutputWatts = 450.0;
        panel20.weight = 22.5;
        panel20.isPortable = false;
        panel20.cellType = "Mono";
        panel20.warrantyYears = 25;
        panel20.panelEfficiency = 21.5;
        panel20.hasAntiReflectiveCoating = true;
        panel20.color = "Blue";
        panel20.stockQuantity = 35;
        panel20.panelLength = 200.0;
        panel20.isEcoFriendly = true;
        panel20.frameMaterial = "Aluminum";
        panel20.rating = 5;
        panel20.voltage = 40.5;
        panel20.isCertified = true;
        panel20.countryOfOrigin = "China";
        panel20.manufacturingYear = 2025;
        panel20.panelWidth = 100.0;
        panel20.supportsOffGrid = true;
        panel20.certificationType = "IEC";

        System.out.println("After initialization");

        System.out.println("The panelBrand is : " + panel20.panelBrand);
        System.out.println("The panelId is : " + panel20.panelId);
        System.out.println("The panelPrice is : " + panel20.panelPrice);
        System.out.println("The isAvailable is : " + panel20.isAvailable);
        System.out.println("The panelType is : " + panel20.panelType);
        System.out.println("The powerOutputWatts is : " + panel20.powerOutputWatts);
        System.out.println("The weight is : " + panel20.weight);
        System.out.println("The isPortable is : " + panel20.isPortable);
        System.out.println("The cellType is : " + panel20.cellType);
        System.out.println("The warrantyYears is : " + panel20.warrantyYears);
        System.out.println("The panelEfficiency is : " + panel20.panelEfficiency);
        System.out.println("The hasAntiReflectiveCoating is : " + panel20.hasAntiReflectiveCoating);
        System.out.println("The color is : " + panel20.color);
        System.out.println("The stockQuantity is : " + panel20.stockQuantity);
        System.out.println("The panelLength is : " + panel20.panelLength);
        System.out.println("The isEcoFriendly is : " + panel20.isEcoFriendly);
        System.out.println("The frameMaterial is : " + panel20.frameMaterial);
        System.out.println("The rating is : " + panel20.rating);
        System.out.println("The voltage is : " + panel20.voltage);
        System.out.println("The isCertified is : " + panel20.isCertified);
        System.out.println("The countryOfOrigin is : " + panel20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + panel20.manufacturingYear);
        System.out.println("The panelWidth is : " + panel20.panelWidth);
        System.out.println("The supportsOffGrid is : " + panel20.supportsOffGrid);
        System.out.println("The certificationType is : " + panel20.certificationType);


    }
}
