class WalkieTalkieExecutor {

    public static void main(String[] args) {

        WalkieTalkie device1 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device1.deviceBrand);
        System.out.println("The deviceId is : " + device1.deviceId);
        System.out.println("The devicePrice is : " + device1.devicePrice);
        System.out.println("The isAvailable is : " + device1.isAvailable);
        System.out.println("The deviceType is : " + device1.deviceType);
        System.out.println("The rangeKm is : " + device1.rangeKm);
        System.out.println("The weight is : " + device1.weight);
        System.out.println("The isRechargeable is : " + device1.isRechargeable);
        System.out.println("The batteryType is : " + device1.batteryType);
        System.out.println("The warrantyYears is : " + device1.warrantyYears);
        System.out.println("The frequencyMHz is : " + device1.frequencyMHz);
        System.out.println("The hasLCD is : " + device1.hasLCD);
        System.out.println("The color is : " + device1.color);
        System.out.println("The stockQuantity is : " + device1.stockQuantity);
        System.out.println("The channelCount is : " + device1.channelCount);
        System.out.println("The isEcoFriendly is : " + device1.isEcoFriendly);
        System.out.println("The antennaType is : " + device1.antennaType);
        System.out.println("The rating is : " + device1.rating);
        System.out.println("The batteryCapacity is : " + device1.batteryCapacity);
        System.out.println("The isCertified is : " + device1.isCertified);
        System.out.println("The countryOfOrigin is : " + device1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device1.manufacturingYear);
        System.out.println("The speakerPower is : " + device1.speakerPower);
        System.out.println("The supportsVOX is : " + device1.supportsVOX);
        System.out.println("The certificationType is : " + device1.certificationType);

        device1.deviceBrand = "Motorola";
        device1.deviceId = 1;
        device1.devicePrice = 199.99;
        device1.isAvailable = true;
        device1.deviceType = "Two Way Radio";
        device1.rangeKm = 10.0;
        device1.weight = 0.35;
        device1.isRechargeable = true;
        device1.batteryType = "Li-Ion";
        device1.warrantyYears = 2;
        device1.frequencyMHz = 462.5;
        device1.hasLCD = true;
        device1.color = "Black";
        device1.stockQuantity = 30;
        device1.channelCount = 22;
        device1.isEcoFriendly = true;
        device1.antennaType = "External";
        device1.rating = 4;
        device1.batteryCapacity = 1500.0;
        device1.isCertified = true;
        device1.countryOfOrigin = "USA";
        device1.manufacturingYear = 2025;
        device1.speakerPower = 1.5;
        device1.supportsVOX = true;
        device1.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device1.deviceBrand);
        System.out.println("The deviceId is : " + device1.deviceId);
        System.out.println("The devicePrice is : " + device1.devicePrice);
        System.out.println("The isAvailable is : " + device1.isAvailable);
        System.out.println("The deviceType is : " + device1.deviceType);
        System.out.println("The rangeKm is : " + device1.rangeKm);
        System.out.println("The weight is : " + device1.weight);
        System.out.println("The isRechargeable is : " + device1.isRechargeable);
        System.out.println("The batteryType is : " + device1.batteryType);
        System.out.println("The warrantyYears is : " + device1.warrantyYears);
        System.out.println("The frequencyMHz is : " + device1.frequencyMHz);
        System.out.println("The hasLCD is : " + device1.hasLCD);
        System.out.println("The color is : " + device1.color);
        System.out.println("The stockQuantity is : " + device1.stockQuantity);
        System.out.println("The channelCount is : " + device1.channelCount);
        System.out.println("The isEcoFriendly is : " + device1.isEcoFriendly);
        System.out.println("The antennaType is : " + device1.antennaType);
        System.out.println("The rating is : " + device1.rating);
        System.out.println("The batteryCapacity is : " + device1.batteryCapacity);
        System.out.println("The isCertified is : " + device1.isCertified);
        System.out.println("The countryOfOrigin is : " + device1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device1.manufacturingYear);
        System.out.println("The speakerPower is : " + device1.speakerPower);
        System.out.println("The supportsVOX is : " + device1.supportsVOX);
        System.out.println("The certificationType is : " + device1.certificationType);


        WalkieTalkie device2 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device2.deviceBrand);
        System.out.println("The deviceId is : " + device2.deviceId);
        System.out.println("The devicePrice is : " + device2.devicePrice);
        System.out.println("The isAvailable is : " + device2.isAvailable);
        System.out.println("The deviceType is : " + device2.deviceType);
        System.out.println("The rangeKm is : " + device2.rangeKm);
        System.out.println("The weight is : " + device2.weight);
        System.out.println("The isRechargeable is : " + device2.isRechargeable);
        System.out.println("The batteryType is : " + device2.batteryType);
        System.out.println("The warrantyYears is : " + device2.warrantyYears);
        System.out.println("The frequencyMHz is : " + device2.frequencyMHz);
        System.out.println("The hasLCD is : " + device2.hasLCD);
        System.out.println("The color is : " + device2.color);
        System.out.println("The stockQuantity is : " + device2.stockQuantity);
        System.out.println("The channelCount is : " + device2.channelCount);
        System.out.println("The isEcoFriendly is : " + device2.isEcoFriendly);
        System.out.println("The antennaType is : " + device2.antennaType);
        System.out.println("The rating is : " + device2.rating);
        System.out.println("The batteryCapacity is : " + device2.batteryCapacity);
        System.out.println("The isCertified is : " + device2.isCertified);
        System.out.println("The countryOfOrigin is : " + device2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device2.manufacturingYear);
        System.out.println("The speakerPower is : " + device2.speakerPower);
        System.out.println("The supportsVOX is : " + device2.supportsVOX);
        System.out.println("The certificationType is : " + device2.certificationType);

        device2.deviceBrand = "Motorola";
        device2.deviceId = 2;
        device2.devicePrice = 299.99;
        device2.isAvailable = true;
        device2.deviceType = "Two Way Radio";
        device2.rangeKm = 10.0;
        device2.weight = 0.35;
        device2.isRechargeable = true;
        device2.batteryType = "Li-Ion";
        device2.warrantyYears = 2;
        device2.frequencyMHz = 462.5;
        device2.hasLCD = true;
        device2.color = "Black";
        device2.stockQuantity = 30;
        device2.channelCount = 22;
        device2.isEcoFriendly = true;
        device2.antennaType = "External";
        device2.rating = 4;
        device2.batteryCapacity = 1500.0;
        device2.isCertified = true;
        device2.countryOfOrigin = "USA";
        device2.manufacturingYear = 2025;
        device2.speakerPower = 1.5;
        device2.supportsVOX = true;
        device2.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device2.deviceBrand);
        System.out.println("The deviceId is : " + device2.deviceId);
        System.out.println("The devicePrice is : " + device2.devicePrice);
        System.out.println("The isAvailable is : " + device2.isAvailable);
        System.out.println("The deviceType is : " + device2.deviceType);
        System.out.println("The rangeKm is : " + device2.rangeKm);
        System.out.println("The weight is : " + device2.weight);
        System.out.println("The isRechargeable is : " + device2.isRechargeable);
        System.out.println("The batteryType is : " + device2.batteryType);
        System.out.println("The warrantyYears is : " + device2.warrantyYears);
        System.out.println("The frequencyMHz is : " + device2.frequencyMHz);
        System.out.println("The hasLCD is : " + device2.hasLCD);
        System.out.println("The color is : " + device2.color);
        System.out.println("The stockQuantity is : " + device2.stockQuantity);
        System.out.println("The channelCount is : " + device2.channelCount);
        System.out.println("The isEcoFriendly is : " + device2.isEcoFriendly);
        System.out.println("The antennaType is : " + device2.antennaType);
        System.out.println("The rating is : " + device2.rating);
        System.out.println("The batteryCapacity is : " + device2.batteryCapacity);
        System.out.println("The isCertified is : " + device2.isCertified);
        System.out.println("The countryOfOrigin is : " + device2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device2.manufacturingYear);
        System.out.println("The speakerPower is : " + device2.speakerPower);
        System.out.println("The supportsVOX is : " + device2.supportsVOX);
        System.out.println("The certificationType is : " + device2.certificationType);


        WalkieTalkie device3 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device3.deviceBrand);
        System.out.println("The deviceId is : " + device3.deviceId);
        System.out.println("The devicePrice is : " + device3.devicePrice);
        System.out.println("The isAvailable is : " + device3.isAvailable);
        System.out.println("The deviceType is : " + device3.deviceType);
        System.out.println("The rangeKm is : " + device3.rangeKm);
        System.out.println("The weight is : " + device3.weight);
        System.out.println("The isRechargeable is : " + device3.isRechargeable);
        System.out.println("The batteryType is : " + device3.batteryType);
        System.out.println("The warrantyYears is : " + device3.warrantyYears);
        System.out.println("The frequencyMHz is : " + device3.frequencyMHz);
        System.out.println("The hasLCD is : " + device3.hasLCD);
        System.out.println("The color is : " + device3.color);
        System.out.println("The stockQuantity is : " + device3.stockQuantity);
        System.out.println("The channelCount is : " + device3.channelCount);
        System.out.println("The isEcoFriendly is : " + device3.isEcoFriendly);
        System.out.println("The antennaType is : " + device3.antennaType);
        System.out.println("The rating is : " + device3.rating);
        System.out.println("The batteryCapacity is : " + device3.batteryCapacity);
        System.out.println("The isCertified is : " + device3.isCertified);
        System.out.println("The countryOfOrigin is : " + device3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device3.manufacturingYear);
        System.out.println("The speakerPower is : " + device3.speakerPower);
        System.out.println("The supportsVOX is : " + device3.supportsVOX);
        System.out.println("The certificationType is : " + device3.certificationType);

        device3.deviceBrand = "Motorola";
        device3.deviceId = 3;
        device3.devicePrice = 399.99;
        device3.isAvailable = true;
        device3.deviceType = "Two Way Radio";
        device3.rangeKm = 10.0;
        device3.weight = 0.35;
        device3.isRechargeable = true;
        device3.batteryType = "Li-Ion";
        device3.warrantyYears = 2;
        device3.frequencyMHz = 462.5;
        device3.hasLCD = true;
        device3.color = "Black";
        device3.stockQuantity = 30;
        device3.channelCount = 22;
        device3.isEcoFriendly = true;
        device3.antennaType = "External";
        device3.rating = 4;
        device3.batteryCapacity = 1500.0;
        device3.isCertified = true;
        device3.countryOfOrigin = "USA";
        device3.manufacturingYear = 2025;
        device3.speakerPower = 1.5;
        device3.supportsVOX = true;
        device3.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device3.deviceBrand);
        System.out.println("The deviceId is : " + device3.deviceId);
        System.out.println("The devicePrice is : " + device3.devicePrice);
        System.out.println("The isAvailable is : " + device3.isAvailable);
        System.out.println("The deviceType is : " + device3.deviceType);
        System.out.println("The rangeKm is : " + device3.rangeKm);
        System.out.println("The weight is : " + device3.weight);
        System.out.println("The isRechargeable is : " + device3.isRechargeable);
        System.out.println("The batteryType is : " + device3.batteryType);
        System.out.println("The warrantyYears is : " + device3.warrantyYears);
        System.out.println("The frequencyMHz is : " + device3.frequencyMHz);
        System.out.println("The hasLCD is : " + device3.hasLCD);
        System.out.println("The color is : " + device3.color);
        System.out.println("The stockQuantity is : " + device3.stockQuantity);
        System.out.println("The channelCount is : " + device3.channelCount);
        System.out.println("The isEcoFriendly is : " + device3.isEcoFriendly);
        System.out.println("The antennaType is : " + device3.antennaType);
        System.out.println("The rating is : " + device3.rating);
        System.out.println("The batteryCapacity is : " + device3.batteryCapacity);
        System.out.println("The isCertified is : " + device3.isCertified);
        System.out.println("The countryOfOrigin is : " + device3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device3.manufacturingYear);
        System.out.println("The speakerPower is : " + device3.speakerPower);
        System.out.println("The supportsVOX is : " + device3.supportsVOX);
        System.out.println("The certificationType is : " + device3.certificationType);


        WalkieTalkie device4 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device4.deviceBrand);
        System.out.println("The deviceId is : " + device4.deviceId);
        System.out.println("The devicePrice is : " + device4.devicePrice);
        System.out.println("The isAvailable is : " + device4.isAvailable);
        System.out.println("The deviceType is : " + device4.deviceType);
        System.out.println("The rangeKm is : " + device4.rangeKm);
        System.out.println("The weight is : " + device4.weight);
        System.out.println("The isRechargeable is : " + device4.isRechargeable);
        System.out.println("The batteryType is : " + device4.batteryType);
        System.out.println("The warrantyYears is : " + device4.warrantyYears);
        System.out.println("The frequencyMHz is : " + device4.frequencyMHz);
        System.out.println("The hasLCD is : " + device4.hasLCD);
        System.out.println("The color is : " + device4.color);
        System.out.println("The stockQuantity is : " + device4.stockQuantity);
        System.out.println("The channelCount is : " + device4.channelCount);
        System.out.println("The isEcoFriendly is : " + device4.isEcoFriendly);
        System.out.println("The antennaType is : " + device4.antennaType);
        System.out.println("The rating is : " + device4.rating);
        System.out.println("The batteryCapacity is : " + device4.batteryCapacity);
        System.out.println("The isCertified is : " + device4.isCertified);
        System.out.println("The countryOfOrigin is : " + device4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device4.manufacturingYear);
        System.out.println("The speakerPower is : " + device4.speakerPower);
        System.out.println("The supportsVOX is : " + device4.supportsVOX);
        System.out.println("The certificationType is : " + device4.certificationType);

        device4.deviceBrand = "Motorola";
        device4.deviceId = 4;
        device4.devicePrice = 499.99;
        device4.isAvailable = true;
        device4.deviceType = "Two Way Radio";
        device4.rangeKm = 10.0;
        device4.weight = 0.35;
        device4.isRechargeable = true;
        device4.batteryType = "Li-Ion";
        device4.warrantyYears = 2;
        device4.frequencyMHz = 462.5;
        device4.hasLCD = true;
        device4.color = "Black";
        device4.stockQuantity = 30;
        device4.channelCount = 22;
        device4.isEcoFriendly = true;
        device4.antennaType = "External";
        device4.rating = 4;
        device4.batteryCapacity = 1500.0;
        device4.isCertified = true;
        device4.countryOfOrigin = "USA";
        device4.manufacturingYear = 2025;
        device4.speakerPower = 1.5;
        device4.supportsVOX = true;
        device4.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device4.deviceBrand);
        System.out.println("The deviceId is : " + device4.deviceId);
        System.out.println("The devicePrice is : " + device4.devicePrice);
        System.out.println("The isAvailable is : " + device4.isAvailable);
        System.out.println("The deviceType is : " + device4.deviceType);
        System.out.println("The rangeKm is : " + device4.rangeKm);
        System.out.println("The weight is : " + device4.weight);
        System.out.println("The isRechargeable is : " + device4.isRechargeable);
        System.out.println("The batteryType is : " + device4.batteryType);
        System.out.println("The warrantyYears is : " + device4.warrantyYears);
        System.out.println("The frequencyMHz is : " + device4.frequencyMHz);
        System.out.println("The hasLCD is : " + device4.hasLCD);
        System.out.println("The color is : " + device4.color);
        System.out.println("The stockQuantity is : " + device4.stockQuantity);
        System.out.println("The channelCount is : " + device4.channelCount);
        System.out.println("The isEcoFriendly is : " + device4.isEcoFriendly);
        System.out.println("The antennaType is : " + device4.antennaType);
        System.out.println("The rating is : " + device4.rating);
        System.out.println("The batteryCapacity is : " + device4.batteryCapacity);
        System.out.println("The isCertified is : " + device4.isCertified);
        System.out.println("The countryOfOrigin is : " + device4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device4.manufacturingYear);
        System.out.println("The speakerPower is : " + device4.speakerPower);
        System.out.println("The supportsVOX is : " + device4.supportsVOX);
        System.out.println("The certificationType is : " + device4.certificationType);


        WalkieTalkie device5 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device5.deviceBrand);
        System.out.println("The deviceId is : " + device5.deviceId);
        System.out.println("The devicePrice is : " + device5.devicePrice);
        System.out.println("The isAvailable is : " + device5.isAvailable);
        System.out.println("The deviceType is : " + device5.deviceType);
        System.out.println("The rangeKm is : " + device5.rangeKm);
        System.out.println("The weight is : " + device5.weight);
        System.out.println("The isRechargeable is : " + device5.isRechargeable);
        System.out.println("The batteryType is : " + device5.batteryType);
        System.out.println("The warrantyYears is : " + device5.warrantyYears);
        System.out.println("The frequencyMHz is : " + device5.frequencyMHz);
        System.out.println("The hasLCD is : " + device5.hasLCD);
        System.out.println("The color is : " + device5.color);
        System.out.println("The stockQuantity is : " + device5.stockQuantity);
        System.out.println("The channelCount is : " + device5.channelCount);
        System.out.println("The isEcoFriendly is : " + device5.isEcoFriendly);
        System.out.println("The antennaType is : " + device5.antennaType);
        System.out.println("The rating is : " + device5.rating);
        System.out.println("The batteryCapacity is : " + device5.batteryCapacity);
        System.out.println("The isCertified is : " + device5.isCertified);
        System.out.println("The countryOfOrigin is : " + device5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device5.manufacturingYear);
        System.out.println("The speakerPower is : " + device5.speakerPower);
        System.out.println("The supportsVOX is : " + device5.supportsVOX);
        System.out.println("The certificationType is : " + device5.certificationType);

        device5.deviceBrand = "Motorola";
        device5.deviceId = 5;
        device5.devicePrice = 599.99;
        device5.isAvailable = true;
        device5.deviceType = "Two Way Radio";
        device5.rangeKm = 10.0;
        device5.weight = 0.35;
        device5.isRechargeable = true;
        device5.batteryType = "Li-Ion";
        device5.warrantyYears = 2;
        device5.frequencyMHz = 462.5;
        device5.hasLCD = true;
        device5.color = "Black";
        device5.stockQuantity = 30;
        device5.channelCount = 22;
        device5.isEcoFriendly = true;
        device5.antennaType = "External";
        device5.rating = 4;
        device5.batteryCapacity = 1500.0;
        device5.isCertified = true;
        device5.countryOfOrigin = "USA";
        device5.manufacturingYear = 2025;
        device5.speakerPower = 1.5;
        device5.supportsVOX = true;
        device5.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device5.deviceBrand);
        System.out.println("The deviceId is : " + device5.deviceId);
        System.out.println("The devicePrice is : " + device5.devicePrice);
        System.out.println("The isAvailable is : " + device5.isAvailable);
        System.out.println("The deviceType is : " + device5.deviceType);
        System.out.println("The rangeKm is : " + device5.rangeKm);
        System.out.println("The weight is : " + device5.weight);
        System.out.println("The isRechargeable is : " + device5.isRechargeable);
        System.out.println("The batteryType is : " + device5.batteryType);
        System.out.println("The warrantyYears is : " + device5.warrantyYears);
        System.out.println("The frequencyMHz is : " + device5.frequencyMHz);
        System.out.println("The hasLCD is : " + device5.hasLCD);
        System.out.println("The color is : " + device5.color);
        System.out.println("The stockQuantity is : " + device5.stockQuantity);
        System.out.println("The channelCount is : " + device5.channelCount);
        System.out.println("The isEcoFriendly is : " + device5.isEcoFriendly);
        System.out.println("The antennaType is : " + device5.antennaType);
        System.out.println("The rating is : " + device5.rating);
        System.out.println("The batteryCapacity is : " + device5.batteryCapacity);
        System.out.println("The isCertified is : " + device5.isCertified);
        System.out.println("The countryOfOrigin is : " + device5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device5.manufacturingYear);
        System.out.println("The speakerPower is : " + device5.speakerPower);
        System.out.println("The supportsVOX is : " + device5.supportsVOX);
        System.out.println("The certificationType is : " + device5.certificationType);


        WalkieTalkie device6 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device6.deviceBrand);
        System.out.println("The deviceId is : " + device6.deviceId);
        System.out.println("The devicePrice is : " + device6.devicePrice);
        System.out.println("The isAvailable is : " + device6.isAvailable);
        System.out.println("The deviceType is : " + device6.deviceType);
        System.out.println("The rangeKm is : " + device6.rangeKm);
        System.out.println("The weight is : " + device6.weight);
        System.out.println("The isRechargeable is : " + device6.isRechargeable);
        System.out.println("The batteryType is : " + device6.batteryType);
        System.out.println("The warrantyYears is : " + device6.warrantyYears);
        System.out.println("The frequencyMHz is : " + device6.frequencyMHz);
        System.out.println("The hasLCD is : " + device6.hasLCD);
        System.out.println("The color is : " + device6.color);
        System.out.println("The stockQuantity is : " + device6.stockQuantity);
        System.out.println("The channelCount is : " + device6.channelCount);
        System.out.println("The isEcoFriendly is : " + device6.isEcoFriendly);
        System.out.println("The antennaType is : " + device6.antennaType);
        System.out.println("The rating is : " + device6.rating);
        System.out.println("The batteryCapacity is : " + device6.batteryCapacity);
        System.out.println("The isCertified is : " + device6.isCertified);
        System.out.println("The countryOfOrigin is : " + device6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device6.manufacturingYear);
        System.out.println("The speakerPower is : " + device6.speakerPower);
        System.out.println("The supportsVOX is : " + device6.supportsVOX);
        System.out.println("The certificationType is : " + device6.certificationType);

        device6.deviceBrand = "Motorola";
        device6.deviceId = 6;
        device6.devicePrice = 699.99;
        device6.isAvailable = true;
        device6.deviceType = "Two Way Radio";
        device6.rangeKm = 10.0;
        device6.weight = 0.35;
        device6.isRechargeable = true;
        device6.batteryType = "Li-Ion";
        device6.warrantyYears = 2;
        device6.frequencyMHz = 462.5;
        device6.hasLCD = true;
        device6.color = "Black";
        device6.stockQuantity = 30;
        device6.channelCount = 22;
        device6.isEcoFriendly = true;
        device6.antennaType = "External";
        device6.rating = 4;
        device6.batteryCapacity = 1500.0;
        device6.isCertified = true;
        device6.countryOfOrigin = "USA";
        device6.manufacturingYear = 2025;
        device6.speakerPower = 1.5;
        device6.supportsVOX = true;
        device6.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device6.deviceBrand);
        System.out.println("The deviceId is : " + device6.deviceId);
        System.out.println("The devicePrice is : " + device6.devicePrice);
        System.out.println("The isAvailable is : " + device6.isAvailable);
        System.out.println("The deviceType is : " + device6.deviceType);
        System.out.println("The rangeKm is : " + device6.rangeKm);
        System.out.println("The weight is : " + device6.weight);
        System.out.println("The isRechargeable is : " + device6.isRechargeable);
        System.out.println("The batteryType is : " + device6.batteryType);
        System.out.println("The warrantyYears is : " + device6.warrantyYears);
        System.out.println("The frequencyMHz is : " + device6.frequencyMHz);
        System.out.println("The hasLCD is : " + device6.hasLCD);
        System.out.println("The color is : " + device6.color);
        System.out.println("The stockQuantity is : " + device6.stockQuantity);
        System.out.println("The channelCount is : " + device6.channelCount);
        System.out.println("The isEcoFriendly is : " + device6.isEcoFriendly);
        System.out.println("The antennaType is : " + device6.antennaType);
        System.out.println("The rating is : " + device6.rating);
        System.out.println("The batteryCapacity is : " + device6.batteryCapacity);
        System.out.println("The isCertified is : " + device6.isCertified);
        System.out.println("The countryOfOrigin is : " + device6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device6.manufacturingYear);
        System.out.println("The speakerPower is : " + device6.speakerPower);
        System.out.println("The supportsVOX is : " + device6.supportsVOX);
        System.out.println("The certificationType is : " + device6.certificationType);


        WalkieTalkie device7 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device7.deviceBrand);
        System.out.println("The deviceId is : " + device7.deviceId);
        System.out.println("The devicePrice is : " + device7.devicePrice);
        System.out.println("The isAvailable is : " + device7.isAvailable);
        System.out.println("The deviceType is : " + device7.deviceType);
        System.out.println("The rangeKm is : " + device7.rangeKm);
        System.out.println("The weight is : " + device7.weight);
        System.out.println("The isRechargeable is : " + device7.isRechargeable);
        System.out.println("The batteryType is : " + device7.batteryType);
        System.out.println("The warrantyYears is : " + device7.warrantyYears);
        System.out.println("The frequencyMHz is : " + device7.frequencyMHz);
        System.out.println("The hasLCD is : " + device7.hasLCD);
        System.out.println("The color is : " + device7.color);
        System.out.println("The stockQuantity is : " + device7.stockQuantity);
        System.out.println("The channelCount is : " + device7.channelCount);
        System.out.println("The isEcoFriendly is : " + device7.isEcoFriendly);
        System.out.println("The antennaType is : " + device7.antennaType);
        System.out.println("The rating is : " + device7.rating);
        System.out.println("The batteryCapacity is : " + device7.batteryCapacity);
        System.out.println("The isCertified is : " + device7.isCertified);
        System.out.println("The countryOfOrigin is : " + device7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device7.manufacturingYear);
        System.out.println("The speakerPower is : " + device7.speakerPower);
        System.out.println("The supportsVOX is : " + device7.supportsVOX);
        System.out.println("The certificationType is : " + device7.certificationType);

        device7.deviceBrand = "Motorola";
        device7.deviceId = 7;
        device7.devicePrice = 799.99;
        device7.isAvailable = true;
        device7.deviceType = "Two Way Radio";
        device7.rangeKm = 10.0;
        device7.weight = 0.35;
        device7.isRechargeable = true;
        device7.batteryType = "Li-Ion";
        device7.warrantyYears = 2;
        device7.frequencyMHz = 462.5;
        device7.hasLCD = true;
        device7.color = "Black";
        device7.stockQuantity = 30;
        device7.channelCount = 22;
        device7.isEcoFriendly = true;
        device7.antennaType = "External";
        device7.rating = 4;
        device7.batteryCapacity = 1500.0;
        device7.isCertified = true;
        device7.countryOfOrigin = "USA";
        device7.manufacturingYear = 2025;
        device7.speakerPower = 1.5;
        device7.supportsVOX = true;
        device7.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device7.deviceBrand);
        System.out.println("The deviceId is : " + device7.deviceId);
        System.out.println("The devicePrice is : " + device7.devicePrice);
        System.out.println("The isAvailable is : " + device7.isAvailable);
        System.out.println("The deviceType is : " + device7.deviceType);
        System.out.println("The rangeKm is : " + device7.rangeKm);
        System.out.println("The weight is : " + device7.weight);
        System.out.println("The isRechargeable is : " + device7.isRechargeable);
        System.out.println("The batteryType is : " + device7.batteryType);
        System.out.println("The warrantyYears is : " + device7.warrantyYears);
        System.out.println("The frequencyMHz is : " + device7.frequencyMHz);
        System.out.println("The hasLCD is : " + device7.hasLCD);
        System.out.println("The color is : " + device7.color);
        System.out.println("The stockQuantity is : " + device7.stockQuantity);
        System.out.println("The channelCount is : " + device7.channelCount);
        System.out.println("The isEcoFriendly is : " + device7.isEcoFriendly);
        System.out.println("The antennaType is : " + device7.antennaType);
        System.out.println("The rating is : " + device7.rating);
        System.out.println("The batteryCapacity is : " + device7.batteryCapacity);
        System.out.println("The isCertified is : " + device7.isCertified);
        System.out.println("The countryOfOrigin is : " + device7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device7.manufacturingYear);
        System.out.println("The speakerPower is : " + device7.speakerPower);
        System.out.println("The supportsVOX is : " + device7.supportsVOX);
        System.out.println("The certificationType is : " + device7.certificationType);


        WalkieTalkie device8 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device8.deviceBrand);
        System.out.println("The deviceId is : " + device8.deviceId);
        System.out.println("The devicePrice is : " + device8.devicePrice);
        System.out.println("The isAvailable is : " + device8.isAvailable);
        System.out.println("The deviceType is : " + device8.deviceType);
        System.out.println("The rangeKm is : " + device8.rangeKm);
        System.out.println("The weight is : " + device8.weight);
        System.out.println("The isRechargeable is : " + device8.isRechargeable);
        System.out.println("The batteryType is : " + device8.batteryType);
        System.out.println("The warrantyYears is : " + device8.warrantyYears);
        System.out.println("The frequencyMHz is : " + device8.frequencyMHz);
        System.out.println("The hasLCD is : " + device8.hasLCD);
        System.out.println("The color is : " + device8.color);
        System.out.println("The stockQuantity is : " + device8.stockQuantity);
        System.out.println("The channelCount is : " + device8.channelCount);
        System.out.println("The isEcoFriendly is : " + device8.isEcoFriendly);
        System.out.println("The antennaType is : " + device8.antennaType);
        System.out.println("The rating is : " + device8.rating);
        System.out.println("The batteryCapacity is : " + device8.batteryCapacity);
        System.out.println("The isCertified is : " + device8.isCertified);
        System.out.println("The countryOfOrigin is : " + device8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device8.manufacturingYear);
        System.out.println("The speakerPower is : " + device8.speakerPower);
        System.out.println("The supportsVOX is : " + device8.supportsVOX);
        System.out.println("The certificationType is : " + device8.certificationType);

        device8.deviceBrand = "Motorola";
        device8.deviceId = 8;
        device8.devicePrice = 899.99;
        device8.isAvailable = true;
        device8.deviceType = "Two Way Radio";
        device8.rangeKm = 10.0;
        device8.weight = 0.35;
        device8.isRechargeable = true;
        device8.batteryType = "Li-Ion";
        device8.warrantyYears = 2;
        device8.frequencyMHz = 462.5;
        device8.hasLCD = true;
        device8.color = "Black";
        device8.stockQuantity = 30;
        device8.channelCount = 22;
        device8.isEcoFriendly = true;
        device8.antennaType = "External";
        device8.rating = 4;
        device8.batteryCapacity = 1500.0;
        device8.isCertified = true;
        device8.countryOfOrigin = "USA";
        device8.manufacturingYear = 2025;
        device8.speakerPower = 1.5;
        device8.supportsVOX = true;
        device8.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device8.deviceBrand);
        System.out.println("The deviceId is : " + device8.deviceId);
        System.out.println("The devicePrice is : " + device8.devicePrice);
        System.out.println("The isAvailable is : " + device8.isAvailable);
        System.out.println("The deviceType is : " + device8.deviceType);
        System.out.println("The rangeKm is : " + device8.rangeKm);
        System.out.println("The weight is : " + device8.weight);
        System.out.println("The isRechargeable is : " + device8.isRechargeable);
        System.out.println("The batteryType is : " + device8.batteryType);
        System.out.println("The warrantyYears is : " + device8.warrantyYears);
        System.out.println("The frequencyMHz is : " + device8.frequencyMHz);
        System.out.println("The hasLCD is : " + device8.hasLCD);
        System.out.println("The color is : " + device8.color);
        System.out.println("The stockQuantity is : " + device8.stockQuantity);
        System.out.println("The channelCount is : " + device8.channelCount);
        System.out.println("The isEcoFriendly is : " + device8.isEcoFriendly);
        System.out.println("The antennaType is : " + device8.antennaType);
        System.out.println("The rating is : " + device8.rating);
        System.out.println("The batteryCapacity is : " + device8.batteryCapacity);
        System.out.println("The isCertified is : " + device8.isCertified);
        System.out.println("The countryOfOrigin is : " + device8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device8.manufacturingYear);
        System.out.println("The speakerPower is : " + device8.speakerPower);
        System.out.println("The supportsVOX is : " + device8.supportsVOX);
        System.out.println("The certificationType is : " + device8.certificationType);


        WalkieTalkie device9 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device9.deviceBrand);
        System.out.println("The deviceId is : " + device9.deviceId);
        System.out.println("The devicePrice is : " + device9.devicePrice);
        System.out.println("The isAvailable is : " + device9.isAvailable);
        System.out.println("The deviceType is : " + device9.deviceType);
        System.out.println("The rangeKm is : " + device9.rangeKm);
        System.out.println("The weight is : " + device9.weight);
        System.out.println("The isRechargeable is : " + device9.isRechargeable);
        System.out.println("The batteryType is : " + device9.batteryType);
        System.out.println("The warrantyYears is : " + device9.warrantyYears);
        System.out.println("The frequencyMHz is : " + device9.frequencyMHz);
        System.out.println("The hasLCD is : " + device9.hasLCD);
        System.out.println("The color is : " + device9.color);
        System.out.println("The stockQuantity is : " + device9.stockQuantity);
        System.out.println("The channelCount is : " + device9.channelCount);
        System.out.println("The isEcoFriendly is : " + device9.isEcoFriendly);
        System.out.println("The antennaType is : " + device9.antennaType);
        System.out.println("The rating is : " + device9.rating);
        System.out.println("The batteryCapacity is : " + device9.batteryCapacity);
        System.out.println("The isCertified is : " + device9.isCertified);
        System.out.println("The countryOfOrigin is : " + device9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device9.manufacturingYear);
        System.out.println("The speakerPower is : " + device9.speakerPower);
        System.out.println("The supportsVOX is : " + device9.supportsVOX);
        System.out.println("The certificationType is : " + device9.certificationType);

        device9.deviceBrand = "Motorola";
        device9.deviceId = 9;
        device9.devicePrice = 999.99;
        device9.isAvailable = true;
        device9.deviceType = "Two Way Radio";
        device9.rangeKm = 10.0;
        device9.weight = 0.35;
        device9.isRechargeable = true;
        device9.batteryType = "Li-Ion";
        device9.warrantyYears = 2;
        device9.frequencyMHz = 462.5;
        device9.hasLCD = true;
        device9.color = "Black";
        device9.stockQuantity = 30;
        device9.channelCount = 22;
        device9.isEcoFriendly = true;
        device9.antennaType = "External";
        device9.rating = 4;
        device9.batteryCapacity = 1500.0;
        device9.isCertified = true;
        device9.countryOfOrigin = "USA";
        device9.manufacturingYear = 2025;
        device9.speakerPower = 1.5;
        device9.supportsVOX = true;
        device9.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device9.deviceBrand);
        System.out.println("The deviceId is : " + device9.deviceId);
        System.out.println("The devicePrice is : " + device9.devicePrice);
        System.out.println("The isAvailable is : " + device9.isAvailable);
        System.out.println("The deviceType is : " + device9.deviceType);
        System.out.println("The rangeKm is : " + device9.rangeKm);
        System.out.println("The weight is : " + device9.weight);
        System.out.println("The isRechargeable is : " + device9.isRechargeable);
        System.out.println("The batteryType is : " + device9.batteryType);
        System.out.println("The warrantyYears is : " + device9.warrantyYears);
        System.out.println("The frequencyMHz is : " + device9.frequencyMHz);
        System.out.println("The hasLCD is : " + device9.hasLCD);
        System.out.println("The color is : " + device9.color);
        System.out.println("The stockQuantity is : " + device9.stockQuantity);
        System.out.println("The channelCount is : " + device9.channelCount);
        System.out.println("The isEcoFriendly is : " + device9.isEcoFriendly);
        System.out.println("The antennaType is : " + device9.antennaType);
        System.out.println("The rating is : " + device9.rating);
        System.out.println("The batteryCapacity is : " + device9.batteryCapacity);
        System.out.println("The isCertified is : " + device9.isCertified);
        System.out.println("The countryOfOrigin is : " + device9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device9.manufacturingYear);
        System.out.println("The speakerPower is : " + device9.speakerPower);
        System.out.println("The supportsVOX is : " + device9.supportsVOX);
        System.out.println("The certificationType is : " + device9.certificationType);


        WalkieTalkie device10 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device10.deviceBrand);
        System.out.println("The deviceId is : " + device10.deviceId);
        System.out.println("The devicePrice is : " + device10.devicePrice);
        System.out.println("The isAvailable is : " + device10.isAvailable);
        System.out.println("The deviceType is : " + device10.deviceType);
        System.out.println("The rangeKm is : " + device10.rangeKm);
        System.out.println("The weight is : " + device10.weight);
        System.out.println("The isRechargeable is : " + device10.isRechargeable);
        System.out.println("The batteryType is : " + device10.batteryType);
        System.out.println("The warrantyYears is : " + device10.warrantyYears);
        System.out.println("The frequencyMHz is : " + device10.frequencyMHz);
        System.out.println("The hasLCD is : " + device10.hasLCD);
        System.out.println("The color is : " + device10.color);
        System.out.println("The stockQuantity is : " + device10.stockQuantity);
        System.out.println("The channelCount is : " + device10.channelCount);
        System.out.println("The isEcoFriendly is : " + device10.isEcoFriendly);
        System.out.println("The antennaType is : " + device10.antennaType);
        System.out.println("The rating is : " + device10.rating);
        System.out.println("The batteryCapacity is : " + device10.batteryCapacity);
        System.out.println("The isCertified is : " + device10.isCertified);
        System.out.println("The countryOfOrigin is : " + device10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device10.manufacturingYear);
        System.out.println("The speakerPower is : " + device10.speakerPower);
        System.out.println("The supportsVOX is : " + device10.supportsVOX);
        System.out.println("The certificationType is : " + device10.certificationType);

        device10.deviceBrand = "Motorola";
        device10.deviceId = 10;
        device10.devicePrice = 1099.99;
        device10.isAvailable = true;
        device10.deviceType = "Two Way Radio";
        device10.rangeKm = 10.0;
        device10.weight = 0.35;
        device10.isRechargeable = true;
        device10.batteryType = "Li-Ion";
        device10.warrantyYears = 2;
        device10.frequencyMHz = 462.5;
        device10.hasLCD = true;
        device10.color = "Black";
        device10.stockQuantity = 30;
        device10.channelCount = 22;
        device10.isEcoFriendly = true;
        device10.antennaType = "External";
        device10.rating = 4;
        device10.batteryCapacity = 1500.0;
        device10.isCertified = true;
        device10.countryOfOrigin = "USA";
        device10.manufacturingYear = 2025;
        device10.speakerPower = 1.5;
        device10.supportsVOX = true;
        device10.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device10.deviceBrand);
        System.out.println("The deviceId is : " + device10.deviceId);
        System.out.println("The devicePrice is : " + device10.devicePrice);
        System.out.println("The isAvailable is : " + device10.isAvailable);
        System.out.println("The deviceType is : " + device10.deviceType);
        System.out.println("The rangeKm is : " + device10.rangeKm);
        System.out.println("The weight is : " + device10.weight);
        System.out.println("The isRechargeable is : " + device10.isRechargeable);
        System.out.println("The batteryType is : " + device10.batteryType);
        System.out.println("The warrantyYears is : " + device10.warrantyYears);
        System.out.println("The frequencyMHz is : " + device10.frequencyMHz);
        System.out.println("The hasLCD is : " + device10.hasLCD);
        System.out.println("The color is : " + device10.color);
        System.out.println("The stockQuantity is : " + device10.stockQuantity);
        System.out.println("The channelCount is : " + device10.channelCount);
        System.out.println("The isEcoFriendly is : " + device10.isEcoFriendly);
        System.out.println("The antennaType is : " + device10.antennaType);
        System.out.println("The rating is : " + device10.rating);
        System.out.println("The batteryCapacity is : " + device10.batteryCapacity);
        System.out.println("The isCertified is : " + device10.isCertified);
        System.out.println("The countryOfOrigin is : " + device10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device10.manufacturingYear);
        System.out.println("The speakerPower is : " + device10.speakerPower);
        System.out.println("The supportsVOX is : " + device10.supportsVOX);
        System.out.println("The certificationType is : " + device10.certificationType);


        WalkieTalkie device11 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device11.deviceBrand);
        System.out.println("The deviceId is : " + device11.deviceId);
        System.out.println("The devicePrice is : " + device11.devicePrice);
        System.out.println("The isAvailable is : " + device11.isAvailable);
        System.out.println("The deviceType is : " + device11.deviceType);
        System.out.println("The rangeKm is : " + device11.rangeKm);
        System.out.println("The weight is : " + device11.weight);
        System.out.println("The isRechargeable is : " + device11.isRechargeable);
        System.out.println("The batteryType is : " + device11.batteryType);
        System.out.println("The warrantyYears is : " + device11.warrantyYears);
        System.out.println("The frequencyMHz is : " + device11.frequencyMHz);
        System.out.println("The hasLCD is : " + device11.hasLCD);
        System.out.println("The color is : " + device11.color);
        System.out.println("The stockQuantity is : " + device11.stockQuantity);
        System.out.println("The channelCount is : " + device11.channelCount);
        System.out.println("The isEcoFriendly is : " + device11.isEcoFriendly);
        System.out.println("The antennaType is : " + device11.antennaType);
        System.out.println("The rating is : " + device11.rating);
        System.out.println("The batteryCapacity is : " + device11.batteryCapacity);
        System.out.println("The isCertified is : " + device11.isCertified);
        System.out.println("The countryOfOrigin is : " + device11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device11.manufacturingYear);
        System.out.println("The speakerPower is : " + device11.speakerPower);
        System.out.println("The supportsVOX is : " + device11.supportsVOX);
        System.out.println("The certificationType is : " + device11.certificationType);

        device11.deviceBrand = "Motorola";
        device11.deviceId = 11;
        device11.devicePrice = 1199.99;
        device11.isAvailable = true;
        device11.deviceType = "Two Way Radio";
        device11.rangeKm = 10.0;
        device11.weight = 0.35;
        device11.isRechargeable = true;
        device11.batteryType = "Li-Ion";
        device11.warrantyYears = 2;
        device11.frequencyMHz = 462.5;
        device11.hasLCD = true;
        device11.color = "Black";
        device11.stockQuantity = 30;
        device11.channelCount = 22;
        device11.isEcoFriendly = true;
        device11.antennaType = "External";
        device11.rating = 4;
        device11.batteryCapacity = 1500.0;
        device11.isCertified = true;
        device11.countryOfOrigin = "USA";
        device11.manufacturingYear = 2025;
        device11.speakerPower = 1.5;
        device11.supportsVOX = true;
        device11.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device11.deviceBrand);
        System.out.println("The deviceId is : " + device11.deviceId);
        System.out.println("The devicePrice is : " + device11.devicePrice);
        System.out.println("The isAvailable is : " + device11.isAvailable);
        System.out.println("The deviceType is : " + device11.deviceType);
        System.out.println("The rangeKm is : " + device11.rangeKm);
        System.out.println("The weight is : " + device11.weight);
        System.out.println("The isRechargeable is : " + device11.isRechargeable);
        System.out.println("The batteryType is : " + device11.batteryType);
        System.out.println("The warrantyYears is : " + device11.warrantyYears);
        System.out.println("The frequencyMHz is : " + device11.frequencyMHz);
        System.out.println("The hasLCD is : " + device11.hasLCD);
        System.out.println("The color is : " + device11.color);
        System.out.println("The stockQuantity is : " + device11.stockQuantity);
        System.out.println("The channelCount is : " + device11.channelCount);
        System.out.println("The isEcoFriendly is : " + device11.isEcoFriendly);
        System.out.println("The antennaType is : " + device11.antennaType);
        System.out.println("The rating is : " + device11.rating);
        System.out.println("The batteryCapacity is : " + device11.batteryCapacity);
        System.out.println("The isCertified is : " + device11.isCertified);
        System.out.println("The countryOfOrigin is : " + device11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device11.manufacturingYear);
        System.out.println("The speakerPower is : " + device11.speakerPower);
        System.out.println("The supportsVOX is : " + device11.supportsVOX);
        System.out.println("The certificationType is : " + device11.certificationType);


        WalkieTalkie device12 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device12.deviceBrand);
        System.out.println("The deviceId is : " + device12.deviceId);
        System.out.println("The devicePrice is : " + device12.devicePrice);
        System.out.println("The isAvailable is : " + device12.isAvailable);
        System.out.println("The deviceType is : " + device12.deviceType);
        System.out.println("The rangeKm is : " + device12.rangeKm);
        System.out.println("The weight is : " + device12.weight);
        System.out.println("The isRechargeable is : " + device12.isRechargeable);
        System.out.println("The batteryType is : " + device12.batteryType);
        System.out.println("The warrantyYears is : " + device12.warrantyYears);
        System.out.println("The frequencyMHz is : " + device12.frequencyMHz);
        System.out.println("The hasLCD is : " + device12.hasLCD);
        System.out.println("The color is : " + device12.color);
        System.out.println("The stockQuantity is : " + device12.stockQuantity);
        System.out.println("The channelCount is : " + device12.channelCount);
        System.out.println("The isEcoFriendly is : " + device12.isEcoFriendly);
        System.out.println("The antennaType is : " + device12.antennaType);
        System.out.println("The rating is : " + device12.rating);
        System.out.println("The batteryCapacity is : " + device12.batteryCapacity);
        System.out.println("The isCertified is : " + device12.isCertified);
        System.out.println("The countryOfOrigin is : " + device12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device12.manufacturingYear);
        System.out.println("The speakerPower is : " + device12.speakerPower);
        System.out.println("The supportsVOX is : " + device12.supportsVOX);
        System.out.println("The certificationType is : " + device12.certificationType);

        device12.deviceBrand = "Motorola";
        device12.deviceId = 12;
        device12.devicePrice = 1299.99;
        device12.isAvailable = true;
        device12.deviceType = "Two Way Radio";
        device12.rangeKm = 10.0;
        device12.weight = 0.35;
        device12.isRechargeable = true;
        device12.batteryType = "Li-Ion";
        device12.warrantyYears = 2;
        device12.frequencyMHz = 462.5;
        device12.hasLCD = true;
        device12.color = "Black";
        device12.stockQuantity = 30;
        device12.channelCount = 22;
        device12.isEcoFriendly = true;
        device12.antennaType = "External";
        device12.rating = 4;
        device12.batteryCapacity = 1500.0;
        device12.isCertified = true;
        device12.countryOfOrigin = "USA";
        device12.manufacturingYear = 2025;
        device12.speakerPower = 1.5;
        device12.supportsVOX = true;
        device12.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device12.deviceBrand);
        System.out.println("The deviceId is : " + device12.deviceId);
        System.out.println("The devicePrice is : " + device12.devicePrice);
        System.out.println("The isAvailable is : " + device12.isAvailable);
        System.out.println("The deviceType is : " + device12.deviceType);
        System.out.println("The rangeKm is : " + device12.rangeKm);
        System.out.println("The weight is : " + device12.weight);
        System.out.println("The isRechargeable is : " + device12.isRechargeable);
        System.out.println("The batteryType is : " + device12.batteryType);
        System.out.println("The warrantyYears is : " + device12.warrantyYears);
        System.out.println("The frequencyMHz is : " + device12.frequencyMHz);
        System.out.println("The hasLCD is : " + device12.hasLCD);
        System.out.println("The color is : " + device12.color);
        System.out.println("The stockQuantity is : " + device12.stockQuantity);
        System.out.println("The channelCount is : " + device12.channelCount);
        System.out.println("The isEcoFriendly is : " + device12.isEcoFriendly);
        System.out.println("The antennaType is : " + device12.antennaType);
        System.out.println("The rating is : " + device12.rating);
        System.out.println("The batteryCapacity is : " + device12.batteryCapacity);
        System.out.println("The isCertified is : " + device12.isCertified);
        System.out.println("The countryOfOrigin is : " + device12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device12.manufacturingYear);
        System.out.println("The speakerPower is : " + device12.speakerPower);
        System.out.println("The supportsVOX is : " + device12.supportsVOX);
        System.out.println("The certificationType is : " + device12.certificationType);


        WalkieTalkie device13 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device13.deviceBrand);
        System.out.println("The deviceId is : " + device13.deviceId);
        System.out.println("The devicePrice is : " + device13.devicePrice);
        System.out.println("The isAvailable is : " + device13.isAvailable);
        System.out.println("The deviceType is : " + device13.deviceType);
        System.out.println("The rangeKm is : " + device13.rangeKm);
        System.out.println("The weight is : " + device13.weight);
        System.out.println("The isRechargeable is : " + device13.isRechargeable);
        System.out.println("The batteryType is : " + device13.batteryType);
        System.out.println("The warrantyYears is : " + device13.warrantyYears);
        System.out.println("The frequencyMHz is : " + device13.frequencyMHz);
        System.out.println("The hasLCD is : " + device13.hasLCD);
        System.out.println("The color is : " + device13.color);
        System.out.println("The stockQuantity is : " + device13.stockQuantity);
        System.out.println("The channelCount is : " + device13.channelCount);
        System.out.println("The isEcoFriendly is : " + device13.isEcoFriendly);
        System.out.println("The antennaType is : " + device13.antennaType);
        System.out.println("The rating is : " + device13.rating);
        System.out.println("The batteryCapacity is : " + device13.batteryCapacity);
        System.out.println("The isCertified is : " + device13.isCertified);
        System.out.println("The countryOfOrigin is : " + device13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device13.manufacturingYear);
        System.out.println("The speakerPower is : " + device13.speakerPower);
        System.out.println("The supportsVOX is : " + device13.supportsVOX);
        System.out.println("The certificationType is : " + device13.certificationType);

        device13.deviceBrand = "Motorola";
        device13.deviceId = 13;
        device13.devicePrice = 1399.99;
        device13.isAvailable = true;
        device13.deviceType = "Two Way Radio";
        device13.rangeKm = 10.0;
        device13.weight = 0.35;
        device13.isRechargeable = true;
        device13.batteryType = "Li-Ion";
        device13.warrantyYears = 2;
        device13.frequencyMHz = 462.5;
        device13.hasLCD = true;
        device13.color = "Black";
        device13.stockQuantity = 30;
        device13.channelCount = 22;
        device13.isEcoFriendly = true;
        device13.antennaType = "External";
        device13.rating = 4;
        device13.batteryCapacity = 1500.0;
        device13.isCertified = true;
        device13.countryOfOrigin = "USA";
        device13.manufacturingYear = 2025;
        device13.speakerPower = 1.5;
        device13.supportsVOX = true;
        device13.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device13.deviceBrand);
        System.out.println("The deviceId is : " + device13.deviceId);
        System.out.println("The devicePrice is : " + device13.devicePrice);
        System.out.println("The isAvailable is : " + device13.isAvailable);
        System.out.println("The deviceType is : " + device13.deviceType);
        System.out.println("The rangeKm is : " + device13.rangeKm);
        System.out.println("The weight is : " + device13.weight);
        System.out.println("The isRechargeable is : " + device13.isRechargeable);
        System.out.println("The batteryType is : " + device13.batteryType);
        System.out.println("The warrantyYears is : " + device13.warrantyYears);
        System.out.println("The frequencyMHz is : " + device13.frequencyMHz);
        System.out.println("The hasLCD is : " + device13.hasLCD);
        System.out.println("The color is : " + device13.color);
        System.out.println("The stockQuantity is : " + device13.stockQuantity);
        System.out.println("The channelCount is : " + device13.channelCount);
        System.out.println("The isEcoFriendly is : " + device13.isEcoFriendly);
        System.out.println("The antennaType is : " + device13.antennaType);
        System.out.println("The rating is : " + device13.rating);
        System.out.println("The batteryCapacity is : " + device13.batteryCapacity);
        System.out.println("The isCertified is : " + device13.isCertified);
        System.out.println("The countryOfOrigin is : " + device13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device13.manufacturingYear);
        System.out.println("The speakerPower is : " + device13.speakerPower);
        System.out.println("The supportsVOX is : " + device13.supportsVOX);
        System.out.println("The certificationType is : " + device13.certificationType);


        WalkieTalkie device14 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device14.deviceBrand);
        System.out.println("The deviceId is : " + device14.deviceId);
        System.out.println("The devicePrice is : " + device14.devicePrice);
        System.out.println("The isAvailable is : " + device14.isAvailable);
        System.out.println("The deviceType is : " + device14.deviceType);
        System.out.println("The rangeKm is : " + device14.rangeKm);
        System.out.println("The weight is : " + device14.weight);
        System.out.println("The isRechargeable is : " + device14.isRechargeable);
        System.out.println("The batteryType is : " + device14.batteryType);
        System.out.println("The warrantyYears is : " + device14.warrantyYears);
        System.out.println("The frequencyMHz is : " + device14.frequencyMHz);
        System.out.println("The hasLCD is : " + device14.hasLCD);
        System.out.println("The color is : " + device14.color);
        System.out.println("The stockQuantity is : " + device14.stockQuantity);
        System.out.println("The channelCount is : " + device14.channelCount);
        System.out.println("The isEcoFriendly is : " + device14.isEcoFriendly);
        System.out.println("The antennaType is : " + device14.antennaType);
        System.out.println("The rating is : " + device14.rating);
        System.out.println("The batteryCapacity is : " + device14.batteryCapacity);
        System.out.println("The isCertified is : " + device14.isCertified);
        System.out.println("The countryOfOrigin is : " + device14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device14.manufacturingYear);
        System.out.println("The speakerPower is : " + device14.speakerPower);
        System.out.println("The supportsVOX is : " + device14.supportsVOX);
        System.out.println("The certificationType is : " + device14.certificationType);

        device14.deviceBrand = "Motorola";
        device14.deviceId = 14;
        device14.devicePrice = 1499.99;
        device14.isAvailable = true;
        device14.deviceType = "Two Way Radio";
        device14.rangeKm = 10.0;
        device14.weight = 0.35;
        device14.isRechargeable = true;
        device14.batteryType = "Li-Ion";
        device14.warrantyYears = 2;
        device14.frequencyMHz = 462.5;
        device14.hasLCD = true;
        device14.color = "Black";
        device14.stockQuantity = 30;
        device14.channelCount = 22;
        device14.isEcoFriendly = true;
        device14.antennaType = "External";
        device14.rating = 4;
        device14.batteryCapacity = 1500.0;
        device14.isCertified = true;
        device14.countryOfOrigin = "USA";
        device14.manufacturingYear = 2025;
        device14.speakerPower = 1.5;
        device14.supportsVOX = true;
        device14.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device14.deviceBrand);
        System.out.println("The deviceId is : " + device14.deviceId);
        System.out.println("The devicePrice is : " + device14.devicePrice);
        System.out.println("The isAvailable is : " + device14.isAvailable);
        System.out.println("The deviceType is : " + device14.deviceType);
        System.out.println("The rangeKm is : " + device14.rangeKm);
        System.out.println("The weight is : " + device14.weight);
        System.out.println("The isRechargeable is : " + device14.isRechargeable);
        System.out.println("The batteryType is : " + device14.batteryType);
        System.out.println("The warrantyYears is : " + device14.warrantyYears);
        System.out.println("The frequencyMHz is : " + device14.frequencyMHz);
        System.out.println("The hasLCD is : " + device14.hasLCD);
        System.out.println("The color is : " + device14.color);
        System.out.println("The stockQuantity is : " + device14.stockQuantity);
        System.out.println("The channelCount is : " + device14.channelCount);
        System.out.println("The isEcoFriendly is : " + device14.isEcoFriendly);
        System.out.println("The antennaType is : " + device14.antennaType);
        System.out.println("The rating is : " + device14.rating);
        System.out.println("The batteryCapacity is : " + device14.batteryCapacity);
        System.out.println("The isCertified is : " + device14.isCertified);
        System.out.println("The countryOfOrigin is : " + device14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device14.manufacturingYear);
        System.out.println("The speakerPower is : " + device14.speakerPower);
        System.out.println("The supportsVOX is : " + device14.supportsVOX);
        System.out.println("The certificationType is : " + device14.certificationType);


        WalkieTalkie device15 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device15.deviceBrand);
        System.out.println("The deviceId is : " + device15.deviceId);
        System.out.println("The devicePrice is : " + device15.devicePrice);
        System.out.println("The isAvailable is : " + device15.isAvailable);
        System.out.println("The deviceType is : " + device15.deviceType);
        System.out.println("The rangeKm is : " + device15.rangeKm);
        System.out.println("The weight is : " + device15.weight);
        System.out.println("The isRechargeable is : " + device15.isRechargeable);
        System.out.println("The batteryType is : " + device15.batteryType);
        System.out.println("The warrantyYears is : " + device15.warrantyYears);
        System.out.println("The frequencyMHz is : " + device15.frequencyMHz);
        System.out.println("The hasLCD is : " + device15.hasLCD);
        System.out.println("The color is : " + device15.color);
        System.out.println("The stockQuantity is : " + device15.stockQuantity);
        System.out.println("The channelCount is : " + device15.channelCount);
        System.out.println("The isEcoFriendly is : " + device15.isEcoFriendly);
        System.out.println("The antennaType is : " + device15.antennaType);
        System.out.println("The rating is : " + device15.rating);
        System.out.println("The batteryCapacity is : " + device15.batteryCapacity);
        System.out.println("The isCertified is : " + device15.isCertified);
        System.out.println("The countryOfOrigin is : " + device15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device15.manufacturingYear);
        System.out.println("The speakerPower is : " + device15.speakerPower);
        System.out.println("The supportsVOX is : " + device15.supportsVOX);
        System.out.println("The certificationType is : " + device15.certificationType);

        device15.deviceBrand = "Motorola";
        device15.deviceId = 15;
        device15.devicePrice = 1599.99;
        device15.isAvailable = true;
        device15.deviceType = "Two Way Radio";
        device15.rangeKm = 10.0;
        device15.weight = 0.35;
        device15.isRechargeable = true;
        device15.batteryType = "Li-Ion";
        device15.warrantyYears = 2;
        device15.frequencyMHz = 462.5;
        device15.hasLCD = true;
        device15.color = "Black";
        device15.stockQuantity = 30;
        device15.channelCount = 22;
        device15.isEcoFriendly = true;
        device15.antennaType = "External";
        device15.rating = 4;
        device15.batteryCapacity = 1500.0;
        device15.isCertified = true;
        device15.countryOfOrigin = "USA";
        device15.manufacturingYear = 2025;
        device15.speakerPower = 1.5;
        device15.supportsVOX = true;
        device15.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device15.deviceBrand);
        System.out.println("The deviceId is : " + device15.deviceId);
        System.out.println("The devicePrice is : " + device15.devicePrice);
        System.out.println("The isAvailable is : " + device15.isAvailable);
        System.out.println("The deviceType is : " + device15.deviceType);
        System.out.println("The rangeKm is : " + device15.rangeKm);
        System.out.println("The weight is : " + device15.weight);
        System.out.println("The isRechargeable is : " + device15.isRechargeable);
        System.out.println("The batteryType is : " + device15.batteryType);
        System.out.println("The warrantyYears is : " + device15.warrantyYears);
        System.out.println("The frequencyMHz is : " + device15.frequencyMHz);
        System.out.println("The hasLCD is : " + device15.hasLCD);
        System.out.println("The color is : " + device15.color);
        System.out.println("The stockQuantity is : " + device15.stockQuantity);
        System.out.println("The channelCount is : " + device15.channelCount);
        System.out.println("The isEcoFriendly is : " + device15.isEcoFriendly);
        System.out.println("The antennaType is : " + device15.antennaType);
        System.out.println("The rating is : " + device15.rating);
        System.out.println("The batteryCapacity is : " + device15.batteryCapacity);
        System.out.println("The isCertified is : " + device15.isCertified);
        System.out.println("The countryOfOrigin is : " + device15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device15.manufacturingYear);
        System.out.println("The speakerPower is : " + device15.speakerPower);
        System.out.println("The supportsVOX is : " + device15.supportsVOX);
        System.out.println("The certificationType is : " + device15.certificationType);


        WalkieTalkie device16 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device16.deviceBrand);
        System.out.println("The deviceId is : " + device16.deviceId);
        System.out.println("The devicePrice is : " + device16.devicePrice);
        System.out.println("The isAvailable is : " + device16.isAvailable);
        System.out.println("The deviceType is : " + device16.deviceType);
        System.out.println("The rangeKm is : " + device16.rangeKm);
        System.out.println("The weight is : " + device16.weight);
        System.out.println("The isRechargeable is : " + device16.isRechargeable);
        System.out.println("The batteryType is : " + device16.batteryType);
        System.out.println("The warrantyYears is : " + device16.warrantyYears);
        System.out.println("The frequencyMHz is : " + device16.frequencyMHz);
        System.out.println("The hasLCD is : " + device16.hasLCD);
        System.out.println("The color is : " + device16.color);
        System.out.println("The stockQuantity is : " + device16.stockQuantity);
        System.out.println("The channelCount is : " + device16.channelCount);
        System.out.println("The isEcoFriendly is : " + device16.isEcoFriendly);
        System.out.println("The antennaType is : " + device16.antennaType);
        System.out.println("The rating is : " + device16.rating);
        System.out.println("The batteryCapacity is : " + device16.batteryCapacity);
        System.out.println("The isCertified is : " + device16.isCertified);
        System.out.println("The countryOfOrigin is : " + device16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device16.manufacturingYear);
        System.out.println("The speakerPower is : " + device16.speakerPower);
        System.out.println("The supportsVOX is : " + device16.supportsVOX);
        System.out.println("The certificationType is : " + device16.certificationType);

        device16.deviceBrand = "Motorola";
        device16.deviceId = 16;
        device16.devicePrice = 1699.99;
        device16.isAvailable = true;
        device16.deviceType = "Two Way Radio";
        device16.rangeKm = 10.0;
        device16.weight = 0.35;
        device16.isRechargeable = true;
        device16.batteryType = "Li-Ion";
        device16.warrantyYears = 2;
        device16.frequencyMHz = 462.5;
        device16.hasLCD = true;
        device16.color = "Black";
        device16.stockQuantity = 30;
        device16.channelCount = 22;
        device16.isEcoFriendly = true;
        device16.antennaType = "External";
        device16.rating = 4;
        device16.batteryCapacity = 1500.0;
        device16.isCertified = true;
        device16.countryOfOrigin = "USA";
        device16.manufacturingYear = 2025;
        device16.speakerPower = 1.5;
        device16.supportsVOX = true;
        device16.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device16.deviceBrand);
        System.out.println("The deviceId is : " + device16.deviceId);
        System.out.println("The devicePrice is : " + device16.devicePrice);
        System.out.println("The isAvailable is : " + device16.isAvailable);
        System.out.println("The deviceType is : " + device16.deviceType);
        System.out.println("The rangeKm is : " + device16.rangeKm);
        System.out.println("The weight is : " + device16.weight);
        System.out.println("The isRechargeable is : " + device16.isRechargeable);
        System.out.println("The batteryType is : " + device16.batteryType);
        System.out.println("The warrantyYears is : " + device16.warrantyYears);
        System.out.println("The frequencyMHz is : " + device16.frequencyMHz);
        System.out.println("The hasLCD is : " + device16.hasLCD);
        System.out.println("The color is : " + device16.color);
        System.out.println("The stockQuantity is : " + device16.stockQuantity);
        System.out.println("The channelCount is : " + device16.channelCount);
        System.out.println("The isEcoFriendly is : " + device16.isEcoFriendly);
        System.out.println("The antennaType is : " + device16.antennaType);
        System.out.println("The rating is : " + device16.rating);
        System.out.println("The batteryCapacity is : " + device16.batteryCapacity);
        System.out.println("The isCertified is : " + device16.isCertified);
        System.out.println("The countryOfOrigin is : " + device16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device16.manufacturingYear);
        System.out.println("The speakerPower is : " + device16.speakerPower);
        System.out.println("The supportsVOX is : " + device16.supportsVOX);
        System.out.println("The certificationType is : " + device16.certificationType);


        WalkieTalkie device17 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device17.deviceBrand);
        System.out.println("The deviceId is : " + device17.deviceId);
        System.out.println("The devicePrice is : " + device17.devicePrice);
        System.out.println("The isAvailable is : " + device17.isAvailable);
        System.out.println("The deviceType is : " + device17.deviceType);
        System.out.println("The rangeKm is : " + device17.rangeKm);
        System.out.println("The weight is : " + device17.weight);
        System.out.println("The isRechargeable is : " + device17.isRechargeable);
        System.out.println("The batteryType is : " + device17.batteryType);
        System.out.println("The warrantyYears is : " + device17.warrantyYears);
        System.out.println("The frequencyMHz is : " + device17.frequencyMHz);
        System.out.println("The hasLCD is : " + device17.hasLCD);
        System.out.println("The color is : " + device17.color);
        System.out.println("The stockQuantity is : " + device17.stockQuantity);
        System.out.println("The channelCount is : " + device17.channelCount);
        System.out.println("The isEcoFriendly is : " + device17.isEcoFriendly);
        System.out.println("The antennaType is : " + device17.antennaType);
        System.out.println("The rating is : " + device17.rating);
        System.out.println("The batteryCapacity is : " + device17.batteryCapacity);
        System.out.println("The isCertified is : " + device17.isCertified);
        System.out.println("The countryOfOrigin is : " + device17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device17.manufacturingYear);
        System.out.println("The speakerPower is : " + device17.speakerPower);
        System.out.println("The supportsVOX is : " + device17.supportsVOX);
        System.out.println("The certificationType is : " + device17.certificationType);

        device17.deviceBrand = "Motorola";
        device17.deviceId = 17;
        device17.devicePrice = 1799.99;
        device17.isAvailable = true;
        device17.deviceType = "Two Way Radio";
        device17.rangeKm = 10.0;
        device17.weight = 0.35;
        device17.isRechargeable = true;
        device17.batteryType = "Li-Ion";
        device17.warrantyYears = 2;
        device17.frequencyMHz = 462.5;
        device17.hasLCD = true;
        device17.color = "Black";
        device17.stockQuantity = 30;
        device17.channelCount = 22;
        device17.isEcoFriendly = true;
        device17.antennaType = "External";
        device17.rating = 4;
        device17.batteryCapacity = 1500.0;
        device17.isCertified = true;
        device17.countryOfOrigin = "USA";
        device17.manufacturingYear = 2025;
        device17.speakerPower = 1.5;
        device17.supportsVOX = true;
        device17.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device17.deviceBrand);
        System.out.println("The deviceId is : " + device17.deviceId);
        System.out.println("The devicePrice is : " + device17.devicePrice);
        System.out.println("The isAvailable is : " + device17.isAvailable);
        System.out.println("The deviceType is : " + device17.deviceType);
        System.out.println("The rangeKm is : " + device17.rangeKm);
        System.out.println("The weight is : " + device17.weight);
        System.out.println("The isRechargeable is : " + device17.isRechargeable);
        System.out.println("The batteryType is : " + device17.batteryType);
        System.out.println("The warrantyYears is : " + device17.warrantyYears);
        System.out.println("The frequencyMHz is : " + device17.frequencyMHz);
        System.out.println("The hasLCD is : " + device17.hasLCD);
        System.out.println("The color is : " + device17.color);
        System.out.println("The stockQuantity is : " + device17.stockQuantity);
        System.out.println("The channelCount is : " + device17.channelCount);
        System.out.println("The isEcoFriendly is : " + device17.isEcoFriendly);
        System.out.println("The antennaType is : " + device17.antennaType);
        System.out.println("The rating is : " + device17.rating);
        System.out.println("The batteryCapacity is : " + device17.batteryCapacity);
        System.out.println("The isCertified is : " + device17.isCertified);
        System.out.println("The countryOfOrigin is : " + device17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device17.manufacturingYear);
        System.out.println("The speakerPower is : " + device17.speakerPower);
        System.out.println("The supportsVOX is : " + device17.supportsVOX);
        System.out.println("The certificationType is : " + device17.certificationType);


        WalkieTalkie device18 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device18.deviceBrand);
        System.out.println("The deviceId is : " + device18.deviceId);
        System.out.println("The devicePrice is : " + device18.devicePrice);
        System.out.println("The isAvailable is : " + device18.isAvailable);
        System.out.println("The deviceType is : " + device18.deviceType);
        System.out.println("The rangeKm is : " + device18.rangeKm);
        System.out.println("The weight is : " + device18.weight);
        System.out.println("The isRechargeable is : " + device18.isRechargeable);
        System.out.println("The batteryType is : " + device18.batteryType);
        System.out.println("The warrantyYears is : " + device18.warrantyYears);
        System.out.println("The frequencyMHz is : " + device18.frequencyMHz);
        System.out.println("The hasLCD is : " + device18.hasLCD);
        System.out.println("The color is : " + device18.color);
        System.out.println("The stockQuantity is : " + device18.stockQuantity);
        System.out.println("The channelCount is : " + device18.channelCount);
        System.out.println("The isEcoFriendly is : " + device18.isEcoFriendly);
        System.out.println("The antennaType is : " + device18.antennaType);
        System.out.println("The rating is : " + device18.rating);
        System.out.println("The batteryCapacity is : " + device18.batteryCapacity);
        System.out.println("The isCertified is : " + device18.isCertified);
        System.out.println("The countryOfOrigin is : " + device18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device18.manufacturingYear);
        System.out.println("The speakerPower is : " + device18.speakerPower);
        System.out.println("The supportsVOX is : " + device18.supportsVOX);
        System.out.println("The certificationType is : " + device18.certificationType);

        device18.deviceBrand = "Motorola";
        device18.deviceId = 18;
        device18.devicePrice = 1899.99;
        device18.isAvailable = true;
        device18.deviceType = "Two Way Radio";
        device18.rangeKm = 10.0;
        device18.weight = 0.35;
        device18.isRechargeable = true;
        device18.batteryType = "Li-Ion";
        device18.warrantyYears = 2;
        device18.frequencyMHz = 462.5;
        device18.hasLCD = true;
        device18.color = "Black";
        device18.stockQuantity = 30;
        device18.channelCount = 22;
        device18.isEcoFriendly = true;
        device18.antennaType = "External";
        device18.rating = 4;
        device18.batteryCapacity = 1500.0;
        device18.isCertified = true;
        device18.countryOfOrigin = "USA";
        device18.manufacturingYear = 2025;
        device18.speakerPower = 1.5;
        device18.supportsVOX = true;
        device18.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device18.deviceBrand);
        System.out.println("The deviceId is : " + device18.deviceId);
        System.out.println("The devicePrice is : " + device18.devicePrice);
        System.out.println("The isAvailable is : " + device18.isAvailable);
        System.out.println("The deviceType is : " + device18.deviceType);
        System.out.println("The rangeKm is : " + device18.rangeKm);
        System.out.println("The weight is : " + device18.weight);
        System.out.println("The isRechargeable is : " + device18.isRechargeable);
        System.out.println("The batteryType is : " + device18.batteryType);
        System.out.println("The warrantyYears is : " + device18.warrantyYears);
        System.out.println("The frequencyMHz is : " + device18.frequencyMHz);
        System.out.println("The hasLCD is : " + device18.hasLCD);
        System.out.println("The color is : " + device18.color);
        System.out.println("The stockQuantity is : " + device18.stockQuantity);
        System.out.println("The channelCount is : " + device18.channelCount);
        System.out.println("The isEcoFriendly is : " + device18.isEcoFriendly);
        System.out.println("The antennaType is : " + device18.antennaType);
        System.out.println("The rating is : " + device18.rating);
        System.out.println("The batteryCapacity is : " + device18.batteryCapacity);
        System.out.println("The isCertified is : " + device18.isCertified);
        System.out.println("The countryOfOrigin is : " + device18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device18.manufacturingYear);
        System.out.println("The speakerPower is : " + device18.speakerPower);
        System.out.println("The supportsVOX is : " + device18.supportsVOX);
        System.out.println("The certificationType is : " + device18.certificationType);


        WalkieTalkie device19 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device19.deviceBrand);
        System.out.println("The deviceId is : " + device19.deviceId);
        System.out.println("The devicePrice is : " + device19.devicePrice);
        System.out.println("The isAvailable is : " + device19.isAvailable);
        System.out.println("The deviceType is : " + device19.deviceType);
        System.out.println("The rangeKm is : " + device19.rangeKm);
        System.out.println("The weight is : " + device19.weight);
        System.out.println("The isRechargeable is : " + device19.isRechargeable);
        System.out.println("The batteryType is : " + device19.batteryType);
        System.out.println("The warrantyYears is : " + device19.warrantyYears);
        System.out.println("The frequencyMHz is : " + device19.frequencyMHz);
        System.out.println("The hasLCD is : " + device19.hasLCD);
        System.out.println("The color is : " + device19.color);
        System.out.println("The stockQuantity is : " + device19.stockQuantity);
        System.out.println("The channelCount is : " + device19.channelCount);
        System.out.println("The isEcoFriendly is : " + device19.isEcoFriendly);
        System.out.println("The antennaType is : " + device19.antennaType);
        System.out.println("The rating is : " + device19.rating);
        System.out.println("The batteryCapacity is : " + device19.batteryCapacity);
        System.out.println("The isCertified is : " + device19.isCertified);
        System.out.println("The countryOfOrigin is : " + device19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device19.manufacturingYear);
        System.out.println("The speakerPower is : " + device19.speakerPower);
        System.out.println("The supportsVOX is : " + device19.supportsVOX);
        System.out.println("The certificationType is : " + device19.certificationType);

        device19.deviceBrand = "Motorola";
        device19.deviceId = 19;
        device19.devicePrice = 1999.99;
        device19.isAvailable = true;
        device19.deviceType = "Two Way Radio";
        device19.rangeKm = 10.0;
        device19.weight = 0.35;
        device19.isRechargeable = true;
        device19.batteryType = "Li-Ion";
        device19.warrantyYears = 2;
        device19.frequencyMHz = 462.5;
        device19.hasLCD = true;
        device19.color = "Black";
        device19.stockQuantity = 30;
        device19.channelCount = 22;
        device19.isEcoFriendly = true;
        device19.antennaType = "External";
        device19.rating = 4;
        device19.batteryCapacity = 1500.0;
        device19.isCertified = true;
        device19.countryOfOrigin = "USA";
        device19.manufacturingYear = 2025;
        device19.speakerPower = 1.5;
        device19.supportsVOX = true;
        device19.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device19.deviceBrand);
        System.out.println("The deviceId is : " + device19.deviceId);
        System.out.println("The devicePrice is : " + device19.devicePrice);
        System.out.println("The isAvailable is : " + device19.isAvailable);
        System.out.println("The deviceType is : " + device19.deviceType);
        System.out.println("The rangeKm is : " + device19.rangeKm);
        System.out.println("The weight is : " + device19.weight);
        System.out.println("The isRechargeable is : " + device19.isRechargeable);
        System.out.println("The batteryType is : " + device19.batteryType);
        System.out.println("The warrantyYears is : " + device19.warrantyYears);
        System.out.println("The frequencyMHz is : " + device19.frequencyMHz);
        System.out.println("The hasLCD is : " + device19.hasLCD);
        System.out.println("The color is : " + device19.color);
        System.out.println("The stockQuantity is : " + device19.stockQuantity);
        System.out.println("The channelCount is : " + device19.channelCount);
        System.out.println("The isEcoFriendly is : " + device19.isEcoFriendly);
        System.out.println("The antennaType is : " + device19.antennaType);
        System.out.println("The rating is : " + device19.rating);
        System.out.println("The batteryCapacity is : " + device19.batteryCapacity);
        System.out.println("The isCertified is : " + device19.isCertified);
        System.out.println("The countryOfOrigin is : " + device19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device19.manufacturingYear);
        System.out.println("The speakerPower is : " + device19.speakerPower);
        System.out.println("The supportsVOX is : " + device19.supportsVOX);
        System.out.println("The certificationType is : " + device19.certificationType);


        WalkieTalkie device20 = new WalkieTalkie();

        System.out.println("Before initialization");

        System.out.println("The deviceBrand is : " + device20.deviceBrand);
        System.out.println("The deviceId is : " + device20.deviceId);
        System.out.println("The devicePrice is : " + device20.devicePrice);
        System.out.println("The isAvailable is : " + device20.isAvailable);
        System.out.println("The deviceType is : " + device20.deviceType);
        System.out.println("The rangeKm is : " + device20.rangeKm);
        System.out.println("The weight is : " + device20.weight);
        System.out.println("The isRechargeable is : " + device20.isRechargeable);
        System.out.println("The batteryType is : " + device20.batteryType);
        System.out.println("The warrantyYears is : " + device20.warrantyYears);
        System.out.println("The frequencyMHz is : " + device20.frequencyMHz);
        System.out.println("The hasLCD is : " + device20.hasLCD);
        System.out.println("The color is : " + device20.color);
        System.out.println("The stockQuantity is : " + device20.stockQuantity);
        System.out.println("The channelCount is : " + device20.channelCount);
        System.out.println("The isEcoFriendly is : " + device20.isEcoFriendly);
        System.out.println("The antennaType is : " + device20.antennaType);
        System.out.println("The rating is : " + device20.rating);
        System.out.println("The batteryCapacity is : " + device20.batteryCapacity);
        System.out.println("The isCertified is : " + device20.isCertified);
        System.out.println("The countryOfOrigin is : " + device20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device20.manufacturingYear);
        System.out.println("The speakerPower is : " + device20.speakerPower);
        System.out.println("The supportsVOX is : " + device20.supportsVOX);
        System.out.println("The certificationType is : " + device20.certificationType);

        device20.deviceBrand = "Motorola";
        device20.deviceId = 20;
        device20.devicePrice = 2099.99;
        device20.isAvailable = true;
        device20.deviceType = "Two Way Radio";
        device20.rangeKm = 10.0;
        device20.weight = 0.35;
        device20.isRechargeable = true;
        device20.batteryType = "Li-Ion";
        device20.warrantyYears = 2;
        device20.frequencyMHz = 462.5;
        device20.hasLCD = true;
        device20.color = "Black";
        device20.stockQuantity = 30;
        device20.channelCount = 22;
        device20.isEcoFriendly = true;
        device20.antennaType = "External";
        device20.rating = 4;
        device20.batteryCapacity = 1500.0;
        device20.isCertified = true;
        device20.countryOfOrigin = "USA";
        device20.manufacturingYear = 2025;
        device20.speakerPower = 1.5;
        device20.supportsVOX = true;
        device20.certificationType = "FCC";

        System.out.println("After initialization");

        System.out.println("The deviceBrand is : " + device20.deviceBrand);
        System.out.println("The deviceId is : " + device20.deviceId);
        System.out.println("The devicePrice is : " + device20.devicePrice);
        System.out.println("The isAvailable is : " + device20.isAvailable);
        System.out.println("The deviceType is : " + device20.deviceType);
        System.out.println("The rangeKm is : " + device20.rangeKm);
        System.out.println("The weight is : " + device20.weight);
        System.out.println("The isRechargeable is : " + device20.isRechargeable);
        System.out.println("The batteryType is : " + device20.batteryType);
        System.out.println("The warrantyYears is : " + device20.warrantyYears);
        System.out.println("The frequencyMHz is : " + device20.frequencyMHz);
        System.out.println("The hasLCD is : " + device20.hasLCD);
        System.out.println("The color is : " + device20.color);
        System.out.println("The stockQuantity is : " + device20.stockQuantity);
        System.out.println("The channelCount is : " + device20.channelCount);
        System.out.println("The isEcoFriendly is : " + device20.isEcoFriendly);
        System.out.println("The antennaType is : " + device20.antennaType);
        System.out.println("The rating is : " + device20.rating);
        System.out.println("The batteryCapacity is : " + device20.batteryCapacity);
        System.out.println("The isCertified is : " + device20.isCertified);
        System.out.println("The countryOfOrigin is : " + device20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + device20.manufacturingYear);
        System.out.println("The speakerPower is : " + device20.speakerPower);
        System.out.println("The supportsVOX is : " + device20.supportsVOX);
        System.out.println("The certificationType is : " + device20.certificationType);


    }
}
